using EarthCountriesInfo.CountryInformation;

namespace EarthCountriesInfo
{
	public static class Countries
	{
		public static Dictionary<CountryIsoCode, CountryProperties> CountryPropertiesDictionary = new()
		{
			{
					CountryIsoCode.CA,
					CA.CountryProperties
			},
			{
					CountryIsoCode.US,
					US.CountryProperties
			},
			{
					CountryIsoCode.BS,
					BS.CountryProperties
			},
			{
					CountryIsoCode.BB,
					BB.CountryProperties
			},
			{
					CountryIsoCode.AI,
					AI.CountryProperties
			},
			{
					CountryIsoCode.AG,
					AG.CountryProperties
			},
			{
					CountryIsoCode.VG,
					VG.CountryProperties
			},
			{
					CountryIsoCode.VI,
					VI.CountryProperties
			},
			{
					CountryIsoCode.KY,
					KY.CountryProperties
			},
			{
					CountryIsoCode.BM,
					BM.CountryProperties
			},
			{
					CountryIsoCode.GD,
					GD.CountryProperties
			},
			{
					CountryIsoCode.TC,
					TC.CountryProperties
			},
			{
					CountryIsoCode.MS,
					MS.CountryProperties
			},
			{
					CountryIsoCode.GU,
					GU.CountryProperties
			},
			{
					CountryIsoCode.LC,
					LC.CountryProperties
			},
			{
					CountryIsoCode.DM,
					DM.CountryProperties
			},
			{
					CountryIsoCode.VC,
					VC.CountryProperties
			},
			{
					CountryIsoCode.PR,
					PR.CountryProperties
			},
			{
					CountryIsoCode.DO,
					DO.CountryProperties
			},
			{
					CountryIsoCode.TT,
					TT.CountryProperties
			},
			{
					CountryIsoCode.KN,
					KN.CountryProperties
			},
			{
					CountryIsoCode.JM,
					JM.CountryProperties
			},
			{
					CountryIsoCode.KZ,
					KZ.CountryProperties
			},
			{
					CountryIsoCode.RU,
					RU.CountryProperties
			},
			{
					CountryIsoCode.EG,
					EG.CountryProperties
			},
			{
					CountryIsoCode.ZA,
					ZA.CountryProperties
			},
			{
					CountryIsoCode.GR,
					GR.CountryProperties
			},
			{
					CountryIsoCode.NL,
					NL.CountryProperties
			},
			{
					CountryIsoCode.BE,
					BE.CountryProperties
			},
			{
					CountryIsoCode.FR,
					FR.CountryProperties
			},
			{
					CountryIsoCode.ES,
					ES.CountryProperties
			},
			{
					CountryIsoCode.HU,
					HU.CountryProperties
			},
			{
					CountryIsoCode.IT,
					IT.CountryProperties
			},
			{
					CountryIsoCode.RO,
					RO.CountryProperties
			},
			{
					CountryIsoCode.CH,
					CH.CountryProperties
			},
			{
					CountryIsoCode.AT,
					AT.CountryProperties
			},
			{
					CountryIsoCode.GB,
					GB.CountryProperties
			},
			{
					CountryIsoCode.DK,
					DK.CountryProperties
			},
			{
					CountryIsoCode.SE,
					SE.CountryProperties
			},
			{
					CountryIsoCode.NO,
					NO.CountryProperties
			},
			{
					CountryIsoCode.SJ,
					SJ.CountryProperties
			},
			{
					CountryIsoCode.PL,
					PL.CountryProperties
			},
			{
					CountryIsoCode.DE,
					DE.CountryProperties
			},
			{
					CountryIsoCode.PE,
					PE.CountryProperties
			},
			{
					CountryIsoCode.MX,
					MX.CountryProperties
			},
			{
					CountryIsoCode.CU,
					CU.CountryProperties
			},
			{
					CountryIsoCode.AR,
					AR.CountryProperties
			},
			{
					CountryIsoCode.BR,
					BR.CountryProperties
			},
			{
					CountryIsoCode.CL,
					CL.CountryProperties
			},
			{
					CountryIsoCode.CO,
					CO.CountryProperties
			},
			{
					CountryIsoCode.VE,
					VE.CountryProperties
			},
			{
					CountryIsoCode.MY,
					MY.CountryProperties
			},
			{
					CountryIsoCode.AU,
					AU.CountryProperties
			},
			{
					CountryIsoCode.ID,
					ID.CountryProperties
			},
			{
					CountryIsoCode.PH,
					PH.CountryProperties
			},
			{
					CountryIsoCode.NZ,
					NZ.CountryProperties
			},
			{
					CountryIsoCode.PN,
					PN.CountryProperties
			},
			{
					CountryIsoCode.SG,
					SG.CountryProperties
			},
			{
					CountryIsoCode.TH,
					TH.CountryProperties
			},
			{
					CountryIsoCode.JP,
					JP.CountryProperties
			},
			{
					CountryIsoCode.KR,
					KR.CountryProperties
			},
			{
					CountryIsoCode.VN,
					VN.CountryProperties
			},
			{
					CountryIsoCode.CN,
					CN.CountryProperties
			},
			{
					CountryIsoCode.TR,
					TR.CountryProperties
			},
			{
					CountryIsoCode.IN,
					IN.CountryProperties
			},
			{
					CountryIsoCode.PK,
					PK.CountryProperties
			},
			{
					CountryIsoCode.AF,
					AF.CountryProperties
			},
			{
					CountryIsoCode.LK,
					LK.CountryProperties
			},
			{
					CountryIsoCode.MM,
					MM.CountryProperties
			},
			{
					CountryIsoCode.IR,
					IR.CountryProperties
			},
			{
					CountryIsoCode.MA,
					MA.CountryProperties
			},
			{
					CountryIsoCode.EH,
					EH.CountryProperties
			},
			{
					CountryIsoCode.DZ,
					DZ.CountryProperties
			},
			{
					CountryIsoCode.TN,
					TN.CountryProperties
			},
			{
					CountryIsoCode.LY,
					LY.CountryProperties
			},
			{
					CountryIsoCode.GM,
					GM.CountryProperties
			},
			{
					CountryIsoCode.SN,
					SN.CountryProperties
			},
			{
					CountryIsoCode.MR,
					MR.CountryProperties
			},
			{
					CountryIsoCode.ML,
					ML.CountryProperties
			},
			{
					CountryIsoCode.GN,
					GN.CountryProperties
			},
			{
					CountryIsoCode.BF,
					BF.CountryProperties
			},
			{
					CountryIsoCode.NE,
					NE.CountryProperties
			},
			{
					CountryIsoCode.TG,
					TG.CountryProperties
			},
			{
					CountryIsoCode.BJ,
					BJ.CountryProperties
			},
			{
					CountryIsoCode.MU,
					MU.CountryProperties
			},
			{
					CountryIsoCode.LR,
					LR.CountryProperties
			},
			{
					CountryIsoCode.SL,
					SL.CountryProperties
			},
			{
					CountryIsoCode.GH,
					GH.CountryProperties
			},
			{
					CountryIsoCode.NG,
					NG.CountryProperties
			},
			{
					CountryIsoCode.TD,
					TD.CountryProperties
			},
			{
					CountryIsoCode.CF,
					CF.CountryProperties
			},
			{
					CountryIsoCode.CM,
					CM.CountryProperties
			},
			{
					CountryIsoCode.CV,
					CV.CountryProperties
			},
			{
					CountryIsoCode.ST,
					ST.CountryProperties
			},
			{
					CountryIsoCode.GQ,
					GQ.CountryProperties
			},
			{
					CountryIsoCode.GA,
					GA.CountryProperties
			},
			{
					CountryIsoCode.CG,
					CG.CountryProperties
			},
			{
					CountryIsoCode.CD,
					CD.CountryProperties
			},
			{
					CountryIsoCode.AO,
					AO.CountryProperties
			},
			{
					CountryIsoCode.GW,
					GW.CountryProperties
			},
			{
					CountryIsoCode.SC,
					SC.CountryProperties
			},
			{
					CountryIsoCode.SD,
					SD.CountryProperties
			},
			{
					CountryIsoCode.RW,
					RW.CountryProperties
			},
			{
					CountryIsoCode.ET,
					ET.CountryProperties
			},
			{
					CountryIsoCode.SO,
					SO.CountryProperties
			},
			{
					CountryIsoCode.DJ,
					DJ.CountryProperties
			},
			{
					CountryIsoCode.KE,
					KE.CountryProperties
			},
			{
					CountryIsoCode.TZ,
					TZ.CountryProperties
			},
			{
					CountryIsoCode.UG,
					UG.CountryProperties
			},
			{
					CountryIsoCode.BI,
					BI.CountryProperties
			},
			{
					CountryIsoCode.MZ,
					MZ.CountryProperties
			},
			{
					CountryIsoCode.ZM,
					ZM.CountryProperties
			},
			{
					CountryIsoCode.MG,
					MG.CountryProperties
			},
			{
					CountryIsoCode.YT,
					YT.CountryProperties
			},
			{
					CountryIsoCode.RE,
					RE.CountryProperties
			},
			{
					CountryIsoCode.ZW,
					ZW.CountryProperties
			},
			{
					CountryIsoCode.NA,
					NA.CountryProperties
			},
			{
					CountryIsoCode.MW,
					MW.CountryProperties
			},
			{
					CountryIsoCode.LS,
					LS.CountryProperties
			},
			{
					CountryIsoCode.BW,
					BW.CountryProperties
			},
			{
					CountryIsoCode.SZ,
					SZ.CountryProperties
			},
			{
					CountryIsoCode.KM,
					KM.CountryProperties
			},
			{
					CountryIsoCode.SH,
					SH.CountryProperties
			},
			{
					CountryIsoCode.ER,
					ER.CountryProperties
			},
			{
					CountryIsoCode.AW,
					AW.CountryProperties
			},
			{
					CountryIsoCode.FO,
					FO.CountryProperties
			},
			{
					CountryIsoCode.GL,
					GL.CountryProperties
			},
			{
					CountryIsoCode.GI,
					GI.CountryProperties
			},
			{
					CountryIsoCode.PT,
					PT.CountryProperties
			},
			{
					CountryIsoCode.LU,
					LU.CountryProperties
			},
			{
					CountryIsoCode.IE,
					IE.CountryProperties
			},
			{
					CountryIsoCode.IS,
					IS.CountryProperties
			},
			{
					CountryIsoCode.AL,
					AL.CountryProperties
			},
			{
					CountryIsoCode.MT,
					MT.CountryProperties
			},
			{
					CountryIsoCode.CY,
					CY.CountryProperties
			},
			{
					CountryIsoCode.FI,
					FI.CountryProperties
			},
			{
					CountryIsoCode.BG,
					BG.CountryProperties
			},
			{
					CountryIsoCode.LT,
					LT.CountryProperties
			},
			{
					CountryIsoCode.LV,
					LV.CountryProperties
			},
			{
					CountryIsoCode.EE,
					EE.CountryProperties
			},
			{
					CountryIsoCode.MD,
					MD.CountryProperties
			},
			{
					CountryIsoCode.AM,
					AM.CountryProperties
			},
			{
					CountryIsoCode.BY,
					BY.CountryProperties
			},
			{
					CountryIsoCode.AD,
					AD.CountryProperties
			},
			{
					CountryIsoCode.MC,
					MC.CountryProperties
			},
			{
					CountryIsoCode.SM,
					SM.CountryProperties
			},
			{
					CountryIsoCode.VA,
					VA.CountryProperties
			},
			{
					CountryIsoCode.UA,
					UA.CountryProperties
			},
			{
					CountryIsoCode.HR,
					HR.CountryProperties
			},
			{
					CountryIsoCode.SI,
					SI.CountryProperties
			},
			{
					CountryIsoCode.BA,
					BA.CountryProperties
			},
			{
					CountryIsoCode.MK,
					MK.CountryProperties
			},
			{
					CountryIsoCode.CZ,
					CZ.CountryProperties
			},
			{
					CountryIsoCode.SK,
					SK.CountryProperties
			},
			{
					CountryIsoCode.LI,
					LI.CountryProperties
			},
			{
					CountryIsoCode.FK,
					FK.CountryProperties
			},
			{
					CountryIsoCode.BZ,
					BZ.CountryProperties
			},
			{
					CountryIsoCode.GT,
					GT.CountryProperties
			},
			{
					CountryIsoCode.SV,
					SV.CountryProperties
			},
			{
					CountryIsoCode.HN,
					HN.CountryProperties
			},
			{
					CountryIsoCode.NI,
					NI.CountryProperties
			},
			{
					CountryIsoCode.CR,
					CR.CountryProperties
			},
			{
					CountryIsoCode.PA,
					PA.CountryProperties
			},
			{
					CountryIsoCode.PM,
					PM.CountryProperties
			},
			{
					CountryIsoCode.HT,
					HT.CountryProperties
			},
			{
					CountryIsoCode.GP,
					GP.CountryProperties
			},
			{
					CountryIsoCode.BO,
					BO.CountryProperties
			},
			{
					CountryIsoCode.GY,
					GY.CountryProperties
			},
			{
					CountryIsoCode.EC,
					EC.CountryProperties
			},
			{
					CountryIsoCode.GF,
					GF.CountryProperties
			},
			{
					CountryIsoCode.PY,
					PY.CountryProperties
			},
			{
					CountryIsoCode.MQ,
					MQ.CountryProperties
			},
			{
					CountryIsoCode.SR,
					SR.CountryProperties
			},
			{
					CountryIsoCode.UY,
					UY.CountryProperties
			},
			{
					CountryIsoCode.TL,
					TL.CountryProperties
			},
			{
					CountryIsoCode.NF,
					NF.CountryProperties
			},
			{
					CountryIsoCode.BN,
					BN.CountryProperties
			},
			{
					CountryIsoCode.NR,
					NR.CountryProperties
			},
			{
					CountryIsoCode.PG,
					PG.CountryProperties
			},
			{
					CountryIsoCode.TO,
					TO.CountryProperties
			},
			{
					CountryIsoCode.SB,
					SB.CountryProperties
			},
			{
					CountryIsoCode.VU,
					VU.CountryProperties
			},
			{
					CountryIsoCode.FJ,
					FJ.CountryProperties
			},
			{
					CountryIsoCode.PW,
					PW.CountryProperties
			},
			{
					CountryIsoCode.WF,
					WF.CountryProperties
			},
			{
					CountryIsoCode.NU,
					NU.CountryProperties
			},
			{
					CountryIsoCode.WS,
					WS.CountryProperties
			},
			{
					CountryIsoCode.KI,
					KI.CountryProperties
			},
			{
					CountryIsoCode.NC,
					NC.CountryProperties
			},
			{
					CountryIsoCode.TV,
					TV.CountryProperties
			},
			{
					CountryIsoCode.PF,
					PF.CountryProperties
			},
			{
					CountryIsoCode.TK,
					TK.CountryProperties
			},
			{
					CountryIsoCode.FM,
					FM.CountryProperties
			},
			{
					CountryIsoCode.MH,
					MH.CountryProperties
			},
			{
					CountryIsoCode.KP,
					KP.CountryProperties
			},
			{
					CountryIsoCode.HK,
					HK.CountryProperties
			},
			{
					CountryIsoCode.MO,
					MO.CountryProperties
			},
			{
					CountryIsoCode.KH,
					KH.CountryProperties
			},
			{
					CountryIsoCode.LA,
					LA.CountryProperties
			},
			{
					CountryIsoCode.BD,
					BD.CountryProperties
			},
			{
					CountryIsoCode.TW,
					TW.CountryProperties
			},
			{
					CountryIsoCode.MV,
					MV.CountryProperties
			},
			{
					CountryIsoCode.LB,
					LB.CountryProperties
			},
			{
					CountryIsoCode.JO,
					JO.CountryProperties
			},
			{
					CountryIsoCode.SY,
					SY.CountryProperties
			},
			{
					CountryIsoCode.IQ,
					IQ.CountryProperties
			},
			{
					CountryIsoCode.KW,
					KW.CountryProperties
			},
			{
					CountryIsoCode.SA,
					SA.CountryProperties
			},
			{
					CountryIsoCode.YE,
					YE.CountryProperties
			},
			{
					CountryIsoCode.OM,
					OM.CountryProperties
			},
			{
					CountryIsoCode.AE,
					AE.CountryProperties
			},
			{
					CountryIsoCode.IL,
					IL.CountryProperties
			},
			{
					CountryIsoCode.BH,
					BH.CountryProperties
			},
			{
					CountryIsoCode.QA,
					QA.CountryProperties
			},
			{
					CountryIsoCode.BT,
					BT.CountryProperties
			},
			{
					CountryIsoCode.MN,
					MN.CountryProperties
			},
			{
					CountryIsoCode.NP,
					NP.CountryProperties
			},
			{
					CountryIsoCode.TJ,
					TJ.CountryProperties
			},
			{
					CountryIsoCode.TM,
					TM.CountryProperties
			},
			{
					CountryIsoCode.AZ,
					AZ.CountryProperties
			},
			{
					CountryIsoCode.GE,
					GE.CountryProperties
			},
			{
					CountryIsoCode.KG,
					KG.CountryProperties
			},
			{
					CountryIsoCode.UZ,
					UZ.CountryProperties
			},
			{
					CountryIsoCode.RS,
					RS.CountryProperties
			},
			{
					CountryIsoCode.ME,
					ME.CountryProperties
			},
			{
					CountryIsoCode.CI,
					CI.CountryProperties
			},
			{
					CountryIsoCode.SS,
					SS.CountryProperties
			},
			{
					CountryIsoCode.PS,
					PS.CountryProperties
			},
			{
					CountryIsoCode.AX,
					AX.CountryProperties
			},
			{
					CountryIsoCode.BL,
					BL.CountryProperties
			},
			{
					CountryIsoCode.MF,
					MF.CountryProperties
			},
			{
					CountryIsoCode.BQ,
					BQ.CountryProperties
			},
			{
					CountryIsoCode.CW,
					CW.CountryProperties
			},
			{
					CountryIsoCode.SX,
					SX.CountryProperties
			}
		};
	}
}
