// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class AE
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "971",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "De Forenede Arabiske Emirater" },
				{ LanguageId.af, "Verenigde Arabiese Emirate" },
				{ LanguageId.agq, "Yùnaetɛ Alab ɛmelɛ̀" },
				{ LanguageId.ak, "United Arab Emirates" },
				{ LanguageId.am, "የተባበሩት ዓረብ ኤምሬትስ" },
				{ LanguageId.ar, "الإمارات العربية المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "সংযুক্ত আৰব আমিৰাত" },
				{ LanguageId.asa, "Falme dha Kiarabu" },
				{ LanguageId.ast, "Emiratos Árabes Xuníos" },
				{ LanguageId.az, "Birləşmiş Ərəb Əmirlikləri" },
				{ LanguageId.ba, "Берләшкән Ғәрәп Әмирлектәре" },
				{ LanguageId.bas, "Àdnà i Bilɔ̀ŋ bi Arābìà" },
				{ LanguageId.be, "Аб’яднаныя Арабскія Эміраты" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hufalme dza Hihalabu" },
				{ LanguageId.bg, "Обединени арабски емирства" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Arabu mara kafoli" },
				{ LanguageId.bn, "সংযুক্ত আরব আমিরাত" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Emirelezhioù-Arab-Unanet" },
				{ LanguageId.brx, "जथाय आराब एमिरेत" },
				{ LanguageId.bs, "Ujedinjeni Arapski Emirati" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Emirats Àrabs Units" },
				{ LanguageId.ccp, "𑄎𑄧𑄙 𑄃𑄢𑄧𑄝𑄴 𑄃𑄟𑄨𑄢𑄖𑄴" },
				{ LanguageId.ce, "Ӏарбийн Цхьанатоьхна Эмираташ" },
				{ LanguageId.ceb, "United Arab Emirates" },
				{ LanguageId.cgg, "Amahanga ga Buharabu ageeteereine" },
				{ LanguageId.chr, "ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᎡᎳᏈ ᎢᎹᎵᏘᏏ" },
				{ LanguageId.ckb, "میرنشینە یەکگرتووە عەرەبییەکان" },
				{ LanguageId.co, "Emirati Arabi Uniti" },
				{ LanguageId.cs, "Spojené arabské emiráty" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Emiradau Arabaidd Unedig" },
				{ LanguageId.dav, "Falme za Kiarabu" },
				{ LanguageId.de, "Vereinigte Arabische Emirate" },
				{ LanguageId.dje, "Laaraw Imaarawey Margantey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Zjadnośone arabiske emiraty" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཡུ་ནཱའི་ཊེཌ་ ཨ་རབ་ ཨེ་མེ་རེཊས" },
				{ LanguageId.ebu, "Falme za Kiarabu" },
				{ LanguageId.ee, "United Arab Emirates nutome" },
				{ LanguageId.el, "Ηνωμένα Αραβικά Εμιράτα" },
				{ LanguageId.en, "United Arab Emirates" },
				{ LanguageId.eo, "Unuiĝintaj Arabaj Emirlandoj" },
				{ LanguageId.es, "Emiratos Árabes Unidos" },
				{ LanguageId.et, "Araabia Ühendemiraadid" },
				{ LanguageId.eu, "Arabiar Emirerri Batuak" },
				{ LanguageId.ewo, "Bemirá yá Arábə uní" },
				{ LanguageId.fa, "امارات متحدهٔ عربی" },
				{ LanguageId.ff, "Emiraat Araab Denntuɗe" },
				{ LanguageId.fi, "Arabiemiirikunnat" },
				{ LanguageId.fil, "United Arab Emirates" },
				{ LanguageId.fo, "Sameindu Emirríkini" },
				{ LanguageId.fr, "Émirats arabes unis" },
				{ LanguageId.fur, "Emirâts araps unîts" },
				{ LanguageId.fy, "Verenigde Arabyske Emiraten" },
				{ LanguageId.ga, "Aontas na nÉimíríochtaí Arabacha" },
				{ LanguageId.gd, "Na h-Iomaratan Arabach Aonaichte" },
				{ LanguageId.gl, "Emiratos Árabes Unidos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Veräinigti Arabischi Emirate" },
				{ LanguageId.gu, "યુનાઇટેડ આરબ અમીરાત" },
				{ LanguageId.guz, "Falme za Kiarabu" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Haɗaɗɗiyar Daular Larabawa" },
				{ LanguageId.haw, "Aupuni ʻEmira ʻAlapia Hui Pū ʻia" },
				{ LanguageId.he, "איחוד האמירויות הערביות" },
				{ LanguageId.hi, "संयुक्त अरब अमीरात" },
				{ LanguageId.hr, "Ujedinjeni Arapski Emirati" },
				{ LanguageId.hsb, "Zjednoćene arabske emiraty" },
				{ LanguageId.hu, "Egyesült Arab Emírségek" },
				{ LanguageId.hy, "Արաբական Միացյալ Էմիրություններ" },
				{ LanguageId.ia, "Emiratos Arabe Unite" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Uni Emirat Arab" },
				{ LanguageId.ig, "United Arab Emirates" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sameinuðu arabísku furstadæmin" },
				{ LanguageId.it, "Emirati Arabi Uniti" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アラブ首長国連邦" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Falme za Kiarabu" },
				{ LanguageId.jv, "Uni Émirat Arab" },
				{ LanguageId.ka, "არაბთა გაერთიანებული საამიროები" },
				{ LanguageId.kab, "Tigeldunin Yedduklen Taɛrabin" },
				{ LanguageId.kam, "Falme za Kiarabu" },
				{ LanguageId.kde, "Dimiliki dya Vakulungwa va Chalabu" },
				{ LanguageId.kea, "Emiradus Árabi Unidu" },
				{ LanguageId.khq, "Laaraw Imaarawey Margantey" },
				{ LanguageId.ki, "Falme za Kiarabu" },
				{ LanguageId.kk, "Біріккен Араб Әмірліктері" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab kibagenge nebo arabuk" },
				{ LanguageId.km, "អេមីរ៉ាត​អារ៉ាប់​រួម" },
				{ LanguageId.kn, "ಯುನೈಟೆಡ್ ಅರಬ್ ಎಮಿರೇಟ್ಸ್" },
				{ LanguageId.ko, "아랍에미리트" },
				{ LanguageId.kok, "संयुक्त अरबी अमीरात" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مُتحدہ عرَب امارات" },
				{ LanguageId.ksb, "Falme za Kialabu" },
				{ LanguageId.ksf, "bǝlɔŋ bǝ kaksa bɛ táatáaŋzǝn" },
				{ LanguageId.ksh, "Vereinschte Arrabesche Emmirate" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Бириккен Араб Эмираттары" },
				{ LanguageId.la, "United Arab Emirates" },
				{ LanguageId.lag, "Ʉtemi wa Kɨaráabu" },
				{ LanguageId.lb, "Vereenegt Arabesch Emirater" },
				{ LanguageId.lg, "Emireeti" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Lɛmila alabo" },
				{ LanguageId.lo, "ສະຫະລັດອາຣັບເອມິເຣດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jungtiniai Arabų Emyratai" },
				{ LanguageId.luo, "United Arab Emirates" },
				{ LanguageId.luy, "Falme za Kiarabu" },
				{ LanguageId.lv, "Apvienotie Arābu Emirāti" },
				{ LanguageId.mai, "संयुक्त अरब अमीरात" },
				{ LanguageId.mas, "Falme za Kiarabu" },
				{ LanguageId.mer, "Falme cia Kiarabu" },
				{ LanguageId.mfe, "Emira arab ini" },
				{ LanguageId.mg, "Emirà Arabo mitambatra" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Kotahitanga o ngā Whenua o Ārapi" },
				{ LanguageId.mk, "Обединети Арапски Емирати" },
				{ LanguageId.ml, "യുണൈറ്റഡ് അറബ് എമിറൈറ്റ്‌സ്" },
				{ LanguageId.mn, "Арабын Нэгдсэн Эмират Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "संयुक्त अरब अमिराती" },
				{ LanguageId.ms, "Emiriah Arab Bersatu" },
				{ LanguageId.mt, "l-Emirati Għarab Magħquda" },
				{ LanguageId.mua, "Sǝr Arabiya ma taini" },
				{ LanguageId.my, "ယူအေအီး" },
				{ LanguageId.mzn, "متحده عربی امارات" },
				{ LanguageId.naq, "United Arab Emirates" },
				{ LanguageId.nb, "De forente arabiske emirater" },
				{ LanguageId.nd, "United Arab Emirates" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त अरब इमिराट्स" },
				{ LanguageId.nl, "Verenigde Arabische Emiraten" },
				{ LanguageId.nmg, "Minlambɔ́ Nsaŋ́nsa mí Arabia" },
				{ LanguageId.nn, "Dei sameinte arabiske emirata" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߋߡߌߙߊߕ ߊߙߊߓߎ߫ ߘߍ߬ߣߍ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Amahanga ga Buharabu ageeteereine" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Yuunaatid Arab Emereet" },
				{ LanguageId.or, "ସଂଯୁକ୍ତ ଆରବ ଏମିରେଟସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੰਯੁਕਤ ਅਰਬ ਅਮੀਰਾਤ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Yunaítẹ́d Áráb Ẹ́mírets" },
				{ LanguageId.pl, "Zjednoczone Emiraty Arabskie" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "متحده عرب امارات" },
				{ LanguageId.pt, "Emirados Árabes Unidos" },
				{ LanguageId.qu, "Emiratos Árabes Unidos" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Emirats Arabs Unids" },
				{ LanguageId.rn, "Leta Zunze Ubumwe z’Abarabu" },
				{ LanguageId.ro, "Emiratele Arabe Unite" },
				{ LanguageId.rof, "Falme za Kiarabu" },
				{ LanguageId.ru, "ОАЭ" },
				{ LanguageId.rw, "United Arab Emirates" },
				{ LanguageId.rwk, "Falme za Kiarabu" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Falme za Kiarabu" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Wutwa wa shiyalabu" },
				{ LanguageId.sd, "متحده عرب امارات" },
				{ LanguageId.se, "Ovttastuvvan Arábaemiráhtat" },
				{ LanguageId.seh, "Emirados Árabes Unidos" },
				{ LanguageId.ses, "Laaraw Imaarawey Margantey" },
				{ LanguageId.sg, "Arâbo Emirâti Ôko" },
				{ LanguageId.shi, "ⵍⵉⵎⴰⵔⴰⵜ" },
				{ LanguageId.si, "එක්සත් අරාබි එමිර් රාජ්‍යය" },
				{ LanguageId.sk, "Spojené arabské emiráty" },
				{ LanguageId.sl, "Združeni arabski emirati" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Arabiemirkodeh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "United Arab Emirates" },
				{ LanguageId.so, "Midawga Imaaraatka Carabta" },
				{ LanguageId.sq, "Emiratet e Bashkuara Arabe" },
				{ LanguageId.sr, "Уједињени Арапски Емирати" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "United Arab Emirates" },
				{ LanguageId.su, "Uni Émirat Arab" },
				{ LanguageId.sv, "Förenade Arabemiraten" },
				{ LanguageId.sw, "Falme za Kiarabu" },
				{ LanguageId.syr, "ܐܡܝܪ̈ܘܬܐ ܥܪ̈ܒܝܬܐ ܡܚܝ̈ܕܬܐ" },
				{ LanguageId.ta, "ஐக்கிய அரபு அமீரகம்" },
				{ LanguageId.te, "యునైటెడ్ అరబ్ ఎమిరేట్స్" },
				{ LanguageId.teo, "Falme za Kiarabu" },
				{ LanguageId.tg, "Аморатҳои Муттаҳидаи Араб" },
				{ LanguageId.th, "สหรัฐอาหรับเอมิเรตส์" },
				{ LanguageId.ti, "ሕቡራት ኢማራት ዓረብ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Birleşen Arap Emirlikleri" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻAlepea Fakatahataha" },
				{ LanguageId.tr, "Birleşik Arap Emirlikleri" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Берләшкән Гарәп Әмирлекләре" },
				{ LanguageId.twq, "Laaraw Imaarawey Margantey" },
				{ LanguageId.tzm, "Imarat Tiεrabin Tidduklin" },
				{ LanguageId.ug, "ئەرەب بىرلەشمە خەلىپىلىكى" },
				{ LanguageId.uk, "Обʼєднані Арабські Емірати" },
				{ LanguageId.ur, "متحدہ عرب امارات" },
				{ LanguageId.uz, "Birlashgan Arab Amirliklari" },
				{ LanguageId.vai, "ꖳꕯꔤꗳ ꕉꕟꔬ ꗡꕆꔓꔻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Các Tiểu Vương quốc Ả Rập Thống nhất" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Falme za Kiarabu" },
				{ LanguageId.wae, "Vereinigti Arabiše Emirat" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Emira Arab Ini" },
				{ LanguageId.xh, "E-United Arab Emirates" },
				{ LanguageId.xog, "Emireeti" },
				{ LanguageId.yav, "imiláat i paaláap" },
				{ LanguageId.yi, "פאראייניקטע אַראַבער עמיראַטעס" },
				{ LanguageId.yo, "Ẹmirate ti Awọn Arabu" },
				{ LanguageId.zgh, "ⵍⵉⵎⴰⵔⴰⵜ" },
				{ LanguageId.zh, "阿拉伯联合酋长国" },
				{ LanguageId.zu, "i-United Arab Emirates" },
			}
		);
	}
}
