using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class AE
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "971",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Forenede Arabiske Emirater" },
				{ LanguageId.af, "Verenigde Arabiese Emirate" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዩናይትድ ዓረብ ኤምሬት" },
				{ LanguageId.ar, "الإمارات العربية المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Birləşmiş Ərəb Əmirlikləri" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Абяднаныя Арабскія Эміраты" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Обединени арабски емирства" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সংযুক্ত আরব আমিরাত" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Emirelezhioù Arab Unanet" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ujedinjeni Arapski Emirati" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Emirats Àrabs Units" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "United Arab Emirates" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Emirati Arabi Uniti" },
				{ LanguageId.cs, "Spojené arabské emiráty" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Emiradau Arabaidd Unedig" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Vereinigte Arabische Emirate" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ηνωμένα Αραβικά Εμιράτα" },
				{ LanguageId.en, "United Arab Emirates" },
				{ LanguageId.eo, "Unuiĝintaj Arabaj Emirlandoj" },
				{ LanguageId.es, "Emiratos Árabes Unidos" },
				{ LanguageId.et, "Araabia Ühendemiraadid" },
				{ LanguageId.eu, "Arabiar Emirerri Batuak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "امارات متحده عربی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Yhdistyneet Arabiemiirikunnat" },
				{ LanguageId.fil, "United Arab Emirates" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Emirats Arabes Unis" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Feriene Arabyske Emiraten" },
				{ LanguageId.ga, "Aontas na nÉimíríochtaí Arabacha" },
				{ LanguageId.gd, "Emirates Arabach Aonaichte" },
				{ LanguageId.gl, "Emiratos Árabes Unidos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સંયુક્ત આરબ અમીરાત" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Hadaddiyar Daular Larabawa" },
				{ LanguageId.haw, "Aupuni ʻEmira ʻAlapia Hui Pū ʻia" },
				{ LanguageId.he, "איחוד האמירויות הערביות" },
				{ LanguageId.hi, "संयुक्त अरब अमीरात" },
				{ LanguageId.hr, "Ujedinjeni Arapski Emirati" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Egyesült Arab Emírségek" },
				{ LanguageId.hy, "Արաբական Միացյալ Էմիրություններ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Uni Emirat Arab" },
				{ LanguageId.ig, "United Arab Emirates" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sameinuðu arabísku furstadæmin" },
				{ LanguageId.it, "Emirati Arabi Uniti" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アラブ首長国連邦" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Uni Emirat Arab" },
				{ LanguageId.ka, "არაბთა გაერთიანებული საამიროები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Біріккен Араб Әмірліктері" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សហព័ន្ធ​អារ៉ាប់រួម" },
				{ LanguageId.kn, "ಸಂಯುಕ್ತ ಅರಬ್ ಸಂಸ್ಥಾಪನೆಗಳು" },
				{ LanguageId.ko, "아랍 에미리트" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кошмо Араб Эмираттар" },
				{ LanguageId.la, "United Arab Emirates" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Vereenegt Arabesch Emirater" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສະຫະລັດອາຣັບເອມີເຣດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jungtiniai Arabų Emyratai" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Apvienotie Arābu Emirāti" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Emira Arabo Mitambatra" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "United Arab Emirates" },
				{ LanguageId.mk, "Обединети Арапски Емирати" },
				{ LanguageId.ml, "യുണൈറ്റഡ് അറബ് എമിറേറ്റ്സ്" },
				{ LanguageId.mn, "Арабын нэгдсэн Эмират улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "संयुक्त अरब अमिराती" },
				{ LanguageId.ms, "Emiriah Arab Bersatu" },
				{ LanguageId.mt, "Emirati Għarab Magħquda" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အာရပ်စော်ဘွားများ ပြည်ထောင်စု" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "De forente arabiske emirater" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त अरब इमिरेट्स" },
				{ LanguageId.nl, "Verenigde Arabische Emiraten" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ୟୁନାଇଟେଡ୍ ଆରବ ଏମିରେଟେସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੰਯੁਕਤ ਅਰਬ ਅਮੀਰਾਤ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Zjednoczone Emiraty Arabskie" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "متحده عربي امارات" },
				{ LanguageId.pt, "Emirados Árabes Unidos" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Emiratele Arabe Unite" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Объединенные Арабские Эмираты" },
				{ LanguageId.rw, "United Arab Emirates" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "متحده عرب امارات" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "එක්සත් අරාබි එමීර් රාජ්‍යය" },
				{ LanguageId.sk, "Spojené Arabské Emiráty" },
				{ LanguageId.sl, "Združeni Arabski Emirati" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Mubatanidzwa Arabhu Emeretsi" },
				{ LanguageId.so, "Imaaraadka Carabta" },
				{ LanguageId.sq, "Emiratet e Bashkuara Arabe" },
				{ LanguageId.sr, "Уједињени арапски Емирати" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "United Arab Emirates" },
				{ LanguageId.su, "Uni Émirat Arab" },
				{ LanguageId.sv, "Förenade arabemiraten" },
				{ LanguageId.sw, "Umoja wa Falme za Kiarabu" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஐக்கிய அரபு நாடுகள்" },
				{ LanguageId.te, "యునైటెడ్ అరబ్ ఎమిరేట్స్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Аморати Муттахидаи Араб" },
				{ LanguageId.th, "สหรัฐอาหรับเอมิเรตส์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Birleşen Arap Emirlikleri" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Birleşik Arap Emirlikleri" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Берләшкән Гарәп Әмирлекләре" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ئەرەب بىرلەشمە خەلىپىلىكى" },
				{ LanguageId.uk, "Об'єднані Арабські Емірати" },
				{ LanguageId.ur, "متحدہ عرب امارات" },
				{ LanguageId.uz, "Birlashgan Arab Amirliklari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "các Tiểu Vương Quốc Ả Rập Thống Nhất" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IUnited Arab Emirates" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פאראייניקטע אַראַבער עמיראַטעס" },
				{ LanguageId.yo, "Apapọ Arab Emirates" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "阿拉伯联合酋长国" },
				{ LanguageId.zu, "I-United Arab Emirates" },
			}
		);
	}
}
