using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class AG
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Antigua og Barbuda" },
				{ LanguageId.af, "Antigua en Barbuda" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "አንቲጉአ እና ባርቡዳ" },
				{ LanguageId.ar, "أنتيغوا وبربودا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Antiqua və Barbuda" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Антыгуа і Барбуда" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Антигуа и Барбуда" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "অ্যান্টিগুয়া ও বার্বুডা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Antigva i Barbuda" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Antigua i Barbuda" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Antigua ug Barbuda" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Antigua è Barbuda" },
				{ LanguageId.cs, "Antigua a Barbuda" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Antigua a Barbuda" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Antigua und Barbuda" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Αντίγκουα και Μπαρμπούντα" },
				{ LanguageId.en, "Antigua and Barbuda" },
				{ LanguageId.eo, "Antigvo kaj Barbudo" },
				{ LanguageId.es, "Antigua y Barbuda" },
				{ LanguageId.et, "Antigua ja Barbuda" },
				{ LanguageId.eu, "Antigua eta Barbuda" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "آنتیگوا و باربودا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Antigua ja Barbuda" },
				{ LanguageId.fil, "Antigua at Barbuda" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Antigua-et-Barbuda" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Antigûa en Barbûda" },
				{ LanguageId.ga, "Antigua agus Barbúda" },
				{ LanguageId.gd, "Antigua is Barbuda" },
				{ LanguageId.gl, "Antiga e Barbuda" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "એન્ટિગુઆ અને બાર્બુડા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Antigua da Barbuda" },
				{ LanguageId.haw, "ʻAnatigua me Parapuka" },
				{ LanguageId.he, "אנטיגואה וברבודה" },
				{ LanguageId.hi, "अण्टीगुआ और बारबूडा" },
				{ LanguageId.hr, "Antigva i Barbuda" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Antigua és Barbuda" },
				{ LanguageId.hy, "Անտիգուա և Բարբուդա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Antigua dan Barbuda" },
				{ LanguageId.ig, "Antigua na Barbuda" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Antígva og Barbúda" },
				{ LanguageId.it, "Antigua e Barbuda" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アンティグアバーブーダ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Antigua lan Barbuda" },
				{ LanguageId.ka, "ანტიგუა და ბარბუდა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Антигуа және Барбуда" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Antigua និង Barbuda" },
				{ LanguageId.kn, "ಆಂಟಿಗುವಾ ಮತ್ತು ಬಾರ್ಬುಡಾ" },
				{ LanguageId.ko, "앤티가 바부다" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Антигуа жана Барбуда" },
				{ LanguageId.la, "Antigua et Barbuda" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Antigua a Barbuda" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Antigua ແລະ Barbuda" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Antigva ir Barbuda" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Antigva un Barbuda" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Antigua sy Barbuda" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Antigua me Barbuda" },
				{ LanguageId.mk, "Антигва и Барбуда" },
				{ LanguageId.ml, "ആൻ്റിഗ്വയും ബാർബുഡയും" },
				{ LanguageId.mn, "Антигуа ба Барбуда" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "अँटिग्वा आणि बार्बुडा" },
				{ LanguageId.ms, "Antigua dan Barbuda" },
				{ LanguageId.mt, "Antigwa u Barbuda" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အန်တီဂွါနဲ့ ဘာဘူဒါ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Antigua og Barbuda" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "एन्टिगुवा र बारबुडा" },
				{ LanguageId.nl, "Antigua en Barbuda" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଆଣ୍ଟିଗୁଆ ଏବଂ ବାରବୁଦା |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਐਂਟੀਗੁਆ ਅਤੇ ਬਾਰਬੁਡਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Antigua i Barbuda" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "انتیګا او باربودا" },
				{ LanguageId.pt, "Antígua e Barbuda" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Antigua si Barbuda" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Антигуа и Барбуда" },
				{ LanguageId.rw, "Antigua na Barbuda" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "انٽيگوا ۽ باربودا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ඇන්ටිගුවා සහ බාබුඩා" },
				{ LanguageId.sk, "Antigua a Barbuda" },
				{ LanguageId.sl, "Antigva in Barbuda" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Andiguya neBhabhudha" },
				{ LanguageId.so, "Antigua iyo Barbuda" },
				{ LanguageId.sq, "Antigua dhe Barbuda" },
				{ LanguageId.sr, "Антигва и Барбуда" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Antigua le Barbuda" },
				{ LanguageId.su, "Antigua jeung Barbuda" },
				{ LanguageId.sv, "Antigua och Barbuda" },
				{ LanguageId.sw, "Antigua na Barbuda" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஆன்டிகுவா மற்றும் பார்புடா" },
				{ LanguageId.te, "ఆంటిగ్వా మరియు బార్బుడా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Антигуа ва Барбуда" },
				{ LanguageId.th, "แอนติกาและบาร์บูดา" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Antigua we Barbuda" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Antigua ve Barbuda" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Антигуа һәм Барбуда" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ئانتىگۇئا ۋە باربۇدا" },
				{ LanguageId.uk, "Антигуа і Барбуда" },
				{ LanguageId.ur, "انٹیگوا اور باربوڈا" },
				{ LanguageId.uz, "Antigua va Barbuda" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Antigua và Barbuda" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Antiguwa neBarbuda " },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "אַנטיגואַ און באַרבודאַ" },
				{ LanguageId.yo, "Antigua ati Barbuda" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "安提瓜和巴布达" },
				{ LanguageId.zu, "I-Antigua ne-Barbuda" },
			}
		);
	}
}
