// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class AG
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Antigua og Barbuda" },
				{ LanguageId.af, "Antigua en Barbuda" },
				{ LanguageId.agq, "Àntigwà à Bàbudà" },
				{ LanguageId.ak, "Antigua ne Baabuda" },
				{ LanguageId.am, "አንቲጓ እና ባርቡዳ" },
				{ LanguageId.ar, "أنتيغوا وبربودا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "এণ্টিগুৱা আৰু বাৰ্বুডা" },
				{ LanguageId.asa, "Antigua na Barbuda" },
				{ LanguageId.ast, "Antigua y Barbuda" },
				{ LanguageId.az, "Antiqua və Barbuda" },
				{ LanguageId.ba, "Антигуа һәм Барбуда" },
				{ LanguageId.bas, "Àŋtigà ɓɔ Bàrbudà" },
				{ LanguageId.be, "Антыгуа і Барбуда" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huantigua na Hubarubuda" },
				{ LanguageId.bg, "Антигуа и Барбуда" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Antiga-ni-Barbuda" },
				{ LanguageId.bn, "অ্যান্টিগুয়া ও বারবুডা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Antigua-ha-Barbuda" },
				{ LanguageId.brx, "एन्टिगुआ आरो बारबुडा" },
				{ LanguageId.bs, "Antigva i Barbuda" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Antigua i Barbuda" },
				{ LanguageId.ccp, "𑄆𑄚𑄴𑄖𑄨𑄉𑄱 𑄃𑄮 𑄝𑄢𑄴𑄟𑄪𑄓" },
				{ LanguageId.ce, "Антигуа а, Барбуда а" },
				{ LanguageId.ceb, "Antigua & Barbuda" },
				{ LanguageId.cgg, "Angiguwa na Babuda" },
				{ LanguageId.chr, "ᎤᏪᏘ & ᏆᏊᏓ" },
				{ LanguageId.ckb, "ئانتیگوا و باربودا" },
				{ LanguageId.co, "Antigua è Barbuda" },
				{ LanguageId.cs, "Antigua a Barbuda" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Antigua a Barbuda" },
				{ LanguageId.dav, "Antigua na Barbuda" },
				{ LanguageId.de, "Antigua und Barbuda" },
				{ LanguageId.dje, "Antigua nda Barbuuda" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Antigua a Barbuda" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཨན་ཊི་གུ་ཝ་ ཨེནཌ་ བྷར་བྷུ་ཌ" },
				{ LanguageId.ebu, "Antigua na Barbuda" },
				{ LanguageId.ee, "́Antigua kple Barbuda nutome" },
				{ LanguageId.el, "Αντίγκουα και Μπαρμπούντα" },
				{ LanguageId.en, "Antigua & Barbuda" },
				{ LanguageId.eo, "Antigvo kaj Barbudo" },
				{ LanguageId.es, "Antigua y Barbuda" },
				{ LanguageId.et, "Antigua ja Barbuda" },
				{ LanguageId.eu, "Antigua eta Barbuda" },
				{ LanguageId.ewo, "Antígwa ai Barəbúda" },
				{ LanguageId.fa, "آنتیگوا و باربودا" },
				{ LanguageId.ff, "Antiguwaa e Barbudaa" },
				{ LanguageId.fi, "Antigua ja Barbuda" },
				{ LanguageId.fil, "Antigua & Barbuda" },
				{ LanguageId.fo, "Antigua & Barbuda" },
				{ LanguageId.fr, "Antigua-et-Barbuda" },
				{ LanguageId.fur, "Antigua e Barbuda" },
				{ LanguageId.fy, "Antigua en Barbuda" },
				{ LanguageId.ga, "Antigua agus Barbúda" },
				{ LanguageId.gd, "Aintìoga is Barbuda" },
				{ LanguageId.gl, "Antigua e Barbuda" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Antigua und Barbuda" },
				{ LanguageId.gu, "ઍન્ટિગુઆ અને બર્મુડા" },
				{ LanguageId.guz, "Antigua na Barbuda" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Antigua da Barbuda" },
				{ LanguageId.haw, "ʻAnatigua me Parapuka" },
				{ LanguageId.he, "אנטיגואה וברבודה" },
				{ LanguageId.hi, "एंटिगुआ और बरबुडा" },
				{ LanguageId.hr, "Antigva i Barbuda" },
				{ LanguageId.hsb, "Antigua a Barbuda" },
				{ LanguageId.hu, "Antigua és Barbuda" },
				{ LanguageId.hy, "Անտիգուա և Բարբուդա" },
				{ LanguageId.ia, "Antigua e Barbuda" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Antigua dan Barbuda" },
				{ LanguageId.ig, "Antigua na Barbuda" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Antígva og Barbúda" },
				{ LanguageId.it, "Antigua e Barbuda" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アンティグア・バーブーダ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Antigua na Barbuda" },
				{ LanguageId.jv, "Antigua lan Barbuda" },
				{ LanguageId.ka, "ანტიგუა და ბარბუდა" },
				{ LanguageId.kab, "Untiga d Barbuda" },
				{ LanguageId.kam, "Antigua na Barbuda" },
				{ LanguageId.kde, "Antigua na Balbuda" },
				{ LanguageId.kea, "Antigua i Barbuda" },
				{ LanguageId.khq, "Antigua nda Barbuuda" },
				{ LanguageId.ki, "Antigua na Barbuda" },
				{ LanguageId.kk, "Антигуа және Барбуда" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Antigua ak Barbuda" },
				{ LanguageId.km, "អង់ទីហ្គា និង បាប៊ុយដា" },
				{ LanguageId.kn, "ಆಂಟಿಗುವಾ ಮತ್ತು ಬರ್ಬುಡಾ" },
				{ LanguageId.ko, "앤티가 바부다" },
				{ LanguageId.kok, "अँटिगुआ आनी बार्बुडा" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "اؠنٹِگُوا تہٕ باربوڑا" },
				{ LanguageId.ksb, "Antigua na Balbuda" },
				{ LanguageId.ksf, "antiga ri barbúda" },
				{ LanguageId.ksh, "Antigwa un Barbuda" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Антигуа жана Барбуда" },
				{ LanguageId.la, "Antigua et Barbuda" },
				{ LanguageId.lag, "Antigúua na Baribúuda" },
				{ LanguageId.lb, "Antigua a Barbuda" },
				{ LanguageId.lg, "Antigwa ne Barabuda" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Antiga mpé Barbuda" },
				{ LanguageId.lo, "ແອນທິກົວ ແລະ ບາບູດາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Antigva ir Barbuda" },
				{ LanguageId.luo, "Antigua gi Barbuda" },
				{ LanguageId.luy, "Antigua na Barbuda" },
				{ LanguageId.lv, "Antigva un Barbuda" },
				{ LanguageId.mai, "एंटिगुआ आ बारबुडा" },
				{ LanguageId.mas, "Antigua na Barbuda" },
				{ LanguageId.mer, "Antigua na Barbuda" },
				{ LanguageId.mfe, "Antigua-ek-Barbuda" },
				{ LanguageId.mg, "Antiga sy Barboda" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Motu Nehe me Pāputa" },
				{ LanguageId.mk, "Антига и Барбуда" },
				{ LanguageId.ml, "ആൻറിഗ്വയും ബർബുഡയും" },
				{ LanguageId.mn, "Антигуа ба Барбуда" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "अँटिग्वा आणि बर्बुडा" },
				{ LanguageId.ms, "Antigua dan Barbuda" },
				{ LanguageId.mt, "Antigua u Barbuda" },
				{ LanguageId.mua, "antiguan ne Barbuda" },
				{ LanguageId.my, "အန်တီဂွါနှင့် ဘာဘူဒါ" },
				{ LanguageId.mzn, "آنتیگوا و باربودا" },
				{ LanguageId.naq, "Antiguab tsî Barbudab" },
				{ LanguageId.nb, "Antigua og Barbuda" },
				{ LanguageId.nd, "Antigua le Barbuda" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "एन्टिगुआ र बारबुडा" },
				{ LanguageId.nl, "Antigua en Barbuda" },
				{ LanguageId.nmg, "Antíga bá Barbúda" },
				{ LanguageId.nn, "Antigua og Barbuda" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߊ߲ߕߌߞߎߥߊ߫ ߣߌ߫ ߓߊߙߑߓߎߘߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Antiguaa kɛnɛ Barbuda" },
				{ LanguageId.nyn, "Angiguwa na Babuda" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Antiiguyaa fi Barbuudaa" },
				{ LanguageId.or, "ଆଣ୍ଟିଗୁଆ ଏବଂ ବାରବୁଦା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਐਂਟੀਗੁਆ ਅਤੇ ਬਾਰਬੁਡਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Antígwua & Barbúda" },
				{ LanguageId.pl, "Antigua i Barbuda" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "انټيګوا او باربودا" },
				{ LanguageId.pt, "Antígua e Barbuda" },
				{ LanguageId.qu, "Antigua y Barbuda" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Antigua e Barbuda" },
				{ LanguageId.rn, "Antigwa na Baribuda" },
				{ LanguageId.ro, "Antigua și Barbuda" },
				{ LanguageId.rof, "Antigua na Babuda" },
				{ LanguageId.ru, "Антигуа и Барбуда" },
				{ LanguageId.rw, "Antigua na Barbuda" },
				{ LanguageId.rwk, "Antigua na Barbuda" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Antigua na Barbuda" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Anitiguya ni Balubuda" },
				{ LanguageId.sd, "اينٽيگا ۽ باربوڊا" },
				{ LanguageId.se, "Antigua ja Barbuda" },
				{ LanguageId.seh, "Antígua e Barbuda" },
				{ LanguageId.ses, "Antigua nda Barbuuda" },
				{ LanguageId.sg, "Antîgua na Barbûda" },
				{ LanguageId.shi, "ⴰⵏⵜⵉⴳⴰ ⴷ ⴱⵔⴱⵓⴷⴰ" },
				{ LanguageId.si, "ඇන්ටිගුවා සහ බාබියුඩාව" },
				{ LanguageId.sk, "Antigua a Barbuda" },
				{ LanguageId.sl, "Antigva in Barbuda" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Antigua já Barbuda" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Antigua ne Barbuda" },
				{ LanguageId.so, "Antigua & Barbuuda" },
				{ LanguageId.sq, "Antigua e Barbuda" },
				{ LanguageId.sr, "Антигва и Барбуда" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Antigua le Barbuda" },
				{ LanguageId.su, "Antigua jeung Barbuda" },
				{ LanguageId.sv, "Antigua och Barbuda" },
				{ LanguageId.sw, "Antigua na Barbuda" },
				{ LanguageId.syr, "ܐܢܬܝܓܘܐ ܘܒܐܪܒܘܕܐ" },
				{ LanguageId.ta, "ஆண்டிகுவா மற்றும் பார்புடா" },
				{ LanguageId.te, "ఆంటిగ్వా & బార్బుడా" },
				{ LanguageId.teo, "Antigua na Barbuda" },
				{ LanguageId.tg, "Антигуа ва Барбуда" },
				{ LanguageId.th, "แอนติกาและบาร์บูดา" },
				{ LanguageId.ti, "ኣንቲጓን ባርቡዳን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Antigua we Barbuda" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Anitikua mo Palaputa" },
				{ LanguageId.tr, "Antigua ve Barbuda" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Антигуа һәм Барбуда" },
				{ LanguageId.twq, "Antigua nda Barbuuda" },
				{ LanguageId.tzm, "Antigwa d Barbuda" },
				{ LanguageId.ug, "ئانتىگۇئا ۋە باربۇدا" },
				{ LanguageId.uk, "Антигуа і Барбуда" },
				{ LanguageId.ur, "انٹیگوا اور باربودا" },
				{ LanguageId.uz, "Antigua va Barbuda" },
				{ LanguageId.vai, "ꕉꘋꔳꖶꕎ ꗪ ꕑꖜꕜ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Antigua và Barbuda" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Antigua na Barbuda" },
				{ LanguageId.wae, "Antigua und Barbuda" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Antiguwa ak Barbuda" },
				{ LanguageId.xh, "E-Antigua & Barbuda" },
				{ LanguageId.xog, "Antigwa ni Barabuda" },
				{ LanguageId.yav, "Aŋtíka na Palpúta" },
				{ LanguageId.yi, "אַנטיגוע און באַרבודע" },
				{ LanguageId.yo, "Ààntígúà àti Báríbúdà" },
				{ LanguageId.zgh, "ⴰⵏⵜⵉⴳⴰ ⴷ ⴱⵔⴱⵓⴷⴰ" },
				{ LanguageId.zh, "安提瓜和巴布达" },
				{ LanguageId.zu, "i-Antigua ne-Barbuda" },
			}
		);
	}
}
