using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class AN
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "599",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Hollandske Antiller" },
				{ LanguageId.af, "Nederlandse Antille" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኔዘርላንድስ አንቲልስ" },
				{ LanguageId.ar, "جزر الأنتيل الهولندية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Hollandiya Antilləri" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Нідэрландскія Антыльскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Холандски Антили" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "নেদারল্যান্ডস এন্টিলস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Nizozemski Antili" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Antilles Holandeses" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Netherlands Antilles" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Antille Olandesi" },
				{ LanguageId.cs, "Nizozemské Antily" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Antilles yr Iseldiroedd" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Niederländische Antillen" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ολλανδικές Αντίλλες" },
				{ LanguageId.en, "Netherlands Antilles" },
				{ LanguageId.eo, "Nederlandaj Antiloj" },
				{ LanguageId.es, "Antillas Holandesas" },
				{ LanguageId.et, "Hollandi Antillid" },
				{ LanguageId.eu, "Herbehereetako Antillas" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "آنتیل هلند" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Alankomaiden Antillit" },
				{ LanguageId.fil, "Netherlands Antilles" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Antilles néerlandaises" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Nederlânske Antillen" },
				{ LanguageId.ga, "Aintillí na hÍsiltíre" },
				{ LanguageId.gd, "Antilles na h-Òlaind" },
				{ LanguageId.gl, "Antillas Holandesas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "નેધરલેન્ડ એન્ટિલ્સ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Netherlands Antilles" },
				{ LanguageId.haw, "ʻAnelani ʻAnelani" },
				{ LanguageId.he, "האנטילים ההולנדיים" },
				{ LanguageId.hi, "नीदरलैंड्स एंटाइल्स" },
				{ LanguageId.hr, "Nizozemski Antili" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Holland Antillák" },
				{ LanguageId.hy, "Նիդեռլանդական Անտիլներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Antillen Belanda" },
				{ LanguageId.ig, "Antilles nke Netherlands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Hollensku Antillaeyjar" },
				{ LanguageId.it, "Antille Olandesi" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "オランダ領アンティル諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Antillen Walanda" },
				{ LanguageId.ka, "ნიდერლანდების ანტილები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Нидерланд Антильдері" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ហូឡង់ Antilles" },
				{ LanguageId.kn, "ನೆದರ್ಲ್ಯಾಂಡ್ಸ್ ಆಂಟಿಲೀಸ್" },
				{ LanguageId.ko, "네덜란드 령 앤 틸리 스" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Нидерланд Антиль аралдары" },
				{ LanguageId.la, "Antillae Nederlandiae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Holland Antillen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເນເທີແລນ Antilles" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Nyderlandų Antilai" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Nīderlandes Antiļas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Antilles Holandy" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Antilles Hōrana" },
				{ LanguageId.mk, "Холандски Антили" },
				{ LanguageId.ml, "നെതർലാണ്ട് ആന്റിലെസ്" },
				{ LanguageId.mn, "Нидерландын Антилийн арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "नेदरलँड्स अँटिल्स" },
				{ LanguageId.ms, "Antilles Belanda" },
				{ LanguageId.mt, "Antilli Olandiżi" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "နယ်သာလန် အန်တီ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "De nederlandske Antillene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "नेदरल्याण्ड्स एन्टिलेस" },
				{ LanguageId.nl, "Nederlandse Antillen" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ନେଦରଲ୍ୟାଣ୍ଡ ଆଣ୍ଟିଲସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨੀਦਰਲੈਂਡ ਐਂਟੀਲਜ਼" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Antyle Holenderskie" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "هالنډ انټیلیس" },
				{ LanguageId.pt, "Antilhas Holandesas" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Antilele Olandeze" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Нидерландские Антильские острова" },
				{ LanguageId.rw, "Ubuholandi Antilles" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "هالينڊ انٽيليس" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නෙදර්ලන්ත ඇන්ටිලස්" },
				{ LanguageId.sk, "Holandské Antily" },
				{ LanguageId.sl, "Nizozemski Antili" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Netherlands Antilles" },
				{ LanguageId.so, "Netherlands Antilles" },
				{ LanguageId.sq, "Antilet Hollandeze" },
				{ LanguageId.sr, "Холандски Антили" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Antilles ea Netherlands" },
				{ LanguageId.su, "Antillen Walanda" },
				{ LanguageId.sv, "Nederländska Antillerna" },
				{ LanguageId.sw, "Antilles ya Uholanzi" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "நெதர்லாந்து அண்டிலிஸ்" },
				{ LanguageId.te, "నెదర్లాండ్స్ ఆంటిల్లెస్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Антили Нидерланд" },
				{ LanguageId.th, "เนเธอร์แลนด์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Gollandiýa Antilliler" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Hollanda Antilleri" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Нидерланд Антиль" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "گوللاندىيە ئانتىلىس" },
				{ LanguageId.uk, "Нідерландські Антильські острови" },
				{ LanguageId.ur, "نیدرلینڈ اینٹیلز" },
				{ LanguageId.uz, "Niderlandiya Antillari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Antille thuộc Hà Lan" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Netherlands Antilles" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "נעטהערלאַנדס אַנטילס" },
				{ LanguageId.yo, "Netherlands Antilles" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "荷属安的列斯" },
				{ LanguageId.zu, "I-Netherlands Antilles" },
			}
		);
	}
}
