// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class AX
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "358",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Aland Islands" },
				{ LanguageId.da, "Åland" },
				{ LanguageId.af, "Ålandeilande" },
				{ LanguageId.agq, "Aland Islands" },
				{ LanguageId.ak, "Aland Aeland" },
				{ LanguageId.am, "የአላንድ ደሴቶች" },
				{ LanguageId.ar, "جزر آلاند" },
				{ LanguageId.arn, "Aland Islands" },
				{ LanguageId.@as, "আলণ্ড দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Aland Islands" },
				{ LanguageId.ast, "Islles Aland" },
				{ LanguageId.az, "Aland adaları" },
				{ LanguageId.ba, "Аланд утрауҙары" },
				{ LanguageId.bas, "Aland Islands" },
				{ LanguageId.be, "Аландскія астравы" },
				{ LanguageId.bem, "Aland Islands" },
				{ LanguageId.bez, "Aland Islands" },
				{ LanguageId.bg, "Оландски острови" },
				{ LanguageId.bin, "Aland Islands" },
				{ LanguageId.bm, "Aland Islands" },
				{ LanguageId.bn, "অলান্ড দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "ཨ་ལནྡ་གླིང་ཚོམ།" },
				{ LanguageId.br, "Inizi Åland" },
				{ LanguageId.brx, "आलाण्ड द्वीपफोर" },
				{ LanguageId.bs, "Olandska ostrva" },
				{ LanguageId.byn, "Aland Islands" },
				{ LanguageId.ca, "Illes Åland" },
				{ LanguageId.ccp, "𑄃𑄣𑄚𑄴𑄓𑄧 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Аландан гӀайренаш" },
				{ LanguageId.ceb, "Aland Islands" },
				{ LanguageId.cgg, "Aland Islands" },
				{ LanguageId.chr, "ᎣᎴᏅᏓ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی ئالاند" },
				{ LanguageId.co, "Aland Islands" },
				{ LanguageId.cs, "Ålandy" },
				{ LanguageId.cu, "Аландьскꙑ остров" },
				{ LanguageId.cy, "Ynysoedd Åland" },
				{ LanguageId.dav, "Aland Islands" },
				{ LanguageId.de, "Ålandinseln" },
				{ LanguageId.dje, "Aland Islands" },
				{ LanguageId.doi, "Aland Islands" },
				{ LanguageId.dsb, "Åland" },
				{ LanguageId.dua, "Aland Islands" },
				{ LanguageId.dv, "އަލަންޑް ޖަޒީރާތައް" },
				{ LanguageId.dz, "ཨ་ལནཌ་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Aland Islands" },
				{ LanguageId.ee, "Åland ƒudomekpo nutome" },
				{ LanguageId.el, "Νήσοι Όλαντ" },
				{ LanguageId.en, "Åland Islands" },
				{ LanguageId.eo, "Alando" },
				{ LanguageId.es, "Islas Aland" },
				{ LanguageId.et, "Ahvenamaa" },
				{ LanguageId.eu, "Åland" },
				{ LanguageId.ewo, "Aland Islands" },
				{ LanguageId.fa, "جزایر آلاند" },
				{ LanguageId.ff, "Aland Islands" },
				{ LanguageId.fi, "Ahvenanmaa" },
				{ LanguageId.fil, "Åland Islands" },
				{ LanguageId.fo, "Áland" },
				{ LanguageId.fr, "Îles Åland" },
				{ LanguageId.fur, "Isulis Aland" },
				{ LanguageId.fy, "Ålân" },
				{ LanguageId.ga, "Oileáin Åland" },
				{ LanguageId.gd, "Na h-Eileanan Åland" },
				{ LanguageId.gl, "Illas Åland" },
				{ LanguageId.gn, "Aland Islands" },
				{ LanguageId.gsw, "Aaland-Insle" },
				{ LanguageId.gu, "ઑલૅન્ડ આઇલૅન્ડ્સ" },
				{ LanguageId.guz, "Aland Islands" },
				{ LanguageId.gv, "Ellanyn Åland" },
				{ LanguageId.ha, "Tsibirai na Åland" },
				{ LanguageId.haw, "Aland Islands" },
				{ LanguageId.he, "איי אולנד" },
				{ LanguageId.hi, "एलैंड द्वीपसमूह" },
				{ LanguageId.hr, "Ålandski otoci" },
				{ LanguageId.hsb, "Åland" },
				{ LanguageId.hu, "Åland-szigetek" },
				{ LanguageId.hy, "Ալանդյան կղզիներ" },
				{ LanguageId.ia, "Insulas Åland" },
				{ LanguageId.ibb, "Aland Islands" },
				{ LanguageId.id, "Kepulauan Aland" },
				{ LanguageId.ig, "Åland Islands" },
				{ LanguageId.ii, "Aland Islands" },
				{ LanguageId.@is, "Álandseyjar" },
				{ LanguageId.it, "Isole Åland" },
				{ LanguageId.iu, "Aland Islands" },
				{ LanguageId.ja, "オーランド諸島" },
				{ LanguageId.jgo, "Aland Islands" },
				{ LanguageId.jmc, "Aland Islands" },
				{ LanguageId.jv, "Kapuloan Alan" },
				{ LanguageId.ka, "ალანდის კუნძულები" },
				{ LanguageId.kab, "Aland Islands" },
				{ LanguageId.kam, "Aland Islands" },
				{ LanguageId.kde, "Aland Islands" },
				{ LanguageId.kea, "Ilhas Åland" },
				{ LanguageId.khq, "Aland Islands" },
				{ LanguageId.ki, "Aland Islands" },
				{ LanguageId.kk, "Аланд аралдары" },
				{ LanguageId.kkj, "Aland Islands" },
				{ LanguageId.kl, "Åland" },
				{ LanguageId.kln, "Aland Islands" },
				{ LanguageId.km, "កោះ​អាឡង់" },
				{ LanguageId.kn, "ಆಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "올란드 제도" },
				{ LanguageId.kok, "ओलँड जुंवे" },
				{ LanguageId.kr, "Aland Islands" },
				{ LanguageId.ks, "ایلینڑ جٔزیٖرٕ" },
				{ LanguageId.ksb, "Aland Islands" },
				{ LanguageId.ksf, "Aland Islands" },
				{ LanguageId.ksh, "de Ohland-Enselle" },
				{ LanguageId.kw, "Aland Islands" },
				{ LanguageId.ky, "Аланд аралдары" },
				{ LanguageId.la, "Insulae Alandiae" },
				{ LanguageId.lag, "Aland Islands" },
				{ LanguageId.lb, "Ålandinselen" },
				{ LanguageId.lg, "Aland Islands" },
				{ LanguageId.lkt, "Aland Islands" },
				{ LanguageId.ln, "Aland Islands" },
				{ LanguageId.lo, "ຫມູ່ເກາະໂອລັນ" },
				{ LanguageId.lrc, "Aland Islands" },
				{ LanguageId.lt, "Alandų Salos" },
				{ LanguageId.luo, "Aland Islands" },
				{ LanguageId.luy, "Aland Islands" },
				{ LanguageId.lv, "Olandes salas" },
				{ LanguageId.mai, "अलैंड द्वीपसमूह" },
				{ LanguageId.mas, "Aland Islands" },
				{ LanguageId.mer, "Aland Islands" },
				{ LanguageId.mfe, "Aland Islands" },
				{ LanguageId.mg, "Nosy Aland" },
				{ LanguageId.mgo, "Aland Islands" },
				{ LanguageId.mi, "Motu Ōrana" },
				{ LanguageId.mk, "Оландски Острови" },
				{ LanguageId.ml, "അലൻഡ് ദ്വീപുകൾ" },
				{ LanguageId.mn, "Аландын арлууд" },
				{ LanguageId.mni, "Aland Islands" },
				{ LanguageId.moh, "Aland Islands" },
				{ LanguageId.mr, "अ‍ॅलँड बेटे" },
				{ LanguageId.ms, "Kepulauan Aland" },
				{ LanguageId.mt, "il-Gżejjer Aland" },
				{ LanguageId.mua, "Aland Islands" },
				{ LanguageId.my, "အာလန်ကျွန်း" },
				{ LanguageId.mzn, "آلند جزیره" },
				{ LanguageId.naq, "Aland Islands" },
				{ LanguageId.nb, "Åland" },
				{ LanguageId.nd, "Aland Islands" },
				{ LanguageId.nds, "Åland" },
				{ LanguageId.ne, "अलान्ड टापुहरु" },
				{ LanguageId.nl, "Åland" },
				{ LanguageId.nmg, "Aland Islands" },
				{ LanguageId.nn, "Åland" },
				{ LanguageId.nnh, "Aland Islands" },
				{ LanguageId.nqo, "ߊߟߊ߲ߘ ߕߌ߲" },
				{ LanguageId.nr, "Aland Islands" },
				{ LanguageId.nso, "Aland Islands" },
				{ LanguageId.nus, "Aland Islands" },
				{ LanguageId.nyn, "Aland Islands" },
				{ LanguageId.oc, "Illas Åland" },
				{ LanguageId.om, "Odoloota Alaand" },
				{ LanguageId.or, "ଅଲାଣ୍ଡ ଦ୍ଵୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "Аландаг сакъадæхтæ" },
				{ LanguageId.pa, "ਅਲੈਂਡ ਟਾਪੂ" },
				{ LanguageId.pap, "Aland Islands" },
				{ LanguageId.pcm, "Ọ́lánd Aílands" },
				{ LanguageId.pl, "Wyspy Alandzkie" },
				{ LanguageId.prg, "Aland Islands" },
				{ LanguageId.ps, "الاند ټاپوان" },
				{ LanguageId.pt, "Ilhas Aland" },
				{ LanguageId.qu, "Islas Åland" },
				{ LanguageId.quc, "Aland Islands" },
				{ LanguageId.rm, "Inslas Aland" },
				{ LanguageId.rn, "Ibirwa bya Åland" },
				{ LanguageId.ro, "Insulele Åland" },
				{ LanguageId.rof, "Aland Islands" },
				{ LanguageId.ru, "Аландские о-ва" },
				{ LanguageId.rw, "Ibirwa bya Åland" },
				{ LanguageId.rwk, "Aland Islands" },
				{ LanguageId.sa, "आलैंड द्वीपसमूह" },
				{ LanguageId.sah, "Аланд арыылара" },
				{ LanguageId.saq, "Aland Islands" },
				{ LanguageId.sat, "Aland Islands" },
				{ LanguageId.sbp, "Aland Islands" },
				{ LanguageId.sd, "الند ٻيٽ" },
				{ LanguageId.se, "Ålánda" },
				{ LanguageId.seh, "Aland Islands" },
				{ LanguageId.ses, "Aland Islands" },
				{ LanguageId.sg, "Aland Islands" },
				{ LanguageId.shi, "Aland Islands" },
				{ LanguageId.si, "ඕලන්ඩ් දූපත්" },
				{ LanguageId.sk, "Alandy" },
				{ LanguageId.sl, "Alandski otoki" },
				{ LanguageId.sma, "Åland" },
				{ LanguageId.smj, "Åland" },
				{ LanguageId.smn, "Vuáskueennâm" },
				{ LanguageId.sms, "Åland" },
				{ LanguageId.sn, "Aland Islands" },
				{ LanguageId.so, "Jasiiradda Aland" },
				{ LanguageId.sq, "Ishujt Alandë" },
				{ LanguageId.sr, "Оландска Острва" },
				{ LanguageId.ss, "Aland Islands" },
				{ LanguageId.ssy, "Aland Islands" },
				{ LanguageId.st, "Aland Islands" },
				{ LanguageId.su, "Kapuloan Åland" },
				{ LanguageId.sv, "Åland" },
				{ LanguageId.sw, "Visiwa vya Aland" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܐܠܐܢܕ" },
				{ LanguageId.ta, "ஆலந்து தீவுகள்" },
				{ LanguageId.te, "ఆలాండ్ దీవులు" },
				{ LanguageId.teo, "Aland Islands" },
				{ LanguageId.tg, "Ҷазираҳои Аланд" },
				{ LanguageId.th, "หมู่เกาะโอลันด์" },
				{ LanguageId.ti, "ደሴታት ኣላንድ" },
				{ LanguageId.tig, "Aland Islands" },
				{ LanguageId.tk, "Aland adalary" },
				{ LanguageId.tn, "Aland Islands" },
				{ LanguageId.to, "ʻOtumotu ʻAlani" },
				{ LanguageId.tr, "Åland Adaları" },
				{ LanguageId.ts, "Aland Islands" },
				{ LanguageId.tt, "Аланд утраулары" },
				{ LanguageId.twq, "Aland Islands" },
				{ LanguageId.tzm, "Aland Islands" },
				{ LanguageId.ug, "ئالاند ئاراللىرى" },
				{ LanguageId.uk, "Аландські Острови" },
				{ LanguageId.ur, "آلینڈ آئلینڈز" },
				{ LanguageId.uz, "Aland orollari" },
				{ LanguageId.vai, "ꕉꕞꔺ" },
				{ LanguageId.ve, "Aland Islands" },
				{ LanguageId.vi, "Quần đảo Åland" },
				{ LanguageId.vo, "Älandäns" },
				{ LanguageId.vun, "Aland Islands" },
				{ LanguageId.wae, "Alandinslä" },
				{ LanguageId.wal, "Aland Islands" },
				{ LanguageId.wo, "Duni Aalànd" },
				{ LanguageId.xh, "E-Åland Islands" },
				{ LanguageId.xog, "Aland Islands" },
				{ LanguageId.yav, "Aland Islands" },
				{ LanguageId.yi, "אלאנד אינדזלען" },
				{ LanguageId.yo, "Àwọn Erékùsù ti Aland" },
				{ LanguageId.zgh, "Aland Islands" },
				{ LanguageId.zh, "奥兰群岛" },
				{ LanguageId.zu, "i-Åland Islands" },
			}
		);
	}
}
