using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class AX
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "358",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Aland Islands" },
				{ LanguageId.da, "Åland" },
				{ LanguageId.af, "Åland" },
				{ LanguageId.agq, "Aland Islands" },
				{ LanguageId.ak, "Aland Islands" },
				{ LanguageId.am, "የአላንድ ደሴቶች" },
				{ LanguageId.ar, "جزر أولاند" },
				{ LanguageId.arn, "Aland Islands" },
				{ LanguageId.@as, "এলেণ্ড দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Aland Islands" },
				{ LanguageId.ast, "Aland Islands" },
				{ LanguageId.az, "Aland" },
				{ LanguageId.ba, "Аландскія астравы" },
				{ LanguageId.bas, "Aland Islands" },
				{ LanguageId.be, "Аландскія астравы" },
				{ LanguageId.bem, "Aland Islands" },
				{ LanguageId.bez, "Aland Islands" },
				{ LanguageId.bg, "Оландски острови" },
				{ LanguageId.bin, "Aland Islands" },
				{ LanguageId.bm, "Aland Islands" },
				{ LanguageId.bn, "অল্যান্ড দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "ཨ་ལནྡ་གླིང་ཚོམ།" },
				{ LanguageId.br, "Åland" },
				{ LanguageId.brx, "Aland Islands" },
				{ LanguageId.bs, "Olandska ostrva" },
				{ LanguageId.byn, "Aland Islands" },
				{ LanguageId.ca, "Illes Åland" },
				{ LanguageId.ccp, "Aland Islands" },
				{ LanguageId.ce, "Аланд гІайреш" },
				{ LanguageId.ceb, "Aland Islands" },
				{ LanguageId.cgg, "Aland Islands" },
				{ LanguageId.chr, "Aland Islands" },
				{ LanguageId.ckb, "دوورگەکانی ئالاند" },
				{ LanguageId.co, "Aland Islands" },
				{ LanguageId.cs, "Ålandy" },
				{ LanguageId.cu, "Аландьскꙑ остров" },
				{ LanguageId.cy, "Ynysoedd Åland" },
				{ LanguageId.dav, "Aland Islands" },
				{ LanguageId.de, "Åland" },
				{ LanguageId.dje, "Aland Islands" },
				{ LanguageId.doi, "Aland Islands" },
				{ LanguageId.dsb, "Ålandske kupy" },
				{ LanguageId.dua, "Aland Islands" },
				{ LanguageId.dv, "އަލަންޑް ޖަޒީރާތައް" },
				{ LanguageId.dz, "ཨ་ལནྡ་གླིང་ཚོམ།" },
				{ LanguageId.ebu, "Aland Islands" },
				{ LanguageId.ee, "Aland Islands" },
				{ LanguageId.el, "Νήσοι Ώλαντ" },
				{ LanguageId.en, "Aland Islands" },
				{ LanguageId.eo, "Alando" },
				{ LanguageId.es, "Alandia" },
				{ LanguageId.et, "Ahvenamaa" },
				{ LanguageId.eu, "Åland" },
				{ LanguageId.ewo, "Aland Islands" },
				{ LanguageId.fa, "جزایر الند" },
				{ LanguageId.ff, "Aland Islands" },
				{ LanguageId.fi, "Ahvenanmaa" },
				{ LanguageId.fil, "Aland Islands" },
				{ LanguageId.fo, "Áland" },
				{ LanguageId.fr, "Îles Åland" },
				{ LanguageId.fur, "Aland Islands" },
				{ LanguageId.fy, "Ålaneilân" },
				{ LanguageId.ga, "Oileáin Åland" },
				{ LanguageId.gd, "Eileanan Åland" },
				{ LanguageId.gl, "Illas Åland" },
				{ LanguageId.gn, "Aland Islands" },
				{ LanguageId.gsw, "Åland" },
				{ LanguageId.gu, "અલેન્ડ ટાપુઓ" },
				{ LanguageId.guz, "Aland Islands" },
				{ LanguageId.gv, "Ellanyn Åland" },
				{ LanguageId.ha, "Aland Islands" },
				{ LanguageId.haw, "Aland Islands" },
				{ LanguageId.he, "איי אולנד" },
				{ LanguageId.hi, "ऑलैंड द्वीपसमूह" },
				{ LanguageId.hr, "Ålandski otoci" },
				{ LanguageId.hsb, "Ålandske kupy" },
				{ LanguageId.hu, "Åland-szigetek" },
				{ LanguageId.hy, "Ալանդյան կղզիներ" },
				{ LanguageId.ia, "Insulas Åland" },
				{ LanguageId.ibb, "Aland Islands" },
				{ LanguageId.id, "Kepulauan Åland" },
				{ LanguageId.ig, "Aland Islands" },
				{ LanguageId.ii, "Aland Islands" },
				{ LanguageId.@is, "Álandseyjar" },
				{ LanguageId.it, "Isole Aland" },
				{ LanguageId.iu, "Aland Islands" },
				{ LanguageId.ja, "オーランド" },
				{ LanguageId.jgo, "Aland Islands" },
				{ LanguageId.jmc, "Aland Islands" },
				{ LanguageId.jv, "Kapuloan Åland" },
				{ LanguageId.ka, "ალანდის კუნძულები" },
				{ LanguageId.kab, "Aland Islands" },
				{ LanguageId.kam, "Aland Islands" },
				{ LanguageId.kde, "Aland Islands" },
				{ LanguageId.kea, "Aland Islands" },
				{ LanguageId.khq, "Aland Islands" },
				{ LanguageId.ki, "Aland Islands" },
				{ LanguageId.kk, "Аланд аралдары" },
				{ LanguageId.kkj, "Aland Islands" },
				{ LanguageId.kl, "Åland" },
				{ LanguageId.kln, "Aland Islands" },
				{ LanguageId.km, "កោះអាឡង់" },
				{ LanguageId.kn, "ಆಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "올란드 제도" },
				{ LanguageId.kok, "ओलँड बेटां" },
				{ LanguageId.kr, "Aland Islands" },
				{ LanguageId.ks, "الینڈ جٔزیرٕ" },
				{ LanguageId.ksb, "Aland Islands" },
				{ LanguageId.ksf, "Aland Islands" },
				{ LanguageId.ksh, "Aland Islands" },
				{ LanguageId.kw, "Aland Islands" },
				{ LanguageId.ky, "Аланд аралдары" },
				{ LanguageId.la, "Insulae Alandiae" },
				{ LanguageId.lag, "Aland Islands" },
				{ LanguageId.lb, "Ålandinselen" },
				{ LanguageId.lg, "Aland Islands" },
				{ LanguageId.lkt, "Aland Islands" },
				{ LanguageId.ln, "Aland Islands" },
				{ LanguageId.lo, "ໝູ່ເກາະອາລັນ" },
				{ LanguageId.lrc, "Aland Islands" },
				{ LanguageId.lt, "Alandų salos" },
				{ LanguageId.luo, "Aland Islands" },
				{ LanguageId.luy, "Aland Islands" },
				{ LanguageId.lv, "Olandes salas" },
				{ LanguageId.mai, "ओलान्द द्वीपसमूह" },
				{ LanguageId.mas, "Aland Islands" },
				{ LanguageId.mer, "Aland Islands" },
				{ LanguageId.mfe, "Aland Islands" },
				{ LanguageId.mg, "Nosy Aland" },
				{ LanguageId.mgo, "Aland Islands" },
				{ LanguageId.mi, "Aland Islands" },
				{ LanguageId.mk, "Оландски Острови" },
				{ LanguageId.ml, "ഓളൻഡ് ദ്വീപുകൾ" },
				{ LanguageId.mn, "Аландын арлууд" },
				{ LanguageId.mni, "Aland Islands" },
				{ LanguageId.moh, "Aland Islands" },
				{ LanguageId.mr, "ऑलँड बेटे" },
				{ LanguageId.ms, "Kepulauan Åland" },
				{ LanguageId.mt, "Gżejjer Åland" },
				{ LanguageId.mua, "Aland Islands" },
				{ LanguageId.my, "အလန်းကျွန်းစု" },
				{ LanguageId.mzn, "آلند جزیره‌ئون" },
				{ LanguageId.naq, "Aland Islands" },
				{ LanguageId.nb, "Åland" },
				{ LanguageId.nd, "Aland Islands" },
				{ LanguageId.nds, "Åland" },
				{ LanguageId.ne, "ओलान्ड टापुहरू" },
				{ LanguageId.nl, "Ålandeilanden" },
				{ LanguageId.nmg, "Aland Islands" },
				{ LanguageId.nn, "Åland" },
				{ LanguageId.nnh, "Aland Islands" },
				{ LanguageId.nqo, "Aland Islands" },
				{ LanguageId.nr, "Aland Islands" },
				{ LanguageId.nso, "Aland Islands" },
				{ LanguageId.nus, "Aland Islands" },
				{ LanguageId.nyn, "Aland Islands" },
				{ LanguageId.oc, "Illas Åland" },
				{ LanguageId.om, "Aland Islands" },
				{ LanguageId.or, "ଆଲାଣ୍ଡ ଦ୍ଵୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "Аландаг сакъадæхтæ" },
				{ LanguageId.pa, "ਅਲੈਂਡ ਟਾਪੂ" },
				{ LanguageId.pap, "Aland Islands" },
				{ LanguageId.pcm, "Aland Islands" },
				{ LanguageId.pl, "Wyspy Alandzkie" },
				{ LanguageId.prg, "Aland Islands" },
				{ LanguageId.ps, "د آلند ټاپوګان" },
				{ LanguageId.pt, "Alândia" },
				{ LanguageId.qu, "Aland Islands" },
				{ LanguageId.quc, "Aland Islands" },
				{ LanguageId.rm, "Inslas Åland" },
				{ LanguageId.rn, "Ibirwa bya Åland" },
				{ LanguageId.ro, "Insulele Åland" },
				{ LanguageId.rof, "Aland Islands" },
				{ LanguageId.ru, "Аландские острова" },
				{ LanguageId.rw, "Ibirwa bya Åland" },
				{ LanguageId.rwk, "Aland Islands" },
				{ LanguageId.sa, "आलैंड द्वीपसमूह" },
				{ LanguageId.sah, "Аланд арыылара" },
				{ LanguageId.saq, "Aland Islands" },
				{ LanguageId.sat, "Aland Islands" },
				{ LanguageId.sbp, "Aland Islands" },
				{ LanguageId.sd, "آلنڊ ٻيٽ" },
				{ LanguageId.se, "Åland" },
				{ LanguageId.seh, "Aland Islands" },
				{ LanguageId.ses, "Aland Islands" },
				{ LanguageId.sg, "Aland Islands" },
				{ LanguageId.shi, "Aland Islands" },
				{ LanguageId.si, "ඕලන්ඩ් දූපත්" },
				{ LanguageId.sk, "Alandy" },
				{ LanguageId.sl, "Ålandski otoki" },
				{ LanguageId.sma, "Åland" },
				{ LanguageId.smj, "Åland" },
				{ LanguageId.smn, "Åland" },
				{ LanguageId.sms, "Åland" },
				{ LanguageId.sn, "Aland Islands" },
				{ LanguageId.so, "Jasiiradaha Åland" },
				{ LanguageId.sq, "Ishujt Åland" },
				{ LanguageId.sr, "Olandska Ostrva" },
				{ LanguageId.ss, "Aland Islands" },
				{ LanguageId.ssy, "Aland Islands" },
				{ LanguageId.st, "Aland Islands" },
				{ LanguageId.su, "Kapuloan Åland" },
				{ LanguageId.sv, "Åland" },
				{ LanguageId.sw, "Visiwa vya Åland" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܐܠܢܕ" },
				{ LanguageId.ta, "ஆலந்து தீவுகள்" },
				{ LanguageId.te, "ఆలాండ్ దీవులు" },
				{ LanguageId.teo, "Aland Islands" },
				{ LanguageId.tg, "Ҷазираҳои Аланд" },
				{ LanguageId.th, "หมู่เกาะโอลันด์" },
				{ LanguageId.ti, "የአላንድ ደሴቶች" },
				{ LanguageId.tig, "Aland Islands" },
				{ LanguageId.tk, "Aland adalary" },
				{ LanguageId.tn, "Aland Islands" },
				{ LanguageId.to, "Aland Islands" },
				{ LanguageId.tr, "Åland" },
				{ LanguageId.ts, "Aland Islands" },
				{ LanguageId.tt, "Аланд утраулары" },
				{ LanguageId.twq, "Aland Islands" },
				{ LanguageId.tzm, "Aland Islands" },
				{ LanguageId.ug, "ئالاند ئاراللىرى" },
				{ LanguageId.uk, "Аландські острови" },
				{ LanguageId.ur, "جزائر اولند" },
				{ LanguageId.uz, "Aland orollari" },
				{ LanguageId.vai, "Aland Islands" },
				{ LanguageId.ve, "Aland Islands" },
				{ LanguageId.vi, "Quần đảo Åland" },
				{ LanguageId.vo, "Älandäns" },
				{ LanguageId.vun, "Aland Islands" },
				{ LanguageId.wae, "Åland" },
				{ LanguageId.wal, "Aland Islands" },
				{ LanguageId.wo, "Aland Islands" },
				{ LanguageId.xh, "Aland Islands" },
				{ LanguageId.xog, "Aland Islands" },
				{ LanguageId.yav, "Aland Islands" },
				{ LanguageId.yi, "אלאנד אינדזלען" },
				{ LanguageId.yo, "Aland Islands" },
				{ LanguageId.zgh, "Aland Islands" },
				{ LanguageId.zh, "奥兰群岛" },
				{ LanguageId.zu, "Aland Islands" },
			}
		);
	}
}
