// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BA
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "387",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Bosnia and Herzegovina" },
				{ LanguageId.da, "Bosnien-Hercegovina" },
				{ LanguageId.af, "Bosnië en Herzegowina" },
				{ LanguageId.agq, "Bosɨnyìa à Hɛ̀zɛ̀gòvinà" },
				{ LanguageId.ak, "Bosnia ne Hɛzegovina" },
				{ LanguageId.am, "ቦስኒያ እና ሄርዞጎቪኒያ" },
				{ LanguageId.ar, "البوسنة والهرسك" },
				{ LanguageId.arn, "Bosnia and Herzegovina" },
				{ LanguageId.@as, "ব’ছনিয়া আৰু হাৰ্জেগ’ভিনা" },
				{ LanguageId.asa, "Bothnia na Hedhegovina" },
				{ LanguageId.ast, "Bosnia y Herzegovina" },
				{ LanguageId.az, "Bosniya və Herseqovina" },
				{ LanguageId.ba, "Босния һәм Герцеговина" },
				{ LanguageId.bas, "Bòhnià Ɛrzègòvinà" },
				{ LanguageId.be, "Боснія і Герцагавіна" },
				{ LanguageId.bem, "Bosnia and Herzegovina" },
				{ LanguageId.bez, "Hubosinia na Huhezegovina" },
				{ LanguageId.bg, "Босна и Херцеговина" },
				{ LanguageId.bin, "Bosnia and Herzegovina" },
				{ LanguageId.bm, "Bozni-Ɛrizigovini" },
				{ LanguageId.bn, "বসনিয়া ও হার্জেগোভিনা" },
				{ LanguageId.bo, "བྷོསྣིཡ་དང་ཧར་ཛི་གོ་ཝི་ན།" },
				{ LanguageId.br, "Bosnia-ha-Herzegovina" },
				{ LanguageId.brx, "बसनिया आरो होर्जेगभिना" },
				{ LanguageId.bs, "Bosna i Hercegovina" },
				{ LanguageId.byn, "Bosnia and Herzegovina" },
				{ LanguageId.ca, "Bòsnia i Hercegovina" },
				{ LanguageId.ccp, "𑄝𑄧𑄥𑄴𑄚𑄨𑄠 𑄃𑄮 𑄦𑄢𑄴𑄎𑄬𑄉𑄮𑄞𑄨𑄚" },
				{ LanguageId.ce, "Босни а, Герцеговина а" },
				{ LanguageId.ceb, "Bosnia & Herzegovina" },
				{ LanguageId.cgg, "Boziniya na Hezegovina" },
				{ LanguageId.chr, "ᏉᏏᏂᎠ & ᎲᏤᎪᏫᎾ" },
				{ LanguageId.ckb, "بۆسنیا و ھەرزەگۆڤینا" },
				{ LanguageId.co, "Bosnia e Erzegovina" },
				{ LanguageId.cs, "Bosna a Hercegovina" },
				{ LanguageId.cu, "Босна и Херцеговина" },
				{ LanguageId.cy, "Bosnia a Herzegovina" },
				{ LanguageId.dav, "Bosnia na Hezegovina" },
				{ LanguageId.de, "Bosnien und Herzegowina" },
				{ LanguageId.dje, "Bosni nda Herzegovine" },
				{ LanguageId.doi, "Bosnia and Herzegovina" },
				{ LanguageId.dsb, "Bosniska a Hercegowina" },
				{ LanguageId.dua, "Bosnia and Herzegovina" },
				{ LanguageId.dv, "ބޮސްނިޔާ އަދި ހަރުޒޮގްވީނާ" },
				{ LanguageId.dz, "བྷོས་ནི་ཡ་ ཨེནཌ་ ཧར་ཛི་གྷོ་བི་ན" },
				{ LanguageId.ebu, "Bosnia na Hezegovina" },
				{ LanguageId.ee, "Bosnia kple Herzergovina nutome" },
				{ LanguageId.el, "Βοσνία - Ερζεγοβίνη" },
				{ LanguageId.en, "Bosnia & Herzegovina" },
				{ LanguageId.eo, "Bosnujo kaj Hercegovino" },
				{ LanguageId.es, "Bosnia y Herzegovina" },
				{ LanguageId.et, "Bosnia ja Hertsegoviina" },
				{ LanguageId.eu, "Bosnia-Herzegovina" },
				{ LanguageId.ewo, "Bosəní ai ɛrəzegovín" },
				{ LanguageId.fa, "بوسنی و هرزگوین" },
				{ LanguageId.ff, "Bosnii Hersegowiin" },
				{ LanguageId.fi, "Bosnia ja Hertsegovina" },
				{ LanguageId.fil, "Bosnia and Herzegovina" },
				{ LanguageId.fo, "Bosnia-Hersegovina" },
				{ LanguageId.fr, "Bosnie-Herzégovine" },
				{ LanguageId.fur, "Bosnie e Ercegovine" },
				{ LanguageId.fy, "Bosnië en Herzegovina" },
				{ LanguageId.ga, "an Bhoisnia agus an Heirseagaivéin" },
				{ LanguageId.gd, "Bosna is Hearsagobhana" },
				{ LanguageId.gl, "Bosnia e Hercegovina" },
				{ LanguageId.gn, "Bosnia and Herzegovina" },
				{ LanguageId.gsw, "Bosnie und Herzegowina" },
				{ LanguageId.gu, "બોસ્નિયા અને હર્ઝેગોવિના" },
				{ LanguageId.guz, "Bosnia na Hezegovina" },
				{ LanguageId.gv, "Bosnia as Herzegovina" },
				{ LanguageId.ha, "Bosniya da Harzagobina" },
				{ LanguageId.haw, "Bosenia me Hesegowina" },
				{ LanguageId.he, "בוסניה והרצגובינה" },
				{ LanguageId.hi, "बोस्निया और हर्ज़ेगोविना" },
				{ LanguageId.hr, "Bosna i Hercegovina" },
				{ LanguageId.hsb, "Bosniska a Hercegowina" },
				{ LanguageId.hu, "Bosznia-Hercegovina" },
				{ LanguageId.hy, "Բոսնիա և Հերցեգովինա" },
				{ LanguageId.ia, "Bosnia e Herzegovina" },
				{ LanguageId.ibb, "Bosnia and Herzegovina" },
				{ LanguageId.id, "Bosnia dan Herzegovina" },
				{ LanguageId.ig, "Bosnia & Herzegovina" },
				{ LanguageId.ii, "Bosnia and Herzegovina" },
				{ LanguageId.@is, "Bosnía og Hersegóvína" },
				{ LanguageId.it, "Bosnia ed Erzegovina" },
				{ LanguageId.iu, "Bosnia and Herzegovina" },
				{ LanguageId.ja, "ボスニア・ヘルツェゴビナ" },
				{ LanguageId.jgo, "Bosnia and Herzegovina" },
				{ LanguageId.jmc, "Bosnia na Hezegovina" },
				{ LanguageId.jv, "Bosnia lan Hèrségovina" },
				{ LanguageId.ka, "ბოსნია და ჰერცეგოვინა" },
				{ LanguageId.kab, "Busna d Hersek" },
				{ LanguageId.kam, "Bosnia na Hezegovina" },
				{ LanguageId.kde, "Bosnia na Hezegovina" },
				{ LanguageId.kea, "Bósnia i Erzegovina" },
				{ LanguageId.khq, "Bosni nda Herzegovine" },
				{ LanguageId.ki, "Bosnia na Hezegovina" },
				{ LanguageId.kk, "Босния және Герцеговина" },
				{ LanguageId.kkj, "Bosnia and Herzegovina" },
				{ LanguageId.kl, "Bosnia-Hercegovina" },
				{ LanguageId.kln, "Emetab Bosnia ak Herzegovina" },
				{ LanguageId.km, "បូស្ន៊ី និងហឺហ្ស៊ីហ្គូវីណា" },
				{ LanguageId.kn, "ಬೋಸ್ನಿಯಾ ಮತ್ತು ಹರ್ಜೆಗೋವಿನಾ" },
				{ LanguageId.ko, "보스니아 헤르체고비나" },
				{ LanguageId.kok, "बॉस्निया आनी हर्जेगोविना" },
				{ LanguageId.kr, "Bosnia and Herzegovina" },
				{ LanguageId.ks, "بوسنِیا تہٕ ہَرزِگووِنا" },
				{ LanguageId.ksb, "Bosnia na Hezegovina" },
				{ LanguageId.ksf, "bɔsnyɛ ri hɛrsǝgɔvín" },
				{ LanguageId.ksh, "Boßnije un Herzegovina" },
				{ LanguageId.kw, "Bosnia and Herzegovina" },
				{ LanguageId.ky, "Босния жана Герцеговина" },
				{ LanguageId.la, "Bosnia et Herzegovina" },
				{ LanguageId.lag, "Bósinia" },
				{ LanguageId.lb, "Bosnien an Herzegowina" },
				{ LanguageId.lg, "Boziniya Hezegovina" },
				{ LanguageId.lkt, "Bosnia and Herzegovina" },
				{ LanguageId.ln, "Bosini mpé Hezegovine" },
				{ LanguageId.lo, "ບອດສະເນຍ ແລະ ແຮສໂກວີນາ" },
				{ LanguageId.lrc, "بوسنی و هرزگوین" },
				{ LanguageId.lt, "Bosnija ir Hercegovina" },
				{ LanguageId.luo, "Bosnia gi Herzegovina" },
				{ LanguageId.luy, "Bosnia na Hezegovina" },
				{ LanguageId.lv, "Bosnija un Hercegovina" },
				{ LanguageId.mai, "बोस्निया आ हर्जेगोबिना" },
				{ LanguageId.mas, "Bosnia na Hezegovina" },
				{ LanguageId.mer, "Bosnia na Hezegovina" },
				{ LanguageId.mfe, "Bosni-Herzegovinn" },
				{ LanguageId.mg, "Bosnia sy Herzegovina" },
				{ LanguageId.mgo, "Bosnia and Herzegovina" },
				{ LanguageId.mi, "Pōngia & Herekōwini" },
				{ LanguageId.mk, "Босна и Херцеговина" },
				{ LanguageId.ml, "ബോസ്നിയയും ഹെർസഗോവിനയും" },
				{ LanguageId.mn, "Босни-Херцеговин" },
				{ LanguageId.mni, "Bosnia and Herzegovina" },
				{ LanguageId.moh, "Bosnia and Herzegovina" },
				{ LanguageId.mr, "बोस्निया अणि हर्जेगोविना" },
				{ LanguageId.ms, "Bosnia dan Herzegovina" },
				{ LanguageId.mt, "il-Bożnija-Ħerzegovina" },
				{ LanguageId.mua, "bosniya ne Herzegovina" },
				{ LanguageId.my, "ဘော့စနီးယားနှင့် ဟာဇီဂိုဗီနား" },
				{ LanguageId.mzn, "بوسنی و هرزگوین" },
				{ LanguageId.naq, "Bosniab tsî Herzegovinab" },
				{ LanguageId.nb, "Bosnia-Hercegovina" },
				{ LanguageId.nd, "Bhosnia le Herzegovina" },
				{ LanguageId.nds, "Bosnien-Herzegowina" },
				{ LanguageId.ne, "बोस्निया एण्ड हर्जगोभिनिया" },
				{ LanguageId.nl, "Bosnië en Herzegovina" },
				{ LanguageId.nmg, "Bosnia na Ɛrzegovina" },
				{ LanguageId.nn, "Bosnia-Hercegovina" },
				{ LanguageId.nnh, "Bosnia and Herzegovina" },
				{ LanguageId.nqo, "ߓߐߛߑߣߌ߫-ߍߙߑߖ߭ߋߜ߭ߏߝ߭ߌߣ" },
				{ LanguageId.nr, "Bosnia and Herzegovina" },
				{ LanguageId.nso, "Bosnia and Herzegovina" },
				{ LanguageId.nus, "Bothnia kɛnɛ ɣärgobinia" },
				{ LanguageId.nyn, "Boziniya na Hezegovina" },
				{ LanguageId.oc, "Bòsnia e Hertsegovina" },
				{ LanguageId.om, "Bosiiniyaa fi Herzoogovinaa" },
				{ LanguageId.or, "ବୋସନିଆ ଏବଂ ହର୍ଜଗୋଭିନା" },
				{ LanguageId.os, "Босни æмæ Герцеговинæ" },
				{ LanguageId.pa, "ਬੋਸਨੀਆ ਅਤੇ ਹਰਜ਼ੇਗੋਵੀਨਾ" },
				{ LanguageId.pap, "Bosnia and Herzegovina" },
				{ LanguageId.pcm, "Bọ́zniá & Hẹzẹgovína" },
				{ LanguageId.pl, "Bośnia i Hercegowina" },
				{ LanguageId.prg, "Bosnia and Herzegovina" },
				{ LanguageId.ps, "بوسنيا او هېرزګوينا" },
				{ LanguageId.pt, "Bósnia e Herzegovina" },
				{ LanguageId.qu, "Bosnia y Herzegovina" },
				{ LanguageId.quc, "Bosnia and Herzegovina" },
				{ LanguageId.rm, "Bosnia ed Erzegovina" },
				{ LanguageId.rn, "Bosiniya na Herigozevine" },
				{ LanguageId.ro, "Bosnia și Herțegovina" },
				{ LanguageId.rof, "Bosnia na Hezegovina" },
				{ LanguageId.ru, "Босния и Герцеговина" },
				{ LanguageId.rw, "Bosiniya na Herzegovina" },
				{ LanguageId.rwk, "Bosnia na Hezegovina" },
				{ LanguageId.sa, "बोस्निया हर्जेगोविना" },
				{ LanguageId.sah, "Босния уонна Герцеговина" },
				{ LanguageId.saq, "Bosnia na Hezegovina" },
				{ LanguageId.sat, "Bosnia and Herzegovina" },
				{ LanguageId.sbp, "Bosiniya ni Hesegovina" },
				{ LanguageId.sd, "بوسنيا ۽ هرزيگووينا" },
				{ LanguageId.se, "Bosnia-Hercegovina" },
				{ LanguageId.seh, "Bósnia-Herzegovina" },
				{ LanguageId.ses, "Bosni nda Herzegovine" },
				{ LanguageId.sg, "Bosnïi na Herzegovînni" },
				{ LanguageId.shi, "ⴱⵓⵙⵏⴰ ⴷ ⵀⵉⵔⵙⵉⴽ" },
				{ LanguageId.si, "බොස්නියාව සහ හර්සගොවීනාව" },
				{ LanguageId.sk, "Bosna a Hercegovina" },
				{ LanguageId.sl, "Bosna in Hercegovina" },
				{ LanguageId.sma, "Bosnia-Hercegovina" },
				{ LanguageId.smj, "Bosnia-Hercegovina" },
				{ LanguageId.smn, "Bosnia já Herzegovina" },
				{ LanguageId.sms, "Bosnia-Hercegovina" },
				{ LanguageId.sn, "Boznia ne Herzegovina" },
				{ LanguageId.so, "Boosniya & Harsegofina" },
				{ LanguageId.sq, "Bosnjë-Hercegovinë" },
				{ LanguageId.sr, "Босна и Херцеговина" },
				{ LanguageId.ss, "Bosnia and Herzegovina" },
				{ LanguageId.ssy, "Bosnia and Herzegovina" },
				{ LanguageId.st, "Bosnia le Herzegovina" },
				{ LanguageId.su, "Bosnia jeung Hérzégovina" },
				{ LanguageId.sv, "Bosnien och Hercegovina" },
				{ LanguageId.sw, "Bosnia na Hezegovina" },
				{ LanguageId.syr, "ܒܘܣܢܐ ܘܗܪܬܣܓܘܒܝܢܐ" },
				{ LanguageId.ta, "போஸ்னியா & ஹெர்ஸகோவினா" },
				{ LanguageId.te, "బోస్నియా & హెర్జిగోవినా" },
				{ LanguageId.teo, "Bosnia na Hezegovina" },
				{ LanguageId.tg, "Босния ва Ҳерсеговина" },
				{ LanguageId.th, "บอสเนียและเฮอร์เซโกวีนา" },
				{ LanguageId.ti, "ቦዝንያን ሄርዘጎቪናን" },
				{ LanguageId.tig, "Bosnia and Herzegovina" },
				{ LanguageId.tk, "Bosniýa we Gersegowina" },
				{ LanguageId.tn, "Bosnia and Herzegovina" },
				{ LanguageId.to, "Posinia mo Hesikōvina" },
				{ LanguageId.tr, "Bosna-Hersek" },
				{ LanguageId.ts, "Bosnia and Herzegovina" },
				{ LanguageId.tt, "Босния һәм Герцеговина" },
				{ LanguageId.twq, "Bosni nda Herzegovine" },
				{ LanguageId.tzm, "Busna-d-Hirsik" },
				{ LanguageId.ug, "بوسىنىيە ۋە گېرتسېگوۋىنا" },
				{ LanguageId.uk, "Боснія і Герцеговина" },
				{ LanguageId.ur, "بوسنیا اور ہرزیگووینا" },
				{ LanguageId.uz, "Bosniya va Gertsegovina" },
				{ LanguageId.vai, "ꕷꔻꕇꕰ ꗪ ꗥꕤꖑꔲꕯ" },
				{ LanguageId.ve, "Bosnia and Herzegovina" },
				{ LanguageId.vi, "Bosnia và Herzegovina" },
				{ LanguageId.vo, "Bosnän e Härzegovän" },
				{ LanguageId.vun, "Bosnia na Hezegovina" },
				{ LanguageId.wae, "Bosnie und Herzegovina" },
				{ LanguageId.wal, "Bosnia and Herzegovina" },
				{ LanguageId.wo, "Bosni Ersegowin" },
				{ LanguageId.xh, "EBosnia & Herzegovina" },
				{ LanguageId.xog, "Boziniya Hezegovina" },
				{ LanguageId.yav, "Pusiní-ɛlkofína" },
				{ LanguageId.yi, "באסניע הערצעגאווינע" },
				{ LanguageId.yo, "Bọ̀síníà àti Ẹtisẹgófínà" },
				{ LanguageId.zgh, "ⴱⵓⵙⵏⴰ ⴷ ⵀⵉⵔⵙⵉⴽ" },
				{ LanguageId.zh, "波斯尼亚和黑塞哥维那" },
				{ LanguageId.zu, "i-Bosnia ne-Herzegovina" },
			}
		);
	}
}
