using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "387",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Bosnia and Herzegovina" },
				{ LanguageId.da, "Bosnien-Hercegovina" },
				{ LanguageId.af, "Bosnië en Herzegovina" },
				{ LanguageId.agq, "Bosnia and Herzegovina" },
				{ LanguageId.ak, "Bosnia and Herzegovina" },
				{ LanguageId.am, "ቦስኒያ እና ሔርዞጎቪያ" },
				{ LanguageId.ar, "البوسنة والهرسك" },
				{ LanguageId.arn, "Bosnia and Herzegovina" },
				{ LanguageId.@as, "বছনিয়া আৰু হাৰ্জেগ'ভিনা" },
				{ LanguageId.asa, "Bosnia and Herzegovina" },
				{ LanguageId.ast, "Bosnia and Herzegovina" },
				{ LanguageId.az, "Bosniya və Herseqovina" },
				{ LanguageId.ba, "Босния һәм Герцеговина" },
				{ LanguageId.bas, "Bosnia and Herzegovina" },
				{ LanguageId.be, "Боснія і Герцагавіна" },
				{ LanguageId.bem, "Bosnia and Herzegovina" },
				{ LanguageId.bez, "Bosnia and Herzegovina" },
				{ LanguageId.bg, "Босна и Херцеговина" },
				{ LanguageId.bin, "Bosnia and Herzegovina" },
				{ LanguageId.bm, "Bosnia and Herzegovina" },
				{ LanguageId.bn, "বসনিয়া ও হার্জেগোভিনা" },
				{ LanguageId.bo, "བྷོསྣིཡ་དང་ཧར་ཛི་གོ་ཝི་ན།" },
				{ LanguageId.br, "Bosnia-ha-Herzegovina" },
				{ LanguageId.brx, "Bosnia and Herzegovina" },
				{ LanguageId.bs, "Bosna i Hercegovina" },
				{ LanguageId.byn, "Bosnia and Herzegovina" },
				{ LanguageId.ca, "Bòsnia i Hercegovina" },
				{ LanguageId.ccp, "Bosnia and Herzegovina" },
				{ LanguageId.ce, "Босни-Герцеговина" },
				{ LanguageId.ceb, "Bosnia ug Herzegovina" },
				{ LanguageId.cgg, "Bosnia and Herzegovina" },
				{ LanguageId.chr, "Bosnia and Herzegovina" },
				{ LanguageId.ckb, "بۆسنیا و ھەرزەگۆڤینا" },
				{ LanguageId.co, "Bosnia e Erzegovina" },
				{ LanguageId.cs, "Bosna a Hercegovina" },
				{ LanguageId.cu, "Босна и Херцеговина" },
				{ LanguageId.cy, "Bosnia a Herzegovina" },
				{ LanguageId.dav, "Bosnia and Herzegovina" },
				{ LanguageId.de, "Bosnien und Herzegowina" },
				{ LanguageId.dje, "Bosnia and Herzegovina" },
				{ LanguageId.doi, "Bosnia and Herzegovina" },
				{ LanguageId.dsb, "Bosniska-Hercegowinska" },
				{ LanguageId.dua, "Bosnia and Herzegovina" },
				{ LanguageId.dv, "ބޮސްނިޔާ އަދި ހަރުޒޮގްވީނާ" },
				{ LanguageId.dz, "བྷོསྣིཡ་དང་ཧར་ཛི་གོ་ཝི་ན།" },
				{ LanguageId.ebu, "Bosnia and Herzegovina" },
				{ LanguageId.ee, "Bosnia and Herzegovina" },
				{ LanguageId.el, "Βοσνία και Ερζεγοβίνη" },
				{ LanguageId.en, "Bosnia and Herzegovina" },
				{ LanguageId.eo, "Bosnio kaj Hercegovino" },
				{ LanguageId.es, "Bosnia y Herzegovina" },
				{ LanguageId.et, "Bosnia ja Hertsegoviina" },
				{ LanguageId.eu, "Bosnia eta Herzegovina" },
				{ LanguageId.ewo, "Bosnia and Herzegovina" },
				{ LanguageId.fa, "بوسنی و هرزگوین" },
				{ LanguageId.ff, "Bosnia and Herzegovina" },
				{ LanguageId.fi, "Bosnia ja Hertsegovina" },
				{ LanguageId.fil, "Bosnia at Herzegovina" },
				{ LanguageId.fo, "Bosnia og Herzegovina" },
				{ LanguageId.fr, "Bosnie Herzégovine" },
				{ LanguageId.fur, "Bosnia and Herzegovina" },
				{ LanguageId.fy, "Bosnje en Herzegovina" },
				{ LanguageId.ga, "An Bhoisnia agus an Heirseagaivéin" },
				{ LanguageId.gd, "Bosnia is Herzegovina" },
				{ LanguageId.gl, "Bosnia e Hercegovina" },
				{ LanguageId.gn, "Bosnia and Herzegovina" },
				{ LanguageId.gsw, "Bosnien und Herzegowina" },
				{ LanguageId.gu, "બોસ્નિયા અને હર્ઝેગોવિના" },
				{ LanguageId.guz, "Bosnia and Herzegovina" },
				{ LanguageId.gv, "Bosnia as Herzegovina" },
				{ LanguageId.ha, "Bosnia da Herzegovina" },
				{ LanguageId.haw, "Bosenia me Hesegowina" },
				{ LanguageId.he, "בוסניה והרצגובינה" },
				{ LanguageId.hi, "बोस्निया और हर्जेगोविना" },
				{ LanguageId.hr, "Bosna i Hercegovina" },
				{ LanguageId.hsb, "Bosniska-Hercegowinska" },
				{ LanguageId.hu, "Bosznia és Hercegovina" },
				{ LanguageId.hy, "Բոսնիա եւ Հերցեգովինա" },
				{ LanguageId.ia, "Bosnia e Herzegovina" },
				{ LanguageId.ibb, "Bosnia and Herzegovina" },
				{ LanguageId.id, "Bosnia dan Herzegovina" },
				{ LanguageId.ig, "Bosnia na Herzegovina" },
				{ LanguageId.ii, "Bosnia and Herzegovina" },
				{ LanguageId.@is, "Bosnía og Hersegóvína" },
				{ LanguageId.it, "Bosnia Erzegovina" },
				{ LanguageId.iu, "Bosnia and Herzegovina" },
				{ LanguageId.ja, "ボスニア・ヘルツェゴビナ" },
				{ LanguageId.jgo, "Bosnia and Herzegovina" },
				{ LanguageId.jmc, "Bosnia and Herzegovina" },
				{ LanguageId.jv, "Bosnia lan Herzegovina" },
				{ LanguageId.ka, "ბოსნია და ჰერცოგოვინა" },
				{ LanguageId.kab, "Bosnia and Herzegovina" },
				{ LanguageId.kam, "Bosnia and Herzegovina" },
				{ LanguageId.kde, "Bosnia and Herzegovina" },
				{ LanguageId.kea, "Bosnia and Herzegovina" },
				{ LanguageId.khq, "Bosnia and Herzegovina" },
				{ LanguageId.ki, "Bosnia and Herzegovina" },
				{ LanguageId.kk, "Босния және Герцеговина" },
				{ LanguageId.kkj, "Bosnia and Herzegovina" },
				{ LanguageId.kl, "Bosnia-Hercegovina" },
				{ LanguageId.kln, "Bosnia and Herzegovina" },
				{ LanguageId.km, "បូស្នៀ និងហឺហ្សេហ្គោវីណា" },
				{ LanguageId.kn, "ಬೋಸ್ನಿಯಾ ಮತ್ತು ಹರ್ಜೆಗೋವಿನಾ" },
				{ LanguageId.ko, "보스니아 헤르체고비나" },
				{ LanguageId.kok, "बोस्निया आणी हर्जेगोविना" },
				{ LanguageId.kr, "Bosnia and Herzegovina" },
				{ LanguageId.ks, "بوسنیا تہٕ ہرزِگووینا" },
				{ LanguageId.ksb, "Bosnia and Herzegovina" },
				{ LanguageId.ksf, "Bosnia and Herzegovina" },
				{ LanguageId.ksh, "Bosnia and Herzegovina" },
				{ LanguageId.kw, "Bosnia and Herzegovina" },
				{ LanguageId.ky, "Босния жана Герцеговина" },
				{ LanguageId.la, "Bosnia et Herzegovina" },
				{ LanguageId.lag, "Bosnia and Herzegovina" },
				{ LanguageId.lb, "Bosnien an Herzegowina" },
				{ LanguageId.lg, "Bosnia and Herzegovina" },
				{ LanguageId.lkt, "Bosnia and Herzegovina" },
				{ LanguageId.ln, "Bosnia and Herzegovina" },
				{ LanguageId.lo, "Bosnia ແລະ Herzegovina" },
				{ LanguageId.lrc, "بوسنی و هرزگوین" },
				{ LanguageId.lt, "Bosnija ir Hercegovina" },
				{ LanguageId.luo, "Bosnia and Herzegovina" },
				{ LanguageId.luy, "Bosnia and Herzegovina" },
				{ LanguageId.lv, "Bosnija un Hercegovina" },
				{ LanguageId.mai, "बोस्निया और हर्जेगोविना" },
				{ LanguageId.mas, "Bosnia and Herzegovina" },
				{ LanguageId.mer, "Bosnia and Herzegovina" },
				{ LanguageId.mfe, "Bosnia and Herzegovina" },
				{ LanguageId.mg, "Bosnia sy Herzegovina" },
				{ LanguageId.mgo, "Bosnia and Herzegovina" },
				{ LanguageId.mi, "Bosnia me Herzegovina" },
				{ LanguageId.mk, "Босна и Херцеговина" },
				{ LanguageId.ml, "ബോസ്നിയ ഹെർസഗോവിന" },
				{ LanguageId.mn, "Босни ба Херцеговина" },
				{ LanguageId.mni, "Bosnia and Herzegovina" },
				{ LanguageId.moh, "Bosnia and Herzegovina" },
				{ LanguageId.mr, "बोस्निया आणि हर्जेगोविना" },
				{ LanguageId.ms, "Bosnia dan Herzegovina" },
				{ LanguageId.mt, "Bosnja u Ħerzegovina" },
				{ LanguageId.mua, "Bosnia and Herzegovina" },
				{ LanguageId.my, "ဘော့စနီးယားနှင့် ဟာဇီဂိုဗီးနား" },
				{ LanguageId.mzn, "بوسنی و هرزگوین" },
				{ LanguageId.naq, "Bosnia and Herzegovina" },
				{ LanguageId.nb, "Bosnia og Herzegovina" },
				{ LanguageId.nd, "Bosnia and Herzegovina" },
				{ LanguageId.nds, "Bosnien-Herzegowina" },
				{ LanguageId.ne, "बोस्निया र हेर्जेगोभिना" },
				{ LanguageId.nl, "Bosnië-Herzegovina" },
				{ LanguageId.nmg, "Bosnia and Herzegovina" },
				{ LanguageId.nn, "Bosnia-Hercegovina" },
				{ LanguageId.nnh, "Bosnia and Herzegovina" },
				{ LanguageId.nqo, "Bosnia and Herzegovina" },
				{ LanguageId.nr, "Bosnia and Herzegovina" },
				{ LanguageId.nso, "Bosnia and Herzegovina" },
				{ LanguageId.nus, "Bosnia and Herzegovina" },
				{ LanguageId.nyn, "Bosnia and Herzegovina" },
				{ LanguageId.oc, "Bòsnia e Hertsegovina" },
				{ LanguageId.om, "Bosnia and Herzegovina" },
				{ LanguageId.or, "ବୋସନିଆ ଏବଂ ହେର୍ଜେଗୋଭିନା |" },
				{ LanguageId.os, "Босни æмæ Герцеговинæ" },
				{ LanguageId.pa, "ਬੋਸਨੀਆ ਅਤੇ ਹਰਜ਼ੇਗੋਵਿਨਾ" },
				{ LanguageId.pap, "Bosnia and Herzegovina" },
				{ LanguageId.pcm, "Bosnia and Herzegovina" },
				{ LanguageId.pl, "Bośnia i Hercegowina" },
				{ LanguageId.prg, "Bosnia and Herzegovina" },
				{ LanguageId.ps, "بوسنیا او هرزیګوینا" },
				{ LanguageId.pt, "Bósnia e Herzegovina" },
				{ LanguageId.qu, "Bosnia and Herzegovina" },
				{ LanguageId.quc, "Bosnia and Herzegovina" },
				{ LanguageId.rm, "Bosnia ed Hercegovina" },
				{ LanguageId.rn, "Bosiniya na Herzegovina" },
				{ LanguageId.ro, "Bosnia si Hertegovina" },
				{ LanguageId.rof, "Bosnia and Herzegovina" },
				{ LanguageId.ru, "Босния и Герцеговина" },
				{ LanguageId.rw, "Bosiniya na Herzegovina" },
				{ LanguageId.rwk, "Bosnia and Herzegovina" },
				{ LanguageId.sa, "बोस्निया हर्जेगोविना" },
				{ LanguageId.sah, "Босния уонна Герцеговина" },
				{ LanguageId.saq, "Bosnia and Herzegovina" },
				{ LanguageId.sat, "Bosnia and Herzegovina" },
				{ LanguageId.sbp, "Bosnia and Herzegovina" },
				{ LanguageId.sd, "بوسنيا ۽ هرزيگووينا" },
				{ LanguageId.se, "Bosnia-Hercegovina" },
				{ LanguageId.seh, "Bosnia and Herzegovina" },
				{ LanguageId.ses, "Bosnia and Herzegovina" },
				{ LanguageId.sg, "Bosnia and Herzegovina" },
				{ LanguageId.shi, "Bosnia and Herzegovina" },
				{ LanguageId.si, "බොස්නියාව සහ හර්සගොවිනාව" },
				{ LanguageId.sk, "Bosna a Hercegovina" },
				{ LanguageId.sl, "Bosna in Hercegovina" },
				{ LanguageId.sma, "Bosnia-Hercegovina" },
				{ LanguageId.smj, "Bosnia-Hercegovina" },
				{ LanguageId.smn, "Bosnia-Hercegovina" },
				{ LanguageId.sms, "Bosnia-Hercegovina" },
				{ LanguageId.sn, "Bhoziniya neHezegovhina" },
				{ LanguageId.so, "Bosnia iyo Herzegovina" },
				{ LanguageId.sq, "Bosnjë dhe Hercegovinë" },
				{ LanguageId.sr, "Босна и Херцеговина" },
				{ LanguageId.ss, "Bosnia and Herzegovina" },
				{ LanguageId.ssy, "Bosnia and Herzegovina" },
				{ LanguageId.st, "Bosnia le Herzegovina" },
				{ LanguageId.su, "Bosnia jeung Hérzégovina" },
				{ LanguageId.sv, "Bosnien och Hercegovina" },
				{ LanguageId.sw, "Bosnia na Herzegovina" },
				{ LanguageId.syr, "ܒܘܣܢܐ ܘܗܪܬܣܓܘܒܝܢܐ" },
				{ LanguageId.ta, "போஸ்னியா மற்றும் ஹெர்சகோவினா" },
				{ LanguageId.te, "బోస్నియా మరియు హెర్జెగోవినా" },
				{ LanguageId.teo, "Bosnia and Herzegovina" },
				{ LanguageId.tg, "Босния ва Ҳерсеговина" },
				{ LanguageId.th, "บอสเนียและเฮอร์เซโก" },
				{ LanguageId.ti, "ቦስኒያ እና ሔርዞጎቪያ" },
				{ LanguageId.tig, "Bosnia and Herzegovina" },
				{ LanguageId.tk, "Bosniýa we Gersegowina" },
				{ LanguageId.tn, "Bosnia and Herzegovina" },
				{ LanguageId.to, "Bosnia and Herzegovina" },
				{ LanguageId.tr, "Bosna Hersek" },
				{ LanguageId.ts, "Bosnia and Herzegovina" },
				{ LanguageId.tt, "Босния һәм Герцеговина" },
				{ LanguageId.twq, "Bosnia and Herzegovina" },
				{ LanguageId.tzm, "Bosnia and Herzegovina" },
				{ LanguageId.ug, "بوسنىيە-گېرتسېگوۋىنا" },
				{ LanguageId.uk, "Боснія і Герцеговина" },
				{ LanguageId.ur, "بوسنیا اور ہرزیگوینا" },
				{ LanguageId.uz, "Bosniya va Gertsegovina" },
				{ LanguageId.vai, "Bosnia and Herzegovina" },
				{ LanguageId.ve, "Bosnia and Herzegovina" },
				{ LanguageId.vi, "Bosnia và Herzegovina" },
				{ LanguageId.vo, "Bosnän e Härzegovän" },
				{ LanguageId.vun, "Bosnia and Herzegovina" },
				{ LanguageId.wae, "Bosnien-Herzegowina" },
				{ LanguageId.wal, "Bosnia and Herzegovina" },
				{ LanguageId.wo, "Bosnia and Herzegovina" },
				{ LanguageId.xh, "Bhozniya neHerzegovina" },
				{ LanguageId.xog, "Bosnia and Herzegovina" },
				{ LanguageId.yav, "Bosnia and Herzegovina" },
				{ LanguageId.yi, "באָסניאַ און הערזעגאָווינאַ" },
				{ LanguageId.yo, "Bosnia ati Herzegovina" },
				{ LanguageId.zgh, "Bosnia and Herzegovina" },
				{ LanguageId.zh, "波斯尼亚和黑塞哥维那" },
				{ LanguageId.zu, "I-Bosnia ne-Herzegovina" },
			}
		);
	}
}
