using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "387",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Bosnien-Hercegovina" },
				{ LanguageId.af, "Bosnië en Herzegovina" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቦስኒያ እና ሔርዞጎቪያ" },
				{ LanguageId.ar, "البوسنة والهرسك" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Bosniya və Herseqovina" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Боснія і Герцагавіна" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Босна и Херцеговина" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "বসনিয়া ও হার্জেগোভিনা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Bosna i Hercegovina" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Bòsnia i Hercegovina" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Bosnia ug Herzegovina" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Bosnia e Erzegovina" },
				{ LanguageId.cs, "Bosna a Hercegovina" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Bosnia a Herzegovina" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Bosnien und Herzegowina" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Βοσνία και Ερζεγοβίνη" },
				{ LanguageId.en, "Bosnia and Herzegovina" },
				{ LanguageId.eo, "Bosnio kaj Hercegovino" },
				{ LanguageId.es, "Bosnia y Herzegovina" },
				{ LanguageId.et, "Bosnia ja Hertsegoviina" },
				{ LanguageId.eu, "Bosnia eta Herzegovina" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "بوسنی و هرزگوین" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Bosnia ja Hertsegovina" },
				{ LanguageId.fil, "Bosnia at Herzegovina" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Bosnie Herzégovine" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Bosnje en Herzegovina" },
				{ LanguageId.ga, "An Bhoisnia agus an Heirseagaivéin" },
				{ LanguageId.gd, "Bosnia is Herzegovina" },
				{ LanguageId.gl, "Bosnia e Hercegovina" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "બોસ્નિયા અને હર્ઝેગોવિના" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Bosnia da Herzegovina" },
				{ LanguageId.haw, "Bosenia me Hesegowina" },
				{ LanguageId.he, "בוסניה והרצגובינה" },
				{ LanguageId.hi, "बोस्निया और हर्जेगोविना" },
				{ LanguageId.hr, "Bosna i Hercegovina" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Bosznia és Hercegovina" },
				{ LanguageId.hy, "Բոսնիա եւ Հերցեգովինա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Bosnia dan Herzegovina" },
				{ LanguageId.ig, "Bosnia na Herzegovina" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bosnía og Hersegóvína" },
				{ LanguageId.it, "Bosnia Erzegovina" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ボスニア・ヘルツェゴビナ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Bosnia lan Herzegovina" },
				{ LanguageId.ka, "ბოსნია და ჰერცოგოვინა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Босния және Герцеговина" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "បូស្នៀ និងហឺហ្សេហ្គោវីណា" },
				{ LanguageId.kn, "ಬೋಸ್ನಿಯಾ ಮತ್ತು ಹರ್ಜೆಗೋವಿನಾ" },
				{ LanguageId.ko, "보스니아 헤르체고비나" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Босния жана Герцеговина" },
				{ LanguageId.la, "Bosnia et Herzegovina" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Bosnien an Herzegowina" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Bosnia ແລະ Herzegovina" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Bosnija ir Hercegovina" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Bosnija un Hercegovina" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Bosnia sy Herzegovina" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Bosnia me Herzegovina" },
				{ LanguageId.mk, "Босна и Херцеговина" },
				{ LanguageId.ml, "ബോസ്നിയ ഹെർസഗോവിന" },
				{ LanguageId.mn, "Босни ба Херцеговина" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "बोस्निया आणि हर्जेगोविना" },
				{ LanguageId.ms, "Bosnia dan Herzegovina" },
				{ LanguageId.mt, "Bosnja u Ħerzegovina" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဘော့စနီးယားနှင့် ဟာဇီဂိုဗီးနား" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Bosnia og Herzegovina" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "बोस्निया र हेर्जेगोभिना" },
				{ LanguageId.nl, "Bosnië-Herzegovina" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ବୋସନିଆ ଏବଂ ହେର୍ଜେଗୋଭିନା |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬੋਸਨੀਆ ਅਤੇ ਹਰਜ਼ੇਗੋਵਿਨਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Bośnia i Hercegowina" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بوسنیا او هرزیګوینا" },
				{ LanguageId.pt, "Bósnia e Herzegovina" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Bosnia si Hertegovina" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Босния и Герцеговина" },
				{ LanguageId.rw, "Bosiniya na Herzegovina" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "بوسنيا ۽ هرزيگووينا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "බොස්නියාව සහ හර්සගොවිනාව" },
				{ LanguageId.sk, "Bosna a Hercegovina" },
				{ LanguageId.sl, "Bosna in Hercegovina" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Bhoziniya neHezegovhina" },
				{ LanguageId.so, "Bosnia iyo Herzegovina" },
				{ LanguageId.sq, "Bosnjë dhe Hercegovinë" },
				{ LanguageId.sr, "Босна и Херцеговина" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Bosnia le Herzegovina" },
				{ LanguageId.su, "Bosnia jeung Hérzégovina" },
				{ LanguageId.sv, "Bosnien och Hercegovina" },
				{ LanguageId.sw, "Bosnia na Herzegovina" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "போஸ்னியா மற்றும் ஹெர்சகோவினா" },
				{ LanguageId.te, "బోస్నియా మరియు హెర్జెగోవినా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Босния ва Ҳерсеговина" },
				{ LanguageId.th, "บอสเนียและเฮอร์เซโก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Bosniýa we Gersegowina" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Bosna Hersek" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Босния һәм Герцеговина" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "بوسنىيە-گېرتسېگوۋىنا" },
				{ LanguageId.uk, "Боснія і Герцеговина" },
				{ LanguageId.ur, "بوسنیا اور ہرزیگوینا" },
				{ LanguageId.uz, "Bosniya va Gertsegovina" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Bosnia và Herzegovina" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Bhozniya neHerzegovina" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "באָסניאַ און הערזעגאָווינאַ" },
				{ LanguageId.yo, "Bosnia ati Herzegovina" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "波斯尼亚和黑塞哥维那" },
				{ LanguageId.zu, "I-Bosnia ne-Herzegovina" },
			}
		);
	}
}
