// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "226",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Burkina Faso" },
				{ LanguageId.af, "Burkina Faso" },
				{ LanguageId.agq, "Bùkinà Fasò" },
				{ LanguageId.ak, "Bɔkina Faso" },
				{ LanguageId.am, "ቡርኪና ፋሶ" },
				{ LanguageId.ar, "بوركينا فاسو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "বুৰকিনা ফাচো" },
				{ LanguageId.asa, "Bukinafatho" },
				{ LanguageId.ast, "Burkina Fasu" },
				{ LanguageId.az, "Burkina Faso" },
				{ LanguageId.ba, "Буркина-Фасо" },
				{ LanguageId.bas, "Bùrkìnà Fasò" },
				{ LanguageId.be, "Буркіна-Фасо" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hubukinafaso" },
				{ LanguageId.bg, "Буркина Фасо" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Burukina Faso" },
				{ LanguageId.bn, "বুরকিনা ফাসো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Burkina Faso" },
				{ LanguageId.brx, "बुर्किना फास’" },
				{ LanguageId.bs, "Burkina Faso" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Burkina Faso" },
				{ LanguageId.ccp, "𑄝𑄪𑄢𑄴𑄇𑄨𑄚 𑄜𑄥𑄮" },
				{ LanguageId.ce, "Буркина- Фасо" },
				{ LanguageId.ceb, "Burkina Faso" },
				{ LanguageId.cgg, "Bokina Faso" },
				{ LanguageId.chr, "ᏋᎩᎾ ᏩᏐ" },
				{ LanguageId.ckb, "بورکینافاسۆ" },
				{ LanguageId.co, "Burkina Faso" },
				{ LanguageId.cs, "Burkina Faso" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Burkina Faso" },
				{ LanguageId.dav, "Bukinafaso" },
				{ LanguageId.de, "Burkina Faso" },
				{ LanguageId.dje, "Burkina faso" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Burkina Faso" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "བྷར་ཀི་ན་ ཕེ་སོ" },
				{ LanguageId.ebu, "Bukinafaso" },
				{ LanguageId.ee, "Burkina Faso nutome" },
				{ LanguageId.el, "Μπουρκίνα Φάσο" },
				{ LanguageId.en, "Burkina Faso" },
				{ LanguageId.eo, "Burkino" },
				{ LanguageId.es, "Burkina Faso" },
				{ LanguageId.et, "Burkina Faso" },
				{ LanguageId.eu, "Burkina Faso" },
				{ LanguageId.ewo, "Buləkiná Fasó" },
				{ LanguageId.fa, "بورکینافاسو" },
				{ LanguageId.ff, "Burkibaa Faaso" },
				{ LanguageId.fi, "Burkina Faso" },
				{ LanguageId.fil, "Burkina Faso" },
				{ LanguageId.fo, "Burkina Faso" },
				{ LanguageId.fr, "Burkina Faso" },
				{ LanguageId.fur, "Burkina Faso" },
				{ LanguageId.fy, "Burkina Faso" },
				{ LanguageId.ga, "Buircíne Fasó" },
				{ LanguageId.gd, "Buirciona Faso" },
				{ LanguageId.gl, "Burkina Faso" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Burkina Faaso" },
				{ LanguageId.gu, "બુર્કિના ફાસો" },
				{ LanguageId.guz, "Bukinafaso" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Burkina Faso" },
				{ LanguageId.haw, "Burakina Faso" },
				{ LanguageId.he, "בורקינה פאסו" },
				{ LanguageId.hi, "बुर्किना फ़ासो" },
				{ LanguageId.hr, "Burkina Faso" },
				{ LanguageId.hsb, "Burkina Faso" },
				{ LanguageId.hu, "Burkina Faso" },
				{ LanguageId.hy, "Բուրկինա Ֆասո" },
				{ LanguageId.ia, "Burkina Faso" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Burkina Faso" },
				{ LanguageId.ig, "Burkina Faso" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Búrkína Fasó" },
				{ LanguageId.it, "Burkina Faso" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ブルキナファソ" },
				{ LanguageId.jgo, "Mbulukína Fásɔ" },
				{ LanguageId.jmc, "Bukinafaso" },
				{ LanguageId.jv, "Burkina Faso" },
				{ LanguageId.ka, "ბურკინა-ფასო" },
				{ LanguageId.kab, "Burkina Fasu" },
				{ LanguageId.kam, "Bukinafaso" },
				{ LanguageId.kde, "Buchinafaso" },
				{ LanguageId.kea, "Burkina Fasu" },
				{ LanguageId.khq, "Burkina faso" },
				{ LanguageId.ki, "Bukinafaso" },
				{ LanguageId.kk, "Буркина-Фасо" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Burkina Faso" },
				{ LanguageId.km, "បួគីណាហ្វាសូ" },
				{ LanguageId.kn, "ಬುರ್ಕಿನಾ ಫಾಸೊ" },
				{ LanguageId.ko, "부르키나파소" },
				{ LanguageId.kok, "बुर्कीना फासो" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "بُرکِنا فیسو" },
				{ LanguageId.ksb, "Bukinafaso" },
				{ LanguageId.ksf, "bukína fǝ́ asɔ" },
				{ LanguageId.ksh, "Bukkinna-Faase" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Буркина-Фасо" },
				{ LanguageId.la, "Burkina Faso" },
				{ LanguageId.lag, "Bukinafáaso" },
				{ LanguageId.lb, "Burkina Faso" },
				{ LanguageId.lg, "Burukina Faso" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bukina Faso" },
				{ LanguageId.lo, "ເບີກິນາ ຟາໂຊ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Burkina Fasas" },
				{ LanguageId.luo, "Burkina Faso" },
				{ LanguageId.luy, "Bukinafaso" },
				{ LanguageId.lv, "Burkinafaso" },
				{ LanguageId.mai, "बुरकिना फासो" },
				{ LanguageId.mas, "Bukinafaso" },
				{ LanguageId.mer, "Bukinafaso" },
				{ LanguageId.mfe, "Burkina Faso" },
				{ LanguageId.mg, "Borkina Faso" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Pākina Wharo" },
				{ LanguageId.mk, "Буркина Фасо" },
				{ LanguageId.ml, "ബർക്കിന ഫാസോ" },
				{ LanguageId.mn, "Буркина Фасо" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "बुर्किना फासो" },
				{ LanguageId.ms, "Burkina Faso" },
				{ LanguageId.mt, "il-Burkina Faso" },
				{ LanguageId.mua, "burkina Faso" },
				{ LanguageId.my, "ဘာကီးနား ဖားဆို" },
				{ LanguageId.mzn, "بورکینا فاسو" },
				{ LanguageId.naq, "Burkina Fasob" },
				{ LanguageId.nb, "Burkina Faso" },
				{ LanguageId.nd, "Bhukina Faso" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "बुर्किना फासो" },
				{ LanguageId.nl, "Burkina Faso" },
				{ LanguageId.nmg, "Burkina Faso" },
				{ LanguageId.nn, "Burkina Faso" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߓߙߎߞߌߣߊ߫ ߝߊ߬ߛߏ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Burkinɛ pa̱thu" },
				{ LanguageId.nyn, "Bokina Faso" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Burkiinaa Faasoo" },
				{ LanguageId.or, "ବୁର୍କିନା ଫାସୋ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬੁਰਕੀਨਾ ਫ਼ਾਸੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Burkína Fáso" },
				{ LanguageId.pl, "Burkina Faso" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بورکینا فاسو" },
				{ LanguageId.pt, "Burquina Faso" },
				{ LanguageId.qu, "Burkina Faso" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Burkina Faso" },
				{ LanguageId.rn, "Burukina Faso" },
				{ LanguageId.ro, "Burkina Faso" },
				{ LanguageId.rof, "Bukinafaso" },
				{ LanguageId.ru, "Буркина-Фасо" },
				{ LanguageId.rw, "Burkina Faso" },
				{ LanguageId.rwk, "Bukinafaso" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Bukinafaso" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Bukinafaso" },
				{ LanguageId.sd, "برڪينا فاسو" },
				{ LanguageId.se, "Burkina Faso" },
				{ LanguageId.seh, "Burquina Faso" },
				{ LanguageId.ses, "Burkina faso" },
				{ LanguageId.sg, "Burkina Faso" },
				{ LanguageId.shi, "ⴱⵓⵔⴽⵉⵏⴰ ⴼⴰⵙⵓ" },
				{ LanguageId.si, "බර්කිනා ෆාසෝ" },
				{ LanguageId.sk, "Burkina Faso" },
				{ LanguageId.sl, "Burkina Faso" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Burkina Faso" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Bukinafaso" },
				{ LanguageId.so, "Burkiina Faaso" },
				{ LanguageId.sq, "Burkina-Faso" },
				{ LanguageId.sr, "Буркина Фасо" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Burkina Faso" },
				{ LanguageId.su, "Burkina Faso" },
				{ LanguageId.sv, "Burkina Faso" },
				{ LanguageId.sw, "Bukinafaso" },
				{ LanguageId.syr, "ܒܘܪܩܝܢܐ ܦܐܣܘ" },
				{ LanguageId.ta, "புர்கினா ஃபாஸோ" },
				{ LanguageId.te, "బుర్కినా ఫాసో" },
				{ LanguageId.teo, "Bukinafaso" },
				{ LanguageId.tg, "Буркина-Фасо" },
				{ LanguageId.th, "บูร์กินาฟาโซ" },
				{ LanguageId.ti, "ቡርኪና ፋሶ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Burkina-Faso" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Pekano Faso" },
				{ LanguageId.tr, "Burkina Faso" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Буркина-Фасо" },
				{ LanguageId.twq, "Burkina faso" },
				{ LanguageId.tzm, "Burkina Fasu" },
				{ LanguageId.ug, "بۇركىنا فاسو" },
				{ LanguageId.uk, "Буркіна-Фасо" },
				{ LanguageId.ur, "برکینا فاسو" },
				{ LanguageId.uz, "Burkina-Faso" },
				{ LanguageId.vai, "ꕷꕃꕯ ꕘꖇ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Burkina Faso" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Bukinafaso" },
				{ LanguageId.wae, "Burkina Faso" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Burkina Faaso" },
				{ LanguageId.xh, "EBurkina Faso" },
				{ LanguageId.xog, "Burukina Faso" },
				{ LanguageId.yav, "Pulikínafásó" },
				{ LanguageId.yi, "בורקינע פֿאַסא" },
				{ LanguageId.yo, "Bùùkíná Fasò" },
				{ LanguageId.zgh, "ⴱⵓⵔⴽⵉⵏⴰ ⴼⴰⵙⵓ" },
				{ LanguageId.zh, "布基纳法索" },
				{ LanguageId.zu, "i-Burkina Faso" },
			}
		);
	}
}
