using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "226",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Burkina Faso" },
				{ LanguageId.af, "Burkina Faso" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቡርክናፋሶ" },
				{ LanguageId.ar, "بوركينا فاسو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Burkina Faso" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Буркіна-Фасо" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Буркина Фасо" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "বুর্কিনা ফাসো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Burkina Faso" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Burkina Faso" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Burkina Faso" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Burkina Faso" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Burkina Faso" },
				{ LanguageId.cs, "Burkina Faso" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Burkina Faso" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Burkina Faso" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Μπουρκίνα Φάσο" },
				{ LanguageId.en, "Burkina Faso" },
				{ LanguageId.eo, "Burkino" },
				{ LanguageId.es, "Burkina Faso" },
				{ LanguageId.et, "Burkina Faso" },
				{ LanguageId.eu, "Burkina Faso" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "بورکینافاسو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Burkina Faso" },
				{ LanguageId.fil, "Burkina Faso" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Burkina Faso" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Boerkina Faso" },
				{ LanguageId.ga, "Buircíne Fasó" },
				{ LanguageId.gd, "Burknina Faso" },
				{ LanguageId.gl, "Burkina Faso" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "બુર્કિના ફાસો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Burkina Faso" },
				{ LanguageId.haw, "Burakina Faso" },
				{ LanguageId.he, "בורקינה פאסו" },
				{ LanguageId.hi, "बुर्किना फासो" },
				{ LanguageId.hr, "Burkina Faso" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Burkina Faso" },
				{ LanguageId.hy, "Բուրկինա Ֆասո" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Burkina Faso" },
				{ LanguageId.ig, "Burkina Faso" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Búrkína Fasó" },
				{ LanguageId.it, "Burkina Faso" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ブルキナファソ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Burkina Faso" },
				{ LanguageId.ka, "ბურკინა ფასო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Буркина-Фасо" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ប៊ូគីណាហ្វាសូ" },
				{ LanguageId.kn, "ಬುರ್ಕಿನಾ ಫಾಸೊ" },
				{ LanguageId.ko, "부키 나 파소" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Буркина Фасо" },
				{ LanguageId.la, "Burkina Faso" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Burkina Faso" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ບູກີນາຟາໂຊ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Burkina Fasas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Burkinafaso" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Burkina Faso" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Burkina Faso" },
				{ LanguageId.mk, "Буркина Фасо" },
				{ LanguageId.ml, "ബുർക്കിന ഫാസോ" },
				{ LanguageId.mn, "Буркина Фасо" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "बुर्किना फासो" },
				{ LanguageId.ms, "Burkina Faso" },
				{ LanguageId.mt, "Burkina Faso" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဘာကီနာဖာဆို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Burkina Faso" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "बुर्किना फासो" },
				{ LanguageId.nl, "Burkina Faso" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ବୁର୍କିନା ଫାସୋ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬੁਰਕੀਨਾ ਫਾਸੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Burkina Faso" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بورکینا فاسو" },
				{ LanguageId.pt, "Burkina Faso" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Burkina Faso" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Буркина-Фасо" },
				{ LanguageId.rw, "Burkina Faso" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "برڪينا فاسو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "බුර්කිනා ෆාසෝ" },
				{ LanguageId.sk, "Burkina Faso" },
				{ LanguageId.sl, "Burkina Faso" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Bhakina Faso" },
				{ LanguageId.so, "Burkina Faso" },
				{ LanguageId.sq, "Burkina Faso" },
				{ LanguageId.sr, "Буркина Фасо" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Burkina Faso" },
				{ LanguageId.su, "Burkina Faso" },
				{ LanguageId.sv, "Burkina Faso" },
				{ LanguageId.sw, "Burkina Faso" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "புர்கினா பாசோ" },
				{ LanguageId.te, "బుర్కినా ఫాసో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Буркина Фасо" },
				{ LanguageId.th, "บูร์กินาฟาโซ" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Burkina Faso" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Burkina Faso" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Буркина Фасо" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Burkina Faso" },
				{ LanguageId.uk, "Буркіна Фасо" },
				{ LanguageId.ur, "برکینا فاسو" },
				{ LanguageId.uz, "Burkina-Faso" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Burkina Faso" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Bhekina Faso" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "בורקינאַ פאַסאָ" },
				{ LanguageId.yo, "Burkina Faso" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "布基纳法索" },
				{ LanguageId.zu, "Burkina Faso" },
			}
		);
	}
}
