// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BL
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "590",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Barthélemy" },
				{ LanguageId.af, "Sint Barthélemy" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "St. Baatilemi" },
				{ LanguageId.am, "ሴንት ባርቴሌሚ" },
				{ LanguageId.ar, "سان بارتليمي" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট বাৰ্থলেমে" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "San Bartolomé" },
				{ LanguageId.az, "Sent-Bartelemi" },
				{ LanguageId.ba, "Сен-Бартелеми" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сен-Бартэльмі" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сен Бартелеми" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট বার্থেলেমি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sant-Bertele" },
				{ LanguageId.brx, "सैन्ट बार्थेलेमी" },
				{ LanguageId.bs, "Sveti Bartolomej" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint-Barthélemy" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄝𑄢𑄴𑄗𑄬𑄣𑄨𑄟𑄨" },
				{ LanguageId.ce, "Сен-Бартельми" },
				{ LanguageId.ceb, "St. Barthelemy" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᏆᏕᎳᎻ" },
				{ LanguageId.ckb, "سەن بارتێلێمی" },
				{ LanguageId.co, "" },
				{ LanguageId.cs, "Svatý Bartoloměj" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Barthélemy" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Barthélemy" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Barthélemy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ བར་ཐོ་ལོམ་མིའུ" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Saint Barthélemy nutome" },
				{ LanguageId.el, "Άγιος Βαρθολομαίος" },
				{ LanguageId.en, "St. Barthélemy" },
				{ LanguageId.eo, "Sankta Bartolomeo" },
				{ LanguageId.es, "San Bartolomé" },
				{ LanguageId.et, "Saint-Barthélemy" },
				{ LanguageId.eu, "Saint Barthélemy" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سن بارتلمی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saint-Barthélemy" },
				{ LanguageId.fil, "St. Barthélemy" },
				{ LanguageId.fo, "St. Barthélemy" },
				{ LanguageId.fr, "Saint-Barthélemy" },
				{ LanguageId.fur, "Sant Barthélemy" },
				{ LanguageId.fy, "Saint Barthélemy" },
				{ LanguageId.ga, "Saint Barthélemy" },
				{ LanguageId.gd, "Saint Barthélemy" },
				{ LanguageId.gl, "Saint Barthélemy" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Barthelemi" },
				{ LanguageId.gu, "સેંટ બાર્થેલેમી" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Barthélemy" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "סנט ברתולומיאו" },
				{ LanguageId.hi, "सेंट बार्थेलेमी" },
				{ LanguageId.hr, "Saint Barthélemy" },
				{ LanguageId.hsb, "St. Barthélemy" },
				{ LanguageId.hu, "Saint-Barthélemy" },
				{ LanguageId.hy, "Սուրբ Բարդուղիմեոս" },
				{ LanguageId.ia, "Sancte Bartholomeo" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Barthélemy" },
				{ LanguageId.ig, "St. Barthélemy" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Bartólómeusareyjar" },
				{ LanguageId.it, "Saint-Barthélemy" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サン・バルテルミー" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Saint Barthélémi" },
				{ LanguageId.ka, "სენ-ბართელმი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "San Bartolomeu" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сен-Бартелеми" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាំង​បាថេឡេមី" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಬಾರ್ಥೆಲೆಮಿ" },
				{ LanguageId.ko, "생바르텔레미" },
				{ LanguageId.kok, "सांव बार्टोलोमेव" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ بارتَھیلمی" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "de Zint Battälmi-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент Бартелеми" },
				{ LanguageId.la, "" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saint-Barthélemy" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊນ ບາເທເລມີ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sen Bartelemi" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Senbartelmī" },
				{ LanguageId.mai, "सेंट बार्थेलेमी" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Pāteremi" },
				{ LanguageId.mk, "Свети Вартоломеј" },
				{ LanguageId.ml, "സെന്റ് ബാർത്തലമി" },
				{ LanguageId.mn, "Сент-Бартельми" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट बार्थेलेमी" },
				{ LanguageId.ms, "St. Barthelemy" },
				{ LanguageId.mt, "Saint Barthélemy" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စိန့်ဘာသယ်လ်မီ" },
				{ LanguageId.mzn, "سنت بارتلمی" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saint-Barthélemy" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट बार्थेलेमी" },
				{ LanguageId.nl, "Saint-Barthélemy" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Saint-Barthélemy" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߓߌߙߑߕߟߋߡߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Barzeleemii" },
				{ LanguageId.or, "ସେଣ୍ଟ ବାର୍ଥେଲେମି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਬਾਰਥੇਲੇਮੀ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sént Batẹlẹ́mi" },
				{ LanguageId.pl, "Saint-Barthélemy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سينټ بارتيلمي" },
				{ LanguageId.pt, "São Bartolomeu" },
				{ LanguageId.qu, "San Bartolomé" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Son Barthélemy" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Saint-Barthélemy" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сен-Бартелеми" },
				{ LanguageId.rw, "" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سینٽ برٿلیمی" },
				{ LanguageId.se, "Saint Barthélemy" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත බර්තලෙමි" },
				{ LanguageId.sk, "Svätý Bartolomej" },
				{ LanguageId.sl, "Sveti Bartolomej" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Barthélemy" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "" },
				{ LanguageId.so, "St. Baathelemiy" },
				{ LanguageId.sq, "Sen-Bartelemi" },
				{ LanguageId.sr, "Свети Бартоломеј" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "" },
				{ LanguageId.sv, "S:t Barthélemy" },
				{ LanguageId.sw, "St. Barthelemy" },
				{ LanguageId.syr, "ܡܪܝ ܒܪ ܬܘܠܡܝ" },
				{ LanguageId.ta, "செயின்ட் பார்தேலெமி" },
				{ LanguageId.te, "సెయింట్ బర్థెలిమి" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент-Бартелми" },
				{ LanguageId.th, "เซนต์บาร์เธเลมี" },
				{ LanguageId.ti, "ቅዱስ ባርተለሚ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sen-Bartelemi" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Patēlemi" },
				{ LanguageId.tr, "Saint Barthelemy" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сен-Бартельми" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ساينت بارتېلېمى" },
				{ LanguageId.uk, "Сен-Бартелемі" },
				{ LanguageId.ur, "سینٹ برتھلیمی" },
				{ LanguageId.uz, "Sen-Bartelemi" },
				{ LanguageId.vai, "ꕪꘋꕓ ꗞꗢ ꕒꕚꕞꕆ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Barthélemy" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "St. Bartholomäus-Insla" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Bartalemi" },
				{ LanguageId.xh, "ESt. Barthélemy" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "" },
				{ LanguageId.yo, "Ìlú Bátílẹ́mì" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣巴泰勒米" },
				{ LanguageId.zu, "i-Saint Barthélemy" },
			}
		);
	}
}
