// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Bermuda" },
				{ LanguageId.da, "Bermuda" },
				{ LanguageId.af, "Bermuda" },
				{ LanguageId.agq, "Bɛ̀mudà" },
				{ LanguageId.ak, "Bɛmuda" },
				{ LanguageId.am, "ቤርሙዳ" },
				{ LanguageId.ar, "برمودا" },
				{ LanguageId.arn, "Bermuda" },
				{ LanguageId.@as, "বাৰ্মুডা" },
				{ LanguageId.asa, "Bermuda" },
				{ LanguageId.ast, "Les Bermudes" },
				{ LanguageId.az, "Bermud adaları" },
				{ LanguageId.ba, "Бермуд утрауҙары" },
				{ LanguageId.bas, "Bɛ̀rmudà" },
				{ LanguageId.be, "Бермудскія астравы" },
				{ LanguageId.bem, "Bermuda" },
				{ LanguageId.bez, "Hubelmuda" },
				{ LanguageId.bg, "Бермудски острови" },
				{ LanguageId.bin, "Bermuda" },
				{ LanguageId.bm, "Bermudi" },
				{ LanguageId.bn, "বারমুডা" },
				{ LanguageId.bo, "བར་མུ་ཌ།" },
				{ LanguageId.br, "Bermudez" },
				{ LanguageId.brx, "बारमूडा" },
				{ LanguageId.bs, "Bermuda" },
				{ LanguageId.byn, "Bermuda" },
				{ LanguageId.ca, "Bermudes" },
				{ LanguageId.ccp, "𑄝𑄢𑄴𑄟𑄪𑄓" },
				{ LanguageId.ce, "Бермудан гӀайренаш" },
				{ LanguageId.ceb, "Bermuda" },
				{ LanguageId.cgg, "Berimuda" },
				{ LanguageId.chr, "ᏆᏊᏓ" },
				{ LanguageId.ckb, "بێرموودا" },
				{ LanguageId.co, "Bermuda" },
				{ LanguageId.cs, "Bermudy" },
				{ LanguageId.cu, "Бермуды" },
				{ LanguageId.cy, "Bermuda" },
				{ LanguageId.dav, "Bermuda" },
				{ LanguageId.de, "Bermuda" },
				{ LanguageId.dje, "Bermuda" },
				{ LanguageId.doi, "बरमूडा" },
				{ LanguageId.dsb, "Bermudy" },
				{ LanguageId.dua, "Bermuda" },
				{ LanguageId.dv, "ބަރމިއުޑާ" },
				{ LanguageId.dz, "བར་མུ་ཌ" },
				{ LanguageId.ebu, "Bermuda" },
				{ LanguageId.ee, "Bermuda nutome" },
				{ LanguageId.el, "Βερμούδες" },
				{ LanguageId.en, "Bermuda" },
				{ LanguageId.eo, "Bermudoj" },
				{ LanguageId.es, "Bermudas" },
				{ LanguageId.et, "Bermuda" },
				{ LanguageId.eu, "Bermuda" },
				{ LanguageId.ewo, "Bɛrəmúd" },
				{ LanguageId.fa, "برمودا" },
				{ LanguageId.ff, "Bermudaa" },
				{ LanguageId.fi, "Bermuda" },
				{ LanguageId.fil, "Bermuda" },
				{ LanguageId.fo, "Bermuda" },
				{ LanguageId.fr, "Bermudes" },
				{ LanguageId.fur, "Bermuda" },
				{ LanguageId.fy, "Bermuda" },
				{ LanguageId.ga, "Beirmiúda" },
				{ LanguageId.gd, "Bearmùda" },
				{ LanguageId.gl, "Illas Bermudas" },
				{ LanguageId.gn, "Bermuda" },
				{ LanguageId.gsw, "Bermuuda" },
				{ LanguageId.gu, "બર્મુડા" },
				{ LanguageId.guz, "Bermuda" },
				{ LanguageId.gv, "Bermuda" },
				{ LanguageId.ha, "Barmuda" },
				{ LanguageId.haw, "Beramuda" },
				{ LanguageId.he, "ברמודה" },
				{ LanguageId.hi, "बरमूडा" },
				{ LanguageId.hr, "Bermudi" },
				{ LanguageId.hsb, "Bermudy" },
				{ LanguageId.hu, "Bermuda" },
				{ LanguageId.hy, "Բերմուդներ" },
				{ LanguageId.ia, "Bermuda" },
				{ LanguageId.ibb, "Bermuda" },
				{ LanguageId.id, "Bermuda" },
				{ LanguageId.ig, "Bemuda" },
				{ LanguageId.ii, "百慕大" },
				{ LanguageId.@is, "Bermúdaeyjar" },
				{ LanguageId.it, "Bermuda" },
				{ LanguageId.iu, "ᐱᕐᒧᑕ" },
				{ LanguageId.ja, "バミューダ" },
				{ LanguageId.jgo, "Bermuda" },
				{ LanguageId.jmc, "Bermuda" },
				{ LanguageId.jv, "Bermuda" },
				{ LanguageId.ka, "ბერმუდა" },
				{ LanguageId.kab, "Bermuda" },
				{ LanguageId.kam, "Bermuda" },
				{ LanguageId.kde, "Belmuda" },
				{ LanguageId.kea, "Bermudas" },
				{ LanguageId.khq, "Bermuda" },
				{ LanguageId.ki, "Bermuda" },
				{ LanguageId.kk, "Бермуд аралдары" },
				{ LanguageId.kkj, "Bermuda" },
				{ LanguageId.kl, "Bermuda" },
				{ LanguageId.kln, "Emetab Bermuda" },
				{ LanguageId.km, "ប៊ឺមុយដា" },
				{ LanguageId.kn, "ಬರ್ಮುಡಾ" },
				{ LanguageId.ko, "버뮤다" },
				{ LanguageId.kok, "बर्मुडा" },
				{ LanguageId.kr, "Bermuda" },
				{ LanguageId.ks, "برمودا" },
				{ LanguageId.ksb, "Belmuda" },
				{ LanguageId.ksf, "bɛɛmúdǝ" },
				{ LanguageId.ksh, "de Bermudas" },
				{ LanguageId.kw, "Bermuda" },
				{ LanguageId.ky, "Бермуд аралдары" },
				{ LanguageId.la, "Bermuda" },
				{ LanguageId.lag, "Berimúuda" },
				{ LanguageId.lb, "Bermuda" },
				{ LanguageId.lg, "Beremuda" },
				{ LanguageId.lkt, "Bermuda" },
				{ LanguageId.ln, "Bermuda" },
				{ LanguageId.lo, "ເບີມິວດາ" },
				{ LanguageId.lrc, "بئرموٙدا" },
				{ LanguageId.lt, "Bermuda" },
				{ LanguageId.luo, "Bermuda" },
				{ LanguageId.luy, "Bermuda" },
				{ LanguageId.lv, "Bermudu salas" },
				{ LanguageId.mai, "बरमुडा" },
				{ LanguageId.mas, "Bermuda" },
				{ LanguageId.mer, "Bamuda" },
				{ LanguageId.mfe, "Bermid" },
				{ LanguageId.mg, "Bermioda" },
				{ LanguageId.mgo, "Bermuda" },
				{ LanguageId.mi, "Pāmura" },
				{ LanguageId.mk, "Бермуди" },
				{ LanguageId.ml, "ബർമുഡ" },
				{ LanguageId.mn, "Бермуда" },
				{ LanguageId.mni, "বাৰ্মুডা" },
				{ LanguageId.moh, "Bermuda" },
				{ LanguageId.mr, "बर्मुडा" },
				{ LanguageId.ms, "Bermuda" },
				{ LanguageId.mt, "Bermuda" },
				{ LanguageId.mua, "bermudiya" },
				{ LanguageId.my, "ဘာမြူဒါ" },
				{ LanguageId.mzn, "برمودا" },
				{ LanguageId.naq, "Bermudas" },
				{ LanguageId.nb, "Bermuda" },
				{ LanguageId.nd, "Bhemuda" },
				{ LanguageId.nds, "Bermuda" },
				{ LanguageId.ne, "बर्मुडा" },
				{ LanguageId.nl, "Bermuda" },
				{ LanguageId.nmg, "Bɛrmuda" },
				{ LanguageId.nn, "Bermuda" },
				{ LanguageId.nnh, "Bermuda" },
				{ LanguageId.nqo, "ߓߍߙߑߓߎߘ" },
				{ LanguageId.nr, "Bermuda" },
				{ LanguageId.nso, "Bermuda" },
				{ LanguageId.nus, "Be̱rmudaa" },
				{ LanguageId.nyn, "Berimuda" },
				{ LanguageId.oc, "Bermuda" },
				{ LanguageId.om, "Beermudaa" },
				{ LanguageId.or, "ବର୍ମୁଡା" },
				{ LanguageId.os, "Бермуды" },
				{ LanguageId.pa, "ਬਰਮੂਡਾ" },
				{ LanguageId.pap, "Bermuda" },
				{ LanguageId.pcm, "Bẹmiúda" },
				{ LanguageId.pl, "Bermudy" },
				{ LanguageId.prg, "Bermuda" },
				{ LanguageId.ps, "برمودا" },
				{ LanguageId.pt, "Bermudas" },
				{ LanguageId.qu, "Bermudas" },
				{ LanguageId.quc, "Bermuda" },
				{ LanguageId.rm, "Bermudas" },
				{ LanguageId.rn, "Berimuda" },
				{ LanguageId.ro, "Bermuda" },
				{ LanguageId.rof, "Bermuda" },
				{ LanguageId.ru, "Бермудские о-ва" },
				{ LanguageId.rw, "Bermuda" },
				{ LanguageId.rwk, "Bermuda" },
				{ LanguageId.sa, "बर्मूडा" },
				{ LanguageId.sah, "Бермуды" },
				{ LanguageId.saq, "Bermuda" },
				{ LanguageId.sat, "ᱵᱚᱨᱢᱩᱰᱟ" },
				{ LanguageId.sbp, "Belimuda" },
				{ LanguageId.sd, "برمودا" },
				{ LanguageId.se, "Bermuda" },
				{ LanguageId.seh, "Bermudas" },
				{ LanguageId.ses, "Bermuda" },
				{ LanguageId.sg, "Beremûda" },
				{ LanguageId.shi, "ⴱⵔⵎⵓⴷⴰ" },
				{ LanguageId.si, "බර්මියුඩා" },
				{ LanguageId.sk, "Bermudy" },
				{ LanguageId.sl, "Bermudi" },
				{ LanguageId.sma, "Bermuda" },
				{ LanguageId.smj, "Bermuda" },
				{ LanguageId.smn, "Bermuda" },
				{ LanguageId.sms, "Bermuda" },
				{ LanguageId.sn, "Bermuda" },
				{ LanguageId.so, "Barmuuda" },
				{ LanguageId.sq, "Bermude" },
				{ LanguageId.sr, "Бермуди" },
				{ LanguageId.ss, "Bermuda" },
				{ LanguageId.ssy, "Bermuda" },
				{ LanguageId.st, "Bermuda" },
				{ LanguageId.su, "Bermuda" },
				{ LanguageId.sv, "Bermuda" },
				{ LanguageId.sw, "Bermuda" },
				{ LanguageId.syr, "ܒܝܪܡܘܕܐ" },
				{ LanguageId.ta, "பெர்முடா" },
				{ LanguageId.te, "బెర్ముడా" },
				{ LanguageId.teo, "Bermuda" },
				{ LanguageId.tg, "Бермуда" },
				{ LanguageId.th, "เบอร์มิวดา" },
				{ LanguageId.ti, "በርሙዳ" },
				{ LanguageId.tig, "በርሙዳ" },
				{ LanguageId.tk, "Bermuda" },
				{ LanguageId.tn, "Bermuda" },
				{ LanguageId.to, "Pēmuta" },
				{ LanguageId.tr, "Bermuda" },
				{ LanguageId.ts, "Bermuda" },
				{ LanguageId.tt, "Бермуд утраулары" },
				{ LanguageId.twq, "Bermuda" },
				{ LanguageId.tzm, "Birmuda" },
				{ LanguageId.ug, "بېرمۇدا" },
				{ LanguageId.uk, "Бермудські Острови" },
				{ LanguageId.ur, "برمودا" },
				{ LanguageId.uz, "Bermuda orollari" },
				{ LanguageId.vai, "ꗩꖷꕜ" },
				{ LanguageId.ve, "Bermuda" },
				{ LanguageId.vi, "Bermuda" },
				{ LanguageId.vo, "Bermuda" },
				{ LanguageId.vun, "Bermuda" },
				{ LanguageId.wae, "Bermuda" },
				{ LanguageId.wal, "Bermuda" },
				{ LanguageId.wo, "Bermid" },
				{ LanguageId.xh, "EBermuda" },
				{ LanguageId.xog, "Beremuda" },
				{ LanguageId.yav, "Pɛlmúta" },
				{ LanguageId.yi, "בערמודע" },
				{ LanguageId.yo, "Bémúdà" },
				{ LanguageId.zgh, "ⴱⵔⵎⵓⴷⴰ" },
				{ LanguageId.zh, "百慕大" },
				{ LanguageId.zu, "i-Bermuda" },
			}
		);
	}
}
