// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BN
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "673",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Brunei Darussalam" },
				{ LanguageId.da, "Brunei" },
				{ LanguageId.af, "Broenei" },
				{ LanguageId.agq, "Bɨ̀lunè" },
				{ LanguageId.ak, "Brunae" },
				{ LanguageId.am, "ብሩኒ" },
				{ LanguageId.ar, "بروناي" },
				{ LanguageId.arn, "Brunei Darussalam" },
				{ LanguageId.@as, "ব্ৰুনেই" },
				{ LanguageId.asa, "Brunei" },
				{ LanguageId.ast, "Brunéi" },
				{ LanguageId.az, "Bruney" },
				{ LanguageId.ba, "Бруней" },
				{ LanguageId.bas, "Brunei" },
				{ LanguageId.be, "Бруней" },
				{ LanguageId.bem, "Brunei Darussalam" },
				{ LanguageId.bez, "Hubrunei" },
				{ LanguageId.bg, "Бруней Даруссалам" },
				{ LanguageId.bin, "Brunei Darussalam" },
				{ LanguageId.bm, "Burinɛyi" },
				{ LanguageId.bn, "ব্রুনেই" },
				{ LanguageId.bo, "བུ་རུ་ནེ་ད་རུ་ས་ལམ།" },
				{ LanguageId.br, "Brunei" },
				{ LanguageId.brx, "ब्रूने" },
				{ LanguageId.bs, "Brunej" },
				{ LanguageId.byn, "Brunei Darussalam" },
				{ LanguageId.ca, "Brunei" },
				{ LanguageId.ccp, "𑄝𑄳𑄢𑄪𑄚𑄬𑄭" },
				{ LanguageId.ce, "Бруней-Даруссалам" },
				{ LanguageId.ceb, "Brunei" },
				{ LanguageId.cgg, "Burunei" },
				{ LanguageId.chr, "ᏊᎾᎢ" },
				{ LanguageId.ckb, "بروونای" },
				{ LanguageId.co, "Brunei Darussalam" },
				{ LanguageId.cs, "Brunej" },
				{ LanguageId.cu, "Брунеи" },
				{ LanguageId.cy, "Brunei" },
				{ LanguageId.dav, "Brunei" },
				{ LanguageId.de, "Brunei Darussalam" },
				{ LanguageId.dje, "Bruunee" },
				{ LanguageId.doi, "ब्रुनेई दारुसलाम" },
				{ LanguageId.dsb, "Brunei" },
				{ LanguageId.dua, "Brunei Darussalam" },
				{ LanguageId.dv, "ބުރުނާއީ ދާރުއްސަލާމް" },
				{ LanguageId.dz, "བྷྲུ་ནའི" },
				{ LanguageId.ebu, "Brunei" },
				{ LanguageId.ee, "Brunei nutome" },
				{ LanguageId.el, "Μπρουνέι" },
				{ LanguageId.en, "Brunei" },
				{ LanguageId.eo, "Brunejo" },
				{ LanguageId.es, "Brunéi" },
				{ LanguageId.et, "Brunei" },
				{ LanguageId.eu, "Brunei" },
				{ LanguageId.ewo, "Buluné" },
				{ LanguageId.fa, "برونئی" },
				{ LanguageId.ff, "Burnaay" },
				{ LanguageId.fi, "Brunei" },
				{ LanguageId.fil, "Brunei" },
				{ LanguageId.fo, "Brunei" },
				{ LanguageId.fr, "Brunei" },
				{ LanguageId.fur, "Brunei" },
				{ LanguageId.fy, "Brunei" },
				{ LanguageId.ga, "Brúiné" },
				{ LanguageId.gd, "Brùnaigh" },
				{ LanguageId.gl, "Brunei" },
				{ LanguageId.gn, "Brunei Darussalam" },
				{ LanguageId.gsw, "Brunäi Tarussalam" },
				{ LanguageId.gu, "બ્રુનેઇ" },
				{ LanguageId.guz, "Brunei" },
				{ LanguageId.gv, "Brunei Darussalam" },
				{ LanguageId.ha, "Burune" },
				{ LanguageId.haw, "Brunei Darussalam" },
				{ LanguageId.he, "ברוניי" },
				{ LanguageId.hi, "ब्रूनेई" },
				{ LanguageId.hr, "Brunej" },
				{ LanguageId.hsb, "Brunei" },
				{ LanguageId.hu, "Brunei" },
				{ LanguageId.hy, "Բրունեյ" },
				{ LanguageId.ia, "Brunei" },
				{ LanguageId.ibb, "Brunei Darussalam" },
				{ LanguageId.id, "Brunei" },
				{ LanguageId.ig, "Brunei" },
				{ LanguageId.ii, "文莱达鲁萨兰国" },
				{ LanguageId.@is, "Brúnei" },
				{ LanguageId.it, "Brunei" },
				{ LanguageId.iu, "ᐳᕉᓂ" },
				{ LanguageId.ja, "ブルネイ" },
				{ LanguageId.jgo, "Brunei Darussalam" },
				{ LanguageId.jmc, "Brunei" },
				{ LanguageId.jv, "Brunéi" },
				{ LanguageId.ka, "ბრუნეი" },
				{ LanguageId.kab, "Bruney" },
				{ LanguageId.kam, "Brunei" },
				{ LanguageId.kde, "Blunei" },
				{ LanguageId.kea, "Brunei" },
				{ LanguageId.khq, "Bruunee" },
				{ LanguageId.ki, "Brunei" },
				{ LanguageId.kk, "Бруней" },
				{ LanguageId.kkj, "Brunei Darussalam" },
				{ LanguageId.kl, "Brunei Darussalam" },
				{ LanguageId.kln, "Emetab Brunei" },
				{ LanguageId.km, "ព្រុយណេ" },
				{ LanguageId.kn, "ಬ್ರೂನಿ" },
				{ LanguageId.ko, "브루나이" },
				{ LanguageId.kok, "ब्रूनेई" },
				{ LanguageId.kr, "Brunei Darussalam" },
				{ LanguageId.ks, "برونے" },
				{ LanguageId.ksb, "Blunei" },
				{ LanguageId.ksf, "brunǝ́" },
				{ LanguageId.ksh, "Brunei" },
				{ LanguageId.kw, "Brunei Darussalam" },
				{ LanguageId.ky, "Бруней" },
				{ LanguageId.la, "Bruneium Darussalam" },
				{ LanguageId.lag, "Burunéei" },
				{ LanguageId.lb, "Brunei" },
				{ LanguageId.lg, "Burunayi" },
				{ LanguageId.lkt, "Brunei Darussalam" },
				{ LanguageId.ln, "Brineyi" },
				{ LanguageId.lo, "ບຣູໄນ" },
				{ LanguageId.lrc, "بروٙنئی دارالسئلام" },
				{ LanguageId.lt, "Brunėjus" },
				{ LanguageId.luo, "Brunei" },
				{ LanguageId.luy, "Brunei" },
				{ LanguageId.lv, "Bruneja" },
				{ LanguageId.mai, "ब्रूनेई" },
				{ LanguageId.mas, "Brunei" },
				{ LanguageId.mer, "Brunei" },
				{ LanguageId.mfe, "Brunei" },
				{ LanguageId.mg, "Brunei" },
				{ LanguageId.mgo, "Brunei Darussalam" },
				{ LanguageId.mi, "Poronai" },
				{ LanguageId.mk, "Брунеј" },
				{ LanguageId.ml, "ബ്രൂണൈ" },
				{ LanguageId.mn, "Бруней" },
				{ LanguageId.mni, "ব্ৰুনাই দাৰুছালাম" },
				{ LanguageId.moh, "Brunei Darussalam" },
				{ LanguageId.mr, "ब्रुनेई" },
				{ LanguageId.ms, "Brunei" },
				{ LanguageId.mt, "il-Brunei" },
				{ LanguageId.mua, "bruniya" },
				{ LanguageId.my, "ဘရူနိုင်း" },
				{ LanguageId.mzn, "برونئی" },
				{ LanguageId.naq, "Brunei" },
				{ LanguageId.nb, "Brunei" },
				{ LanguageId.nd, "Brunei" },
				{ LanguageId.nds, "Brunei Darussalam" },
				{ LanguageId.ne, "ब्रुनाइ" },
				{ LanguageId.nl, "Brunei" },
				{ LanguageId.nmg, "Brunɛi" },
				{ LanguageId.nn, "Brunei" },
				{ LanguageId.nnh, "Brunei Darussalam" },
				{ LanguageId.nqo, "ߓߙߎߣߋ߫" },
				{ LanguageId.nr, "Brunei Darussalam" },
				{ LanguageId.nso, "Brunei Darussalam" },
				{ LanguageId.nus, "Burunɛy" },
				{ LanguageId.nyn, "Burunei" },
				{ LanguageId.oc, "Brunei Darussalam" },
				{ LanguageId.om, "Biruniyee" },
				{ LanguageId.or, "ବ୍ରୁନେଇ" },
				{ LanguageId.os, "Бруней" },
				{ LanguageId.pa, "ਬਰੂਨੇਈ" },
				{ LanguageId.pap, "Brunei Darussalam" },
				{ LanguageId.pcm, "Brunẹi" },
				{ LanguageId.pl, "Brunei" },
				{ LanguageId.prg, "Brunei Darussalam" },
				{ LanguageId.ps, "برونائي" },
				{ LanguageId.pt, "Brunei" },
				{ LanguageId.qu, "Brunéi" },
				{ LanguageId.quc, "Brunei Darussalam" },
				{ LanguageId.rm, "Brunei" },
				{ LanguageId.rn, "Buruneyi" },
				{ LanguageId.ro, "Brunei" },
				{ LanguageId.rof, "Brunei" },
				{ LanguageId.ru, "Бруней" },
				{ LanguageId.rw, "Brunei Darussalam" },
				{ LanguageId.rwk, "Brunei" },
				{ LanguageId.sa, "ब्रुनेई" },
				{ LanguageId.sah, "Бруней" },
				{ LanguageId.saq, "Brunei" },
				{ LanguageId.sat, "ᱵᱨᱩᱱᱟᱭ" },
				{ LanguageId.sbp, "Buluneyi" },
				{ LanguageId.sd, "برونائي" },
				{ LanguageId.se, "Brunei" },
				{ LanguageId.seh, "Brunei" },
				{ LanguageId.ses, "Bruunee" },
				{ LanguageId.sg, "Brunêi" },
				{ LanguageId.shi, "ⴱⵔⵓⵏⵉ" },
				{ LanguageId.si, "බෲනායි" },
				{ LanguageId.sk, "Brunej" },
				{ LanguageId.sl, "Brunej" },
				{ LanguageId.sma, "Brunei Darussalam" },
				{ LanguageId.smj, "Brunei Darussalam" },
				{ LanguageId.smn, "Brunei" },
				{ LanguageId.sms, "Brunei Darussalam" },
				{ LanguageId.sn, "Burunei" },
				{ LanguageId.so, "Buruneey" },
				{ LanguageId.sq, "Brunei" },
				{ LanguageId.sr, "Брунеј" },
				{ LanguageId.ss, "Brunei Darussalam" },
				{ LanguageId.ssy, "Brunei Darussalam" },
				{ LanguageId.st, "Brunei Darussalam" },
				{ LanguageId.su, "Brunei Darussalam" },
				{ LanguageId.sv, "Brunei" },
				{ LanguageId.sw, "Brunei" },
				{ LanguageId.syr, "ܒܪܘܢܐܝ" },
				{ LanguageId.ta, "புருனே" },
				{ LanguageId.te, "బ్రూనే" },
				{ LanguageId.teo, "Brunei" },
				{ LanguageId.tg, "Бруней" },
				{ LanguageId.th, "บรูไน" },
				{ LanguageId.ti, "ብሩነይ" },
				{ LanguageId.tig, "ብሩናይ" },
				{ LanguageId.tk, "Bruneý" },
				{ LanguageId.tn, "Brunei Darussalam" },
				{ LanguageId.to, "Pulunei" },
				{ LanguageId.tr, "Brunei" },
				{ LanguageId.ts, "Brunei Darussalam" },
				{ LanguageId.tt, "Бруней" },
				{ LanguageId.twq, "Bruunee" },
				{ LanguageId.tzm, "Brunay" },
				{ LanguageId.ug, "بىرۇنېي" },
				{ LanguageId.uk, "Бруней" },
				{ LanguageId.ur, "برونائی" },
				{ LanguageId.uz, "Bruney" },
				{ LanguageId.vai, "ꖜꖩꘉꔧ" },
				{ LanguageId.ve, "Brunei Darussalam" },
				{ LanguageId.vi, "Brunei" },
				{ LanguageId.vo, "Brunei Darussalam" },
				{ LanguageId.vun, "Brunei" },
				{ LanguageId.wae, "Brunei" },
				{ LanguageId.wal, "Brunei Darussalam" },
				{ LanguageId.wo, "Burney" },
				{ LanguageId.xh, "eBrunei" },
				{ LanguageId.xog, "Burunayi" },
				{ LanguageId.yav, "Pulunéy" },
				{ LanguageId.yi, "ברוניי" },
				{ LanguageId.yo, "Búrúnẹ́lì" },
				{ LanguageId.zgh, "ⴱⵔⵓⵏⵉ" },
				{ LanguageId.zh, "文莱" },
				{ LanguageId.zu, "i-Brunei" },
			}
		);
	}
}
