using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BN
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "673",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Brunei Darussalam" },
				{ LanguageId.af, "Brunei Darussalam" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ብሩኒ ዳሩሳላም።" },
				{ LanguageId.ar, "بروناي دار السلام" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Bruney Darussalam" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Бруней-Даруссалам" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Бруней Даруссалам" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ব্রুনাই দারুসসালাম" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Brunej Darussalam" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Brunei Darussalam" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Brunei Darussalam" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Brunei Darussalam" },
				{ LanguageId.cs, "Brunej Darussalam" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Brunei Darussalam" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Brunei Darussalam" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Μπρουνάι Νταρουσαλάμ" },
				{ LanguageId.en, "Brunei Darussalam" },
				{ LanguageId.eo, "Brunejo Darussalam" },
				{ LanguageId.es, "Brunei Darussalam" },
				{ LanguageId.et, "Brunei Darussalam" },
				{ LanguageId.eu, "Brunei Darussalam" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "برونئی دارالسلام" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Brunei Darussalam" },
				{ LanguageId.fil, "Brunei Darussalam" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Brunei Darussalam" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Brunei Darussalam" },
				{ LanguageId.ga, "Brúiné Dárasalám" },
				{ LanguageId.gd, "Brunei Darussalam" },
				{ LanguageId.gl, "Brunei Darussalam" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "બ્રુનેઇ દારુસલામ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Brunei Darussalam" },
				{ LanguageId.haw, "Brunei Darussalam" },
				{ LanguageId.he, "ברוניי דארוסלאם" },
				{ LanguageId.hi, "ब्रूनेइ्र दारएस्सलाम" },
				{ LanguageId.hr, "Brunei Darussalam" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Brunei Darussalam" },
				{ LanguageId.hy, "Բրունեյ Դարուսսալամ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Brunei Darussalam" },
				{ LanguageId.ig, "Brunei Darussalam" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Brúnei Darussalam" },
				{ LanguageId.it, "Brunei Darussalam" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ブルネイ ダルサラーム" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Brunei Darussalam" },
				{ LanguageId.ka, "ბრუნეი დარუსალამი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Бруней-Даруссалам" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ប្រទេស​ព្រុយ​ណេ​ដា​រូ​សា​ឡឹម" },
				{ LanguageId.kn, "ಬ್ರೂನಿ ದಾರುಸ್ಸಲಾಮ್" },
				{ LanguageId.ko, "브루나이 다루살람" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Бруней Даруссалам" },
				{ LanguageId.la, "Bruneium Darussalam" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Brunei Darussalam" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ບຣູໄນ ດາຣູຊາລາມ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Brunėjus Darusalamas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Bruneja Darusalama" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Brunei Darussalam" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Brunei Darussalam" },
				{ LanguageId.mk, "Брунеи Дарусалам" },
				{ LanguageId.ml, "ബ്രൂണെ ദാറുസ്സലാം" },
				{ LanguageId.mn, "Бруней Даруссалам" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "ब्रुनेई दारुसलाम" },
				{ LanguageId.ms, "Brunei Darussalam" },
				{ LanguageId.mt, "Brunei Darussalam" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဘရူနိုင်း ဒါရုစလမ်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Brunei Darussalam" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "ब्रुनाई दारुसलाम" },
				{ LanguageId.nl, "Brunei Darussalam" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ବ୍ରୁନେଇ ଦାରୁସଲାମ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬਰੂਨੇਈ ਦਾਰੂਸਲਾਮ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Brunei Darussalam" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "برونای دارالسلام" },
				{ LanguageId.pt, "Brunei Darussalam" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Brunei Darussalam" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Бруней-Даруссалам" },
				{ LanguageId.rw, "Brunei Darussalam" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "برونائي دارالسلام" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "බෲනායි දරුස්සලාම්" },
				{ LanguageId.sk, "Brunej Darussalam" },
				{ LanguageId.sl, "Brunej Darusalam" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Brunei Darussalam" },
				{ LanguageId.so, "Brunei Darussalam" },
				{ LanguageId.sq, "Brunei Darussalam" },
				{ LanguageId.sr, "Брунеј" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Brunei Darussalam" },
				{ LanguageId.su, "Brunei Darussalam" },
				{ LanguageId.sv, "Brunei Darussalam" },
				{ LanguageId.sw, "Brunei Darussalam" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "புருனே தருசலாம்" },
				{ LanguageId.te, "బ్రూనై దారుస్సలాం" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Бруней Доруссалом" },
				{ LanguageId.th, "บรูไนดารุสซาลาม" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Bruneý Darussalam" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Brunei Sultanlığı" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Бруней Даруссалам" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "برۇنېي دارۇسسالام" },
				{ LanguageId.uk, "Бруней Даруссалам" },
				{ LanguageId.ur, "برونائی دارالسلام" },
				{ LanguageId.uz, "Bruney Darussalam" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Vương quốc Bru-nây" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Brunei Darussalam" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "ברוניי דארוסלאם" },
				{ LanguageId.yo, "Brunei Darussalam" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "文莱达鲁萨兰国" },
				{ LanguageId.zu, "I-Brunei Darussalam" },
			}
		);
	}
}
