using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BN
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "673",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Brunei Darussalam" },
				{ LanguageId.da, "Brunei Darussalam" },
				{ LanguageId.af, "Brunei Darussalam" },
				{ LanguageId.agq, "Brunei Darussalam" },
				{ LanguageId.ak, "Brunei Darussalam" },
				{ LanguageId.am, "ብሩኒ ዳሩሳላም።" },
				{ LanguageId.ar, "بروناي دار السلام" },
				{ LanguageId.arn, "Brunei Darussalam" },
				{ LanguageId.@as, "ব্ৰুনাই দাৰুছালাম" },
				{ LanguageId.asa, "Brunei Darussalam" },
				{ LanguageId.ast, "Brunei Darussalam" },
				{ LanguageId.az, "Bruney Darussalam" },
				{ LanguageId.ba, "Бруней-Даруссалам" },
				{ LanguageId.bas, "Brunei Darussalam" },
				{ LanguageId.be, "Бруней-Даруссалам" },
				{ LanguageId.bem, "Brunei Darussalam" },
				{ LanguageId.bez, "Brunei Darussalam" },
				{ LanguageId.bg, "Бруней Даруссалам" },
				{ LanguageId.bin, "Brunei Darussalam" },
				{ LanguageId.bm, "Brunei Darussalam" },
				{ LanguageId.bn, "ব্রুনাই দারুসসালাম" },
				{ LanguageId.bo, "བུ་རུ་ནེ་ད་རུ་ས་ལམ།" },
				{ LanguageId.br, "Brunei" },
				{ LanguageId.brx, "ब्रुनाइ दारुस्सलाम" },
				{ LanguageId.bs, "Brunej Darussalam" },
				{ LanguageId.byn, "Brunei Darussalam" },
				{ LanguageId.ca, "Brunei Darussalam" },
				{ LanguageId.ccp, "𑄝𑄳𑄢𑄪𑄚𑄬𑄭 𑄘𑄢𑄪𑄥𑄴𑄥𑄣𑄟𑄴" },
				{ LanguageId.ce, "Бруней-Даруссалам" },
				{ LanguageId.ceb, "Brunei Darussalam" },
				{ LanguageId.cgg, "Brunei Darussalam" },
				{ LanguageId.chr, "ᏊᎾᎢ" },
				{ LanguageId.ckb, "بروونای" },
				{ LanguageId.co, "Brunei Darussalam" },
				{ LanguageId.cs, "Brunej Darussalam" },
				{ LanguageId.cu, "Брунеи" },
				{ LanguageId.cy, "Brunei Darussalam" },
				{ LanguageId.dav, "Brunei Darussalam" },
				{ LanguageId.de, "Brunei Darussalam" },
				{ LanguageId.dje, "Brunei Darussalam" },
				{ LanguageId.doi, "ब्रुनेई दारुसलाम" },
				{ LanguageId.dsb, "Brunei" },
				{ LanguageId.dua, "Brunei Darussalam" },
				{ LanguageId.dv, "ބުރުނާއީ ދާރުއްސަލާމް" },
				{ LanguageId.dz, "བུ་རུ་ནེ་ད་རུ་ས་ལམ།" },
				{ LanguageId.ebu, "Brunei Darussalam" },
				{ LanguageId.ee, "Brunei Darussalam" },
				{ LanguageId.el, "Μπρουνάι Νταρουσαλάμ" },
				{ LanguageId.en, "Brunei Darussalam" },
				{ LanguageId.eo, "Brunejo Darussalam" },
				{ LanguageId.es, "Brunei Darussalam" },
				{ LanguageId.et, "Brunei Darussalam" },
				{ LanguageId.eu, "Brunei Darussalam" },
				{ LanguageId.ewo, "Brunei Darussalam" },
				{ LanguageId.fa, "برونئی دارالسلام" },
				{ LanguageId.ff, "Brunei Darussalam" },
				{ LanguageId.fi, "Brunei Darussalam" },
				{ LanguageId.fil, "Brunei Darussalam" },
				{ LanguageId.fo, "Brunei Darussalam" },
				{ LanguageId.fr, "Brunei Darussalam" },
				{ LanguageId.fur, "Brunei Darussalam" },
				{ LanguageId.fy, "Brunei Darussalam" },
				{ LanguageId.ga, "Brúiné Dárasalám" },
				{ LanguageId.gd, "Brunei Darussalam" },
				{ LanguageId.gl, "Brunei Darussalam" },
				{ LanguageId.gn, "Brunei Darussalam" },
				{ LanguageId.gsw, "Brunei Darussalam" },
				{ LanguageId.gu, "બ્રુનેઇ દારુસલામ" },
				{ LanguageId.guz, "Brunei Darussalam" },
				{ LanguageId.gv, "Brunei Darussalam" },
				{ LanguageId.ha, "Brunei Darussalam" },
				{ LanguageId.haw, "Brunei Darussalam" },
				{ LanguageId.he, "ברוניי דארוסלאם" },
				{ LanguageId.hi, "ब्रूनेइ्र दारएस्सलाम" },
				{ LanguageId.hr, "Brunei Darussalam" },
				{ LanguageId.hsb, "Brunei" },
				{ LanguageId.hu, "Brunei Darussalam" },
				{ LanguageId.hy, "Բրունեյ Դարուսսալամ" },
				{ LanguageId.ia, "Brunei Darussalam" },
				{ LanguageId.ibb, "Brunei Darussalam" },
				{ LanguageId.id, "Brunei Darussalam" },
				{ LanguageId.ig, "Brunei Darussalam" },
				{ LanguageId.ii, "文莱达鲁萨兰国" },
				{ LanguageId.@is, "Brúnei Darussalam" },
				{ LanguageId.it, "Brunei Darussalam" },
				{ LanguageId.iu, "ᐳᕉᓂ" },
				{ LanguageId.ja, "ブルネイ ダルサラーム" },
				{ LanguageId.jgo, "Brunei Darussalam" },
				{ LanguageId.jmc, "Brunei Darussalam" },
				{ LanguageId.jv, "Brunei Darussalam" },
				{ LanguageId.ka, "ბრუნეი დარუსალამი" },
				{ LanguageId.kab, "Brunei Darussalam" },
				{ LanguageId.kam, "Brunei Darussalam" },
				{ LanguageId.kde, "Brunei Darussalam" },
				{ LanguageId.kea, "Brunei Darussalam" },
				{ LanguageId.khq, "Brunei Darussalam" },
				{ LanguageId.ki, "Brunei Darussalam" },
				{ LanguageId.kk, "Бруней-Даруссалам" },
				{ LanguageId.kkj, "Brunei Darussalam" },
				{ LanguageId.kl, "Brunei Darussalam" },
				{ LanguageId.kln, "Brunei Darussalam" },
				{ LanguageId.km, "ប្រទេស​ព្រុយ​ណេ​ដា​រូ​សា​ឡឹម" },
				{ LanguageId.kn, "ಬ್ರೂನಿ ದಾರುಸ್ಸಲಾಮ್" },
				{ LanguageId.ko, "브루나이 다루살람" },
				{ LanguageId.kok, "ब्रुनेई दारुसलाम" },
				{ LanguageId.kr, "Brunei Darussalam" },
				{ LanguageId.ks, "برونائی دارالسلام" },
				{ LanguageId.ksb, "Brunei Darussalam" },
				{ LanguageId.ksf, "Brunei Darussalam" },
				{ LanguageId.ksh, "Brunei Darussalam" },
				{ LanguageId.kw, "Brunei Darussalam" },
				{ LanguageId.ky, "Бруней Даруссалам" },
				{ LanguageId.la, "Bruneium Darussalam" },
				{ LanguageId.lag, "Brunei Darussalam" },
				{ LanguageId.lb, "Brunei Darussalam" },
				{ LanguageId.lg, "Brunei Darussalam" },
				{ LanguageId.lkt, "Brunei Darussalam" },
				{ LanguageId.ln, "Brunei Darussalam" },
				{ LanguageId.lo, "ບຣູໄນ ດາຣູຊາລາມ" },
				{ LanguageId.lrc, "بروٙنئی دارالسئلام" },
				{ LanguageId.lt, "Brunėjus Darusalamas" },
				{ LanguageId.luo, "Brunei Darussalam" },
				{ LanguageId.luy, "Brunei Darussalam" },
				{ LanguageId.lv, "Bruneja Darusalama" },
				{ LanguageId.mai, "ब्रुनेई दारुसलाम" },
				{ LanguageId.mas, "Brunei Darussalam" },
				{ LanguageId.mer, "Brunei Darussalam" },
				{ LanguageId.mfe, "Brunei Darussalam" },
				{ LanguageId.mg, "Brunei Darussalam" },
				{ LanguageId.mgo, "Brunei Darussalam" },
				{ LanguageId.mi, "Brunei Darussalam" },
				{ LanguageId.mk, "Брунеи Дарусалам" },
				{ LanguageId.ml, "ബ്രൂണെ ദാറുസ്സലാം" },
				{ LanguageId.mn, "Бруней Даруссалам" },
				{ LanguageId.mni, "ব্ৰুনাই দাৰুছালাম" },
				{ LanguageId.moh, "Brunei Darussalam" },
				{ LanguageId.mr, "ब्रुनेई दारुसलाम" },
				{ LanguageId.ms, "Brunei Darussalam" },
				{ LanguageId.mt, "Brunei Darussalam" },
				{ LanguageId.mua, "Brunei Darussalam" },
				{ LanguageId.my, "ဘရူနိုင်း ဒါရုစလမ်" },
				{ LanguageId.mzn, "برونئی دارالسلام" },
				{ LanguageId.naq, "Brunei Darussalam" },
				{ LanguageId.nb, "Brunei Darussalam" },
				{ LanguageId.nd, "Brunei Darussalam" },
				{ LanguageId.nds, "Brunei Darussalam" },
				{ LanguageId.ne, "ब्रुनाई दारुसलाम" },
				{ LanguageId.nl, "Brunei Darussalam" },
				{ LanguageId.nmg, "Brunei Darussalam" },
				{ LanguageId.nn, "Brunei Darussalam" },
				{ LanguageId.nnh, "Brunei Darussalam" },
				{ LanguageId.nqo, "ߓߙߎߣߍߌ" },
				{ LanguageId.nr, "Brunei Darussalam" },
				{ LanguageId.nso, "Brunei Darussalam" },
				{ LanguageId.nus, "Brunei Darussalam" },
				{ LanguageId.nyn, "Brunei Darussalam" },
				{ LanguageId.oc, "Brunei Darussalam" },
				{ LanguageId.om, "Brunei Darussalam" },
				{ LanguageId.or, "ବ୍ରୁନେଇ ଦାରୁସଲାମ |" },
				{ LanguageId.os, "Бруней" },
				{ LanguageId.pa, "ਬਰੂਨੇਈ ਦਾਰੂਸਲਾਮ" },
				{ LanguageId.pap, "Brunei Darussalam" },
				{ LanguageId.pcm, "Brunei" },
				{ LanguageId.pl, "Brunei Darussalam" },
				{ LanguageId.prg, "Brunei Darussalam" },
				{ LanguageId.ps, "برونای دارالسلام" },
				{ LanguageId.pt, "Brunei Darussalam" },
				{ LanguageId.qu, "Brunei Darussalam" },
				{ LanguageId.quc, "Brunei Darussalam" },
				{ LanguageId.rm, "Brunei Darussalam" },
				{ LanguageId.rn, "Brunei Darussalam" },
				{ LanguageId.ro, "Brunei Darussalam" },
				{ LanguageId.rof, "Brunei Darussalam" },
				{ LanguageId.ru, "Бруней-Даруссалам" },
				{ LanguageId.rw, "Brunei Darussalam" },
				{ LanguageId.rwk, "Brunei Darussalam" },
				{ LanguageId.sa, "ब्रुनेई" },
				{ LanguageId.sah, "Бруней" },
				{ LanguageId.saq, "Brunei Darussalam" },
				{ LanguageId.sat, "ᱵᱨᱩᱱᱟᱭ" },
				{ LanguageId.sbp, "Brunei Darussalam" },
				{ LanguageId.sd, "برونائي دارالسلام" },
				{ LanguageId.se, "Brunei Darussalam" },
				{ LanguageId.seh, "Brunei Darussalam" },
				{ LanguageId.ses, "Brunei Darussalam" },
				{ LanguageId.sg, "Brunei Darussalam" },
				{ LanguageId.shi, "ⴱⵔⵓⵏⵉ" },
				{ LanguageId.si, "බෲනායි දරුස්සලාම්" },
				{ LanguageId.sk, "Brunej Darussalam" },
				{ LanguageId.sl, "Brunej Darusalam" },
				{ LanguageId.sma, "Brunei Darussalam" },
				{ LanguageId.smj, "Brunei Darussalam" },
				{ LanguageId.smn, "Brunei Darussalam" },
				{ LanguageId.sms, "Brunei Darussalam" },
				{ LanguageId.sn, "Brunei Darussalam" },
				{ LanguageId.so, "Brunei Darussalam" },
				{ LanguageId.sq, "Brunei Darussalam" },
				{ LanguageId.sr, "Брунеј" },
				{ LanguageId.ss, "Brunei Darussalam" },
				{ LanguageId.ssy, "Brunei Darussalam" },
				{ LanguageId.st, "Brunei Darussalam" },
				{ LanguageId.su, "Brunei Darussalam" },
				{ LanguageId.sv, "Brunei Darussalam" },
				{ LanguageId.sw, "Brunei Darussalam" },
				{ LanguageId.syr, "ܒܪܘܢܝ" },
				{ LanguageId.ta, "புருனே தருசலாம்" },
				{ LanguageId.te, "బ్రూనై దారుస్సలాం" },
				{ LanguageId.teo, "Brunei Darussalam" },
				{ LanguageId.tg, "Бруней Доруссалом" },
				{ LanguageId.th, "บรูไนดารุสซาลาม" },
				{ LanguageId.ti, "ብሩናይ ዳሩስሳላም" },
				{ LanguageId.tig, "ብሩናይ" },
				{ LanguageId.tk, "Bruneý Darussalam" },
				{ LanguageId.tn, "Brunei Darussalam" },
				{ LanguageId.to, "Pulunei" },
				{ LanguageId.tr, "Brunei Sultanlığı" },
				{ LanguageId.ts, "Brunei Darussalam" },
				{ LanguageId.tt, "Бруней Даруссалам" },
				{ LanguageId.twq, "Brunei Darussalam" },
				{ LanguageId.tzm, "ⴱⵔⵓⵏⵉ" },
				{ LanguageId.ug, "برۇنېي دارۇسسالام" },
				{ LanguageId.uk, "Бруней Даруссалам" },
				{ LanguageId.ur, "برونائی دارالسلام" },
				{ LanguageId.uz, "Bruney Darussalam" },
				{ LanguageId.vai, "ߓߙߎߣߍߌ" },
				{ LanguageId.ve, "Brunei Darussalam" },
				{ LanguageId.vi, "Vương quốc Bru-nây" },
				{ LanguageId.vo, "Brunei Darussalam" },
				{ LanguageId.vun, "Brunei Darussalam" },
				{ LanguageId.wae, "Brunei Darussalam" },
				{ LanguageId.wal, "Brunei Darussalam" },
				{ LanguageId.wo, "Brunei Darussalam" },
				{ LanguageId.xh, "Brunei Darussalam" },
				{ LanguageId.xog, "Brunei Darussalam" },
				{ LanguageId.yav, "Brunei Darussalam" },
				{ LanguageId.yi, "ברוניי דארוסלאם" },
				{ LanguageId.yo, "Brunei Darussalam" },
				{ LanguageId.zgh, "ⴱⵔⵓⵏⵉ" },
				{ LanguageId.zh, "文莱达鲁萨兰国" },
				{ LanguageId.zu, "I-Brunei Darussalam" },
			}
		);
	}
}
