// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BQ
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "599",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.da, "De tidligere Nederlandske Antiller" },
				{ LanguageId.af, "Karibiese Nederland" },
				{ LanguageId.agq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ak, "Caribbean Netherlands" },
				{ LanguageId.am, "የካሪቢያን ኔዘርላንድስ" },
				{ LanguageId.ar, "هولندا الكاريبية" },
				{ LanguageId.arn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.@as, "কেৰিবিয়ান নেদাৰলেণ্ডছ" },
				{ LanguageId.asa, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ast, "Caribe neerlandés" },
				{ LanguageId.az, "Karib Niderlandı" },
				{ LanguageId.ba, "Карибтағы Нидерланд" },
				{ LanguageId.bas, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.be, "Карыбскія Нідэрланды" },
				{ LanguageId.bem, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bez, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bg, "Карибска Нидерландия" },
				{ LanguageId.bin, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bm, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bn, "ক্যারিবিয়ান নেদারল্যান্ডস" },
				{ LanguageId.bo, "བཱོ་ནེར།" },
				{ LanguageId.br, "Karib Nederlandat" },
				{ LanguageId.brx, "केरिबियान नेदारलेण्डस" },
				{ LanguageId.bs, "Karipska Holandija" },
				{ LanguageId.byn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ca, "Carib Neerlandès" },
				{ LanguageId.ccp, "𑄇𑄳𑄠𑄢𑄨𑄝𑄨𑄠𑄚𑄴 𑄚𑄬𑄘𑄢𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄧𑄥𑄴" },
				{ LanguageId.ce, "Бонэйр, Синт-Эстатиус а, Саба а" },
				{ LanguageId.ceb, "Caribbean Netherlands" },
				{ LanguageId.cgg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.chr, "ᎧᎵᏈᎢᏂᎯ ᎾᏍᎩᏁᏛᎳᏂ" },
				{ LanguageId.ckb, "دوورگە کاریبیەکانی هۆڵەندا" },
				{ LanguageId.co, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.cs, "Karibské Nizozemsko" },
				{ LanguageId.cu, "Карибьскꙑ Нидерландꙑ" },
				{ LanguageId.cy, "Antilles yr Iseldiroedd" },
				{ LanguageId.dav, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.de, "Karibische Niederlande" },
				{ LanguageId.dje, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.doi, "बोनेयर, सिंट युस्तातियुस अर साबा" },
				{ LanguageId.dsb, "Karibiska Nižozemska" },
				{ LanguageId.dua, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.dv, "ބޮނެއަރ، ސިންޓް އިއުސްޓޭޓިއުސް އަދި ސަބާ" },
				{ LanguageId.dz, "ཀེ་རི་བི་ཡེན་ནེ་དར་ལནཌས྄" },
				{ LanguageId.ebu, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ee, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.el, "Ολλανδία Καραϊβικής" },
				{ LanguageId.en, "Caribbean Netherlands" },
				{ LanguageId.eo, "Kariba Nederlando" },
				{ LanguageId.es, "Caribe neerlandés" },
				{ LanguageId.et, "Kariibi Madalmaad" },
				{ LanguageId.eu, "Karibeko Herbehereak" },
				{ LanguageId.ewo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.fa, "جزایر کارائیب هلند" },
				{ LanguageId.ff, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.fi, "Karibian Alankomaat" },
				{ LanguageId.fil, "Caribbean Netherlands" },
				{ LanguageId.fo, "Niðurlonds Karibia" },
				{ LanguageId.fr, "Pays-Bas caribéens" },
				{ LanguageId.fur, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.fy, "Karibysk Nederlân" },
				{ LanguageId.ga, "an Ísiltír Chairibeach" },
				{ LanguageId.gd, "Na Tìrean Ìsle Caraibeach" },
				{ LanguageId.gl, "Caribe Neerlandés" },
				{ LanguageId.gn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.gsw, "Karibischi Niiderlande" },
				{ LanguageId.gu, "કેરેબિયન નેધરલેન્ડ્ઝ" },
				{ LanguageId.guz, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.gv, "Bonaire, Sint Eustatius as Saba" },
				{ LanguageId.ha, "Caribbean Netherlands" },
				{ LanguageId.haw, "Caribbean Netherlands" },
				{ LanguageId.he, "האיים הקריביים ההולנדיים" },
				{ LanguageId.hi, "कैरिबियन नीदरलैंड" },
				{ LanguageId.hr, "Karipski otoci Nizozemske" },
				{ LanguageId.hsb, "Karibiska Nižozemska" },
				{ LanguageId.hu, "Holland Karib-térség" },
				{ LanguageId.hy, "Կարիբյան Նիդեռլանդներ" },
				{ LanguageId.ia, "Paises Basse caribe" },
				{ LanguageId.ibb, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.id, "Belanda Karibia" },
				{ LanguageId.ig, "Caribbean Netherlands" },
				{ LanguageId.ii, "荷蘭加勒比區" },
				{ LanguageId.@is, "Karíbahafshluti Hollands" },
				{ LanguageId.it, "Caraibi Olandesi" },
				{ LanguageId.iu, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ja, "オランダ領カリブ" },
				{ LanguageId.jgo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.jmc, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.jv, "Karibia Walanda" },
				{ LanguageId.ka, "კარიბის ნიდერლანდები" },
				{ LanguageId.kab, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kam, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kde, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kea, "Karaibas Olandezas" },
				{ LanguageId.khq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ki, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kk, "Бонэйр, Синт-Эстатиус және Саба" },
				{ LanguageId.kkj, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kl, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kln, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.km, "ហូឡង់ ការ៉ាប៊ីន" },
				{ LanguageId.kn, "ಕೆರೀಬಿಯನ್ ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್" },
				{ LanguageId.ko, "네덜란드령 카리브" },
				{ LanguageId.kok, "कॅरिबियन नॅदरलँड" },
				{ LanguageId.kr, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ks, "کیریبین نیدرلینڈس" },
				{ LanguageId.ksb, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ksf, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ksh, "de karribbesche Nederläng" },
				{ LanguageId.kw, "Bonaire, Sint Eustatius ha Saba" },
				{ LanguageId.ky, "Кариб Нидерланддары" },
				{ LanguageId.la, "Bonaire, Sint Eustatius et Saba" },
				{ LanguageId.lag, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lb, "Karibescht Holland" },
				{ LanguageId.lg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lkt, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ln, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lo, "ຄາຣິບບຽນ ເນເທີແລນ" },
				{ LanguageId.lrc, "ھولەنە کاریبی" },
				{ LanguageId.lt, "Karibų Nyderlandai" },
				{ LanguageId.luo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.luy, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lv, "Nīderlandes Karību salas" },
				{ LanguageId.mai, "कैरिबियाई नीदरलैंड" },
				{ LanguageId.mas, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mer, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mfe, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mg, "Bonaire, Sint Eustatius sy Saba" },
				{ LanguageId.mgo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mi, "Karapīana Hōrana" },
				{ LanguageId.mk, "Карипска Холандија" },
				{ LanguageId.ml, "കരീബിയൻ നെതർലാൻഡ്സ്" },
				{ LanguageId.mn, "Карибын Нидерланд" },
				{ LanguageId.mni, "বনেয়াৰ, ছিণ্ট ইউষ্টেটিয়াছ আৰু ছাবা" },
				{ LanguageId.moh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mr, "कॅरिबियन नेदरलँड्स" },
				{ LanguageId.ms, "Belanda Caribbean" },
				{ LanguageId.mt, "in-Netherlands tal-Karibew" },
				{ LanguageId.mua, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.my, "ကာရစ်ဘီယံ နယ်သာလန်" },
				{ LanguageId.mzn, "هلند ِکاراییبی جزایر" },
				{ LanguageId.naq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nb, "Karibisk Nederland" },
				{ LanguageId.nd, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nds, "Karibisch Nedderland" },
				{ LanguageId.ne, "क्यारिवियन नेदरल्याण्ड्स" },
				{ LanguageId.nl, "Caribisch Nederland" },
				{ LanguageId.nmg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nn, "Karibisk Nederland" },
				{ LanguageId.nnh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nqo, "ߤߏߟߊ߲ߘ ߞߊߙߌߓߋ߫" },
				{ LanguageId.nr, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nso, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nus, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nyn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.oc, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.om, "Neezerlaandota Kariibaan" },
				{ LanguageId.or, "କାରବିୟନ୍‌ ନେଦରଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Карибы Нидерландтæ" },
				{ LanguageId.pa, "ਕੈਰੇਬੀਆਈ ਨੀਦਰਲੈਂਡ" },
				{ LanguageId.pap, "Boneiru, Sint Eustatius y Saba" },
				{ LanguageId.pcm, "Karíbián Nẹ́dalands" },
				{ LanguageId.pl, "Niderlandy Karaibskie" },
				{ LanguageId.prg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ps, "کیریبین هالینډ" },
				{ LanguageId.pt, "Países Baixos Caribenhos" },
				{ LanguageId.qu, "Bonaire" },
				{ LanguageId.quc, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.rm, "Pajais Bass caribics" },
				{ LanguageId.rn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ro, "Insulele Caraibe Olandeze" },
				{ LanguageId.rof, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ru, "Бонэйр, Синт-Эстатиус и Саба" },
				{ LanguageId.rw, "Bonaire, Sint Eustatius na Saba" },
				{ LanguageId.rwk, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sa, "बोनेर, सिंट युस्तातियुस तथा साबा" },
				{ LanguageId.sah, "Карибскай Недерлаандтар" },
				{ LanguageId.saq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sat, "ᱵᱚᱱᱮᱨ, ᱥᱤᱸᱴ ᱤᱣᱥᱴᱟᱥᱤᱭᱟᱥ ᱟᱨ ᱥᱟᱵᱟ" },
				{ LanguageId.sbp, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sd, "ڪيريبين نيدرلينڊ" },
				{ LanguageId.se, "Bonaire, Sint Eustatius ja Saba" },
				{ LanguageId.seh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ses, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.shi, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.si, "කැරිබියානු නෙදර්ලන්තය" },
				{ LanguageId.sk, "Karibské Holandsko" },
				{ LanguageId.sl, "Nizozemski Karibi" },
				{ LanguageId.sma, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.smj, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.smn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sms, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sn, "Bonaire, Sint Eustatius naSaba" },
				{ LanguageId.so, "Karibiyaan Nadarlands" },
				{ LanguageId.sq, "Karaibet holandeze" },
				{ LanguageId.sr, "Карипска Холандија" },
				{ LanguageId.ss, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ssy, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.st, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.su, "Bonaire, Sint Eustatius sareng Saba" },
				{ LanguageId.sv, "Karibiska Nederländerna" },
				{ LanguageId.sw, "Uholanzi ya Karibiani" },
				{ LanguageId.syr, "ܟܐܪܝܒܐ ܕܢܝܬܝܪܠܐܢܕܣ" },
				{ LanguageId.ta, "கரீபியன் நெதர்லாந்து" },
				{ LanguageId.te, "కరీబియన్ నెదర్లాండ్స్" },
				{ LanguageId.teo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tg, "Кариби Нидерланд" },
				{ LanguageId.th, "เนเธอร์แลนด์แคริบเบียน" },
				{ LanguageId.ti, "ካሪብያን ኔዘርላንድ" },
				{ LanguageId.tig, "ቦነይር" },
				{ LanguageId.tk, "Karib Niderlandlary" },
				{ LanguageId.tn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.to, "Kalipiane fakahōlani" },
				{ LanguageId.tr, "Karayip Hollandası" },
				{ LanguageId.ts, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tt, "Кариб Нидерландлары" },
				{ LanguageId.twq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tzm, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.ug, "كارىب دېڭىزى گوللاندىيە" },
				{ LanguageId.uk, "Карибські Нідерланди" },
				{ LanguageId.ur, "کریبیائی نیدرلینڈز" },
				{ LanguageId.uz, "Boneyr, Sint-Estatius va Saba" },
				{ LanguageId.vai, "ꕪꔓꔬꘂꘋ ꖨꕮ ꗨꗳꗣ" },
				{ LanguageId.ve, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.vi, "Ca-ri-bê Hà Lan" },
				{ LanguageId.vo, "Bonaire, Sint Eustatius äd Saba" },
				{ LanguageId.vun, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.wae, "Karibisch Niiderlande" },
				{ LanguageId.wal, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.wo, "Pays-Bas bu Caraïbe" },
				{ LanguageId.xh, "ECaribbean Netherlands" },
				{ LanguageId.xog, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.yav, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.yi, "באָנאַירע, סינט אייסטאטיוס און סאבא" },
				{ LanguageId.yo, "Kàríbíánì ti Nẹ́dálándì" },
				{ LanguageId.zgh, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.zh, "荷属加勒比区" },
				{ LanguageId.zu, "i-Caribbean Netherlands" },
			}
		);
	}
}
