using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class BQ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "599",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.da, "Caribisk Nederlandene" },
				{ LanguageId.af, "Karibiese Nederland" },
				{ LanguageId.agq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ak, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.am, "የካሪቢያን ኔዘርላንድስ" },
				{ LanguageId.ar, "الجزر الكاريبية الهولندية" },
				{ LanguageId.arn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.@as, "বনেয়াৰ, ছিণ্ট ইউষ্টেটিয়াছ আৰু ছাবা" },
				{ LanguageId.asa, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ast, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.az, "Karib Niderlandı" },
				{ LanguageId.ba, "Кариб Нидерландтары" },
				{ LanguageId.bas, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.be, "Карыбскія Нідэрланды" },
				{ LanguageId.bem, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bez, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bg, "Карибска Нидерландия" },
				{ LanguageId.bin, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bm, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.bn, "ক্যারিবীয় নেদারল্যান্ডস" },
				{ LanguageId.bo, "བཱོ་ནེར།" },
				{ LanguageId.br, "Bonaire, Sint Eustatius ha Saba" },
				{ LanguageId.brx, "बोनेयर, सिंट युस्तातियुस आरो साबा" },
				{ LanguageId.bs, "Karibi Nizozemska" },
				{ LanguageId.byn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ca, "Bonaire, Sint Eustatius i Saba" },
				{ LanguageId.ccp, "𑄝𑄮𑄚𑄬𑄠𑄢𑄴, 𑄥𑄨𑄚𑄴𑄑𑄴 𑄃𑄨𑄅𑄪𑄌𑄴𑄑𑄬𑄑𑄨𑄠𑄌𑄴 𑄃𑄳𑄃 𑄥𑄝" },
				{ LanguageId.ce, "Карибски Нидерланд" },
				{ LanguageId.ceb, "Caribbean Netherlands" },
				{ LanguageId.cgg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.chr, "ᎧᎵᏇᎢᏂ ᎾᏍᎳᏅᎢ" },
				{ LanguageId.ckb, "ھۆڵەندای کاریبی" },
				{ LanguageId.co, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.cs, "Karibské Nizozemsko" },
				{ LanguageId.cu, "Карибьскꙑ Нидерландꙑ" },
				{ LanguageId.cy, "Antilles yr Iseldiroedd" },
				{ LanguageId.dav, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.de, "Karibische Niederlande" },
				{ LanguageId.dje, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.doi, "बोनेयर, सिंट युस्तातियुस अर साबा" },
				{ LanguageId.dsb, "Karibiske Nižozemske" },
				{ LanguageId.dua, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.dv, "ބޮނެއަރ، ސިންޓް އިއުސްޓޭޓިއުސް އަދި ސަބާ" },
				{ LanguageId.dz, "བཱོ་ནེར།" },
				{ LanguageId.ebu, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ee, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.el, "Καραϊβική Ολλανδία" },
				{ LanguageId.en, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.eo, "Karibia Nederlando" },
				{ LanguageId.es, "Caribe Neerlandés" },
				{ LanguageId.et, "Bonaire, Sint Eustatius ja Saba" },
				{ LanguageId.eu, "Bonaire, Sint Eustatius eta Saba" },
				{ LanguageId.ewo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.fa, "هلند کارائیب" },
				{ LanguageId.ff, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.fi, "Bonaire, Sint Eustatius ja Saba" },
				{ LanguageId.fil, "Caribbean Netherlands" },
				{ LanguageId.fo, "Bonaire, Sint Eustatius og Saba" },
				{ LanguageId.fr, "Pays-Bas caribéens" },
				{ LanguageId.fur, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.fy, "Karibysk Nederlân" },
				{ LanguageId.ga, "An Ísiltír Chairibeanach" },
				{ LanguageId.gd, "An Òlaind Chairibeach" },
				{ LanguageId.gl, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.gn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.gsw, "Karibischi Niiderlande" },
				{ LanguageId.gu, "બોનેર, સિન્ટ યુસ્ટેટિયસ અને સબા" },
				{ LanguageId.guz, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.gv, "Bonaire, Sint Eustatius as Saba" },
				{ LanguageId.ha, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.haw, "Caribbean Netherlands" },
				{ LanguageId.he, "האיים הקאריביים ההולנדיים" },
				{ LanguageId.hi, "बोनेयर, सिंट यूस्टेशस और साबा" },
				{ LanguageId.hr, "Bonaire, Sint Eustatius i Saba" },
				{ LanguageId.hsb, "Karibiske Nižozemske" },
				{ LanguageId.hu, "Bonaire" },
				{ LanguageId.hy, "Կարիբյան Նիդերլանդներ" },
				{ LanguageId.ia, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ibb, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.id, "Belanda Karibia" },
				{ LanguageId.ig, "Caribbean Netherlands" },
				{ LanguageId.ii, "荷蘭加勒比區" },
				{ LanguageId.@is, "Bonaire, Sint Eustatius og Saba" },
				{ LanguageId.it, "Paesi Bassi caraibici" },
				{ LanguageId.iu, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ja, "BES諸島" },
				{ LanguageId.jgo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.jmc, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.jv, "Bonaire, Sint Eustatius lan Saba" },
				{ LanguageId.ka, "კარიბის ნიდერლანდები" },
				{ LanguageId.kab, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kam, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kde, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kea, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.khq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ki, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kk, "Кариб Нидерланды" },
				{ LanguageId.kkj, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kl, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.kln, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.km, "បូណែរ ស៊ីនធ៍ អឺស្តាស៊ីស និងសាបា" },
				{ LanguageId.kn, "ಬೊನೈರ್, ಸಿಂಟ್ ಯುಸ್ಟೇಶಿಯಸ್ ಮತ್ತು ಸಬಾ" },
				{ LanguageId.ko, "카리브 네덜란드" },
				{ LanguageId.kok, "बोनेर, सिंट युस्तातियुस आणी साबा" },
				{ LanguageId.kr, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ks, "بونیر، سنٹ یوسٹیٹیس اور صبا" },
				{ LanguageId.ksb, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ksf, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ksh, "Bonaire, Sint Eustatius un Saba" },
				{ LanguageId.kw, "Bonaire, Sint Eustatius ha Saba" },
				{ LanguageId.ky, "Кариб Нидерланды" },
				{ LanguageId.la, "Bonaire, Sint Eustatius et Saba" },
				{ LanguageId.lag, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lb, "Karibescht Nidderlanden" },
				{ LanguageId.lg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lkt, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ln, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lo, "ໂບແນຣ, ຊິນ ເອີສຕາສຽສ ແລະ ຊາບາ" },
				{ LanguageId.lrc, "ھولەنە کاریبی" },
				{ LanguageId.lt, "Bonaire, Sint Eustatius ir Saba" },
				{ LanguageId.luo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.luy, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.lv, "Bonaire, Sint Eustatius un Saba" },
				{ LanguageId.mai, "बोनेयर, सिंट युस्तातियुस आरो साबा" },
				{ LanguageId.mas, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mer, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mfe, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mg, "Bonaire, Sint Eustatius sy Saba" },
				{ LanguageId.mgo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mi, "Bonaire, Sint Eustatius me Saba" },
				{ LanguageId.mk, "Бонер, Свети Евстатиј и Саба" },
				{ LanguageId.ml, "ബൊണെയർ, സിന്റ് യൂസ്റ്റേഷ്യസ്, സാബ" },
				{ LanguageId.mn, "Бонэйр, Синт-Эстатиус ба Саба" },
				{ LanguageId.mni, "বনেয়াৰ, ছিণ্ট ইউষ্টেটিয়াছ আৰু ছাবা" },
				{ LanguageId.moh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.mr, "बोनेर, सिंट युस्तातियुस आणि साबा" },
				{ LanguageId.ms, "Bonaire, Sint Eustatius dan Saba" },
				{ LanguageId.mt, "Bonaire, Sint Eustatius u Saba" },
				{ LanguageId.mua, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.my, "ဘိုနေးရ်၊ စင့်ယူစတေးရှင်စ်နှင့် ဆာဘာ" },
				{ LanguageId.mzn, "کارائیب هلند" },
				{ LanguageId.naq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nb, "Bonaire, Sint Eustatius og Saba" },
				{ LanguageId.nd, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nds, "Karibisch Nedderland" },
				{ LanguageId.ne, "बोनेयर, सिन्ट युस्टेटियस र साबा" },
				{ LanguageId.nl, "Bonaire, Sint Eustatius en Saba" },
				{ LanguageId.nmg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nn, "Bonaire, Sint Eustatius og Saba" },
				{ LanguageId.nnh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nqo, "ߓߏߣߍߙߌ߫" },
				{ LanguageId.nr, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nso, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nus, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.nyn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.oc, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.om, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.or, "ବୋନେର, ସିଣ୍ଟ ୟୁସ୍ତାଟସ ଏବଂ ସାବା" },
				{ LanguageId.os, "Карибы Нидерландтæ" },
				{ LanguageId.pa, "ਬੋਨੇਅਰ, ਸਿੰਟ ਯੂਸਟੇਸ਼ਿਯਸ ਅਤੇ ਸਾਬਾ" },
				{ LanguageId.pap, "Boneiru, Sint Eustatius y Saba" },
				{ LanguageId.pcm, "Caribbean Netherlands" },
				{ LanguageId.pl, "Antyle Holenderskie" },
				{ LanguageId.prg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ps, "بونیر، سینټ یوسټاتیوس او صابا" },
				{ LanguageId.pt, "Países Baixos Caribenhos" },
				{ LanguageId.qu, "Bonaire, Sint Eustatius, Saba" },
				{ LanguageId.quc, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.rm, "Bonaire, Sint Eustatius e Saba" },
				{ LanguageId.rn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ro, "Bonaire, Sint Eustatius și Saba" },
				{ LanguageId.rof, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ru, "Карибские Нидерланды" },
				{ LanguageId.rw, "Bonaire, Sint Eustatius na Saba" },
				{ LanguageId.rwk, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sa, "बोनेर, सिंट युस्तातियुस तथा साबा" },
				{ LanguageId.sah, "Карибскай Недерлаандтар" },
				{ LanguageId.saq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sat, "ᱵᱚᱱᱮᱨ, ᱥᱤᱸᱴ ᱤᱣᱥᱴᱟᱥᱤᱭᱟᱥ ᱟᱨ ᱥᱟᱵᱟ" },
				{ LanguageId.sbp, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sd, "بونير، سنٽ يوسٽيٽس ۽ صبا" },
				{ LanguageId.se, "Bonaire, Sint Eustatius ja Saba" },
				{ LanguageId.seh, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ses, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sg, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.shi, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.si, "බොනෙයාර්, සින්ට් යුස්ටේසියස් සහ සබා" },
				{ LanguageId.sk, "Bonaire, Sint Eustatius a Saba" },
				{ LanguageId.sl, "Bonaire, Sint Eustatius in Saba" },
				{ LanguageId.sma, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.smj, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.smn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sms, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.sn, "Bonaire, Sint Eustatius naSaba" },
				{ LanguageId.so, "Bonaire, Sint Eustatius iyo Saba" },
				{ LanguageId.sq, "Bonaire, Sint Eustatius dhe Saba" },
				{ LanguageId.sr, "Karipska Holandija" },
				{ LanguageId.ss, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.ssy, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.st, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.su, "Bonaire, Sint Eustatius sareng Saba" },
				{ LanguageId.sv, "Karibiska Nederländerna" },
				{ LanguageId.sw, "Bonaire, Sint Eustatius na Saba" },
				{ LanguageId.syr, "ܒܘܢܝܪ، ܣܝܢܛ ܐܘܣܬܐܬܝܘܣ ܘܣܒܐ" },
				{ LanguageId.ta, "போனயர், சின்ட் யூஸ்டேஷியஸ் மற்றும் சபா" },
				{ LanguageId.te, "బోనైర్, సింట్ యుస్టేటియస్ మరియు సబా" },
				{ LanguageId.teo, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tg, "Бонайр, Синт-Эстатиус ва Саба" },
				{ LanguageId.th, "โบแนร์ ซินต์เอิสตาซียึส และซาบา" },
				{ LanguageId.ti, "ቦነይር፣ ሲንት ዩስታቲየስን ሳባን" },
				{ LanguageId.tig, "ቦነይር" },
				{ LanguageId.tk, "Bonaire, Sint Eustatius we Saba" },
				{ LanguageId.tn, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.to, "Ponea, Sinte ʻEusetāsio mo Sapa" },
				{ LanguageId.tr, "Karayip Hollandası" },
				{ LanguageId.ts, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tt, "Кариб Нидерландлары" },
				{ LanguageId.twq, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.tzm, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.ug, "بونەر، سىنت ئېۋستاتىئۇس ۋە سابا" },
				{ LanguageId.uk, "Бонайре, Сінт-Естатіус і Саба" },
				{ LanguageId.ur, "کیریبین نیدرلینڈز" },
				{ LanguageId.uz, "Boner, Sint-Evstatius va Saba" },
				{ LanguageId.vai, "ߓߏߣߍߙߌ߫" },
				{ LanguageId.ve, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.vi, "Bonaire, Sint Eustatius và Saba" },
				{ LanguageId.vo, "Bonaire, Sint Eustatius äd Saba" },
				{ LanguageId.vun, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.wae, "Karibisch Niiderlande" },
				{ LanguageId.wal, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.wo, "Bonaire, Sint Eustatius ak Saba" },
				{ LanguageId.xh, "Bonaire, Sint Eustatius noSaba" },
				{ LanguageId.xog, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.yav, "Bonaire, Sint Eustatius and Saba" },
				{ LanguageId.yi, "באָנאַירע, סינט אייסטאטיוס און סאבא" },
				{ LanguageId.yo, "Bonaire, Sint Eustatius ati Saba" },
				{ LanguageId.zgh, "ⴱⵓⵏⵉⵔ" },
				{ LanguageId.zh, "荷蘭加勒比區" },
				{ LanguageId.zu, "I-Bonaire, Sint Eustatius ne-Saba" },
			}
		);
	}
}
