// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class BS
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Bahamas" },
				{ LanguageId.af, "Bahamas" },
				{ LanguageId.agq, "Bàhamàs" },
				{ LanguageId.ak, "Bahamase" },
				{ LanguageId.am, "ባሃማስ" },
				{ LanguageId.ar, "جزر البهاما" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "বাহামাছ" },
				{ LanguageId.asa, "Bahama" },
				{ LanguageId.ast, "Les Bahames" },
				{ LanguageId.az, "Baham adaları" },
				{ LanguageId.ba, "Багам утрауҙары" },
				{ LanguageId.bas, "Bàhamàs" },
				{ LanguageId.be, "Багамскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hubahama" },
				{ LanguageId.bg, "Бахамски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Bahamasi" },
				{ LanguageId.bn, "বাহামা দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Bahamas" },
				{ LanguageId.brx, "बाहामास" },
				{ LanguageId.bs, "Bahami" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Bahames" },
				{ LanguageId.ccp, "𑄝𑄦𑄟 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Багаман гӀайренаш" },
				{ LanguageId.ceb, "Bahamas" },
				{ LanguageId.cgg, "Bahama" },
				{ LanguageId.chr, "ᎾᏍᎩ ᏆᎭᎹᏍ" },
				{ LanguageId.ckb, "بەھاما" },
				{ LanguageId.co, "Bahamas" },
				{ LanguageId.cs, "Bahamy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Bahamas" },
				{ LanguageId.dav, "Bahama" },
				{ LanguageId.de, "Bahamas" },
				{ LanguageId.dje, "Bahamas" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Bahamy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "བྷ་ཧ་མས྄" },
				{ LanguageId.ebu, "Bahama" },
				{ LanguageId.ee, "Bahamas nutome" },
				{ LanguageId.el, "Μπαχάμες" },
				{ LanguageId.en, "Bahamas" },
				{ LanguageId.eo, "Bahamoj" },
				{ LanguageId.es, "Bahamas" },
				{ LanguageId.et, "Bahama" },
				{ LanguageId.eu, "Bahamak" },
				{ LanguageId.ewo, "Bahámas" },
				{ LanguageId.fa, "باهاما" },
				{ LanguageId.ff, "Bahamaas" },
				{ LanguageId.fi, "Bahama" },
				{ LanguageId.fil, "Bahamas" },
				{ LanguageId.fo, "Bahamaoyggjar" },
				{ LanguageId.fr, "Bahamas" },
				{ LanguageId.fur, "Bahamas" },
				{ LanguageId.fy, "Bahama’s" },
				{ LanguageId.ga, "na Bahámaí" },
				{ LanguageId.gd, "Na h-Eileanan Bhathama" },
				{ LanguageId.gl, "Bahamas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Bahaamas" },
				{ LanguageId.gu, "બહામાસ" },
				{ LanguageId.guz, "Bahama" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Bahamas" },
				{ LanguageId.haw, "Pahama" },
				{ LanguageId.he, "איי בהאמה" },
				{ LanguageId.hi, "बहामास" },
				{ LanguageId.hr, "Bahami" },
				{ LanguageId.hsb, "Bahamy" },
				{ LanguageId.hu, "Bahama-szigetek" },
				{ LanguageId.hy, "Բահամյան կղզիներ" },
				{ LanguageId.ia, "Bahamas" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Bahama" },
				{ LanguageId.ig, "Bahamas" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bahamaeyjar" },
				{ LanguageId.it, "Bahamas" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "バハマ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Bahama" },
				{ LanguageId.jv, "Bahama" },
				{ LanguageId.ka, "ბაჰამის კუნძულები" },
				{ LanguageId.kab, "Bahamas" },
				{ LanguageId.kam, "Bahama" },
				{ LanguageId.kde, "Bahama" },
				{ LanguageId.kea, "Baamas" },
				{ LanguageId.khq, "Bahamas" },
				{ LanguageId.ki, "Bahama" },
				{ LanguageId.kk, "Багам аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Bahamas" },
				{ LanguageId.km, "បាហាម៉ា" },
				{ LanguageId.kn, "ಬಹಾಮಾಸ್" },
				{ LanguageId.ko, "바하마" },
				{ LanguageId.kok, "बाहामास" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "بَہامَس" },
				{ LanguageId.ksb, "Bahama" },
				{ LanguageId.ksf, "baamás" },
				{ LanguageId.ksh, "de Bahamas" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Багама аралдары" },
				{ LanguageId.la, "Bahamas" },
				{ LanguageId.lag, "Baháama" },
				{ LanguageId.lb, "Bahamas" },
				{ LanguageId.lg, "Bahamasi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bahamasɛ" },
				{ LanguageId.lo, "ບາຮາມາສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Bahamos" },
				{ LanguageId.luo, "Bahamas" },
				{ LanguageId.luy, "Bahama" },
				{ LanguageId.lv, "Bahamu salas" },
				{ LanguageId.mai, "बहामास" },
				{ LanguageId.mas, "Bahama" },
				{ LanguageId.mer, "Bahamasi" },
				{ LanguageId.mfe, "Bahamas" },
				{ LanguageId.mg, "Bahamas" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Pahama" },
				{ LanguageId.mk, "Бахами" },
				{ LanguageId.ml, "ബഹാമാസ്" },
				{ LanguageId.mn, "Багамын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "बहामाज" },
				{ LanguageId.ms, "Bahamas" },
				{ LanguageId.mt, "il-Bahamas" },
				{ LanguageId.mua, "bahamas" },
				{ LanguageId.my, "ဘဟားမား" },
				{ LanguageId.mzn, "باهاما" },
				{ LanguageId.naq, "Bahamas" },
				{ LanguageId.nb, "Bahamas" },
				{ LanguageId.nd, "Bhahamas" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "बहामास" },
				{ LanguageId.nl, "Bahama’s" },
				{ LanguageId.nmg, "Bahamas" },
				{ LanguageId.nn, "Bahamas" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߓߤߊߡߊߛ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Bämuɔth" },
				{ LanguageId.nyn, "Bahama" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Bahaamas" },
				{ LanguageId.or, "ବାହାମାସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬਹਾਮਾਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Bahámas" },
				{ LanguageId.pl, "Bahamy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "باهماس" },
				{ LanguageId.pt, "Bahamas" },
				{ LanguageId.qu, "Bahamas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Bahamas" },
				{ LanguageId.rn, "Bahamasi" },
				{ LanguageId.ro, "Bahamas" },
				{ LanguageId.rof, "Bahamasi" },
				{ LanguageId.ru, "Багамы" },
				{ LanguageId.rw, "Bahamas" },
				{ LanguageId.rwk, "Bahama" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Bahama" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Bahama" },
				{ LanguageId.sd, "باهاماس" },
				{ LanguageId.se, "Bahamas" },
				{ LanguageId.seh, "Bahamas" },
				{ LanguageId.ses, "Bahamas" },
				{ LanguageId.sg, "Bahâmasa" },
				{ LanguageId.shi, "ⴱⴰⵀⴰⵎⴰⵙ" },
				{ LanguageId.si, "බහමාස්" },
				{ LanguageId.sk, "Bahamy" },
				{ LanguageId.sl, "Bahami" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Bahama" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Bahama" },
				{ LanguageId.so, "Bahaamas" },
				{ LanguageId.sq, "Bahama" },
				{ LanguageId.sr, "Бахами" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Bahamas" },
				{ LanguageId.su, "Bahama" },
				{ LanguageId.sv, "Bahamas" },
				{ LanguageId.sw, "Bahama" },
				{ LanguageId.syr, "ܒܗܐܡܣ" },
				{ LanguageId.ta, "பஹாமாஸ்" },
				{ LanguageId.te, "బహామాస్" },
				{ LanguageId.teo, "Bahama" },
				{ LanguageId.tg, "Багам" },
				{ LanguageId.th, "บาฮามาส" },
				{ LanguageId.ti, "ባሃማስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Bagama adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Pahama" },
				{ LanguageId.tr, "Bahamalar" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Багам утраулары" },
				{ LanguageId.twq, "Bahamas" },
				{ LanguageId.tzm, "Bahamas" },
				{ LanguageId.ug, "باھاما" },
				{ LanguageId.uk, "Багамські Острови" },
				{ LanguageId.ur, "بہاماس" },
				{ LanguageId.uz, "Bagama orollari" },
				{ LanguageId.vai, "ꕑꕌꕮꔻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Bahamas" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Bahama" },
				{ LanguageId.wae, "Bahamas" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Bahamas" },
				{ LanguageId.xh, "EBahamas" },
				{ LanguageId.xog, "Bahamasi" },
				{ LanguageId.yav, "Pahámas" },
				{ LanguageId.yi, "באַהאַמאַס" },
				{ LanguageId.yo, "Bàhámásì" },
				{ LanguageId.zgh, "ⴱⴰⵀⴰⵎⴰⵙ" },
				{ LanguageId.zh, "巴哈马" },
				{ LanguageId.zu, "i-Bahamas" },
			}
		);
	}
}
