using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CD
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "243",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Demokratiske Republik Congo" },
				{ LanguageId.af, "Demokratiese Republiek van die Kongo" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዲሞክራቲክ ሩፑብሊክ ኮንጎ" },
				{ LanguageId.ar, "جمهورية الكونغو الديموقراطية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Konqo Demokratik Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Дэмакратычная Рэспубліка Конга" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Демократична република Конго" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "গণপ্রজাতান্ত্রিক কঙ্গো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Kongo-Kinshasa" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Demokratska Republika Kongo" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Democràtica del Congo" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Demokratikong Republika sa Congo" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Republica Democratica di Congo" },
				{ LanguageId.cs, "Demokratická republika Kongo" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Ddemocrataidd y Congo" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Demokratische Republik Kongo" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Λαϊκή Δημοκρατία του Κονγκό" },
				{ LanguageId.en, "Democratic Republic of the Congo" },
				{ LanguageId.eo, "Demokratia Respubliko Kongo" },
				{ LanguageId.es, "República Democrática del Congo" },
				{ LanguageId.et, "Kongo Demokraatlik Vabariik" },
				{ LanguageId.eu, "Kongoko Errepublika Demokratikoa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری دموکراتیک کنگو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Kongon demokraattinen tasavalta" },
				{ LanguageId.fil, "Demokratikong Republika ng bansang Congo" },
				{ LanguageId.fo, "Kongo-Kinshasa" },
				{ LanguageId.fr, "République Démocratique du Congo" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Demokratyske Republyk de Kongo" },
				{ LanguageId.ga, "Poblacht Dhaonlathach an Chongó" },
				{ LanguageId.gd, "Poblachd Deamocratach a' Chongo" },
				{ LanguageId.gl, "República Democrática do Congo" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ડેમોક્રેટિક રિપબ્લિક ઓફ કોંગો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Demokradiyyar Kongo" },
				{ LanguageId.haw, "Lepupalika Kemokalaka ʻo Konokō" },
				{ LanguageId.he, "הרפובליקה הדמוקרטית של קונגו" },
				{ LanguageId.hi, "कांगो लोकतांत्रिक गणराज्य" },
				{ LanguageId.hr, "Demokratska Republika Kongo" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Kongói Demokratikus Köztársaság" },
				{ LanguageId.hy, "Կոնգոյի Դեմոկրատական ​​Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Demokrasi Kongo" },
				{ LanguageId.ig, "Democratic Republic of Congo" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Lýðveldið Kongó" },
				{ LanguageId.it, "Repubblica Democratica del Congo" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コンゴ民主共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Demokratik Kongo" },
				{ LanguageId.ka, "კონგოს დემოკრატიული რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Конго Демократиялық Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋប្រជាធិបតេយ្យកុងហ្គោ" },
				{ LanguageId.kn, "ಕಾಂಗೋ ಪ್ರಜಾಸತ್ತಾತ್ಮಕ ಗಣರಾಜ್ಯ" },
				{ LanguageId.ko, "콩고민주공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Конго демократиялык республикасы" },
				{ LanguageId.la, "Respublica Congensis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Demokratesch Republik vum Kongo" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Republiki ya Kongó Demokratiki" },
				{ LanguageId.lo, "ສາທາລະນະລັດປະຊາທິປະໄຕຄອງໂກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kongo Demokratinė Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Kongo Demokrātiskā Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Demokratikan'i Congo" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Repupiripia Manapori o Congo" },
				{ LanguageId.mk, "Демократска Република Конго" },
				{ LanguageId.ml, "ഡെമോക്രാറ്റിക് റിപ്പബ്ലിക് ഓഫ് കോംഗോ" },
				{ LanguageId.mn, "Бүгд Найрамдах Ардчилсан Конго Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "काँगोचे लोकशाही प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Demokratik Congo" },
				{ LanguageId.mt, "Repubblika Demokratika tal-Kongo" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကွန်ဂိုဒီမိုကရက်တစ်သမ္မတနိုင်ငံ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Den demokratiske republikken Kongo" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "प्रजातान्त्रिक गणतन्त्र कंगो" },
				{ LanguageId.nl, "Democratische Republiek Congo" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Kongo-Kinshasa" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଡେମୋକ୍ରାଟିକ୍ ରିପବ୍ଲିକ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕਾਂਗੋ ਦਾ ਲੋਕਤੰਤਰੀ ਗਣਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Demokratyczna Republika Konga" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د کانکو دیموکراتیک جمهوریت" },
				{ LanguageId.pt, "República Democrática do Congo" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Democrata din Congo" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Демократическая Республика Конго" },
				{ LanguageId.rw, "Repubulika Iharanira Demokarasi ya Kongo" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "عوامي جمهوريه ڪانگو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කොංගෝ ප්‍රජාතන්ත්‍රවාදී ජනරජය" },
				{ LanguageId.sk, "Konžská demokratická republika" },
				{ LanguageId.sl, "Demokratična republika Kongo" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Dhemokiratiki Ripabhuriki yeKongo" },
				{ LanguageId.so, "Jamhuuriyadda Dimuqraadiga ah ee Koongo" },
				{ LanguageId.sq, "Republika Demokratike e Kongos" },
				{ LanguageId.sr, "Демократска Република Конго" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Democratic Republic of the Congo" },
				{ LanguageId.su, "Républik Démokratik Kongo" },
				{ LanguageId.sv, "Demokratiska republiken Kongo" },
				{ LanguageId.sw, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "காங்கோ ஜனநாயக குடியரசு" },
				{ LanguageId.te, "డెమొక్రాటిక్ రిపబ్లిక్ ఆఫ్ ద కాంగో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Республикаи Демократии Конго" },
				{ LanguageId.th, "สาธารณรัฐประชาธิปไตยคองโก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kongo Demokratik Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Kongo Demokratik Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Конго Демократик Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "كونگو دېموكراتىك جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Демократична Республіка Конго" },
				{ LanguageId.ur, "جمہوری جمہوریہ کانگو" },
				{ LanguageId.uz, "Kongo Demokratik Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Dân chủ Congo" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iriphabliki yaseKhongo Ekhululekile" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "דעמאָקראַטיש רעפובליק פון קאָנגאָ" },
				{ LanguageId.yo, "Democratic Republic of Congo" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "刚果民主共和国" },
				{ LanguageId.zu, "IDemocratic Republic of the Congo" },
			}
		);
	}
}
