// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CD
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "243",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Congo-Kinshasa" },
				{ LanguageId.af, "Demokratiese Republiek van die Kongo" },
				{ LanguageId.agq, "Dɛ̀mùkàlatì Lèkpubèlè è Kuŋgù" },
				{ LanguageId.ak, "Kongo Kinhyaahya" },
				{ LanguageId.am, "ኮንጎ-ኪንሻሳ" },
				{ LanguageId.ar, "الكونغو - كينشاسا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "কঙ্গো - কিনচাছা" },
				{ LanguageId.asa, "Jamhuri ya Kidemokrathia ya Kongo" },
				{ LanguageId.ast, "Congu - Kinxasa" },
				{ LanguageId.az, "Konqo - Kinşasa" },
				{ LanguageId.ba, "Конго - Киншаса" },
				{ LanguageId.bas, "Kòŋgo ìkɛŋi" },
				{ LanguageId.be, "Конга (Кіншаса)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ijamhuri ya Hidemokrasi ya Hukongo" },
				{ LanguageId.bg, "Конго (Киншаса)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kongo ka republiki demɔkratiki" },
				{ LanguageId.bn, "কঙ্গো-কিনশাসা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Kongo - Kinshasa" },
				{ LanguageId.brx, "कंग’-किनशासा" },
				{ LanguageId.bs, "Demokratska Republika Kongo" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Congo - Kinshasa" },
				{ LanguageId.ccp, "𑄇𑄧𑄋𑄴𑄉𑄮-𑄚𑄨𑄇𑄴𑄥𑄥" },
				{ LanguageId.ce, "Демократин Республика Конго" },
				{ LanguageId.ceb, "Congo - Kinshasa" },
				{ LanguageId.cgg, "Demokoratika Ripaaburika ya Kongo" },
				{ LanguageId.chr, "ᎧᏂᎪ - ᎨᏂᏝᏌ" },
				{ LanguageId.ckb, "کۆنگۆ کینشاسا" },
				{ LanguageId.co, "Republica Democratica di Congo" },
				{ LanguageId.cs, "Kongo – Kinshasa" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Congo - Kinshasa" },
				{ LanguageId.dav, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.de, "Kongo-Kinshasa" },
				{ LanguageId.dje, "Kongoo demookaratiki laboo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Kongo-Kinshasa" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཀོང་གྷོ ཀིན་ཤ་ས" },
				{ LanguageId.ebu, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.ee, "Kongo Kinshasa nutome" },
				{ LanguageId.el, "Κονγκό - Κινσάσα" },
				{ LanguageId.en, "Congo - Kinshasa" },
				{ LanguageId.eo, "Kongo Kinŝasa" },
				{ LanguageId.es, "República Democrática del Congo" },
				{ LanguageId.et, "Kongo DV" },
				{ LanguageId.eu, "Kongoko Errepublika Demokratikoa" },
				{ LanguageId.ewo, "ǹnam Kongó Demokəlatíg" },
				{ LanguageId.fa, "کنگو - کینشاسا" },
				{ LanguageId.ff, "Ndenndaandi Demokaraasiire Konngo" },
				{ LanguageId.fi, "Kongon demokraattinen tasavalta" },
				{ LanguageId.fil, "Congo - Kinshasa" },
				{ LanguageId.fo, "Kongo, Dem. Lýðveldið" },
				{ LanguageId.fr, "Congo-Kinshasa" },
				{ LanguageId.fur, "Republiche Democratiche dal Congo" },
				{ LanguageId.fy, "Congo-Kinshasa" },
				{ LanguageId.ga, "Poblacht Dhaonlathach an Chongó" },
				{ LanguageId.gd, "Congo - Kinshasa" },
				{ LanguageId.gl, "República Democrática do Congo" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Temokraatischi Republik Kongo" },
				{ LanguageId.gu, "કોંગો - કિંશાસા" },
				{ LanguageId.guz, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Dimokuraɗiyyar Kongo" },
				{ LanguageId.haw, "Lepupalika Kemokalaka ʻo Konokō" },
				{ LanguageId.he, "קונגו - קינשאסה" },
				{ LanguageId.hi, "कांगो - किंशासा" },
				{ LanguageId.hr, "Kongo - Kinshasa" },
				{ LanguageId.hsb, "Kongo-Kinshasa" },
				{ LanguageId.hu, "Kongó – Kinshasa" },
				{ LanguageId.hy, "Կոնգո - Կինշասա" },
				{ LanguageId.ia, "Congo - Kinshasa" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kongo - Kinshasa" },
				{ LanguageId.ig, "Congo - Kinshasa" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Kongó-Kinshasa" },
				{ LanguageId.it, "Congo - Kinshasa" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コンゴ民主共和国(キンシャサ)" },
				{ LanguageId.jgo, "Kɔ́ŋgɔ-Kinshása" },
				{ LanguageId.jmc, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.jv, "Kongo - Kinshasa" },
				{ LanguageId.ka, "კონგო - კინშასა" },
				{ LanguageId.kab, "Tigduda Tagdudant n Kungu" },
				{ LanguageId.kam, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.kde, "Jamuhuli ya Chidemoklasia ya kuKongo" },
				{ LanguageId.kea, "Kongu - Kinxasa" },
				{ LanguageId.khq, "Kongoo demookaratiki laboo" },
				{ LanguageId.ki, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.kk, "Конго" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Congo - Kinshasa" },
				{ LanguageId.km, "កុងហ្គោ- គីនស្ហាសា" },
				{ LanguageId.kn, "ಕಾಂಗೋ - ಕಿನ್ಶಾಸಾ" },
				{ LanguageId.ko, "콩고-킨샤사" },
				{ LanguageId.kok, "काँगो - किंशासा" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "کونگو کِنشاسا" },
				{ LanguageId.ksb, "Jamhuli ya Kidemoklasia ya Kongo" },
				{ LanguageId.ksf, "kɔngó anyɔ́n" },
				{ LanguageId.ksh, "dä Konggo (Kinschasa)" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Конго-Киншаса" },
				{ LanguageId.la, "Respublica Congensis" },
				{ LanguageId.lag, "Jamuhúuri ya Kɨdemokurasía ya Kóongo" },
				{ LanguageId.lb, "Kongo-Kinshasa" },
				{ LanguageId.lg, "Kongo - Zayire" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Republíki ya Kongó Demokratíki" },
				{ LanguageId.lo, "ຄອງໂກ - ຄິນຊາຊາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kongas-Kinšasa" },
				{ LanguageId.luo, "Democratic Republic of the Congo" },
				{ LanguageId.luy, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.lv, "Kongo (Kinšasa)" },
				{ LanguageId.mai, "कांगो-किंशासा" },
				{ LanguageId.mas, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.mer, "Nthĩ ya Kidemokrasĩ ya Kongo" },
				{ LanguageId.mfe, "Repiblik demokratik Kongo" },
				{ LanguageId.mg, "Repoblikan’i Kongo" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Kōngo - Kinihāha" },
				{ LanguageId.mk, "Конго - Киншаса" },
				{ LanguageId.ml, "കോംഗോ - കിൻഷാസ" },
				{ LanguageId.mn, "Конго-Киншаса" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "काँगो - किंशासा" },
				{ LanguageId.ms, "Congo - Kinshasa" },
				{ LanguageId.mt, "ir-Repubblika Demokratika tal-Kongo" },
				{ LanguageId.mua, "Sǝr Kongo ma dii ne zair" },
				{ LanguageId.my, "ကွန်ဂို" },
				{ LanguageId.mzn, "کنگو کینشاسا" },
				{ LanguageId.naq, "Democratic Republic of the Congo" },
				{ LanguageId.nb, "Kongo" },
				{ LanguageId.nd, "Democratic Republic of the Congo" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कङ्गो - किन्शासा" },
				{ LanguageId.nl, "Congo-Kinshasa" },
				{ LanguageId.nmg, "Kongó Zaïre" },
				{ LanguageId.nn, "Kongo-Kinshasa" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߏ߲߬ߜ߭ߏ߫-ߞߌ߲ߛߊߛߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Demokoratika Ripaaburika ya Kongo" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Koongoo - Kinshaasaa" },
				{ LanguageId.or, "କଙ୍ଗୋ (ଡିଆରସି)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕਾਂਗੋ - ਕਿੰਸ਼ਾਸਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Kóngó – Kinshása" },
				{ LanguageId.pl, "Demokratyczna Republika Konga" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کانګو - کینشاسا" },
				{ LanguageId.pt, "Congo - Kinshasa" },
				{ LanguageId.qu, "Congo (RDC)" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Congo-Kinshasa" },
				{ LanguageId.rn, "Repubulika Iharanira Demokarasi ya Kongo" },
				{ LanguageId.ro, "Congo - Kinshasa" },
				{ LanguageId.rof, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.ru, "Конго - Киншаса" },
				{ LanguageId.rw, "Repubulika Iharanira Demokarasi ya Kongo" },
				{ LanguageId.rwk, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Jamuhuli ya Kidemokilasiya ya Kongo" },
				{ LanguageId.sd, "ڪانگو -ڪنشاسا" },
				{ LanguageId.se, "Kongo-Kinshasa" },
				{ LanguageId.seh, "Congo-Kinshasa" },
				{ LanguageId.ses, "Kongoo demookaratiki laboo" },
				{ LanguageId.sg, "Ködörösêse tî Ngunuhalëzo tî kongö" },
				{ LanguageId.shi, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵉⵎⵓⵇⵔⴰⵜⵉⵜ ⵏ ⴽⵓⵏⴳⵓ" },
				{ LanguageId.si, "කොංගෝව (ඩීආර්සී)" },
				{ LanguageId.sk, "Konžská demokratická republika" },
				{ LanguageId.sl, "Demokratična republika Kongo" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Kongo demokraattisâš täsiväldi" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Democratic Republic of the Congo" },
				{ LanguageId.so, "Jamhuuriyadda Dimuquraadiga Kongo" },
				{ LanguageId.sq, "Kongo-Kinshasa" },
				{ LanguageId.sr, "Конго - Киншаса" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Democratic Republic of the Congo" },
				{ LanguageId.su, "Républik Démokratik Kongo" },
				{ LanguageId.sv, "Kongo-Kinshasa" },
				{ LanguageId.sw, "Kongo - Kinshasa" },
				{ LanguageId.syr, "ܟܘܢܓܘ - ܟܝܢܫܐܣܐ" },
				{ LanguageId.ta, "காங்கோ - கின்ஷாசா" },
				{ LanguageId.te, "కాంగో- కిన్షాసా" },
				{ LanguageId.teo, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.tg, "Конго - Киншаса" },
				{ LanguageId.th, "คองโก - กินชาซา" },
				{ LanguageId.ti, "ደሞክራስያዊት ሪፓብሊክ ኮንጎ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kongo - Kinşasa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Kongo - Kinisasa" },
				{ LanguageId.tr, "Kongo - Kinşasa" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Конго (КДР)" },
				{ LanguageId.twq, "Kongoo demookaratiki laboo" },
				{ LanguageId.tzm, "Tagduda Tadimuqraṭit n Kungu" },
				{ LanguageId.ug, "كونگو - كىنشاسا" },
				{ LanguageId.uk, "Конго – Кіншаса" },
				{ LanguageId.ur, "کانگو - کنشاسا" },
				{ LanguageId.uz, "Kongo – Kinshasa" },
				{ LanguageId.vai, "ꖏꖐ ꗵꗞꖴꕟꔎ ꕸꖃꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Congo - Kinshasa" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Jamhuri ya Kidemokrasia ya Kongo" },
				{ LanguageId.wae, "Kongo-Kinshasa" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Kongo (R K D)" },
				{ LanguageId.xh, "ECongo -Kinshasa" },
				{ LanguageId.xog, "Kongo - Zayire" },
				{ LanguageId.yav, "kitɔŋ kí kongó" },
				{ LanguageId.yi, "קאנגא־קינשאַזע" },
				{ LanguageId.yo, "Kóńgò – Kinshasa" },
				{ LanguageId.zgh, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵉⵎⵓⵇⵔⴰⵜⵉⵜ ⵏ ⴽⵓⵏⴳⵓ" },
				{ LanguageId.zh, "刚果（金）" },
				{ LanguageId.zu, "i-Congo - Kinshasa" },
			}
		);
	}
}
