// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "236",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Central African Republic" },
				{ LanguageId.da, "Den Centralafrikanske Republik" },
				{ LanguageId.af, "Sentraal-Afrikaanse Republiek" },
				{ LanguageId.agq, "Sɛnta Afɨlekan Lèkpobèlè" },
				{ LanguageId.ak, "Afrika Finimfin Man" },
				{ LanguageId.am, "ማዕከላዊ አፍሪካ ሪፑብሊክ" },
				{ LanguageId.ar, "جمهورية أفريقيا الوسطى" },
				{ LanguageId.arn, "Central African Republic" },
				{ LanguageId.@as, "মধ্য আফ্রিকান প্রজাতন্ত্র" },
				{ LanguageId.asa, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.ast, "República Centroafricana" },
				{ LanguageId.az, "Mərkəzi Afrika Respublikası" },
				{ LanguageId.ba, "Үҙәк Африка Республикаһы" },
				{ LanguageId.bas, "Ŋ̀ɛm Afrīkà" },
				{ LanguageId.be, "Цэнтральна-Афрыканская Рэспубліка" },
				{ LanguageId.bem, "Central African Republic" },
				{ LanguageId.bez, "Ijamhuri ya Afrika ya Pagati" },
				{ LanguageId.bg, "Централноафриканска република" },
				{ LanguageId.bin, "Central African Republic" },
				{ LanguageId.bm, "Santarafiriki" },
				{ LanguageId.bn, "মধ্য আফ্রিকান প্রজাতন্ত্র" },
				{ LanguageId.bo, "Central African Republic" },
				{ LanguageId.br, "Republik Kreizafrikan" },
				{ LanguageId.brx, "मिरु आफ्रिका सुबुंखुंथाय" },
				{ LanguageId.bs, "Centralnoafrička Republika" },
				{ LanguageId.byn, "Central African Republic" },
				{ LanguageId.ca, "República Centreafricana" },
				{ LanguageId.ccp, "𑄟𑄧𑄖𑄴𑄙𑄳𑄠𑄧 𑄃𑄜𑄳𑄢𑄨𑄇𑄢𑄴𑄛𑄳𑄢𑄎𑄖𑄧𑄚𑄴𑄖𑄳𑄢𑄧" },
				{ LanguageId.ce, "Юккъерчу Африкин Республика" },
				{ LanguageId.ceb, "Central African Republic" },
				{ LanguageId.cgg, "Eihanga rya Rwagati ya Afirika" },
				{ LanguageId.chr, "ᎬᎿᎨᏍᏛ ᎠᏰᏟ ᏍᎦᏚᎩ" },
				{ LanguageId.ckb, "کۆماری ئەفریقای ناوەڕاست" },
				{ LanguageId.co, "Republica di Centru Africa" },
				{ LanguageId.cs, "Středoafrická republika" },
				{ LanguageId.cu, "Central African Republic" },
				{ LanguageId.cy, "Gweriniaeth Canolbarth Affrica" },
				{ LanguageId.dav, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.de, "Zentralafrikanische Republik" },
				{ LanguageId.dje, "Centraafriki koyra" },
				{ LanguageId.doi, "Central African Republic" },
				{ LanguageId.dsb, "Centralnoafriska republika" },
				{ LanguageId.dua, "Central African Republic" },
				{ LanguageId.dv, "Central African Republic" },
				{ LanguageId.dz, "སེན་ཊལ་ ཨཕ་རི་ཀཱན་ རི་པབ་ལིཀ" },
				{ LanguageId.ebu, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.ee, "Titina Afrika repɔblik nutome" },
				{ LanguageId.el, "Κεντροαφρικανική Δημοκρατία" },
				{ LanguageId.en, "Central African Republic" },
				{ LanguageId.eo, "Centr-Afriko" },
				{ LanguageId.es, "República Centroafricana" },
				{ LanguageId.et, "Kesk-Aafrika Vabariik" },
				{ LanguageId.eu, "Afrika Erdiko Errepublika" },
				{ LanguageId.ewo, "ǹnam Zǎŋ Afiriká" },
				{ LanguageId.fa, "جمهوری افریقای مرکزی" },
				{ LanguageId.ff, "Ndenndaandi Santarafrik" },
				{ LanguageId.fi, "Keski-Afrikan tasavalta" },
				{ LanguageId.fil, "Central African Republic" },
				{ LanguageId.fo, "Miðafrikalýðveldið" },
				{ LanguageId.fr, "République centrafricaine" },
				{ LanguageId.fur, "Republiche centri africane" },
				{ LanguageId.fy, "Sintraal-Afrikaanske Republyk" },
				{ LanguageId.ga, "Poblacht na hAfraice Láir" },
				{ LanguageId.gd, "Poblachd Meadhan Afraga" },
				{ LanguageId.gl, "República Centroafricana" },
				{ LanguageId.gn, "Central African Republic" },
				{ LanguageId.gsw, "Zentraalafrikaanischi Republik" },
				{ LanguageId.gu, "સેન્ટ્રલ આફ્રિકન રિપબ્લિક" },
				{ LanguageId.guz, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.gv, "Central African Republic" },
				{ LanguageId.ha, "Jamhuriyar Afirka Ta Tsakiya" },
				{ LanguageId.haw, "Lepupalika ʻApelika Waena" },
				{ LanguageId.he, "הרפובליקה המרכז-אפריקאית" },
				{ LanguageId.hi, "मध्य अफ़्रीकी गणराज्य" },
				{ LanguageId.hr, "Srednjoafrička Republika" },
				{ LanguageId.hsb, "Centralnoafriska republika" },
				{ LanguageId.hu, "Közép-afrikai Köztársaság" },
				{ LanguageId.hy, "Կենտրոնական Աֆրիկյան Հանրապետություն" },
				{ LanguageId.ia, "Republica African Central" },
				{ LanguageId.ibb, "Central African Republic" },
				{ LanguageId.id, "Republik Afrika Tengah" },
				{ LanguageId.ig, "Central African Republik" },
				{ LanguageId.ii, "Central African Republic" },
				{ LanguageId.@is, "Mið-Afríkulýðveldið" },
				{ LanguageId.it, "Repubblica Centrafricana" },
				{ LanguageId.iu, "Central African Republic" },
				{ LanguageId.ja, "中央アフリカ共和国" },
				{ LanguageId.jgo, "Central African Republic" },
				{ LanguageId.jmc, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.jv, "Républik Afrika Tengah" },
				{ LanguageId.ka, "ცენტრალური აფრიკის რესპუბლიკა" },
				{ LanguageId.kab, "Tigduda n Tefriqt Talemmast" },
				{ LanguageId.kam, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.kde, "Jamuhuli ya Afilika ya Paching’ati" },
				{ LanguageId.kea, "Republika Sentru-Afrikanu" },
				{ LanguageId.khq, "Centraafriki koyra" },
				{ LanguageId.ki, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.kk, "Орталық Африка Республикасы" },
				{ LanguageId.kkj, "Central African Republic" },
				{ LanguageId.kl, "Central African Republic" },
				{ LanguageId.kln, "Emetab Afrika nebo Kwen" },
				{ LanguageId.km, "សាធារណរដ្ឋអាហ្វ្រិកកណ្ដាល" },
				{ LanguageId.kn, "ಮಧ್ಯ ಆಫ್ರಿಕಾ ಗಣರಾಜ್ಯ" },
				{ LanguageId.ko, "중앙 아프리카 공화국" },
				{ LanguageId.kok, "मदलें अफ्रीकी प्रजासत्तो" },
				{ LanguageId.kr, "Central African Republic" },
				{ LanguageId.ks, "مرکٔزی اَفریٖکی جموٗریَت" },
				{ LanguageId.ksb, "Jamhuli ya Afrika ya Gati" },
				{ LanguageId.ksf, "santrafrík" },
				{ LanguageId.ksh, "de Zäntraalaffrikaanesche Republik" },
				{ LanguageId.kw, "Central African Republic" },
				{ LanguageId.ky, "Борбордук Африка Республикасы" },
				{ LanguageId.la, "Respublica Africae Mediae" },
				{ LanguageId.lag, "Juhúuri ya Afɨrɨka ya katɨ katɨ" },
				{ LanguageId.lb, "Zentralafrikanesch Republik" },
				{ LanguageId.lg, "Lipubulika eya Senturafiriki" },
				{ LanguageId.lkt, "Central African Republic" },
				{ LanguageId.ln, "Repibiki ya Afríka ya Káti" },
				{ LanguageId.lo, "ສາທາລະນະລັດອາຟຣິກາກາງ" },
				{ LanguageId.lrc, "Central African Republic" },
				{ LanguageId.lt, "Centrinės Afrikos Respublika" },
				{ LanguageId.luo, "Central African Republic" },
				{ LanguageId.luy, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.lv, "Centrālāfrikas Republika" },
				{ LanguageId.mai, "मध्य अफ्रीकी रिपब्लिक" },
				{ LanguageId.mas, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.mer, "Nthĩ ya Afrika gatĩgatĩ" },
				{ LanguageId.mfe, "Repiblik Lafrik Santral" },
				{ LanguageId.mg, "Repoblika Ivon’Afrika" },
				{ LanguageId.mgo, "Central African Republic" },
				{ LanguageId.mi, "Te Whenua Tūhake o Āwherika Waenga" },
				{ LanguageId.mk, "Централноафриканска Република" },
				{ LanguageId.ml, "സെൻട്രൽ ആഫ്രിക്കൻ റിപ്പബ്ലിക്ക്" },
				{ LanguageId.mn, "Төв Африкийн Бүгд Найрамдах Улс" },
				{ LanguageId.mni, "Central African Republic" },
				{ LanguageId.moh, "Central African Republic" },
				{ LanguageId.mr, "केंद्रीय अफ्रिकी प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Afrika Tengah" },
				{ LanguageId.mt, "ir-Repubblika Ċentru-Afrikana" },
				{ LanguageId.mua, "centrafrika" },
				{ LanguageId.my, "ဗဟို အာဖရိက ပြည်ထောင်စု" },
				{ LanguageId.mzn, "مرکزی آفریقای جمهوری" },
				{ LanguageId.naq, "Central African Republiki" },
				{ LanguageId.nb, "Den sentralafrikanske republikk" },
				{ LanguageId.nd, "Central African Republic" },
				{ LanguageId.nds, "Zentralafrikanische Republik" },
				{ LanguageId.ne, "मध्य अफ्रिकी गणतन्त्र" },
				{ LanguageId.nl, "Centraal-Afrikaanse Republiek" },
				{ LanguageId.nmg, "Sentrafríka" },
				{ LanguageId.nn, "Den sentralafrikanske republikken" },
				{ LanguageId.nnh, "Central African Republic" },
				{ LanguageId.nqo, "ߕߊ߲ߓߊ߲-ߝߘߊ߬ߝߌ߲߬ߠߊ߫ ߞߊ߲ߓߍ߲" },
				{ LanguageId.nr, "Central African Republic" },
				{ LanguageId.nso, "Central African Republic" },
				{ LanguageId.nus, "Cɛntrɔl aprika repuɔblic" },
				{ LanguageId.nyn, "Eihanga rya Rwagati ya Afirika" },
				{ LanguageId.oc, "Centreafrica" },
				{ LanguageId.om, "Rippaablika Afrikaa Gidduugaleessaa" },
				{ LanguageId.or, "ମଧ୍ୟ ଆଫ୍ରିକୀୟ ସାଧାରଣତନ୍ତ୍ର" },
				{ LanguageId.os, "Central African Republic" },
				{ LanguageId.pa, "ਕੇਂਦਰੀ ਅਫ਼ਰੀਕੀ ਗਣਰਾਜ" },
				{ LanguageId.pap, "Central African Republic" },
				{ LanguageId.pcm, "Sẹ́ntrál Áfríkán Ripọ́blik" },
				{ LanguageId.pl, "Republika Środkowoafrykańska" },
				{ LanguageId.prg, "Central African Republic" },
				{ LanguageId.ps, "وسطي افريقا جمهور" },
				{ LanguageId.pt, "República Centro-Africana" },
				{ LanguageId.qu, "República Centroafricana" },
				{ LanguageId.quc, "Central African Republic" },
				{ LanguageId.rm, "Republica Centralafricana" },
				{ LanguageId.rn, "Repubulika ya Santarafurika" },
				{ LanguageId.ro, "Republica Centrafricană" },
				{ LanguageId.rof, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.ru, "Центрально-Африканская Республика" },
				{ LanguageId.rw, "Repubulika ya Centrafrique" },
				{ LanguageId.rwk, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.sa, "Central African Republic" },
				{ LanguageId.sah, "Central African Republic" },
				{ LanguageId.saq, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.sat, "Central African Republic" },
				{ LanguageId.sbp, "Jamuhuli ya Afilika ya Pakhati" },
				{ LanguageId.sd, "وچ آفريقي جمهوريه" },
				{ LanguageId.se, "Gaska-Afrihká dásseváldi" },
				{ LanguageId.seh, "República Centro-Africana" },
				{ LanguageId.ses, "Centraafriki koyra" },
				{ LanguageId.sg, "Ködörösêse tî Bêafrîka" },
				{ LanguageId.shi, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵏⴰⵎⵎⴰⵙⵜ ⵏ ⵉⴼⵔⵉⵇⵢⴰ" },
				{ LanguageId.si, "මධ්‍යම අප්‍රිකානු ජනරජය" },
				{ LanguageId.sk, "Stredoafrická republika" },
				{ LanguageId.sl, "Srednjeafriška republika" },
				{ LanguageId.sma, "Central African Republic" },
				{ LanguageId.smj, "Central African Republic" },
				{ LanguageId.smn, "Koskâ-Afrika täsiväldi" },
				{ LanguageId.sms, "Central African Republic" },
				{ LanguageId.sn, "Central African Republic" },
				{ LanguageId.so, "Jamhuuriyadda Afrikada Dhexe" },
				{ LanguageId.sq, "Republika e Afrikës Qendrore" },
				{ LanguageId.sr, "Централноафричка Република" },
				{ LanguageId.ss, "Central African Republic" },
				{ LanguageId.ssy, "Central African Republic" },
				{ LanguageId.st, "Central African Republic" },
				{ LanguageId.su, "Républik Afrika Tengah" },
				{ LanguageId.sv, "Centralafrikanska republiken" },
				{ LanguageId.sw, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.syr, "ܩܘܛܢܝܘܬܐ ܕܐܦܪܝܩܐ ܡܨܥܝܬܐ" },
				{ LanguageId.ta, "மத்திய ஆப்ரிக்கக் குடியரசு" },
				{ LanguageId.te, "సెంట్రల్ ఆఫ్రికన్ రిపబ్లిక్" },
				{ LanguageId.teo, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.tg, "Ҷумҳурии Африқои Марказӣ" },
				{ LanguageId.th, "สาธารณรัฐแอฟริกากลาง" },
				{ LanguageId.ti, "ሪፓብሊክ ማእከላይ ኣፍሪቃ" },
				{ LanguageId.tig, "Central African Republic" },
				{ LanguageId.tk, "Merkezi Afrika Respublikasy" },
				{ LanguageId.tn, "Central African Republic" },
				{ LanguageId.to, "Lepupelika ʻAfilika Lotoloto" },
				{ LanguageId.tr, "Orta Afrika Cumhuriyeti" },
				{ LanguageId.ts, "Central African Republic" },
				{ LanguageId.tt, "Үзәк Африка Республикасы" },
				{ LanguageId.twq, "Centraafriki koyra" },
				{ LanguageId.tzm, "Tagduda n Afrika Wammas" },
				{ LanguageId.ug, "ئوتتۇرا ئافرىقا جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Центральноафриканська Республіка" },
				{ LanguageId.ur, "وسط افریقی جمہوریہ" },
				{ LanguageId.uz, "Markaziy Afrika Respublikasi" },
				{ LanguageId.vai, "ꕉꔱꔸꕪ ꗳ ꗳ ꕸꖃꔀ" },
				{ LanguageId.ve, "Central African Republic" },
				{ LanguageId.vi, "Cộng hòa Trung Phi" },
				{ LanguageId.vo, "Central African Republic" },
				{ LanguageId.vun, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.wae, "Zentralafrikaniši Rebublik" },
				{ LanguageId.wal, "Central African Republic" },
				{ LanguageId.wo, "Repiblik Sàntar Afrik" },
				{ LanguageId.xh, "ECentral African Republic" },
				{ LanguageId.xog, "Lipabulika ya Senturafiriki" },
				{ LanguageId.yav, "Santalafilíik" },
				{ LanguageId.yi, "צענטראַל־אַפֿריקאַנישע רעפּובליק" },
				{ LanguageId.yo, "Àrin gùngun Áfíríkà" },
				{ LanguageId.zgh, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵏⴰⵎⵎⴰⵙⵜ ⵏ ⵉⴼⵔⵉⵇⵢⴰ" },
				{ LanguageId.zh, "中非共和国" },
				{ LanguageId.zu, "i-Central African Republic" },
			}
		);
	}
}
