using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "236",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Central African Republic" },
				{ LanguageId.da, "Den Centralafrikanske Republik" },
				{ LanguageId.af, "Sentraal-Afrikaanse Republiek" },
				{ LanguageId.agq, "Central African Republic" },
				{ LanguageId.ak, "Central African Republic" },
				{ LanguageId.am, "ሴንትራል አፍሪካ ሪፑቢሊክ" },
				{ LanguageId.ar, "جمهورية افريقيا الوسطى" },
				{ LanguageId.arn, "Central African Republic" },
				{ LanguageId.@as, "Central African Republic" },
				{ LanguageId.asa, "Central African Republic" },
				{ LanguageId.ast, "República Centroafricana" },
				{ LanguageId.az, "Mərkəzi Afrika Respublikası" },
				{ LanguageId.ba, "Central African Republic" },
				{ LanguageId.bas, "Central African Republic" },
				{ LanguageId.be, "Цэнтральна-Афрыканская Рэспубліка" },
				{ LanguageId.bem, "Central African Republic" },
				{ LanguageId.bez, "Central African Republic" },
				{ LanguageId.bg, "Централноафриканска република" },
				{ LanguageId.bin, "Central African Republic" },
				{ LanguageId.bm, "Central African Republic" },
				{ LanguageId.bn, "মধ্য আফ্রিকান প্রজাতন্ত্র" },
				{ LanguageId.bo, "Central African Republic" },
				{ LanguageId.br, "Republik Kreizafrikan" },
				{ LanguageId.brx, "Central African Republic" },
				{ LanguageId.bs, "Centralnoafrička Republika" },
				{ LanguageId.byn, "Central African Republic" },
				{ LanguageId.ca, "República Centreafricana" },
				{ LanguageId.ccp, "Central African Republic" },
				{ LanguageId.ce, "Central African Republic" },
				{ LanguageId.ceb, "Republika sa Sentral Aprika" },
				{ LanguageId.cgg, "Central African Republic" },
				{ LanguageId.chr, "Central African Republic" },
				{ LanguageId.ckb, "کۆماری ناوەڕاستی ئەفریقا" },
				{ LanguageId.co, "Republica di Centru Africa" },
				{ LanguageId.cs, "Středoafrická republika" },
				{ LanguageId.cu, "Central African Republic" },
				{ LanguageId.cy, "Gweriniaeth Canolbarth Affrica" },
				{ LanguageId.dav, "Central African Republic" },
				{ LanguageId.de, "Zentralafrikanische Republik" },
				{ LanguageId.dje, "Central African Republic" },
				{ LanguageId.doi, "Central African Republic" },
				{ LanguageId.dsb, "Centralnoafriska republika" },
				{ LanguageId.dua, "Central African Republic" },
				{ LanguageId.dv, "Central African Republic" },
				{ LanguageId.dz, "Central African Republic" },
				{ LanguageId.ebu, "Central African Republic" },
				{ LanguageId.ee, "Central African Republic" },
				{ LanguageId.el, "Δημοκρατία Κεντρικής Αφρικής" },
				{ LanguageId.en, "Central African Republic" },
				{ LanguageId.eo, "Centafrika Respubliko" },
				{ LanguageId.es, "República Centroafricana" },
				{ LanguageId.et, "Kesk-Aafrika Vabariik" },
				{ LanguageId.eu, "Afrika Erdiko Errepublika" },
				{ LanguageId.ewo, "Central African Republic" },
				{ LanguageId.fa, "جمهوری آفریقای مرکزی" },
				{ LanguageId.ff, "Central African Republic" },
				{ LanguageId.fi, "Keski-Afrikan tasavalta" },
				{ LanguageId.fil, "Central African Republic" },
				{ LanguageId.fo, "Miðafrikanska lýðveldið" },
				{ LanguageId.fr, "République centrafricaine" },
				{ LanguageId.fur, "Republiche Centrafricane" },
				{ LanguageId.fy, "de Sintraal-Afrikaanske Republyk" },
				{ LanguageId.ga, "Poblacht na hAfraice Láir" },
				{ LanguageId.gd, "Poblachd Meadhan Afraga" },
				{ LanguageId.gl, "República Centroafricana" },
				{ LanguageId.gn, "Central African Republic" },
				{ LanguageId.gsw, "Zentralafrikanischi Republik" },
				{ LanguageId.gu, "સેન્ટ્રલ આફ્રિકન રિપબ્લિક" },
				{ LanguageId.guz, "Central African Republic" },
				{ LanguageId.gv, "Central African Republic" },
				{ LanguageId.ha, "Jamhuriyar Afirka ta Tsakiya" },
				{ LanguageId.haw, "Lepupalika ʻApelika Waena" },
				{ LanguageId.he, "הרפובליקה המרכז - אפריקאית" },
				{ LanguageId.hi, "केन्द्रीय अफ़्रीकी गणराज्य" },
				{ LanguageId.hr, "Centralna Afrička Republika" },
				{ LanguageId.hsb, "Centralnoafriska republika" },
				{ LanguageId.hu, "Közép-Afrikai Köztársaság" },
				{ LanguageId.hy, "Կենտրոնական Աֆրիկյան Հանրապետություն" },
				{ LanguageId.ia, "Republica Centroafrican" },
				{ LanguageId.ibb, "Central African Republic" },
				{ LanguageId.id, "Republik Afrika Tengah" },
				{ LanguageId.ig, "Central African Republic" },
				{ LanguageId.ii, "Central African Republic" },
				{ LanguageId.@is, "Mið-Afríkulýðveldið" },
				{ LanguageId.it, "Repubblica Centrafricana" },
				{ LanguageId.iu, "Central African Republic" },
				{ LanguageId.ja, "中央アフリカ共和国" },
				{ LanguageId.jgo, "Central African Republic" },
				{ LanguageId.jmc, "Central African Republic" },
				{ LanguageId.jv, "Republik Afrika Tengah" },
				{ LanguageId.ka, "ცენტრალური აფრიკის რესპუბლიკა" },
				{ LanguageId.kab, "Central African Republic" },
				{ LanguageId.kam, "Central African Republic" },
				{ LanguageId.kde, "Central African Republic" },
				{ LanguageId.kea, "Central African Republic" },
				{ LanguageId.khq, "Central African Republic" },
				{ LanguageId.ki, "Central African Republic" },
				{ LanguageId.kk, "Орталық Африка Республикасы" },
				{ LanguageId.kkj, "Central African Republic" },
				{ LanguageId.kl, "Central African Republic" },
				{ LanguageId.kln, "Central African Republic" },
				{ LanguageId.km, "សាធារណរដ្ឋអាហ្វ្រិកកណ្តាល" },
				{ LanguageId.kn, "ಮಧ್ಯ ಆಫ್ರಿಕಾದ ಗಣರಾಜ್ಯ" },
				{ LanguageId.ko, "중앙 아프리카 공화국" },
				{ LanguageId.kok, "Central African Republic" },
				{ LanguageId.kr, "Central African Republic" },
				{ LanguageId.ks, "Central African Republic" },
				{ LanguageId.ksb, "Central African Republic" },
				{ LanguageId.ksf, "Central African Republic" },
				{ LanguageId.ksh, "Central African Republic" },
				{ LanguageId.kw, "Central African Republic" },
				{ LanguageId.ky, "Борбордук Африка Республикасы" },
				{ LanguageId.la, "Respublica Africae Mediae" },
				{ LanguageId.lag, "Central African Republic" },
				{ LanguageId.lb, "Zentralafrikanesch Republik" },
				{ LanguageId.lg, "Central African Republic" },
				{ LanguageId.lkt, "Central African Republic" },
				{ LanguageId.ln, "Central African Republic" },
				{ LanguageId.lo, "ສາທາລະນະລັດອາຟຣິກາກາງ" },
				{ LanguageId.lrc, "Central African Republic" },
				{ LanguageId.lt, "Centrine Afrikos Respublika" },
				{ LanguageId.luo, "Central African Republic" },
				{ LanguageId.luy, "Central African Republic" },
				{ LanguageId.lv, "Centrālāfrikas Republika" },
				{ LanguageId.mai, "Central African Republic" },
				{ LanguageId.mas, "Central African Republic" },
				{ LanguageId.mer, "Central African Republic" },
				{ LanguageId.mfe, "Central African Republic" },
				{ LanguageId.mg, "Repoblikan'i Afrika Afovoany" },
				{ LanguageId.mgo, "Central African Republic" },
				{ LanguageId.mi, "Te Repupirita Afirika Waenga" },
				{ LanguageId.mk, "Централноафриканска Република" },
				{ LanguageId.ml, "മധ്യ ആഫ്രിക്കൻ റിപ്പബ്ലിക്" },
				{ LanguageId.mn, "Төв Африкийн Бүгд Найрамдах Улс" },
				{ LanguageId.mni, "Central African Republic" },
				{ LanguageId.moh, "Central African Republic" },
				{ LanguageId.mr, "सेंट्रल आफ्रिकन रिपब्लिक" },
				{ LanguageId.ms, "Republik Afrika Tengah" },
				{ LanguageId.mt, "Repubblika Ċentru-Afrikana" },
				{ LanguageId.mua, "Central African Republic" },
				{ LanguageId.my, "ဗဟိုအာဖရိကသမ္မတနိုင်ငံ၊" },
				{ LanguageId.mzn, "Central African Republic" },
				{ LanguageId.naq, "Central African Republic" },
				{ LanguageId.nb, "Den sentralafrikanske republikk" },
				{ LanguageId.nd, "Central African Republic" },
				{ LanguageId.nds, "Zentralafrikanische Republik" },
				{ LanguageId.ne, "मध्य अफ्रिकी गणतन्त्र" },
				{ LanguageId.nl, "Centraal Afrikaanse Republiek" },
				{ LanguageId.nmg, "Central African Republic" },
				{ LanguageId.nn, "Den sentralafrikanske republikken" },
				{ LanguageId.nnh, "Central African Republic" },
				{ LanguageId.nqo, "Central African Republic" },
				{ LanguageId.nr, "Central African Republic" },
				{ LanguageId.nso, "Central African Republic" },
				{ LanguageId.nus, "Central African Republic" },
				{ LanguageId.nyn, "Central African Republic" },
				{ LanguageId.oc, "Centreafrica" },
				{ LanguageId.om, "Central African Republic" },
				{ LanguageId.or, "କେନ୍ଦ୍ରୀୟ ଆଫ୍ରିକୀୟ ଗଣତନ୍ତ୍ର" },
				{ LanguageId.os, "Central African Republic" },
				{ LanguageId.pa, "ਮੱਧ ਅਫ਼ਰੀਕੀ ਗਣਰਾਜ" },
				{ LanguageId.pap, "Central African Republic" },
				{ LanguageId.pcm, "Central African Republic" },
				{ LanguageId.pl, "Republika Środkowoafrykańska" },
				{ LanguageId.prg, "Central African Republic" },
				{ LanguageId.ps, "د مرکزي افریقا جمهوریت" },
				{ LanguageId.pt, "República Centro-Africana" },
				{ LanguageId.qu, "Central African Republic" },
				{ LanguageId.quc, "Central African Republic" },
				{ LanguageId.rm, "Republica Centralafricana" },
				{ LanguageId.rn, "Central African Republic" },
				{ LanguageId.ro, "Republica Centrafricană" },
				{ LanguageId.rof, "Central African Republic" },
				{ LanguageId.ru, "Центрально-Африканская Республика" },
				{ LanguageId.rw, "Repubulika ya Centrafrique" },
				{ LanguageId.rwk, "Central African Republic" },
				{ LanguageId.sa, "Central African Republic" },
				{ LanguageId.sah, "Central African Republic" },
				{ LanguageId.saq, "Central African Republic" },
				{ LanguageId.sat, "Central African Republic" },
				{ LanguageId.sbp, "Central African Republic" },
				{ LanguageId.sd, "وسطي آفريقي جمهوريه" },
				{ LanguageId.se, "Central African Republic" },
				{ LanguageId.seh, "Central African Republic" },
				{ LanguageId.ses, "Central African Republic" },
				{ LanguageId.sg, "Bêafrîka" },
				{ LanguageId.shi, "Central African Republic" },
				{ LanguageId.si, "මධ්යම අප්රිකානු ජනරජය" },
				{ LanguageId.sk, "Stredoafrická republika" },
				{ LanguageId.sl, "centralna afriška republika" },
				{ LanguageId.sma, "Central African Republic" },
				{ LanguageId.smj, "Central African Republic" },
				{ LanguageId.smn, "Central African Republic" },
				{ LanguageId.sms, "Central African Republic" },
				{ LanguageId.sn, "Yepakati Ripabhuriki Afrika" },
				{ LanguageId.so, "Jamhuuriyadda Afrikada Dhexe" },
				{ LanguageId.sq, "Republika e Afrikës Qendrore" },
				{ LanguageId.sr, "Централна Афричка Република" },
				{ LanguageId.ss, "Central African Republic" },
				{ LanguageId.ssy, "Central African Republic" },
				{ LanguageId.st, "Central African Republic" },
				{ LanguageId.su, "Républik Afrika Tengah" },
				{ LanguageId.sv, "Centralafrikanska republiken" },
				{ LanguageId.sw, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.syr, "Central African Republic" },
				{ LanguageId.ta, "மத்திய ஆப்பிரிக்க குடியரசு" },
				{ LanguageId.te, "సెంట్రల్ ఆఫ్రికన్ రిపబ్లిక్" },
				{ LanguageId.teo, "Central African Republic" },
				{ LanguageId.tg, "Республикаи Африкаи Марказй" },
				{ LanguageId.th, "สาธารณรัฐอัฟริกากลาง" },
				{ LanguageId.ti, "Central African Republic" },
				{ LanguageId.tig, "Central African Republic" },
				{ LanguageId.tk, "Merkezi Afrika Respublikasy" },
				{ LanguageId.tn, "Central African Republic" },
				{ LanguageId.to, "Central African Republic" },
				{ LanguageId.tr, "Orta Afrika Cumhuriyeti" },
				{ LanguageId.ts, "Central African Republic" },
				{ LanguageId.tt, "Centralзәк Африка Республикасы" },
				{ LanguageId.twq, "Central African Republic" },
				{ LanguageId.tzm, "Central African Republic" },
				{ LanguageId.ug, "ئوتتۇرا ئافرىقا جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Центральноафриканська Республіка" },
				{ LanguageId.ur, "مرکزی افریقی جمہوریت" },
				{ LanguageId.uz, "Markaziy Afrika Respublikasi" },
				{ LanguageId.vai, "Central African Republic" },
				{ LanguageId.ve, "Central African Republic" },
				{ LanguageId.vi, "Cộng hòa trung phi" },
				{ LanguageId.vo, "Central African Republic" },
				{ LanguageId.vun, "Central African Republic" },
				{ LanguageId.wae, "Central African Republic" },
				{ LanguageId.wal, "Central African Republic" },
				{ LanguageId.wo, "Central African Republic" },
				{ LanguageId.xh, "Iriphabliki yaseAfrika eseMbindini" },
				{ LanguageId.xog, "Central African Republic" },
				{ LanguageId.yav, "Central African Republic" },
				{ LanguageId.yi, "סענטראַל אפריקאנער רעפובליק" },
				{ LanguageId.yo, "Central African Republic" },
				{ LanguageId.zgh, "Central African Republic" },
				{ LanguageId.zh, "中非共和国" },
				{ LanguageId.zu, "I-Central African Republic" },
			}
		);
	}
}
