using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "236",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Den Centralafrikanske Republik" },
				{ LanguageId.af, "Sentraal-Afrikaanse Republiek" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሴንትራል አፍሪካ ሪፑቢሊክ" },
				{ LanguageId.ar, "جمهورية افريقيا الوسطى" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Mərkəzi Afrika Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Цэнтральна-Афрыканская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Централноафриканска република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "মধ্য আফ্রিকান প্রজাতন্ত্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Republik Kreizafrikan" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Centralnoafrička Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Centreafricana" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Republika sa Sentral Aprika" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Republica di Centru Africa" },
				{ LanguageId.cs, "Středoafrická republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Canolbarth Affrica" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Zentralafrikanische Republik" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Δημοκρατία Κεντρικής Αφρικής" },
				{ LanguageId.en, "Central African Republic" },
				{ LanguageId.eo, "Centafrika Respubliko" },
				{ LanguageId.es, "República Centroafricana" },
				{ LanguageId.et, "Kesk-Aafrika Vabariik" },
				{ LanguageId.eu, "Afrika Erdiko Errepublika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری آفریقای مرکزی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Keski-Afrikan tasavalta" },
				{ LanguageId.fil, "Central African Republic" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République centrafricaine" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Sintraal-Afrikaanske Republyk" },
				{ LanguageId.ga, "Poblacht na hAfraice Láir" },
				{ LanguageId.gd, "Poblachd Meadhan Afraga" },
				{ LanguageId.gl, "República Centroafricana" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ્રલ આફ્રિકન રિપબ્લિક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Afirka ta Tsakiya" },
				{ LanguageId.haw, "Lepupalika ʻApelika Waena" },
				{ LanguageId.he, "הרפובליקה המרכז - אפריקאית" },
				{ LanguageId.hi, "केन्द्रीय अफ़्रीकी गणराज्य" },
				{ LanguageId.hr, "Centralna Afrička Republika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Közép-Afrikai Köztársaság" },
				{ LanguageId.hy, "Կենտրոնական Աֆրիկյան Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Afrika Tengah" },
				{ LanguageId.ig, "Central African Republic" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Mið-Afríkulýðveldið" },
				{ LanguageId.it, "Repubblica Centrafricana" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "中央アフリカ共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Afrika Tengah" },
				{ LanguageId.ka, "ცენტრალური აფრიკის რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Орталық Африка Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋអាហ្វ្រិកកណ្តាល" },
				{ LanguageId.kn, "ಮಧ್ಯ ಆಫ್ರಿಕಾದ ಗಣರಾಜ್ಯ" },
				{ LanguageId.ko, "중앙 아프리카 공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Борбордук Африка Республикасы" },
				{ LanguageId.la, "Respublica Africae Mediae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Zentralafrikanesch Republik" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາທາລະນະລັດອາຟຣິກາກາງ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Centrine Afrikos Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Centrālāfrikas Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblikan'i Afrika Afovoany" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Repupirita Afirika Waenga" },
				{ LanguageId.mk, "Централноафриканска Република" },
				{ LanguageId.ml, "മധ്യ ആഫ്രിക്കൻ റിപ്പബ്ലിക്" },
				{ LanguageId.mn, "Төв Африкийн Бүгд Найрамдах Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट्रल आफ्रिकन रिपब्लिक" },
				{ LanguageId.ms, "Republik Afrika Tengah" },
				{ LanguageId.mt, "Repubblika Ċentru-Afrikana" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဗဟိုအာဖရိကသမ္မတနိုင်ငံ၊" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Den sentralafrikanske republikk" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "मध्य अफ्रिकी गणतन्त्र" },
				{ LanguageId.nl, "Centraal Afrikaanse Republiek" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କେନ୍ଦ୍ରୀୟ ଆଫ୍ରିକୀୟ ଗଣତନ୍ତ୍ର" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮੱਧ ਅਫ਼ਰੀਕੀ ਗਣਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Republika Środkowoafrykańska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د مرکزي افریقا جمهوریت" },
				{ LanguageId.pt, "República Centro-Africana" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Centrafricană" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Центрально-Африканская Республика" },
				{ LanguageId.rw, "Repubulika ya Centrafrique" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "وسطي آفريقي جمهوريه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "Bêafrîka" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "මධ්යම අප්රිකානු ජනරජය" },
				{ LanguageId.sk, "Stredoafrická republika" },
				{ LanguageId.sl, "centralna afriška republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Yepakati Ripabhuriki Afrika" },
				{ LanguageId.so, "Jamhuuriyadda Afrikada Dhexe" },
				{ LanguageId.sq, "Republika e Afrikës Qendrore" },
				{ LanguageId.sr, "Централна Афричка Република" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Central African Republic" },
				{ LanguageId.su, "Républik Afrika Tengah" },
				{ LanguageId.sv, "Centralafrikanska republiken" },
				{ LanguageId.sw, "Jamhuri ya Afrika ya Kati" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "மத்திய ஆப்பிரிக்க குடியரசு" },
				{ LanguageId.te, "సెంట్రల్ ఆఫ్రికన్ రిపబ్లిక్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Республикаи Африкаи Марказй" },
				{ LanguageId.th, "สาธารณรัฐอัฟริกากลาง" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Merkezi Afrika Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Orta Afrika Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Centralзәк Африка Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ئوتتۇرا ئافرىقا جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Центральноафриканська Республіка" },
				{ LanguageId.ur, "مرکزی افریقی جمہوریت" },
				{ LanguageId.uz, "Markaziy Afrika Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa trung phi" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iriphabliki yaseAfrika eseMbindini" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סענטראַל אפריקאנער רעפובליק" },
				{ LanguageId.yo, "Central African Republic" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "中非共和国" },
				{ LanguageId.zu, "I-Central African Republic" },
			}
		);
	}
}
