// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CG
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "242",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Congo" },
				{ LanguageId.da, "Congo-Brazzaville" },
				{ LanguageId.af, "Kongo-Brazzaville" },
				{ LanguageId.agq, "Kuŋgù" },
				{ LanguageId.ak, "Kongo" },
				{ LanguageId.am, "ኮንጎ ብራዛቪል" },
				{ LanguageId.ar, "الكونغو - برازافيل" },
				{ LanguageId.arn, "Congo" },
				{ LanguageId.@as, "কঙ্গো - ব্রাজাভিল" },
				{ LanguageId.asa, "Kongo" },
				{ LanguageId.ast, "Congu - Brazzaville" },
				{ LanguageId.az, "Konqo - Brazzavil" },
				{ LanguageId.ba, "Конго - Браззавиль" },
				{ LanguageId.bas, "Kòŋgo" },
				{ LanguageId.be, "Конга - Бразавіль" },
				{ LanguageId.bem, "Congo" },
				{ LanguageId.bez, "Hukongo" },
				{ LanguageId.bg, "Конго (Бразавил)" },
				{ LanguageId.bin, "Congo" },
				{ LanguageId.bm, "Kongo" },
				{ LanguageId.bn, "কঙ্গো - ব্রাজাভিল" },
				{ LanguageId.bo, "Congo" },
				{ LanguageId.br, "Kongo - Brazzaville" },
				{ LanguageId.brx, "कंग’- ब्राज्जाभील" },
				{ LanguageId.bs, "Kongo" },
				{ LanguageId.byn, "Congo" },
				{ LanguageId.ca, "Congo - Brazzaville" },
				{ LanguageId.ccp, "𑄇𑄧𑄋𑄴𑄉𑄮-𑄝𑄳𑄢𑄎𑄞𑄨𑄣𑄴" },
				{ LanguageId.ce, "Конго - Браззавиль" },
				{ LanguageId.ceb, "Congo - Brazzaville" },
				{ LanguageId.cgg, "Kongo" },
				{ LanguageId.chr, "ᎧᏂᎪ - ᏆᏌᏩᎵ" },
				{ LanguageId.ckb, "کۆنگۆ برازاڤیل" },
				{ LanguageId.co, "Congo" },
				{ LanguageId.cs, "Kongo – Brazzaville" },
				{ LanguageId.cu, "Congo" },
				{ LanguageId.cy, "Y Congo - Brazzaville" },
				{ LanguageId.dav, "Kongo" },
				{ LanguageId.de, "Kongo-Brazzaville" },
				{ LanguageId.dje, "Kongoo" },
				{ LanguageId.doi, "Congo" },
				{ LanguageId.dsb, "Kongo-Brazzaville" },
				{ LanguageId.dua, "Congo" },
				{ LanguageId.dv, "Congo" },
				{ LanguageId.dz, "ཀོང་གྷོ བྷྲ་ཛ་བིལ" },
				{ LanguageId.ebu, "Kongo" },
				{ LanguageId.ee, "Kongo Brazzaville nutome" },
				{ LanguageId.el, "Κονγκό - Μπραζαβίλ" },
				{ LanguageId.en, "Congo - Brazzaville" },
				{ LanguageId.eo, "Kongo Brazavila" },
				{ LanguageId.es, "Congo" },
				{ LanguageId.et, "Kongo Vabariik" },
				{ LanguageId.eu, "Kongo" },
				{ LanguageId.ewo, "Kongó" },
				{ LanguageId.fa, "کنگو - برازویل" },
				{ LanguageId.ff, "Konngo" },
				{ LanguageId.fi, "Kongon tasavalta" },
				{ LanguageId.fil, "Congo - Brazzaville" },
				{ LanguageId.fo, "Kongo" },
				{ LanguageId.fr, "Congo-Brazzaville" },
				{ LanguageId.fur, "Congo - Brazzaville" },
				{ LanguageId.fy, "Congo-Brazzaville" },
				{ LanguageId.ga, "Congó-Brazzaville" },
				{ LanguageId.gd, "A’ Chongo - Brazzaville" },
				{ LanguageId.gl, "República do Congo" },
				{ LanguageId.gn, "Congo" },
				{ LanguageId.gsw, "Kongo" },
				{ LanguageId.gu, "કોંગો - બ્રાઝાવિલે" },
				{ LanguageId.guz, "Kongo" },
				{ LanguageId.gv, "Congo" },
				{ LanguageId.ha, "Kongo" },
				{ LanguageId.haw, "Konokō" },
				{ LanguageId.he, "קונגו - ברזאויל" },
				{ LanguageId.hi, "कांगो – ब्राज़ाविल" },
				{ LanguageId.hr, "Kongo - Brazzaville" },
				{ LanguageId.hsb, "Kongo-Brazzaville" },
				{ LanguageId.hu, "Kongó – Brazzaville" },
				{ LanguageId.hy, "Կոնգո - Բրազավիլ" },
				{ LanguageId.ia, "Congo - Brazzaville" },
				{ LanguageId.ibb, "Congo" },
				{ LanguageId.id, "Kongo - Brazzaville" },
				{ LanguageId.ig, "Congo" },
				{ LanguageId.ii, "Congo" },
				{ LanguageId.@is, "Kongó-Brazzaville" },
				{ LanguageId.it, "Congo-Brazzaville" },
				{ LanguageId.iu, "Congo" },
				{ LanguageId.ja, "コンゴ共和国(ブラザビル)" },
				{ LanguageId.jgo, "Kɔ́ŋgɔ-Mbɛlazavîl" },
				{ LanguageId.jmc, "Kongo" },
				{ LanguageId.jv, "Kongo - Brassaville" },
				{ LanguageId.ka, "კონგო - ბრაზავილი" },
				{ LanguageId.kab, "Kungu" },
				{ LanguageId.kam, "Kongo" },
				{ LanguageId.kde, "Kongo" },
				{ LanguageId.kea, "Kongu - Brazavili" },
				{ LanguageId.khq, "Kongoo" },
				{ LanguageId.ki, "Kongo" },
				{ LanguageId.kk, "Конго-Браззавиль Республикасы" },
				{ LanguageId.kkj, "Congo" },
				{ LanguageId.kl, "Congo" },
				{ LanguageId.kln, "Emetab Congo - Brazzaville" },
				{ LanguageId.km, "កុងហ្គោ - ប្រាហ្សាវីល" },
				{ LanguageId.kn, "ಕಾಂಗೋ - ಬ್ರಾಜಾವಿಲ್ಲೇ" },
				{ LanguageId.ko, "콩고-브라자빌" },
				{ LanguageId.kok, "कोंगो - ब्राझाविला" },
				{ LanguageId.kr, "Congo" },
				{ LanguageId.ks, "کونگو بٔرزاوِلی" },
				{ LanguageId.ksb, "Kongo" },
				{ LanguageId.ksf, "kɔngó" },
				{ LanguageId.ksh, "dä Konggo (Brassavill)" },
				{ LanguageId.kw, "Congo" },
				{ LanguageId.ky, "Конго-Браззавил" },
				{ LanguageId.la, "Congo" },
				{ LanguageId.lag, "Kóongo" },
				{ LanguageId.lb, "Kongo-Brazzaville" },
				{ LanguageId.lg, "Kongo" },
				{ LanguageId.lkt, "Congo" },
				{ LanguageId.ln, "Kongo" },
				{ LanguageId.lo, "ຄອງໂກ - ບຣາຊາວິວ" },
				{ LanguageId.lrc, "Congo" },
				{ LanguageId.lt, "Kongas-Brazavilis" },
				{ LanguageId.luo, "Congo" },
				{ LanguageId.luy, "Kongo" },
				{ LanguageId.lv, "Kongo (Brazavila)" },
				{ LanguageId.mai, "कांगो-ब्राजाबिले" },
				{ LanguageId.mas, "Kongo" },
				{ LanguageId.mer, "Kongo" },
				{ LanguageId.mfe, "Kongo" },
				{ LanguageId.mg, "Kôngô" },
				{ LanguageId.mgo, "Congo" },
				{ LanguageId.mi, "Kōngo - Pārawhe" },
				{ LanguageId.mk, "Конго - Бразавил" },
				{ LanguageId.ml, "കോംഗോ - ബ്രാസവില്ലി" },
				{ LanguageId.mn, "Конго-Браззавиль" },
				{ LanguageId.mni, "Congo" },
				{ LanguageId.moh, "Congo" },
				{ LanguageId.mr, "काँगो - ब्राझाविले" },
				{ LanguageId.ms, "Congo - Brazzaville" },
				{ LanguageId.mt, "il-Kongo - Brazzaville" },
				{ LanguageId.mua, "kongo" },
				{ LanguageId.my, "ကွန်ဂို-ဘရာဇာဗီးလ်" },
				{ LanguageId.mzn, "کنگو برازاویل" },
				{ LanguageId.naq, "Congob" },
				{ LanguageId.nb, "Kongo-Brazzaville" },
				{ LanguageId.nd, "Khongo" },
				{ LanguageId.nds, "Kongo" },
				{ LanguageId.ne, "कङ्गो ब्राजाभिल" },
				{ LanguageId.nl, "Congo-Brazzaville" },
				{ LanguageId.nmg, "Kongo" },
				{ LanguageId.nn, "Kongo-Brazzaville" },
				{ LanguageId.nnh, "Congo" },
				{ LanguageId.nqo, "ߞߏ߲߬ߜ߭ߏ߫-ߓߙߊߖ߭ߊ߫" },
				{ LanguageId.nr, "Congo" },
				{ LanguageId.nso, "Congo" },
				{ LanguageId.nus, "Kɔŋgɔ" },
				{ LanguageId.nyn, "Kongo" },
				{ LanguageId.oc, "Congo" },
				{ LanguageId.om, "Koongoo - Biraazaavil" },
				{ LanguageId.or, "କଙ୍ଗୋ-ବ୍ରାଜିଭିଲ୍ଲେ" },
				{ LanguageId.os, "Congo" },
				{ LanguageId.pa, "ਕਾਂਗੋ - ਬ੍ਰਾਜ਼ਾਵਿਲੇ" },
				{ LanguageId.pap, "Congo" },
				{ LanguageId.pcm, "Kóngo – Brázavil" },
				{ LanguageId.pl, "Kongo" },
				{ LanguageId.prg, "Congo" },
				{ LanguageId.ps, "کانګو - بروزوییل" },
				{ LanguageId.pt, "República do Congo" },
				{ LanguageId.qu, "Congo" },
				{ LanguageId.quc, "Congo" },
				{ LanguageId.rm, "Congo-Brazzaville" },
				{ LanguageId.rn, "Kongo" },
				{ LanguageId.ro, "Congo - Brazzaville" },
				{ LanguageId.rof, "Kongo" },
				{ LanguageId.ru, "Конго - Браззавиль" },
				{ LanguageId.rw, "Kongo" },
				{ LanguageId.rwk, "Kongo" },
				{ LanguageId.sa, "Congo" },
				{ LanguageId.sah, "Congo" },
				{ LanguageId.saq, "Kongo" },
				{ LanguageId.sat, "Congo" },
				{ LanguageId.sbp, "Kongo" },
				{ LanguageId.sd, "ڪانگو - برازاویل" },
				{ LanguageId.se, "Kongo-Brazzaville" },
				{ LanguageId.seh, "Congo" },
				{ LanguageId.ses, "Kongoo" },
				{ LanguageId.sg, "Kongö" },
				{ LanguageId.shi, "ⴽⵓⵏⴳⵓ" },
				{ LanguageId.si, "කොංගො - බ්‍රසාවිල්" },
				{ LanguageId.sk, "Konžská republika" },
				{ LanguageId.sl, "Kongo - Brazzaville" },
				{ LanguageId.sma, "Congo" },
				{ LanguageId.smj, "Congo" },
				{ LanguageId.smn, "Kongo täsiväldi" },
				{ LanguageId.sms, "Congo" },
				{ LanguageId.sn, "Kongo" },
				{ LanguageId.so, "Kongo" },
				{ LanguageId.sq, "Kongo-Brazavilë" },
				{ LanguageId.sr, "Конго - Бразавил" },
				{ LanguageId.ss, "Congo" },
				{ LanguageId.ssy, "Congo" },
				{ LanguageId.st, "Kongo" },
				{ LanguageId.su, "Kongo" },
				{ LanguageId.sv, "Kongo-Brazzaville" },
				{ LanguageId.sw, "Kongo - Brazzaville" },
				{ LanguageId.syr, "ܟܘܢܓܘ - ܒܪܐܙܐܒܝܠ" },
				{ LanguageId.ta, "காங்கோ - ப்ராஸாவில்லே" },
				{ LanguageId.te, "కాంగో- బ్రాజావిల్లి" },
				{ LanguageId.teo, "Kongo" },
				{ LanguageId.tg, "Конго - Браззавил" },
				{ LanguageId.th, "คองโก - บราซซาวิล" },
				{ LanguageId.ti, "ኮንጎ" },
				{ LanguageId.tig, "Congo" },
				{ LanguageId.tk, "Kongo - Brazzawil" },
				{ LanguageId.tn, "Congo" },
				{ LanguageId.to, "Kongo - Palasavila" },
				{ LanguageId.tr, "Kongo - Brazavil" },
				{ LanguageId.ts, "Congo" },
				{ LanguageId.tt, "Конго - Браззавиль" },
				{ LanguageId.twq, "Kongoo" },
				{ LanguageId.tzm, "Kungu" },
				{ LanguageId.ug, "كونگو - بىراززاۋىل" },
				{ LanguageId.uk, "Конго – Браззавіль" },
				{ LanguageId.ur, "کانگو - برازاویلے" },
				{ LanguageId.uz, "Kongo – Brazzavil" },
				{ LanguageId.vai, "ꖏꖐ" },
				{ LanguageId.ve, "Congo" },
				{ LanguageId.vi, "Congo - Brazzaville" },
				{ LanguageId.vo, "Congo" },
				{ LanguageId.vun, "Kongo" },
				{ LanguageId.wae, "Kongo Brazzaville" },
				{ LanguageId.wal, "Congo" },
				{ LanguageId.wo, "Réewum Kongo" },
				{ LanguageId.xh, "ECongo - Brazzaville" },
				{ LanguageId.xog, "Kongo" },
				{ LanguageId.yav, "Kongó" },
				{ LanguageId.yi, "קאָנגאָ" },
				{ LanguageId.yo, "Kóńgò – Brazaville" },
				{ LanguageId.zgh, "ⴽⵓⵏⴳⵓ" },
				{ LanguageId.zh, "刚果（布）" },
				{ LanguageId.zu, "i-Congo - Brazzaville" },
			}
		);
	}
}
