// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "41",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Switzerland" },
				{ LanguageId.da, "Schweiz" },
				{ LanguageId.af, "Switserland" },
				{ LanguageId.agq, "Suezàlân" },
				{ LanguageId.ak, "Swetzaland" },
				{ LanguageId.am, "ስዊዘርላንድ" },
				{ LanguageId.ar, "سويسرا" },
				{ LanguageId.arn, "Switzerland" },
				{ LanguageId.@as, "চুইজাৰলেণ্ড" },
				{ LanguageId.asa, "Uthwithi" },
				{ LanguageId.ast, "Suiza" },
				{ LanguageId.az, "İsveçrə" },
				{ LanguageId.ba, "Швейцария" },
				{ LanguageId.bas, "Sùwîs" },
				{ LanguageId.be, "Швейцарыя" },
				{ LanguageId.bem, "Switzerland" },
				{ LanguageId.bez, "Huuswisi" },
				{ LanguageId.bg, "Швейцария" },
				{ LanguageId.bin, "Switzerland" },
				{ LanguageId.bm, "Suwisi" },
				{ LanguageId.bn, "সুইজারল্যান্ড" },
				{ LanguageId.bo, "Switzerland" },
				{ LanguageId.br, "Suis" },
				{ LanguageId.brx, "सुईजारलेण्ड" },
				{ LanguageId.bs, "Švicarska" },
				{ LanguageId.byn, "Switzerland" },
				{ LanguageId.ca, "Suïssa" },
				{ LanguageId.ccp, "𑄥𑄭𑄪𑄎𑄢𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Швейцари" },
				{ LanguageId.ceb, "Switzerland" },
				{ LanguageId.cgg, "Swisi" },
				{ LanguageId.chr, "ᏍᏫᏍ" },
				{ LanguageId.ckb, "سویسڕا" },
				{ LanguageId.co, "Svizzera" },
				{ LanguageId.cs, "Švýcarsko" },
				{ LanguageId.cu, "Switzerland" },
				{ LanguageId.cy, "Y Swistir" },
				{ LanguageId.dav, "Uswisi" },
				{ LanguageId.de, "Schweiz" },
				{ LanguageId.dje, "Swisu" },
				{ LanguageId.doi, "Switzerland" },
				{ LanguageId.dsb, "Šwicarska" },
				{ LanguageId.dua, "Switzerland" },
				{ LanguageId.dv, "Switzerland" },
				{ LanguageId.dz, "སུ་ཝིཊ་ཛར་ལེནཌ" },
				{ LanguageId.ebu, "Uswisi" },
				{ LanguageId.ee, "Switzerland nutome" },
				{ LanguageId.el, "Ελβετία" },
				{ LanguageId.en, "Switzerland" },
				{ LanguageId.eo, "Svisujo" },
				{ LanguageId.es, "Suiza" },
				{ LanguageId.et, "Šveits" },
				{ LanguageId.eu, "Suitza" },
				{ LanguageId.ewo, "Suís" },
				{ LanguageId.fa, "سوئیس" },
				{ LanguageId.ff, "Suwiis" },
				{ LanguageId.fi, "Sveitsi" },
				{ LanguageId.fil, "Switzerland" },
				{ LanguageId.fo, "Sveis" },
				{ LanguageId.fr, "Suisse" },
				{ LanguageId.fur, "Svuizare" },
				{ LanguageId.fy, "Switserlân" },
				{ LanguageId.ga, "an Eilvéis" },
				{ LanguageId.gd, "An Eilbheis" },
				{ LanguageId.gl, "Suíza" },
				{ LanguageId.gn, "Switzerland" },
				{ LanguageId.gsw, "Schwiiz" },
				{ LanguageId.gu, "સ્વિટ્ઝર્લૅન્ડ" },
				{ LanguageId.guz, "Uswisi" },
				{ LanguageId.gv, "Switzerland" },
				{ LanguageId.ha, "Suwizalan" },
				{ LanguageId.haw, "Kuikilana" },
				{ LanguageId.he, "שווייץ" },
				{ LanguageId.hi, "स्विट्ज़रलैंड" },
				{ LanguageId.hr, "Švicarska" },
				{ LanguageId.hsb, "Šwicarska" },
				{ LanguageId.hu, "Svájc" },
				{ LanguageId.hy, "Շվեյցարիա" },
				{ LanguageId.ia, "Suissa" },
				{ LanguageId.ibb, "Switzerland" },
				{ LanguageId.id, "Swiss" },
				{ LanguageId.ig, "Switzerland" },
				{ LanguageId.ii, "Switzerland" },
				{ LanguageId.@is, "Sviss" },
				{ LanguageId.it, "Svizzera" },
				{ LanguageId.iu, "Switzerland" },
				{ LanguageId.ja, "スイス" },
				{ LanguageId.jgo, "Sẅísɛ" },
				{ LanguageId.jmc, "Uswisi" },
				{ LanguageId.jv, "Switserlan" },
				{ LanguageId.ka, "შვეიცარია" },
				{ LanguageId.kab, "Swis" },
				{ LanguageId.kam, "Uswisi" },
				{ LanguageId.kde, "Uswisi" },
				{ LanguageId.kea, "Suisa" },
				{ LanguageId.khq, "Swisu" },
				{ LanguageId.ki, "Uswisi" },
				{ LanguageId.kk, "Швейцария" },
				{ LanguageId.kkj, "Switzerland" },
				{ LanguageId.kl, "Switzerland" },
				{ LanguageId.kln, "Emetab Switzerland" },
				{ LanguageId.km, "ស្វ៊ីស" },
				{ LanguageId.kn, "ಸ್ವಿಟ್ಜರ್ಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "스위스" },
				{ LanguageId.kok, "स्वित्झरलँड" },
				{ LanguageId.kr, "Switzerland" },
				{ LanguageId.ks, "سُوِزَرلینڑ" },
				{ LanguageId.ksb, "Uswisi" },
				{ LanguageId.ksf, "swís" },
				{ LanguageId.ksh, "de Schweiz" },
				{ LanguageId.kw, "Switzerland" },
				{ LanguageId.ky, "Швейцария" },
				{ LanguageId.la, "Helvetia" },
				{ LanguageId.lag, "Uswíisi" },
				{ LanguageId.lb, "Schwäiz" },
				{ LanguageId.lg, "Switizirandi" },
				{ LanguageId.lkt, "Switzerland" },
				{ LanguageId.ln, "Swisɛ" },
				{ LanguageId.lo, "ສະວິດເຊີແລນ" },
				{ LanguageId.lrc, "Switzerland" },
				{ LanguageId.lt, "Šveicarija" },
				{ LanguageId.luo, "Switzerland" },
				{ LanguageId.luy, "Uswisi" },
				{ LanguageId.lv, "Šveice" },
				{ LanguageId.mai, "स्विट्जरलैंड" },
				{ LanguageId.mas, "Uswisi" },
				{ LanguageId.mer, "Swizilandi" },
				{ LanguageId.mfe, "Laswis" },
				{ LanguageId.mg, "Soisa" },
				{ LanguageId.mgo, "Switzerland" },
				{ LanguageId.mi, "Huiterangi" },
				{ LanguageId.mk, "Швајцарија" },
				{ LanguageId.ml, "സ്വിറ്റ്സർലാൻഡ്" },
				{ LanguageId.mn, "Швейцар" },
				{ LanguageId.mni, "Switzerland" },
				{ LanguageId.moh, "Switzerland" },
				{ LanguageId.mr, "स्वित्झर्लंड" },
				{ LanguageId.ms, "Switzerland" },
				{ LanguageId.mt, "l-Iżvizzera" },
				{ LanguageId.mua, "Sǝr Swiss" },
				{ LanguageId.my, "ဆွစ်ဇာလန်" },
				{ LanguageId.mzn, "سوییس" },
				{ LanguageId.naq, "Switzerlandi" },
				{ LanguageId.nb, "Sveits" },
				{ LanguageId.nd, "Switzerland" },
				{ LanguageId.nds, "Swiez" },
				{ LanguageId.ne, "स्विजरल्याण्ड" },
				{ LanguageId.nl, "Zwitserland" },
				{ LanguageId.nmg, "Switzɛrland" },
				{ LanguageId.nn, "Sveits" },
				{ LanguageId.nnh, "Switzerland" },
				{ LanguageId.nqo, "ߛߎߥߌߛ" },
				{ LanguageId.nr, "Switzerland" },
				{ LanguageId.nso, "Switzerland" },
				{ LanguageId.nus, "Switzerland" },
				{ LanguageId.nyn, "Swisi" },
				{ LanguageId.oc, "Suïssa" },
				{ LanguageId.om, "Siwizerlaand" },
				{ LanguageId.or, "ସ୍ୱିଜରଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Switzerland" },
				{ LanguageId.pa, "ਸਵਿਟਜ਼ਰਲੈਂਡ" },
				{ LanguageId.pap, "Switzerland" },
				{ LanguageId.pcm, "Swítsaland" },
				{ LanguageId.pl, "Szwajcaria" },
				{ LanguageId.prg, "Switzerland" },
				{ LanguageId.ps, "سویس" },
				{ LanguageId.pt, "Suíça" },
				{ LanguageId.qu, "Suiza" },
				{ LanguageId.quc, "Switzerland" },
				{ LanguageId.rm, "Svizra" },
				{ LanguageId.rn, "Ubusuwisi" },
				{ LanguageId.ro, "Elveția" },
				{ LanguageId.rof, "Uswisi" },
				{ LanguageId.ru, "Швейцария" },
				{ LanguageId.rw, "Busuwisi" },
				{ LanguageId.rwk, "Uswisi" },
				{ LanguageId.sa, "Switzerland" },
				{ LanguageId.sah, "Switzerland" },
				{ LanguageId.saq, "Uswisi" },
				{ LanguageId.sat, "Switzerland" },
				{ LanguageId.sbp, "Uswisi" },
				{ LanguageId.sd, "سوئزرلينڊ" },
				{ LanguageId.se, "Šveica" },
				{ LanguageId.seh, "Suíça" },
				{ LanguageId.ses, "Swisu" },
				{ LanguageId.sg, "Sûîsi" },
				{ LanguageId.shi, "ⵙⵡⵉⵙⵔⴰ" },
				{ LanguageId.si, "ස්විස්ටර්ලන්තය" },
				{ LanguageId.sk, "Švajčiarsko" },
				{ LanguageId.sl, "Švica" },
				{ LanguageId.sma, "Switzerland" },
				{ LanguageId.smj, "Switzerland" },
				{ LanguageId.smn, "Sveitsi" },
				{ LanguageId.sms, "Switzerland" },
				{ LanguageId.sn, "Switzerland" },
				{ LanguageId.so, "Swiiserlaand" },
				{ LanguageId.sq, "Zvicër" },
				{ LanguageId.sr, "Швајцарска" },
				{ LanguageId.ss, "Switzerland" },
				{ LanguageId.ssy, "Switzerland" },
				{ LanguageId.st, "Switzerland" },
				{ LanguageId.su, "Swiss" },
				{ LanguageId.sv, "Schweiz" },
				{ LanguageId.sw, "Uswisi" },
				{ LanguageId.syr, "ܣܘܝܣܪܐ" },
				{ LanguageId.ta, "ஸ்விட்சர்லாந்து" },
				{ LanguageId.te, "స్విట్జర్లాండ్" },
				{ LanguageId.teo, "Uswisi" },
				{ LanguageId.tg, "Швейтсария" },
				{ LanguageId.th, "สวิตเซอร์แลนด์" },
				{ LanguageId.ti, "ስዊዘርላንድ" },
				{ LanguageId.tig, "Switzerland" },
				{ LanguageId.tk, "Şweýsariýa" },
				{ LanguageId.tn, "Switzerland" },
				{ LanguageId.to, "Suisilani" },
				{ LanguageId.tr, "İsviçre" },
				{ LanguageId.ts, "Switzerland" },
				{ LanguageId.tt, "Швейцария" },
				{ LanguageId.twq, "Swisu" },
				{ LanguageId.tzm, "Swisra" },
				{ LanguageId.ug, "شىۋېتسارىيە" },
				{ LanguageId.uk, "Швейцарія" },
				{ LanguageId.ur, "سوئٹزر لینڈ" },
				{ LanguageId.uz, "Shveytsariya" },
				{ LanguageId.vai, "ꖬꔃꕤ ꖨꕮꕊ" },
				{ LanguageId.ve, "Switzerland" },
				{ LanguageId.vi, "Thụy Sĩ" },
				{ LanguageId.vo, "Switzerland" },
				{ LanguageId.vun, "Uswisi" },
				{ LanguageId.wae, "Schwiz" },
				{ LanguageId.wal, "Switzerland" },
				{ LanguageId.wo, "Siwis" },
				{ LanguageId.xh, "ESwitzerland" },
				{ LanguageId.xog, "Switizirandi" },
				{ LanguageId.yav, "suwíis" },
				{ LanguageId.yi, "שווייץ" },
				{ LanguageId.yo, "Súwísìlanìdì" },
				{ LanguageId.zgh, "ⵙⵡⵉⵙⵔⴰ" },
				{ LanguageId.zh, "瑞士" },
				{ LanguageId.zu, "i-Switzerland" },
			}
		);
	}
}
