using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CI
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "225",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Cote d'Ivoire" },
				{ LanguageId.da, "Elfenbenskysten" },
				{ LanguageId.af, "Ivoorkus" },
				{ LanguageId.agq, "Cote d'Ivoire" },
				{ LanguageId.ak, "Cote d'Ivoire" },
				{ LanguageId.am, "ኮት ዲቯር" },
				{ LanguageId.ar, "ساحل العاج" },
				{ LanguageId.arn, "Cote d'Ivoire" },
				{ LanguageId.@as, "Cote d'Ivoire" },
				{ LanguageId.asa, "Cote d'Ivoire" },
				{ LanguageId.ast, "Costa de Marfil" },
				{ LanguageId.az, "Kot-d'İvuar" },
				{ LanguageId.ba, "Cote d'Ivoire" },
				{ LanguageId.bas, "Cote d'Ivoire" },
				{ LanguageId.be, "Кот-д'Івуар" },
				{ LanguageId.bem, "Cote d'Ivoire" },
				{ LanguageId.bez, "Cote d'Ivoire" },
				{ LanguageId.bg, "Кот д'Ивоар" },
				{ LanguageId.bin, "Cote d'Ivoire" },
				{ LanguageId.bm, "Cote d'Ivoire" },
				{ LanguageId.bn, "কোট ডি'আইভরি" },
				{ LanguageId.bo, "Cote d'Ivoire" },
				{ LanguageId.br, "Aod an Olifant" },
				{ LanguageId.brx, "Cote d'Ivoire" },
				{ LanguageId.bs, "Obala Slonovače" },
				{ LanguageId.byn, "Cote d'Ivoire" },
				{ LanguageId.ca, "Costa d'Ivori" },
				{ LanguageId.ccp, "Cote d'Ivoire" },
				{ LanguageId.ce, "Cote d'Ivoire" },
				{ LanguageId.ceb, "Cote d'Ivoire" },
				{ LanguageId.cgg, "Cote d'Ivoire" },
				{ LanguageId.chr, "Cote d'Ivoire" },
				{ LanguageId.ckb, "کۆتدیڤوار" },
				{ LanguageId.co, "Costa d'Avoriu" },
				{ LanguageId.cs, "Pobřeží slonoviny" },
				{ LanguageId.cu, "Cote d'Ivoire" },
				{ LanguageId.cy, "Côte d'Ivoire" },
				{ LanguageId.dav, "Cote d'Ivoire" },
				{ LanguageId.de, "Côte d'Ivoire" },
				{ LanguageId.dje, "Cote d'Ivoire" },
				{ LanguageId.doi, "Cote d'Ivoire" },
				{ LanguageId.dsb, "Côte d'Ivoire" },
				{ LanguageId.dua, "Cote d'Ivoire" },
				{ LanguageId.dv, "Cote d'Ivoire" },
				{ LanguageId.dz, "Cote d'Ivoire" },
				{ LanguageId.ebu, "Cote d'Ivoire" },
				{ LanguageId.ee, "Cote d'Ivoire" },
				{ LanguageId.el, "Ακτή Ελεφαντοστού" },
				{ LanguageId.en, "Cote d'Ivoire" },
				{ LanguageId.eo, "Ebur-Bordo" },
				{ LanguageId.es, "Costa de Marfil" },
				{ LanguageId.et, "Elevandiluurannik" },
				{ LanguageId.eu, "Boli Kosta" },
				{ LanguageId.ewo, "Cote d'Ivoire" },
				{ LanguageId.fa, "ساحل عاج" },
				{ LanguageId.ff, "Cote d'Ivoire" },
				{ LanguageId.fi, "Norsunluurannikko" },
				{ LanguageId.fil, "Cote d'Ivoire" },
				{ LanguageId.fo, "Cote d'Ivoire" },
				{ LanguageId.fr, "Côte d'Ivoire" },
				{ LanguageId.fur, "Cote d'Ivoire" },
				{ LanguageId.fy, "Ivoorkust" },
				{ LanguageId.ga, "An Cósta Eabhair" },
				{ LanguageId.gd, "Côte d'Ivoire" },
				{ LanguageId.gl, "Costa de Marfil" },
				{ LanguageId.gn, "Cote d'Ivoire" },
				{ LanguageId.gsw, "Côte d'Ivoire" },
				{ LanguageId.gu, "કોટ ડી'આઇવરી" },
				{ LanguageId.guz, "Cote d'Ivoire" },
				{ LanguageId.gv, "Cote d'Ivoire" },
				{ LanguageId.ha, "Cote d'Ivoire" },
				{ LanguageId.haw, "Cote d'Ivoire" },
				{ LanguageId.he, "חוף השנהב" },
				{ LanguageId.hi, "कोटे डी आइवर" },
				{ LanguageId.hr, "Obala Bjelokosti" },
				{ LanguageId.hsb, "Côte d'Ivoire" },
				{ LanguageId.hu, "Elefántcsontpart" },
				{ LanguageId.hy, "Կոտ դ'Իվուար" },
				{ LanguageId.ia, "Costa de Ebore" },
				{ LanguageId.ibb, "Cote d'Ivoire" },
				{ LanguageId.id, "Pantai Gading" },
				{ LanguageId.ig, "Cote d'Ivoire" },
				{ LanguageId.ii, "Cote d'Ivoire" },
				{ LanguageId.@is, "Fílabeinsströndin" },
				{ LanguageId.it, "Costa d'Avorio" },
				{ LanguageId.iu, "Cote d'Ivoire" },
				{ LanguageId.ja, "コートジボワール" },
				{ LanguageId.jgo, "Cote d'Ivoire" },
				{ LanguageId.jmc, "Cote d'Ivoire" },
				{ LanguageId.jv, "Pantai Gading" },
				{ LanguageId.ka, "კოტ-დ'ივუარი" },
				{ LanguageId.kab, "Cote d'Ivoire" },
				{ LanguageId.kam, "Cote d'Ivoire" },
				{ LanguageId.kde, "Cote d'Ivoire" },
				{ LanguageId.kea, "Cote d'Ivoire" },
				{ LanguageId.khq, "Cote d'Ivoire" },
				{ LanguageId.ki, "Cote d'Ivoire" },
				{ LanguageId.kk, "Кот-д'Ивуар" },
				{ LanguageId.kkj, "Cote d'Ivoire" },
				{ LanguageId.kl, "Cote d'Ivoire" },
				{ LanguageId.kln, "Cote d'Ivoire" },
				{ LanguageId.km, "កូត ឌី វ័រ" },
				{ LanguageId.kn, "ಕೋಟ್ ಡಿ'ಐವರಿ" },
				{ LanguageId.ko, "코트디부아르" },
				{ LanguageId.kok, "Cote d'Ivoire" },
				{ LanguageId.kr, "Cote d'Ivoire" },
				{ LanguageId.ks, "Cote d'Ivoire" },
				{ LanguageId.ksb, "Cote d'Ivoire" },
				{ LanguageId.ksf, "Cote d'Ivoire" },
				{ LanguageId.ksh, "Cote d'Ivoire" },
				{ LanguageId.kw, "Cote d'Ivoire" },
				{ LanguageId.ky, "Кот-д'Ивуар" },
				{ LanguageId.la, "Litus Eburneum" },
				{ LanguageId.lag, "Cote d'Ivoire" },
				{ LanguageId.lb, "Côte d'Ivoire" },
				{ LanguageId.lg, "Cote d'Ivoire" },
				{ LanguageId.lkt, "Cote d'Ivoire" },
				{ LanguageId.ln, "Cote d'Ivoire" },
				{ LanguageId.lo, "Cote d'Ivoire" },
				{ LanguageId.lrc, "Cote d'Ivoire" },
				{ LanguageId.lt, "Dramblio Kaulo Krantas" },
				{ LanguageId.luo, "Cote d'Ivoire" },
				{ LanguageId.luy, "Cote d'Ivoire" },
				{ LanguageId.lv, "Kotdivuāra" },
				{ LanguageId.mai, "Cote d'Ivoire" },
				{ LanguageId.mas, "Cote d'Ivoire" },
				{ LanguageId.mer, "Cote d'Ivoire" },
				{ LanguageId.mfe, "Cote d'Ivoire" },
				{ LanguageId.mg, "Cote d'Ivoire" },
				{ LanguageId.mgo, "Cote d'Ivoire" },
				{ LanguageId.mi, "Cote d'Ivoire" },
				{ LanguageId.mk, "Обала на Слоновата Коска" },
				{ LanguageId.ml, "കോട്ട് ഡി ഐവറി" },
				{ LanguageId.mn, "Кот-д'Ивуар" },
				{ LanguageId.mni, "Cote d'Ivoire" },
				{ LanguageId.moh, "Cote d'Ivoire" },
				{ LanguageId.mr, "कोट डी आयव्होइरे" },
				{ LanguageId.ms, "Côte d'Ivoire" },
				{ LanguageId.mt, "Costa tal-Ivorju" },
				{ LanguageId.mua, "Cote d'Ivoire" },
				{ LanguageId.my, "ကို့တ်ဒီဗွာ" },
				{ LanguageId.mzn, "Cote d'Ivoire" },
				{ LanguageId.naq, "Cote d'Ivoire" },
				{ LanguageId.nb, "Elfenbenskysten" },
				{ LanguageId.nd, "Cote d'Ivoire" },
				{ LanguageId.nds, "Elfenbeenküst" },
				{ LanguageId.ne, "कोटे दिवोइरे" },
				{ LanguageId.nl, "Ivoorkust" },
				{ LanguageId.nmg, "Cote d'Ivoire" },
				{ LanguageId.nn, "Elfenbeinskysten" },
				{ LanguageId.nnh, "Cote d'Ivoire" },
				{ LanguageId.nqo, "Cote d'Ivoire" },
				{ LanguageId.nr, "Cote d'Ivoire" },
				{ LanguageId.nso, "Cote d'Ivoire" },
				{ LanguageId.nus, "Cote d'Ivoire" },
				{ LanguageId.nyn, "Cote d'Ivoire" },
				{ LanguageId.oc, "Còsta d'Evòri" },
				{ LanguageId.om, "Cote d'Ivoire" },
				{ LanguageId.or, "କୋଟେ ଡି'ଆଇଭୋରି" },
				{ LanguageId.os, "Cote d'Ivoire" },
				{ LanguageId.pa, "ਕੋਟੇ ਡੀ'ਆਈਵੋਰ" },
				{ LanguageId.pap, "Cote d'Ivoire" },
				{ LanguageId.pcm, "Cote d'Ivoire" },
				{ LanguageId.pl, "WybrzeŻe Kości Słoniowej" },
				{ LanguageId.prg, "Cote d'Ivoire" },
				{ LanguageId.ps, "کوت ډیوویر" },
				{ LanguageId.pt, "Costa do Marfim" },
				{ LanguageId.qu, "Cote d'Ivoire" },
				{ LanguageId.quc, "Cote d'Ivoire" },
				{ LanguageId.rm, "Costa d'Ivur" },
				{ LanguageId.rn, "Cote d'Ivoire" },
				{ LanguageId.ro, "Coasta de Fildeș" },
				{ LanguageId.rof, "Cote d'Ivoire" },
				{ LanguageId.ru, "Кот-д'Ивуар" },
				{ LanguageId.rw, "Côte d'Ivoire" },
				{ LanguageId.rwk, "Cote d'Ivoire" },
				{ LanguageId.sa, "Cote d'Ivoire" },
				{ LanguageId.sah, "Cote d'Ivoire" },
				{ LanguageId.saq, "Cote d'Ivoire" },
				{ LanguageId.sat, "Cote d'Ivoire" },
				{ LanguageId.sbp, "Cote d'Ivoire" },
				{ LanguageId.sd, "ڪوٽ ڊي آئيوائر" },
				{ LanguageId.se, "Cote d'Ivoire" },
				{ LanguageId.seh, "Cote d'Ivoire" },
				{ LanguageId.ses, "Cote d'Ivoire" },
				{ LanguageId.sg, "Cote d'Ivoire" },
				{ LanguageId.shi, "Cote d'Ivoire" },
				{ LanguageId.si, "කෝට් ඩි අයිවරි" },
				{ LanguageId.sk, "Pobržie Slonoviny" },
				{ LanguageId.sl, "Slonokoščena obala" },
				{ LanguageId.sma, "Cote d'Ivoire" },
				{ LanguageId.smj, "Cote d'Ivoire" },
				{ LanguageId.smn, "Cote d'Ivoire" },
				{ LanguageId.sms, "Cote d'Ivoire" },
				{ LanguageId.sn, "Cote d'Ivoire" },
				{ LanguageId.so, "Xeebta Foolmaroodi" },
				{ LanguageId.sq, "Bregu i Fildishtë" },
				{ LanguageId.sr, "Obala Slonovače" },
				{ LanguageId.ss, "Cote d'Ivoire" },
				{ LanguageId.ssy, "Cote d'Ivoire" },
				{ LanguageId.st, "Cote d'Ivoire" },
				{ LanguageId.su, "Basisir Gading" },
				{ LanguageId.sv, "Elfenbenskusten" },
				{ LanguageId.sw, "Pwani ya Pembe" },
				{ LanguageId.syr, "Cote d'Ivoire" },
				{ LanguageId.ta, "கோட் டி ஐவரி" },
				{ LanguageId.te, "కోట్ డి ఐవరీ" },
				{ LanguageId.teo, "Cote d'Ivoire" },
				{ LanguageId.tg, "Кот-д'Ивуар" },
				{ LanguageId.th, "โกตดิวัวร์" },
				{ LanguageId.ti, "Cote d'Ivoire" },
				{ LanguageId.tig, "Cote d'Ivoire" },
				{ LanguageId.tk, "Kot-d'Iwuar" },
				{ LanguageId.tn, "Cote d'Ivoire" },
				{ LanguageId.to, "Cote d'Ivoire" },
				{ LanguageId.tr, "Fildişi Sahili" },
				{ LanguageId.ts, "Cote d'Ivoire" },
				{ LanguageId.tt, "Кот-д'Ивуар" },
				{ LanguageId.twq, "Cote d'Ivoire" },
				{ LanguageId.tzm, "Cote d'Ivoire" },
				{ LanguageId.ug, "پىل چىشى قىرغىقى" },
				{ LanguageId.uk, "Кот-д'Івуар" },
				{ LanguageId.ur, "آئیوری کوسٹ" },
				{ LanguageId.uz, "Kot-d'Ivuar" },
				{ LanguageId.vai, "Cote d'Ivoire" },
				{ LanguageId.ve, "Cote d'Ivoire" },
				{ LanguageId.vi, "Bờ Biển Ngà" },
				{ LanguageId.vo, "Cote d'Ivoire" },
				{ LanguageId.vun, "Cote d'Ivoire" },
				{ LanguageId.wae, "Cote d'Ivoire" },
				{ LanguageId.wal, "Cote d'Ivoire" },
				{ LanguageId.wo, "Cote d'Ivoire" },
				{ LanguageId.xh, "Cote d'Ivoire" },
				{ LanguageId.xog, "Cote d'Ivoire" },
				{ LanguageId.yav, "Cote d'Ivoire" },
				{ LanguageId.yi, "העלפֿאַנדביין ברעג" },
				{ LanguageId.yo, "Cote d'Ivoire" },
				{ LanguageId.zgh, "Cote d'Ivoire" },
				{ LanguageId.zh, "科特迪瓦" },
				{ LanguageId.zu, "I-Côte d'Ivoire" },
			}
		);
	}
}
