// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CI
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "225",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Cote d'Ivoire" },
				{ LanguageId.da, "Elfenbenskysten" },
				{ LanguageId.af, "Ivoorkus" },
				{ LanguageId.agq, "Ku Dɨ̀vûa" },
				{ LanguageId.ak, "Kodivuwa" },
				{ LanguageId.am, "ኮትዲቯር" },
				{ LanguageId.ar, "ساحل العاج" },
				{ LanguageId.arn, "Cote d'Ivoire" },
				{ LanguageId.@as, "কোটে ডি আইভৰ" },
				{ LanguageId.asa, "Kodivaa" },
				{ LanguageId.ast, "Costa de Marfil" },
				{ LanguageId.az, "Kotd’ivuar" },
				{ LanguageId.ba, "Кот-д’Ивуар" },
				{ LanguageId.bas, "Màŋ mi Njɔ̂k" },
				{ LanguageId.be, "Кот-д’Івуар" },
				{ LanguageId.bem, "Cote d'Ivoire" },
				{ LanguageId.bez, "Hukodivaa" },
				{ LanguageId.bg, "Кот д’Ивоар" },
				{ LanguageId.bin, "Cote d'Ivoire" },
				{ LanguageId.bm, "Kodiwari" },
				{ LanguageId.bn, "কোট ডি‘আইভোর" },
				{ LanguageId.bo, "Cote d'Ivoire" },
				{ LanguageId.br, "Aod-an-Olifant" },
				{ LanguageId.brx, "कट दिभवेर" },
				{ LanguageId.bs, "Obala Slonovače" },
				{ LanguageId.byn, "Cote d'Ivoire" },
				{ LanguageId.ca, "Côte d’Ivoire" },
				{ LanguageId.ccp, "𑄃𑄭𑄞𑄧𑄢𑄨 𑄇𑄮𑄌𑄴𑄑𑄴" },
				{ LanguageId.ce, "Кот-Д’ивуар" },
				{ LanguageId.ceb, "Cote d’Ivoire" },
				{ LanguageId.cgg, "Aivore Kositi" },
				{ LanguageId.chr, "ᎢᏬᎵ ᎾᎿ ᎠᎹᏳᎶᏗ" },
				{ LanguageId.ckb, "کۆتدیڤوار" },
				{ LanguageId.co, "Costa d'Avoriu" },
				{ LanguageId.cs, "Pobřeží slonoviny" },
				{ LanguageId.cu, "Cote d'Ivoire" },
				{ LanguageId.cy, "Côte d’Ivoire" },
				{ LanguageId.dav, "Kodivaa" },
				{ LanguageId.de, "Côte d’Ivoire" },
				{ LanguageId.dje, "Kudwar" },
				{ LanguageId.doi, "Cote d'Ivoire" },
				{ LanguageId.dsb, "Côte d’Ivoire" },
				{ LanguageId.dua, "Cote d'Ivoire" },
				{ LanguageId.dv, "Cote d'Ivoire" },
				{ LanguageId.dz, "ཀོ་ཊེ་ ཌི་ཨི་ཝོ་རེ" },
				{ LanguageId.ebu, "Kodivaa" },
				{ LanguageId.ee, "Kote d’Ivoire nutome" },
				{ LanguageId.el, "Ακτή Ελεφαντοστού" },
				{ LanguageId.en, "Côte d’Ivoire" },
				{ LanguageId.eo, "Ebur-Bordo" },
				{ LanguageId.es, "Côte d’Ivoire" },
				{ LanguageId.et, "Elevandiluurannik" },
				{ LanguageId.eu, "Boli Kosta" },
				{ LanguageId.ewo, "Kód Divɔ́r" },
				{ LanguageId.fa, "ساحل عاج" },
				{ LanguageId.ff, "Kodduwaar" },
				{ LanguageId.fi, "Norsunluurannikko" },
				{ LanguageId.fil, "Côte d’Ivoire" },
				{ LanguageId.fo, "Fílabeinsstrondin" },
				{ LanguageId.fr, "Côte d’Ivoire" },
				{ LanguageId.fur, "Cueste di Avoli" },
				{ LanguageId.fy, "Ivoorkust" },
				{ LanguageId.ga, "Côte d’Ivoire" },
				{ LanguageId.gd, "Côte d’Ivoire" },
				{ LanguageId.gl, "Côte d’Ivoire" },
				{ LanguageId.gn, "Cote d'Ivoire" },
				{ LanguageId.gsw, "Elfebäiküschte" },
				{ LanguageId.gu, "કોટ ડીઆઇવરી" },
				{ LanguageId.guz, "Kodivaa" },
				{ LanguageId.gv, "Cote d'Ivoire" },
				{ LanguageId.ha, "Aibari Kwas" },
				{ LanguageId.haw, "Cote d'Ivoire" },
				{ LanguageId.he, "חוף השנהב" },
				{ LanguageId.hi, "कोत दिवुआर" },
				{ LanguageId.hr, "Obala Bjelokosti" },
				{ LanguageId.hsb, "Côte d’Ivoire" },
				{ LanguageId.hu, "Elefántcsontpart" },
				{ LanguageId.hy, "Կոտ դ՚Իվուար" },
				{ LanguageId.ia, "Costa de Ebore" },
				{ LanguageId.ibb, "Cote d'Ivoire" },
				{ LanguageId.id, "Côte d’Ivoire" },
				{ LanguageId.ig, "Côte d’Ivoire" },
				{ LanguageId.ii, "Cote d'Ivoire" },
				{ LanguageId.@is, "Fílabeinsströndin" },
				{ LanguageId.it, "Costa d’Avorio" },
				{ LanguageId.iu, "Cote d'Ivoire" },
				{ LanguageId.ja, "コートジボワール" },
				{ LanguageId.jgo, "Kɔ́t Ndivwâ" },
				{ LanguageId.jmc, "Kodivaa" },
				{ LanguageId.jv, "Pasisir Gadhing" },
				{ LanguageId.ka, "კოტ-დივუარი" },
				{ LanguageId.kab, "Kuṭ Divwar" },
				{ LanguageId.kam, "Kodivaa" },
				{ LanguageId.kde, "Kodivaa" },
				{ LanguageId.kea, "Kosta di Marfin" },
				{ LanguageId.khq, "Kudwar" },
				{ LanguageId.ki, "Kodivaa" },
				{ LanguageId.kk, "Кот-д’Ивуар" },
				{ LanguageId.kkj, "Cote d'Ivoire" },
				{ LanguageId.kl, "Cote d'Ivoire" },
				{ LanguageId.kln, "Emetab Côte d’Ivoire" },
				{ LanguageId.km, "កូតឌីវ័រ" },
				{ LanguageId.kn, "ಕೋತ್ ದ್‘ಇವಾರ್" },
				{ LanguageId.ko, "코트디부아르" },
				{ LanguageId.kok, "कोस्ता दो मारफ़ीम" },
				{ LanguageId.kr, "Cote d'Ivoire" },
				{ LanguageId.ks, "کوٹ ڈلوائر" },
				{ LanguageId.ksb, "Kodivaa" },
				{ LanguageId.ksf, "kɔtiwuár" },
				{ LanguageId.ksh, "Älfebeijn-Köß" },
				{ LanguageId.kw, "Cote d'Ivoire" },
				{ LanguageId.ky, "Кот-д’Ивуар" },
				{ LanguageId.la, "Litus Eburneum" },
				{ LanguageId.lag, "Ivori Kositi" },
				{ LanguageId.lb, "Côte d’Ivoire" },
				{ LanguageId.lg, "Kote Divwa" },
				{ LanguageId.lkt, "Cote d'Ivoire" },
				{ LanguageId.ln, "Kotídivualɛ" },
				{ LanguageId.lo, "ໂຄຕີ ວົວ" },
				{ LanguageId.lrc, "Cote d'Ivoire" },
				{ LanguageId.lt, "Dramblio Kaulo Krantas" },
				{ LanguageId.luo, "Côte d" },
				{ LanguageId.luy, "Kodivaa" },
				{ LanguageId.lv, "Kotdivuāra" },
				{ LanguageId.mai, "कोट डी आइवर" },
				{ LanguageId.mas, "Kodivaa" },
				{ LanguageId.mer, "Kodivaa" },
				{ LanguageId.mfe, "Côte d’Ivoire" },
				{ LanguageId.mg, "Côte d’Ivoire" },
				{ LanguageId.mgo, "Cote d'Ivoire" },
				{ LanguageId.mi, "Te Tai Rei" },
				{ LanguageId.mk, "Брегот на Слоновата Коска" },
				{ LanguageId.ml, "കോട്ട് ഡി വാർ" },
				{ LanguageId.mn, "Кот-д’Ивуар" },
				{ LanguageId.mni, "Cote d'Ivoire" },
				{ LanguageId.moh, "Cote d'Ivoire" },
				{ LanguageId.mr, "कोत द’ईवोआर" },
				{ LanguageId.ms, "Cote d’Ivoire" },
				{ LanguageId.mt, "il-Kosta tal-Avorju" },
				{ LanguageId.mua, "ser Ivoiriya" },
				{ LanguageId.my, "ကို့တ် ဒီဗွာ" },
				{ LanguageId.mzn, "عاج ِساحل" },
				{ LanguageId.naq, "Ivoorkusi" },
				{ LanguageId.nb, "Elfenbenskysten" },
				{ LanguageId.nd, "Ivory Coast" },
				{ LanguageId.nds, "Elfenbeenküst" },
				{ LanguageId.ne, "कोट दिभोर" },
				{ LanguageId.nl, "Ivoorkust" },
				{ LanguageId.nmg, "Kote d´Ivoire" },
				{ LanguageId.nn, "Elfenbeinskysten" },
				{ LanguageId.nnh, "Cote d'Ivoire" },
				{ LanguageId.nqo, "ߜߋ߲-ߞߐ߰ߖߌ߬ߘߊ" },
				{ LanguageId.nr, "Cote d'Ivoire" },
				{ LanguageId.nso, "Cote d'Ivoire" },
				{ LanguageId.nus, "Kodibo̱o̱" },
				{ LanguageId.nyn, "Aivore Kositi" },
				{ LanguageId.oc, "Còsta d'Evòri" },
				{ LanguageId.om, "Koti divoor" },
				{ LanguageId.or, "କୋତ୍ ଡି ଭ୍ଵାର୍" },
				{ LanguageId.os, "Cote d'Ivoire" },
				{ LanguageId.pa, "ਕੋਟ ਡੀਵੋਆਰ" },
				{ LanguageId.pap, "Cote d'Ivoire" },
				{ LanguageId.pcm, "Aívri Kost" },
				{ LanguageId.pl, "Côte d’Ivoire" },
				{ LanguageId.prg, "Cote d'Ivoire" },
				{ LanguageId.ps, "د عاج ساحل" },
				{ LanguageId.pt, "Costa do Marfim" },
				{ LanguageId.qu, "Côte d’Ivoire" },
				{ LanguageId.quc, "Cote d'Ivoire" },
				{ LanguageId.rm, "Costa d’Ivur" },
				{ LanguageId.rn, "Kotedivuware" },
				{ LanguageId.ro, "Côte d’Ivoire" },
				{ LanguageId.rof, "Kodivaa" },
				{ LanguageId.ru, "Кот-д’Ивуар" },
				{ LanguageId.rw, "Côte d'Ivoire" },
				{ LanguageId.rwk, "Kodivaa" },
				{ LanguageId.sa, "Cote d'Ivoire" },
				{ LanguageId.sah, "Cote d'Ivoire" },
				{ LanguageId.saq, "Kodivaa" },
				{ LanguageId.sat, "Cote d'Ivoire" },
				{ LanguageId.sbp, "Kodivaya" },
				{ LanguageId.sd, "ڪوٽي ويرا" },
				{ LanguageId.se, "Elfenbenariddu" },
				{ LanguageId.seh, "Costa do Marfim" },
				{ LanguageId.ses, "Kudwar" },
				{ LanguageId.sg, "Kôdivüära" },
				{ LanguageId.shi, "ⴽⵓⵜ ⴷⵉⴼⵡⴰⵔ" },
				{ LanguageId.si, "කෝට් දි අයිවරි" },
				{ LanguageId.sk, "Pobrežie Slonoviny" },
				{ LanguageId.sl, "Slonokoščena obala" },
				{ LanguageId.sma, "Cote d'Ivoire" },
				{ LanguageId.smj, "Cote d'Ivoire" },
				{ LanguageId.smn, "Côte d’Ivoire" },
				{ LanguageId.sms, "Cote d'Ivoire" },
				{ LanguageId.sn, "Ivory Coast" },
				{ LanguageId.so, "Ayfori Koost" },
				{ LanguageId.sq, "Côte d’Ivoire" },
				{ LanguageId.sr, "Обала Слоноваче (Кот д’Ивоар)" },
				{ LanguageId.ss, "Cote d'Ivoire" },
				{ LanguageId.ssy, "Cote d'Ivoire" },
				{ LanguageId.st, "Cote d'Ivoire" },
				{ LanguageId.su, "Basisir Gading" },
				{ LanguageId.sv, "Elfenbenskusten" },
				{ LanguageId.sw, "Cote d’Ivoire" },
				{ LanguageId.syr, "ܩܘܛ ܕܝܒܘܐܪ" },
				{ LanguageId.ta, "கோட் தி’வாயர்" },
				{ LanguageId.te, "కోట్ డి ఐవోర్" },
				{ LanguageId.teo, "Kodivaa" },
				{ LanguageId.tg, "Кот-д’Ивуар" },
				{ LanguageId.th, "โกตดิวัวร์" },
				{ LanguageId.ti, "ኮት ዲቭዋር" },
				{ LanguageId.tig, "Cote d'Ivoire" },
				{ LanguageId.tk, "Kot-d’Iwuar" },
				{ LanguageId.tn, "Cote d'Ivoire" },
				{ LanguageId.to, "Matafonua ʻAivolī" },
				{ LanguageId.tr, "Côte d’Ivoire" },
				{ LanguageId.ts, "Cote d'Ivoire" },
				{ LanguageId.tt, "Кот-д’Ивуар" },
				{ LanguageId.twq, "Kudwar" },
				{ LanguageId.tzm, "Taɣazut n Uszer" },
				{ LanguageId.ug, "كوتې دې ئىۋوئىر" },
				{ LanguageId.uk, "Кот-дʼІвуар" },
				{ LanguageId.ur, "کوٹ ڈی آئیوری" },
				{ LanguageId.uz, "Kot-d’Ivuar" },
				{ LanguageId.vai, "ꖏꔳ ꕾꕎ" },
				{ LanguageId.ve, "Cote d'Ivoire" },
				{ LanguageId.vi, "Côte d’Ivoire" },
				{ LanguageId.vo, "Cote d'Ivoire" },
				{ LanguageId.vun, "Kodivaa" },
				{ LanguageId.wae, "Elfebeiküšta" },
				{ LanguageId.wal, "Cote d'Ivoire" },
				{ LanguageId.wo, "Kodiwaar" },
				{ LanguageId.xh, "ECôte d’Ivoire" },
				{ LanguageId.xog, "Kote Divwa" },
				{ LanguageId.yav, "Kótifualɛ" },
				{ LanguageId.yi, "העלפֿאַ נדביין בארטן" },
				{ LanguageId.yo, "Kóútè forà" },
				{ LanguageId.zgh, "ⴽⵓⵜ ⴷⵉⴼⵡⴰⵔ" },
				{ LanguageId.zh, "科特迪瓦" },
				{ LanguageId.zu, "i-Côte d’Ivoire" },
			}
		);
	}
}
