using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CR
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "506",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Costa Rica" },
				{ LanguageId.af, "Costa Rica" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኮስታሪካ" },
				{ LanguageId.ar, "كوستا ريكا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Kosta Rika" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Коста-Рыка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Коста Рика" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "কোস্টারিকা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Costa Rica" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "kosta rika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Costa Rica" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Costa Rica" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Costa Rica" },
				{ LanguageId.cs, "Kostarika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Costa Rica" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Costa Rica" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Κόστα Ρίκα" },
				{ LanguageId.en, "Costa Rica" },
				{ LanguageId.eo, "Kostariko" },
				{ LanguageId.es, "Costa Rica" },
				{ LanguageId.et, "Costa Rica" },
				{ LanguageId.eu, "Costa Rica" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "کاستاریکا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Costa Rica" },
				{ LanguageId.fil, "Costa Rica" },
				{ LanguageId.fo, "Kosta Rika" },
				{ LanguageId.fr, "Costa Rica" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Kosta Rika" },
				{ LanguageId.ga, "Costa Rica" },
				{ LanguageId.gd, "Costa Rica" },
				{ LanguageId.gl, "Costa Rica" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "કોસ્ટા રિકા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Costa Rica" },
				{ LanguageId.haw, "Koka Rika" },
				{ LanguageId.he, "קוסטה ריקה" },
				{ LanguageId.hi, "कोस्टा रिका" },
				{ LanguageId.hr, "Kostarika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Costa Rica" },
				{ LanguageId.hy, "Կոստա Ռիկա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kosta Rika" },
				{ LanguageId.ig, "Costa Rica" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Kosta Ríka" },
				{ LanguageId.it, "Costa Rica" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コスタリカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kosta Rika" },
				{ LanguageId.ka, "კოსტა - რიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Коста-Рика" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កូស្តារីកា" },
				{ LanguageId.kn, "ಕೋಸ್ಟ ರಿಕಾ" },
				{ LanguageId.ko, "코스타리카" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Коста Рика" },
				{ LanguageId.la, "Costa Rica" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Costa Rica" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Costa Rica" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kosta Rika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Kostarika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Costa Rica" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Costa Rica" },
				{ LanguageId.mk, "Костарика" },
				{ LanguageId.ml, "കോസ്റ്റാറിക്ക" },
				{ LanguageId.mn, "Коста Рика" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "कॉस्टा रिका" },
				{ LanguageId.ms, "Costa rica" },
				{ LanguageId.mt, "Kosta Rika" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကော့စတာရီကာ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Costa Rica" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोस्टारिका" },
				{ LanguageId.nl, "Costa Rica" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Costa Rica" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କୋଷ୍ଟାରିକା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੋਸਟਾਰੀਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Kostaryka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کوسټاریکا" },
				{ LanguageId.pt, "Costa Rica" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Costa Rica" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Коста-Рика" },
				{ LanguageId.rw, "Kosta Rika" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪوسٽا ريڪا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කොස්ට රිකා" },
				{ LanguageId.sk, "Kostarika" },
				{ LanguageId.sl, "Kostarika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Kosita Rika" },
				{ LanguageId.so, "Costa Rica" },
				{ LanguageId.sq, "Kosta Rika" },
				{ LanguageId.sr, "Костарика" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Costa Rica" },
				{ LanguageId.su, "Kosta Rika" },
				{ LanguageId.sv, "Costa Rica" },
				{ LanguageId.sw, "Kosta Rika" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கோஸ்ட்டா ரிக்கா" },
				{ LanguageId.te, "కోస్టా రికా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Коста-Рика" },
				{ LanguageId.th, "คอสตาริกา" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kosta Rika" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Kosta Rika" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Коста-Рика" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "كوستارىكا" },
				{ LanguageId.uk, "Коста-Ріка" },
				{ LanguageId.ur, "کوسٹا ریکا" },
				{ LanguageId.uz, "Kosta-Rika" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Costa Rica" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Khosta Rika" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "קאסטא ריקא" },
				{ LanguageId.yo, "Kosta Rika" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "哥斯达黎加" },
				{ LanguageId.zu, "I-Costa Rica" },
			}
		);
	}
}
