// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CR
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "506",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Costa Rica" },
				{ LanguageId.af, "Costa Rica" },
				{ LanguageId.agq, "Kòsɨ̀tà Lekà" },
				{ LanguageId.ak, "Kɔsta Rika" },
				{ LanguageId.am, "ኮስታሪካ" },
				{ LanguageId.ar, "كوستاريكا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "কোষ্টা ৰিকা" },
				{ LanguageId.asa, "Kothtarika" },
				{ LanguageId.ast, "Costa Rica" },
				{ LanguageId.az, "Kosta Rika" },
				{ LanguageId.ba, "Коста-Рика" },
				{ LanguageId.bas, "Kòstà Rikà" },
				{ LanguageId.be, "Коста-Рыка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hukostarika" },
				{ LanguageId.bg, "Коста Рика" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kɔsitarika" },
				{ LanguageId.bn, "কোস্টারিকা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Costa Rica" },
				{ LanguageId.brx, "कस्टा रिका" },
				{ LanguageId.bs, "Kostarika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Costa Rica" },
				{ LanguageId.ccp, "𑄇𑄮𑄥𑄳𑄑𑄢𑄨𑄇" },
				{ LanguageId.ce, "Коста-Рика" },
				{ LanguageId.ceb, "Costa Rica" },
				{ LanguageId.cgg, "Kositarika" },
				{ LanguageId.chr, "ᎪᏍᏓ ᎵᎧ" },
				{ LanguageId.ckb, "کۆستاریکا" },
				{ LanguageId.co, "Costa Rica" },
				{ LanguageId.cs, "Kostarika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Costa Rica" },
				{ LanguageId.dav, "Kostarika" },
				{ LanguageId.de, "Costa Rica" },
				{ LanguageId.dje, "Kosta rika" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Kosta Rika" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཀོས་ཊ་རི་ཀ" },
				{ LanguageId.ebu, "Kostarika" },
				{ LanguageId.ee, "Kosta Rika nutome" },
				{ LanguageId.el, "Κόστα Ρίκα" },
				{ LanguageId.en, "Costa Rica" },
				{ LanguageId.eo, "Kostariko" },
				{ LanguageId.es, "Costa Rica" },
				{ LanguageId.et, "Costa Rica" },
				{ LanguageId.eu, "Costa Rica" },
				{ LanguageId.ewo, "Kosta Ríka" },
				{ LanguageId.fa, "کاستاریکا" },
				{ LanguageId.ff, "Kosta Rikaa" },
				{ LanguageId.fi, "Costa Rica" },
				{ LanguageId.fil, "Costa Rica" },
				{ LanguageId.fo, "Kosta Rika" },
				{ LanguageId.fr, "Costa Rica" },
				{ LanguageId.fur, "Costa Rica" },
				{ LanguageId.fy, "Costa Rica" },
				{ LanguageId.ga, "Cósta Ríce" },
				{ LanguageId.gd, "Costa Rìcea" },
				{ LanguageId.gl, "Costa Rica" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Coschta Rica" },
				{ LanguageId.gu, "કોસ્ટા રિકા" },
				{ LanguageId.guz, "Kostarika" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Kwasta Rika" },
				{ LanguageId.haw, "Koka Rika" },
				{ LanguageId.he, "קוסטה ריקה" },
				{ LanguageId.hi, "कोस्टारिका" },
				{ LanguageId.hr, "Kostarika" },
				{ LanguageId.hsb, "Kosta Rika" },
				{ LanguageId.hu, "Costa Rica" },
				{ LanguageId.hy, "Կոստա Ռիկա" },
				{ LanguageId.ia, "Costa Rica" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kosta Rika" },
				{ LanguageId.ig, "Kosta Rika" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Kostaríka" },
				{ LanguageId.it, "Costa Rica" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コスタリカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Kostarika" },
				{ LanguageId.jv, "Kosta Rika" },
				{ LanguageId.ka, "კოსტა-რიკა" },
				{ LanguageId.kab, "Kusta Rika" },
				{ LanguageId.kam, "Kostarika" },
				{ LanguageId.kde, "Kostalika" },
				{ LanguageId.kea, "Kosta Rika" },
				{ LanguageId.khq, "Kosta rika" },
				{ LanguageId.ki, "Kostarika" },
				{ LanguageId.kk, "Коста-Рика" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Costa Rica" },
				{ LanguageId.km, "កូស្តារីកា" },
				{ LanguageId.kn, "ಕೊಸ್ಟಾ ರಿಕಾ" },
				{ LanguageId.ko, "코스타리카" },
				{ LanguageId.kok, "कोस्ता रिका" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "کوسٹا ریکا" },
				{ LanguageId.ksb, "Kostalika" },
				{ LanguageId.ksf, "kɔstaríka" },
				{ LanguageId.ksh, "Kostarika" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Коста-Рика" },
				{ LanguageId.la, "Costa Rica" },
				{ LanguageId.lag, "Kósita Rɨ́ɨka" },
				{ LanguageId.lb, "Costa Rica" },
				{ LanguageId.lg, "Kosita Rika" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Kositarika" },
				{ LanguageId.lo, "ໂຄສຕາ ຣິກາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kosta Rika" },
				{ LanguageId.luo, "Costa Rica" },
				{ LanguageId.luy, "Kostarika" },
				{ LanguageId.lv, "Kostarika" },
				{ LanguageId.mai, "कोस्टारिका" },
				{ LanguageId.mas, "Kostarika" },
				{ LanguageId.mer, "Kostarika" },
				{ LanguageId.mfe, "Costa Rica" },
				{ LanguageId.mg, "Kosta Rikà" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Koto Rīka" },
				{ LanguageId.mk, "Костарика" },
				{ LanguageId.ml, "കോസ്റ്ററിക്ക" },
				{ LanguageId.mn, "Коста-Рика" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "कोस्टा रिका" },
				{ LanguageId.ms, "Costa Rica" },
				{ LanguageId.mt, "il-Costa Rica" },
				{ LanguageId.mua, "kosta Rika" },
				{ LanguageId.my, "ကို့စ်တာရီကာ" },
				{ LanguageId.mzn, "کاستاریکا" },
				{ LanguageId.naq, "Costa Rica" },
				{ LanguageId.nb, "Costa Rica" },
				{ LanguageId.nd, "Khosta Rikha" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोष्टारिका" },
				{ LanguageId.nl, "Costa Rica" },
				{ LanguageId.nmg, "Kosta Ríka" },
				{ LanguageId.nn, "Costa Rica" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߐߛߑߕߊ߫ ߙߌߞߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Kothtirika" },
				{ LanguageId.nyn, "Kositarika" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Kostaa Rikaa" },
				{ LanguageId.or, "କୋଷ୍ଟା ରିକା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੋਸਟਾ ਰੀਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Kósta Ríka" },
				{ LanguageId.pl, "Kostaryka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کوستاریکا" },
				{ LanguageId.pt, "Costa Rica" },
				{ LanguageId.qu, "Costa Rica" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Costa Rica" },
				{ LanguageId.rn, "Kositarika" },
				{ LanguageId.ro, "Costa Rica" },
				{ LanguageId.rof, "Kostarika" },
				{ LanguageId.ru, "Коста-Рика" },
				{ LanguageId.rw, "Kosta Rika" },
				{ LanguageId.rwk, "Kostarika" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Kostarika" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Kositalika" },
				{ LanguageId.sd, "ڪوسٽا ريڪا" },
				{ LanguageId.se, "Costa Rica" },
				{ LanguageId.seh, "Costa Rica" },
				{ LanguageId.ses, "Kosta rika" },
				{ LanguageId.sg, "Kôsta Rîka" },
				{ LanguageId.shi, "ⴽⵓⵙⵜⴰ ⵔⵉⴽⴰ" },
				{ LanguageId.si, "කොස්ටරිකාව" },
				{ LanguageId.sk, "Kostarika" },
				{ LanguageId.sl, "Kostarika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Costa Rica" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Kostarika" },
				{ LanguageId.so, "Costa Rica" },
				{ LanguageId.sq, "Kosta-Rikë" },
				{ LanguageId.sr, "Костарика" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Costa Rica" },
				{ LanguageId.su, "Kosta Rika" },
				{ LanguageId.sv, "Costa Rica" },
				{ LanguageId.sw, "Kostarika" },
				{ LanguageId.syr, "ܟܘܣܬܐ ܪܝܟܐ" },
				{ LanguageId.ta, "கோஸ்டாரிகா" },
				{ LanguageId.te, "కోస్టా రికా" },
				{ LanguageId.teo, "Kostarika" },
				{ LanguageId.tg, "Коста-Рика" },
				{ LanguageId.th, "คอสตาริกา" },
				{ LanguageId.ti, "ኮስታ ሪካ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kosta-Rika" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Kosita Lika" },
				{ LanguageId.tr, "Kosta Rika" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Коста-Рика" },
				{ LanguageId.twq, "Kosta rika" },
				{ LanguageId.tzm, "Kusṭa Rika" },
				{ LanguageId.ug, "كوستارىكا" },
				{ LanguageId.uk, "Коста-Рика" },
				{ LanguageId.ur, "کوسٹا ریکا" },
				{ LanguageId.uz, "Kosta-Rika" },
				{ LanguageId.vai, "ꖏꔻꕚ ꔸꕪ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Costa Rica" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Kostarika" },
				{ LanguageId.wae, "Costa Rica" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Kosta Rika" },
				{ LanguageId.xh, "ECosta Rica" },
				{ LanguageId.xog, "Kosita Rika" },
				{ LanguageId.yav, "Kóstálíka" },
				{ LanguageId.yi, "קאסטאַ ריקאַ" },
				{ LanguageId.yo, "Kuusita Ríkà" },
				{ LanguageId.zgh, "ⴽⵓⵙⵜⴰ ⵔⵉⴽⴰ" },
				{ LanguageId.zh, "哥斯达黎加" },
				{ LanguageId.zu, "i-Costa Rica" },
			}
		);
	}
}
