// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CV
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "238",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Kap Verde" },
				{ LanguageId.af, "Kaap Verde" },
				{ LanguageId.agq, "Chwɨla ŋ̀ Kɛ̀b Vɛ̂ɛ" },
				{ LanguageId.ak, "Kepvɛdfo Islands" },
				{ LanguageId.am, "ኬፕቨርዴ" },
				{ LanguageId.ar, "الرأس الأخضر" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "কেপ ভার্দে" },
				{ LanguageId.asa, "Kepuvede" },
				{ LanguageId.ast, "Cabu Verde" },
				{ LanguageId.az, "Kabo-Verde" },
				{ LanguageId.ba, "Кабо-Верде" },
				{ LanguageId.bas, "Kabwɛ᷆r" },
				{ LanguageId.be, "Каба-Вердэ" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hukepuvede" },
				{ LanguageId.bg, "Кабо Верде" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Capivɛrdi" },
				{ LanguageId.bn, "কেপ ভার্দে" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Kab-Glas" },
				{ LanguageId.brx, "केप भेर्दे" },
				{ LanguageId.bs, "Zelenortska Ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Cap Verd" },
				{ LanguageId.ccp, "𑄇𑄬𑄛𑄴𑄞𑄢𑄴𑄘𑄬" },
				{ LanguageId.ce, "Кабо-Верде" },
				{ LanguageId.ceb, "Cape Verde" },
				{ LanguageId.cgg, "Ebizinga bya Kepuvade" },
				{ LanguageId.chr, "ᎢᎬᎾᏕᎾ ᎢᏤᏳᏍᏗ" },
				{ LanguageId.ckb, "کەیپڤەرد" },
				{ LanguageId.co, "Capu Verde" },
				{ LanguageId.cs, "Kapverdy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Cabo Verde" },
				{ LanguageId.dav, "Kepuvede" },
				{ LanguageId.de, "Cabo Verde" },
				{ LanguageId.dje, "Kapuver gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Kap Verde" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཀེཔ་བཱཌ" },
				{ LanguageId.ebu, "Kepuvede" },
				{ LanguageId.ee, "Kape Verde nutome" },
				{ LanguageId.el, "Πράσινο Ακρωτήριο" },
				{ LanguageId.en, "Cape Verde" },
				{ LanguageId.eo, "Kaboverdo" },
				{ LanguageId.es, "Cabo Verde" },
				{ LanguageId.et, "Roheneemesaared" },
				{ LanguageId.eu, "Cabo Verde" },
				{ LanguageId.ewo, "Minlán Mí Káb Vɛr" },
				{ LanguageId.fa, "کیپ‌ورد" },
				{ LanguageId.ff, "Duuɗe Kap Weer" },
				{ LanguageId.fi, "Kap Verde" },
				{ LanguageId.fil, "Cape Verde" },
				{ LanguageId.fo, "Grønhøvdaoyggjar" },
				{ LanguageId.fr, "Cap-Vert" },
				{ LanguageId.fur, "Cjâf vert" },
				{ LanguageId.fy, "Kaapverdië" },
				{ LanguageId.ga, "Poblacht Cabo Verde" },
				{ LanguageId.gd, "An Ceap Uaine" },
				{ LanguageId.gl, "Cabo Verde" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Kap Verde" },
				{ LanguageId.gu, "કૅપ વર્ડે" },
				{ LanguageId.guz, "Kepuvede" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Cape Verde" },
				{ LanguageId.haw, "Laeuliuli" },
				{ LanguageId.he, "כף ורדה" },
				{ LanguageId.hi, "केप वर्ड" },
				{ LanguageId.hr, "Zelenortska Republika" },
				{ LanguageId.hsb, "Kap Verde" },
				{ LanguageId.hu, "Zöld-foki Köztársaság" },
				{ LanguageId.hy, "Կաբո Վերդե" },
				{ LanguageId.ia, "Capo Verde" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Tanjung Verde" },
				{ LanguageId.ig, "Cape Verde" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Grænhöfðaeyjar" },
				{ LanguageId.it, "Capo Verde" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "カーボベルデ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Kepuvede" },
				{ LanguageId.jv, "Pongol Verdé" },
				{ LanguageId.ka, "კაბო-ვერდე" },
				{ LanguageId.kab, "Tigzirin n yixef azegzaw" },
				{ LanguageId.kam, "Kepuvede" },
				{ LanguageId.kde, "Kepuvede" },
				{ LanguageId.kea, "Kabu Verdi" },
				{ LanguageId.khq, "Kapuver gungey" },
				{ LanguageId.ki, "Kepuvede" },
				{ LanguageId.kk, "Кабо-Верде" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeyotab Cape Verde" },
				{ LanguageId.km, "កាប់វែរ" },
				{ LanguageId.kn, "ಕೇಪ್ ವರ್ಡೆ" },
				{ LanguageId.ko, "카보베르데" },
				{ LanguageId.kok, "काबो वेर्दे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "کیپ ؤرڑی" },
				{ LanguageId.ksb, "Kepuvede" },
				{ LanguageId.ksf, "kapvɛr" },
				{ LanguageId.ksh, "de kapvärdesche Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кабо-Верде" },
				{ LanguageId.la, "Promontorium Verde" },
				{ LanguageId.lag, "Kepuvéede" },
				{ LanguageId.lb, "Kap Verde" },
				{ LanguageId.lg, "Bizinga by’e Kepu Veredi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Kapevɛrɛ" },
				{ LanguageId.lo, "ເຄບ ເວີດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Žaliasis Kyšulys" },
				{ LanguageId.luo, "Cape Verde Islands" },
				{ LanguageId.luy, "Kepuvede" },
				{ LanguageId.lv, "Kaboverde" },
				{ LanguageId.mai, "कैप बर्डे" },
				{ LanguageId.mas, "Kepuvede" },
				{ LanguageId.mer, "Kepuvede" },
				{ LanguageId.mfe, "Kap-Ver" },
				{ LanguageId.mg, "Nosy Cap-Vert" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Kūrae Matomato" },
				{ LanguageId.mk, "Кабо Верде" },
				{ LanguageId.ml, "കേപ്പ് വേർഡ്" },
				{ LanguageId.mn, "Кабо-Верде" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "केप व्हर्डे" },
				{ LanguageId.ms, "Cape Verde" },
				{ LanguageId.mt, "Cape Verde" },
				{ LanguageId.mua, "kap ma laŋne" },
				{ LanguageId.my, "ကိတ်ဗာဒီ" },
				{ LanguageId.mzn, "کیپ ورد" },
				{ LanguageId.naq, "Cape Verde Islands" },
				{ LanguageId.nb, "Kapp Verde" },
				{ LanguageId.nd, "Cape Verde Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "केप भर्डे" },
				{ LanguageId.nl, "Kaapverdië" },
				{ LanguageId.nmg, "Maŋ́ má Kapvɛr" },
				{ LanguageId.nn, "Kapp Verde" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߜߙߋߞߎ߲߫-ߝߙߌߛߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Kɛp bedi ɣa̱ylɛn" },
				{ LanguageId.nyn, "Ebizinga bya Kepuvade" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Keeppi Vaardee" },
				{ LanguageId.or, "କେପ୍ ଭର୍ଦେ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੇਪ ਵਰਡੇ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Kép Vẹ́d" },
				{ LanguageId.pl, "Republika Zielonego Przylądka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کیپ ورد" },
				{ LanguageId.pt, "Cabo Verde" },
				{ LanguageId.qu, "Cabo Verde" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Cap Verd" },
				{ LanguageId.rn, "Ibirwa bya Kapuveri" },
				{ LanguageId.ro, "Capul Verde" },
				{ LanguageId.rof, "Kepuvede" },
				{ LanguageId.ru, "Кабо-Верде" },
				{ LanguageId.rw, "Cape Verde" },
				{ LanguageId.rwk, "Kepuvede" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Kepuvede" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Kepuvede" },
				{ LanguageId.sd, "ڪيپ وردي" },
				{ LanguageId.se, "Kap Verde" },
				{ LanguageId.seh, "Cabo Verde" },
				{ LanguageId.ses, "Kapuver gungey" },
				{ LanguageId.sg, "Azûâ tî Kâpo-Vêre" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⴱⴱⵉⵔⴷⵉ" },
				{ LanguageId.si, "කේප් වර්ඩ්" },
				{ LanguageId.sk, "Kapverdy" },
				{ LanguageId.sl, "Zelenortski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Cape Verde" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveCape Verde" },
				{ LanguageId.so, "Jasiiradda Kayb Faarde" },
				{ LanguageId.sq, "Kepi i Gjelbër" },
				{ LanguageId.sr, "Зеленортска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Cape Verde" },
				{ LanguageId.su, "Tanjung Verde" },
				{ LanguageId.sv, "Kap Verde" },
				{ LanguageId.sw, "Cape Verde" },
				{ LanguageId.syr, "ܟܐܦ ܒܝܪܕܝ (ܪܝܫܐ ܝܘܪܩܐ)" },
				{ LanguageId.ta, "கேப் வெர்டே" },
				{ LanguageId.te, "కేప్ వెర్డె" },
				{ LanguageId.teo, "Kepuvede" },
				{ LanguageId.tg, "Кабо-Верде" },
				{ LanguageId.th, "เคปเวิร์ด" },
				{ LanguageId.ti, "ኬፕ ቨርደ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kabo-Werde" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Muiʻi Vēte" },
				{ LanguageId.tr, "Cabo Verde" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Кабо-Верде" },
				{ LanguageId.twq, "Kapuver gungey" },
				{ LanguageId.tzm, "Tigzirin n Iɣf Uzegzaw" },
				{ LanguageId.ug, "يېشىل تۇمشۇق" },
				{ LanguageId.uk, "Кабо-Верде" },
				{ LanguageId.ur, "کیپ ورڈی" },
				{ LanguageId.uz, "Kabo-Verde" },
				{ LanguageId.vai, "ꔞꔪ ꗲꔵ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cape Verde" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Kepuvede" },
				{ LanguageId.wae, "Kap Verde" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Kabo Werde" },
				{ LanguageId.xh, "ECape Verde" },
				{ LanguageId.xog, "Ebizinga bya Kepu Veredi" },
				{ LanguageId.yav, "Kápfɛl" },
				{ LanguageId.yi, "קאַפּווערדישע אינזלען" },
				{ LanguageId.yo, "Etíokun Kápé féndè" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⴱⴱⵉⵔⴷⵉ" },
				{ LanguageId.zh, "佛得角" },
				{ LanguageId.zu, "i-Cape Verde" },
			}
		);
	}
}
