using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CV
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "238",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Kap Verde" },
				{ LanguageId.af, "Kaap Verde" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኬፕ ቬሪዴ" },
				{ LanguageId.ar, "الرأس الأخضر" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Cape Verde" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Каба-Вэрдэ" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Кабо Верде" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "কেপ ভার্দে" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Cape Verde" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Cap Verd" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Cape Verde" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Capu Verde" },
				{ LanguageId.cs, "Kapverdy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Cape Verde" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Kap Verde" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Πράσινο Ακρωτήριο" },
				{ LanguageId.en, "Cape Verde" },
				{ LanguageId.eo, "Kabo-Verdo" },
				{ LanguageId.es, "Cabo Verde" },
				{ LanguageId.et, "Roheneemesaared" },
				{ LanguageId.eu, "Cabo Verde" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "کیپ ورد" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Kap Verde" },
				{ LanguageId.fil, "Cape Verde" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Cap-Vert" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Kaapverdje" },
				{ LanguageId.ga, "Rinn Verde" },
				{ LanguageId.gd, "Cape Verdi" },
				{ LanguageId.gl, "Cabo Verde" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "કેપ વર્ડે" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Cape Verde" },
				{ LanguageId.haw, "Laeuliuli" },
				{ LanguageId.he, "קייפ ורדה" },
				{ LanguageId.hi, "केप वर्ड" },
				{ LanguageId.hr, "Kabo Verde" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "zöld-fok" },
				{ LanguageId.hy, "Կաբո Վերդե" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Tanjung Verde" },
				{ LanguageId.ig, "Cape Verde" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Grænhöfðaeyjar" },
				{ LanguageId.it, "capo Verde" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "カーボベルデ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Tanjung Verde" },
				{ LanguageId.ka, "კაბო ვერდე" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Кабо-Верде" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Cape Verde" },
				{ LanguageId.kn, "ಕೇಪ್ ವರ್ಡೆ" },
				{ LanguageId.ko, "카보베르데" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кабо-Верде" },
				{ LanguageId.la, "Promontorium Verde" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Cap Vert" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Cape Verde" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Žaliasis Kyšulys" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Kaboverde" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Cape Verde" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Cape Verde" },
				{ LanguageId.mk, "Кејп Верде" },
				{ LanguageId.ml, "കേപ് വെർദെ" },
				{ LanguageId.mn, "Кабо Верде" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "केप वर्दे" },
				{ LanguageId.ms, "Cape Verde" },
				{ LanguageId.mt, "Kap Verde" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကိပ်ဗာဒီ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Kapp Verde" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "केप भर्डे" },
				{ LanguageId.nl, "Kaapverdië" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କେପ୍ ଭର୍ଡେ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੇਪ ਵਰਡੇ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Zielonego Przylądka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کیپ ورد" },
				{ LanguageId.pt, "cabo Verde" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "capul Verde" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Кабо-Верде" },
				{ LanguageId.rw, "Cape Verde" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪيپ ورڊي" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කේප් වර්ඩ්" },
				{ LanguageId.sk, "Kapverdy" },
				{ LanguageId.sl, "Zelenortski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Kepu Vhedhi" },
				{ LanguageId.so, "Cape Verde" },
				{ LanguageId.sq, "Kepi ​​Verde" },
				{ LanguageId.sr, "Цапе Верде" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Cape Verde" },
				{ LanguageId.su, "Tanjung Verde" },
				{ LanguageId.sv, "Cap Verde" },
				{ LanguageId.sw, "Cape Verde" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கேப் வெர்டே" },
				{ LanguageId.te, "కేప్ వర్దె" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Кабо-Верде" },
				{ LanguageId.th, "เคปเวิร์ด" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Cape Verde" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Yeşil Burun Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Кейп Верде" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Cape Verde" },
				{ LanguageId.uk, "Кабо-Верде" },
				{ LanguageId.ur, "کیپ وردے" },
				{ LanguageId.uz, "Kabo-Verde" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cabo Verde" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Kheyip Verde" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "קאַפּע ווערד" },
				{ LanguageId.yo, "Cape Verde" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "佛得角" },
				{ LanguageId.zu, "Cape Verde" },
			}
		);
	}
}
