using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class CZ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "420",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Tjekkiet" },
				{ LanguageId.af, "Tsjeggiese Republiek" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቼክ ሪፐብሊክ" },
				{ LanguageId.ar, "الجمهورية التشيكية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Çexiya Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Чэская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Чехия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "চেক প্রজাতন্ত্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Češka Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Txeca" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Czech Republic" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Repubblica Ceca" },
				{ LanguageId.cs, "Česká republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Tsiec" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Tschechien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Τσεχική Δημοκρατία" },
				{ LanguageId.en, "Czech Republic" },
				{ LanguageId.eo, "Ĉeĥio" },
				{ LanguageId.es, "República Checa" },
				{ LanguageId.et, "Tšehhi Vabariik" },
				{ LanguageId.eu, "Txekiar Errepublika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری چک" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Tšekin tasavalta" },
				{ LanguageId.fil, "Czech Republic" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République tchèque" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Tsjechje" },
				{ LanguageId.ga, "Poblacht na Seice" },
				{ LanguageId.gd, "Poblachd nan Seic" },
				{ LanguageId.gl, "República Checa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ચેક રિપબ્લિક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Czech" },
				{ LanguageId.haw, "Czech Republic" },
				{ LanguageId.he, "הרפובליקה הצ'כית" },
				{ LanguageId.hi, "चेक रिपब्लिक" },
				{ LanguageId.hr, "Češka Republika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Cseh Köztársaság" },
				{ LanguageId.hy, "Չեխիայի Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Ceko" },
				{ LanguageId.ig, "Czech Republic" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Tékkland" },
				{ LanguageId.it, "Repubblica Ceca" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "チェコ共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Ceko" },
				{ LanguageId.ka, "ჩეხეთის რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Чех Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋ​ឆែក" },
				{ LanguageId.kn, "ಜೆಕ್ ರಿಪಬ್ಲಿಕ್" },
				{ LanguageId.ko, "체코 공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Чех Республикасы" },
				{ LanguageId.la, "Res publica Bohemica" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Tschechesch Republik" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາ​ທາ​ລະ​ນະ​ລັດ​ເຊັກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Čekijos Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Čehu Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Tcheky" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Czech Republic" },
				{ LanguageId.mk, "Чешка република" },
				{ LanguageId.ml, "ചെക്ക് റിപ്പബ്ലിക്" },
				{ LanguageId.mn, "Чех" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "झेक प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Czech" },
				{ LanguageId.mt, "Repubblika Ċeka" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ချက်သမ္မတနိုင်ငံ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Tsjekkisk Republikk" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "चेक गणतन्त्र" },
				{ LanguageId.nl, "Tsjechische Republiek" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଚେକ୍ ରିପବ୍ଲିକ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਚੇਕ ਗਣਤੰਤਰ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Republika Czeska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "چک جمهوريت" },
				{ LanguageId.pt, "República Checa" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Cehă" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Чешская Республика" },
				{ LanguageId.rw, "Repubulika ya Ceki" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "چيڪ ريپبلڪ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "චෙක් ජනරජය" },
				{ LanguageId.sk, "Česká republika" },
				{ LanguageId.sl, "Češka" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Czech Republic" },
				{ LanguageId.so, "Czech Republic" },
				{ LanguageId.sq, "Republika Çeke" },
				{ LanguageId.sr, "Чешка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Riphaboliki ea Czech" },
				{ LanguageId.su, "Républik Czech" },
				{ LanguageId.sv, "Tjeckien" },
				{ LanguageId.sw, "Jamhuri ya Czech" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "செ குடியரசு" },
				{ LanguageId.te, "చెక్ రిపబ్లిక్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷумҳуриӣ Чех" },
				{ LanguageId.th, "สาธารณรัฐเช็ก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Çehiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Çek Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Чех Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "چېخ" },
				{ LanguageId.uk, "Чеська Республіка" },
				{ LanguageId.ur, "جمہوریہ چیک" },
				{ LanguageId.uz, "Chex Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Séc" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Umphakathi waseCzech" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "טשעכיי" },
				{ LanguageId.yo, "Apapọ Ilẹ Ṣẹẹki" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "捷克共和国" },
				{ LanguageId.zu, "I-Czech Republic" },
			}
		);
	}
}
