// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class CZ
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "420",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Tjekkiet" },
				{ LanguageId.af, "Tsjeggië" },
				{ LanguageId.agq, "Chɛ̂ Lèkpubèlè" },
				{ LanguageId.ak, "Kyɛk" },
				{ LanguageId.am, "ቼቺያ" },
				{ LanguageId.ar, "التشيك" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চিজেচিয়া" },
				{ LanguageId.asa, "Jamhuri ya Cheki" },
				{ LanguageId.ast, "Chequia" },
				{ LanguageId.az, "Çexiya" },
				{ LanguageId.ba, "Чехия" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Чэхія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ijamhuri ya Cheki" },
				{ LanguageId.bg, "Чехия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Ceki republiki" },
				{ LanguageId.bn, "চেকিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Tchekia" },
				{ LanguageId.brx, "चेखिया" },
				{ LanguageId.bs, "Češka" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Txèquia" },
				{ LanguageId.ccp, "𑄌𑄬𑄌𑄨𑄠" },
				{ LanguageId.ce, "Чехи" },
				{ LanguageId.ceb, "Czechia" },
				{ LanguageId.cgg, "Ripaaburika ya Zeeki" },
				{ LanguageId.chr, "ᏤᎩᎠ" },
				{ LanguageId.ckb, "کۆماری چیک" },
				{ LanguageId.co, "Repubblica Ceca" },
				{ LanguageId.cs, "Česko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Tsiecia" },
				{ LanguageId.dav, "Jamhuri ya Cheki" },
				{ LanguageId.de, "Tschechien" },
				{ LanguageId.dje, "Cek labo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Česka republika" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཅེཀ་ རི་པབ་ལིཀ" },
				{ LanguageId.ebu, "Jamhuri ya Cheki" },
				{ LanguageId.ee, "Tsɛk repɔblik nutome" },
				{ LanguageId.el, "Τσεχία" },
				{ LanguageId.en, "Czechia" },
				{ LanguageId.eo, "Ĉeĥujo" },
				{ LanguageId.es, "Chequia" },
				{ LanguageId.et, "Tšehhi" },
				{ LanguageId.eu, "Txekia" },
				{ LanguageId.ewo, "Ǹnam Tsɛ́g" },
				{ LanguageId.fa, "چک" },
				{ LanguageId.ff, "Ndenndaandi Cek" },
				{ LanguageId.fi, "Tšekki" },
				{ LanguageId.fil, "Czechia" },
				{ LanguageId.fo, "Kekkia" },
				{ LanguageId.fr, "Tchéquie" },
				{ LanguageId.fur, "Republiche ceche" },
				{ LanguageId.fy, "Tsjechje" },
				{ LanguageId.ga, "an tSeicia" },
				{ LanguageId.gd, "An t-Seic" },
				{ LanguageId.gl, "Chequia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Tschechischi Republik" },
				{ LanguageId.gu, "ચેકીયા" },
				{ LanguageId.guz, "Jamhuri ya Cheki" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Czechia" },
				{ LanguageId.haw, "Czech Republic" },
				{ LanguageId.he, "צ׳כיה" },
				{ LanguageId.hi, "चेकिया" },
				{ LanguageId.hr, "Češka" },
				{ LanguageId.hsb, "Čěska republika" },
				{ LanguageId.hu, "Csehország" },
				{ LanguageId.hy, "Չեխիա" },
				{ LanguageId.ia, "Chechia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Ceko" },
				{ LanguageId.ig, "Czechia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Tékkland" },
				{ LanguageId.it, "Cechia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "チェコ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Jamhuri ya Cheki" },
				{ LanguageId.jv, "Céko" },
				{ LanguageId.ka, "ჩეხეთი" },
				{ LanguageId.kab, "Čček" },
				{ LanguageId.kam, "Jamhuri ya Cheki" },
				{ LanguageId.kde, "Jamuhuli ya Chechi" },
				{ LanguageId.kea, "Txékia" },
				{ LanguageId.khq, "Cek labo" },
				{ LanguageId.ki, "Jamhuri ya Cheki" },
				{ LanguageId.kk, "Чехия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Czech Republic" },
				{ LanguageId.km, "ឆែក" },
				{ LanguageId.kn, "ಝೆಕಿಯಾ" },
				{ LanguageId.ko, "체코" },
				{ LanguageId.kok, "चेकिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "چیکیا" },
				{ LanguageId.ksb, "Jamhuli ya Cheki" },
				{ LanguageId.ksf, "cɛ́k" },
				{ LanguageId.ksh, "de Tschäschei" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Чехия" },
				{ LanguageId.la, "Res publica Bohemica" },
				{ LanguageId.lag, "Jamuhúuri ya Chéeki" },
				{ LanguageId.lb, "Tschechien" },
				{ LanguageId.lg, "Lipubulika ya Ceeka" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Shekia" },
				{ LanguageId.lo, "ເຊັກເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Čekija" },
				{ LanguageId.luo, "Czech Republic" },
				{ LanguageId.luy, "Jamhuri ya Cheki" },
				{ LanguageId.lv, "Čehija" },
				{ LanguageId.mai, "चेकिया" },
				{ LanguageId.mas, "Jamhuri ya Cheki" },
				{ LanguageId.mer, "Nthĩ ya Cheki" },
				{ LanguageId.mfe, "Repiblik Chek" },
				{ LanguageId.mg, "Repoblikan’i Tseky" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Tiekia" },
				{ LanguageId.mk, "Чешка" },
				{ LanguageId.ml, "ചെക്കിയ" },
				{ LanguageId.mn, "Чех" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "झेकिया" },
				{ LanguageId.ms, "Czechia" },
				{ LanguageId.mt, "ir-Repubblika Ċeka" },
				{ LanguageId.mua, "Sǝr Syek" },
				{ LanguageId.my, "ချက်ကီယား" },
				{ LanguageId.mzn, "چک جمهوری" },
				{ LanguageId.naq, "Czech Republiki" },
				{ LanguageId.nb, "Tsjekkia" },
				{ LanguageId.nd, "Czech Republic" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "चेकिया" },
				{ LanguageId.nl, "Tsjechië" },
				{ LanguageId.nmg, "Nlambɔ́ bó tschɛk" },
				{ LanguageId.nn, "Tsjekkia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߗߍߞ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ripaaburika ya Zeeki" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Cheechiya" },
				{ LanguageId.or, "ଚେଚିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਚੈਕੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Chẹ́kia" },
				{ LanguageId.pl, "Czechy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "چکیا" },
				{ LanguageId.pt, "Tchéquia" },
				{ LanguageId.qu, "Chequia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Tschechia" },
				{ LanguageId.rn, "Repubulika ya Ceke" },
				{ LanguageId.ro, "Cehia" },
				{ LanguageId.rof, "Jamhuri ya Cheki" },
				{ LanguageId.ru, "Чехия" },
				{ LanguageId.rw, "Repubulika ya Ceki" },
				{ LanguageId.rwk, "Jamhuri ya Cheki" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Jamhuri ya Cheki" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Jamuhuli ya Sheki" },
				{ LanguageId.sd, "چيڪيا" },
				{ LanguageId.se, "Čeahkka" },
				{ LanguageId.seh, "República Tcheca" },
				{ LanguageId.ses, "Cek labo" },
				{ LanguageId.sg, "Ködörösêse tî Tyêki" },
				{ LanguageId.shi, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵜⵛⵉⴽⵉⵜ" },
				{ LanguageId.si, "චෙචියාව" },
				{ LanguageId.sk, "Česko" },
				{ LanguageId.sl, "Češka" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Tšekki" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Czech Republic" },
				{ LanguageId.so, "Jekiya" },
				{ LanguageId.sq, "Çeki" },
				{ LanguageId.sr, "Чешка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Riphaboliki ea Czech" },
				{ LanguageId.su, "Républik Czech" },
				{ LanguageId.sv, "Tjeckien" },
				{ LanguageId.sw, "Chechia" },
				{ LanguageId.syr, "ܬܫܝܟܝܐ" },
				{ LanguageId.ta, "செசியா" },
				{ LanguageId.te, "చెకియా" },
				{ LanguageId.teo, "Jamhuri ya Cheki" },
				{ LanguageId.tg, "Ҷумҳурии Чех" },
				{ LanguageId.th, "เช็ก" },
				{ LanguageId.ti, "ቸክያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Çehiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sēkia" },
				{ LanguageId.tr, "Çekya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Чехия Республикасы" },
				{ LanguageId.twq, "Cek labo" },
				{ LanguageId.tzm, "Tagduda n Čik" },
				{ LanguageId.ug, "چېخ جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Чехія" },
				{ LanguageId.ur, "چیکیا" },
				{ LanguageId.uz, "Chexiya" },
				{ LanguageId.vai, "ꗿꕃ ꕸꖃꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Séc" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Jamhuri ya Cheki" },
				{ LanguageId.wae, "Tšečie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Réewum Cek" },
				{ LanguageId.xh, "ECzechia" },
				{ LanguageId.xog, "Lipabulika ya Ceeka" },
				{ LanguageId.yav, "kitɔŋ kí cɛ́k" },
				{ LanguageId.yi, "טשעכיי" },
				{ LanguageId.yo, "Ṣẹ́ẹ́kì" },
				{ LanguageId.zgh, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵜⵛⵉⴽⵉⵜ" },
				{ LanguageId.zh, "捷克" },
				{ LanguageId.zu, "i-Czechia" },
			}
		);
	}
}
