using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class DO
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Dominikanske republik" },
				{ LanguageId.af, "Dominikaanse Republiek" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዶሚኒካን ሪፑብሊክ" },
				{ LanguageId.ar, "جمهورية الدومينيكان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Dominik respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Дамініканская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Доминиканска република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ডোমিনিকান প্রজাতন্ত্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Dominikanska republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Dominicana" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Dominican Republic" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Republica Dumenicana" },
				{ LanguageId.cs, "Dominikánská republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Dominica" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Dominikanische Republik" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Δομινικανή Δημοκρατία" },
				{ LanguageId.en, "Dominican Republic" },
				{ LanguageId.eo, "Dominika Respubliko" },
				{ LanguageId.es, "República Dominicana" },
				{ LanguageId.et, "Dominikaani Vabariik" },
				{ LanguageId.eu, "Dominikar Errepublika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری دومینیکن" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Dominikaaninen tasavalta" },
				{ LanguageId.fil, "Dominican Republic" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République dominicaine" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Dominikaanske Republyk" },
				{ LanguageId.ga, "An Phoblacht Dhoiminiceach" },
				{ LanguageId.gd, "Poblachd Dominica" },
				{ LanguageId.gl, "República Dominicana" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ડોમિનિકન રિપબ્લિક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Dominican" },
				{ LanguageId.haw, "Lepubalika Dominika" },
				{ LanguageId.he, "הרפובליקה הדומיניקנית" },
				{ LanguageId.hi, "डोमिनिकन गणराज्य" },
				{ LanguageId.hr, "Dominikanska Republika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Dominikai Köztársaság" },
				{ LanguageId.hy, "Դոմինիկյան Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Dominika" },
				{ LanguageId.ig, "Dominican Republic" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Dóminíska lýðveldið" },
				{ LanguageId.it, "Repubblica Dominicana" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ドミニカ共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Dominika" },
				{ LanguageId.ka, "დომინიკის რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Доминикан республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋ​ដូ​មីនី​កែន" },
				{ LanguageId.kn, "ಡೊಮಿನಿಕನ್ ರಿಪಬ್ಲಿಕ್" },
				{ LanguageId.ko, "도미니카 공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Доминика республикасы" },
				{ LanguageId.la, "Respublica Dominicana" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Dominikanesch Republik" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາທາລະນະລັດໂດມິນິກັນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Dominikos Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Dominikānas republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Dominikanina" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Dominican Republic" },
				{ LanguageId.mk, "Доминиканска Република" },
				{ LanguageId.ml, "ഡൊമിനിക്കന് റിപ്പബ്ലിക്ക്" },
				{ LanguageId.mn, "Доминиканы Бүгд Найрамдах Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "डोमिनिकन रिपब्लीक" },
				{ LanguageId.ms, "Republik Dominican" },
				{ LanguageId.mt, "Repubblika Dominikana" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဒိုမီနီကန်သမ္မတနိုင်ငံ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "den dominikanske republikk" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "डोमिनिकन गणतन्त्र" },
				{ LanguageId.nl, "Dominicaanse Republiek" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଡୋମିନିକାନ୍ ରିପବ୍ଲିକ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਡੋਮਿਨਿੱਕ ਰਿਪਬਲਿਕ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Republika Dominikany" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "دومینیکا جمهوریت" },
				{ LanguageId.pt, "República Dominicana" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Dominicană" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Доминиканская Республика" },
				{ LanguageId.rw, "Repubulika ya Dominikani" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڊومينيڪن جمهوريه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ඩොමිනිකානු ජනරජය" },
				{ LanguageId.sk, "Dominikánska republika" },
				{ LanguageId.sl, "Dominikanska republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Ripabhuriki Dhominika" },
				{ LanguageId.so, "Jamhuuriyadda Dominikan" },
				{ LanguageId.sq, "Republika Domenikane" },
				{ LanguageId.sr, "Доминиканска република" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "dominican republic" },
				{ LanguageId.su, "Républik Dominika" },
				{ LanguageId.sv, "Dominikanska republiken" },
				{ LanguageId.sw, "Jamhuri ya Dominika" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "டொமினிக்கன் குடியரசு" },
				{ LanguageId.te, "డొమినికన్ రిపబ్లిక్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷумҳурии Доминикан" },
				{ LanguageId.th, "สาธารณรัฐโดมินิกัน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Dominikan Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Dominik Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Доминикан Җөмһүрияте" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "دومىنىكا جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Домініканська республіка" },
				{ LanguageId.ur, "ڈومینیکن ریپبلک" },
				{ LanguageId.uz, "Dominika Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Dominica" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iriphabliki yaseDominikha" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "דאָמיניקאַן רעפובליק" },
				{ LanguageId.yo, "orilẹ-ede ara dominika" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "多明尼加共和国" },
				{ LanguageId.zu, "i-Dominican Republic" },
			}
		);
	}
}
