// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class DO
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Den Dominikanske Republik" },
				{ LanguageId.af, "Dominikaanse Republiek" },
				{ LanguageId.agq, "Dòmenekà Lèkpubèlè" },
				{ LanguageId.ak, "Dɔmeneka Man" },
				{ LanguageId.am, "ዶመኒካን ሪፑብሊክ" },
				{ LanguageId.ar, "جمهورية الدومينيكان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ড’মিনিকান ৰিপাব্লিক" },
				{ LanguageId.asa, "Jamhuri ya Dominika" },
				{ LanguageId.ast, "República Dominicana" },
				{ LanguageId.az, "Dominikan Respublikası" },
				{ LanguageId.ba, "Доминикан Республикаһы" },
				{ LanguageId.bas, "Dòmnikà" },
				{ LanguageId.be, "Дамініканская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ijamhuri ya Hudominika" },
				{ LanguageId.bg, "Доминиканска република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Dɔmimiki republiki" },
				{ LanguageId.bn, "ডোমেনিকান প্রজাতন্ত্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Republik Dominikan" },
				{ LanguageId.brx, "दमिनिकान सुबुंखुंथाय" },
				{ LanguageId.bs, "Dominikanska Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Dominicana" },
				{ LanguageId.ccp, "𑄓𑄮𑄟𑄨𑄚𑄨𑄇𑄚𑄴 𑄛𑄳𑄢𑄧𑄎𑄖𑄧𑄚𑄴𑄖𑄳𑄢𑄧" },
				{ LanguageId.ce, "Доминикан Республика" },
				{ LanguageId.ceb, "Dominican Republic" },
				{ LanguageId.cgg, "Ripaaburika ya Dominica" },
				{ LanguageId.chr, "ᏙᎻᏂᎧᏂ ᏍᎦᏚᎩ" },
				{ LanguageId.ckb, "کۆماری دۆمینیکا" },
				{ LanguageId.co, "Republica Dumenicana" },
				{ LanguageId.cs, "Dominikánská republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Dominica" },
				{ LanguageId.dav, "Jamhuri ya Dominika" },
				{ LanguageId.de, "Dominikanische Republik" },
				{ LanguageId.dje, "Doominiki laboo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Dominikańska republika" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཌོ་མི་ནི་ཀཱན་ རི་པབ་ལིཀ" },
				{ LanguageId.ebu, "Jamhuri ya Dominika" },
				{ LanguageId.ee, "Dominika repɔblik nutome" },
				{ LanguageId.el, "Δομινικανή Δημοκρατία" },
				{ LanguageId.en, "Dominican Republic" },
				{ LanguageId.eo, "Dominika Respubliko" },
				{ LanguageId.es, "República Dominicana" },
				{ LanguageId.et, "Dominikaani Vabariik" },
				{ LanguageId.eu, "Dominikar Errepublika" },
				{ LanguageId.ewo, "République dominicaine" },
				{ LanguageId.fa, "جمهوری دومینیکن" },
				{ LanguageId.ff, "Ndenndanndi Dominika" },
				{ LanguageId.fi, "Dominikaaninen tasavalta" },
				{ LanguageId.fil, "Dominican Republic" },
				{ LanguageId.fo, "Dominikalýðveldið" },
				{ LanguageId.fr, "République dominicaine" },
				{ LanguageId.fur, "Republiche dominicane" },
				{ LanguageId.fy, "Dominikaanske Republyk" },
				{ LanguageId.ga, "an Phoblacht Dhoiminiceach" },
				{ LanguageId.gd, "A’ Phoblachd Dhoiminiceach" },
				{ LanguageId.gl, "República Dominicana" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Tominikaanischi Republik" },
				{ LanguageId.gu, "ડોમિનિકન રિપબ્લિક" },
				{ LanguageId.guz, "Jamhuri ya Dominika" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Dominika" },
				{ LanguageId.haw, "Lepubalika Dominika" },
				{ LanguageId.he, "הרפובליקה הדומיניקנית" },
				{ LanguageId.hi, "डोमिनिकन गणराज्य" },
				{ LanguageId.hr, "Dominikanska Republika" },
				{ LanguageId.hsb, "Dominikanska republika" },
				{ LanguageId.hu, "Dominikai Köztársaság" },
				{ LanguageId.hy, "Դոմինիկյան Հանրապետություն" },
				{ LanguageId.ia, "Republica Dominican" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Dominika" },
				{ LanguageId.ig, "Dominican Republik" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Dóminíska lýðveldið" },
				{ LanguageId.it, "Repubblica Dominicana" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ドミニカ共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Jamhuri ya Dominika" },
				{ LanguageId.jv, "Républik Dominika" },
				{ LanguageId.ka, "დომინიკელთა რესპუბლიკა" },
				{ LanguageId.kab, "Tigduda Taduminikit" },
				{ LanguageId.kam, "Jamhuri ya Dominika" },
				{ LanguageId.kde, "Jamuhuli ya Dominika" },
				{ LanguageId.kea, "Repúblika Dominikana" },
				{ LanguageId.khq, "Doominiki laboo" },
				{ LanguageId.ki, "Jamhuri ya Dominika" },
				{ LanguageId.kk, "Доминикан Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Dominican Republic" },
				{ LanguageId.km, "សាធារណរដ្ឋ​ដូមីនីក" },
				{ LanguageId.kn, "ಡೊಮೆನಿಕನ್ ರಿಪಬ್ಲಿಕ್" },
				{ LanguageId.ko, "도미니카 공화국" },
				{ LanguageId.kok, "डोमिनिकन प्रजासत्तो" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ڈومِنِکَن جموٗرِیَت" },
				{ LanguageId.ksb, "Jamhuli ya Dominika" },
				{ LanguageId.ksf, "dɔminik rɛpublík" },
				{ LanguageId.ksh, "de Dommenekaanesche Reppublik" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Доминика Республикасы" },
				{ LanguageId.la, "Respublica Dominicana" },
				{ LanguageId.lag, "Jamuhúuri ya Dominɨka" },
				{ LanguageId.lb, "Dominikanesch Republik" },
				{ LanguageId.lg, "Lipubulika ya Dominika" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Repibiki ya Domínikɛ" },
				{ LanguageId.lo, "ສາທາລະນະລັດ ໂດມິນິກັນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Dominikos Respublika" },
				{ LanguageId.luo, "Dominican Republic" },
				{ LanguageId.luy, "Jamhuri ya Dominika" },
				{ LanguageId.lv, "Dominikāna" },
				{ LanguageId.mai, "डोमिनिकन रिपब्लिक" },
				{ LanguageId.mas, "Jamhuri ya Dominika" },
				{ LanguageId.mer, "Nthĩ ya Dominika" },
				{ LanguageId.mfe, "Repiblik dominikin" },
				{ LanguageId.mg, "Repoblika Dominikanina" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Whenua Tūhake o Tominika" },
				{ LanguageId.mk, "Доминиканска Република" },
				{ LanguageId.ml, "ഡൊമിനിക്കൻ റിപ്പബ്ലിക്ക്" },
				{ LanguageId.mn, "Бүгд Найрамдах Доминикан Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "डोमिनिकन प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Dominica" },
				{ LanguageId.mt, "ir-Repubblika Dominicana" },
				{ LanguageId.mua, "Sǝr Dominik ma lii" },
				{ LanguageId.my, "ဒိုမီနီကန်" },
				{ LanguageId.mzn, "دومنیکن جمهوری" },
				{ LanguageId.naq, "Dominican Republic" },
				{ LanguageId.nb, "Den dominikanske republikk" },
				{ LanguageId.nd, "Dominican Republic" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "डोमिनिकन गणतन्त्र" },
				{ LanguageId.nl, "Dominicaanse Republiek" },
				{ LanguageId.nmg, "Nlambɔ́ Dominíka" },
				{ LanguageId.nn, "Den dominikanske republikken" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߘߏߡߣߌߞ ߞߊ߲ߓߍ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ripaaburika ya Dominica" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Dominikaa Rippaabilik" },
				{ LanguageId.or, "ଡୋମିନିକାନ୍‌ ସାଧାରଣତନ୍ତ୍ର" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਡੋਮੀਨਿਕਾਈ ਗਣਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Dọmíníka Ripọ́blik" },
				{ LanguageId.pl, "Dominikana" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "جمهوريه ډومينيکن" },
				{ LanguageId.pt, "República Dominicana" },
				{ LanguageId.qu, "República Dominicana" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Republica Dominicana" },
				{ LanguageId.rn, "Repubulika ya Dominika" },
				{ LanguageId.ro, "Republica Dominicană" },
				{ LanguageId.rof, "Jamhuri ya Dominika" },
				{ LanguageId.ru, "Доминиканская Республика" },
				{ LanguageId.rw, "Repubulika ya Dominikani" },
				{ LanguageId.rwk, "Jamhuri ya Dominika" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Jamhuri ya Dominika" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Jamuhuli ya Dominika" },
				{ LanguageId.sd, "ڊومينيڪن جمهوريه" },
				{ LanguageId.se, "Dominikána dásseváldi" },
				{ LanguageId.seh, "República Dominicana" },
				{ LanguageId.ses, "Doominiki laboo" },
				{ LanguageId.sg, "Ködörösêse tî Dominîka" },
				{ LanguageId.shi, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵓⵎⵉⵏⵉⴽⵜ" },
				{ LanguageId.si, "ඩොමිනිකා ජනරජය" },
				{ LanguageId.sk, "Dominikánska republika" },
				{ LanguageId.sl, "Dominikanska republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Dominikaanisâš täsiväldi" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Dominican Republic" },
				{ LanguageId.so, "Jamhuuriyaddda Dominika" },
				{ LanguageId.sq, "Republika Dominikane" },
				{ LanguageId.sr, "Доминиканска Република" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "dominican republic" },
				{ LanguageId.su, "Républik Dominika" },
				{ LanguageId.sv, "Dominikanska republiken" },
				{ LanguageId.sw, "Jamhuri ya Dominika" },
				{ LanguageId.syr, "ܩܘܛܢܝܘܬܐ ܕܘܡܝܢܝܩܐܢܝܬܐ" },
				{ LanguageId.ta, "டொமினிகன் குடியரசு" },
				{ LanguageId.te, "డొమినికన్ రిపబ్లిక్" },
				{ LanguageId.teo, "Jamhuri ya Dominika" },
				{ LanguageId.tg, "Ҷумҳурии Доминикан" },
				{ LanguageId.th, "สาธารณรัฐโดมินิกัน" },
				{ LanguageId.ti, "ዶሚኒካዊት ሪፓብሊክ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Dominikan Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Lepupelika Tominika" },
				{ LanguageId.tr, "Dominik Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Доминикана Республикасы" },
				{ LanguageId.twq, "Doominiki laboo" },
				{ LanguageId.tzm, "Tagduda n Ḍuminikan" },
				{ LanguageId.ug, "دومىنىكا جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Домініканська Республіка" },
				{ LanguageId.ur, "جمہوریہ ڈومينيکن" },
				{ LanguageId.uz, "Dominikan Respublikasi" },
				{ LanguageId.vai, "ꖁꕆꕇꕪꘋ ꕸꕱꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Dominica" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Jamhuri ya Dominika" },
				{ LanguageId.wae, "Dominikaniši Rebublik" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Repiblik Dominiken" },
				{ LanguageId.xh, "EDominican Republic" },
				{ LanguageId.xog, "Lipabulika ya Dominika" },
				{ LanguageId.yav, "kitɔŋ kí tumunikɛ́ŋ" },
				{ LanguageId.yi, "דאמיניקאַנישע רעפּובליק" },
				{ LanguageId.yo, "Dòmíníkánì" },
				{ LanguageId.zgh, "ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵓⵎⵉⵏⵉⴽⵜ" },
				{ LanguageId.zh, "多米尼加共和国" },
				{ LanguageId.zu, "i-Dominican Republic" },
			}
		);
	}
}
