using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class EH
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "212",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Vestsahara" },
				{ LanguageId.af, "Wes-Sahara" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ምዕራባዊ ሳሃራ" },
				{ LanguageId.ar, "الصحراء الغربية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Qərbi Sahara" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Заходняя Сахара" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "западна Сахара" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পশ্চিম সাহারা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sahara ar C'hornôg" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Zapadna Sahara" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sàhara Occidental" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Kasadpang Sahara" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Sahara Occidentale" },
				{ LanguageId.cs, "západní Sahara" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gorllewin y Sahara" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Westsahara" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Δυτική Σαχάρα" },
				{ LanguageId.en, "Western Sahara" },
				{ LanguageId.eo, "Okcidenta Saharo" },
				{ LanguageId.es, "Sahara Occidental" },
				{ LanguageId.et, "Lääne-Sahara" },
				{ LanguageId.eu, "Mendebaldeko Sahara" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "صحرای غربی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Länsi-Sahara" },
				{ LanguageId.fil, "Kanlurang Sahara" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Sahara occidental" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Westlike Sahara" },
				{ LanguageId.ga, "Sahára Thiar" },
				{ LanguageId.gd, "Sahara an Iar" },
				{ LanguageId.gl, "Sahara Occidental" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "પશ્ચિમી સહારા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Yammacin Sahara" },
				{ LanguageId.haw, "Sahara Komohana" },
				{ LanguageId.he, "סהרה המערבית" },
				{ LanguageId.hi, "पश्चिमी सहारा" },
				{ LanguageId.hr, "Zapadna Sahara" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "nyugat-Szahara" },
				{ LanguageId.hy, "Արևմտյան Սահարա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sahara Barat" },
				{ LanguageId.ig, "Western Sahara" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Vestur-Sahara" },
				{ LanguageId.it, "Sahara occidentale" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "西サハラ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sahara Barat" },
				{ LanguageId.ka, "დასავლეთ საჰარა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Батыс Сахара" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាហារ៉ាខាងលិច" },
				{ LanguageId.kn, "ಪಶ್ಚಿಮ ಸಹಾರಾ" },
				{ LanguageId.ko, "서부 사하라" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Батыш Сахара" },
				{ LanguageId.la, "Sahara Occidentalis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Westsahara" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊາຮາຣາຕາເວັນຕົກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Vakarų Sachara" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Rietumsahāra" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Sahara Andrefana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hahara uru" },
				{ LanguageId.mk, "Западна Сахара" },
				{ LanguageId.ml, "പടിഞ്ഞാറൻ സഹാറ" },
				{ LanguageId.mn, "Баруун Сахар" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पश्चिम सहारा" },
				{ LanguageId.ms, "Sahara Barat" },
				{ LanguageId.mt, "Saħara tal-Punent" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အနောက်ဆာဟာရ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Vestre Sahara" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पश्चिमी सहारा" },
				{ LanguageId.nl, "Westelijke Sahara" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ପଶ୍ଚିମ ସାହାରା |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪੱਛਮੀ ਸਹਾਰਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Sahara Zachodnia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "لویدیځ صحارا" },
				{ LanguageId.pt, "Saara Ocidental" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "sahara de Vest" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Западная Сахара" },
				{ LanguageId.rw, "Sahara y'Uburengerazuba" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "مغربي صحارا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "බටහිර සහරා" },
				{ LanguageId.sk, "Západná Sahara" },
				{ LanguageId.sl, "Zahodna Sahara" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Western Sahara" },
				{ LanguageId.so, "Saxaraha Galbeed" },
				{ LanguageId.sq, "Sahara Perëndimore" },
				{ LanguageId.sr, "западна Сахара" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sahara Bophirimela" },
				{ LanguageId.su, "Sahara Kulon" },
				{ LanguageId.sv, "Västra Sahara" },
				{ LanguageId.sw, "Sahara Magharibi" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "மேற்கு சாஹாரா" },
				{ LanguageId.te, "పశ్చిమ సహారా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Саҳрои Ғарбӣ" },
				{ LanguageId.th, "ซาฮาร่าตะวันตก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günbatar Sahara" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Batı Sahra" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көнбатыш Сахара" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "غەربىي سەھرايى كەبىر" },
				{ LanguageId.uk, "Західна Сахара" },
				{ LanguageId.ur, "مغربی صحارا" },
				{ LanguageId.uz, "G'arbiy Sahara" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Phía tây Sahara" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Intshona yeSahara" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מערב סאַהאַראַ" },
				{ LanguageId.yo, "Western Sahara" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "撒哈拉沙漠西部" },
				{ LanguageId.zu, "I-Western Sahara" },
			}
		);
	}
}
