// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class EH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "212",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Vestsahara" },
				{ LanguageId.af, "Wes-Sahara" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Sahara Atɔeɛ" },
				{ LanguageId.am, "ምዕራባዊ ሳህራ" },
				{ LanguageId.ar, "الصحراء الغربية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "পশ্চিমীয় ছাহাৰা" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Sáḥara Occidental" },
				{ LanguageId.az, "Qərbi Saxara" },
				{ LanguageId.ba, "Көнбайыш Сахара" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Заходняя Сахара" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Западна Сахара" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পশ্চিম সাহারা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sahara ar Cʼhornôg" },
				{ LanguageId.brx, "सोनाबारि साहारा" },
				{ LanguageId.bs, "Zapadna Sahara" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sàhara Occidental" },
				{ LanguageId.ccp, "𑄛𑄧𑄎𑄨𑄟𑄴 𑄥𑄦𑄢" },
				{ LanguageId.ce, "Малхбузен Саьхьара" },
				{ LanguageId.ceb, "Western Sahara" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏭᏕᎵᎬ ᏗᏜ ᏌᎮᎳ" },
				{ LanguageId.ckb, "سەحرای ڕۆژاوا" },
				{ LanguageId.co, "Sahara Occidentale" },
				{ LanguageId.cs, "Západní Sahara" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gorllewin Sahara" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Westsahara" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódwjacorna Sahara" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ནུབ་ཕྱོགས་ ས་ཧཱ་ར" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Ɣetoɖoƒe Sahara nutome" },
				{ LanguageId.el, "Δυτική Σαχάρα" },
				{ LanguageId.en, "Western Sahara" },
				{ LanguageId.eo, "Okcidenta Saharo" },
				{ LanguageId.es, "Sáhara Occidental" },
				{ LanguageId.et, "Lääne-Sahara" },
				{ LanguageId.eu, "Mendebaldeko Sahara" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "صحرای غربی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Länsi-Sahara" },
				{ LanguageId.fil, "Kanlurang Sahara" },
				{ LanguageId.fo, "Vestursahara" },
				{ LanguageId.fr, "Sahara occidental" },
				{ LanguageId.fur, "Sahara ocidentâl" },
				{ LanguageId.fy, "Westelijke Sahara" },
				{ LanguageId.ga, "an Sahára Thiar" },
				{ LanguageId.gd, "Sathara an Iar" },
				{ LanguageId.gl, "Sáhara Occidental" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Weschtsahara" },
				{ LanguageId.gu, "પશ્ચિમી સહારા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Yammacin Sahara" },
				{ LanguageId.haw, "Sahara Komohana" },
				{ LanguageId.he, "סהרה המערבית" },
				{ LanguageId.hi, "पश्चिमी सहारा" },
				{ LanguageId.hr, "Zapadna Sahara" },
				{ LanguageId.hsb, "Zapadna Sahara" },
				{ LanguageId.hu, "Nyugat-Szahara" },
				{ LanguageId.hy, "Արևմտյան Սահարա" },
				{ LanguageId.ia, "Sahara occidental" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sahara Barat" },
				{ LanguageId.ig, "Ọdịda Anyanwụ Sahara" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Vestur-Sahara" },
				{ LanguageId.it, "Sahara Occidentale" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "西サハラ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sahara Kulon" },
				{ LanguageId.ka, "დასავლეთ საჰარა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Sara Osidental" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Батыс Сахара" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាហារ៉ាខាងលិច" },
				{ LanguageId.kn, "ಪಶ್ಚಿಮ ಸಹಾರಾ" },
				{ LanguageId.ko, "서사하라" },
				{ LanguageId.kok, "अस्तंती सहारा" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مشرِقی سَہارا" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "Wäß-Sahara" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Батыш Сахара" },
				{ LanguageId.la, "Sahara Occidentalis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Westsahara" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊາຮາຣາຕາເວັນຕົກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Vakarų Sachara" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Rietumsahāra" },
				{ LanguageId.mai, "पश्चिमी सहारा" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Sahara Andrefana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hahāra ki te Tonga" },
				{ LanguageId.mk, "Западна Сахара" },
				{ LanguageId.ml, "പശ്ചിമ സഹാറ" },
				{ LanguageId.mn, "Баруун Сахар" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पश्चिम सहारा" },
				{ LanguageId.ms, "Sahara Barat" },
				{ LanguageId.mt, "is-Saħara tal-Punent" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အနောက် ဆာဟာရ" },
				{ LanguageId.mzn, "غربی صحرا" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Vest-Sahara" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पश्चिमी साहारा" },
				{ LanguageId.nl, "Westelijke Sahara" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Vest-Sahara" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߌ߲߬ߢߍ߬ߞߏ߲ߞߏ߫ ߕߟߋ߬ߓߋ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Sahaaraa Dhihaa" },
				{ LanguageId.or, "ପଶ୍ଚିମ ସାହାରା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪੱਛਮੀ ਸਹਾਰਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Wẹ́stán Sahára" },
				{ LanguageId.pl, "Sahara Zachodnia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "لويديځ صحارا" },
				{ LanguageId.pt, "Saara Ocidental" },
				{ LanguageId.qu, "Sahara Occidental" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sahara Occidentala" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sahara Occidentală" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Западная Сахара" },
				{ LanguageId.rw, "Sahara y'Uburengerazuba" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "اولهه صحارا" },
				{ LanguageId.se, "Oarje-Sahára" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "බටහිර සහරාව" },
				{ LanguageId.sk, "Západná Sahara" },
				{ LanguageId.sl, "Zahodna Sahara" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Western Sahara" },
				{ LanguageId.so, "Saxaraha Galbeed" },
				{ LanguageId.sq, "Saharaja Perëndimore" },
				{ LanguageId.sr, "Западна Сахара" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sahara Bophirimela" },
				{ LanguageId.su, "Sahara Kulon" },
				{ LanguageId.sv, "Västsahara" },
				{ LanguageId.sw, "Sahara Magharibi" },
				{ LanguageId.syr, "ܨܚܪܐ ܡܥܪܒܝܬܐ" },
				{ LanguageId.ta, "மேற்கு சஹாரா" },
				{ LanguageId.te, "పడమటి సహారా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сахараи Ғарбӣ" },
				{ LanguageId.th, "ซาฮาราตะวันตก" },
				{ LanguageId.ti, "ምዕራባዊ ሰሃራ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günbatar Sahara" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sahala fakahihifo" },
				{ LanguageId.tr, "Batı Sahra" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көнбатыш Сахара" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "غەربىي ساخارا" },
				{ LanguageId.uk, "Західна Сахара" },
				{ LanguageId.ur, "مغربی صحارا" },
				{ LanguageId.uz, "G‘arbiy Sahroi Kabir" },
				{ LanguageId.vai, "ꕢꕌꕟ ꔎꔒ ꕀꔤ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Tây Sahara" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "Weštsahara" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Sahara bu sowwu" },
				{ LanguageId.xh, "EWestern Sahara" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מערב סאַהאַראַ" },
				{ LanguageId.yo, "Ìwọ̀òòrùn Sàhárà" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "西撒哈拉" },
				{ LanguageId.zu, "i-Western Sahara" },
			}
		);
	}
}
