// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class FI
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "358",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Finland" },
				{ LanguageId.da, "Finland" },
				{ LanguageId.af, "Finland" },
				{ LanguageId.agq, "Fɨnlàn" },
				{ LanguageId.ak, "Finland" },
				{ LanguageId.am, "ፊንላንድ" },
				{ LanguageId.ar, "فنلندا" },
				{ LanguageId.arn, "Finland" },
				{ LanguageId.@as, "ফিনলেণ্ড" },
				{ LanguageId.asa, "Ufini" },
				{ LanguageId.ast, "Finlandia" },
				{ LanguageId.az, "Finlandiya" },
				{ LanguageId.ba, "Финляндия" },
				{ LanguageId.bas, "Fìnlând" },
				{ LanguageId.be, "Фінляндыя" },
				{ LanguageId.bem, "Finland" },
				{ LanguageId.bez, "Huufini" },
				{ LanguageId.bg, "Финландия" },
				{ LanguageId.bin, "Finland" },
				{ LanguageId.bm, "Finilandi" },
				{ LanguageId.bn, "ফিনল্যান্ড" },
				{ LanguageId.bo, "ཧྥིན་ལན" },
				{ LanguageId.br, "Finland" },
				{ LanguageId.brx, "फिनलेण्ड" },
				{ LanguageId.bs, "Finska" },
				{ LanguageId.byn, "ፊንላንድ" },
				{ LanguageId.ca, "Finlàndia" },
				{ LanguageId.ccp, "𑄜𑄨𑄚𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Финлянди" },
				{ LanguageId.ceb, "Finland" },
				{ LanguageId.cgg, "Bufini" },
				{ LanguageId.chr, "ᏫᏂᎦᏙᎯ" },
				{ LanguageId.ckb, "فینلاند" },
				{ LanguageId.co, "Finlandia" },
				{ LanguageId.cs, "Finsko" },
				{ LanguageId.cu, "Фінландїꙗ" },
				{ LanguageId.cy, "Y Ffindir" },
				{ LanguageId.dav, "Ufini" },
				{ LanguageId.de, "Finnland" },
				{ LanguageId.dje, "Finlandu" },
				{ LanguageId.doi, "फिनलैंड" },
				{ LanguageId.dsb, "Finska" },
				{ LanguageId.dua, "Finland" },
				{ LanguageId.dv, "ފިންލޭންޑު" },
				{ LanguageId.dz, "ཕིན་ལེནཌ" },
				{ LanguageId.ebu, "Ufini" },
				{ LanguageId.ee, "Finland nutome" },
				{ LanguageId.el, "Φινλανδία" },
				{ LanguageId.en, "Finland" },
				{ LanguageId.eo, "Finnlando" },
				{ LanguageId.es, "Finlandia" },
				{ LanguageId.et, "Soome" },
				{ LanguageId.eu, "Finlandia" },
				{ LanguageId.ewo, "Finəlán" },
				{ LanguageId.fa, "فنلاند" },
				{ LanguageId.ff, "Fenland" },
				{ LanguageId.fi, "Suomi" },
				{ LanguageId.fil, "Finland" },
				{ LanguageId.fo, "Finnland" },
				{ LanguageId.fr, "Finlande" },
				{ LanguageId.fur, "Finlandie" },
				{ LanguageId.fy, "Finlân" },
				{ LanguageId.ga, "an Fhionlainn" },
				{ LanguageId.gd, "An Fhionnlann" },
				{ LanguageId.gl, "Finlandia" },
				{ LanguageId.gn, "Finlandia" },
				{ LanguageId.gsw, "Finnland" },
				{ LanguageId.gu, "ફિનલેન્ડ" },
				{ LanguageId.guz, "Ufini" },
				{ LanguageId.gv, "Finnlynn" },
				{ LanguageId.ha, "Finlan" },
				{ LanguageId.haw, "Pinilana" },
				{ LanguageId.he, "פינלנד" },
				{ LanguageId.hi, "फ़िनलैंड" },
				{ LanguageId.hr, "Finska" },
				{ LanguageId.hsb, "Finska" },
				{ LanguageId.hu, "Finnország" },
				{ LanguageId.hy, "Ֆինլանդիա" },
				{ LanguageId.ia, "Finlandia" },
				{ LanguageId.ibb, "Finland" },
				{ LanguageId.id, "Finlandia" },
				{ LanguageId.ig, "Finland" },
				{ LanguageId.ii, "ꃏꇩ" },
				{ LanguageId.@is, "Finnland" },
				{ LanguageId.it, "Finlandia" },
				{ LanguageId.iu, "ᕖᓚᓐ" },
				{ LanguageId.ja, "フィンランド" },
				{ LanguageId.jgo, "Finland" },
				{ LanguageId.jmc, "Ufini" },
				{ LanguageId.jv, "Finlan" },
				{ LanguageId.ka, "ფინეთი" },
				{ LanguageId.kab, "Finlund" },
				{ LanguageId.kam, "Ufini" },
				{ LanguageId.kde, "Ufini" },
				{ LanguageId.kea, "Finlándia" },
				{ LanguageId.khq, "Finlandu" },
				{ LanguageId.ki, "Ufini" },
				{ LanguageId.kk, "Финляндия" },
				{ LanguageId.kkj, "Finland" },
				{ LanguageId.kl, "Finland" },
				{ LanguageId.kln, "Emetab Finland" },
				{ LanguageId.km, "ហ្វាំងឡង់" },
				{ LanguageId.kn, "ಫಿನ್‌ಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "핀란드" },
				{ LanguageId.kok, "फिनलँड" },
				{ LanguageId.kr, "Finland" },
				{ LanguageId.ks, "فِن لینڈ" },
				{ LanguageId.ksb, "Ufini" },
				{ LanguageId.ksf, "fínlan" },
				{ LanguageId.ksh, "Finnland" },
				{ LanguageId.kw, "Fynnlond" },
				{ LanguageId.ky, "Финляндия" },
				{ LanguageId.la, "Finnia" },
				{ LanguageId.lag, "Ufíini" },
				{ LanguageId.lb, "Finnland" },
				{ LanguageId.lg, "Finilandi" },
				{ LanguageId.lkt, "Finland" },
				{ LanguageId.ln, "Filandɛ" },
				{ LanguageId.lo, "ຟິນແລນ" },
				{ LanguageId.lrc, "فینلاند" },
				{ LanguageId.lt, "Suomija" },
				{ LanguageId.luo, "Finland" },
				{ LanguageId.luy, "Ufini" },
				{ LanguageId.lv, "Somija" },
				{ LanguageId.mai, "फिनलैंड" },
				{ LanguageId.mas, "Ufini" },
				{ LanguageId.mer, "Finilandi" },
				{ LanguageId.mfe, "Finland" },
				{ LanguageId.mg, "Finlandy" },
				{ LanguageId.mgo, "Finland" },
				{ LanguageId.mi, "Whinarana" },
				{ LanguageId.mk, "Финска" },
				{ LanguageId.ml, "ഫിൻലാൻഡ്" },
				{ LanguageId.mn, "Финланд" },
				{ LanguageId.mni, "ফিনল্যান্দ" },
				{ LanguageId.moh, "Finland" },
				{ LanguageId.mr, "फिनलंड" },
				{ LanguageId.ms, "Finland" },
				{ LanguageId.mt, "il-Finlandja" },
				{ LanguageId.mua, "Sǝr Finland" },
				{ LanguageId.my, "ဖင်လန်" },
				{ LanguageId.mzn, "فنلاند" },
				{ LanguageId.naq, "Finlandi" },
				{ LanguageId.nb, "Finland" },
				{ LanguageId.nd, "Finland" },
				{ LanguageId.nds, "Finnland" },
				{ LanguageId.ne, "फिनल्याण्ड" },
				{ LanguageId.nl, "Finland" },
				{ LanguageId.nmg, "Finlande" },
				{ LanguageId.nn, "Finland" },
				{ LanguageId.nnh, "Finland" },
				{ LanguageId.nqo, "ߝߍ߲ߟߊ߲ߘ" },
				{ LanguageId.nr, "Finland" },
				{ LanguageId.nso, "Finland" },
				{ LanguageId.nus, "Finland" },
				{ LanguageId.nyn, "Bufini" },
				{ LanguageId.oc, "Finlàndia" },
				{ LanguageId.om, "Fiinlaand" },
				{ LanguageId.or, "ଫିନଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Финлянди" },
				{ LanguageId.pa, "ਫਿਨਲੈਂਡ" },
				{ LanguageId.pap, "Finlandia" },
				{ LanguageId.pcm, "Fínland" },
				{ LanguageId.pl, "Finlandia" },
				{ LanguageId.prg, "Finland" },
				{ LanguageId.ps, "فنلینډ" },
				{ LanguageId.pt, "Finlândia" },
				{ LanguageId.qu, "Finlandia" },
				{ LanguageId.quc, "Finlandia" },
				{ LanguageId.rm, "Finlanda" },
				{ LanguageId.rn, "Finilandi" },
				{ LanguageId.ro, "Finlanda" },
				{ LanguageId.rof, "Ufini" },
				{ LanguageId.ru, "Финляндия" },
				{ LanguageId.rw, "Finlande" },
				{ LanguageId.rwk, "Ufini" },
				{ LanguageId.sa, "फिनलैंड" },
				{ LanguageId.sah, "Финляндия" },
				{ LanguageId.saq, "Ufini" },
				{ LanguageId.sat, "ᱯᱷᱤᱱᱞᱮᱱᱰ" },
				{ LanguageId.sbp, "Wufini" },
				{ LanguageId.sd, "فن لينڊ" },
				{ LanguageId.se, "Suopma" },
				{ LanguageId.seh, "Finlândia" },
				{ LanguageId.ses, "Finlandu" },
				{ LanguageId.sg, "Fëlânde" },
				{ LanguageId.shi, "ⴼⵉⵍⵍⴰⵏⴷⴰ" },
				{ LanguageId.si, "ෆින්ලන්තය" },
				{ LanguageId.sk, "Fínsko" },
				{ LanguageId.sl, "Finska" },
				{ LanguageId.sma, "Såevmie" },
				{ LanguageId.smj, "Suopma" },
				{ LanguageId.smn, "Suomâ" },
				{ LanguageId.sms, "Lääʹddjânnam" },
				{ LanguageId.sn, "Finland" },
				{ LanguageId.so, "Finland" },
				{ LanguageId.sq, "Finlandë" },
				{ LanguageId.sr, "Финска" },
				{ LanguageId.ss, "IFinlandi" },
				{ LanguageId.ssy, "Finland" },
				{ LanguageId.st, "Finland" },
				{ LanguageId.su, "Finlandia" },
				{ LanguageId.sv, "Finland" },
				{ LanguageId.sw, "Ufini" },
				{ LanguageId.syr, "ܦܝܢܠܢܕ" },
				{ LanguageId.ta, "பின்லாந்து" },
				{ LanguageId.te, "ఫిన్లాండ్" },
				{ LanguageId.teo, "Ufini" },
				{ LanguageId.tg, "Финляндия" },
				{ LanguageId.th, "ฟินแลนด์" },
				{ LanguageId.ti, "ፊንላንድ" },
				{ LanguageId.tig, "ፊንላንድ" },
				{ LanguageId.tk, "Finlýandiýa" },
				{ LanguageId.tn, "Finland" },
				{ LanguageId.to, "Finilani" },
				{ LanguageId.tr, "Finlandiya" },
				{ LanguageId.ts, "Finland" },
				{ LanguageId.tt, "Финляндия" },
				{ LanguageId.twq, "Finlandu" },
				{ LanguageId.tzm, "Finlanḍa" },
				{ LanguageId.ug, "فىنلاندىيە" },
				{ LanguageId.uk, "Фінляндія" },
				{ LanguageId.ur, "فن لینڈ" },
				{ LanguageId.uz, "Finlandiya" },
				{ LanguageId.vai, "ꔱꘋ ꖨꕮꕊ" },
				{ LanguageId.ve, "Finland" },
				{ LanguageId.vi, "Phần Lan" },
				{ LanguageId.vo, "Suomiyän" },
				{ LanguageId.vun, "Ufini" },
				{ LanguageId.wae, "Finnland" },
				{ LanguageId.wal, "Finland" },
				{ LanguageId.wo, "Finlànd" },
				{ LanguageId.xh, "EFinland" },
				{ LanguageId.xog, "Finilandi" },
				{ LanguageId.yav, "fɛnlánd" },
				{ LanguageId.yi, "פֿינלאַנד" },
				{ LanguageId.yo, "Filandi" },
				{ LanguageId.zgh, "ⴼⵉⵍⵍⴰⵏⴷⴰ" },
				{ LanguageId.zh, "芬兰" },
				{ LanguageId.zu, "i-Finland" },
			}
		);
	}
}
