using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class FK
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "500",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Falklandsøerne" },
				{ LanguageId.af, "Falkland-eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የፎክላንድ ደሴቶች" },
				{ LanguageId.ar, "جزر فوكلاند" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Folklend adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Фолклендскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Фолкландски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ফকল্যান্ড দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Falklandska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Malvines" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga dapit nga gitawag Falkland Islands" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isole Falkland" },
				{ LanguageId.cs, "Falklandy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Falkland" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Falkland Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησιά Φώκλαντ" },
				{ LanguageId.en, "Falkland Islands" },
				{ LanguageId.eo, "Falklandinsuloj" },
				{ LanguageId.es, "Islas Malvinas" },
				{ LanguageId.et, "Falklandi saared" },
				{ LanguageId.eu, "Falkland uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر فالکلند" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Falkland saaret" },
				{ LanguageId.fil, "mga isla ng Falkland" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "les îles Falkland" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Falklâneilannen" },
				{ LanguageId.ga, "Oileáin Fháclainne" },
				{ LanguageId.gd, "Eileanan Faclanach" },
				{ LanguageId.gl, "Illas Malvinas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ફોકલેન્ડ ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Falkland" },
				{ LanguageId.haw, "Pae ʻāina ʻo Falkland" },
				{ LanguageId.he, "איי פוקלנד" },
				{ LanguageId.hi, "फ़ॉकलैंड आइलैंड" },
				{ LanguageId.hr, "Falklandski otoci" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Falkland-szigetek" },
				{ LanguageId.hy, "Ֆոլքլենդյան կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Falkland" },
				{ LanguageId.ig, "Agwaetiti Falkland" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Falklandseyjar" },
				{ LanguageId.it, "Isole Falkland" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フォークランド諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Falkland" },
				{ LanguageId.ka, "ფოლკლენდის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Фолкленд аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Falkland" },
				{ LanguageId.kn, "ಫಾಕ್ಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "포클랜드 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Фолкленд аралдары" },
				{ LanguageId.la, "Insulae Malvinae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Falkland Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະຟອກແລນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Folklando salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Folklenda salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Falkland" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Nga Moutere o Falkland" },
				{ LanguageId.mk, "Фолкландските Острови" },
				{ LanguageId.ml, "ഫോക്ക്ലാൻഡ് ദ്വീപുകൾ" },
				{ LanguageId.mn, "Фолкландын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फॉकलंड बेटे" },
				{ LanguageId.ms, "Kepulauan Falkland" },
				{ LanguageId.mt, "Gżejjer Falkland" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဖော့ကလန်ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Falklandsøyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फकल्याण्ड टापुहरू" },
				{ LanguageId.nl, "Falkland Eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଫାଲ୍କଲ୍ୟାଣ୍ଡ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫਾਕਲੈਂਡ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Falklandy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فاکلنډ ټاپوګان" },
				{ LanguageId.pt, "Ilhas Malvinas" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Falkland" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Фолклендские острова" },
				{ LanguageId.rw, "Ibirwa bya Falkland" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "فاڪلينڊ ٻيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ෆෝක්ලන්ඩ් දූපත්" },
				{ LanguageId.sk, "Falklandské ostrovy" },
				{ LanguageId.sl, "Falklandski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Falkland Islands" },
				{ LanguageId.so, "Jasiiradaha Falkland" },
				{ LanguageId.sq, "Ishujt Falkland" },
				{ LanguageId.sr, "Фокландска острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Falkland" },
				{ LanguageId.su, "Kapuloan Falkland" },
				{ LanguageId.sv, "Falklandsöarna" },
				{ LanguageId.sw, "Visiwa vya Falkland" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "பால்க்லாந்து தீவுகள்" },
				{ LanguageId.te, "ఫాక్లాండ్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Фолкленд" },
				{ LanguageId.th, "หมู่เกาะฟอล์กแลนด์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Folklend adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Falkland adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Фолкленд утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "فالكلاند ئارىلى" },
				{ LanguageId.uk, "Фолклендські острови" },
				{ LanguageId.ur, "فاک لینڈ جزائر" },
				{ LanguageId.uz, "Folklend orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Falkland" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseFalkland" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פאַלקלאַנד אינזלען" },
				{ LanguageId.yo, "Awọn erekusu Falkland" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "福克兰群岛" },
				{ LanguageId.zu, "Iziqhingi zase-Falkland" },
			}
		);
	}
}
