// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class FK
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "500",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Falklandsøerne" },
				{ LanguageId.af, "Falklandeilande" },
				{ LanguageId.agq, "Chwɨlà fɨ Fakɨlàn" },
				{ LanguageId.ak, "Fɔkman Aeland" },
				{ LanguageId.am, "የፎክላንድ ደሴቶች" },
				{ LanguageId.ar, "جزر فوكلاند" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ফকলেণ্ড দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Falkland" },
				{ LanguageId.ast, "Falkland Islands" },
				{ LanguageId.az, "Folklend adaları" },
				{ LanguageId.ba, "Фолкленд утрауҙары" },
				{ LanguageId.bas, "Bìòn bi Falkland" },
				{ LanguageId.be, "Фалклендскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Falkland" },
				{ LanguageId.bg, "Фолкландски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Maluwini Gun" },
				{ LanguageId.bn, "ফকল্যান্ড দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Falkland" },
				{ LanguageId.brx, "फकलेण्ड द्वीपफोर" },
				{ LanguageId.bs, "Folklandska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Falkland" },
				{ LanguageId.ccp, "𑄜𑄧𑄇𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Фолклендан гӀайренаш" },
				{ LanguageId.ceb, "Falkland Islands" },
				{ LanguageId.cgg, "Ebizinga bya Faakilanda" },
				{ LanguageId.chr, "ᏩᎩ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی مالڤیناس (دوورگەکانی فاڵکلاند)" },
				{ LanguageId.co, "Isole Falkland" },
				{ LanguageId.cs, "Falklandské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd y Falkland/Malvinas" },
				{ LanguageId.dav, "Visiwa vya Falkland" },
				{ LanguageId.de, "Falklandinseln" },
				{ LanguageId.dje, "Kalkan gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Falklandske kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཕལྐ་ལནྜ་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Visiwa vya Falkland" },
				{ LanguageId.ee, "Falkland ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Φόκλαντ" },
				{ LanguageId.en, "Falkland Islands" },
				{ LanguageId.eo, "Falklandoj" },
				{ LanguageId.es, "Islas Malvinas" },
				{ LanguageId.et, "Falklandi saared" },
				{ LanguageId.eu, "Falklandak" },
				{ LanguageId.ewo, "Minlán Mi Fóləkəlan" },
				{ LanguageId.fa, "جزایر فالکلند" },
				{ LanguageId.ff, "Duuɗe Falkland" },
				{ LanguageId.fi, "Falklandinsaaret" },
				{ LanguageId.fil, "Falkland Islands" },
				{ LanguageId.fo, "Falklandsoyggjar" },
				{ LanguageId.fr, "Îles Malouines" },
				{ LanguageId.fur, "Isulis Falkland" },
				{ LanguageId.fy, "Falklâneilannen" },
				{ LanguageId.ga, "Oileáin Fháclainne" },
				{ LanguageId.gd, "Na h-Eileanan Fàclannach" },
				{ LanguageId.gl, "Illas Malvinas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Falkland-Insle" },
				{ LanguageId.gu, "ફૉકલૅન્ડ આઇલૅન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Falkland" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Falkilan" },
				{ LanguageId.haw, "Pae ʻāina ʻo Falkland" },
				{ LanguageId.he, "איי פוקלנד" },
				{ LanguageId.hi, "फ़ॉकलैंड द्वीपसमूह" },
				{ LanguageId.hr, "Falklandski Otoci" },
				{ LanguageId.hsb, "Falklandske kupy" },
				{ LanguageId.hu, "Falkland-szigetek" },
				{ LanguageId.hy, "Ֆոլքլենդյան կղզիներ" },
				{ LanguageId.ia, "Insulas Falkland" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Falkland" },
				{ LanguageId.ig, "Falkland Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Falklandseyjar" },
				{ LanguageId.it, "Isole Falkland" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フォークランド諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Falkland" },
				{ LanguageId.jv, "Kapuloan Falkland" },
				{ LanguageId.ka, "ფოლკლენდის კუნძულები" },
				{ LanguageId.kab, "Tigzirin n Falkland" },
				{ LanguageId.kam, "Visiwa vya Falkland" },
				{ LanguageId.kde, "Chisiwa cha Falkland" },
				{ LanguageId.kea, "Ilhas Malvinas" },
				{ LanguageId.khq, "Kalkan gungey" },
				{ LanguageId.ki, "Visiwa vya Falkland" },
				{ LanguageId.kk, "Фолкленд аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeyotab Falkland" },
				{ LanguageId.km, "កោះ​ហ្វក់ឡែន" },
				{ LanguageId.kn, "ಫಾಕ್‌ಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "포클랜드 제도" },
				{ LanguageId.kok, "फ़ॉकलैंड आइलैंड्स" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "فٕلاکلینڑ جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Falkland" },
				{ LanguageId.ksf, "zǝ maalwín" },
				{ LanguageId.ksh, "de Falkland-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Фолкленд аралдары" },
				{ LanguageId.la, "Insulae Malvinae" },
				{ LanguageId.lag, "Visíiwa vya Fakulandi" },
				{ LanguageId.lb, "Falklandinselen" },
				{ LanguageId.lg, "Bizinga by’eFalikalandi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Maluni" },
				{ LanguageId.lo, "ຫມູ່ເກາະຟອກແລນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Folklando salos" },
				{ LanguageId.luo, "Chuia mar Falkland" },
				{ LanguageId.luy, "Visiwa vya Falkland" },
				{ LanguageId.lv, "Folklenda salas" },
				{ LanguageId.mai, "फाकलैंड द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Falkland" },
				{ LanguageId.mer, "Aĩrandi cia Falklandi" },
				{ LanguageId.mfe, "Zil malwinn" },
				{ LanguageId.mg, "Nosy Falkand" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Motu Whākarangi" },
				{ LanguageId.mk, "Фолкландски Острови" },
				{ LanguageId.ml, "ഫാക്ക്‌ലാന്റ് ദ്വീപുകൾ" },
				{ LanguageId.mn, "Фолклендийн арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फॉकलंड बेटे" },
				{ LanguageId.ms, "Kepulauan Falkland" },
				{ LanguageId.mt, "il-Gżejjer Falkland" },
				{ LanguageId.mua, "Sǝr malouniya ma laŋne" },
				{ LanguageId.my, "ဖော့ကလန် ကျွန်းစု" },
				{ LanguageId.mzn, "فالکلند جزیره‌ئون" },
				{ LanguageId.naq, "Falkland Islands" },
				{ LanguageId.nb, "Falklandsøyene" },
				{ LanguageId.nd, "Falkland Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फकल्याण्ड टापुहरु" },
				{ LanguageId.nl, "Falklandeilanden" },
				{ LanguageId.nmg, "Maŋ má Falkland" },
				{ LanguageId.nn, "Falklandsøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߊߟߎ߲ߌ߲߫ ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ebizinga bya Faakilanda" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Faalklaand" },
				{ LanguageId.or, "ଫକ୍‌ଲ୍ୟାଣ୍ଡ ଦ୍ଵୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫ਼ਾਕਲੈਂਡ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Fọ́klánd Aílands" },
				{ LanguageId.pl, "Falklandy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فاکلينډ ټاپوګان" },
				{ LanguageId.pt, "Ilhas Malvinas" },
				{ LanguageId.qu, "Islas Malvinas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Falkland" },
				{ LanguageId.rn, "Izinga rya Filikilandi" },
				{ LanguageId.ro, "Insulele Falkland" },
				{ LanguageId.rof, "Visiwa vya Falkland" },
				{ LanguageId.ru, "Фолклендские о-ва" },
				{ LanguageId.rw, "Ibirwa bya Falkland" },
				{ LanguageId.rwk, "Visiwa vya Falkland" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Falkland" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli fya Fokolendi" },
				{ LanguageId.sd, "فاڪ لينڊ ٻيٽ" },
				{ LanguageId.se, "Falklandsullot" },
				{ LanguageId.seh, "Ilhas Malvinas" },
				{ LanguageId.ses, "Kalkan gungey" },
				{ LanguageId.sg, "Âzûâ tî Mälüîni" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵍⴰⵡⵉ" },
				{ LanguageId.si, "ෆෝක්ලන්ත දූපත්" },
				{ LanguageId.sk, "Falklandy" },
				{ LanguageId.sl, "Falklandski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Falklandsuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveFalklands" },
				{ LanguageId.so, "Jaziiradaha Fooklaan" },
				{ LanguageId.sq, "Ishujt Falkland" },
				{ LanguageId.sr, "Фокландска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Falkland" },
				{ LanguageId.su, "Kapuloan Falkland" },
				{ LanguageId.sv, "Falklandsöarna" },
				{ LanguageId.sw, "Visiwa vya Falkland" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܦܠܟܠܢܕ" },
				{ LanguageId.ta, "ஃபாக்லாந்து தீவுகள்" },
				{ LanguageId.te, "ఫాక్‌ల్యాండ్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Falkland" },
				{ LanguageId.tg, "Ҷазираҳои Фолкленд" },
				{ LanguageId.th, "หมู่เกาะฟอล์กแลนด์" },
				{ LanguageId.ti, "ደሴታት ፎክላንድ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Folklend adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Fokulani" },
				{ LanguageId.tr, "Falkland Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Фолкленд утраулары" },
				{ LanguageId.twq, "Kalkan gungey" },
				{ LanguageId.tzm, "Tigzirin n Falkland" },
				{ LanguageId.ug, "فالكلاند ئاراللىرى" },
				{ LanguageId.uk, "Фолклендські Острови" },
				{ LanguageId.ur, "فاکلینڈ جزائر" },
				{ LanguageId.uz, "Folklend orollari" },
				{ LanguageId.vai, "ꕘꔷꕃ ꖨꕮ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Falkland" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Falkland" },
				{ LanguageId.wae, "Falklandinslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Falkland" },
				{ LanguageId.xh, "EFalkland Islands" },
				{ LanguageId.xog, "Ebiizinga bya Falikalandi" },
				{ LanguageId.yav, "maluwín" },
				{ LanguageId.yi, "פֿאַלקלאַנד אינזלען" },
				{ LanguageId.yo, "Etikun Fakalandi" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵍⴰⵡⵉ" },
				{ LanguageId.zh, "福克兰群岛" },
				{ LanguageId.zu, "i-Falkland Islands" },
			}
		);
	}
}
