// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class FM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "691",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Mikronesien" },
				{ LanguageId.af, "Mikronesië" },
				{ LanguageId.agq, "Maekòlòneshìa" },
				{ LanguageId.ak, "Maekronehyia" },
				{ LanguageId.am, "ማይክሮኔዢያ" },
				{ LanguageId.ar, "ميكرونيزيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মাইক্ৰোনেচিয়া" },
				{ LanguageId.asa, "Mikronethia" },
				{ LanguageId.ast, "Micronesia" },
				{ LanguageId.az, "Mikroneziya" },
				{ LanguageId.ba, "Микронезия" },
				{ LanguageId.bas, "Mìkrònesìà" },
				{ LanguageId.be, "Мікранезія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Humikronesia" },
				{ LanguageId.bg, "Микронезия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Mikironesi" },
				{ LanguageId.bn, "মাইক্রোনেশিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Mikronezia" },
				{ LanguageId.brx, "माइक्रनेशिया" },
				{ LanguageId.bs, "Mikronezija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Micronèsia" },
				{ LanguageId.ccp, "𑄟𑄭𑄇𑄳𑄢𑄮𑄚𑄬𑄥𑄨𑄠" },
				{ LanguageId.ce, "Микронезин Федеративни штаташ" },
				{ LanguageId.ceb, "Micronesia" },
				{ LanguageId.cgg, "Mikironesiya" },
				{ LanguageId.chr, "ᎹᎢᏉᏂᏏᏯ" },
				{ LanguageId.ckb, "مایکرۆنیزیا" },
				{ LanguageId.co, "Micronesia" },
				{ LanguageId.cs, "Mikronésie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Micronesia" },
				{ LanguageId.dav, "Mikronesia" },
				{ LanguageId.de, "Mikronesien" },
				{ LanguageId.dje, "Mikronezi" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Mikroneziska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "མའི་ཀྲོ་ནི་ཤི་ཡ" },
				{ LanguageId.ebu, "Mikronesia" },
				{ LanguageId.ee, "Mikronesia nutome" },
				{ LanguageId.el, "Μικρονησία" },
				{ LanguageId.en, "Micronesia" },
				{ LanguageId.eo, "Mikronezio" },
				{ LanguageId.es, "Micronesia" },
				{ LanguageId.et, "Mikroneesia" },
				{ LanguageId.eu, "Mikronesia" },
				{ LanguageId.ewo, "Mikoronésia" },
				{ LanguageId.fa, "میکرونزی" },
				{ LanguageId.ff, "Mikoronesii" },
				{ LanguageId.fi, "Mikronesia" },
				{ LanguageId.fil, "Micronesia" },
				{ LanguageId.fo, "Mikronesiasamveldið" },
				{ LanguageId.fr, "Micronésie" },
				{ LanguageId.fur, "Micronesie" },
				{ LanguageId.fy, "Micronesië" },
				{ LanguageId.ga, "an Mhicrinéis" },
				{ LanguageId.gd, "Na Meanbh-eileanan" },
				{ LanguageId.gl, "Micronesia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Mikroneesie" },
				{ LanguageId.gu, "માઇક્રોનેશિયા" },
				{ LanguageId.guz, "Mikronesia" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Mikuronesiya" },
				{ LanguageId.haw, "Maikonekia" },
				{ LanguageId.he, "מיקרונזיה" },
				{ LanguageId.hi, "माइक्रोनेशिया" },
				{ LanguageId.hr, "Mikronezija" },
				{ LanguageId.hsb, "Mikroneziska" },
				{ LanguageId.hu, "Mikronézia" },
				{ LanguageId.hy, "Միկրոնեզիա" },
				{ LanguageId.ia, "Micronesia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Mikronesia" },
				{ LanguageId.ig, "Micronesia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Míkrónesía" },
				{ LanguageId.it, "Micronesia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ミクロネシア連邦" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Mikronesia" },
				{ LanguageId.jv, "Féderasi Mikronésia" },
				{ LanguageId.ka, "მიკრონეზია" },
				{ LanguageId.kab, "Mikrunizya" },
				{ LanguageId.kam, "Mikronesia" },
				{ LanguageId.kde, "Mikilonesia" },
				{ LanguageId.kea, "Mikronézia" },
				{ LanguageId.khq, "Mikronezi" },
				{ LanguageId.ki, "Mikronesia" },
				{ LanguageId.kk, "Микронезия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Micronesia" },
				{ LanguageId.km, "មីក្រូណេស៊ី" },
				{ LanguageId.kn, "ಮೈಕ್ರೋನೇಶಿಯಾ" },
				{ LanguageId.ko, "미크로네시아" },
				{ LanguageId.kok, "मायक्रोनिशिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مائیکرونیشیا" },
				{ LanguageId.ksb, "Miklonesia" },
				{ LanguageId.ksf, "mikronɛ́si" },
				{ LanguageId.ksh, "Mikroneesije" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Микронезия" },
				{ LanguageId.la, "Micronesia" },
				{ LanguageId.lag, "Mikironésia" },
				{ LanguageId.lb, "Mikronesien" },
				{ LanguageId.lg, "Mikuronezya" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Mikronezi" },
				{ LanguageId.lo, "ໄມໂຄຣນີເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Mikronezija" },
				{ LanguageId.luo, "Micronesia" },
				{ LanguageId.luy, "Mikronesia" },
				{ LanguageId.lv, "Mikronēzija" },
				{ LanguageId.mai, "माइक्रोनेशिया" },
				{ LanguageId.mas, "Mikronesia" },
				{ LanguageId.mer, "Mikronesia" },
				{ LanguageId.mfe, "Mikronezi" },
				{ LanguageId.mg, "Mikrônezia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Mekanēhia" },
				{ LanguageId.mk, "Микронезија" },
				{ LanguageId.ml, "മൈക്രോനേഷ്യ" },
				{ LanguageId.mn, "Микронези" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मायक्रोनेशिया" },
				{ LanguageId.ms, "Micronesia" },
				{ LanguageId.mt, "il-Mikroneżja" },
				{ LanguageId.mua, "Micronesiya" },
				{ LanguageId.my, "မိုင်ခရိုနီရှား" },
				{ LanguageId.mzn, "میکرونزی" },
				{ LanguageId.naq, "Micronesia" },
				{ LanguageId.nb, "Mikronesiaføderasjonen" },
				{ LanguageId.nd, "Micronesia" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "माइक्रोनेसिया" },
				{ LanguageId.nl, "Micronesia" },
				{ LanguageId.nmg, "Mikronesia" },
				{ LanguageId.nn, "Mikronesiaføderasjonen" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߌߞߙߏߣߋߖ߭ߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Mikironesiya" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Maayikirooneeshiyaa" },
				{ LanguageId.or, "ମାଇକ୍ରୋନେସିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮਾਇਕ੍ਰੋਨੇਸ਼ੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Maikroníshia" },
				{ LanguageId.pl, "Mikronezja" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "میکرونیزیا" },
				{ LanguageId.pt, "Micronésia" },
				{ LanguageId.qu, "Micronesia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Micronesia" },
				{ LanguageId.rn, "Mikoroniziya" },
				{ LanguageId.ro, "Micronezia" },
				{ LanguageId.rof, "Mikronesia" },
				{ LanguageId.ru, "Федеративные Штаты Микронезии" },
				{ LanguageId.rw, "Micronesia" },
				{ LanguageId.rwk, "Mikronesia" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Mikronesia" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Mikilonesiya" },
				{ LanguageId.sd, "مائڪرونيشيا" },
				{ LanguageId.se, "Mikronesia" },
				{ LanguageId.seh, "Micronésia" },
				{ LanguageId.ses, "Mikronezi" },
				{ LanguageId.sg, "Mikronezïi" },
				{ LanguageId.shi, "ⵎⵉⴽⵔⵓⵏⵉⵣⵢⴰ" },
				{ LanguageId.si, "මයික්‍රොනීසියාව" },
				{ LanguageId.sk, "Mikronézia" },
				{ LanguageId.sl, "Mikronezija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Mikronesia littoväldi" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Micronesia" },
				{ LanguageId.so, "Mikroneesiya" },
				{ LanguageId.sq, "Mikronezi" },
				{ LanguageId.sr, "Микронезија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Micronesia" },
				{ LanguageId.su, "Mikronésia" },
				{ LanguageId.sv, "Mikronesien" },
				{ LanguageId.sw, "Mikronesia" },
				{ LanguageId.syr, "ܐܬܪ̈ܘܬܐ ܦܕܪܠܝܐ ܕܡܝܩܪܘܢܝܣܝܐ" },
				{ LanguageId.ta, "மைக்ரோனேஷியா" },
				{ LanguageId.te, "మైక్రోనేషియా" },
				{ LanguageId.teo, "Mikronesia" },
				{ LanguageId.tg, "Штатҳои Федеративии Микронезия" },
				{ LanguageId.th, "ไมโครนีเซีย" },
				{ LanguageId.ti, "ማይክሮነዥያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Mikroneziýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Mikolonīsia" },
				{ LanguageId.tr, "Mikronezya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Микронезия" },
				{ LanguageId.twq, "Mikronezi" },
				{ LanguageId.tzm, "Mikrunizya" },
				{ LanguageId.ug, "مىكرونېزىيە" },
				{ LanguageId.uk, "Мікронезія" },
				{ LanguageId.ur, "مائکرونیشیا" },
				{ LanguageId.uz, "Mikroneziya" },
				{ LanguageId.vai, "ꕆꖏꕇꔻꕩ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Micronesia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Mikronesia" },
				{ LanguageId.wae, "Mikronesie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Mikoronesi" },
				{ LanguageId.xh, "EMicronesia" },
				{ LanguageId.xog, "Mikuronezya" },
				{ LanguageId.yav, "mikolonesí" },
				{ LanguageId.yi, "מיקראנעזיע" },
				{ LanguageId.yo, "Makoronesia" },
				{ LanguageId.zgh, "ⵎⵉⴽⵔⵓⵏⵉⵣⵢⴰ" },
				{ LanguageId.zh, "密克罗尼西亚" },
				{ LanguageId.zu, "i-Micronesia" },
			}
		);
	}
}
