using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class FO
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "298",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Færøerne" },
				{ LanguageId.af, "Faroëreilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የፋሮ ደሴቶች" },
				{ LanguageId.ar, "جزر فاروس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Farer adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Фарэрскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Фарьорските острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ফারো দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Faero" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Farska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Faroe" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga isla sa Faroe" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Feroe" },
				{ LanguageId.cs, "Faerské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Faroe" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Färöer Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νήσοι Φερόες" },
				{ LanguageId.en, "Faroe Islands" },
				{ LanguageId.eo, "Feroaj Insuloj" },
				{ LanguageId.es, "Islas Faroe" },
				{ LanguageId.et, "Fääri saared" },
				{ LanguageId.eu, "Faroe uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر فارو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Färsaaret" },
				{ LanguageId.fil, "isla ng Faroe" },
				{ LanguageId.fo, "Føroyar" },
				{ LanguageId.fr, "Îles Féroé" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Faeröer Eilannen" },
				{ LanguageId.ga, "Oileáin Fharó" },
				{ LanguageId.gd, "Eileanan Fàrach" },
				{ LanguageId.gl, "Illas Feroe" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ફેરો ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Faroe" },
				{ LanguageId.haw, "Paeaina Faroe" },
				{ LanguageId.he, "איי פרו" },
				{ LanguageId.hi, "फ़ैरो द्वीप" },
				{ LanguageId.hr, "Farski otoci" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Faroe Szigetek" },
				{ LanguageId.hy, "Ֆարերյան կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Faroe" },
				{ LanguageId.ig, "Agwaetiti Faroe" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Færeyjar" },
				{ LanguageId.it, "Isole Faroe" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フェロー諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Faroe" },
				{ LanguageId.ka, "ფარერის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Фарер аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះហ្វារ៉ូ" },
				{ LanguageId.kn, "ಫರೋ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "페로 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Фарер аралдары" },
				{ LanguageId.la, "Insulae Faroe" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Färöer Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະຟາໂຣ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Farerų salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Fēru salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Faroe" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Moutere o Faroe" },
				{ LanguageId.mk, "Фарски Острови" },
				{ LanguageId.ml, "ഫറോ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Фарерын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फॅरो बेटे" },
				{ LanguageId.ms, "Pulau Faroe" },
				{ LanguageId.mt, "Gżejjer Faroe" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဖာရိုးကျွန်းစုများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Færøyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फारो टापुहरू" },
				{ LanguageId.nl, "Faeröer eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Færøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଫାରୋ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫਾਰੋ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Owcze" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د فارو ټاپو" },
				{ LanguageId.pt, "ilhas Faroe" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Feroe" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Фарерские острова" },
				{ LanguageId.rw, "Ibirwa bya Faroe" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "فيرو ٻيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ෆාරෝ දූපත්" },
				{ LanguageId.sk, "Faerské ostrovy" },
				{ LanguageId.sl, "Ferski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Faroe Islands" },
				{ LanguageId.so, "Jasiiradaha Faroe" },
				{ LanguageId.sq, "Ishujt Faroe" },
				{ LanguageId.sr, "Фарска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Faroe" },
				{ LanguageId.su, "Kapuloan Faroe" },
				{ LanguageId.sv, "Färöarna" },
				{ LanguageId.sw, "Visiwa vya Faroe" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஃபாரோ தீவுகள்" },
				{ LanguageId.te, "ఫారో దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Фарер" },
				{ LanguageId.th, "หมู่เกาะแฟโร" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Farer adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Faroe Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Фарер утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "فارو ئارىلى" },
				{ LanguageId.uk, "Фарерські острови" },
				{ LanguageId.ur, "جزائر فیرو" },
				{ LanguageId.uz, "Farer orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Faroe" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseFaroe" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פאַראָו אינזלען" },
				{ LanguageId.yo, "Awọn erekusu Faroe" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "法罗群岛" },
				{ LanguageId.zu, "Iziqhingi zase-Faroe" },
			}
		);
	}
}
