// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class FO
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "298",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Færøerne" },
				{ LanguageId.af, "Faroëreilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Faro Aeland" },
				{ LanguageId.am, "የፋሮ ደሴቶች" },
				{ LanguageId.ar, "جزر فارو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ফাৰো দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Islles Feroe" },
				{ LanguageId.az, "Farer adaları" },
				{ LanguageId.ba, "Фарер утрауҙары" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Фарэрскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Фарьорски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ফ্যারো দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Faero" },
				{ LanguageId.brx, "फेर’ द्वीपफोर" },
				{ LanguageId.bs, "Farska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Fèroe" },
				{ LanguageId.ccp, "𑄜𑄳𑄠𑄢𑄧𑄃𑄮 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Фарерийн гӀайренаш" },
				{ LanguageId.ceb, "Faroe Islands" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏪᎶ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی فارەو" },
				{ LanguageId.co, "Isule Feroe" },
				{ LanguageId.cs, "Faerské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Ffaro" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Färöer" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Färöje" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཕཱའེ་རོ་གླིང་ཚོམ" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Faroe ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Φερόες" },
				{ LanguageId.en, "Faroe Islands" },
				{ LanguageId.eo, "Ferooj" },
				{ LanguageId.es, "Islas Feroe" },
				{ LanguageId.et, "Fääri saared" },
				{ LanguageId.eu, "Faroe uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر فارو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Färsaaret" },
				{ LanguageId.fil, "Faroe Islands" },
				{ LanguageId.fo, "Føroyar" },
				{ LanguageId.fr, "Îles Féroé" },
				{ LanguageId.fur, "Isulis Faroe" },
				{ LanguageId.fy, "Faeröer" },
				{ LanguageId.ga, "Oileáin Fharó" },
				{ LanguageId.gd, "Na h-Eileanan Fàro" },
				{ LanguageId.gl, "Illas Feroe" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Färöer" },
				{ LanguageId.gu, "ફેરો આઇલૅન્ડ્સ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirai na Faroe" },
				{ LanguageId.haw, "Paeaina Faroe" },
				{ LanguageId.he, "איי פארו" },
				{ LanguageId.hi, "फ़ेरो द्वीपसमूह" },
				{ LanguageId.hr, "Farski Otoci" },
				{ LanguageId.hsb, "Färöske kupy" },
				{ LanguageId.hu, "Feröer szigetek" },
				{ LanguageId.hy, "Ֆարերյան կղզիներ" },
				{ LanguageId.ia, "Insulas Feroe" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Faroe" },
				{ LanguageId.ig, "Faroe Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Færeyjar" },
				{ LanguageId.it, "Isole Fær Øer" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フェロー諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Faro" },
				{ LanguageId.ka, "ფარერის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Ilhas Faroe" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Фарер аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ​ហ្វារ៉ូ" },
				{ LanguageId.kn, "ಫರೋ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "페로 제도" },
				{ LanguageId.kok, "फेरो जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "فارو جزیرہ" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "de Färrör-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Фарер аралдары" },
				{ LanguageId.la, "Insulae Faroe" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Färöer" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຫມູ່ເກາະແຟໂຣ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Farerų Salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Fēru salas" },
				{ LanguageId.mai, "फेरो द्वीपसमूह" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Faroe" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Motu Wharau" },
				{ LanguageId.mk, "Фарски Острови" },
				{ LanguageId.ml, "ഫറോ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Фарерын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फेरो बेटे" },
				{ LanguageId.ms, "Kepulauan Faroe" },
				{ LanguageId.mt, "il-Gżejjer Faeroe" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဖာရိုး ကျွန်းစုများ" },
				{ LanguageId.mzn, "فارو جزایر" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Færøyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फारो टापुहरू" },
				{ LanguageId.nl, "Faeröer" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Færøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߝߋߙߏߦߋ߫ ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Fafo’ee" },
				{ LanguageId.or, "ଫାରୋଇ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫੈਰੋ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Fáro Aílands" },
				{ LanguageId.pl, "Wyspy Owcze" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فارو ټاپو" },
				{ LanguageId.pt, "Ilhas Faroé" },
				{ LanguageId.qu, "Islas Feroe" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Feroe" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Feroe" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Фарерские о-ва" },
				{ LanguageId.rw, "Ibirwa bya Faroe" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "فارو ٻيٽ" },
				{ LanguageId.se, "Fearsullot" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ෆැරෝ දූපත්" },
				{ LanguageId.sk, "Faerské ostrovy" },
				{ LanguageId.sl, "Ferski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Färsuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Faroe Islands" },
				{ LanguageId.so, "Jasiiradda Faroo" },
				{ LanguageId.sq, "Ishujt Faroe" },
				{ LanguageId.sr, "Фарска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Faroe" },
				{ LanguageId.su, "Kapuloan Faroe" },
				{ LanguageId.sv, "Färöarna" },
				{ LanguageId.sw, "Visiwa vya Faroe" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܦܪܘ" },
				{ LanguageId.ta, "ஃபாரோ தீவுகள்" },
				{ LanguageId.te, "ఫారో దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Фарер" },
				{ LanguageId.th, "หมู่เกาะแฟโร" },
				{ LanguageId.ti, "ደሴታት ፋሮ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Farer adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Faloe" },
				{ LanguageId.tr, "Faroe Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Фарер утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "فارو ئاراللىرى" },
				{ LanguageId.uk, "Фарерські Острови" },
				{ LanguageId.ur, "جزائر فارو" },
				{ LanguageId.uz, "Farer orollari" },
				{ LanguageId.vai, "ꕘꖄ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Faroe" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "Färöe" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Faro" },
				{ LanguageId.xh, "EFaroe Islands" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פֿאַרא אינזלען" },
				{ LanguageId.yo, "Àwọn Erékùsù ti Faroe" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "法罗群岛" },
				{ LanguageId.zu, "i-Faroe Islands" },
			}
		);
	}
}
