using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GB
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "44",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Det Forenede Kongerige" },
				{ LanguageId.af, "Verenigde Koninkryk" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የተባበሩት የንጉሥ ግዛት" },
				{ LanguageId.ar, "المملكة المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Birləşmiş Krallıq" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Злучанае Каралеўства" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Великобритания" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "যুক্তরাজ্য" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "ujedinjeno kraljevstvo" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Regne Unit" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "United Kingdom" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Regnu Unitu" },
				{ LanguageId.cs, "Spojené království" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Deyrnas Unedig" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Großbritannien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ηνωμένο Βασίλειο" },
				{ LanguageId.en, "United Kingdom" },
				{ LanguageId.eo, "Unuiĝinta Reĝlando" },
				{ LanguageId.es, "Reino Unido" },
				{ LanguageId.et, "Ühendkuningriik" },
				{ LanguageId.eu, "Erresuma Batua" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "انگلستان" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Yhdistynyt kuningaskunta" },
				{ LanguageId.fil, "United Kingdom" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Royaume-Uni" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Feriene Keninkryk" },
				{ LanguageId.ga, "an Ríocht Aontaithe" },
				{ LanguageId.gd, "An Rìoghachd Aonaichte" },
				{ LanguageId.gl, "Reino Unido" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "યુનાઇટેડ કિંગડમ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Ƙasar Ingila" },
				{ LanguageId.haw, "Aupuni Mōʻī Hui Pū ʻia" },
				{ LanguageId.he, "הממלכה המאוחדת" },
				{ LanguageId.hi, "यूनाइटेड किंगडम" },
				{ LanguageId.hr, "Ujedinjeno Kraljevstvo" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Egyesült Királyság" },
				{ LanguageId.hy, "Միացյալ թագավորություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Britania Raya" },
				{ LanguageId.ig, "United Kingdom" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bretland" },
				{ LanguageId.it, "Regno Unito" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "イギリス" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Inggris Raya" },
				{ LanguageId.ka, "გაერთიანებული სამეფო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Біріккен корольдігі" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ចក្រភពអង់គ្លេស" },
				{ LanguageId.kn, "ಯುನೈಟೆಡ್ ಕಿಂಗ್ಡಮ್" },
				{ LanguageId.ko, "영국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Бириккен королдук" },
				{ LanguageId.la, "regnum Unitum" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Vereenegt Kinnekräich" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສະຫະລາຊະອານາຈັກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jungtinė Karalystė" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Apvienotā Karaliste" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "fanjakana mitambatra" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "United Kingdom" },
				{ LanguageId.mk, "Обединето Кралство" },
				{ LanguageId.ml, "യുണൈറ്റഡ് കിംഗ്ഡം" },
				{ LanguageId.mn, "Их Британи" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "युनायटेड किंगडम" },
				{ LanguageId.ms, "United Kingdom" },
				{ LanguageId.mt, "Ir-Renju Unit" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ယူနိုက်တက်ကင်းဒမ်း" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Storbritannia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "युनाइटेड किंगडम" },
				{ LanguageId.nl, "Verenigd Koninkrijk" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଇଂଗଲାଣ୍ଡ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਯੁਨਾਇਟੇਡ ਕਿਂਗਡਮ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Zjednoczone Królestwo" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "انګلستان" },
				{ LanguageId.pt, "Reino Unido" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Regatul Unit" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Великобритания" },
				{ LanguageId.rw, "Ubwongereza" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "برطانيه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "එක්සත් රාජධානිය" },
				{ LanguageId.sk, "Spojene kralovstvo" },
				{ LanguageId.sl, "Združeno kraljestvo" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Nyika dzakabatana" },
				{ LanguageId.so, "Boqortooyada Ingiriiska" },
				{ LanguageId.sq, "Mbretëria e Bashkuar" },
				{ LanguageId.sr, "Велика Британија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "united kingdom" },
				{ LanguageId.su, "karajaan Inggris" },
				{ LanguageId.sv, "Storbritannien" },
				{ LanguageId.sw, "Uingereza" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஐக்கிய இராச்சியம்" },
				{ LanguageId.te, "యునైటెడ్ కింగ్‌డమ్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Инглистон" },
				{ LanguageId.th, "ประเทศอังกฤษ" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Angliýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Birleşik Krallık" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Берләшкән Корольлек" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "United Kingdom" },
				{ LanguageId.uk, "Об'єднане Королівство" },
				{ LanguageId.ur, "متحدہ سلطنت یونائیٹڈ کنگڈم" },
				{ LanguageId.uz, "Birlashgan Qirollik" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Vương quốc Anh" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iunited kingdom" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פֿאַראייניקטע מלכות" },
				{ LanguageId.yo, "apapọ ijọba gẹẹsi" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "英国" },
				{ LanguageId.zu, "i-United Kingdom" },
			}
		);
	}
}
