// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GB
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "44",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Storbritannien" },
				{ LanguageId.af, "Verenigde Koninkryk" },
				{ LanguageId.agq, "Yùnaetɛ Kiŋdɔ̀m" },
				{ LanguageId.ak, "UK" },
				{ LanguageId.am, "ዩናይትድ ኪንግደም" },
				{ LanguageId.ar, "المملكة المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "সংযুক্ত ৰাজ্য" },
				{ LanguageId.asa, "Uingeredha" },
				{ LanguageId.ast, "Reinu Xuníu" },
				{ LanguageId.az, "Birləşmiş Krallıq" },
				{ LanguageId.ba, "Бөйөк Британия" },
				{ LanguageId.bas, "Àdnà i Lɔ̂ŋ" },
				{ LanguageId.be, "Вялікабрытанія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huuingereza" },
				{ LanguageId.bg, "Обединеното кралство" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Angilɛtɛri" },
				{ LanguageId.bn, "যুক্তরাজ্য" },
				{ LanguageId.bo, "དབྱིན་ཇི་" },
				{ LanguageId.br, "Rouantelezh-Unanet" },
				{ LanguageId.brx, "जथाय ब्रिटिश हादोर" },
				{ LanguageId.bs, "Ujedinjeno Kraljevstvo" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Regne Unit" },
				{ LanguageId.ccp, "𑄎𑄧𑄙𑄢𑄬𑄌𑄴𑄎𑄮" },
				{ LanguageId.ce, "Йоккха Британи" },
				{ LanguageId.ceb, "United Kingdom" },
				{ LanguageId.cgg, "Bungyereza" },
				{ LanguageId.chr, "ᎩᎵᏏᏲ" },
				{ LanguageId.ckb, "شانشینی یەکگرتوو" },
				{ LanguageId.co, "Regnu Unitu" },
				{ LanguageId.cs, "Spojené království" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Deyrnas Unedig" },
				{ LanguageId.dav, "Uingereza" },
				{ LanguageId.de, "Vereinigtes Königreich" },
				{ LanguageId.dje, "Albaasalaama Marganta" },
				{ LanguageId.doi, "यूनाइटेड किंगडम" },
				{ LanguageId.dsb, "Zjadnośone kralejstwo" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཡུ་ནཱའི་ཊེཌ་ ཀིང་ཌམ" },
				{ LanguageId.ebu, "Uingereza" },
				{ LanguageId.ee, "United Kingdom nutome" },
				{ LanguageId.el, "Ηνωμένο Βασίλειο" },
				{ LanguageId.en, "United Kingdom" },
				{ LanguageId.eo, "Unuiĝinta Reĝlando" },
				{ LanguageId.es, "Reino Unido" },
				{ LanguageId.et, "Ühendkuningriik" },
				{ LanguageId.eu, "Erresuma Batua" },
				{ LanguageId.ewo, "Ǹnam Engəlis" },
				{ LanguageId.fa, "بریتانیا" },
				{ LanguageId.ff, "Laamateeri Rentundi" },
				{ LanguageId.fi, "Iso-Britannia" },
				{ LanguageId.fil, "United Kingdom" },
				{ LanguageId.fo, "Stórabretland" },
				{ LanguageId.fr, "Royaume-Uni" },
				{ LanguageId.fur, "Ream unît" },
				{ LanguageId.fy, "Verenigd Koninkrijk" },
				{ LanguageId.ga, "an Ríocht Aontaithe" },
				{ LanguageId.gd, "An Rìoghachd Aonaichte" },
				{ LanguageId.gl, "Reino Unido" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Veräinigts Chönigriich" },
				{ LanguageId.gu, "યુનાઇટેડ કિંગડમ" },
				{ LanguageId.guz, "Uingereza" },
				{ LanguageId.gv, "Rywvaneth Unys" },
				{ LanguageId.ha, "Biritaniya" },
				{ LanguageId.haw, "Aupuni Mōʻī Hui Pū ʻIa" },
				{ LanguageId.he, "בריטניה" },
				{ LanguageId.hi, "यूनाइटेड किंगडम" },
				{ LanguageId.hr, "Ujedinjeno Kraljevstvo" },
				{ LanguageId.hsb, "Zjednoćene kralestwo" },
				{ LanguageId.hu, "Egyesült Királyság" },
				{ LanguageId.hy, "Միացյալ Թագավորություն" },
				{ LanguageId.ia, "Regno Unite" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Inggris Raya" },
				{ LanguageId.ig, "United Kingdom" },
				{ LanguageId.ii, "ꑱꇩ" },
				{ LanguageId.@is, "Bretland" },
				{ LanguageId.it, "Regno Unito" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "イギリス" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Uingereza" },
				{ LanguageId.jv, "Karajan Manunggal" },
				{ LanguageId.ka, "გაერთიანებული სამეფო" },
				{ LanguageId.kab, "Tagelda Yedduklen" },
				{ LanguageId.kam, "Uingereza" },
				{ LanguageId.kde, "Nngalesa" },
				{ LanguageId.kea, "Reinu Unidu" },
				{ LanguageId.khq, "Albaasalaama Marganta" },
				{ LanguageId.ki, "Ngeretha" },
				{ LanguageId.kk, "Ұлыбритания" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Kibagenge nebo Uingereza" },
				{ LanguageId.km, "ចក្រភព​អង់គ្លេស" },
				{ LanguageId.kn, "ಯುನೈಟೆಡ್ ಕಿಂಗ್‌ಡಮ್" },
				{ LanguageId.ko, "영국" },
				{ LanguageId.kok, "युनायटेड किंगडम" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "متحدہ مملِکت" },
				{ LanguageId.ksb, "Uingeeza" },
				{ LanguageId.ksf, "kǝlɔŋ kǝ kǝtáatáaŋzǝn" },
				{ LanguageId.ksh, "Jruußbrettannije" },
				{ LanguageId.kw, "Rywvaneth Unys" },
				{ LanguageId.ky, "Улуу Британия" },
				{ LanguageId.la, "regnum Unitum" },
				{ LanguageId.lag, "Ʉɨngeréesa" },
				{ LanguageId.lb, "Groussbritannien" },
				{ LanguageId.lg, "Bungereza" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Angɛlɛtɛ́lɛ" },
				{ LanguageId.lo, "ສະຫະລາດຊະອະນາຈັກ" },
				{ LanguageId.lrc, "بیریتانیا گأپ" },
				{ LanguageId.lt, "Jungtinė Karalystė" },
				{ LanguageId.luo, "United Kingdom" },
				{ LanguageId.luy, "Uingereza" },
				{ LanguageId.lv, "Apvienotā Karaliste" },
				{ LanguageId.mai, "यूनाइटेड किंगडम" },
				{ LanguageId.mas, "Uingereza" },
				{ LanguageId.mer, "Ngeretha" },
				{ LanguageId.mfe, "United Kingdom" },
				{ LanguageId.mg, "Angletera" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Hononga o Piritene" },
				{ LanguageId.mk, "Обединето Кралство" },
				{ LanguageId.ml, "യുണൈറ്റഡ് കിംഗ്ഡം" },
				{ LanguageId.mn, "Их Британи" },
				{ LanguageId.mni, "য়ুনাইটেদ কিংদম" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "युनायटेड किंगडम" },
				{ LanguageId.ms, "United Kingdom" },
				{ LanguageId.mt, "ir-Renju Unit" },
				{ LanguageId.mua, "Sǝr Anglofoŋ" },
				{ LanguageId.my, "ယူနိုက်တက်ကင်းဒမ်း" },
				{ LanguageId.mzn, "بریتانیا" },
				{ LanguageId.naq, "United Kingdom" },
				{ LanguageId.nb, "Storbritannia" },
				{ LanguageId.nd, "United Kingdom" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त अधिराज्य" },
				{ LanguageId.nl, "Verenigd Koninkrijk" },
				{ LanguageId.nmg, "Nlambɔ́ Ngɛlɛn" },
				{ LanguageId.nn, "Storbritannia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߊ߲߬ߛߊ߬ߟߊ߫ ߟߊߘߍ߬ߣߍ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Bungyereza" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "United Kingdom" },
				{ LanguageId.or, "ଯୁକ୍ତରାଜ୍ୟ" },
				{ LanguageId.os, "Стыр Британи" },
				{ LanguageId.pa, "ਯੂਨਾਈਟਡ ਕਿੰਗਡਮ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Yunáítẹ́d Kíndọm" },
				{ LanguageId.pl, "Wielka Brytania" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "برتانیه" },
				{ LanguageId.pt, "Reino Unido" },
				{ LanguageId.qu, "Reino Unido" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Reginavel Unì" },
				{ LanguageId.rn, "Ubwongereza" },
				{ LanguageId.ro, "Regatul Unit" },
				{ LanguageId.rof, "Uingereza" },
				{ LanguageId.ru, "Великобритания" },
				{ LanguageId.rw, "Ubwongereza" },
				{ LanguageId.rwk, "Uingereza" },
				{ LanguageId.sa, "संयुक्त राष्ट्र:" },
				{ LanguageId.sah, "Улуу Британия" },
				{ LanguageId.saq, "Uingereza" },
				{ LanguageId.sat, "ᱭᱩᱱᱤᱭᱴᱮᱰ ᱠᱤᱝᱰᱚᱢ" },
				{ LanguageId.sbp, "Uwingelesa" },
				{ LanguageId.sd, "برطانيہ" },
				{ LanguageId.se, "Stuorra-Británnia" },
				{ LanguageId.seh, "Reino Unido" },
				{ LanguageId.ses, "Albaasalaama Marganta" },
				{ LanguageId.sg, "Ködörögbïä--Ôko" },
				{ LanguageId.shi, "ⵜⴰⴳⵍⴷⵉⵜ ⵉⵎⵓⵏⵏ" },
				{ LanguageId.si, "එක්සත් රාජධානිය" },
				{ LanguageId.sk, "Spojené kráľovstvo" },
				{ LanguageId.sl, "Združeno kraljestvo" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Ovtâstum Kunâgâskodde" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "United Kingdom" },
				{ LanguageId.so, "Boqortooyada Midowday" },
				{ LanguageId.sq, "Mbretëria e Bashkuar" },
				{ LanguageId.sr, "Уједињено Краљевство" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "united kingdom" },
				{ LanguageId.su, "Britania Raya" },
				{ LanguageId.sv, "Storbritannien" },
				{ LanguageId.sw, "Ufalme wa Muungano" },
				{ LanguageId.syr, "ܡܠܟܘܬܐ ܡܚܝܕܬܐ" },
				{ LanguageId.ta, "யுனைடெட் கிங்டம்" },
				{ LanguageId.te, "యునైటెడ్ కింగ్‌డమ్" },
				{ LanguageId.teo, "Uingereza" },
				{ LanguageId.tg, "Шоҳигарии Муттаҳида" },
				{ LanguageId.th, "สหราชอาณาจักร" },
				{ LanguageId.ti, "ብሪጣንያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Birleşen Patyşalyk" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Pilitānia" },
				{ LanguageId.tr, "Birleşik Krallık" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Берләшкән Корольлек" },
				{ LanguageId.twq, "Albaasalaama Marganta" },
				{ LanguageId.tzm, "Tagelda Taddukelt" },
				{ LanguageId.ug, "بىرلەشمە پادىشاھلىق" },
				{ LanguageId.uk, "Велика Британія" },
				{ LanguageId.ur, "سلطنت متحدہ" },
				{ LanguageId.uz, "Buyuk Britaniya" },
				{ LanguageId.vai, "ꖕꕯꔤꗳ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Vương quốc Anh" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Uingereza" },
				{ LanguageId.wae, "England" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Ruwaayom Ini" },
				{ LanguageId.xh, "E-United Kingdom" },
				{ LanguageId.xog, "Bungereza" },
				{ LanguageId.yav, "ingilíís" },
				{ LanguageId.yi, "פֿאַראייניגטע קעניגרייך" },
				{ LanguageId.yo, "Gẹ̀ẹ́sì" },
				{ LanguageId.zgh, "ⵜⴰⴳⵍⴷⵉⵜ ⵉⵎⵓⵏⵏ" },
				{ LanguageId.zh, "英国" },
				{ LanguageId.zu, "i-United Kingdom" },
			}
		);
	}
}
