// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "594",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "French Guiana" },
				{ LanguageId.da, "Fransk Guyana" },
				{ LanguageId.af, "Frans-Guyana" },
				{ LanguageId.agq, "Gàyanà è Fàlâŋnsì" },
				{ LanguageId.ak, "Frɛnkye Gayana" },
				{ LanguageId.am, "የፈረንሳይ ጉዊአና" },
				{ LanguageId.ar, "غويانا الفرنسية" },
				{ LanguageId.arn, "French Guiana" },
				{ LanguageId.@as, "ফ্ৰান্স গয়ানা" },
				{ LanguageId.asa, "Gwiyana ya Ufarantha" },
				{ LanguageId.ast, "Guyana Francesa" },
				{ LanguageId.az, "Fransa Qvianası" },
				{ LanguageId.ba, "Француз Гвианаһы" },
				{ LanguageId.bas, "Gùyanà Pùlàsi" },
				{ LanguageId.be, "Французская Гвіяна" },
				{ LanguageId.bem, "French Guiana" },
				{ LanguageId.bez, "Hugwiyana ya Huufaransa" },
				{ LanguageId.bg, "Френска Гвиана" },
				{ LanguageId.bin, "French Guiana" },
				{ LanguageId.bm, "Faransi ka gwiyani" },
				{ LanguageId.bn, "ফরাসী গায়ানা" },
				{ LanguageId.bo, "ཕ་རན་སིའི་གུ་ཡ་ན" },
				{ LanguageId.br, "Gwiana cʼhall" },
				{ LanguageId.brx, "फ्रेन्च गिआना" },
				{ LanguageId.bs, "Francuska Gvajana" },
				{ LanguageId.byn, "French Guiana" },
				{ LanguageId.ca, "Guaiana Francesa" },
				{ LanguageId.ccp, "𑄜𑄧𑄢𑄥𑄩 𑄉𑄠𑄚" },
				{ LanguageId.ce, "Французийн Гвиана" },
				{ LanguageId.ceb, "French Guiana" },
				{ LanguageId.cgg, "Guyana ya Bufaransa" },
				{ LanguageId.chr, "ᎠᏂᎦᎸᏥ ᎩᎠ" },
				{ LanguageId.ckb, "گیانای فەرەنسا" },
				{ LanguageId.co, "Guyana francese" },
				{ LanguageId.cs, "Francouzská Guyana" },
				{ LanguageId.cu, "Франкїискаꙗ Гвїана" },
				{ LanguageId.cy, "Guyane Ffrengig" },
				{ LanguageId.dav, "Gwiyana ya Ufaransa" },
				{ LanguageId.de, "Französisch-Guayana" },
				{ LanguageId.dje, "Faransi Guyaan" },
				{ LanguageId.doi, "फ्रांसीसी गयाना" },
				{ LanguageId.dsb, "Francojska Guyana" },
				{ LanguageId.dua, "French Guiana" },
				{ LanguageId.dv, "ފަރަންސޭސި ގީނާ" },
				{ LanguageId.dz, "གུའི་ཡ་ན་ ཕྲནས྄་མངའ་ཁོངས" },
				{ LanguageId.ebu, "Gwiyana ya Ufaransa" },
				{ LanguageId.ee, "Frentsi Gayana nutome" },
				{ LanguageId.el, "Γαλλική Γουιάνα" },
				{ LanguageId.en, "French Guiana" },
				{ LanguageId.eo, "Franca Gujano" },
				{ LanguageId.es, "Guayana Francesa" },
				{ LanguageId.et, "Prantsuse Guajaana" },
				{ LanguageId.eu, "Guyana Frantsesa" },
				{ LanguageId.ewo, "Guyán yá Fulɛnsí" },
				{ LanguageId.fa, "گویان فرانسه" },
				{ LanguageId.ff, "Giyaan Farayse" },
				{ LanguageId.fi, "Ranskan Guayana" },
				{ LanguageId.fil, "French Guiana" },
				{ LanguageId.fo, "Franska Gujana" },
				{ LanguageId.fr, "Guyane française" },
				{ LanguageId.fur, "Guiana francês" },
				{ LanguageId.fy, "Frans-Guyana" },
				{ LanguageId.ga, "Guáin na Fraince" },
				{ LanguageId.gd, "Guidheàna na Frainge" },
				{ LanguageId.gl, "Güiana Francesa" },
				{ LanguageId.gn, "Guyana Francesa" },
				{ LanguageId.gsw, "Französisch-Guäjaana" },
				{ LanguageId.gu, "ફ્રેંચ ગયાના" },
				{ LanguageId.guz, "Gwiyana ya Ufaransa" },
				{ LanguageId.gv, "Geeaaney ny Frank" },
				{ LanguageId.ha, "Gini Ta Faransa" },
				{ LanguageId.haw, "Guiana Palani" },
				{ LanguageId.he, "גיאנה הצרפתית" },
				{ LanguageId.hi, "फ़्रेंच गुयाना" },
				{ LanguageId.hr, "Francuska Gijana" },
				{ LanguageId.hsb, "Francoska Guyana" },
				{ LanguageId.hu, "Francia Guyana" },
				{ LanguageId.hy, "Ֆրանսիական Գվիանա" },
				{ LanguageId.ia, "Guyana francese" },
				{ LanguageId.ibb, "French Guiana" },
				{ LanguageId.id, "Guyana Prancis" },
				{ LanguageId.ig, "French Guiana" },
				{ LanguageId.ii, "ꃔꇩꌦꀉꆆ" },
				{ LanguageId.@is, "Franska Gvæjana" },
				{ LanguageId.it, "Guyana Francese" },
				{ LanguageId.iu, "ᐃᓄᐃᑦ ᑲᐃᐊᓇ" },
				{ LanguageId.ja, "仏領ギアナ" },
				{ LanguageId.jgo, "French Guiana" },
				{ LanguageId.jmc, "Gwiyana ya Ufaransa" },
				{ LanguageId.jv, "Guyana Prancis" },
				{ LanguageId.ka, "საფრანგეთის გვიანა" },
				{ LanguageId.kab, "Ɣana tafransist" },
				{ LanguageId.kam, "Gwiyana ya Ufaransa" },
				{ LanguageId.kde, "Gwiyana ya Ufalansa" },
				{ LanguageId.kea, "Giana Franseza" },
				{ LanguageId.khq, "Faransi Guyaan" },
				{ LanguageId.ki, "Gwiyana ya Ufaransa" },
				{ LanguageId.kk, "Француз Гвианасы" },
				{ LanguageId.kkj, "French Guiana" },
				{ LanguageId.kl, "Frankrigi Guiana" },
				{ LanguageId.kln, "Emetab Guiana nebo Ufaransa" },
				{ LanguageId.km, "ហ្គីអាណា បារាំង" },
				{ LanguageId.kn, "ಫ್ರೆಂಚ್ ಗಯಾನಾ" },
				{ LanguageId.ko, "프랑스령 기아나" },
				{ LanguageId.kok, "फ्रांसेझ गियॅना" },
				{ LanguageId.kr, "French Guiana" },
				{ LanguageId.ks, "فرانسِسی گِانا" },
				{ LanguageId.ksb, "Gwiyana ya Ufalansa" },
				{ LanguageId.ksf, "guyán i pɛrɛsǝ́" },
				{ LanguageId.ksh, "Franzüüsesch Jujaana" },
				{ LanguageId.kw, "Giana Frynkek" },
				{ LanguageId.ky, "Франция Гвианасы" },
				{ LanguageId.la, "Guiana" },
				{ LanguageId.lag, "Gwiyáana yʉ Ʉfaráansa" },
				{ LanguageId.lb, "Guayane" },
				{ LanguageId.lg, "Guyana enfalansa" },
				{ LanguageId.lkt, "French Guiana" },
				{ LanguageId.ln, "Giyanɛ ya Falánsɛ" },
				{ LanguageId.lo, "ເຟຣນຊ໌ ກຸຍອານາ" },
				{ LanguageId.lrc, "گویانا فرانسە" },
				{ LanguageId.lt, "Prancūzijos Gviana" },
				{ LanguageId.luo, "French Guiana" },
				{ LanguageId.luy, "Gwiyana ya Ufaransa" },
				{ LanguageId.lv, "Francijas Gviāna" },
				{ LanguageId.mai, "फ्रेंच गुयाना" },
				{ LanguageId.mas, "Gwiyana ya Ufaransa" },
				{ LanguageId.mer, "Gwiyana ya Fransi" },
				{ LanguageId.mfe, "Gwiyann franse" },
				{ LanguageId.mg, "Guyana frantsay" },
				{ LanguageId.mgo, "French Guiana" },
				{ LanguageId.mi, "Kiāna Wīwī" },
				{ LanguageId.mk, "Француска Гвајана" },
				{ LanguageId.ml, "ഫ്രഞ്ച് ഗയാന" },
				{ LanguageId.mn, "Францын Гвиана" },
				{ LanguageId.mni, "ফ্রেঞ্চ গায়ানা" },
				{ LanguageId.moh, "French Guiana" },
				{ LanguageId.mr, "फ्रेंच गयाना" },
				{ LanguageId.ms, "Guiana Perancis" },
				{ LanguageId.mt, "il-Guyana Franċiża" },
				{ LanguageId.mua, "Sǝr Guyana ma Franssǝ" },
				{ LanguageId.my, "ပြင်သစ် ဂီယာနာ" },
				{ LanguageId.mzn, "فرانسه‌ی ِگویان" },
				{ LanguageId.naq, "French Guiana" },
				{ LanguageId.nb, "Fransk Guyana" },
				{ LanguageId.nd, "Gwiyana ye Furansi" },
				{ LanguageId.nds, "Franzöösch-Guayana" },
				{ LanguageId.ne, "फ्रान्सेली गायना" },
				{ LanguageId.nl, "Frans-Guyana" },
				{ LanguageId.nmg, "Guyane Fala" },
				{ LanguageId.nn, "Fransk Guyana" },
				{ LanguageId.nnh, "French Guiana" },
				{ LanguageId.nqo, "ߝߊ߲߬ߙߊ߲߬ߛߌ߫ ߜ߭ߎ߳ߦߊߣ" },
				{ LanguageId.nr, "French Guiana" },
				{ LanguageId.nso, "French Guiana" },
				{ LanguageId.nus, "French Guiana" },
				{ LanguageId.nyn, "Guyana ya Bufaransa" },
				{ LanguageId.oc, "Guaiana Francesa" },
				{ LanguageId.om, "Faransaay Guyiinaa" },
				{ LanguageId.or, "ଫ୍ରେଞ୍ଚ ଗୁଇନା" },
				{ LanguageId.os, "Францаг Гвиана" },
				{ LanguageId.pa, "ਫਰੈਂਚ ਗੁਇਆਨਾ" },
				{ LanguageId.pap, "Guyana Franses" },
				{ LanguageId.pcm, "Frẹ́nch Giána" },
				{ LanguageId.pl, "Gujana Francuska" },
				{ LanguageId.prg, "Prancūzijas Gviana" },
				{ LanguageId.ps, "فرانسوي ګانا" },
				{ LanguageId.pt, "Guiana Francesa" },
				{ LanguageId.qu, "Guayana Francesa" },
				{ LanguageId.quc, "French Guiana" },
				{ LanguageId.rm, "Guyana Franzosa" },
				{ LanguageId.rn, "Gwayana y’Abafaransa" },
				{ LanguageId.ro, "Guyana Franceză" },
				{ LanguageId.rof, "Gwiyana ya Ufaransa" },
				{ LanguageId.ru, "Французская Гвиана" },
				{ LanguageId.rw, "Igifaransa Guiana" },
				{ LanguageId.rwk, "Gwiyana ya Ufaransa" },
				{ LanguageId.sa, "फ्रांसीसी गयाना" },
				{ LanguageId.sah, "Француз Гвианата" },
				{ LanguageId.saq, "Gwiyana ya Ufaransa" },
				{ LanguageId.sat, "ᱯᱷᱨᱮᱸᱪ ᱜᱩᱭᱟᱱᱟ" },
				{ LanguageId.sbp, "Gwiyana ya Wufalansa" },
				{ LanguageId.sd, "فرانسيسي گيانا" },
				{ LanguageId.se, "Frankriikka Guayana" },
				{ LanguageId.seh, "Guiana Francesa" },
				{ LanguageId.ses, "Faransi Guyaan" },
				{ LanguageId.sg, "Güyâni tî farânzi" },
				{ LanguageId.shi, "ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.si, "ප්‍රංශ ගයනාව" },
				{ LanguageId.sk, "Francúzska Guyana" },
				{ LanguageId.sl, "Francoska Gvajana" },
				{ LanguageId.sma, "Franskalándda Guyana" },
				{ LanguageId.smj, "Franska Guyana" },
				{ LanguageId.smn, "Ranska Guyana" },
				{ LanguageId.sms, "Prantsksarnn Guyana" },
				{ LanguageId.sn, "French Guiana" },
				{ LanguageId.so, "Faransiis Gini" },
				{ LanguageId.sq, "Guajana Franceze" },
				{ LanguageId.sr, "Француска Гвајана" },
				{ LanguageId.ss, "French Guiana" },
				{ LanguageId.ssy, "French Guiana" },
				{ LanguageId.st, "French Guiana" },
				{ LanguageId.su, "Guyana Perancis" },
				{ LanguageId.sv, "Franska Guyana" },
				{ LanguageId.sw, "Guiana ya Ufaransa" },
				{ LanguageId.syr, "ܓܘܝܐܢܐ ܦܪܢܣܝܬܐ" },
				{ LanguageId.ta, "பிரெஞ்சு கயானா" },
				{ LanguageId.te, "ఫ్రెంచ్ గియానా" },
				{ LanguageId.teo, "Gwiyana ya Ufaransa" },
				{ LanguageId.tg, "Гвианаи Фаронса" },
				{ LanguageId.th, "เฟรนช์เกียนา" },
				{ LanguageId.ti, "ፈረንሳዊት ጊያና" },
				{ LanguageId.tig, "ፈረንሳዊት ጊያና" },
				{ LanguageId.tk, "Fransuz Gwianasy" },
				{ LanguageId.tn, "French Guiana" },
				{ LanguageId.to, "Kuiana fakafalanisē" },
				{ LanguageId.tr, "Fransız Guyanası" },
				{ LanguageId.ts, "French Guiana" },
				{ LanguageId.tt, "Француз Гвианасы" },
				{ LanguageId.twq, "Faransi Guyaan" },
				{ LanguageId.tzm, "Guyana Tafransist" },
				{ LanguageId.ug, "فىرانسىيەگە قاراشلىق گىۋىيانا" },
				{ LanguageId.uk, "Французька Гвіана" },
				{ LanguageId.ur, "فرینچ گیانا" },
				{ LanguageId.uz, "Fransuz Gvianasi" },
				{ LanguageId.vai, "ꗱꘋꔻ ꖶꕎꕯ" },
				{ LanguageId.ve, "French Guiana" },
				{ LanguageId.vi, "Guiana thuộc Pháp" },
				{ LanguageId.vo, "Gvayän Fransänik" },
				{ LanguageId.vun, "Gwiyana ya Ufaransa" },
				{ LanguageId.wae, "Französiš Guiana" },
				{ LanguageId.wal, "የፈረንሳይ ጉያና" },
				{ LanguageId.wo, "Guyaan Farañse" },
				{ LanguageId.xh, "EFrench Guiana" },
				{ LanguageId.xog, "Guyana enfalansa" },
				{ LanguageId.yav, "kuyáan u felensí" },
				{ LanguageId.yi, "פֿראַנצויזישע גויאַנע" },
				{ LanguageId.yo, "Firenṣi Guana" },
				{ LanguageId.zgh, "ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.zh, "法属圭亚那" },
				{ LanguageId.zu, "i-French Guiana" },
			}
		);
	}
}
