using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "594",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "French Guiana" },
				{ LanguageId.da, "Fransk Guyana" },
				{ LanguageId.af, "Frans Guyana" },
				{ LanguageId.agq, "French Guiana" },
				{ LanguageId.ak, "French Guiana" },
				{ LanguageId.am, "የፈረንሳይ ጉያና" },
				{ LanguageId.ar, "غيانا الفرنسية" },
				{ LanguageId.arn, "French Guiana" },
				{ LanguageId.@as, "ফৰাচী গায়ানা" },
				{ LanguageId.asa, "French Guiana" },
				{ LanguageId.ast, "Guyana Francesa" },
				{ LanguageId.az, "Fransız Qvianası" },
				{ LanguageId.ba, "Франция Гвианаһы" },
				{ LanguageId.bas, "French Guiana" },
				{ LanguageId.be, "Французская Гвіяна" },
				{ LanguageId.bem, "French Guiana" },
				{ LanguageId.bez, "French Guiana" },
				{ LanguageId.bg, "Френска Гвиана" },
				{ LanguageId.bin, "French Guiana" },
				{ LanguageId.bm, "French Guiana" },
				{ LanguageId.bn, "একটি দেশের নাম" },
				{ LanguageId.bo, "ཕ་རན་སིའི་གུ་ཡ་ན" },
				{ LanguageId.br, "Gwiana C'hall" },
				{ LanguageId.brx, "फ्रान्सिसि गुयाना" },
				{ LanguageId.bs, "Francuska Gvajana" },
				{ LanguageId.byn, "French Guiana" },
				{ LanguageId.ca, "Guaiana Francesa" },
				{ LanguageId.ccp, "𑄜𑄳𑄢𑄚𑄴𑄌𑄧 𑄉𑄪𑄠𑄚" },
				{ LanguageId.ce, "Французийн Гвиана" },
				{ LanguageId.ceb, "French Guiana" },
				{ LanguageId.cgg, "French Guiana" },
				{ LanguageId.chr, "ᎦᎸᏥ ᎩᎠᎾ" },
				{ LanguageId.ckb, "گویانای فەڕەنسا" },
				{ LanguageId.co, "Guyana francese" },
				{ LanguageId.cs, "Francouzská Guyana" },
				{ LanguageId.cu, "Франкїискаꙗ Гвїана" },
				{ LanguageId.cy, "Guiana Ffrengig" },
				{ LanguageId.dav, "French Guiana" },
				{ LanguageId.de, "Französisch-Guayana" },
				{ LanguageId.dje, "French Guiana" },
				{ LanguageId.doi, "फ्रांसीसी गयाना" },
				{ LanguageId.dsb, "Francojska Guyana" },
				{ LanguageId.dua, "French Guiana" },
				{ LanguageId.dv, "ފަރަންސޭސި ގީނާ" },
				{ LanguageId.dz, "ཕྲནཅ་གི་གུ་ཡ་ན" },
				{ LanguageId.ebu, "French Guiana" },
				{ LanguageId.ee, "French Guiana" },
				{ LanguageId.el, "Γαλλική Γουιάνα" },
				{ LanguageId.en, "French Guiana" },
				{ LanguageId.eo, "Franca Gujano" },
				{ LanguageId.es, "Guayana Francesa" },
				{ LanguageId.et, "Prantsuse Guajaana" },
				{ LanguageId.eu, "Guyana Frantsesa" },
				{ LanguageId.ewo, "French Guiana" },
				{ LanguageId.fa, "گویان فرانسه" },
				{ LanguageId.ff, "Gini Farayse" },
				{ LanguageId.fi, "Ranskan Guayana" },
				{ LanguageId.fil, "French Guiana" },
				{ LanguageId.fo, "Franska Gujana" },
				{ LanguageId.fr, "Guyane Française" },
				{ LanguageId.fur, "Guiane francês" },
				{ LanguageId.fy, "Frânsk Guiana" },
				{ LanguageId.ga, "Guáin na Fraince" },
				{ LanguageId.gd, "Guiana Frangach" },
				{ LanguageId.gl, "Güiana Francesa" },
				{ LanguageId.gn, "Guyana Francesa" },
				{ LanguageId.gsw, "Französisch-Guayana" },
				{ LanguageId.gu, "ફ્રેન્ચ ગુયાના" },
				{ LanguageId.guz, "French Guiana" },
				{ LanguageId.gv, "Geeaaney ny Frank" },
				{ LanguageId.ha, "Faransa Guiana" },
				{ LanguageId.haw, "Guiana Palani" },
				{ LanguageId.he, "גיאנה הצרפתית" },
				{ LanguageId.hi, "फ्रेंच गयाना" },
				{ LanguageId.hr, "Francuska Gvajana" },
				{ LanguageId.hsb, "Francoska Guyana" },
				{ LanguageId.hu, "Francia Guyana" },
				{ LanguageId.hy, "Ֆրանսիական Գվիանա" },
				{ LanguageId.ia, "Guyana francese" },
				{ LanguageId.ibb, "French Guiana" },
				{ LanguageId.id, "Guyana Perancis" },
				{ LanguageId.ig, "French Guiana" },
				{ LanguageId.ii, "ꃔꇩꌦꀉꆆ" },
				{ LanguageId.@is, "Franska Gvæjana" },
				{ LanguageId.it, "Guiana francese" },
				{ LanguageId.iu, "ᐃᓄᐃᑦ ᑲᐃᐊᓇ" },
				{ LanguageId.ja, "フランス領ギアナ" },
				{ LanguageId.jgo, "French Guiana" },
				{ LanguageId.jmc, "French Guiana" },
				{ LanguageId.jv, "Guyana Prancis" },
				{ LanguageId.ka, "ფრანგული გუიანა" },
				{ LanguageId.kab, "Gwiyana tafransist" },
				{ LanguageId.kam, "French Guiana" },
				{ LanguageId.kde, "French Guiana" },
				{ LanguageId.kea, "Giana Franses" },
				{ LanguageId.khq, "French Guiana" },
				{ LanguageId.ki, "French Guiana" },
				{ LanguageId.kk, "Француз Гвианасы" },
				{ LanguageId.kkj, "French Guiana" },
				{ LanguageId.kl, "Frankrigi Guiana" },
				{ LanguageId.kln, "French Guiana" },
				{ LanguageId.km, "ហ្គីយ៉ាណាបារាំង" },
				{ LanguageId.kn, "ಫ್ರೆಂಚ್ ಗಯಾನಾ" },
				{ LanguageId.ko, "프랑스령 기아나" },
				{ LanguageId.kok, "फ्रेंच गयाना" },
				{ LanguageId.kr, "French Guiana" },
				{ LanguageId.ks, "فرانسِسی گِیانا" },
				{ LanguageId.ksb, "French Guiana" },
				{ LanguageId.ksf, "French Guiana" },
				{ LanguageId.ksh, "Französisch-Guayana" },
				{ LanguageId.kw, "Giana Frynkek" },
				{ LanguageId.ky, "Француз Гвианасы" },
				{ LanguageId.la, "Guiana" },
				{ LanguageId.lag, "French Guiana" },
				{ LanguageId.lb, "Franséisch Guyana" },
				{ LanguageId.lg, "French Guiana" },
				{ LanguageId.lkt, "French Guiana" },
				{ LanguageId.ln, "Giyana ya Falánsɛ́" },
				{ LanguageId.lo, "ຝຣັ່ງກີອານາ" },
				{ LanguageId.lrc, "گویانا فرانسە" },
				{ LanguageId.lt, "Prancūzijos Gviana" },
				{ LanguageId.luo, "French Guiana" },
				{ LanguageId.luy, "French Guiana" },
				{ LanguageId.lv, "Franču Gviāna" },
				{ LanguageId.mai, "फ्रांसीसी गयाना" },
				{ LanguageId.mas, "French Guiana" },
				{ LanguageId.mer, "French Guiana" },
				{ LanguageId.mfe, "Guyan Franse" },
				{ LanguageId.mg, "Guyana frantsay" },
				{ LanguageId.mgo, "French Guiana" },
				{ LanguageId.mi, "French Guiana" },
				{ LanguageId.mk, "Француска Гвајана" },
				{ LanguageId.ml, "ഫ്രഞ്ച് ഗയാന" },
				{ LanguageId.mn, "Францын Гвиана" },
				{ LanguageId.mni, "ফ্রেঞ্চ গায়ানা" },
				{ LanguageId.moh, "French Guiana" },
				{ LanguageId.mr, "फ्रेंच गयाना" },
				{ LanguageId.ms, "Guiana Perancis" },
				{ LanguageId.mt, "Gujana Franċiża" },
				{ LanguageId.mua, "French Guiana" },
				{ LanguageId.my, "ပြင်သစ်ဂီယာနာ" },
				{ LanguageId.mzn, "فرانسه گویان" },
				{ LanguageId.naq, "French Guiana" },
				{ LanguageId.nb, "fransk Guyana" },
				{ LanguageId.nd, "French Guiana" },
				{ LanguageId.nds, "Franzöösch-Guayana" },
				{ LanguageId.ne, "फ्रान्सेली गुयाना" },
				{ LanguageId.nl, "Frans-Guyana" },
				{ LanguageId.nmg, "French Guiana" },
				{ LanguageId.nn, "Fransk Guyana" },
				{ LanguageId.nnh, "French Guiana" },
				{ LanguageId.nqo, "ߝߊ߬ߙߊ߲߬ߛߌ߫ ߖ߭ߌߦߊߣߊ߫" },
				{ LanguageId.nr, "French Guiana" },
				{ LanguageId.nso, "French Guiana" },
				{ LanguageId.nus, "French Guiana" },
				{ LanguageId.nyn, "French Guiana" },
				{ LanguageId.oc, "Guaiana Francesa" },
				{ LanguageId.om, "Guaana Faransaay" },
				{ LanguageId.or, "ଫରାସୀ ଗୁଇନା |" },
				{ LanguageId.os, "Францаг Гвиана" },
				{ LanguageId.pa, "ਫ੍ਰੈਂਚ ਗੁਆਨਾ" },
				{ LanguageId.pap, "Guyana Franses" },
				{ LanguageId.pcm, "Frẹ́nch Giána" },
				{ LanguageId.pl, "Gujana Francuska" },
				{ LanguageId.prg, "Prancūzijas Gviana" },
				{ LanguageId.ps, "فرانسوي ګیانا" },
				{ LanguageId.pt, "Guiana Francesa" },
				{ LanguageId.qu, "Phransya Guyana" },
				{ LanguageId.quc, "French Guiana" },
				{ LanguageId.rm, "Guiana franzosa" },
				{ LanguageId.rn, "Guyana y'Abafaransa" },
				{ LanguageId.ro, "Guyana Franceză" },
				{ LanguageId.rof, "French Guiana" },
				{ LanguageId.ru, "Французская Гвиана" },
				{ LanguageId.rw, "Igifaransa Guiana" },
				{ LanguageId.rwk, "French Guiana" },
				{ LanguageId.sa, "फ्रांसीसी गयाना" },
				{ LanguageId.sah, "Француз Гвианата" },
				{ LanguageId.saq, "French Guiana" },
				{ LanguageId.sat, "ᱯᱷᱨᱮᱸᱪ ᱜᱩᱭᱟᱱᱟ" },
				{ LanguageId.sbp, "French Guiana" },
				{ LanguageId.sd, "فرانسيسي گيانا" },
				{ LanguageId.se, "Frankriikka Guayana" },
				{ LanguageId.seh, "French Guiana" },
				{ LanguageId.ses, "French Guiana" },
				{ LanguageId.sg, "Guyâni tî Farânzi" },
				{ LanguageId.shi, "ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.si, "ප්රංශ ගයනා" },
				{ LanguageId.sk, "Francúzska Guiana" },
				{ LanguageId.sl, "Francoska Gvajana" },
				{ LanguageId.sma, "Franskalándda Guyana" },
				{ LanguageId.smj, "Franska Guyana" },
				{ LanguageId.smn, "Frankriikka Guayana" },
				{ LanguageId.sms, "Prantsksarnn Guyana" },
				{ LanguageId.sn, "French Guiana" },
				{ LanguageId.so, "Guiana Faransiis" },
				{ LanguageId.sq, "Guiana Franceze" },
				{ LanguageId.sr, "Француска Гвајана" },
				{ LanguageId.ss, "French Guiana" },
				{ LanguageId.ssy, "French Guiana" },
				{ LanguageId.st, "French Guiana" },
				{ LanguageId.su, "Guyana Perancis" },
				{ LanguageId.sv, "Franska Guyana" },
				{ LanguageId.sw, "Guiana ya Ufaransa" },
				{ LanguageId.syr, "ܓܘܝܐܢܐ ܦܪܢܣܝܬܐ" },
				{ LanguageId.ta, "பிரஞ்சு கயானா" },
				{ LanguageId.te, "ఫ్రెంచ్ గయానా" },
				{ LanguageId.teo, "French Guiana" },
				{ LanguageId.tg, "Гвианаи Фаронса" },
				{ LanguageId.th, "เฟรนช์เกีย" },
				{ LanguageId.ti, "ፈረንሳዊት ጊያና" },
				{ LanguageId.tig, "ፈረንሳዊት ጊያና" },
				{ LanguageId.tk, "Fransuz Gwiana" },
				{ LanguageId.tn, "French Guiana" },
				{ LanguageId.to, "Kuiana Fakafalanisē" },
				{ LanguageId.tr, "Fransız Guyanası" },
				{ LanguageId.ts, "French Guiana" },
				{ LanguageId.tt, "Француз Гвианы" },
				{ LanguageId.twq, "French Guiana" },
				{ LanguageId.tzm, "ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.ug, "French Guiana" },
				{ LanguageId.uk, "Французька Гвіана" },
				{ LanguageId.ur, "فرانسیسی گیانا" },
				{ LanguageId.uz, "Fransuz Gvianasi" },
				{ LanguageId.vai, "ꗼꗴꘋꔪ ꕉꔤꕀꕡ" },
				{ LanguageId.ve, "French Guiana" },
				{ LanguageId.vi, "Guiana thuộc Pháp" },
				{ LanguageId.vo, "Gvayän Fransänik" },
				{ LanguageId.vun, "French Guiana" },
				{ LanguageId.wae, "Französisch-Guyana" },
				{ LanguageId.wal, "የፈረንሳይ ጉያና" },
				{ LanguageId.wo, "Giyaan bu Faraas" },
				{ LanguageId.xh, "IFrench Guiana" },
				{ LanguageId.xog, "French Guiana" },
				{ LanguageId.yav, "French Guiana" },
				{ LanguageId.yi, "פראנצויזיש גיאַנאַ" },
				{ LanguageId.yo, "French Guiana" },
				{ LanguageId.zgh, "ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.zh, "法属圭亚那" },
				{ LanguageId.zu, "I-French Guiana" },
			}
		);
	}
}
