using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "594",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Fransk Guyana" },
				{ LanguageId.af, "Frans Guyana" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የፈረንሳይ ጉያና" },
				{ LanguageId.ar, "غيانا الفرنسية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Fransız Qvianası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Французская Гвіяна" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Френска Гвиана" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "একটি দেশের নাম" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Gwiana C'hall" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Francuska Gvajana" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Guaiana Francesa" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "French Guiana" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Guyana francese" },
				{ LanguageId.cs, "Francouzská Guyana" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Guiana Ffrengig" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Französisch-Guayana" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Γαλλική Γουιάνα" },
				{ LanguageId.en, "French Guiana" },
				{ LanguageId.eo, "Franca Gujano" },
				{ LanguageId.es, "Guayana Francesa" },
				{ LanguageId.et, "Prantsuse Guajaana" },
				{ LanguageId.eu, "Guyana Frantsesa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "گویان فرانسه" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Ranskan Guayana" },
				{ LanguageId.fil, "French Guiana" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Guyane Française" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Frânsk Guiana" },
				{ LanguageId.ga, "Guáin na Fraince" },
				{ LanguageId.gd, "Guiana Frangach" },
				{ LanguageId.gl, "Güiana Francesa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ફ્રેન્ચ ગુયાના" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Faransa Guiana" },
				{ LanguageId.haw, "Guiana Palani" },
				{ LanguageId.he, "גיאנה הצרפתית" },
				{ LanguageId.hi, "फ्रेंच गयाना" },
				{ LanguageId.hr, "Francuska Gvajana" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Francia Guyana" },
				{ LanguageId.hy, "Ֆրանսիական Գվիանա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Guyana Perancis" },
				{ LanguageId.ig, "French Guiana" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Franska Gvæjana" },
				{ LanguageId.it, "Guiana francese" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フランス領ギアナ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Guyana Prancis" },
				{ LanguageId.ka, "ფრანგული გუიანა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Француз Гвианасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ហ្គីយ៉ាណាបារាំង" },
				{ LanguageId.kn, "ಫ್ರೆಂಚ್ ಗಯಾನಾ" },
				{ LanguageId.ko, "프랑스령 기아나" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Француз Гвианасы" },
				{ LanguageId.la, "Guiana" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Franséisch Guyana" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຝຣັ່ງກີອານາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Prancūzijos Gviana" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Franču Gviāna" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Guyana frantsay" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "French Guiana" },
				{ LanguageId.mk, "Француска Гвајана" },
				{ LanguageId.ml, "ഫ്രഞ്ച് ഗയാന" },
				{ LanguageId.mn, "Францын Гвиана" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फ्रेंच गयाना" },
				{ LanguageId.ms, "Guiana Perancis" },
				{ LanguageId.mt, "Gujana Franċiża" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ပြင်သစ်ဂီယာနာ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "fransk Guyana" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फ्रान्सेली गुयाना" },
				{ LanguageId.nl, "Frans-Guyana" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଫରାସୀ ଗୁଇନା |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫ੍ਰੈਂਚ ਗੁਆਨਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Gujana Francuska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فرانسوي ګیانا" },
				{ LanguageId.pt, "Guiana Francesa" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Guyana Franceză" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Французская Гвиана" },
				{ LanguageId.rw, "Igifaransa Guiana" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "فرانسيسي گيانا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ප්රංශ ගයනා" },
				{ LanguageId.sk, "Francúzska Guiana" },
				{ LanguageId.sl, "Francoska Gvajana" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "French Guiana" },
				{ LanguageId.so, "Guiana Faransiis" },
				{ LanguageId.sq, "Guiana Franceze" },
				{ LanguageId.sr, "Француска Гвајана" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "French Guiana" },
				{ LanguageId.su, "Guyana Perancis" },
				{ LanguageId.sv, "Franska Guyana" },
				{ LanguageId.sw, "Guiana ya Ufaransa" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "பிரஞ்சு கயானா" },
				{ LanguageId.te, "ఫ్రెంచ్ గయానా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Гвианаи Фаронса" },
				{ LanguageId.th, "เฟรนช์เกีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Fransuz Gwiana" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Fransız Guyanası" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Француз Гвианы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "French Guiana" },
				{ LanguageId.uk, "Французька Гвіана" },
				{ LanguageId.ur, "فرانسیسی گیانا" },
				{ LanguageId.uz, "Fransuz Gvianasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Guiana thuộc Pháp" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IFrench Guiana" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פראנצויזיש גיאַנאַ" },
				{ LanguageId.yo, "French Guiana" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "法属圭亚那" },
				{ LanguageId.zu, "I-French Guiana" },
			}
		);
	}
}
