// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GI
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "350",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Gibraltar" },
				{ LanguageId.da, "Gibraltar" },
				{ LanguageId.af, "Gibraltar" },
				{ LanguageId.agq, "Dzibɨ̀latà" },
				{ LanguageId.ak, "Gyebralta" },
				{ LanguageId.am, "ጂብራልተር" },
				{ LanguageId.ar, "جبل طارق" },
				{ LanguageId.arn, "Gibraltar" },
				{ LanguageId.@as, "জিব্ৰাল্টৰ" },
				{ LanguageId.asa, "Jibralta" },
				{ LanguageId.ast, "Xibraltar" },
				{ LanguageId.az, "Cəbəllütariq" },
				{ LanguageId.ba, "Гибралтар" },
				{ LanguageId.bas, "Gìlbràtâr" },
				{ LanguageId.be, "Гібралтар" },
				{ LanguageId.bem, "Gibraltar" },
				{ LanguageId.bez, "Hujiblalta" },
				{ LanguageId.bg, "Гибралтар" },
				{ LanguageId.bin, "Gibraltar" },
				{ LanguageId.bm, "Zibralitari" },
				{ LanguageId.bn, "জিব্রাল্টার" },
				{ LanguageId.bo, "ཇིབ་རཱལ་ཊར" },
				{ LanguageId.br, "Jibraltar" },
				{ LanguageId.brx, "जिब्राल्टार" },
				{ LanguageId.bs, "Gibraltar" },
				{ LanguageId.byn, "Gibraltar" },
				{ LanguageId.ca, "Gibraltar" },
				{ LanguageId.ccp, "𑄎𑄨𑄝𑄳𑄢𑄣𑄴𑄑𑄢𑄴" },
				{ LanguageId.ce, "Гибралтар" },
				{ LanguageId.ceb, "Gibraltar" },
				{ LanguageId.cgg, "Giburaata" },
				{ LanguageId.chr, "ᏥᏆᎵᏓ" },
				{ LanguageId.ckb, "گیبرالتار" },
				{ LanguageId.co, "Gibraltar" },
				{ LanguageId.cs, "Gibraltar" },
				{ LanguageId.cu, "Гїбралтаръ" },
				{ LanguageId.cy, "Gibraltar" },
				{ LanguageId.dav, "Jibralta" },
				{ LanguageId.de, "Gibraltar" },
				{ LanguageId.dje, "Gibraltar" },
				{ LanguageId.doi, "जिब्राल्टर" },
				{ LanguageId.dsb, "Gibraltar" },
				{ LanguageId.dua, "Gibraltar" },
				{ LanguageId.dv, "ޖަބަލްޠާރިޤް" },
				{ LanguageId.dz, "ཇིབ་རཱལ་ཊར" },
				{ LanguageId.ebu, "Jibralta" },
				{ LanguageId.ee, "Gibraltar nutome" },
				{ LanguageId.el, "Γιβραλτάρ" },
				{ LanguageId.en, "Gibraltar" },
				{ LanguageId.eo, "Ĝibraltaro" },
				{ LanguageId.es, "Gibraltar" },
				{ LanguageId.et, "Gibraltar" },
				{ LanguageId.eu, "Gibraltar" },
				{ LanguageId.ewo, "Yiləbalatár" },
				{ LanguageId.fa, "جبل‌الطارق" },
				{ LanguageId.ff, "Jibraltaar" },
				{ LanguageId.fi, "Gibraltar" },
				{ LanguageId.fil, "Gibraltar" },
				{ LanguageId.fo, "Gibraltar" },
				{ LanguageId.fr, "Gibraltar" },
				{ LanguageId.fur, "Gjibraltar" },
				{ LanguageId.fy, "Gibraltar" },
				{ LanguageId.ga, "Giobráltar" },
				{ LanguageId.gd, "Diobraltar" },
				{ LanguageId.gl, "Xibraltar" },
				{ LanguageId.gn, "Gibraltar" },
				{ LanguageId.gsw, "Gibraltar" },
				{ LanguageId.gu, "જીબ્રાલ્ટર" },
				{ LanguageId.guz, "Jibralta" },
				{ LanguageId.gv, "Gibraaltar" },
				{ LanguageId.ha, "Jibaraltar" },
				{ LanguageId.haw, "Kipalaleka" },
				{ LanguageId.he, "גיברלטר" },
				{ LanguageId.hi, "जिब्राल्टर" },
				{ LanguageId.hr, "Gibraltar" },
				{ LanguageId.hsb, "Gibraltar" },
				{ LanguageId.hu, "Gibraltár" },
				{ LanguageId.hy, "Ջիբրալթար" },
				{ LanguageId.ia, "Gibraltar" },
				{ LanguageId.ibb, "Gibraltar" },
				{ LanguageId.id, "Gibraltar" },
				{ LanguageId.ig, "Gibraltar" },
				{ LanguageId.ii, "ꐮꀨꇁꇐ" },
				{ LanguageId.@is, "Gíbraltar" },
				{ LanguageId.it, "Gibilterra" },
				{ LanguageId.iu, "ᔨᐳᕋᓪᑕ" },
				{ LanguageId.ja, "ジブラルタル" },
				{ LanguageId.jgo, "Gibraltar" },
				{ LanguageId.jmc, "Jibralta" },
				{ LanguageId.jv, "Gibraltar" },
				{ LanguageId.ka, "გიბრალტარი" },
				{ LanguageId.kab, "Jibraltar" },
				{ LanguageId.kam, "Jibralta" },
				{ LanguageId.kde, "Diblalta" },
				{ LanguageId.kea, "Jibraltar" },
				{ LanguageId.khq, "Gibraltar" },
				{ LanguageId.ki, "Jibralta" },
				{ LanguageId.kk, "Гибралтар" },
				{ LanguageId.kkj, "Gibraltar" },
				{ LanguageId.kl, "Gibraltar" },
				{ LanguageId.kln, "Emetab Gibraltar" },
				{ LanguageId.km, "ហ្ស៊ីប្រាល់តា" },
				{ LanguageId.kn, "ಗಿಬ್ರಾಲ್ಟರ್" },
				{ LanguageId.ko, "지브롤터" },
				{ LanguageId.kok, "जिब्राल्टर" },
				{ LanguageId.kr, "Gibraltar" },
				{ LanguageId.ks, "جِبرالٹَر" },
				{ LanguageId.ksb, "Jiblalta" },
				{ LanguageId.ksf, "jibraltá" },
				{ LanguageId.ksh, "Jibralltaa" },
				{ LanguageId.kw, "Jibraltar" },
				{ LanguageId.ky, "Гибралтар" },
				{ LanguageId.la, "Gaditanum" },
				{ LanguageId.lag, "Jiburálita" },
				{ LanguageId.lb, "Gibraltar" },
				{ LanguageId.lg, "Giburalita" },
				{ LanguageId.lkt, "Gibraltar" },
				{ LanguageId.ln, "Zibatalɛ" },
				{ LanguageId.lo, "ຈິບບຣອນທາ" },
				{ LanguageId.lrc, "جەبەل تاریق" },
				{ LanguageId.lt, "Gibraltaras" },
				{ LanguageId.luo, "Gibraltar" },
				{ LanguageId.luy, "Jibralta" },
				{ LanguageId.lv, "Gibraltārs" },
				{ LanguageId.mai, "जिब्राल्टर" },
				{ LanguageId.mas, "Jibralta" },
				{ LanguageId.mer, "Ngĩbrata" },
				{ LanguageId.mfe, "Zibraltar" },
				{ LanguageId.mg, "Zibraltara" },
				{ LanguageId.mgo, "Gibraltar" },
				{ LanguageId.mi, "Kāmaka" },
				{ LanguageId.mk, "Гибралтар" },
				{ LanguageId.ml, "ജിബ്രാൾട്ടർ" },
				{ LanguageId.mn, "Гибралтар" },
				{ LanguageId.mni, "জিব্রাল্টার" },
				{ LanguageId.moh, "Gibraltar" },
				{ LanguageId.mr, "जिब्राल्टर" },
				{ LanguageId.ms, "Gibraltar" },
				{ LanguageId.mt, "Ġibiltà" },
				{ LanguageId.mua, "Sǝr Gibraltar" },
				{ LanguageId.my, "ဂျီဘရော်လ်တာ" },
				{ LanguageId.mzn, "جبل طارق" },
				{ LanguageId.naq, "Gibraltar" },
				{ LanguageId.nb, "Gibraltar" },
				{ LanguageId.nd, "Gibraltar" },
				{ LanguageId.nds, "Gibraltar" },
				{ LanguageId.ne, "जिब्राल्टार" },
				{ LanguageId.nl, "Gibraltar" },
				{ LanguageId.nmg, "Gilbratar" },
				{ LanguageId.nn, "Gibraltar" },
				{ LanguageId.nnh, "Gibraltar" },
				{ LanguageId.nqo, "ߜ߭ߌߓߙߊߟߑߕߊߙ" },
				{ LanguageId.nr, "Gibraltar" },
				{ LanguageId.nso, "Gibraltar" },
				{ LanguageId.nus, "Gibraltar" },
				{ LanguageId.nyn, "Giburaata" },
				{ LanguageId.oc, "Gibraltar" },
				{ LanguageId.om, "Gibraaltar" },
				{ LanguageId.or, "ଜିବ୍ରାଲ୍ଟର୍" },
				{ LanguageId.os, "Гибралтар" },
				{ LanguageId.pa, "ਜਿਬਰਾਲਟਰ" },
				{ LanguageId.pap, "Gibraltar" },
				{ LanguageId.pcm, "Jibrọ́lta" },
				{ LanguageId.pl, "Gibraltar" },
				{ LanguageId.prg, "Gibraltars" },
				{ LanguageId.ps, "جبل الطارق" },
				{ LanguageId.pt, "Gibraltar" },
				{ LanguageId.qu, "Gibraltar" },
				{ LanguageId.quc, "Gibraltar" },
				{ LanguageId.rm, "Gibraltar" },
				{ LanguageId.rn, "Juburalitari" },
				{ LanguageId.ro, "Gibraltar" },
				{ LanguageId.rof, "Jibralta" },
				{ LanguageId.ru, "Гибралтар" },
				{ LanguageId.rw, "Gibraltar" },
				{ LanguageId.rwk, "Jibralta" },
				{ LanguageId.sa, "जिब्राल्टर" },
				{ LanguageId.sah, "Гибралтар" },
				{ LanguageId.saq, "Jibralta" },
				{ LanguageId.sat, "ᱡᱤᱵᱽᱨᱟᱞᱴᱚᱨ" },
				{ LanguageId.sbp, "Jibulalita" },
				{ LanguageId.sd, "جبرالٽر" },
				{ LanguageId.se, "Gibraltar" },
				{ LanguageId.seh, "Gibraltar" },
				{ LanguageId.ses, "Gibraltar" },
				{ LanguageId.sg, "Zibraltära, Zibaratära" },
				{ LanguageId.shi, "ⴰⴷⵔⴰⵔ ⵏ ⵟⴰⵕⵉⵇ" },
				{ LanguageId.si, "ජිබ්‍රෝල්ටාව" },
				{ LanguageId.sk, "Gibraltár" },
				{ LanguageId.sl, "Gibraltar" },
				{ LanguageId.sma, "Gibraltar" },
				{ LanguageId.smj, "Gibraltar" },
				{ LanguageId.smn, "Gibraltar" },
				{ LanguageId.sms, "Gibraltar" },
				{ LanguageId.sn, "Gibraltar" },
				{ LanguageId.so, "Gibraltar" },
				{ LanguageId.sq, "Gjibraltar" },
				{ LanguageId.sr, "Гибралтар" },
				{ LanguageId.ss, "Gibraltar" },
				{ LanguageId.ssy, "Gibraltar" },
				{ LanguageId.st, "Gibraltar" },
				{ LanguageId.su, "Gibraltar" },
				{ LanguageId.sv, "Gibraltar" },
				{ LanguageId.sw, "Gibraltar" },
				{ LanguageId.syr, "ܓܒܪܠܛܪ" },
				{ LanguageId.ta, "ஜிப்ரால்டர்" },
				{ LanguageId.te, "జిబ్రాల్టర్" },
				{ LanguageId.teo, "Jibralta" },
				{ LanguageId.tg, "Гибралтар" },
				{ LanguageId.th, "ยิบรอลตาร์" },
				{ LanguageId.ti, "ጂብራልታር" },
				{ LanguageId.tig, "ጊብራልታር" },
				{ LanguageId.tk, "Gibraltar" },
				{ LanguageId.tn, "Gibraltar" },
				{ LanguageId.to, "Sipalālitā" },
				{ LanguageId.tr, "Cebelitarık" },
				{ LanguageId.ts, "Gibraltar" },
				{ LanguageId.tt, "Гибралтар" },
				{ LanguageId.twq, "Gibraltar" },
				{ LanguageId.tzm, "Jibralṭar" },
				{ LanguageId.ug, "جەبىلتارىق" },
				{ LanguageId.uk, "Гібралтар" },
				{ LanguageId.ur, "جبل الطارق" },
				{ LanguageId.uz, "Gibraltar" },
				{ LanguageId.vai, "ꕀꖜꕟꕚ" },
				{ LanguageId.ve, "Gibraltar" },
				{ LanguageId.vi, "Gibraltar" },
				{ LanguageId.vo, "Gibraltär" },
				{ LanguageId.vun, "Jibralta" },
				{ LanguageId.wae, "Gibraltar" },
				{ LanguageId.wal, "ጊብራልታር" },
				{ LanguageId.wo, "Sibraltaar" },
				{ LanguageId.xh, "EGibraltar" },
				{ LanguageId.xog, "Giburalita" },
				{ LanguageId.yav, "sílpalatáal" },
				{ LanguageId.yi, "גיבראַלטאַר" },
				{ LanguageId.yo, "Gibaratara" },
				{ LanguageId.zgh, "ⴰⴷⵔⴰⵔ ⵏ ⵟⴰⵕⵉⵇ" },
				{ LanguageId.zh, "直布罗陀" },
				{ LanguageId.zu, "i-Gibraltar" },
			}
		);
	}
}
