// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GL
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "299",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Greenland" },
				{ LanguageId.da, "Grønland" },
				{ LanguageId.af, "Groenland" },
				{ LanguageId.agq, "Gɨ̀lenlân" },
				{ LanguageId.ak, "Greenman" },
				{ LanguageId.am, "ግሪንላንድ" },
				{ LanguageId.ar, "غرينلاند" },
				{ LanguageId.arn, "Greenland" },
				{ LanguageId.@as, "গ্ৰীণলেণ্ড" },
				{ LanguageId.asa, "Grinlandi" },
				{ LanguageId.ast, "Groenlandia" },
				{ LanguageId.az, "Qrenlandiya" },
				{ LanguageId.ba, "Гренландия" },
				{ LanguageId.bas, "Grǐnlànd" },
				{ LanguageId.be, "Грэнландыя" },
				{ LanguageId.bem, "Greenland" },
				{ LanguageId.bez, "Hujinlandi" },
				{ LanguageId.bg, "Гренландия" },
				{ LanguageId.bin, "Greenland" },
				{ LanguageId.bm, "Gɔrɔhenelandi" },
				{ LanguageId.bn, "গ্রীনল্যান্ড" },
				{ LanguageId.bo, "གེ་རེན་ལེན" },
				{ LanguageId.br, "Greunland" },
				{ LanguageId.brx, "ग्रीनलेण्ड" },
				{ LanguageId.bs, "Grenland" },
				{ LanguageId.byn, "Greenland" },
				{ LanguageId.ca, "Groenlàndia" },
				{ LanguageId.ccp, "𑄉𑄳𑄢𑄩𑄚𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Гренланди" },
				{ LanguageId.ceb, "Greenland" },
				{ LanguageId.cgg, "Guriinirandi" },
				{ LanguageId.chr, "ᎢᏤᏍᏛᏱ" },
				{ LanguageId.ckb, "گرینلاند" },
				{ LanguageId.co, "Groenlandia" },
				{ LanguageId.cs, "Grónsko" },
				{ LanguageId.cu, "Гренландїꙗ" },
				{ LanguageId.cy, "Yr Ynys Las" },
				{ LanguageId.dav, "Grinlandi" },
				{ LanguageId.de, "Grönland" },
				{ LanguageId.dje, "Grinland" },
				{ LanguageId.doi, "ग्रीनलैंड" },
				{ LanguageId.dsb, "Grönlandska" },
				{ LanguageId.dua, "Greenland" },
				{ LanguageId.dv, "ގްރީންލޭންޑް" },
				{ LanguageId.dz, "གིརཱིན་ལནཌ྄" },
				{ LanguageId.ebu, "Grinlandi" },
				{ LanguageId.ee, "Grinland nutome" },
				{ LanguageId.el, "Γροιλανδία" },
				{ LanguageId.en, "Greenland" },
				{ LanguageId.eo, "Gronlando" },
				{ LanguageId.es, "Groenlandia" },
				{ LanguageId.et, "Gröönimaa" },
				{ LanguageId.eu, "Groenlandia" },
				{ LanguageId.ewo, "Goelán" },
				{ LanguageId.fa, "گرینلند" },
				{ LanguageId.ff, "Gorwendland" },
				{ LanguageId.fi, "Grönlanti" },
				{ LanguageId.fil, "Greenland" },
				{ LanguageId.fo, "Grønland" },
				{ LanguageId.fr, "Groenland" },
				{ LanguageId.fur, "Groenlande" },
				{ LanguageId.fy, "Grienlân" },
				{ LanguageId.ga, "an Ghraonlainn" },
				{ LanguageId.gd, "A’ Ghraonlann" },
				{ LanguageId.gl, "Groenlandia" },
				{ LanguageId.gn, "Groenlandia" },
				{ LanguageId.gsw, "Gröönland" },
				{ LanguageId.gu, "ગ્રીનલેન્ડ" },
				{ LanguageId.guz, "Grinlandi" },
				{ LanguageId.gv, "Greenlyn" },
				{ LanguageId.ha, "Grinlan" },
				{ LanguageId.haw, "ʻĀina ʻŌmaʻomaʻo" },
				{ LanguageId.he, "גרינלנד" },
				{ LanguageId.hi, "ग्रीनलैंड" },
				{ LanguageId.hr, "Grenland" },
				{ LanguageId.hsb, "Grönlandska" },
				{ LanguageId.hu, "Grönland" },
				{ LanguageId.hy, "Գրենլանդիա" },
				{ LanguageId.ia, "Groenlandia" },
				{ LanguageId.ibb, "Greenland" },
				{ LanguageId.id, "Greenland" },
				{ LanguageId.ig, "Greenland" },
				{ LanguageId.ii, "ꇬꑘꇁꅉ" },
				{ LanguageId.@is, "Grænland" },
				{ LanguageId.it, "Groenlandia" },
				{ LanguageId.iu, "ᑲᓛᓪᓕᑦ ᓄᓈᑦ" },
				{ LanguageId.ja, "グリーンランド" },
				{ LanguageId.jgo, "Greenland" },
				{ LanguageId.jmc, "Grinlandi" },
				{ LanguageId.jv, "Greenland" },
				{ LanguageId.ka, "გრენლანდია" },
				{ LanguageId.kab, "Grunland" },
				{ LanguageId.kam, "Grinlandi" },
				{ LanguageId.kde, "Glinlandi" },
				{ LanguageId.kea, "Gronelándia" },
				{ LanguageId.khq, "Grinland" },
				{ LanguageId.ki, "Grinlandi" },
				{ LanguageId.kk, "Гренландия" },
				{ LanguageId.kkj, "Greenland" },
				{ LanguageId.kl, "Kalaallit Nunaat" },
				{ LanguageId.kln, "Emetab Greenland" },
				{ LanguageId.km, "ហ្គ្រោអង់ឡង់" },
				{ LanguageId.kn, "ಗ್ರೀನ್‌ಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "그린란드" },
				{ LanguageId.kok, "ग्रीनलँड" },
				{ LanguageId.kr, "Greenland" },
				{ LanguageId.ks, "گرین لینڈ" },
				{ LanguageId.ksb, "Glinlandi" },
				{ LanguageId.ksf, "grínlan" },
				{ LanguageId.ksh, "Jröhnland" },
				{ LanguageId.kw, "Greunland" },
				{ LanguageId.ky, "Гренландия" },
				{ LanguageId.la, "Groenlandiae" },
				{ LanguageId.lag, "Giriniláandi" },
				{ LanguageId.lb, "Grönland" },
				{ LanguageId.lg, "Gurenelandi" },
				{ LanguageId.lkt, "Greenland" },
				{ LanguageId.ln, "Gowelande" },
				{ LanguageId.lo, "ກຣີນແລນ" },
				{ LanguageId.lrc, "گرینلند" },
				{ LanguageId.lt, "Grenlandija" },
				{ LanguageId.luo, "Greenland" },
				{ LanguageId.luy, "Grinlandi" },
				{ LanguageId.lv, "Grenlande" },
				{ LanguageId.mai, "ग्रीनलैंड" },
				{ LanguageId.mas, "Grinlandi" },
				{ LanguageId.mer, "Ngirinilandi" },
				{ LanguageId.mfe, "Greenland" },
				{ LanguageId.mg, "Groenland" },
				{ LanguageId.mgo, "Greenland" },
				{ LanguageId.mi, "Whenuakāriki" },
				{ LanguageId.mk, "Гренланд" },
				{ LanguageId.ml, "ഗ്രീൻലൻഡ്" },
				{ LanguageId.mn, "Гренланд" },
				{ LanguageId.mni, "গ্রীনল্যান্ড" },
				{ LanguageId.moh, "Greenland" },
				{ LanguageId.mr, "ग्रीनलंड" },
				{ LanguageId.ms, "Greenland" },
				{ LanguageId.mt, "Greenland" },
				{ LanguageId.mua, "Sǝr Groenland" },
				{ LanguageId.my, "ဂရင်းလန်း" },
				{ LanguageId.mzn, "گرینلند" },
				{ LanguageId.naq, "Greenland" },
				{ LanguageId.nb, "Grønland" },
				{ LanguageId.nd, "Greenland" },
				{ LanguageId.nds, "Gröönland" },
				{ LanguageId.ne, "ग्रिनल्याण्ड" },
				{ LanguageId.nl, "Groenland" },
				{ LanguageId.nmg, "Greenland" },
				{ LanguageId.nn, "Grønland" },
				{ LanguageId.nnh, "Greenland" },
				{ LanguageId.nqo, "ߜ߭ߎߙߎ߲ߟߊ߲ߘ" },
				{ LanguageId.nr, "Greenland" },
				{ LanguageId.nso, "Greenland" },
				{ LanguageId.nus, "Greenland" },
				{ LanguageId.nyn, "Guriinirandi" },
				{ LanguageId.oc, "Groenlandia" },
				{ LanguageId.om, "Giriinlaand" },
				{ LanguageId.or, "ଗ୍ରୀନଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Гренланди" },
				{ LanguageId.pa, "ਗ੍ਰੀਨਲੈਂਡ" },
				{ LanguageId.pap, "Groenlandia" },
				{ LanguageId.pcm, "Grínland" },
				{ LanguageId.pl, "Grenlandia" },
				{ LanguageId.prg, "Grenlande" },
				{ LanguageId.ps, "ګرینلینډ" },
				{ LanguageId.pt, "Groenlândia" },
				{ LanguageId.qu, "Groenlandia" },
				{ LanguageId.quc, "Greenland" },
				{ LanguageId.rm, "Grönlanda" },
				{ LanguageId.rn, "Gurunilandi" },
				{ LanguageId.ro, "Groenlanda" },
				{ LanguageId.rof, "Grinlandi" },
				{ LanguageId.ru, "Гренландия" },
				{ LanguageId.rw, "Greenland" },
				{ LanguageId.rwk, "Grinlandi" },
				{ LanguageId.sa, "ग्रीनलैंड" },
				{ LanguageId.sah, "Гренландия" },
				{ LanguageId.saq, "Grinlandi" },
				{ LanguageId.sat, "ᱜᱽᱨᱤᱱᱞᱮᱱᱰ" },
				{ LanguageId.sbp, "Gilinilandi" },
				{ LanguageId.sd, "گرين لينڊ" },
				{ LanguageId.se, "Kalaallit Nunaat" },
				{ LanguageId.seh, "Groênlandia" },
				{ LanguageId.ses, "Grinland" },
				{ LanguageId.sg, "Gorolânde" },
				{ LanguageId.shi, "ⴳⵔⵉⵍⴰⵏⴷ" },
				{ LanguageId.si, "ග්‍රීන්ලන්තය" },
				{ LanguageId.sk, "Grónsko" },
				{ LanguageId.sl, "Grenlandija" },
				{ LanguageId.sma, "Gröönlánda" },
				{ LanguageId.smj, "Gröönlánda" },
				{ LanguageId.smn, "Grönland" },
				{ LanguageId.sms, "Grönland" },
				{ LanguageId.sn, "Greenland" },
				{ LanguageId.so, "Greenland" },
				{ LanguageId.sq, "Grënlandë" },
				{ LanguageId.sr, "Гренланд" },
				{ LanguageId.ss, "Greenland" },
				{ LanguageId.ssy, "Greenland" },
				{ LanguageId.st, "Greenland" },
				{ LanguageId.su, "Greenland" },
				{ LanguageId.sv, "Grönland" },
				{ LanguageId.sw, "Greenland" },
				{ LanguageId.syr, "ܓܪܝܢܠܢܕ" },
				{ LanguageId.ta, "கிரீன்லாந்து" },
				{ LanguageId.te, "గ్రీన్‌ల్యాండ్" },
				{ LanguageId.teo, "Grinlandi" },
				{ LanguageId.tg, "Гренландия" },
				{ LanguageId.th, "กรีนแลนด์" },
				{ LanguageId.ti, "ግሪንላንድ" },
				{ LanguageId.tig, "ግሪንላንድ" },
				{ LanguageId.tk, "Grenlandiýa" },
				{ LanguageId.tn, "Greenland" },
				{ LanguageId.to, "Kulinilani" },
				{ LanguageId.tr, "Grönland" },
				{ LanguageId.ts, "Greenland" },
				{ LanguageId.tt, "Гренландия" },
				{ LanguageId.twq, "Grinland" },
				{ LanguageId.tzm, "Grinlanḍa" },
				{ LanguageId.ug, "گىرېنلاندىيە" },
				{ LanguageId.uk, "Гренландія" },
				{ LanguageId.ur, "گرین لینڈ" },
				{ LanguageId.uz, "Grenlandiya" },
				{ LanguageId.vai, "ꕧꕓ ꖴꕎ ꖨꕮꕊ" },
				{ LanguageId.ve, "Greenland" },
				{ LanguageId.vi, "Greenland" },
				{ LanguageId.vo, "Gröneän" },
				{ LanguageId.vun, "Grinlandi" },
				{ LanguageId.wae, "Grönland" },
				{ LanguageId.wal, "ግሪንላንድ" },
				{ LanguageId.wo, "Girinlànd" },
				{ LanguageId.xh, "EGreenland" },
				{ LanguageId.xog, "Gurenelandi" },
				{ LanguageId.yav, "kuluɛnlánd" },
				{ LanguageId.yi, "גרינלאַנד" },
				{ LanguageId.yo, "Gerelandi" },
				{ LanguageId.zgh, "ⴳⵔⵉⵍⴰⵏⴷ" },
				{ LanguageId.zh, "格陵兰" },
				{ LanguageId.zu, "i-Greenland" },
			}
		);
	}
}
