using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GL
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "299",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Greenland" },
				{ LanguageId.da, "Grønland" },
				{ LanguageId.af, "Groenland" },
				{ LanguageId.agq, "Greenland" },
				{ LanguageId.ak, "Greenland" },
				{ LanguageId.am, "ግሪንላንድ" },
				{ LanguageId.ar, "الأرض الخضراء" },
				{ LanguageId.arn, "Greenland" },
				{ LanguageId.@as, "গ্ৰীণলেণ্ড" },
				{ LanguageId.asa, "Greenland" },
				{ LanguageId.ast, "Groenlandia" },
				{ LanguageId.az, "Qrenlandiya" },
				{ LanguageId.ba, "Гренландия" },
				{ LanguageId.bas, "Greenland" },
				{ LanguageId.be, "Грэнландыя" },
				{ LanguageId.bem, "Greenland" },
				{ LanguageId.bez, "Greenland" },
				{ LanguageId.bg, "Гренландия" },
				{ LanguageId.bin, "Greenland" },
				{ LanguageId.bm, "Greenland" },
				{ LanguageId.bn, "গ্রীনল্যান্ড" },
				{ LanguageId.bo, "གེ་རེན་ལེན" },
				{ LanguageId.br, "Greunland" },
				{ LanguageId.brx, "ग्रीनल्याण्ड" },
				{ LanguageId.bs, "Grenland" },
				{ LanguageId.byn, "Greenland" },
				{ LanguageId.ca, "Groenlàndia" },
				{ LanguageId.ccp, "𑄉𑄳𑄢𑄨𑄚𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Гренланди" },
				{ LanguageId.ceb, "Greenland" },
				{ LanguageId.cgg, "Greenland" },
				{ LanguageId.chr, "ᎩᎴᎵᎳᏂ" },
				{ LanguageId.ckb, "گرینلەند" },
				{ LanguageId.co, "Groenlandia" },
				{ LanguageId.cs, "Grónsko" },
				{ LanguageId.cu, "Гренландїꙗ" },
				{ LanguageId.cy, "Yr Ynys Las" },
				{ LanguageId.dav, "Greenland" },
				{ LanguageId.de, "Grönland" },
				{ LanguageId.dje, "Greenland" },
				{ LanguageId.doi, "ग्रीनलैंड" },
				{ LanguageId.dsb, "Grönlandska" },
				{ LanguageId.dua, "Greenland" },
				{ LanguageId.dv, "ގްރީންލޭންޑް" },
				{ LanguageId.dz, "གེ་རེན་ལེནཌ" },
				{ LanguageId.ebu, "Greenland" },
				{ LanguageId.ee, "Greenland" },
				{ LanguageId.el, "Γροιλανδία" },
				{ LanguageId.en, "Greenland" },
				{ LanguageId.eo, "Gronlando" },
				{ LanguageId.es, "Groenlandia" },
				{ LanguageId.et, "Gröönimaa" },
				{ LanguageId.eu, "Groenlandia" },
				{ LanguageId.ewo, "Greenland" },
				{ LanguageId.fa, "گرینلند" },
				{ LanguageId.ff, "Groenlaand" },
				{ LanguageId.fi, "Grönlanti" },
				{ LanguageId.fil, "Greenland" },
				{ LanguageId.fo, "Grønland" },
				{ LanguageId.fr, "Groenland" },
				{ LanguageId.fur, "Groenlandie" },
				{ LanguageId.fy, "Grienlân" },
				{ LanguageId.ga, "Ghraonlainn" },
				{ LanguageId.gd, "A' Ghraonlainn" },
				{ LanguageId.gl, "Groenlandia" },
				{ LanguageId.gn, "Groenlandia" },
				{ LanguageId.gsw, "Grönland" },
				{ LanguageId.gu, "ગ્રીનલેન્ડ" },
				{ LanguageId.guz, "Greenland" },
				{ LanguageId.gv, "Greenlyn" },
				{ LanguageId.ha, "Greenland" },
				{ LanguageId.haw, "ʻĀina ʻŌmaʻomaʻo" },
				{ LanguageId.he, "גרינלנד" },
				{ LanguageId.hi, "ग्रीनलैंड" },
				{ LanguageId.hr, "Grenland" },
				{ LanguageId.hsb, "Grönlandska" },
				{ LanguageId.hu, "Grönland" },
				{ LanguageId.hy, "Գրենլանդիա" },
				{ LanguageId.ia, "Groenlandia" },
				{ LanguageId.ibb, "Greenland" },
				{ LanguageId.id, "Tanah penggembalaan" },
				{ LanguageId.ig, "Greenland" },
				{ LanguageId.ii, "ꇬꑘꇁꅉ" },
				{ LanguageId.@is, "Grænland" },
				{ LanguageId.it, "Groenlandia" },
				{ LanguageId.iu, "ᑲᓛᓪᓕᑦ ᓄᓈᑦ" },
				{ LanguageId.ja, "グリーンランド" },
				{ LanguageId.jgo, "Greenland" },
				{ LanguageId.jmc, "Greenland" },
				{ LanguageId.jv, "Greenland" },
				{ LanguageId.ka, "გრენლანდია" },
				{ LanguageId.kab, "Grunland" },
				{ LanguageId.kam, "Greenland" },
				{ LanguageId.kde, "Greenland" },
				{ LanguageId.kea, "Gronelándia" },
				{ LanguageId.khq, "Greenland" },
				{ LanguageId.ki, "Greenland" },
				{ LanguageId.kk, "Гренландия" },
				{ LanguageId.kkj, "Greenland" },
				{ LanguageId.kl, "Kalaallit Nunaat" },
				{ LanguageId.kln, "Greenland" },
				{ LanguageId.km, "ហ្គ្រីនឡែន" },
				{ LanguageId.kn, "ಗ್ರೀನ್ಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "그린란드" },
				{ LanguageId.kok, "ग्रीनलँड" },
				{ LanguageId.kr, "Greenland" },
				{ LanguageId.ks, "گرین لینڈ" },
				{ LanguageId.ksb, "Greenland" },
				{ LanguageId.ksf, "Greenland" },
				{ LanguageId.ksh, "Grönland" },
				{ LanguageId.kw, "Greunland" },
				{ LanguageId.ky, "Гринландия" },
				{ LanguageId.la, "Groenlandiae" },
				{ LanguageId.lag, "Greenland" },
				{ LanguageId.lb, "Grönland" },
				{ LanguageId.lg, "Greenland" },
				{ LanguageId.lkt, "Greenland" },
				{ LanguageId.ln, "Groenlandi" },
				{ LanguageId.lo, "ກຣີນແລນ" },
				{ LanguageId.lrc, "گرینلند" },
				{ LanguageId.lt, "Grenlandija" },
				{ LanguageId.luo, "Greenland" },
				{ LanguageId.luy, "Greenland" },
				{ LanguageId.lv, "Grenlande" },
				{ LanguageId.mai, "ग्रीनलैंड" },
				{ LanguageId.mas, "Greenland" },
				{ LanguageId.mer, "Greenland" },
				{ LanguageId.mfe, "Groenland" },
				{ LanguageId.mg, "Groenlandy" },
				{ LanguageId.mgo, "Greenland" },
				{ LanguageId.mi, "Greenland" },
				{ LanguageId.mk, "Гренланд" },
				{ LanguageId.ml, "ഗ്രീൻലാൻഡ്" },
				{ LanguageId.mn, "Гренланд" },
				{ LanguageId.mni, "গ্রীনল্যান্ড" },
				{ LanguageId.moh, "Greenland" },
				{ LanguageId.mr, "ग्रीनलँड" },
				{ LanguageId.ms, "Greenland" },
				{ LanguageId.mt, "Greenland" },
				{ LanguageId.mua, "Greenland" },
				{ LanguageId.my, "ဂရင်းလန်း" },
				{ LanguageId.mzn, "گرینلند" },
				{ LanguageId.naq, "Greenland" },
				{ LanguageId.nb, "Grønland" },
				{ LanguageId.nd, "Greenland" },
				{ LanguageId.nds, "Gröönland" },
				{ LanguageId.ne, "ग्रीनल्याण्ड" },
				{ LanguageId.nl, "Groenland" },
				{ LanguageId.nmg, "Greenland" },
				{ LanguageId.nn, "Grønland" },
				{ LanguageId.nnh, "Greenland" },
				{ LanguageId.nqo, "ߜ߭ߙߌ߲ߟߊ߲ߘ" },
				{ LanguageId.nr, "Greenland" },
				{ LanguageId.nso, "Greenland" },
				{ LanguageId.nus, "Greenland" },
				{ LanguageId.nyn, "Greenland" },
				{ LanguageId.oc, "Groenlandia" },
				{ LanguageId.om, "Greenland" },
				{ LanguageId.or, "ଗ୍ରୀନଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Гренланди" },
				{ LanguageId.pa, "ਗ੍ਰੀਨਲੈਂਡ" },
				{ LanguageId.pap, "Groenlandia" },
				{ LanguageId.pcm, "Grínlándì" },
				{ LanguageId.pl, "Grenlandia" },
				{ LanguageId.prg, "Grenlande" },
				{ LanguageId.ps, "ګرینلینډ" },
				{ LanguageId.pt, "Groenlândia" },
				{ LanguageId.qu, "Groenlandia" },
				{ LanguageId.quc, "Greenland" },
				{ LanguageId.rm, "Grönlanda" },
				{ LanguageId.rn, "Greenland" },
				{ LanguageId.ro, "Groenlanda" },
				{ LanguageId.rof, "Greenland" },
				{ LanguageId.ru, "Гренландия" },
				{ LanguageId.rw, "Greenland" },
				{ LanguageId.rwk, "Greenland" },
				{ LanguageId.sa, "ग्रीनलैंड" },
				{ LanguageId.sah, "Гренландия" },
				{ LanguageId.saq, "Greenland" },
				{ LanguageId.sat, "ᱜᱽᱨᱤᱱᱞᱮᱱᱰ" },
				{ LanguageId.sbp, "Greenland" },
				{ LanguageId.sd, "گرين لينڊ" },
				{ LanguageId.se, "Ruonáenan" },
				{ LanguageId.seh, "Greenland" },
				{ LanguageId.ses, "Greenland" },
				{ LanguageId.sg, "Gorolânde" },
				{ LanguageId.shi, "ⴳⵔⵉⵏⵍⴰⵏⴷ" },
				{ LanguageId.si, "ග්රීන්ලන්තය" },
				{ LanguageId.sk, "Grónsko" },
				{ LanguageId.sl, "Grenlandija" },
				{ LanguageId.sma, "Gröönlánda" },
				{ LanguageId.smj, "Gröönlánda" },
				{ LanguageId.smn, "Kaleenâdâ" },
				{ LanguageId.sms, "Grönland" },
				{ LanguageId.sn, "Girinirendi" },
				{ LanguageId.so, "Greenland" },
				{ LanguageId.sq, "Grenlanda" },
				{ LanguageId.sr, "Гренланд" },
				{ LanguageId.ss, "Greenland" },
				{ LanguageId.ssy, "Greenland" },
				{ LanguageId.st, "Greenland" },
				{ LanguageId.su, "Greenland" },
				{ LanguageId.sv, "Grönland" },
				{ LanguageId.sw, "Greenland" },
				{ LanguageId.syr, "ܓܪܝܢܠܢܕ" },
				{ LanguageId.ta, "கிரீன்லாந்து" },
				{ LanguageId.te, "గ్రీన్లాండ్" },
				{ LanguageId.teo, "Greenland" },
				{ LanguageId.tg, "Гренландия" },
				{ LanguageId.th, "กรีนแลนด์" },
				{ LanguageId.ti, "ግሪንላንድ" },
				{ LanguageId.tig, "ግሪንላንድ" },
				{ LanguageId.tk, "Grenlandiýa" },
				{ LanguageId.tn, "Greenland" },
				{ LanguageId.to, "Kīlinilani" },
				{ LanguageId.tr, "Grönland" },
				{ LanguageId.ts, "Greenland" },
				{ LanguageId.tt, "Гренландия" },
				{ LanguageId.twq, "Greenland" },
				{ LanguageId.tzm, "ⴳⵔⵉⵏⵍⴰⵏⴷ" },
				{ LanguageId.ug, "Greenland" },
				{ LanguageId.uk, "Гренландія" },
				{ LanguageId.ur, "گرین لینڈ" },
				{ LanguageId.uz, "Grenlandiya" },
				{ LanguageId.vai, "ꔳꔸꘋꔔꘋꕜ" },
				{ LanguageId.ve, "Greenland" },
				{ LanguageId.vi, "Greenland" },
				{ LanguageId.vo, "Gröneän" },
				{ LanguageId.vun, "Greenland" },
				{ LanguageId.wae, "Grönland" },
				{ LanguageId.wal, "ግሪንላንድ" },
				{ LanguageId.wo, "Groenlaand" },
				{ LanguageId.xh, "Grinlend" },
				{ LanguageId.xog, "Greenland" },
				{ LanguageId.yav, "Greenland" },
				{ LanguageId.yi, "גרינלאַנד" },
				{ LanguageId.yo, "Girinilandi" },
				{ LanguageId.zgh, "ⴳⵔⵉⵏⵍⴰⵏⴷ" },
				{ LanguageId.zh, "格陵兰" },
				{ LanguageId.zu, "Greenland" },
			}
		);
	}
}
