// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GQ
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "240",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Equatorial Guinea" },
				{ LanguageId.da, "Ækvatorialguinea" },
				{ LanguageId.af, "Ekwatoriaal-Guinee" },
				{ LanguageId.agq, "Èkwɛ̀tolia Ginè" },
				{ LanguageId.ak, "Gini Ikuweta" },
				{ LanguageId.am, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.ar, "غينيا الاستوائية" },
				{ LanguageId.arn, "Equatorial Guinea" },
				{ LanguageId.@as, "ইকুৱেটৰিয়েল গিনি" },
				{ LanguageId.asa, "Ginekweta" },
				{ LanguageId.ast, "Guinea Ecuatorial" },
				{ LanguageId.az, "Ekvatorial Qvineya" },
				{ LanguageId.ba, "Экваториаль Гвинея" },
				{ LanguageId.bas, "Gìne Èkwàtorìà" },
				{ LanguageId.be, "Экватарыяльная Гвінея" },
				{ LanguageId.bem, "Equatorial Guinea" },
				{ LanguageId.bez, "Huginekweta" },
				{ LanguageId.bg, "Екваториална Гвинея" },
				{ LanguageId.bin, "Equatorial Guinea" },
				{ LanguageId.bm, "Gine ekwatɔri" },
				{ LanguageId.bn, "নিরক্ষীয় গিনি" },
				{ LanguageId.bo, "ཨེ་ཁེ་ཊོ་རེལ་གི་ནེ" },
				{ LanguageId.br, "Ginea-ar-Cʼheheder" },
				{ LanguageId.brx, "बिसुबारि गिनीया" },
				{ LanguageId.bs, "Ekvatorijalna Gvineja" },
				{ LanguageId.byn, "Equatorial Guinea" },
				{ LanguageId.ca, "Guinea Equatorial" },
				{ LanguageId.ccp, "𑄚𑄨𑄢𑄧𑄇𑄴𑄈𑄩𑄠𑄧 𑄉𑄨𑄚𑄨" },
				{ LanguageId.ce, "Экваторан Гвиней" },
				{ LanguageId.ceb, "Equatorial Guinea" },
				{ LanguageId.cgg, "Guni" },
				{ LanguageId.chr, "ᎡᏆᏙᎵᎠᎵ ᎩᎢᏂ" },
				{ LanguageId.ckb, "گینێی ئیستوایی" },
				{ LanguageId.co, "Guinea Equatoriale" },
				{ LanguageId.cs, "Rovníková Guinea" },
				{ LanguageId.cu, "Экваторїальна Гвинеꙗ" },
				{ LanguageId.cy, "Gini Gyhydeddol" },
				{ LanguageId.dav, "Ginekweta" },
				{ LanguageId.de, "Äquatorialguinea" },
				{ LanguageId.dje, "Ginee Ekwatorial" },
				{ LanguageId.doi, "इक्वेटोरियल गिनी" },
				{ LanguageId.dsb, "Ekwatorialna Gineja" },
				{ LanguageId.dua, "Equatorial Guinea" },
				{ LanguageId.dv, "އިކުއޭޓޯރިއަލް ގީނީއާ" },
				{ LanguageId.dz, "ཨེ་ཀུ་ཊོ་རེལ་ གི་ནི" },
				{ LanguageId.ebu, "Ginekweta" },
				{ LanguageId.ee, "Ekuatorial Guini nutome" },
				{ LanguageId.el, "Ισημερινή Γουινέα" },
				{ LanguageId.en, "Equatorial Guinea" },
				{ LanguageId.eo, "Ekvatora Gvineo" },
				{ LanguageId.es, "Guinea Ecuatorial" },
				{ LanguageId.et, "Ekvatoriaal-Guinea" },
				{ LanguageId.eu, "Ekuatore Ginea" },
				{ LanguageId.ewo, "Giné Ekwató" },
				{ LanguageId.fa, "گینهٔ استوایی" },
				{ LanguageId.ff, "Ginee Ekuwaatoriyaal" },
				{ LanguageId.fi, "Päiväntasaajan Guinea" },
				{ LanguageId.fil, "Equatorial Guinea" },
				{ LanguageId.fo, "Ekvatorguinea" },
				{ LanguageId.fr, "Guinée équatoriale" },
				{ LanguageId.fur, "Guinee ecuatoriâl" },
				{ LanguageId.fy, "Equatoriaal-Guinea" },
				{ LanguageId.ga, "an Ghuine Mheánchiorclach" },
				{ LanguageId.gd, "Gini Mheadhan-Chriosach" },
				{ LanguageId.gl, "Guinea Ecuatorial" },
				{ LanguageId.gn, "Guinea Ecuatorial" },
				{ LanguageId.gsw, "Äquatoriaalgineea" },
				{ LanguageId.gu, "ઇક્વેટોરિયલ ગિની" },
				{ LanguageId.guz, "Ginekweta" },
				{ LanguageId.gv, "Yn Ghuinea Chryss ny Cruinney" },
				{ LanguageId.ha, "Ikwatoriyal Gini" },
				{ LanguageId.haw, "Kini ʻEkuakolia" },
				{ LanguageId.he, "גינאה המשוונית" },
				{ LanguageId.hi, "इक्वेटोरियल गिनी" },
				{ LanguageId.hr, "Ekvatorska Gvineja" },
				{ LanguageId.hsb, "Ekwatorialna Gineja" },
				{ LanguageId.hu, "Egyenlítői-Guinea" },
				{ LanguageId.hy, "Հասարակածային Գվինեա" },
				{ LanguageId.ia, "Guinea equatorial" },
				{ LanguageId.ibb, "Equatorial Guinea" },
				{ LanguageId.id, "Guinea Ekuatorial" },
				{ LanguageId.ig, "Equatorial Guinea" },
				{ LanguageId.ii, "ꊺꄔꋒꇬꑍ" },
				{ LanguageId.@is, "Miðbaugs-Gínea" },
				{ LanguageId.it, "Guinea Equatoriale" },
				{ LanguageId.iu, "ᐃᖁᐌᑐᕆᐊᓪ ᒋᓂ" },
				{ LanguageId.ja, "赤道ギニア" },
				{ LanguageId.jgo, "Ŋginɛ̂ Ɛkwatɔliyâl" },
				{ LanguageId.jmc, "Ginekweta" },
				{ LanguageId.jv, "Guinéa Katulistiwa" },
				{ LanguageId.ka, "ეკვატორული გვინეა" },
				{ LanguageId.kab, "Ɣinya Tasebgast" },
				{ LanguageId.kam, "Ginekweta" },
				{ LanguageId.kde, "Ginekweta" },
				{ LanguageId.kea, "Gine Ekuatorial" },
				{ LanguageId.khq, "Ginee Ekwatorial" },
				{ LanguageId.ki, "Ginekweta" },
				{ LanguageId.kk, "Экваторлық Гвинея" },
				{ LanguageId.kkj, "Equatorial Guinea" },
				{ LanguageId.kl, "Guinea ekvatoriamiut" },
				{ LanguageId.kln, "Emetab Equatorial Guinea" },
				{ LanguageId.km, "ហ្គីណេអេក្វាទ័រ" },
				{ LanguageId.kn, "ಈಕ್ವೆಟೋರಿಯಲ್ ಗಿನಿ" },
				{ LanguageId.ko, "적도 기니" },
				{ LanguageId.kok, "भूमध्यरेखी गिनी" },
				{ LanguageId.kr, "Equatorial Guinea" },
				{ LanguageId.ks, "اِکوِٹورِیَل گِنی" },
				{ LanguageId.ksb, "Ginekweta" },
				{ LanguageId.ksf, "ginɛ́ ɛkwatɔrial" },
				{ LanguageId.ksh, "Äquatorial Jineeja" },
				{ LanguageId.kw, "Gyni Ekwadorel" },
				{ LanguageId.ky, "Экватордук Гвинея" },
				{ LanguageId.la, "Guinea Aequatorialis" },
				{ LanguageId.lag, "Gíine Ikwéeta" },
				{ LanguageId.lb, "Equatorialguinea" },
				{ LanguageId.lg, "Gayana ey’oku ekweta" },
				{ LanguageId.lkt, "Equatorial Guinea" },
				{ LanguageId.ln, "Ginɛ́kwatɛ́lɛ" },
				{ LanguageId.lo, "ເອຄົວໂທຣຽວ ກີນີ" },
				{ LanguageId.lrc, "گینەی ئیستوایی" },
				{ LanguageId.lt, "Pusiaujo Gvinėja" },
				{ LanguageId.luo, "Equatorial Guinea" },
				{ LanguageId.luy, "Ginekweta" },
				{ LanguageId.lv, "Ekvatoriālā Gvineja" },
				{ LanguageId.mai, "इक्वेटोरियल गिनी" },
				{ LanguageId.mas, "Ginekweta" },
				{ LanguageId.mer, "Gine ya Iquita" },
				{ LanguageId.mfe, "Gine ekwatoryal" },
				{ LanguageId.mg, "Guinea Ekoatera" },
				{ LanguageId.mgo, "Equatorial Guinea" },
				{ LanguageId.mi, "Kini Ekuatoria" },
				{ LanguageId.mk, "Екваторска Гвинеја" },
				{ LanguageId.ml, "ഇക്വറ്റോറിയൽ ഗിനിയ" },
				{ LanguageId.mn, "Экваторын Гвиней" },
				{ LanguageId.mni, "নিরক্ষীয় গিনি" },
				{ LanguageId.moh, "Equatorial Guinea" },
				{ LanguageId.mr, "इक्वेटोरियल गिनी" },
				{ LanguageId.ms, "Guinea Khatulistiwa" },
				{ LanguageId.mt, "il-Guinea Ekwatorjali" },
				{ LanguageId.mua, "Sǝr Guine" },
				{ LanguageId.my, "အီကွေတာ ဂီနီ" },
				{ LanguageId.mzn, "استوایی گینه" },
				{ LanguageId.naq, "Equatorial Guineab" },
				{ LanguageId.nb, "Ekvatorial-Guinea" },
				{ LanguageId.nd, "Equatorial Guinea" },
				{ LanguageId.nds, "Äquatorialguinea" },
				{ LanguageId.ne, "भू-मध्यीय गिनी" },
				{ LanguageId.nl, "Equatoriaal-Guinea" },
				{ LanguageId.nmg, "Guine Ekuatorial" },
				{ LanguageId.nn, "Ekvatorial-Guinea" },
				{ LanguageId.nnh, "Equatorial Guinea" },
				{ LanguageId.nqo, "ߕߍߡߊߓߊ߲߮-ߖߌ߬ߣߍ߫" },
				{ LanguageId.nr, "Equatorial Guinea" },
				{ LanguageId.nso, "Equatorial Guinea" },
				{ LanguageId.nus, "Equatorial Guinea" },
				{ LanguageId.nyn, "Guni" },
				{ LanguageId.oc, "Guinea Equatoriala" },
				{ LanguageId.om, "Ikkuwaatooriyaal Giinii" },
				{ LanguageId.or, "ଇକ୍ବାଟୋରିଆଲ୍ ଗୁଇନିଆ" },
				{ LanguageId.os, "Экваториалон Гвиней" },
				{ LanguageId.pa, "ਭੂ-ਖੰਡੀ ਗਿਨੀ" },
				{ LanguageId.pap, "Guinea Ekuatorial" },
				{ LanguageId.pcm, "Ikwétóriál Gíni" },
				{ LanguageId.pl, "Gwinea Równikowa" },
				{ LanguageId.prg, "Ekvatorialnā Gvineja" },
				{ LanguageId.ps, "استوایی ګیني" },
				{ LanguageId.pt, "Guiné Equatorial" },
				{ LanguageId.qu, "Guinea Ecuatorial" },
				{ LanguageId.quc, "Equatorial Guinea" },
				{ LanguageId.rm, "Guinea Equatoriala" },
				{ LanguageId.rn, "Gineya Ekwatoriyali" },
				{ LanguageId.ro, "Guineea Ecuatorială" },
				{ LanguageId.rof, "Ginekweta" },
				{ LanguageId.ru, "Экваториальная Гвинея" },
				{ LanguageId.rw, "Gineya ya Ekwatoriya" },
				{ LanguageId.rwk, "Ginekweta" },
				{ LanguageId.sa, "इक्वेटोरियल गिनी" },
				{ LanguageId.sah, "Экваториал Гвинея" },
				{ LanguageId.saq, "Ginekweta" },
				{ LanguageId.sat, "ᱤᱠᱣᱮᱴᱳᱨᱤᱭᱟᱞ ᱜᱤᱱᱤ" },
				{ LanguageId.sbp, "Ginekweta" },
				{ LanguageId.sd, "ايڪوٽوريل گائينا" },
				{ LanguageId.se, "Ekvatoriála Guinea" },
				{ LanguageId.seh, "Guiné Equatorial" },
				{ LanguageId.ses, "Ginee Ekwatorial" },
				{ LanguageId.sg, "Ginëe tî Ekuatëre" },
				{ LanguageId.shi, "ⵖⵉⵏⵢⴰ ⵏ ⵉⴽⵡⴰⴷⵓⵔ" },
				{ LanguageId.si, "සමක ගිනියාව" },
				{ LanguageId.sk, "Rovníková Guinea" },
				{ LanguageId.sl, "Ekvatorialna Gvineja" },
				{ LanguageId.sma, "Ekvatoriála Guinea" },
				{ LanguageId.smj, "Ekvatoriála Guinea" },
				{ LanguageId.smn, "Peeivitäsideijee Guinea" },
				{ LanguageId.sms, "Ekvatoria Guinea" },
				{ LanguageId.sn, "Equatorial Guinea" },
				{ LanguageId.so, "Ekuwatooriyal Gini" },
				{ LanguageId.sq, "Guineja Ekuatoriale" },
				{ LanguageId.sr, "Екваторијална Гвинеја" },
				{ LanguageId.ss, "Equatorial Guinea" },
				{ LanguageId.ssy, "Equatorial Guinea" },
				{ LanguageId.st, "Equatorial Guinea" },
				{ LanguageId.su, "Guinea Khatulistiwa" },
				{ LanguageId.sv, "Ekvatorialguinea" },
				{ LanguageId.sw, "Guinea ya Ikweta" },
				{ LanguageId.syr, "ܓܝܢܝܐ ܫܘܝܬܐ" },
				{ LanguageId.ta, "ஈக்வடோரியல் கினியா" },
				{ LanguageId.te, "ఈక్వటోరియల్ గినియా" },
				{ LanguageId.teo, "Ginekweta" },
				{ LanguageId.tg, "Гвинеяи Экваторӣ" },
				{ LanguageId.th, "อิเควทอเรียลกินี" },
				{ LanguageId.ti, "ኢኳቶርያል ጊኒ" },
				{ LanguageId.tig, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.tk, "Ekwatorial Gwineýa" },
				{ LanguageId.tn, "Equatorial Guinea" },
				{ LanguageId.to, "ʻEkueta Kini" },
				{ LanguageId.tr, "Ekvator Ginesi" },
				{ LanguageId.ts, "Equatorial Guinea" },
				{ LanguageId.tt, "Экваториаль Гвинея" },
				{ LanguageId.twq, "Ginee Ekwatorial" },
				{ LanguageId.tzm, "Ɣinya Tikwaṭur it" },
				{ LanguageId.ug, "ئېكۋاتور گىۋىنىيەسى" },
				{ LanguageId.uk, "Екваторіальна Гвінея" },
				{ LanguageId.ur, "استوائی گیانا" },
				{ LanguageId.uz, "Ekvatorial Gvineya" },
				{ LanguageId.vai, "ꖦꕰꕊ ꗳ ꕅꔤꕇ" },
				{ LanguageId.ve, "Equatorial Guinea" },
				{ LanguageId.vi, "Guinea Xích Đạo" },
				{ LanguageId.vo, "Kveatoriala-Gineyän" },
				{ LanguageId.vun, "Ginekweta" },
				{ LanguageId.wae, "Equatorialginea" },
				{ LanguageId.wal, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.wo, "Gine Ekuwatoriyal" },
				{ LanguageId.xh, "E-Equatorial Guinea" },
				{ LanguageId.xog, "Gayana yaku ekweta" },
				{ LanguageId.yav, "kinéekuatolial" },
				{ LanguageId.yi, "עקוואַטארישע גינע" },
				{ LanguageId.yo, "Ekutoria Gini" },
				{ LanguageId.zgh, "ⵖⵉⵏⵢⴰ ⵏ ⵉⴽⵡⴰⴷⵓⵔ" },
				{ LanguageId.zh, "赤道几内亚" },
				{ LanguageId.zu, "i-Equatorial Guinea" },
			}
		);
	}
}
