using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GQ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "240",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Equatorial Guinea" },
				{ LanguageId.da, "Ækvatorial Guinea" },
				{ LanguageId.af, "Ekwatoriaal-Guinee" },
				{ LanguageId.agq, "Equatorial Guinea" },
				{ LanguageId.ak, "Equatorial Guinea" },
				{ LanguageId.am, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.ar, "غينيا الإستوائية" },
				{ LanguageId.arn, "Equatorial Guinea" },
				{ LanguageId.@as, "বিষুৱীয় গিনি" },
				{ LanguageId.asa, "Equatorial Guinea" },
				{ LanguageId.ast, "Guinea Ecuatorial" },
				{ LanguageId.az, "Ekvatorial Qvineya" },
				{ LanguageId.ba, "Экваториаль Гвинея" },
				{ LanguageId.bas, "Equatorial Guinea" },
				{ LanguageId.be, "Экватарыяльная Гвінея" },
				{ LanguageId.bem, "Equatorial Guinea" },
				{ LanguageId.bez, "Equatorial Guinea" },
				{ LanguageId.bg, "Екваториална Гвинея" },
				{ LanguageId.bin, "Equatorial Guinea" },
				{ LanguageId.bm, "Ekwatɔrikal Gine" },
				{ LanguageId.bn, "নিরক্ষীয় গিনি" },
				{ LanguageId.bo, "ཨེ་ཁེ་ཊོ་རེལ་གི་ནེ" },
				{ LanguageId.br, "Ginea ar C'heheder" },
				{ LanguageId.brx, "भूमध्यवर्ती गिनी" },
				{ LanguageId.bs, "Ekvatorijalna Gvineja" },
				{ LanguageId.byn, "Equatorial Guinea" },
				{ LanguageId.ca, "Guinea Equatorial" },
				{ LanguageId.ccp, "𑄚𑄨𑄢𑄧𑄇𑄴𑄈𑄨𑄠𑄧 𑄉𑄨𑄚𑄨" },
				{ LanguageId.ce, "Экваториальни Гвиней" },
				{ LanguageId.ceb, "Equatorial Guinea" },
				{ LanguageId.cgg, "Equatorial Guinea" },
				{ LanguageId.chr, "ᏑᎾᎴᎢ ᎩᏂ" },
				{ LanguageId.ckb, "گینێی ئیستوایی" },
				{ LanguageId.co, "Guinea Equatoriale" },
				{ LanguageId.cs, "Rovníková Guinea" },
				{ LanguageId.cu, "Экваторїальна Гвинеꙗ" },
				{ LanguageId.cy, "Gini Gyhydeddol" },
				{ LanguageId.dav, "Equatorial Guinea" },
				{ LanguageId.de, "Äquatorialguinea" },
				{ LanguageId.dje, "Equatorial Guinea" },
				{ LanguageId.doi, "इक्वेटोरियल गिनी" },
				{ LanguageId.dsb, "Ekwatorialna Gwineja" },
				{ LanguageId.dua, "Equatorial Guinea" },
				{ LanguageId.dv, "އިކުއޭޓޯރިއަލް ގީނީއާ" },
				{ LanguageId.dz, "ཨེ་ཁེ་ཊོ་རེལ་གི་ནེ" },
				{ LanguageId.ebu, "Equatorial Guinea" },
				{ LanguageId.ee, "Equatorial Guinea" },
				{ LanguageId.el, "Ισημερινή Γουινέα" },
				{ LanguageId.en, "Equatorial Guinea" },
				{ LanguageId.eo, "Ekvatora Gvineo" },
				{ LanguageId.es, "Guinea Ecuatorial" },
				{ LanguageId.et, "Ekvatoriaalne Guinea" },
				{ LanguageId.eu, "Ekuatore Ginea" },
				{ LanguageId.ewo, "Equatorial Guinea" },
				{ LanguageId.fa, "گینه استوایی" },
				{ LanguageId.ff, "Gine Ekwatoriyal" },
				{ LanguageId.fi, "Päiväntasaajan Guinea" },
				{ LanguageId.fil, "Equatorial Guinea" },
				{ LanguageId.fo, "Ekvatorguinea" },
				{ LanguageId.fr, "Guinée Équatoriale" },
				{ LanguageId.fur, "Guinee Ecuatoriale" },
				{ LanguageId.fy, "Ekwatoriaal-Guinee" },
				{ LanguageId.ga, "An Ghuine Mheánchriosach" },
				{ LanguageId.gd, "Equatorial Guinea" },
				{ LanguageId.gl, "Guinea Ecuatorial" },
				{ LanguageId.gn, "Guinea Ecuatorial" },
				{ LanguageId.gsw, "Äquatorialguinea" },
				{ LanguageId.gu, "વિષુવવૃત્તીય ગિની" },
				{ LanguageId.guz, "Equatorial Guinea" },
				{ LanguageId.gv, "Yn Ghuinea Chryss ny Cruinney" },
				{ LanguageId.ha, "Equatorial Guinea" },
				{ LanguageId.haw, "Kini ʻEkuakolia" },
				{ LanguageId.he, "גיניאה המשוונית" },
				{ LanguageId.hi, "भूमध्यवर्ती गिनी" },
				{ LanguageId.hr, "Ekvatorijalna Gvineja" },
				{ LanguageId.hsb, "Ekwatorialna Gwineja" },
				{ LanguageId.hu, "Egyenlítői-Guinea" },
				{ LanguageId.hy, "Հասարակածային Գվինեա" },
				{ LanguageId.ia, "Guinea Equatorial" },
				{ LanguageId.ibb, "Equatorial Guinea" },
				{ LanguageId.id, "Guinea ekuator" },
				{ LanguageId.ig, "Equatorial Guinea" },
				{ LanguageId.ii, "ꊺꄔꋒꇬꑍ" },
				{ LanguageId.@is, "Miðbaugs-Gínea" },
				{ LanguageId.it, "Guinea Equatoriale" },
				{ LanguageId.iu, "ᐃᖁᐌᑐᕆᐊᓪ ᒋᓂ" },
				{ LanguageId.ja, "赤道ギニア" },
				{ LanguageId.jgo, "Equatorial Guinea" },
				{ LanguageId.jmc, "Equatorial Guinea" },
				{ LanguageId.jv, "Guinea Khatulistiwa" },
				{ LanguageId.ka, "ეკვატორული გვინეა" },
				{ LanguageId.kab, "Ɣinya Tasebgast" },
				{ LanguageId.kam, "Equatorial Guinea" },
				{ LanguageId.kde, "Equatorial Guinea" },
				{ LanguageId.kea, "Giné Ekuatorial" },
				{ LanguageId.khq, "Equatorial Guinea" },
				{ LanguageId.ki, "Equatorial Guinea" },
				{ LanguageId.kk, "Экваторлық Гвинея" },
				{ LanguageId.kkj, "Equatorial Guinea" },
				{ LanguageId.kl, "Guinea ekvatoriamiut" },
				{ LanguageId.kln, "Equatorial Guinea" },
				{ LanguageId.km, "អេក្វាទ័រហ្គីណេ" },
				{ LanguageId.kn, "ಈಕ್ವಟೋರಿಯಲ್ ಗಿನಿಯಾ" },
				{ LanguageId.ko, "적도기니" },
				{ LanguageId.kok, "इक्वेटोरियल गिनी" },
				{ LanguageId.kr, "Equatorial Guinea" },
				{ LanguageId.ks, "استوائی گنی" },
				{ LanguageId.ksb, "Equatorial Guinea" },
				{ LanguageId.ksf, "Equatorial Guinea" },
				{ LanguageId.ksh, "Äquatorialguinea" },
				{ LanguageId.kw, "Gyni Ekwadorel" },
				{ LanguageId.ky, "Экватордук Гвинея" },
				{ LanguageId.la, "Guinea Aequatorialis" },
				{ LanguageId.lag, "Equatorial Guinea" },
				{ LanguageId.lb, "Äquatorialguinea" },
				{ LanguageId.lg, "Equatorial Guinea" },
				{ LanguageId.lkt, "Equatorial Guinea" },
				{ LanguageId.ln, "Ginɛ́ Ekwatɔ́lɛ" },
				{ LanguageId.lo, "Equatorial Guinea" },
				{ LanguageId.lrc, "گینەی ئیستوایی" },
				{ LanguageId.lt, "Pusiaujo Gvinėja" },
				{ LanguageId.luo, "Equatorial Guinea" },
				{ LanguageId.luy, "Equatorial Guinea" },
				{ LanguageId.lv, "Ekvatoriālā Gvineja" },
				{ LanguageId.mai, "इक्वेटोरियल गिनी" },
				{ LanguageId.mas, "Equatorial Guinea" },
				{ LanguageId.mer, "Equatorial Guinea" },
				{ LanguageId.mfe, "Gine Ekwatoryal" },
				{ LanguageId.mg, "Guinée équatoriale" },
				{ LanguageId.mgo, "Equatorial Guinea" },
				{ LanguageId.mi, "Guinea Equatorial" },
				{ LanguageId.mk, "Екваторијална Гвинеја" },
				{ LanguageId.ml, "ഇക്വറ്റോറിയൽ ഗിനിയ" },
				{ LanguageId.mn, "Экваторын Гвиней" },
				{ LanguageId.mni, "নিরক্ষীয় গিনি" },
				{ LanguageId.moh, "Equatorial Guinea" },
				{ LanguageId.mr, "इक्वेटोरियल गिनी" },
				{ LanguageId.ms, "Guinea Khatulistiwa" },
				{ LanguageId.mt, "Ginea Ekwatorjali" },
				{ LanguageId.mua, "Equatorial Guinea" },
				{ LanguageId.my, "အီကွေတိုရီရယ်ဂီနီ" },
				{ LanguageId.mzn, "استوایی گینه" },
				{ LanguageId.naq, "Equatorial Guinea" },
				{ LanguageId.nb, "Ekvatorial-Guinea" },
				{ LanguageId.nd, "Equatorial Guinea" },
				{ LanguageId.nds, "Äquatorialguinea" },
				{ LanguageId.ne, "इक्वेटोरियल गिनी" },
				{ LanguageId.nl, "Equatoriaal-Guinea" },
				{ LanguageId.nmg, "Equatorial Guinea" },
				{ LanguageId.nn, "Ekvatorial-Guinea" },
				{ LanguageId.nnh, "Equatorial Guinea" },
				{ LanguageId.nqo, "ߖߌ߬ߣߍ߫ ߜߊ߲ߞߎߓߋߘߎ߯" },
				{ LanguageId.nr, "Equatorial Guinea" },
				{ LanguageId.nso, "Equatorial Guinea" },
				{ LanguageId.nus, "Equatorial Guinea" },
				{ LanguageId.nyn, "Equatorial Guinea" },
				{ LanguageId.oc, "Guinea Equatoriala" },
				{ LanguageId.om, "Gini Ekweeteriyaalii" },
				{ LanguageId.or, "ଏକ୍ୟୁଟୋରିଆଲ୍ ଗିନି" },
				{ LanguageId.os, "Экваториалон Гвиней" },
				{ LanguageId.pa, "ਇਕੂਟੇਰੀਅਲ ਗਿਨੀ" },
				{ LanguageId.pap, "Guinea Ekuatorial" },
				{ LanguageId.pcm, "Ikwetọ́ríál Gíní" },
				{ LanguageId.pl, "Gwinea Równikowa" },
				{ LanguageId.prg, "Ekvatorialnā Gvineja" },
				{ LanguageId.ps, "استوایی ګینه" },
				{ LanguageId.pt, "Guiné Equatorial" },
				{ LanguageId.qu, "Guinea Ecuatorial" },
				{ LanguageId.quc, "Equatorial Guinea" },
				{ LanguageId.rm, "Guinea equatoriala" },
				{ LanguageId.rn, "Gineya yo ku Murontsi" },
				{ LanguageId.ro, "Guineea Ecuatorială" },
				{ LanguageId.rof, "Equatorial Guinea" },
				{ LanguageId.ru, "Экваториальная Гвинея" },
				{ LanguageId.rw, "Gineya ya Ekwatoriya" },
				{ LanguageId.rwk, "Equatorial Guinea" },
				{ LanguageId.sa, "इक्वेटोरियल गिनी" },
				{ LanguageId.sah, "Экваториал Гвинея" },
				{ LanguageId.saq, "Equatorial Guinea" },
				{ LanguageId.sat, "ᱤᱠᱣᱮᱴᱳᱨᱤᱭᱟᱞ ᱜᱤᱱᱤ" },
				{ LanguageId.sbp, "Equatorial Guinea" },
				{ LanguageId.sd, "ايڪوٽوريل گائينا" },
				{ LanguageId.se, "Ekvatoriála Guinea" },
				{ LanguageId.seh, "Equatorial Guinea" },
				{ LanguageId.ses, "Equatorial Guinea" },
				{ LanguageId.sg, "Ginëe tî Ekwatëre" },
				{ LanguageId.shi, "ⴳⵉⵏⵢⴰ ⵜⴰⵏⴰⴽⴰⵜⵜ" },
				{ LanguageId.si, "සමක ගිනියාව" },
				{ LanguageId.sk, "rovníková Guinea" },
				{ LanguageId.sl, "Ekvatorialna Gvineja" },
				{ LanguageId.sma, "Ekvatoriála Guinea" },
				{ LanguageId.smj, "Ekvatoriála Guinea" },
				{ LanguageId.smn, "Ekvaattorin Guinea" },
				{ LanguageId.sms, "Ekvatoria Guinea" },
				{ LanguageId.sn, "Ikwetoriya Gini" },
				{ LanguageId.so, "Equatorial Guinea" },
				{ LanguageId.sq, "Guinea Ekuatoriale" },
				{ LanguageId.sr, "Екваторијална Гвинеја" },
				{ LanguageId.ss, "Equatorial Guinea" },
				{ LanguageId.ssy, "Equatorial Guinea" },
				{ LanguageId.st, "Equatorial Guinea" },
				{ LanguageId.su, "Guinea Khatulistiwa" },
				{ LanguageId.sv, "Ekvatorialguinea" },
				{ LanguageId.sw, "Guinea ya Ikweta" },
				{ LanguageId.syr, "ܓܝܢܝܐ ܫܘܝܘܬܐ" },
				{ LanguageId.ta, "எக்குவடோரியல் கினியா" },
				{ LanguageId.te, "ఈక్వటోరియల్ గినియా" },
				{ LanguageId.teo, "Equatorial Guinea" },
				{ LanguageId.tg, "Гвинеяи Экваториалӣ" },
				{ LanguageId.th, "อิเควทอเรียลกินี" },
				{ LanguageId.ti, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.tig, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.tk, "Ekwatorial Gwineýa" },
				{ LanguageId.tn, "Equatorial Guinea" },
				{ LanguageId.to, "Kini ʻEkuētoa" },
				{ LanguageId.tr, "Ekvator Ginesi" },
				{ LanguageId.ts, "Equatorial Guinea" },
				{ LanguageId.tt, "Экваториаль Гвинея" },
				{ LanguageId.twq, "Equatorial Guinea" },
				{ LanguageId.tzm, "ⴳⵉⵏⵢⴰ ⵜⴰⵏⴰⴽⴰⵜⵜ" },
				{ LanguageId.ug, "ئېكۋاتور گۋىنىيىسى" },
				{ LanguageId.uk, "Екваторіальна Гвінея" },
				{ LanguageId.ur, "استوائی گنی" },
				{ LanguageId.uz, "Ekvatorial Gvineya" },
				{ LanguageId.vai, "ꕘꔤꕊ ꕩꕌꕎ" },
				{ LanguageId.ve, "Equatorial Guinea" },
				{ LanguageId.vi, "Equatorial Guinea" },
				{ LanguageId.vo, "Kveatoriala-Gineyän" },
				{ LanguageId.vun, "Equatorial Guinea" },
				{ LanguageId.wae, "Äquatorialguinea" },
				{ LanguageId.wal, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.wo, "Gine Ekwatoriyal" },
				{ LanguageId.xh, "Ekhwithoriyal Gini" },
				{ LanguageId.xog, "Equatorial Guinea" },
				{ LanguageId.yav, "Equatorial Guinea" },
				{ LanguageId.yi, "עקוואַטאָריאַל גיני" },
				{ LanguageId.yo, "Equatorial Guinea" },
				{ LanguageId.zgh, "ⴳⵉⵏⵢⴰ ⵜⴰⵏⴰⴽⴰⵜⵜ" },
				{ LanguageId.zh, "赤道几内亚" },
				{ LanguageId.zu, "I-Equatorial Guinea" },
			}
		);
	}
}
