using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GQ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "240",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Ækvatorial Guinea" },
				{ LanguageId.af, "Ekwatoriaal-Guinee" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኢኳቶሪያል ጊኒ" },
				{ LanguageId.ar, "غينيا الإستوائية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Ekvatorial Qvineya" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Экватарыяльная Гвінея" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Екваториална Гвинея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "নিরক্ষীয় গিনি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Ginea ar C'heheder" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ekvatorijalna Gvineja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Guinea Equatorial" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Equatorial Guinea" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Guinea Equatoriale" },
				{ LanguageId.cs, "Rovníková Guinea" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gini Gyhydeddol" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Äquatorialguinea" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ισημερινή Γουινέα" },
				{ LanguageId.en, "Equatorial Guinea" },
				{ LanguageId.eo, "Ekvatora Gvineo" },
				{ LanguageId.es, "Guinea Ecuatorial" },
				{ LanguageId.et, "Ekvatoriaalne Guinea" },
				{ LanguageId.eu, "Ekuatore Ginea" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "گینه استوایی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Päiväntasaajan Guinea" },
				{ LanguageId.fil, "Equatorial Guinea" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Guinée Équatoriale" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Ekwatoriaal-Guinee" },
				{ LanguageId.ga, "An Ghuine Mheánchriosach" },
				{ LanguageId.gd, "Equatorial Guinea" },
				{ LanguageId.gl, "Guinea Ecuatorial" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "વિષુવવૃત્તીય ગિની" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Equatorial Guinea" },
				{ LanguageId.haw, "Kini ʻEkuakolia" },
				{ LanguageId.he, "גיניאה המשוונית" },
				{ LanguageId.hi, "भूमध्यवर्ती गिनी" },
				{ LanguageId.hr, "Ekvatorijalna Gvineja" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Egyenlítői-Guinea" },
				{ LanguageId.hy, "Հասարակածային Գվինեա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Guinea ekuator" },
				{ LanguageId.ig, "Equatorial Guinea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Miðbaugs-Gínea" },
				{ LanguageId.it, "Guinea Equatoriale" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "赤道ギニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Guinea Khatulistiwa" },
				{ LanguageId.ka, "ეკვატორული გვინეა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Экваторлық Гвинея" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "អេក្វាទ័រហ្គីណេ" },
				{ LanguageId.kn, "ಈಕ್ವಟೋರಿಯಲ್ ಗಿನಿಯಾ" },
				{ LanguageId.ko, "적도기니" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Экватордук Гвинея" },
				{ LanguageId.la, "Guinea Aequatorialis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Äquatorialguinea" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Equatorial Guinea" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Pusiaujo Gvinėja" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Ekvatoriālā Gvineja" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Guinée équatoriale" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Guinea Equatorial" },
				{ LanguageId.mk, "Екваторијална Гвинеја" },
				{ LanguageId.ml, "ഇക്വറ്റോറിയൽ ഗിനിയ" },
				{ LanguageId.mn, "Экваторын Гвиней" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "इक्वेटोरियल गिनी" },
				{ LanguageId.ms, "Guinea Khatulistiwa" },
				{ LanguageId.mt, "Ginea Ekwatorjali" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အီကွေတိုရီရယ်ဂီနီ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Ekvatorial-Guinea" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "इक्वेटोरियल गिनी" },
				{ LanguageId.nl, "Equatoriaal-Guinea" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଏକ୍ୟୁଟୋରିଆଲ୍ ଗିନି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਇਕੂਟੇਰੀਅਲ ਗਿਨੀ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Gwinea Równikowa" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "استوایی ګینه" },
				{ LanguageId.pt, "Guiné Equatorial" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Guineea Ecuatorială" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Экваториальная Гвинея" },
				{ LanguageId.rw, "Gineya ya Ekwatoriya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ايڪوٽوريل گائينا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සමක ගිනියාව" },
				{ LanguageId.sk, "rovníková Guinea" },
				{ LanguageId.sl, "Ekvatorialna Gvineja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Ikwetoriya Gini" },
				{ LanguageId.so, "Equatorial Guinea" },
				{ LanguageId.sq, "Guinea Ekuatoriale" },
				{ LanguageId.sr, "Екваторијална Гвинеја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Equatorial Guinea" },
				{ LanguageId.su, "Guinea Khatulistiwa" },
				{ LanguageId.sv, "Ekvatorialguinea" },
				{ LanguageId.sw, "Guinea ya Ikweta" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "எக்குவடோரியல் கினியா" },
				{ LanguageId.te, "ఈక్వటోరియల్ గినియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Гвинеяи Экваториалӣ" },
				{ LanguageId.th, "อิเควทอเรียลกินี" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Ekwatorial Gwineýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Ekvator Ginesi" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Экваториаль Гвинея" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ئېكۋاتور گۋىنىيىسى" },
				{ LanguageId.uk, "Екваторіальна Гвінея" },
				{ LanguageId.ur, "استوائی گنی" },
				{ LanguageId.uz, "Ekvatorial Gvineya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Equatorial Guinea" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Ekhwithoriyal Gini" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "עקוואַטאָריאַל גיני" },
				{ LanguageId.yo, "Equatorial Guinea" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "赤道几内亚" },
				{ LanguageId.zu, "I-Equatorial Guinea" },
			}
		);
	}
}
