using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GW
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "245",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Guinea-Bissau" },
				{ LanguageId.af, "Guinee-Bissau" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ጊኒ-ቢሳው" },
				{ LanguageId.ar, "غينيا بيساو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Qvineya-Bisau" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Гвінея-Бісаў" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Гвинея-Бисау" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "গিনি-বিসাউ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Gvineja Bisau" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Guinea Bissau" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Guinea-Bissau" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Guinea-Bissau" },
				{ LanguageId.cs, "Guinea-Bissau" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gini-Bissau" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Guinea-Bissau" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Γουινέα-Μπισάου" },
				{ LanguageId.en, "Guinea-Bissau" },
				{ LanguageId.eo, "Gvineo Bisaŭa" },
				{ LanguageId.es, "Guinea-Bisáu" },
				{ LanguageId.et, "Guinea-Bissau" },
				{ LanguageId.eu, "Ginea-Bissau" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "گینه بیسائو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Guinea-Bissau" },
				{ LanguageId.fil, "Guinea-Bissau" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Guinée-Bissau" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Guinee-Bissau" },
				{ LanguageId.ga, "Guine Bhissau" },
				{ LanguageId.gd, "Guinea-Bissau" },
				{ LanguageId.gl, "Guinea-Bissau" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ગિની-બિસાઉ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Guinea-Bissau" },
				{ LanguageId.haw, "Kinibisau" },
				{ LanguageId.he, "גינאה-ביסאו" },
				{ LanguageId.hi, "गिनी-बिसाऊ" },
				{ LanguageId.hr, "Gvineja Bisau" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Bissau-Guinea" },
				{ LanguageId.hy, "Գվինեա-Բիսաու" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Guinea-Bissau" },
				{ LanguageId.ig, "Guinea-Bissau" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Gíneu-Bissá" },
				{ LanguageId.it, "Guinea-Bissau" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ギニアビサウ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Guinea-Bissau" },
				{ LanguageId.ka, "გვინეა-ბისაუ" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Гвинея-Бисау" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ហ្គីណេ-ប៊ីសា" },
				{ LanguageId.kn, "ಗಿನಿ-ಬಿಸ್ಸೌ" },
				{ LanguageId.ko, "기니비사우" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Гвинея-Бисау" },
				{ LanguageId.la, "Guinea-Bissau" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Guinea-Bissau" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Guinea-Bissau" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Bisau Gvinėja" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Gvineja-Bisava" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Guinée-Bissau" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Guinea-Bissau" },
				{ LanguageId.mk, "Гвинеја-Бисао" },
				{ LanguageId.ml, "ഗിനിയ-ബിസാവു" },
				{ LanguageId.mn, "Гвиней-Бисау" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "गिनी-बिसाऊ" },
				{ LanguageId.ms, "Guinea-Bissau" },
				{ LanguageId.mt, "Ginea Bissaw" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဂီနီဘစ်ဆော" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Guinea-Bissau" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "गिनी-बिसाउ" },
				{ LanguageId.nl, "Guinee-Bissau" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଗିନି-ବିସାଉ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਗਿਨੀ-ਬਿਸਾਉ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Gwinea Bissau" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ګینه بیسو" },
				{ LanguageId.pt, "Guiné-Bissau" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Guineea-Bissau" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Гвинея-Бисау" },
				{ LanguageId.rw, "Gineya-Bissau" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "گائينا-بسيو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ගිනියා-බිසාවු" },
				{ LanguageId.sk, "Guinea-Bissau" },
				{ LanguageId.sl, "Gvineja Bissau" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Gini Bhisau" },
				{ LanguageId.so, "Guinea-Bissau" },
				{ LanguageId.sq, "Guinea-Bissau" },
				{ LanguageId.sr, "Гвинеја Бисао" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Guinea-Bissau" },
				{ LanguageId.su, "Guinea-Bissau" },
				{ LanguageId.sv, "Guinea-Bissau" },
				{ LanguageId.sw, "Guinea-Bissau" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கினியா-பிசாவ்" },
				{ LanguageId.te, "గినియా-బిస్సావు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Гвинея-Бисау" },
				{ LanguageId.th, "กินี-บิสเซา" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Gwineýa-Bissau" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Gine-Bissau" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Гвинея-Бисау" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "گۋىنىيە-بىسساۋ" },
				{ LanguageId.uk, "Гвінея-Бісау" },
				{ LanguageId.ur, "گنی بساؤ" },
				{ LanguageId.uz, "Gvineya-Bisau" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Guiné-Bissau" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Gini-Bisawu" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "גיני-ביסאַו" },
				{ LanguageId.yo, "Guinea-Bissau" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "几内亚比绍" },
				{ LanguageId.zu, "I-Guinea-Bissau" },
			}
		);
	}
}
