using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class GW
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "245",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Guinea-Bissau" },
				{ LanguageId.da, "Guinea-Bissau" },
				{ LanguageId.af, "Guinee-Bissau" },
				{ LanguageId.agq, "Guinea-Bissau" },
				{ LanguageId.ak, "Guinea-Bissau" },
				{ LanguageId.am, "ጊኒ-ቢሳው" },
				{ LanguageId.ar, "غينيا بيساو" },
				{ LanguageId.arn, "Guinea-Bissau" },
				{ LanguageId.@as, "গিনি-বিসাউ" },
				{ LanguageId.asa, "Guinea-Bissau" },
				{ LanguageId.ast, "Guinea-Bissáu" },
				{ LanguageId.az, "Qvineya-Bisau" },
				{ LanguageId.ba, "Гвинея-Бисау" },
				{ LanguageId.bas, "Guinea-Bissau" },
				{ LanguageId.be, "Гвінея-Бісаў" },
				{ LanguageId.bem, "Guinea-Bissau" },
				{ LanguageId.bez, "Guinea-Bissau" },
				{ LanguageId.bg, "Гвинея-Бисау" },
				{ LanguageId.bin, "Guinea-Bissau" },
				{ LanguageId.bm, "Gine-Bisawu" },
				{ LanguageId.bn, "গিনি-বিসাউ" },
				{ LanguageId.bo, "གི་ནེ་-བི་སའོ།" },
				{ LanguageId.br, "Ginea-Bissau" },
				{ LanguageId.brx, "Guinea-Bissau" },
				{ LanguageId.bs, "Gvineja Bisau" },
				{ LanguageId.byn, "Guinea-Bissau" },
				{ LanguageId.ca, "Guinea Bissau" },
				{ LanguageId.ccp, "Guinea-Bissau" },
				{ LanguageId.ce, "Гвинея-Бисау" },
				{ LanguageId.ceb, "Guinea-Bissau" },
				{ LanguageId.cgg, "Guinea-Bissau" },
				{ LanguageId.chr, "Guinea-Bissau" },
				{ LanguageId.ckb, "گینێ بیساو" },
				{ LanguageId.co, "Guinea-Bissau" },
				{ LanguageId.cs, "Guinea-Bissau" },
				{ LanguageId.cu, "Guinea-Bissau" },
				{ LanguageId.cy, "Gini-Bissau" },
				{ LanguageId.dav, "Guinea-Bissau" },
				{ LanguageId.de, "Guinea-Bissau" },
				{ LanguageId.dje, "Guinea-Bissau" },
				{ LanguageId.doi, "Guinea-Bissau" },
				{ LanguageId.dsb, "Guinea-Bissau" },
				{ LanguageId.dua, "Guinea-Bissau" },
				{ LanguageId.dv, "ގީނިއާ-ބިސާއޫ" },
				{ LanguageId.dz, "གི་ནེ་-བི་སའོ།" },
				{ LanguageId.ebu, "Guinea-Bissau" },
				{ LanguageId.ee, "Guinea-Bissau" },
				{ LanguageId.el, "Γουινέα-Μπισάου" },
				{ LanguageId.en, "Guinea-Bissau" },
				{ LanguageId.eo, "Gvineo Bisaŭa" },
				{ LanguageId.es, "Guinea-Bisáu" },
				{ LanguageId.et, "Guinea-Bissau" },
				{ LanguageId.eu, "Ginea-Bissau" },
				{ LanguageId.ewo, "Guinea-Bissau" },
				{ LanguageId.fa, "گینه بیسائو" },
				{ LanguageId.ff, "Gine-Bisaawo" },
				{ LanguageId.fi, "Guinea-Bissau" },
				{ LanguageId.fil, "Guinea-Bissau" },
				{ LanguageId.fo, "Guinea-Bissau" },
				{ LanguageId.fr, "Guinée-Bissau" },
				{ LanguageId.fur, "Guinea-Bissau" },
				{ LanguageId.fy, "Guinee-Bissau" },
				{ LanguageId.ga, "Guine Bhissau" },
				{ LanguageId.gd, "Guinea-Bissau" },
				{ LanguageId.gl, "Guinea-Bissau" },
				{ LanguageId.gn, "Guinea-Bissau" },
				{ LanguageId.gsw, "Guinea-Bissau" },
				{ LanguageId.gu, "ગિની-બિસાઉ" },
				{ LanguageId.guz, "Guinea-Bissau" },
				{ LanguageId.gv, "Guinea-Bissau" },
				{ LanguageId.ha, "Guinea-Bissau" },
				{ LanguageId.haw, "Kinibisau" },
				{ LanguageId.he, "גינאה-ביסאו" },
				{ LanguageId.hi, "गिनी-बिसाऊ" },
				{ LanguageId.hr, "Gvineja Bisau" },
				{ LanguageId.hsb, "Guinea-Bissau" },
				{ LanguageId.hu, "Bissau-Guinea" },
				{ LanguageId.hy, "Գվինեա-Բիսաու" },
				{ LanguageId.ia, "Guinea-Bissau" },
				{ LanguageId.ibb, "Guinea-Bissau" },
				{ LanguageId.id, "Guinea-Bissau" },
				{ LanguageId.ig, "Guinea-Bissau" },
				{ LanguageId.ii, "Guinea-Bissau" },
				{ LanguageId.@is, "Gíneu-Bissá" },
				{ LanguageId.it, "Guinea-Bissau" },
				{ LanguageId.iu, "Guinea-Bissau" },
				{ LanguageId.ja, "ギニアビサウ" },
				{ LanguageId.jgo, "Guinea-Bissau" },
				{ LanguageId.jmc, "Guinea-Bissau" },
				{ LanguageId.jv, "Guinea-Bissau" },
				{ LanguageId.ka, "გვინეა-ბისაუ" },
				{ LanguageId.kab, "Guinea-Bissau" },
				{ LanguageId.kam, "Guinea-Bissau" },
				{ LanguageId.kde, "Guinea-Bissau" },
				{ LanguageId.kea, "Guiné-Bisau" },
				{ LanguageId.khq, "Guinea-Bissau" },
				{ LanguageId.ki, "Guinea-Bissau" },
				{ LanguageId.kk, "Гвинея-Бисау" },
				{ LanguageId.kkj, "Guinea-Bissau" },
				{ LanguageId.kl, "Guinea-Bissau" },
				{ LanguageId.kln, "Guinea-Bissau" },
				{ LanguageId.km, "ហ្គីណេ-ប៊ីសា" },
				{ LanguageId.kn, "ಗಿನಿ-ಬಿಸ್ಸೌ" },
				{ LanguageId.ko, "기니비사우" },
				{ LanguageId.kok, "गिनी-बिसाऊ" },
				{ LanguageId.kr, "Guinea-Bissau" },
				{ LanguageId.ks, "گنی بساؤ" },
				{ LanguageId.ksb, "Guinea-Bissau" },
				{ LanguageId.ksf, "Guinea-Bissau" },
				{ LanguageId.ksh, "Guinea-Bissau" },
				{ LanguageId.kw, "Gyni-Bissaw" },
				{ LanguageId.ky, "Гвинея-Бисау" },
				{ LanguageId.la, "Guinea-Bissau" },
				{ LanguageId.lag, "Guinea-Bissau" },
				{ LanguageId.lb, "Guinea-Bissau" },
				{ LanguageId.lg, "Guinea-Bissau" },
				{ LanguageId.lkt, "Guinea-Bissau" },
				{ LanguageId.ln, "Gine-Bisau" },
				{ LanguageId.lo, "Guinea-Bissau" },
				{ LanguageId.lrc, "گینه بیساو" },
				{ LanguageId.lt, "Bisau Gvinėja" },
				{ LanguageId.luo, "Guinea-Bissau" },
				{ LanguageId.luy, "Guinea-Bissau" },
				{ LanguageId.lv, "Gvineja-Bisava" },
				{ LanguageId.mai, "गिनी-बिसाउ" },
				{ LanguageId.mas, "Guinea-Bissau" },
				{ LanguageId.mer, "Guinea-Bissau" },
				{ LanguageId.mfe, "Guinée-Bissau" },
				{ LanguageId.mg, "Guinée-Bissau" },
				{ LanguageId.mgo, "Guinea-Bissau" },
				{ LanguageId.mi, "Guinea-Bissau" },
				{ LanguageId.mk, "Гвинеја-Бисао" },
				{ LanguageId.ml, "ഗിനിയ-ബിസാവു" },
				{ LanguageId.mn, "Гвиней-Бисау" },
				{ LanguageId.mni, "Guinea-Bissau" },
				{ LanguageId.moh, "Guinea-Bissau" },
				{ LanguageId.mr, "गिनी-बिसाऊ" },
				{ LanguageId.ms, "Guinea-Bissau" },
				{ LanguageId.mt, "Ginea Bissaw" },
				{ LanguageId.mua, "Guinea-Bissau" },
				{ LanguageId.my, "ဂီနီဘစ်ဆော" },
				{ LanguageId.mzn, "گینه بیسائو" },
				{ LanguageId.naq, "Guinea-Bissau" },
				{ LanguageId.nb, "Guinea-Bissau" },
				{ LanguageId.nd, "Guinea-Bissau" },
				{ LanguageId.nds, "Guinea-Bissau" },
				{ LanguageId.ne, "गिनी-बिसाउ" },
				{ LanguageId.nl, "Guinee-Bissau" },
				{ LanguageId.nmg, "Guinea-Bissau" },
				{ LanguageId.nn, "Guinea-Bissau" },
				{ LanguageId.nnh, "Guinea-Bissau" },
				{ LanguageId.nqo, "Guinea-Bissau" },
				{ LanguageId.nr, "Guinea-Bissau" },
				{ LanguageId.nso, "Guinea-Bissau" },
				{ LanguageId.nus, "Guinea-Bissau" },
				{ LanguageId.nyn, "Guinea-Bissau" },
				{ LanguageId.oc, "Guinèa Bissau" },
				{ LanguageId.om, "Giinii-Bisaawu" },
				{ LanguageId.or, "ଗିନି-ବିସାଉ |" },
				{ LanguageId.os, "Гвинея-Бисау" },
				{ LanguageId.pa, "ਗਿਨੀ-ਬਿਸਾਉ" },
				{ LanguageId.pap, "Guinea-Bissau" },
				{ LanguageId.pcm, "Guinea-Bissau" },
				{ LanguageId.pl, "Gwinea Bissau" },
				{ LanguageId.prg, "Guinea-Bissau" },
				{ LanguageId.ps, "ګینه بیسو" },
				{ LanguageId.pt, "Guiné-Bissau" },
				{ LanguageId.qu, "Guinea-Bissau" },
				{ LanguageId.quc, "Guinea-Bissau" },
				{ LanguageId.rm, "Guinea-Bissau" },
				{ LanguageId.rn, "Gineya-Bisawu" },
				{ LanguageId.ro, "Guineea-Bissau" },
				{ LanguageId.rof, "Guinea-Bissau" },
				{ LanguageId.ru, "Гвинея-Бисау" },
				{ LanguageId.rw, "Gineya-Bissau" },
				{ LanguageId.rwk, "Guinea-Bissau" },
				{ LanguageId.sa, "गिनी-बिसाऊ" },
				{ LanguageId.sah, "Гвинея-Бисау" },
				{ LanguageId.saq, "Guinea-Bissau" },
				{ LanguageId.sat, "Guinea-Bissau" },
				{ LanguageId.sbp, "Guinea-Bissau" },
				{ LanguageId.sd, "گائينا-بسيو" },
				{ LanguageId.se, "Guinea-Bissau" },
				{ LanguageId.seh, "Guiné-Bissau" },
				{ LanguageId.ses, "Guinea-Bissau" },
				{ LanguageId.sg, "Guinea-Bissau" },
				{ LanguageId.shi, "Guinea-Bissau" },
				{ LanguageId.si, "ගිනියා-බිසාවු" },
				{ LanguageId.sk, "Guinea-Bissau" },
				{ LanguageId.sl, "Gvineja Bissau" },
				{ LanguageId.sma, "Guinea-Bissau" },
				{ LanguageId.smj, "Guinea-Bissau" },
				{ LanguageId.smn, "Guinea-Bissau" },
				{ LanguageId.sms, "Guinea-Bissau" },
				{ LanguageId.sn, "Gini Bhisau" },
				{ LanguageId.so, "Guinea-Bissau" },
				{ LanguageId.sq, "Guinea-Bissau" },
				{ LanguageId.sr, "Гвинеја Бисао" },
				{ LanguageId.ss, "Guinea-Bissau" },
				{ LanguageId.ssy, "Guinea-Bissau" },
				{ LanguageId.st, "Guinea-Bissau" },
				{ LanguageId.su, "Guinea-Bissau" },
				{ LanguageId.sv, "Guinea-Bissau" },
				{ LanguageId.sw, "Guinea-Bissau" },
				{ LanguageId.syr, "Guinea-Bissau" },
				{ LanguageId.ta, "கினியா-பிசாவ்" },
				{ LanguageId.te, "గినియా-బిస్సావు" },
				{ LanguageId.teo, "Guinea-Bissau" },
				{ LanguageId.tg, "Гвинея-Бисау" },
				{ LanguageId.th, "กินี-บิสเซา" },
				{ LanguageId.ti, "Guinea-Bissau" },
				{ LanguageId.tig, "Guinea-Bissau" },
				{ LanguageId.tk, "Gwineýa-Bissau" },
				{ LanguageId.tn, "Guinea-Bissau" },
				{ LanguageId.to, "Kini-Pisau" },
				{ LanguageId.tr, "Gine-Bissau" },
				{ LanguageId.ts, "Guinea-Bissau" },
				{ LanguageId.tt, "Гвинея-Бисау" },
				{ LanguageId.twq, "Guinea-Bissau" },
				{ LanguageId.tzm, "Guinea-Bissau" },
				{ LanguageId.ug, "گۋىنىيە-بىسساۋ" },
				{ LanguageId.uk, "Гвінея-Бісау" },
				{ LanguageId.ur, "گنی بساؤ" },
				{ LanguageId.uz, "Gvineya-Bisau" },
				{ LanguageId.vai, "Guinea-Bissau" },
				{ LanguageId.ve, "Guinea-Bissau" },
				{ LanguageId.vi, "Guiné-Bissau" },
				{ LanguageId.vo, "Gvineän-Bisauän" },
				{ LanguageId.vun, "Guinea-Bissau" },
				{ LanguageId.wae, "Guinea-Bissau" },
				{ LanguageId.wal, "Guinea-Bissau" },
				{ LanguageId.wo, "Gine-Bisaawóo" },
				{ LanguageId.xh, "Gini-Bisawu" },
				{ LanguageId.xog, "Guinea-Bissau" },
				{ LanguageId.yav, "Guinea-Bissau" },
				{ LanguageId.yi, "גיני-ביסאַו" },
				{ LanguageId.yo, "Guinea-Bissau" },
				{ LanguageId.zgh, "Guinea-Bissau" },
				{ LanguageId.zh, "几内亚比绍" },
				{ LanguageId.zu, "I-Guinea-Bissau" },
			}
		);
	}
}
