// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class GW
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "245",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Guinea-Bissau" },
				{ LanguageId.da, "Guinea-Bissau" },
				{ LanguageId.af, "Guinee-Bissau" },
				{ LanguageId.agq, "Ginè Bìsawù" },
				{ LanguageId.ak, "Gini Bisaw" },
				{ LanguageId.am, "ጊኒ-ቢሳው" },
				{ LanguageId.ar, "غينيا بيساو" },
				{ LanguageId.arn, "Guinea-Bissau" },
				{ LanguageId.@as, "গিনি-বিছাও" },
				{ LanguageId.asa, "Ginebisau" },
				{ LanguageId.ast, "Guinea-Bisáu" },
				{ LanguageId.az, "Qvineya-Bisau" },
				{ LanguageId.ba, "Гвинея-Бисау" },
				{ LanguageId.bas, "Gìne Bìsàô" },
				{ LanguageId.be, "Гвінея-Бісау" },
				{ LanguageId.bem, "Guinea-Bissau" },
				{ LanguageId.bez, "Huginebisau" },
				{ LanguageId.bg, "Гвинея-Бисау" },
				{ LanguageId.bin, "Guinea-Bissau" },
				{ LanguageId.bm, "Gine Bisawo" },
				{ LanguageId.bn, "গিনি-বিসাউ" },
				{ LanguageId.bo, "གི་ནེ་-བི་སའོ།" },
				{ LanguageId.br, "Ginea-Bissau" },
				{ LanguageId.brx, "गिनीया- बिसाऊ" },
				{ LanguageId.bs, "Gvineja-Bisao" },
				{ LanguageId.byn, "Guinea-Bissau" },
				{ LanguageId.ca, "Guinea Bissau" },
				{ LanguageId.ccp, "𑄉𑄨𑄚𑄨-𑄝𑄨𑄥𑄃𑄪" },
				{ LanguageId.ce, "Гвиней-Бисау" },
				{ LanguageId.ceb, "Guinea-Bissau" },
				{ LanguageId.cgg, "Ginebisau" },
				{ LanguageId.chr, "ᎩᎢᏂ-ᏈᏌᎤᏫ" },
				{ LanguageId.ckb, "گینێ بیساو" },
				{ LanguageId.co, "Guinea-Bissau" },
				{ LanguageId.cs, "Guinea-Bissau" },
				{ LanguageId.cu, "Guinea-Bissau" },
				{ LanguageId.cy, "Guiné-Bissau" },
				{ LanguageId.dav, "Ginebisau" },
				{ LanguageId.de, "Guinea-Bissau" },
				{ LanguageId.dje, "Gine-Bisso" },
				{ LanguageId.doi, "Guinea-Bissau" },
				{ LanguageId.dsb, "Gineja-Bissau" },
				{ LanguageId.dua, "Guinea-Bissau" },
				{ LanguageId.dv, "ގީނިއާ-ބިސާއޫ" },
				{ LanguageId.dz, "གྷི་ནི་ བྷི་སཱའུ" },
				{ LanguageId.ebu, "Ginebisau" },
				{ LanguageId.ee, "Gini-Bisao nutome" },
				{ LanguageId.el, "Γουινέα Μπισάου" },
				{ LanguageId.en, "Guinea-Bissau" },
				{ LanguageId.eo, "Gvineo-Bisaŭo" },
				{ LanguageId.es, "Guinea-Bisáu" },
				{ LanguageId.et, "Guinea-Bissau" },
				{ LanguageId.eu, "Ginea Bissau" },
				{ LanguageId.ewo, "Giné Bisaó" },
				{ LanguageId.fa, "گینهٔ بیسائو" },
				{ LanguageId.ff, "Gine-Bisaawo" },
				{ LanguageId.fi, "Guinea-Bissau" },
				{ LanguageId.fil, "Guinea-Bissau" },
				{ LanguageId.fo, "Guinea-Bissau" },
				{ LanguageId.fr, "Guinée-Bissau" },
				{ LanguageId.fur, "Guinea-Bissau" },
				{ LanguageId.fy, "Guinee-Bissau" },
				{ LanguageId.ga, "Guine Bissau" },
				{ LanguageId.gd, "Gini-Bioso" },
				{ LanguageId.gl, "Guinea Bissau" },
				{ LanguageId.gn, "Guinea-Bissau" },
				{ LanguageId.gsw, "Gineea-Bissau" },
				{ LanguageId.gu, "ગિની-બિસાઉ" },
				{ LanguageId.guz, "Ginebisau" },
				{ LanguageId.gv, "Guinea-Bissau" },
				{ LanguageId.ha, "Gini Bisau" },
				{ LanguageId.haw, "Kinibisau" },
				{ LanguageId.he, "גינאה-ביסאו" },
				{ LanguageId.hi, "गिनी-बिसाउ" },
				{ LanguageId.hr, "Gvineja Bisau" },
				{ LanguageId.hsb, "Gineja-Bissau" },
				{ LanguageId.hu, "Bissau-Guinea" },
				{ LanguageId.hy, "Գվինեա-Բիսաու" },
				{ LanguageId.ia, "Guinea-Bissau" },
				{ LanguageId.ibb, "Guinea-Bissau" },
				{ LanguageId.id, "Guinea-Bissau" },
				{ LanguageId.ig, "Guinea-Bissau" },
				{ LanguageId.ii, "Guinea-Bissau" },
				{ LanguageId.@is, "Gínea-Bissá" },
				{ LanguageId.it, "Guinea-Bissau" },
				{ LanguageId.iu, "Guinea-Bissau" },
				{ LanguageId.ja, "ギニアビサウ" },
				{ LanguageId.jgo, "Ŋginɛ̂ Mbisáwu" },
				{ LanguageId.jmc, "Ginebisau" },
				{ LanguageId.jv, "Guinea-Bissau" },
				{ LanguageId.ka, "გვინეა-ბისაუ" },
				{ LanguageId.kab, "Ɣinya-Bisaw" },
				{ LanguageId.kam, "Ginebisau" },
				{ LanguageId.kde, "Ginebisau" },
				{ LanguageId.kea, "Gine-Bisau" },
				{ LanguageId.khq, "Gine-Bisso" },
				{ LanguageId.ki, "Ginebisau" },
				{ LanguageId.kk, "Гвинея-Бисау" },
				{ LanguageId.kkj, "Guinea-Bissau" },
				{ LanguageId.kl, "Guinea-Bissau" },
				{ LanguageId.kln, "Emetab Guinea-Bissau" },
				{ LanguageId.km, "ហ្គីណេប៊ីស្សូ" },
				{ LanguageId.kn, "ಗಿನಿ-ಬಿಸ್ಸಾವ್" },
				{ LanguageId.ko, "기니비사우" },
				{ LanguageId.kok, "गिनी-बिसाउ" },
				{ LanguageId.kr, "Guinea-Bissau" },
				{ LanguageId.ks, "گیٖنی بِساو" },
				{ LanguageId.ksb, "Ginebisau" },
				{ LanguageId.ksf, "ginɛ́ bisɔ́" },
				{ LanguageId.ksh, "Jinneha_Bißau" },
				{ LanguageId.kw, "Gyni-Bissaw" },
				{ LanguageId.ky, "Гвинея-Бисау" },
				{ LanguageId.la, "Guinea-Bissau" },
				{ LanguageId.lag, "Gíine Bisáau" },
				{ LanguageId.lb, "Guinea-Bissau" },
				{ LanguageId.lg, "Gini-Bisawu" },
				{ LanguageId.lkt, "Guinea-Bissau" },
				{ LanguageId.ln, "Ginɛbisau" },
				{ LanguageId.lo, "ກິນີ-ບິສເຊົາ" },
				{ LanguageId.lrc, "گینه بیساو" },
				{ LanguageId.lt, "Bisau Gvinėja" },
				{ LanguageId.luo, "Guinea-Bissau" },
				{ LanguageId.luy, "Ginebisau" },
				{ LanguageId.lv, "Gvineja-Bisava" },
				{ LanguageId.mai, "गिनी-बिसाऊ" },
				{ LanguageId.mas, "Ginebisau" },
				{ LanguageId.mer, "Ginebisau" },
				{ LanguageId.mfe, "Gine-Bisau" },
				{ LanguageId.mg, "Giné-Bisao" },
				{ LanguageId.mgo, "Guinea-Bissau" },
				{ LanguageId.mi, "Kini-Pihao" },
				{ LanguageId.mk, "Гвинеја Бисао" },
				{ LanguageId.ml, "ഗിനിയ-ബിസൗ" },
				{ LanguageId.mn, "Гвиней-Бисау" },
				{ LanguageId.mni, "Guinea-Bissau" },
				{ LanguageId.moh, "Guinea-Bissau" },
				{ LanguageId.mr, "गिनी-बिसाउ" },
				{ LanguageId.ms, "Guinea Bissau" },
				{ LanguageId.mt, "il-Guinea-Bissau" },
				{ LanguageId.mua, "Guine ma Bissao" },
				{ LanguageId.my, "ဂီနီ-ဘီစော" },
				{ LanguageId.mzn, "گینه بیسائو" },
				{ LanguageId.naq, "Guinea-Bissau" },
				{ LanguageId.nb, "Guinea-Bissau" },
				{ LanguageId.nd, "Guinea-Bissau" },
				{ LanguageId.nds, "Guinea-Bissau" },
				{ LanguageId.ne, "गिनी-बिसाउ" },
				{ LanguageId.nl, "Guinee-Bissau" },
				{ LanguageId.nmg, "Guine Bisso" },
				{ LanguageId.nn, "Guinea-Bissau" },
				{ LanguageId.nnh, "Guinea-Bissau" },
				{ LanguageId.nqo, "ߖߌ߬ߣߍ߫ ߓߌߛߊߥߏ߫" },
				{ LanguageId.nr, "Guinea-Bissau" },
				{ LanguageId.nso, "Guinea-Bissau" },
				{ LanguageId.nus, "Guinea-Bissau" },
				{ LanguageId.nyn, "Ginebisau" },
				{ LanguageId.oc, "Guinèa Bissau" },
				{ LanguageId.om, "Giinii-Bisaawoo" },
				{ LanguageId.or, "ଗୁଇନିଆ-ବିସାଉ" },
				{ LanguageId.os, "Гвинея-Бисау" },
				{ LanguageId.pa, "ਗਿਨੀ-ਬਿਸਾਉ" },
				{ LanguageId.pap, "Guinea-Bissau" },
				{ LanguageId.pcm, "Gíní-Bisáu" },
				{ LanguageId.pl, "Gwinea Bissau" },
				{ LanguageId.prg, "Guinea-Bissau" },
				{ LanguageId.ps, "ګینه بیسو" },
				{ LanguageId.pt, "Guiné-Bissau" },
				{ LanguageId.qu, "Guinea-Bisáu" },
				{ LanguageId.quc, "Guinea-Bissau" },
				{ LanguageId.rm, "Guinea-Bissau" },
				{ LanguageId.rn, "Gineya Bisawu" },
				{ LanguageId.ro, "Guineea-Bissau" },
				{ LanguageId.rof, "Ginebisau" },
				{ LanguageId.ru, "Гвинея-Бисау" },
				{ LanguageId.rw, "Gineya-Bissau" },
				{ LanguageId.rwk, "Ginebisau" },
				{ LanguageId.sa, "गिनी-बिसाऊ" },
				{ LanguageId.sah, "Гвинея-Бисау" },
				{ LanguageId.saq, "Ginebisau" },
				{ LanguageId.sat, "Guinea-Bissau" },
				{ LanguageId.sbp, "Ginebisawu" },
				{ LanguageId.sd, "گني بسائو" },
				{ LanguageId.se, "Guinea-Bissau" },
				{ LanguageId.seh, "Guiné Bissau" },
				{ LanguageId.ses, "Gine-Bisso" },
				{ LanguageId.sg, "Gninëe-Bisau" },
				{ LanguageId.shi, "ⵖⵉⵏⵢⴰ ⴱⵉⵙⴰⵡ" },
				{ LanguageId.si, "ගිනි බිසව්" },
				{ LanguageId.sk, "Guinea-Bissau" },
				{ LanguageId.sl, "Gvineja Bissau" },
				{ LanguageId.sma, "Guinea-Bissau" },
				{ LanguageId.smj, "Guinea-Bissau" },
				{ LanguageId.smn, "Guinea-Bissau" },
				{ LanguageId.sms, "Guinea-Bissau" },
				{ LanguageId.sn, "Guinea-Bissau" },
				{ LanguageId.so, "Gini-Bisaaw" },
				{ LanguageId.sq, "Guine-Bisau" },
				{ LanguageId.sr, "Гвинеја-Бисао" },
				{ LanguageId.ss, "Guinea-Bissau" },
				{ LanguageId.ssy, "Guinea-Bissau" },
				{ LanguageId.st, "Guinea-Bissau" },
				{ LanguageId.su, "Guinea-Bissau" },
				{ LanguageId.sv, "Guinea-Bissau" },
				{ LanguageId.sw, "Ginebisau" },
				{ LanguageId.syr, "ܓܝܢܝܐ ܒܝܣܐܘ" },
				{ LanguageId.ta, "கினியா-பிஸ்ஸாவ்" },
				{ LanguageId.te, "గినియా-బిస్సావ్" },
				{ LanguageId.teo, "Ginebisau" },
				{ LanguageId.tg, "Гвинея-Бисау" },
				{ LanguageId.th, "กินี-บิสเซา" },
				{ LanguageId.ti, "ጊኒ-ቢሳው" },
				{ LanguageId.tig, "Guinea-Bissau" },
				{ LanguageId.tk, "Gwineýa-Bisau" },
				{ LanguageId.tn, "Guinea-Bissau" },
				{ LanguageId.to, "Kini-Pisau" },
				{ LanguageId.tr, "Gine-Bissau" },
				{ LanguageId.ts, "Guinea-Bissau" },
				{ LanguageId.tt, "Гвинея-Бисау" },
				{ LanguageId.twq, "Gine-Bisso" },
				{ LanguageId.tzm, "Ɣinya-Bissaw" },
				{ LanguageId.ug, "گىۋىنىيە بىسسائۇ" },
				{ LanguageId.uk, "Гвінея-Бісау" },
				{ LanguageId.ur, "گنی بساؤ" },
				{ LanguageId.uz, "Gvineya-Bisau" },
				{ LanguageId.vai, "ꕅꔤꕇ ꔫꕢꕴ" },
				{ LanguageId.ve, "Guinea-Bissau" },
				{ LanguageId.vi, "Guinea-Bissau" },
				{ LanguageId.vo, "Gvineän-Bisauän" },
				{ LanguageId.vun, "Ginebisau" },
				{ LanguageId.wae, "Ginea Bissau" },
				{ LanguageId.wal, "Guinea-Bissau" },
				{ LanguageId.wo, "Gine-Bisaawóo" },
				{ LanguageId.xh, "EGuinea-Bissau" },
				{ LanguageId.xog, "Gini-Bisawu" },
				{ LanguageId.yav, "kiinépisaó" },
				{ LanguageId.yi, "גינע־ביסאַו" },
				{ LanguageId.yo, "Gene-Busau" },
				{ LanguageId.zgh, "ⵖⵉⵏⵢⴰ ⴱⵉⵙⴰⵡ" },
				{ LanguageId.zh, "几内亚比绍" },
				{ LanguageId.zu, "i-Guinea-Bissau" },
			}
		);
	}
}
