using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class HK
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "852",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Hong Kong" },
				{ LanguageId.da, "Hong Kong" },
				{ LanguageId.af, "Hong Kong" },
				{ LanguageId.agq, "Hong Kong" },
				{ LanguageId.ak, "Hong Kong" },
				{ LanguageId.am, "ሆንግ ኮንግ" },
				{ LanguageId.ar, "هونج كونج" },
				{ LanguageId.arn, "Hong Kong" },
				{ LanguageId.@as, "হংকং" },
				{ LanguageId.asa, "Hong Kong" },
				{ LanguageId.ast, "Hong Kong" },
				{ LanguageId.az, "Honq Konq" },
				{ LanguageId.ba, "Гонконг" },
				{ LanguageId.bas, "Hong Kong" },
				{ LanguageId.be, "Ганконг" },
				{ LanguageId.bem, "Hong Kong" },
				{ LanguageId.bez, "Hong Kong" },
				{ LanguageId.bg, "Хонг Конг" },
				{ LanguageId.bin, "Hong Kong" },
				{ LanguageId.bm, "Ɔngi-Kɔngi" },
				{ LanguageId.bn, "হংকং" },
				{ LanguageId.bo, "ཧོང་ཀོང་།" },
				{ LanguageId.br, "Hong Kong" },
				{ LanguageId.brx, "Hong Kong" },
				{ LanguageId.bs, "hong kong" },
				{ LanguageId.byn, "Hong Kong" },
				{ LanguageId.ca, "Hong Kong" },
				{ LanguageId.ccp, "Hong Kong" },
				{ LanguageId.ce, "Гонконг" },
				{ LanguageId.ceb, "Hong Kong" },
				{ LanguageId.cgg, "Hong Kong" },
				{ LanguageId.chr, "Hong Kong" },
				{ LanguageId.ckb, "هۆنگ کۆنگ" },
				{ LanguageId.co, "Hong Kong" },
				{ LanguageId.cs, "Hongkong" },
				{ LanguageId.cu, "Hong Kong" },
				{ LanguageId.cy, "Hong Kong" },
				{ LanguageId.dav, "Hong Kong" },
				{ LanguageId.de, "Hongkong" },
				{ LanguageId.dje, "Hong Kong" },
				{ LanguageId.doi, "Hong Kong" },
				{ LanguageId.dsb, "Hongkong" },
				{ LanguageId.dua, "Hong Kong" },
				{ LanguageId.dv, "ހޮންކޮންގު" },
				{ LanguageId.dz, "ཧོང་ཀོང་།" },
				{ LanguageId.ebu, "Hong Kong" },
				{ LanguageId.ee, "Hong Kong" },
				{ LanguageId.el, "Χονγκ Κονγκ" },
				{ LanguageId.en, "Hong Kong" },
				{ LanguageId.eo, "Honkongo" },
				{ LanguageId.es, "Hong Kong" },
				{ LanguageId.et, "Hongkong" },
				{ LanguageId.eu, "Hong Kong" },
				{ LanguageId.ewo, "Hong Kong" },
				{ LanguageId.fa, "هنگ کنگ" },
				{ LanguageId.ff, "Hong Kong" },
				{ LanguageId.fi, "Hong Kong" },
				{ LanguageId.fil, "Hong Kong" },
				{ LanguageId.fo, "Hong Kong" },
				{ LanguageId.fr, "Hong Kong" },
				{ LanguageId.fur, "Hong Kong" },
				{ LanguageId.fy, "Hong Kong" },
				{ LanguageId.ga, "Hong Cong" },
				{ LanguageId.gd, "Hong Kong" },
				{ LanguageId.gl, "Hong Kong" },
				{ LanguageId.gn, "Hong Kong" },
				{ LanguageId.gsw, "Hongkong" },
				{ LanguageId.gu, "હોંગ કોંગ" },
				{ LanguageId.guz, "Hong Kong" },
				{ LanguageId.gv, "Hong Kong" },
				{ LanguageId.ha, "Hong Kong" },
				{ LanguageId.haw, "Hong Kong" },
				{ LanguageId.he, "הונג קונג" },
				{ LanguageId.hi, "हांगकांग" },
				{ LanguageId.hr, "Hong Kong" },
				{ LanguageId.hsb, "Hongkong" },
				{ LanguageId.hu, "Hong Kong" },
				{ LanguageId.hy, "Հոնգ կոնգ" },
				{ LanguageId.ia, "Hong Kong" },
				{ LanguageId.ibb, "Hong Kong" },
				{ LanguageId.id, "Hongkong" },
				{ LanguageId.ig, "Hong Kong" },
				{ LanguageId.ii, "Hong Kong" },
				{ LanguageId.@is, "Hong Kong" },
				{ LanguageId.it, "Hong Kong" },
				{ LanguageId.iu, "Hong Kong" },
				{ LanguageId.ja, "香港" },
				{ LanguageId.jgo, "Hong Kong" },
				{ LanguageId.jmc, "Hong Kong" },
				{ LanguageId.jv, "Hong Kong" },
				{ LanguageId.ka, "ჰონგ კონგი" },
				{ LanguageId.kab, "Hong Kong" },
				{ LanguageId.kam, "Hong Kong" },
				{ LanguageId.kde, "Hong Kong" },
				{ LanguageId.kea, "Hong Kong" },
				{ LanguageId.khq, "Hong Kong" },
				{ LanguageId.ki, "Hong Kong" },
				{ LanguageId.kk, "Гонконг" },
				{ LanguageId.kkj, "Hong Kong" },
				{ LanguageId.kl, "Hong Kong" },
				{ LanguageId.kln, "Hong Kong" },
				{ LanguageId.km, "ហុងកុង" },
				{ LanguageId.kn, "ಹಾಂಗ್ ಕಾಂಗ್" },
				{ LanguageId.ko, "홍콩" },
				{ LanguageId.kok, "हाँगकाँग" },
				{ LanguageId.kr, "Hong Kong" },
				{ LanguageId.ks, "ہانگ کانگ" },
				{ LanguageId.ksb, "Hong Kong" },
				{ LanguageId.ksf, "Hong Kong" },
				{ LanguageId.ksh, "Hongkong" },
				{ LanguageId.kw, "Hong Kong" },
				{ LanguageId.ky, "Гонконг" },
				{ LanguageId.la, "Hong Kong" },
				{ LanguageId.lag, "Hong Kong" },
				{ LanguageId.lb, "Hong Kong" },
				{ LanguageId.lg, "Hong Kong" },
				{ LanguageId.lkt, "Hong Kong" },
				{ LanguageId.ln, "Hong Kong" },
				{ LanguageId.lo, "ຮົງ​ກົງ" },
				{ LanguageId.lrc, "هنگ کنگ" },
				{ LanguageId.lt, "Honkongas" },
				{ LanguageId.luo, "Hong Kong" },
				{ LanguageId.luy, "Hong Kong" },
				{ LanguageId.lv, "Honkonga" },
				{ LanguageId.mai, "हांगकांग" },
				{ LanguageId.mas, "Hong Kong" },
				{ LanguageId.mer, "Hong Kong" },
				{ LanguageId.mfe, "Hong Kong" },
				{ LanguageId.mg, "Hong Kong" },
				{ LanguageId.mgo, "Hong Kong" },
				{ LanguageId.mi, "Hong Kong" },
				{ LanguageId.mk, "Хонг Конг" },
				{ LanguageId.ml, "ഹോങ്കോംഗ്" },
				{ LanguageId.mn, "Хонг Конг" },
				{ LanguageId.mni, "Hong Kong" },
				{ LanguageId.moh, "Hong Kong" },
				{ LanguageId.mr, "हाँगकाँग" },
				{ LanguageId.ms, "Hong Kong" },
				{ LanguageId.mt, "Ħong Kong" },
				{ LanguageId.mua, "Hong Kong" },
				{ LanguageId.my, "ဟောင်ကောင်" },
				{ LanguageId.mzn, "هنگ کنگ" },
				{ LanguageId.naq, "Hong Kong" },
				{ LanguageId.nb, "Hong Kong" },
				{ LanguageId.nd, "Hong Kong" },
				{ LanguageId.nds, "Hongkong" },
				{ LanguageId.ne, "हंगकंग" },
				{ LanguageId.nl, "Hongkong" },
				{ LanguageId.nmg, "Hong Kong" },
				{ LanguageId.nn, "Hongkong" },
				{ LanguageId.nnh, "Hong Kong" },
				{ LanguageId.nqo, "ɔ́ŋkɔ́ŋ" },
				{ LanguageId.nr, "Hong Kong" },
				{ LanguageId.nso, "Hong Kong" },
				{ LanguageId.nus, "Hong Kong" },
				{ LanguageId.nyn, "Hong Kong" },
				{ LanguageId.oc, "Hong Kong" },
				{ LanguageId.om, "Hoong Koong" },
				{ LanguageId.or, "ହଂଗ କଂଗ" },
				{ LanguageId.os, "Гонконг" },
				{ LanguageId.pa, "ਹਾਂਗ ਕਾਂਗ" },
				{ LanguageId.pap, "Hong Kong" },
				{ LanguageId.pcm, "Hong Kong" },
				{ LanguageId.pl, "Hongkong" },
				{ LanguageId.prg, "Hong Kong" },
				{ LanguageId.ps, "هانګ کانګ" },
				{ LanguageId.pt, "Hong Kong" },
				{ LanguageId.qu, "Hong Kong" },
				{ LanguageId.quc, "Hong Kong" },
				{ LanguageId.rm, "Hongkong" },
				{ LanguageId.rn, "Hongo Kongo" },
				{ LanguageId.ro, "Hong Kong" },
				{ LanguageId.rof, "Hong Kong" },
				{ LanguageId.ru, "Гонконг" },
				{ LanguageId.rw, "Hong Kong" },
				{ LanguageId.rwk, "Hong Kong" },
				{ LanguageId.sa, "हांगकांग" },
				{ LanguageId.sah, "Гонконг" },
				{ LanguageId.saq, "Hong Kong" },
				{ LanguageId.sat, "Hong Kong" },
				{ LanguageId.sbp, "Hong Kong" },
				{ LanguageId.sd, "هانگ ڪانگ" },
				{ LanguageId.se, "Hong Kong" },
				{ LanguageId.seh, "Hong Kong" },
				{ LanguageId.ses, "Hong Kong" },
				{ LanguageId.sg, "Hong Kong" },
				{ LanguageId.shi, "Hong Kong" },
				{ LanguageId.si, "හොංකොං" },
				{ LanguageId.sk, "Hong Kong" },
				{ LanguageId.sl, "Hong Kong" },
				{ LanguageId.sma, "Hong Kong" },
				{ LanguageId.smj, "Hong Kong" },
				{ LanguageId.smn, "Hong Kong" },
				{ LanguageId.sms, "Hong Kong" },
				{ LanguageId.sn, "Hong Kong" },
				{ LanguageId.so, "Hong Kong" },
				{ LanguageId.sq, "Hong Kongu" },
				{ LanguageId.sr, "Хонг Конг" },
				{ LanguageId.ss, "Hong Kong" },
				{ LanguageId.ssy, "Hong Kong" },
				{ LanguageId.st, "Hong Kong" },
				{ LanguageId.su, "Hongkong" },
				{ LanguageId.sv, "Hong Kong" },
				{ LanguageId.sw, "Hong Kong" },
				{ LanguageId.syr, "Hong Kong" },
				{ LanguageId.ta, "ஹாங்காங்" },
				{ LanguageId.te, "హాంగ్ కొంగ" },
				{ LanguageId.teo, "Hong Kong" },
				{ LanguageId.tg, "Гонконг" },
				{ LanguageId.th, "ฮ่องกง" },
				{ LanguageId.ti, "ሆንግ ኮንግ" },
				{ LanguageId.tig, "Hong Kong" },
				{ LanguageId.tk, "Gonkong" },
				{ LanguageId.tn, "Hong Kong" },
				{ LanguageId.to, "Hongo Kongo" },
				{ LanguageId.tr, "Hong Kong" },
				{ LanguageId.ts, "Hong Kong" },
				{ LanguageId.tt, "Гонконг" },
				{ LanguageId.twq, "Hong Kong" },
				{ LanguageId.tzm, "Hong Kong" },
				{ LanguageId.ug, "شياڭگاڭ" },
				{ LanguageId.uk, "Гонконг" },
				{ LanguageId.ur, "ہانگ کانگ" },
				{ LanguageId.uz, "Gonkong" },
				{ LanguageId.vai, "Hong Kong" },
				{ LanguageId.ve, "Hong Kong" },
				{ LanguageId.vi, "Hồng Kông" },
				{ LanguageId.vo, "Hongkong" },
				{ LanguageId.vun, "Hong Kong" },
				{ LanguageId.wae, "Hongkong" },
				{ LanguageId.wal, "Hong Kong" },
				{ LanguageId.wo, "Ooŋ Koŋ" },
				{ LanguageId.xh, "Ehong kong" },
				{ LanguageId.xog, "Hong Kong" },
				{ LanguageId.yav, "Hong Kong" },
				{ LanguageId.yi, "האָנג קאָנג" },
				{ LanguageId.yo, "ilu họngi kọngi" },
				{ LanguageId.zgh, "Hong Kong" },
				{ LanguageId.zh, "香港" },
				{ LanguageId.zu, "i-Hong Kong" },
			}
		);
	}
}
