// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class HK
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "852",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Hong Kong" },
				{ LanguageId.da, "SAR Hongkong" },
				{ LanguageId.af, "Hongkong SAS China" },
				{ LanguageId.agq, "Hong Kong" },
				{ LanguageId.ak, "Hɔnkɔn Kyaena" },
				{ LanguageId.am, "ሆንግ ኮንግ ልዩ የአስተዳደር ክልል ቻይና" },
				{ LanguageId.ar, "هونغ كونغ الصينية (منطقة إدارية خاصة)" },
				{ LanguageId.arn, "Hong Kong" },
				{ LanguageId.@as, "হং কং এছ. এ. আৰ. চীন" },
				{ LanguageId.asa, "Hong Kong" },
				{ LanguageId.ast, "ARE China de Ḥong Kong" },
				{ LanguageId.az, "Honq Konq Xüsusi İnzibati Rayonu Çin" },
				{ LanguageId.ba, "Гонконг, Ҡытай МАР-ы" },
				{ LanguageId.bas, "Hong Kong" },
				{ LanguageId.be, "Ганконг, САР (Кітай)" },
				{ LanguageId.bem, "Hong Kong" },
				{ LanguageId.bez, "Hong Kong" },
				{ LanguageId.bg, "Хонконг, САР на Китай" },
				{ LanguageId.bin, "Hong Kong" },
				{ LanguageId.bm, "Ɔngi-Kɔngi" },
				{ LanguageId.bn, "হংকং এসএআর চীনা" },
				{ LanguageId.bo, "ཧོང་ཀོང་།" },
				{ LanguageId.br, "Hong Kong RMD Sina" },
				{ LanguageId.brx, "हंकं एस.ए.आर चाइना" },
				{ LanguageId.bs, "Hong Kong (SAR Kina)" },
				{ LanguageId.byn, "Hong Kong" },
				{ LanguageId.ca, "Hong Kong (RAE Xina)" },
				{ LanguageId.ccp, "𑄦𑄧𑄁𑄇𑄧𑄁 𑄆𑄌𑄴𑄃𑄬𑄃𑄢𑄴 𑄌𑄩𑄚" },
				{ LanguageId.ce, "Гонконг (ша-къаьстина кӀошт)" },
				{ LanguageId.ceb, "Hong Kong SAR China" },
				{ LanguageId.cgg, "Hong Kong" },
				{ LanguageId.chr, "ᎰᏂᎩ ᎪᏂᎩ ᎤᏓᏤᎵᏓ ᏧᏂᎸᏫᏍᏓᏁᏗ ᎢᎬᎾᏕᎾ ᏓᎶᏂᎨᏍᏛ" },
				{ LanguageId.ckb, "هۆنگ کۆنگ" },
				{ LanguageId.co, "Hong Kong" },
				{ LanguageId.cs, "Hongkong – ZAO Číny" },
				{ LanguageId.cu, "Hong Kong" },
				{ LanguageId.cy, "Hong Kong SAR Tsieina" },
				{ LanguageId.dav, "Hong Kong" },
				{ LanguageId.de, "Sonderverwaltungsregion Hongkong" },
				{ LanguageId.dje, "Hong Kong" },
				{ LanguageId.doi, "Hong Kong" },
				{ LanguageId.dsb, "Wósebna zastojnstwowa cona Hongkong" },
				{ LanguageId.dua, "Hong Kong" },
				{ LanguageId.dv, "ހޮންކޮންގު" },
				{ LanguageId.dz, "ཧོང་ཀོང་ཅཱའི་ན" },
				{ LanguageId.ebu, "Hong Kong" },
				{ LanguageId.ee, "Hɔng Kɔng SAR Tsaina nutome" },
				{ LanguageId.el, "Χονγκ Κονγκ ΕΔΠ Κίνας" },
				{ LanguageId.en, "Hong Kong SAR China" },
				{ LanguageId.eo, "Honkongo (SAR de Ĉinujo)" },
				{ LanguageId.es, "RAE de Hong Kong (China)" },
				{ LanguageId.et, "Hongkongi erihalduspiirkond" },
				{ LanguageId.eu, "Hong Kong Txinako AEB" },
				{ LanguageId.ewo, "Hong Kong" },
				{ LanguageId.fa, "هنگ‌کنگ، منطقهٔ ویژهٔ اداری چین" },
				{ LanguageId.ff, "Hong Kong" },
				{ LanguageId.fi, "Hongkong – Kiinan erityishallintoalue" },
				{ LanguageId.fil, "Hong Kong SAR China" },
				{ LanguageId.fo, "Hong Kong SAR Kina" },
				{ LanguageId.fr, "R.A.S. chinoise de Hong Kong" },
				{ LanguageId.fur, "Regjon aministrative speciâl de Cine di Hong Kong" },
				{ LanguageId.fy, "Hongkong SAR van Sina" },
				{ LanguageId.ga, "Sainréigiún Riaracháin Hong Cong, Daonphoblacht na Síne" },
				{ LanguageId.gd, "Hong Kong SAR na Sìne" },
				{ LanguageId.gl, "Hong Kong RAE da China" },
				{ LanguageId.gn, "Hong Kong" },
				{ LanguageId.gsw, "Sonderverwaltigszone Hongkong" },
				{ LanguageId.gu, "હોંગકોંગ SAR ચીન" },
				{ LanguageId.guz, "Hong Kong" },
				{ LanguageId.gv, "Hong Kong" },
				{ LanguageId.ha, "Babban Yankin Mulkin Hong Kong na Ƙasar Sin" },
				{ LanguageId.haw, "Hong Kong" },
				{ LanguageId.he, "הונג קונג (אזור מנהלי מיוחד של סין)" },
				{ LanguageId.hi, "हाँग काँग (चीन विशेष प्रशासनिक क्षेत्र)" },
				{ LanguageId.hr, "PUP Hong Kong Kina" },
				{ LanguageId.hsb, "Wosebita zarjadniska cona Hongkong" },
				{ LanguageId.hu, "Hongkong KKT" },
				{ LanguageId.hy, "Հոնկոնգի ՀՎՇ" },
				{ LanguageId.ia, "Hongkong, R.A.S. de China" },
				{ LanguageId.ibb, "Hong Kong" },
				{ LanguageId.id, "Hong Kong DAK Tiongkok" },
				{ LanguageId.ig, "Hong Kong SAR China" },
				{ LanguageId.ii, "Hong Kong" },
				{ LanguageId.@is, "sérstjórnarsvæðið Hong Kong" },
				{ LanguageId.it, "RAS di Hong Kong" },
				{ LanguageId.iu, "Hong Kong" },
				{ LanguageId.ja, "中華人民共和国香港特別行政区" },
				{ LanguageId.jgo, "Hong Kong" },
				{ LanguageId.jmc, "Hong Kong" },
				{ LanguageId.jv, "Laladan Administratif Astamiwa Hong Kong" },
				{ LanguageId.ka, "ჰონკონგის სპეციალური ადმინისტრაციული რეგიონი, ჩინეთი" },
				{ LanguageId.kab, "Hong Kong" },
				{ LanguageId.kam, "Hong Kong" },
				{ LanguageId.kde, "Hong Kong" },
				{ LanguageId.kea, "Hong Kong, Rejion Administrativu Spesial di Xina" },
				{ LanguageId.khq, "Hong Kong" },
				{ LanguageId.ki, "Hong Kong" },
				{ LanguageId.kk, "Сянган АӘА" },
				{ LanguageId.kkj, "Hong Kong" },
				{ LanguageId.kl, "Hong Kong" },
				{ LanguageId.kln, "Hong Kong" },
				{ LanguageId.km, "ហុងកុង តំបន់រដ្ឋបាលពិសេសចិន" },
				{ LanguageId.kn, "ಹಾಂಗ್ ಕಾಂಗ್ ಎಸ್ಎಆರ್ ಚೈನಾ" },
				{ LanguageId.ko, "홍콩(중국 특별행정구)" },
				{ LanguageId.kok, "हाँग काँग" },
				{ LanguageId.kr, "Hong Kong" },
				{ LanguageId.ks, "ہانگ کانگ ایس اے آر چیٖن" },
				{ LanguageId.ksb, "Hong Kong" },
				{ LanguageId.ksf, "Hong Kong" },
				{ LanguageId.ksh, "Hongkong" },
				{ LanguageId.kw, "Hong Kong" },
				{ LanguageId.ky, "Гонконг Кытай ААА" },
				{ LanguageId.la, "Hong Kong" },
				{ LanguageId.lag, "Hong Kong" },
				{ LanguageId.lb, "Spezialverwaltungszon Hong Kong" },
				{ LanguageId.lg, "Hong Kong" },
				{ LanguageId.lkt, "Hong Kong" },
				{ LanguageId.ln, "Hong Kong" },
				{ LanguageId.lo, "ຮົງກົງ ເຂດປົກຄອງພິເສດ ຈີນ" },
				{ LanguageId.lrc, "هنگ کنگ" },
				{ LanguageId.lt, "Ypatingasis Administracinis Kinijos Regionas Honkongas" },
				{ LanguageId.luo, "Hong Kong" },
				{ LanguageId.luy, "Hong Kong" },
				{ LanguageId.lv, "Ķīnas īpašās pārvaldes apgabals Honkonga" },
				{ LanguageId.mai, "हांग कांग (विशेष प्रशासनिक क्षेत्र चीन)" },
				{ LanguageId.mas, "Hong Kong" },
				{ LanguageId.mer, "Hong Kong" },
				{ LanguageId.mfe, "Hong Kong" },
				{ LanguageId.mg, "Hong Kong" },
				{ LanguageId.mgo, "Hong Kong" },
				{ LanguageId.mi, "Hongipua Haina" },
				{ LanguageId.mk, "Хонгконг САР Кина" },
				{ LanguageId.ml, "ഹോങ്കോങ് (SAR) ചൈന" },
				{ LanguageId.mn, "БНХАУ-ын Тусгай захиргааны бүс Хонг-Конг" },
				{ LanguageId.mni, "Hong Kong" },
				{ LanguageId.moh, "Hong Kong" },
				{ LanguageId.mr, "हाँगकाँग एसएआर चीन" },
				{ LanguageId.ms, "Hong Kong SAR China" },
				{ LanguageId.mt, "ir-Reġjun Amministrattiv Speċjali ta’ Hong Kong tar-Repubblika tal-Poplu taċ-Ċina" },
				{ LanguageId.mua, "Hong Kong" },
				{ LanguageId.my, "ဟောင်ကောင် (တရုတ်ပြည်)" },
				{ LanguageId.mzn, "هنگ کنگ" },
				{ LanguageId.naq, "Hong Kong" },
				{ LanguageId.nb, "Hongkong SAR Kina" },
				{ LanguageId.nd, "Hong Kong" },
				{ LanguageId.nds, "Hongkong" },
				{ LanguageId.ne, "हङकङ चिनियाँ विशेष प्रशासनिक क्षेत्र" },
				{ LanguageId.nl, "Hongkong SAR van China" },
				{ LanguageId.nmg, "Hong Kong" },
				{ LanguageId.nn, "Hongkong SAR Kina" },
				{ LanguageId.nnh, "Hong Kong" },
				{ LanguageId.nqo, "ߛߌߣ ߕߌ߲߬ߞߎߘߎ߲߫ ߡߊߡߙߊ߬ߣߍ߲ ߤߐ߲ߞߐ߲߫" },
				{ LanguageId.nr, "Hong Kong" },
				{ LanguageId.nso, "Hong Kong" },
				{ LanguageId.nus, "Hong Kong" },
				{ LanguageId.nyn, "Hong Kong" },
				{ LanguageId.oc, "Hong Kong" },
				{ LanguageId.om, "Hoong Koong SAR Chaayinaa" },
				{ LanguageId.or, "ହଂ କଂ ଏସଏଆର୍‌ ଚାଇନା" },
				{ LanguageId.os, "Гонконг" },
				{ LanguageId.pa, "ਹਾਂਗ ਕਾਂਗ ਐਸਏਆਰ ਚੀਨ" },
				{ LanguageId.pap, "Hong Kong" },
				{ LanguageId.pcm, "Họng Kọng SAR" },
				{ LanguageId.pl, "SRA Hongkong (Chiny)" },
				{ LanguageId.prg, "Hong Kong" },
				{ LanguageId.ps, "هانګ کانګ SAR چین" },
				{ LanguageId.pt, "Hong Kong, RAE da China" },
				{ LanguageId.qu, "Hong Kong RAE China" },
				{ LanguageId.quc, "Hong Kong" },
				{ LanguageId.rm, "Regiun d’administraziun speziala Hongkong, China" },
				{ LanguageId.rn, "Hongo Kongo" },
				{ LanguageId.ro, "R.A.S. Hong Kong, China" },
				{ LanguageId.rof, "Hong Kong" },
				{ LanguageId.ru, "Гонконг (САР)" },
				{ LanguageId.rw, "Hong Kong" },
				{ LanguageId.rwk, "Hong Kong" },
				{ LanguageId.sa, "हांगकांग" },
				{ LanguageId.sah, "Гонконг" },
				{ LanguageId.saq, "Hong Kong" },
				{ LanguageId.sat, "Hong Kong" },
				{ LanguageId.sbp, "Hong Kong" },
				{ LanguageId.sd, "هانگ ڪانگ SAR چين" },
				{ LanguageId.se, "Hongkong" },
				{ LanguageId.seh, "Hong Kong" },
				{ LanguageId.ses, "Hong Kong" },
				{ LanguageId.sg, "Hong Kong" },
				{ LanguageId.shi, "Hong Kong" },
				{ LanguageId.si, "හොංකොං විශේෂ පරිපාලන කලාපය චීනය" },
				{ LanguageId.sk, "Hongkong – OAO Číny" },
				{ LanguageId.sl, "Posebno upravno območje Ljudske republike Kitajske Hongkong" },
				{ LanguageId.sma, "Hong Kong" },
				{ LanguageId.smj, "Hong Kong" },
				{ LanguageId.smn, "Hongkong – Kiina e.h.k." },
				{ LanguageId.sms, "Hong Kong" },
				{ LanguageId.sn, "Hong Kong" },
				{ LanguageId.so, "Hong Kong" },
				{ LanguageId.sq, "RPA i Hong-Kongut" },
				{ LanguageId.sr, "САР Хонгконг (Кина)" },
				{ LanguageId.ss, "Hong Kong" },
				{ LanguageId.ssy, "Hong Kong" },
				{ LanguageId.st, "Hong Kong" },
				{ LanguageId.su, "Hongkong" },
				{ LanguageId.sv, "Hongkong SAR" },
				{ LanguageId.sw, "Hong Kong SAR China" },
				{ LanguageId.syr, "ܗܘܢܓ ܟܘܢܓ" },
				{ LanguageId.ta, "ஹாங்காங் எஸ்ஏஆர் சீனா" },
				{ LanguageId.te, "హాంకాంగ్ SAR చైనా" },
				{ LanguageId.teo, "Hong Kong" },
				{ LanguageId.tg, "Ҳонконг (МММ)" },
				{ LanguageId.th, "เขตปกครองพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน" },
				{ LanguageId.ti, "ፍሉይ ምምሕዳራዊ ዞባ ሆንግ ኮንግ (ቻይና)" },
				{ LanguageId.tig, "Hong Kong" },
				{ LanguageId.tk, "Gonkong AAS Hytaý" },
				{ LanguageId.tn, "Hong Kong" },
				{ LanguageId.to, "Hongi Kongi SAR Siaina" },
				{ LanguageId.tr, "Çin Hong Kong ÖİB" },
				{ LanguageId.ts, "Hong Kong" },
				{ LanguageId.tt, "Гонконг Махсус Идарәле Төбәге" },
				{ LanguageId.twq, "Hong Kong" },
				{ LanguageId.tzm, "Hong Kong" },
				{ LanguageId.ug, "شياڭگاڭ ئالاھىدە مەمۇرىي رايونى (جۇڭگو)" },
				{ LanguageId.uk, "Гонконг, ОАР Китаю" },
				{ LanguageId.ur, "ہانگ کانگ SAR چین" },
				{ LanguageId.uz, "Gonkong (Xitoy MMH)" },
				{ LanguageId.vai, "Hong Kong" },
				{ LanguageId.ve, "Hong Kong" },
				{ LanguageId.vi, "Đặc khu Hành chính Hồng Kông, Trung Quốc" },
				{ LanguageId.vo, "Hongkong" },
				{ LanguageId.vun, "Hong Kong" },
				{ LanguageId.wae, "Sonderverwaltigszona Hongkong" },
				{ LanguageId.wal, "Hong Kong" },
				{ LanguageId.wo, "Ooŋ Koŋ" },
				{ LanguageId.xh, "EHong Kong SAR China" },
				{ LanguageId.xog, "Hong Kong" },
				{ LanguageId.yav, "Hong Kong" },
				{ LanguageId.yi, "האָנג קאָנג" },
				{ LanguageId.yo, "Agbègbè Ìṣàkóso Ìṣúná Hong Kong Tí Ṣánà Ń Darí" },
				{ LanguageId.zgh, "Hong Kong" },
				{ LanguageId.zh, "中国香港特别行政区" },
				{ LanguageId.zu, "i-Hong Kong SAR China" },
			}
		);
	}
}
