using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class HK
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "852",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Hong Kong" },
				{ LanguageId.af, "Hong Kong" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሆንግ ኮንግ" },
				{ LanguageId.ar, "هونج كونج" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Honq Konq" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Ганконг" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Хонг Конг" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "হংকং" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "hong kong" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Hong Kong" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Hong Kong" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Hong Kong" },
				{ LanguageId.cs, "Hongkong" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Hong Kong" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Hongkong" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Χονγκ Κονγκ" },
				{ LanguageId.en, "Hong Kong" },
				{ LanguageId.eo, "Honkongo" },
				{ LanguageId.es, "Hong Kong" },
				{ LanguageId.et, "Hongkong" },
				{ LanguageId.eu, "Hong Kong" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "هنگ کنگ" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Hong Kong" },
				{ LanguageId.fil, "Hong Kong" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Hong Kong" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Hong Kong" },
				{ LanguageId.ga, "Hong Cong" },
				{ LanguageId.gd, "Hong Kong" },
				{ LanguageId.gl, "Hong Kong" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "હોંગ કોંગ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Hong Kong" },
				{ LanguageId.haw, "Hong Kong" },
				{ LanguageId.he, "הונג קונג" },
				{ LanguageId.hi, "हांगकांग" },
				{ LanguageId.hr, "Hong Kong" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Hong Kong" },
				{ LanguageId.hy, "Հոնգ կոնգ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Hongkong" },
				{ LanguageId.ig, "Hong Kong" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Hong Kong" },
				{ LanguageId.it, "Hong Kong" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "香港" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Hong Kong" },
				{ LanguageId.ka, "ჰონგ კონგი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Гонконг" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ហុងកុង" },
				{ LanguageId.kn, "ಹಾಂಗ್ ಕಾಂಗ್" },
				{ LanguageId.ko, "홍콩" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Гонконг" },
				{ LanguageId.la, "Hong Kong" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Hong Kong" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຮົງ​ກົງ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Honkongas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Honkonga" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Hong Kong" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hong Kong" },
				{ LanguageId.mk, "Хонг Конг" },
				{ LanguageId.ml, "ഹോങ്കോംഗ്" },
				{ LanguageId.mn, "Хонг Конг" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "हाँगकाँग" },
				{ LanguageId.ms, "Hong Kong" },
				{ LanguageId.mt, "Ħong Kong" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဟောင်ကောင်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Hong Kong" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "हंगकंग" },
				{ LanguageId.nl, "Hongkong" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ହଂଗ କଂଗ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਹਾਂਗ ਕਾਂਗ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Hongkong" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "هانګ کانګ" },
				{ LanguageId.pt, "Hong Kong" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Hong Kong" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Гонконг" },
				{ LanguageId.rw, "Hong Kong" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "هانگ ڪانگ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "හොංකොං" },
				{ LanguageId.sk, "Hong Kong" },
				{ LanguageId.sl, "Hong Kong" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Hong Kong" },
				{ LanguageId.so, "Hong Kong" },
				{ LanguageId.sq, "Hong Kongu" },
				{ LanguageId.sr, "Хонг Конг" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Hong Kong" },
				{ LanguageId.su, "Hongkong" },
				{ LanguageId.sv, "Hong Kong" },
				{ LanguageId.sw, "Hong Kong" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஹாங்காங்" },
				{ LanguageId.te, "హాంగ్ కొంగ" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Гонконг" },
				{ LanguageId.th, "ฮ่องกง" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Gonkong" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Hong Kong" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Гонконг" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "شياڭگاڭ" },
				{ LanguageId.uk, "Гонконг" },
				{ LanguageId.ur, "ہانگ کانگ" },
				{ LanguageId.uz, "Gonkong" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hồng Kông" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Ehong kong" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "האָנג קאָנג" },
				{ LanguageId.yo, "ilu họngi kọngi" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "香港" },
				{ LanguageId.zu, "i-Hong Kong" },
			}
		);
	}
}
