// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class IN
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "91",
			ValidLengthsAndFormat: new Dictionary<int, string>()
			{
				{ 10, "##########" }
			},
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Indien" },
				{ LanguageId.af, "Indië" },
				{ LanguageId.agq, "Endìa" },
				{ LanguageId.ak, "India" },
				{ LanguageId.am, "ህንድ" },
				{ LanguageId.ar, "الهند" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ভাৰত" },
				{ LanguageId.asa, "India" },
				{ LanguageId.ast, "India" },
				{ LanguageId.az, "Hindistan" },
				{ LanguageId.ba, "Һиндостан" },
				{ LanguageId.bas, "Indìà" },
				{ LanguageId.be, "Індыя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huindia" },
				{ LanguageId.bg, "Индия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Ɛndujamana" },
				{ LanguageId.bn, "ভারত" },
				{ LanguageId.bo, "རྒྱ་གར་" },
				{ LanguageId.br, "India" },
				{ LanguageId.brx, "भारत" },
				{ LanguageId.bs, "Indija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Índia" },
				{ LanguageId.ccp, "𑄞𑄢𑄧𑄖𑄴" },
				{ LanguageId.ce, "ХӀинди" },
				{ LanguageId.ceb, "India" },
				{ LanguageId.cgg, "Indiya" },
				{ LanguageId.chr, "ᎢᏅᏗᎾ" },
				{ LanguageId.ckb, "ھیندستان" },
				{ LanguageId.co, "Bharat (India)" },
				{ LanguageId.cs, "Indie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "India" },
				{ LanguageId.dav, "India" },
				{ LanguageId.de, "Indien" },
				{ LanguageId.dje, "Indu laboo" },
				{ LanguageId.doi, "भारत" },
				{ LanguageId.dsb, "Indiska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "རྒྱ་གར" },
				{ LanguageId.ebu, "India" },
				{ LanguageId.ee, "India nutome" },
				{ LanguageId.el, "Ινδία" },
				{ LanguageId.en, "India (Bharat)" },
				{ LanguageId.eo, "Hindujo" },
				{ LanguageId.es, "India" },
				{ LanguageId.et, "India" },
				{ LanguageId.eu, "India" },
				{ LanguageId.ewo, "ɛ́ndə" },
				{ LanguageId.fa, "هند" },
				{ LanguageId.ff, "Enndo" },
				{ LanguageId.fi, "Intia" },
				{ LanguageId.fil, "India" },
				{ LanguageId.fo, "India" },
				{ LanguageId.fr, "Inde" },
				{ LanguageId.fur, "India" },
				{ LanguageId.fy, "India" },
				{ LanguageId.ga, "an India" },
				{ LanguageId.gd, "Na h-Innseachan" },
				{ LanguageId.gl, "India" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Indie" },
				{ LanguageId.gu, "ભારત" },
				{ LanguageId.guz, "India" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Indiya" },
				{ LanguageId.haw, "ʻĪnia" },
				{ LanguageId.he, "הודו" },
				{ LanguageId.hi, "भारत" },
				{ LanguageId.hr, "Indija" },
				{ LanguageId.hsb, "Indiska" },
				{ LanguageId.hu, "India" },
				{ LanguageId.hy, "Հնդկաստան" },
				{ LanguageId.ia, "India" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "India" },
				{ LanguageId.ig, "India" },
				{ LanguageId.ii, "ꑴꄗ" },
				{ LanguageId.@is, "Indland" },
				{ LanguageId.it, "India" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "インド" },
				{ LanguageId.jgo, "Ándɛ" },
				{ LanguageId.jmc, "India" },
				{ LanguageId.jv, "Indhia" },
				{ LanguageId.ka, "ინდოეთი" },
				{ LanguageId.kab, "Lhend" },
				{ LanguageId.kam, "India" },
				{ LanguageId.kde, "India" },
				{ LanguageId.kea, "Índia" },
				{ LanguageId.khq, "Indu laboo" },
				{ LanguageId.ki, "India" },
				{ LanguageId.kk, "Үндістан" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab India" },
				{ LanguageId.km, "ឥណ្ឌា" },
				{ LanguageId.kn, "ಭಾರತ" },
				{ LanguageId.ko, "인도" },
				{ LanguageId.kok, "भारत" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ہِندوستان" },
				{ LanguageId.ksb, "India" },
				{ LanguageId.ksf, "indí" },
				{ LanguageId.ksh, "Indije" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Индия" },
				{ LanguageId.la, "Bharat (India)" },
				{ LanguageId.lag, "Índia" },
				{ LanguageId.lb, "Indien" },
				{ LanguageId.lg, "Buyindi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Índɛ" },
				{ LanguageId.lo, "ອິນເດຍ" },
				{ LanguageId.lrc, "ھئن" },
				{ LanguageId.lt, "Indija" },
				{ LanguageId.luo, "India" },
				{ LanguageId.luy, "India" },
				{ LanguageId.lv, "Indija" },
				{ LanguageId.mai, "भारत" },
				{ LanguageId.mas, "India" },
				{ LanguageId.mer, "India" },
				{ LanguageId.mfe, "Lenn" },
				{ LanguageId.mg, "Indy" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Inia" },
				{ LanguageId.mk, "Индија" },
				{ LanguageId.ml, "ഇന്ത്യ" },
				{ LanguageId.mn, "Энэтхэг" },
				{ LanguageId.mni, "ইন্দিয়া" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "भारत" },
				{ LanguageId.ms, "India" },
				{ LanguageId.mt, "l-Indja" },
				{ LanguageId.mua, "Sǝr Indǝ" },
				{ LanguageId.my, "အိန္ဒိယ" },
				{ LanguageId.mzn, "هند" },
				{ LanguageId.naq, "Indiab" },
				{ LanguageId.nb, "India" },
				{ LanguageId.nd, "Indiya" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भारत" },
				{ LanguageId.nl, "India" },
				{ LanguageId.nmg, "India" },
				{ LanguageId.nn, "India" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߌߘߎ߬" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Indiya" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Hindii" },
				{ LanguageId.or, "ଭାରତ" },
				{ LanguageId.os, "Инди" },
				{ LanguageId.pa, "ਭਾਰਤ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Índia" },
				{ LanguageId.pl, "Indie" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "هند" },
				{ LanguageId.pt, "Índia" },
				{ LanguageId.qu, "India" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "India" },
				{ LanguageId.rn, "Ubuhindi" },
				{ LanguageId.ro, "India" },
				{ LanguageId.rof, "India" },
				{ LanguageId.ru, "Индия" },
				{ LanguageId.rw, "Bharat (Ubuhinde)" },
				{ LanguageId.rwk, "India" },
				{ LanguageId.sa, "भारतः" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "India" },
				{ LanguageId.sat, "ᱤᱱᱰᱤᱭᱟ" },
				{ LanguageId.sbp, "Indiya" },
				{ LanguageId.sd, "ڀارت" },
				{ LanguageId.se, "India" },
				{ LanguageId.seh, "Índia" },
				{ LanguageId.ses, "Indu laboo" },
				{ LanguageId.sg, "Ênnde" },
				{ LanguageId.shi, "ⵍⵀⵉⵏⴷ" },
				{ LanguageId.si, "ඉන්දියාව" },
				{ LanguageId.sk, "India" },
				{ LanguageId.sl, "Indija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "India" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "India" },
				{ LanguageId.so, "Hindiya" },
				{ LanguageId.sq, "Indi" },
				{ LanguageId.sr, "Индија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Bharat (India)" },
				{ LanguageId.su, "India" },
				{ LanguageId.sv, "Indien" },
				{ LanguageId.sw, "India" },
				{ LanguageId.syr, "ܗܢܕܘ" },
				{ LanguageId.ta, "இந்தியா" },
				{ LanguageId.te, "భారతదేశం" },
				{ LanguageId.teo, "India" },
				{ LanguageId.tg, "Ҳиндустон" },
				{ LanguageId.th, "อินเดีย" },
				{ LanguageId.ti, "ህንዲ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Hindistan" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻInitia" },
				{ LanguageId.tr, "Hindistan" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Индия" },
				{ LanguageId.twq, "Indu laboo" },
				{ LanguageId.tzm, "Hind" },
				{ LanguageId.ug, "ھىندىستان" },
				{ LanguageId.uk, "Індія" },
				{ LanguageId.ur, "بھارت" },
				{ LanguageId.uz, "Hindiston" },
				{ LanguageId.vai, "ꔤꔺꕩ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Ấn Độ" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "India" },
				{ LanguageId.wae, "Indie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "End" },
				{ LanguageId.xh, "E-Indiya" },
				{ LanguageId.xog, "Buyindi" },
				{ LanguageId.yav, "ɛ́ɛnd" },
				{ LanguageId.yi, "אינדיע" },
				{ LanguageId.yo, "Íńdíà" },
				{ LanguageId.zgh, "ⵍⵀⵉⵏⴷ" },
				{ LanguageId.zh, "印度" },
				{ LanguageId.zu, "i-India" },
			}
		);
	}
}
