using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class IN
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "91",
			ValidLengthsAndFormat : new Dictionary<int, string>()
			{
				{ 10, "##########" }
			},
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Bharat (Indien)" },
				{ LanguageId.af, "Bharat (Indië)" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ባራት (ህንድ)" },
				{ LanguageId.ar, "بهارات (الهند)" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Bharat (Hindistan)" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Бхарат (Індыя)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Бхарат (Индия)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ভারত (ভারত)" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "India" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "bharat (Indija)" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Bharat (Índia)" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Bharat (India)" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Bharat (India)" },
				{ LanguageId.cs, "Bharat (Indie)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Bharat (India)" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Bharat (Indien)" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Bharat (Ινδία)" },
				{ LanguageId.en, "India (Bharat)" },
				{ LanguageId.eo, "Barato (Hindio)" },
				{ LanguageId.es, "Bharat (India)" },
				{ LanguageId.et, "Bharat (India)" },
				{ LanguageId.eu, "Bharat (India)" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "بهارات (هند)" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Bharat (Intia)" },
				{ LanguageId.fil, "Bharat (India)" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Bharat (Inde)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Bharat (Yndia)" },
				{ LanguageId.ga, "Bharat (India)" },
				{ LanguageId.gd, "Bharat (Na h-Innseachan)" },
				{ LanguageId.gl, "Bharat (India)" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ભારત (ભારત)" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Bharat (Indiya)" },
				{ LanguageId.haw, "Bharat (Inia)" },
				{ LanguageId.he, "בהרט (הודו)" },
				{ LanguageId.hi, "भारत (भारत)" },
				{ LanguageId.hr, "Bharat (Indija)" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Bharat (India)" },
				{ LanguageId.hy, "Բհարատ (Հնդկաստան)" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Bharata (India)" },
				{ LanguageId.ig, "Bharat (India)" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bharat (Indland)" },
				{ LanguageId.it, "Bharat (India)" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "バーラト (インド)" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Bharat (India)" },
				{ LanguageId.ka, "ბჰარატი (ინდოეთი)" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Бхарат (Үндістан)" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Bharat (ឥណ្ឌា)" },
				{ LanguageId.kn, "ಭಾರತ್ (ಭಾರತ)" },
				{ LanguageId.ko, "바라트어(인도)" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Бхарат (Индия)" },
				{ LanguageId.la, "Bharat (India)" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Bharat (Indien)" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Bharat (ອິນເດຍ)" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Bharatas (Indija)" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Bharata (Indija)" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Bharat (India)" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Bharat (Inia)" },
				{ LanguageId.mk, "Бхарат (Индија)" },
				{ LanguageId.ml, "ഭാരത് (ഇന്ത്യ)" },
				{ LanguageId.mn, "Бхарат (Энэтхэг)" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "भारत (भारत)" },
				{ LanguageId.ms, "Bharat (India)" },
				{ LanguageId.mt, "Bharat (Indja)" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Bharat (အိန္ဒိယ)" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Bharat (India)" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भारत (भारत)" },
				{ LanguageId.nl, "Bharat (India)" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଭାରତ (ଭାରତ)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਭਾਰਤ (ਭਾਰਤ)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Bharat (Indie)" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بهارت (هند)" },
				{ LanguageId.pt, "Bharat (Índia)" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Bharat (India)" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Бхарат (Индия)" },
				{ LanguageId.rw, "Bharat (Ubuhinde)" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڀارت (ڀارت)" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "භාරත (ඉන්දියාව)" },
				{ LanguageId.sk, "Bharat (India)" },
				{ LanguageId.sl, "Bharat (Indija)" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Bharat (India)" },
				{ LanguageId.so, "Bharat (Hindiya)" },
				{ LanguageId.sq, "Bharat (Indi)" },
				{ LanguageId.sr, "Бхарат (Индија)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Bharat (India)" },
				{ LanguageId.su, "Bharat (India)" },
				{ LanguageId.sv, "Bharat (Indien)" },
				{ LanguageId.sw, "Bharat (India)" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "பாரத் (இந்தியா)" },
				{ LanguageId.te, "భారత్ (భారతదేశం)" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Бҳарат (Ҳиндустон)" },
				{ LanguageId.th, "ภารัต (อินเดีย)" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Bharat (Hindistan)" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Bharat (Hindistan)" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Бхарат (Indiaиндстан)" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Bharat (India)" },
				{ LanguageId.uk, "Бхарат (Індія)" },
				{ LanguageId.ur, "بھارت (بھارت)" },
				{ LanguageId.uz, "Bharat (Hindiston)" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Bharat (Ấn Độ)" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Bharat (Indiya)" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "בהאַראַט (ינדיאַ)" },
				{ LanguageId.yo, "Bharat (India)" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "巴拉特（印度）" },
				{ LanguageId.zu, "I-Bharat (India)" },
			}
		);
	}
}
