// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class IS
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "354",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Iceland" },
				{ LanguageId.da, "Island" },
				{ LanguageId.af, "Ysland" },
				{ LanguageId.agq, "Aesɨ̀lân" },
				{ LanguageId.ak, "Aesland" },
				{ LanguageId.am, "አይስላንድ" },
				{ LanguageId.ar, "آيسلندا" },
				{ LanguageId.arn, "Iceland" },
				{ LanguageId.@as, "আইচলেণ্ড" },
				{ LanguageId.asa, "Aithlandi" },
				{ LanguageId.ast, "Islandia" },
				{ LanguageId.az, "İslandiya" },
				{ LanguageId.ba, "Исландия" },
				{ LanguageId.bas, "Ìslandìà" },
				{ LanguageId.be, "Ісландыя" },
				{ LanguageId.bem, "Iceland" },
				{ LanguageId.bez, "Huaislandi" },
				{ LanguageId.bg, "Исландия" },
				{ LanguageId.bin, "Iceland" },
				{ LanguageId.bm, "Isilandi" },
				{ LanguageId.bn, "আইসল্যান্ড" },
				{ LanguageId.bo, "ཨ་ཡིསུ་ལེན་ཌ།" },
				{ LanguageId.br, "Island" },
				{ LanguageId.brx, "आइसलेण्ड" },
				{ LanguageId.bs, "Island" },
				{ LanguageId.byn, "Iceland" },
				{ LanguageId.ca, "Islàndia" },
				{ LanguageId.ccp, "𑄃𑄭𑄥𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Исланди" },
				{ LanguageId.ceb, "Iceland" },
				{ LanguageId.cgg, "Aisilandi" },
				{ LanguageId.chr, "ᏧᏁᏍᏓᎸᎯ" },
				{ LanguageId.ckb, "ئایسلەند" },
				{ LanguageId.co, "Islanda" },
				{ LanguageId.cs, "Island" },
				{ LanguageId.cu, "Исландъ" },
				{ LanguageId.cy, "Gwlad yr Iâ" },
				{ LanguageId.dav, "Aislandi" },
				{ LanguageId.de, "Island" },
				{ LanguageId.dje, "Ayseland" },
				{ LanguageId.doi, "आइसलैंड" },
				{ LanguageId.dsb, "Islandska" },
				{ LanguageId.dua, "Iceland" },
				{ LanguageId.dv, "އައިސްލޭންޑް" },
				{ LanguageId.dz, "ཨཱའིས་ལེནཌ" },
				{ LanguageId.ebu, "Aislandi" },
				{ LanguageId.ee, "Aiseland nutome" },
				{ LanguageId.el, "Ισλανδία" },
				{ LanguageId.en, "Iceland" },
				{ LanguageId.eo, "Islando" },
				{ LanguageId.es, "Islandia" },
				{ LanguageId.et, "Island" },
				{ LanguageId.eu, "Islandia" },
				{ LanguageId.ewo, "Isəlándə" },
				{ LanguageId.fa, "ایسلند" },
				{ LanguageId.ff, "Islannda" },
				{ LanguageId.fi, "Islanti" },
				{ LanguageId.fil, "Iceland" },
				{ LanguageId.fo, "Ísland" },
				{ LanguageId.fr, "Islande" },
				{ LanguageId.fur, "Islande" },
				{ LanguageId.fy, "Yslân" },
				{ LanguageId.ga, "an Íoslainn" },
				{ LanguageId.gd, "Innis Tìle" },
				{ LanguageId.gl, "Islandia" },
				{ LanguageId.gn, "Islandia" },
				{ LanguageId.gsw, "Iisland" },
				{ LanguageId.gu, "આઇસલૅન્ડ" },
				{ LanguageId.guz, "Aislandi" },
				{ LanguageId.gv, "Yn Islaant" },
				{ LanguageId.ha, "Aisalan" },
				{ LanguageId.haw, "ʻĀina Hau" },
				{ LanguageId.he, "איסלנד" },
				{ LanguageId.hi, "आइसलैंड" },
				{ LanguageId.hr, "Island" },
				{ LanguageId.hsb, "Islandska" },
				{ LanguageId.hu, "Izland" },
				{ LanguageId.hy, "Իսլանդիա" },
				{ LanguageId.ia, "Islanda" },
				{ LanguageId.ibb, "Iceland" },
				{ LanguageId.id, "Islandia" },
				{ LanguageId.ig, "Iceland" },
				{ LanguageId.ii, "冰岛" },
				{ LanguageId.@is, "Ísland" },
				{ LanguageId.it, "Islanda" },
				{ LanguageId.iu, "ᐃᓯᓚᓐᑦ" },
				{ LanguageId.ja, "アイスランド" },
				{ LanguageId.jgo, "Iceland" },
				{ LanguageId.jmc, "Aislandi" },
				{ LanguageId.jv, "Èslan" },
				{ LanguageId.ka, "ისლანდია" },
				{ LanguageId.kab, "Island" },
				{ LanguageId.kam, "Aislandi" },
				{ LanguageId.kde, "Aislandi" },
				{ LanguageId.kea, "Islándia" },
				{ LanguageId.khq, "Ayceland" },
				{ LanguageId.ki, "Aislandi" },
				{ LanguageId.kk, "Исландия" },
				{ LanguageId.kkj, "Iceland" },
				{ LanguageId.kl, "Islandi" },
				{ LanguageId.kln, "Emetab Iceland" },
				{ LanguageId.km, "អ៊ីស្លង់" },
				{ LanguageId.kn, "ಐಸ್‌ಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "아이슬란드" },
				{ LanguageId.kok, "आइसलँड" },
				{ LanguageId.kr, "Iceland" },
				{ LanguageId.ks, "اَیِسلینڑ" },
				{ LanguageId.ksb, "Aislandi" },
				{ LanguageId.ksf, "zǝ i glás" },
				{ LanguageId.ksh, "Ißland" },
				{ LanguageId.kw, "Island" },
				{ LanguageId.ky, "Исландия" },
				{ LanguageId.la, "Islandia" },
				{ LanguageId.lag, "Aisiláandi" },
				{ LanguageId.lb, "Island" },
				{ LanguageId.lg, "Ayisirandi" },
				{ LanguageId.lkt, "Iceland" },
				{ LanguageId.ln, "Isilandɛ" },
				{ LanguageId.lo, "ໄອສແລນ" },
				{ LanguageId.lrc, "ایسلند" },
				{ LanguageId.lt, "Islandija" },
				{ LanguageId.luo, "Iceland" },
				{ LanguageId.luy, "Aislandi" },
				{ LanguageId.lv, "Islande" },
				{ LanguageId.mai, "आइसलैंड" },
				{ LanguageId.mas, "Aislandi" },
				{ LanguageId.mer, "Aisilandi" },
				{ LanguageId.mfe, "Island" },
				{ LanguageId.mg, "Islandy" },
				{ LanguageId.mgo, "Iceland" },
				{ LanguageId.mi, "Tiorangi" },
				{ LanguageId.mk, "Исланд" },
				{ LanguageId.ml, "ഐസ്‌ലാന്റ്" },
				{ LanguageId.mn, "Исланд" },
				{ LanguageId.mni, "আইচলেন্দ" },
				{ LanguageId.moh, "Iceland" },
				{ LanguageId.mr, "आइसलँड" },
				{ LanguageId.ms, "Iceland" },
				{ LanguageId.mt, "l-Iżlanda" },
				{ LanguageId.mua, "Sǝr Island" },
				{ LanguageId.my, "အိုက်စလန်" },
				{ LanguageId.mzn, "ایسلند" },
				{ LanguageId.naq, "Iceland" },
				{ LanguageId.nb, "Island" },
				{ LanguageId.nd, "Iceland" },
				{ LanguageId.nds, "Island" },
				{ LanguageId.ne, "आइस्ल्याण्ड" },
				{ LanguageId.nl, "IJsland" },
				{ LanguageId.nmg, "Island" },
				{ LanguageId.nn, "Island" },
				{ LanguageId.nnh, "Iceland" },
				{ LanguageId.nqo, "ߌߛߑߟߊߘ" },
				{ LanguageId.nr, "Iceland" },
				{ LanguageId.nso, "Iceland" },
				{ LanguageId.nus, "Iceland" },
				{ LanguageId.nyn, "Aisilandi" },
				{ LanguageId.oc, "Islàndia" },
				{ LanguageId.om, "Ayeslaand" },
				{ LanguageId.or, "ଆଇସଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "Исланди" },
				{ LanguageId.pa, "ਆਈਸਲੈਂਡ" },
				{ LanguageId.pap, "Islándia" },
				{ LanguageId.pcm, "Aísland" },
				{ LanguageId.pl, "Islandia" },
				{ LanguageId.prg, "Islandija" },
				{ LanguageId.ps, "آیسلینډ" },
				{ LanguageId.pt, "Islândia" },
				{ LanguageId.qu, "Islandia" },
				{ LanguageId.quc, "Islandia" },
				{ LanguageId.rm, "Islanda" },
				{ LanguageId.rn, "Ayisilandi" },
				{ LanguageId.ro, "Islanda" },
				{ LanguageId.rof, "Aislandi" },
				{ LanguageId.ru, "Исландия" },
				{ LanguageId.rw, "Isilande" },
				{ LanguageId.rwk, "Aislandi" },
				{ LanguageId.sa, "आइसलैंड" },
				{ LanguageId.sah, "Исландия" },
				{ LanguageId.saq, "Aislandi" },
				{ LanguageId.sat, "आइसलैंड" },
				{ LanguageId.sbp, "Ayisilendi" },
				{ LanguageId.sd, "آئس لينڊ" },
				{ LanguageId.se, "Islánda" },
				{ LanguageId.seh, "Islândia" },
				{ LanguageId.ses, "Ayceland" },
				{ LanguageId.sg, "Islânde" },
				{ LanguageId.shi, "ⵉⵙⵍⴰⵏⴷ" },
				{ LanguageId.si, "අයිස්ලන්තය" },
				{ LanguageId.sk, "Island" },
				{ LanguageId.sl, "Islandija" },
				{ LanguageId.sma, "Islánda" },
				{ LanguageId.smj, "Island" },
				{ LanguageId.smn, "Island" },
				{ LanguageId.sms, "Island" },
				{ LanguageId.sn, "Iceland" },
				{ LanguageId.so, "Ayslaand" },
				{ LanguageId.sq, "Islandë" },
				{ LanguageId.sr, "Исланд" },
				{ LanguageId.ss, "I-Iceland" },
				{ LanguageId.ssy, "Iceland" },
				{ LanguageId.st, "Iceland" },
				{ LanguageId.su, "Islandia" },
				{ LanguageId.sv, "Island" },
				{ LanguageId.sw, "Aisilandi" },
				{ LanguageId.syr, "ܐܝܣܠܢܕ" },
				{ LanguageId.ta, "ஐஸ்லாந்து" },
				{ LanguageId.te, "ఐస్లాండ్" },
				{ LanguageId.teo, "Aislandi" },
				{ LanguageId.tg, "Исландия" },
				{ LanguageId.th, "ไอซ์แลนด์" },
				{ LanguageId.ti, "ኣይስላንድ" },
				{ LanguageId.tig, "አይስላንድ" },
				{ LanguageId.tk, "Islandiýa" },
				{ LanguageId.tn, "Iceland" },
				{ LanguageId.to, "ʻAisilani" },
				{ LanguageId.tr, "İzlanda" },
				{ LanguageId.ts, "Iceland" },
				{ LanguageId.tt, "Исландия" },
				{ LanguageId.twq, "Ayseland" },
				{ LanguageId.tzm, "Islanḍa" },
				{ LanguageId.ug, "ئىسلاندىيە" },
				{ LanguageId.uk, "Ісландія" },
				{ LanguageId.ur, "آئس لینڈ" },
				{ LanguageId.uz, "Islandiya" },
				{ LanguageId.vai, "ꕉꔤꔻ ꖨꕮꕊ" },
				{ LanguageId.ve, "Iceland" },
				{ LanguageId.vi, "Iceland" },
				{ LanguageId.vo, "Lisladeän" },
				{ LanguageId.vun, "Aislandi" },
				{ LanguageId.wae, "Island" },
				{ LanguageId.wal, "Iceland" },
				{ LanguageId.wo, "Islànd" },
				{ LanguageId.xh, "E-Iceland" },
				{ LanguageId.xog, "Ayisirandi" },
				{ LanguageId.yav, "isláand" },
				{ LanguageId.yi, "איסלאַנד" },
				{ LanguageId.yo, "Aṣilandi" },
				{ LanguageId.zgh, "ⵉⵙⵍⴰⵏⴷ" },
				{ LanguageId.zh, "冰岛" },
				{ LanguageId.zu, "i-Iceland" },
			}
		);
	}
}
