using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class KM
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "269",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Comorerne" },
				{ LanguageId.af, "Comore" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኮሞሮስ" },
				{ LanguageId.ar, "جزر القمر" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Komor adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Каморскія выспы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Коморски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "কমোরোস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Komori" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Comores" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Comoros" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Comoros" },
				{ LanguageId.cs, "Komory" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Comoros" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Komoren" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Κομόρες" },
				{ LanguageId.en, "Comoros" },
				{ LanguageId.eo, "Komoroj" },
				{ LanguageId.es, "Comoras" },
				{ LanguageId.et, "Komoorid" },
				{ LanguageId.eu, "Komoreak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "کومور" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Komorit" },
				{ LanguageId.fil, "Comoros" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Comores" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Komoaren" },
				{ LanguageId.ga, "Oileáin Chomóra" },
				{ LanguageId.gd, "Comoros" },
				{ LanguageId.gl, "Comoras" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "કોમોરોસ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Comoros" },
				{ LanguageId.haw, "Komorosa" },
				{ LanguageId.he, "קומורו" },
				{ LanguageId.hi, "कोमोरोस" },
				{ LanguageId.hr, "Komori" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Comore-szigetek" },
				{ LanguageId.hy, "Կոմորներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Komoro" },
				{ LanguageId.ig, "Comoros" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Kómoreyjar" },
				{ LanguageId.it, "Comore" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コモロ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Comoros" },
				{ LanguageId.ka, "კომორის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Комор аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កូម៉ូរ៉ូ" },
				{ LanguageId.kn, "ಕೊಮೊರೊಸ್" },
				{ LanguageId.ko, "코모로" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Комор аралдары" },
				{ LanguageId.la, "Comoros" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Komoren" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໂຄໂມໂຣສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Komorai" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Komoru salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Comores" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Komoro" },
				{ LanguageId.mk, "Коморите" },
				{ LanguageId.ml, "കൊമോറോസ്" },
				{ LanguageId.mn, "Комор" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "कोमोरोस" },
				{ LanguageId.ms, "Comoros" },
				{ LanguageId.mt, "Komoros" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကွန်မိုရို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Komorene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोमोरोस" },
				{ LanguageId.nl, "Comoren" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କୋମୋରସ୍ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੋਮੋਰੋਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Komory" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کوموروس" },
				{ LanguageId.pt, "Comores" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Comore" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Коморские Острова" },
				{ LanguageId.rw, "Comoros" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪوموروس" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කොමරෝස්" },
				{ LanguageId.sk, "Komory" },
				{ LanguageId.sl, "Komori" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Komorosi" },
				{ LanguageId.so, "Komoros" },
				{ LanguageId.sq, "Komoret" },
				{ LanguageId.sr, "Цоморос" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Comoros" },
				{ LanguageId.su, "Komoro" },
				{ LanguageId.sv, "Komorerna" },
				{ LanguageId.sw, "Comoro" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கொமரோஸ்" },
				{ LanguageId.te, "కొమొరోస్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Комор" },
				{ LanguageId.th, "คอโมโรส" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Komorlar" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Komorlar" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Комор" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Comoros" },
				{ LanguageId.uk, "Коморські острови" },
				{ LanguageId.ur, "کوموروس" },
				{ LanguageId.uz, "Komor orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Comoros" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Khomoros" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "קאָמאָראָס" },
				{ LanguageId.yo, "Comoros" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "科摩罗" },
				{ LanguageId.zu, "e-Comoros" },
			}
		);
	}
}
