// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class KM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "269",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Comorerne" },
				{ LanguageId.af, "Comore" },
				{ LanguageId.agq, "Komolòs" },
				{ LanguageId.ak, "Kɔmɔrɔs" },
				{ LanguageId.am, "ኮሞሮስ" },
				{ LanguageId.ar, "جزر القمر" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "কোমোৰোজ" },
				{ LanguageId.asa, "Komoro" },
				{ LanguageId.ast, "Les Comores" },
				{ LanguageId.az, "Komor adaları" },
				{ LanguageId.ba, "Комор утрауҙары" },
				{ LanguageId.bas, "Kɔ̀mɔ̂r" },
				{ LanguageId.be, "Каморскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hukomoro" },
				{ LanguageId.bg, "Коморски острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Komɔri" },
				{ LanguageId.bn, "কমোরোস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Komorez" },
				{ LanguageId.brx, "कम’र’ज" },
				{ LanguageId.bs, "Komori" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Comores" },
				{ LanguageId.ccp, "𑄇𑄧𑄟𑄮𑄢𑄮𑄌𑄴" },
				{ LanguageId.ce, "Комораш" },
				{ LanguageId.ceb, "Comoros" },
				{ LanguageId.cgg, "Koromo" },
				{ LanguageId.chr, "ᎪᎼᎳᏍ" },
				{ LanguageId.ckb, "دوورگەکانی کۆمۆر" },
				{ LanguageId.co, "Comoros" },
				{ LanguageId.cs, "Komory" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Comoros" },
				{ LanguageId.dav, "Komoro" },
				{ LanguageId.de, "Komoren" },
				{ LanguageId.dje, "Komoor" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Komory" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཀོ་མོ་རོས" },
				{ LanguageId.ebu, "Komoro" },
				{ LanguageId.ee, "Komoros nutome" },
				{ LanguageId.el, "Κομόρες" },
				{ LanguageId.en, "Comoros" },
				{ LanguageId.eo, "Komoroj" },
				{ LanguageId.es, "Comoras" },
				{ LanguageId.et, "Komoorid" },
				{ LanguageId.eu, "Komoreak" },
				{ LanguageId.ewo, "Komɔ́r" },
				{ LanguageId.fa, "کومور" },
				{ LanguageId.ff, "Komoor" },
				{ LanguageId.fi, "Komorit" },
				{ LanguageId.fil, "Comoros" },
				{ LanguageId.fo, "Komoroyggjar" },
				{ LanguageId.fr, "Comores" },
				{ LanguageId.fur, "Comoris" },
				{ LanguageId.fy, "Comoren" },
				{ LanguageId.ga, "Oileáin Chomóra" },
				{ LanguageId.gd, "Comoros" },
				{ LanguageId.gl, "Comores" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Komoore" },
				{ LanguageId.gu, "કોમોરસ" },
				{ LanguageId.guz, "Komoro" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Kwamoras" },
				{ LanguageId.haw, "Komorosa" },
				{ LanguageId.he, "קומורו" },
				{ LanguageId.hi, "कोमोरोस" },
				{ LanguageId.hr, "Komori" },
				{ LanguageId.hsb, "Komory" },
				{ LanguageId.hu, "Comore-szigetek" },
				{ LanguageId.hy, "Կոմորյան կղզիներ" },
				{ LanguageId.ia, "Comoros" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Komoro" },
				{ LanguageId.ig, "Comoros" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Kómoreyjar" },
				{ LanguageId.it, "Comore" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "コモロ" },
				{ LanguageId.jgo, "Kɔmɔ́lɔshi" },
				{ LanguageId.jmc, "Komoro" },
				{ LanguageId.jv, "Komoro" },
				{ LanguageId.ka, "კომორის კუნძულები" },
				{ LanguageId.kab, "Kumur" },
				{ LanguageId.kam, "Komoro" },
				{ LanguageId.kde, "Komolo" },
				{ LanguageId.kea, "Kamoris" },
				{ LanguageId.khq, "Komoor" },
				{ LanguageId.ki, "Komoro" },
				{ LanguageId.kk, "Комор аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Comoros" },
				{ LanguageId.km, "កូម័រ" },
				{ LanguageId.kn, "ಕೊಮೊರೊಸ್" },
				{ LanguageId.ko, "코모로" },
				{ LanguageId.kok, "कोमोरोस" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "کَمورَس" },
				{ LanguageId.ksb, "Komolo" },
				{ LanguageId.ksf, "komɔr" },
				{ LanguageId.ksh, "de Kommoore" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Коморос" },
				{ LanguageId.la, "Comoros" },
				{ LanguageId.lag, "Komóoro" },
				{ LanguageId.lb, "Komoren" },
				{ LanguageId.lg, "Bizinga by’eKomoro" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Komorɛ" },
				{ LanguageId.lo, "ໂຄໂມໂຣສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Komorai" },
				{ LanguageId.luo, "Comoros" },
				{ LanguageId.luy, "Komoro" },
				{ LanguageId.lv, "Komoru salas" },
				{ LanguageId.mai, "कोमोरोस" },
				{ LanguageId.mas, "Komoro" },
				{ LanguageId.mer, "Komoro" },
				{ LanguageId.mfe, "Komor" },
				{ LanguageId.mg, "Kômaoro" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Komoro" },
				{ LanguageId.mk, "Коморски Острови" },
				{ LanguageId.ml, "കോമൊറോസ്" },
				{ LanguageId.mn, "Коморын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "कोमोरोज" },
				{ LanguageId.ms, "Comoros" },
				{ LanguageId.mt, "Comoros" },
				{ LanguageId.mua, "komora" },
				{ LanguageId.my, "ကိုမိုရိုစ်" },
				{ LanguageId.mzn, "کومور" },
				{ LanguageId.naq, "Comoros" },
				{ LanguageId.nb, "Komorene" },
				{ LanguageId.nd, "Khomoro" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोमोरोस" },
				{ LanguageId.nl, "Comoren" },
				{ LanguageId.nmg, "Kɔmɔr" },
				{ LanguageId.nn, "Komorane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߡߐߙ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Komruth" },
				{ LanguageId.nyn, "Koromo" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Komoroos" },
				{ LanguageId.or, "କୋମୋରସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੋਮੋਰੋਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Kọ́mọ́ros" },
				{ LanguageId.pl, "Komory" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کوموروس" },
				{ LanguageId.pt, "Comores" },
				{ LanguageId.qu, "Comoras" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Comoras" },
				{ LanguageId.rn, "Izinga rya Komore" },
				{ LanguageId.ro, "Comore" },
				{ LanguageId.rof, "Komoro" },
				{ LanguageId.ru, "Коморы" },
				{ LanguageId.rw, "Comoros" },
				{ LanguageId.rwk, "Komoro" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Komoro" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Komolo" },
				{ LanguageId.sd, "ڪوموروس" },
				{ LanguageId.se, "Komoros" },
				{ LanguageId.seh, "Comores" },
				{ LanguageId.ses, "Komoor" },
				{ LanguageId.sg, "Kömôro" },
				{ LanguageId.shi, "ⵇⵓⵎⵓⵔ" },
				{ LanguageId.si, "කොමොරෝස්" },
				{ LanguageId.sk, "Komory" },
				{ LanguageId.sl, "Komori" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Komoreh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Komoro" },
				{ LanguageId.so, "Komooros" },
				{ LanguageId.sq, "Komore" },
				{ LanguageId.sr, "Коморска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Comoros" },
				{ LanguageId.su, "Komoro" },
				{ LanguageId.sv, "Komorerna" },
				{ LanguageId.sw, "Komoro" },
				{ LanguageId.syr, "ܓܙܪܬܐ ܕܩܡܪ" },
				{ LanguageId.ta, "கோமரோஸ்" },
				{ LanguageId.te, "కొమొరోస్" },
				{ LanguageId.teo, "Komoro" },
				{ LanguageId.tg, "Комор" },
				{ LanguageId.th, "คอโมโรส" },
				{ LanguageId.ti, "ኮሞሮስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Komor adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Komolosi" },
				{ LanguageId.tr, "Komorlar" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Комор утраулары" },
				{ LanguageId.twq, "Komoor" },
				{ LanguageId.tzm, "Qumur" },
				{ LanguageId.ug, "كومورو" },
				{ LanguageId.uk, "Комори" },
				{ LanguageId.ur, "کوموروس" },
				{ LanguageId.uz, "Komor orollari" },
				{ LanguageId.vai, "ꖏꕹꖄꔻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Comoros" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Komoro" },
				{ LanguageId.wae, "Komore" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Komoor" },
				{ LanguageId.xh, "EComoros" },
				{ LanguageId.xog, "Ebizinga bya Komoro" },
				{ LanguageId.yav, "Kɔmɔ́ɔl" },
				{ LanguageId.yi, "קאמאראס" },
				{ LanguageId.yo, "Kòmòrósì" },
				{ LanguageId.zgh, "ⵇⵓⵎⵓⵔ" },
				{ LanguageId.zh, "科摩罗" },
				{ LanguageId.zu, "i-Comoros" },
			}
		);
	}
}
