// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class KN
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Kitts og Nevis" },
				{ LanguageId.af, "Sint Kitts en Nevis" },
				{ LanguageId.agq, "Sɛ̀n Kî à Nevì" },
				{ LanguageId.ak, "Saint Kitts ne Nevis" },
				{ LanguageId.am, "ቅዱስ ኪትስ እና ኔቪስ" },
				{ LanguageId.ar, "سانت كيتس ونيفيس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট কিটছ আৰু নেভিছ" },
				{ LanguageId.asa, "Thantakitdhi na Nevith" },
				{ LanguageId.ast, "Saint Kitts y Nevis" },
				{ LanguageId.az, "Sent-Kits və Nevis" },
				{ LanguageId.ba, "Сент-Китс һәм Невис" },
				{ LanguageId.bas, "Nûmpubi Kîts nì Nevìs" },
				{ LanguageId.be, "Сент-Кітс і Невіс" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husantakitzi na Hunevis" },
				{ LanguageId.bg, "Сейнт Китс и Невис" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kristɔfo-Senu-ni-Ɲevɛs" },
				{ LanguageId.bn, "সেন্ট কিটস ও নেভিস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Saint Kitts-ha-Nevis" },
				{ LanguageId.brx, "सैन्ट कीत्स आरो नेभिस" },
				{ LanguageId.bs, "Sveti Kits i Nevis" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint Kitts i Nevis" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄇𑄨𑄑𑄴𑄥𑄴 𑄃𑄮 𑄚𑄬𑄞𑄨𑄌𑄴" },
				{ LanguageId.ce, "Сент-Китс а, Невис а" },
				{ LanguageId.ceb, "St. Kitts & Nevis" },
				{ LanguageId.cgg, "Senti Kittis na Nevisi" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᎨᏘᏏ ᎠᎴ ᏁᏪᏏ" },
				{ LanguageId.ckb, "سەن کیتس و نیڤیس" },
				{ LanguageId.co, "Santu Kitts è Nevis" },
				{ LanguageId.cs, "Svatý Kryštof a Nevis" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Kitts a Nevis" },
				{ LanguageId.dav, "Santakitzi na Nevis" },
				{ LanguageId.de, "St. Kitts und Nevis" },
				{ LanguageId.dje, "Seŋ Kitts nda Nevis" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Kitts a Nevis" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ ཀིཊས་ དང་ ནེ་བིས" },
				{ LanguageId.ebu, "Santakitzi na Nevis" },
				{ LanguageId.ee, "Saint Kitis kple Nevis nutome" },
				{ LanguageId.el, "Σεν Κιτς και Νέβις" },
				{ LanguageId.en, "St. Kitts & Nevis" },
				{ LanguageId.eo, "Sankta Kristoforo kaj Neviso" },
				{ LanguageId.es, "San Cristóbal y Nieves" },
				{ LanguageId.et, "Saint Kitts ja Nevis" },
				{ LanguageId.eu, "Saint Kitts eta Nevis" },
				{ LanguageId.ewo, "Ǹfúfúb-Kilisətóv-ai-Nevis" },
				{ LanguageId.fa, "سنت کیتس و نویس" },
				{ LanguageId.ff, "Sent Kits e Newis" },
				{ LanguageId.fi, "Saint Kitts ja Nevis" },
				{ LanguageId.fil, "St. Kitts & Nevis" },
				{ LanguageId.fo, "St. Kitts & Nevis" },
				{ LanguageId.fr, "Saint-Christophe-et-Niévès" },
				{ LanguageId.fur, "San Kitts e Nevis" },
				{ LanguageId.fy, "Saint Kitts en Nevis" },
				{ LanguageId.ga, "San Críostóir-Nimheas" },
				{ LanguageId.gd, "Naomh Crìstean is Nibheis" },
				{ LanguageId.gl, "Saint Kitts e Nevis" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Kitts und Niuwis" },
				{ LanguageId.gu, "સેંટ કિટ્સ અને નેવિસ" },
				{ LanguageId.guz, "Santakitzi na Nevis" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Kiti Da Nebis" },
				{ LanguageId.haw, "Kāna Kiti me Newia" },
				{ LanguageId.he, "סנט קיטס ונוויס" },
				{ LanguageId.hi, "सेंट किट्स और नेविस" },
				{ LanguageId.hr, "Sveti Kristofor i Nevis" },
				{ LanguageId.hsb, "St. Kitts a Nevis" },
				{ LanguageId.hu, "Saint Kitts és Nevis" },
				{ LanguageId.hy, "Սենթ Քիտս և Նևիս" },
				{ LanguageId.ia, "Sancte Christophoro e Nevis" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Kitts dan Nevis" },
				{ LanguageId.ig, "St. Kitts & Nevis" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Kitts og Nevis" },
				{ LanguageId.it, "Saint Kitts e Nevis" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントクリストファー・ネーヴィス" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Santakitzi na Nevis" },
				{ LanguageId.jv, "Saint Kits lan Nèvis" },
				{ LanguageId.ka, "სენტ-კიტსი და ნევისი" },
				{ LanguageId.kab, "San Kits d Nivis" },
				{ LanguageId.kam, "Santakitzi na Nevis" },
				{ LanguageId.kde, "Santakitzi na Nevis" },
				{ LanguageId.kea, "San Kristovan i Nevis" },
				{ LanguageId.khq, "Seŋ Kitts nda Nevis" },
				{ LanguageId.ki, "Santakitzi na Nevis" },
				{ LanguageId.kk, "Сент-Китс және Невис" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Saint Kitts ak Nevis" },
				{ LanguageId.km, "សាំង​គីត និង ណេវីស" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಕಿಟ್ಸ್ ಮತ್ತು ನೆವಿಸ್" },
				{ LanguageId.ko, "세인트키츠 네비스" },
				{ LanguageId.kok, "सांव क्रिस्टोवांव आनी नेविस" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ کِٹَس تہٕ نیوِس" },
				{ LanguageId.ksb, "Santakitzi na Nevis" },
				{ LanguageId.ksf, "sɛnkrǝstɔ́f ri nyɛ́vǝ" },
				{ LanguageId.ksh, "Zint Kitts un Nevis" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Китс жана Невис" },
				{ LanguageId.la, "Saint Kitts et Nevis" },
				{ LanguageId.lag, "Mʉtakatíifu kitisi na Nevíisi" },
				{ LanguageId.lb, "St. Kitts an Nevis" },
				{ LanguageId.lg, "Senti Kitisi ne Nevisi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu krístofe mpé Nevɛ̀s" },
				{ LanguageId.lo, "ເຊນ ຄິດ ແລະ ເນວິສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sent Kitsas ir Nevis" },
				{ LanguageId.luo, "Saint Kitts gi Nevis" },
				{ LanguageId.luy, "Santakitzi na Nevis" },
				{ LanguageId.lv, "Sentkitsa un Nevisa" },
				{ LanguageId.mai, "सेंट किट्स आ नेविस" },
				{ LanguageId.mas, "Santakitzi na Nevis" },
				{ LanguageId.mer, "Santakitzi na Nevis" },
				{ LanguageId.mfe, "Saint-Christophe-ek-Niévès" },
				{ LanguageId.mg, "Saint-Christophe-et-Niévès" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Kiti me Newhi" },
				{ LanguageId.mk, "Свети Китс и Невис" },
				{ LanguageId.ml, "സെന്റ് കിറ്റ്‌സും നെവിസും" },
				{ LanguageId.mn, "Сент-Киттс ба Невис" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट किट्स आणि नेव्हिस" },
				{ LanguageId.ms, "Saint Kitts dan Nevis" },
				{ LanguageId.mt, "Saint Kitts u Nevis" },
				{ LanguageId.mua, "Sǝr Kristof ne Nievǝ" },
				{ LanguageId.my, "စိန့်ကစ်နှင့်နီဗီစ်" },
				{ LanguageId.mzn, "سنت کیتس و نویس" },
				{ LanguageId.naq, "Saint Kitts and Nevis" },
				{ LanguageId.nb, "Saint Kitts og Nevis" },
				{ LanguageId.nd, "Saint Kitts and Nevis" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट किट्स र नेभिस" },
				{ LanguageId.nl, "Saint Kitts en Nevis" },
				{ LanguageId.nmg, "Saint Kitts na Nevis" },
				{ LanguageId.nn, "Saint Kitts og Nevis" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߞߙߌߛߑߕߐߝ ߣߌ߫ ߢߝ߭ߋ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Senti Kittis na Nevisi" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Kiitis fi Neevis" },
				{ LanguageId.or, "ସେଣ୍ଟ କିଟସ୍‌ ଏବଂ ନେଭିସ୍‌" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਕਿਟਸ ਐਂਡ ਨੇਵਿਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Kits & Nẹ́vis" },
				{ LanguageId.pl, "Saint Kitts i Nevis" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ کټس او نیویس" },
				{ LanguageId.pt, "São Cristóvão e Névis" },
				{ LanguageId.qu, "San Cristóbal y Nieves" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Son Cristof e Nevis" },
				{ LanguageId.rn, "Sekitsi na Nevisi" },
				{ LanguageId.ro, "Saint Kitts și Nevis" },
				{ LanguageId.rof, "Santakitzi na Nevis" },
				{ LanguageId.ru, "Сент-Китс и Невис" },
				{ LanguageId.rw, "Uwera Kitts na Nevis" },
				{ LanguageId.rwk, "Santakitzi na Nevis" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Santakitzi na Nevis" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Santakitisi ni Nevisi" },
				{ LanguageId.sd, "سينٽ ڪٽس و نيوس" },
				{ LanguageId.se, "Saint Kitts ja Nevis" },
				{ LanguageId.seh, "São Cristovão e Nevis" },
				{ LanguageId.ses, "Seŋ Kitts nda Nevis" },
				{ LanguageId.sg, "Sên-Krïstôfo-na-Nevîsi" },
				{ LanguageId.shi, "ⵙⴰⵏⴽⵔⵉⵙ ⴷ ⵏⵉⴼⵉⵙ" },
				{ LanguageId.si, "ශාන්ත කිට්ස් සහ නේවිස්" },
				{ LanguageId.sk, "Svätý Krištof a Nevis" },
				{ LanguageId.sl, "Sveti Krištof in Nevis" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Kitts já Nevis" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saint Kitts and Nevis" },
				{ LanguageId.so, "St. Kitts iyo Nevis" },
				{ LanguageId.sq, "Shën-Kits dhe Nevis" },
				{ LanguageId.sr, "Сент Китс и Невис" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saint Kitts le Nevis" },
				{ LanguageId.su, "Saint Kitts jeung Névis" },
				{ LanguageId.sv, "S:t Kitts och Nevis" },
				{ LanguageId.sw, "St. Kitts na Nevis" },
				{ LanguageId.syr, "ܣܐܢܬ ܟܝܬܣ ܘܢܝܒܝܣ" },
				{ LanguageId.ta, "செயின்ட் கிட்ஸ் & நெவிஸ்" },
				{ LanguageId.te, "సెయింట్ కిట్స్ & నెవిస్" },
				{ LanguageId.teo, "Santakitzi na Nevis" },
				{ LanguageId.tg, "Сент-Китс ва Невис" },
				{ LanguageId.th, "เซนต์คิตส์และเนวิส" },
				{ LanguageId.ti, "ቅዱስ ኪትስን ኔቪስን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sent-Kits we Newis" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Kitisi mo Nevisi" },
				{ LanguageId.tr, "Saint Kitts ve Nevis" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент-Китс һәм Невис" },
				{ LanguageId.twq, "Seŋ Kitts nda Nevis" },
				{ LanguageId.tzm, "Santekits d Nivis" },
				{ LanguageId.ug, "ساينت كىتىس ۋە نېۋىس" },
				{ LanguageId.uk, "Сент-Кітс і Невіс" },
				{ LanguageId.ur, "سینٹ کٹس اور نیویس" },
				{ LanguageId.uz, "Sent-Kits va Nevis" },
				{ LanguageId.vai, "ꔻꘋ ꕃꔳꔻ ꗪ ꔕꔲꔻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Kitts và Nevis" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Santakitzi na Nevis" },
				{ LanguageId.wae, "St. Kitts und Nevis" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Kits ak Newis" },
				{ LanguageId.xh, "ESt. Kitts & Nevis" },
				{ LanguageId.xog, "Senti Kitisi ne Nevisi" },
				{ LanguageId.yav, "sɛ́ŋkilistɔ́f eniɛ́f" },
				{ LanguageId.yi, "סיינט קיטץ און נעוויס" },
				{ LanguageId.yo, "Kiiti ati Neefi" },
				{ LanguageId.zgh, "ⵙⴰⵏⴽⵔⵉⵙ ⴷ ⵏⵉⴼⵉⵙ" },
				{ LanguageId.zh, "圣基茨和尼维斯" },
				{ LanguageId.zu, "i-Saint Kitts ne-Nevis" },
			}
		);
	}
}
