using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class KN
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Kitts og Nevis" },
				{ LanguageId.af, "Saint Kitts en Nevis" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሰይንት ኪትስ እና ኔቪስ" },
				{ LanguageId.ar, "سانت كيتس ونيفيس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Saint Kitts və Nevis" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сэнт-Кітс і Нэвіс" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сейнт Китс и Невис" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট কিটস ও নেভিস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Saint Kitts i Nevis" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint Kitts i Nevis" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Saint Kitts ug Nevis" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Santu Kitts è Nevis" },
				{ LanguageId.cs, "Svatý Kryštof a Nevis" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sant Kitts a Nevis" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Kitts und Nevis" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Saint Kitts and Nevis" },
				{ LanguageId.en, "Saint Kitts and Nevis" },
				{ LanguageId.eo, "Sankta-Kito kaj Neviso" },
				{ LanguageId.es, "San Cristóbal y Nieves" },
				{ LanguageId.et, "Saint Kitts ja Nevis" },
				{ LanguageId.eu, "Saint Kitts eta Nevis" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت کیتس و نویس" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saint Kitts ja Nevis" },
				{ LanguageId.fil, "Saint Kitts at Nevis" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Saint-Christophe-et-Niévès" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint-Kits en Nevis" },
				{ LanguageId.ga, "San Críostóir-Nimheas" },
				{ LanguageId.gd, "Naomh Kitts and Neibheis" },
				{ LanguageId.gl, "Saint Kitts e Nevis" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ કિટ્સ અને નેવિસ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saint Kitts da Nevis" },
				{ LanguageId.haw, "Kāna Kiti me Newia" },
				{ LanguageId.he, "סנט קיטס ונוויס" },
				{ LanguageId.hi, "संत किट्ट्स और नेविस" },
				{ LanguageId.hr, "Sveti Kristofor i Nevis" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Saint Kitts és Nevis" },
				{ LanguageId.hy, "Սենթ Քիթս և Նևիս" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Kitts dan Nevis" },
				{ LanguageId.ig, "Saint Kitts na Nevis" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Saint Kitts og Nevis" },
				{ LanguageId.it, "Saint Kitts e Nevis" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントクリストファー・ネイビス" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Saint Kitts lan Nevis" },
				{ LanguageId.ka, "სენტ კიტსი და ნევისი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сент-Китс және Невис" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Saint Kitts និង Nevis" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಕಿಟ್ಸ್ ಮತ್ತು ನೆವಿಸ್" },
				{ LanguageId.ko, "세인트키츠네비스" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Китс жана Невис" },
				{ LanguageId.la, "Saint Kitts et Nevis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saint Kitts and Nevis" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Saint Kitts ແລະ Nevis" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sent Kitsas ir Nevis" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sentkitsa un Nevisa" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Saint Kitts sy Nevis" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Saint Kitts me Nevis" },
				{ LanguageId.mk, "Свети Китс и Невис" },
				{ LanguageId.ml, "സെൻ്റ് കിറ്റ്സ് ആൻഡ് നെവിസ്" },
				{ LanguageId.mn, "Сент Китс ба Невис" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट किट्स आणि नेव्हिस" },
				{ LanguageId.ms, "Saint Kitts dan Nevis" },
				{ LanguageId.mt, "Saint Kitts u Nevis" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Saint Kitts နှင့် Nevis" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saint Kitts og Nevis" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट किट्स र नेभिस" },
				{ LanguageId.nl, "Saint Kitts en Nevis" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଣ୍ଟ କିଟ୍ସ ଏବଂ ନେଭିସ୍ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਕਿਟਸ ਅਤੇ ਨੇਵਿਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Saint Kitts i Nevis" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سانت کیټز او نیویس" },
				{ LanguageId.pt, "São Cristóvão e Nevis" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Saint Kitts și Nevis" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сент-Китс и Невис" },
				{ LanguageId.rw, "Uwera Kitts na Nevis" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ ڪيٽس ۽ نيوس" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත කිට්ස් සහ නෙවිස්" },
				{ LanguageId.sk, "Svätý Krištof a Nevis" },
				{ LanguageId.sl, "Saint Kitts in Nevis" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sendi Kitsi ne Nevhisi" },
				{ LanguageId.so, "Saint Kitts iyo Nevis" },
				{ LanguageId.sq, "Shën Kitts dhe Nevis" },
				{ LanguageId.sr, "Сент Китс и Невис" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saint Kitts le Nevis" },
				{ LanguageId.su, "Saint Kitts jeung Névis" },
				{ LanguageId.sv, "Saint Kitts och Nevis" },
				{ LanguageId.sw, "Saint Kitts na Nevis" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "செயின்ட் கிட்ஸ் மற்றும் நெவிஸ்" },
				{ LanguageId.te, "సెయింట్ కిట్స్ మరియు నెవిస్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент Китс ва Невис" },
				{ LanguageId.th, "เซนต์คิตส์และเนวิส" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Kitts we Newis" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Saint Kitts ve Nevis" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент Китс һәм Невис" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Saint Kitts and Nevis" },
				{ LanguageId.uk, "Сент-Кітс і Невіс" },
				{ LanguageId.ur, "سینٹ کٹس اینڈ نیوس" },
				{ LanguageId.uz, "Sent-Kitts va Nevis" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Saint Kitts và Nevis" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Seyint Kitsi neNevis" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיינט קיטץ און נעוויס" },
				{ LanguageId.yo, "Saint Kitts ati Nefisi" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣基茨和尼维斯" },
				{ LanguageId.zu, "I-Saint Kitts ne-Nevis" },
			}
		);
	}
}
