// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class KP
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "850",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Nordkorea" },
				{ LanguageId.af, "Noord-Korea" },
				{ LanguageId.agq, "Kùulîa, Ekùw" },
				{ LanguageId.ak, "Korea Atifi" },
				{ LanguageId.am, "ሰሜን ኮሪያ" },
				{ LanguageId.ar, "كوريا الشمالية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "উত্তৰ কোৰিয়া" },
				{ LanguageId.asa, "Korea Kathkazini" },
				{ LanguageId.ast, "Corea del Norte" },
				{ LanguageId.az, "Şimali Koreya" },
				{ LanguageId.ba, "Төньяҡ Корея" },
				{ LanguageId.bas, "Kɔ̀re ì Ŋ̀ɔmbɔk" },
				{ LanguageId.be, "Паўночная Карэя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hukolea Kaskazini" },
				{ LanguageId.bg, "Северна Корея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kɛɲɛka Kore" },
				{ LanguageId.bn, "উত্তর কোরিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Norzhkorea" },
				{ LanguageId.brx, "साहा करिया" },
				{ LanguageId.bs, "Sjeverna Koreja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Corea del Nord" },
				{ LanguageId.ccp, "𑄅𑄪𑄖𑄴𑄖𑄮𑄢𑄴 𑄇𑄮𑄢𑄨𑄠" },
				{ LanguageId.ce, "Къилбаседа Корей" },
				{ LanguageId.ceb, "North Korea" },
				{ LanguageId.cgg, "Koreya Amatemba" },
				{ LanguageId.chr, "ᏧᏴᏢ ᎪᎵᎠ" },
				{ LanguageId.ckb, "کۆریای باکوور" },
				{ LanguageId.co, "Republica Populari Democràtica di Corea" },
				{ LanguageId.cs, "Severní Korea" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gogledd Corea" },
				{ LanguageId.dav, "Korea Kaskazini" },
				{ LanguageId.de, "Nordkorea" },
				{ LanguageId.dje, "Gurma Kooree" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódpołnocna Koreja" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "བྱང་ ཀོ་རི་ཡ" },
				{ LanguageId.ebu, "Korea Kaskazini" },
				{ LanguageId.ee, "Dziehe Korea nutome" },
				{ LanguageId.el, "Βόρεια Κορέα" },
				{ LanguageId.en, "North Korea" },
				{ LanguageId.eo, "Nord-Koreujo" },
				{ LanguageId.es, "Corea del Norte" },
				{ LanguageId.et, "Põhja-Korea" },
				{ LanguageId.eu, "Ipar Korea" },
				{ LanguageId.ewo, "Koré yá Nór" },
				{ LanguageId.fa, "کرهٔ شمالی" },
				{ LanguageId.ff, "Koree Rewo" },
				{ LanguageId.fi, "Pohjois-Korea" },
				{ LanguageId.fil, "Hilagang Korea" },
				{ LanguageId.fo, "Norðurkorea" },
				{ LanguageId.fr, "Corée du Nord" },
				{ LanguageId.fur, "Coree dal nord" },
				{ LanguageId.fy, "Noard-Korea" },
				{ LanguageId.ga, "an Chóiré Thuaidh" },
				{ LanguageId.gd, "Coirèa a Tuath" },
				{ LanguageId.gl, "Corea do Norte" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Demokraatischi Volksrepublik Koreea" },
				{ LanguageId.gu, "ઉત્તર કોરિયા" },
				{ LanguageId.guz, "Korea Kaskazini" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Koriya Ta Arewa" },
				{ LanguageId.haw, "Lepupalika Makaainana Demokarata o Korea" },
				{ LanguageId.he, "קוריאה הצפונית" },
				{ LanguageId.hi, "उत्तर कोरिया" },
				{ LanguageId.hr, "Sjeverna Koreja" },
				{ LanguageId.hsb, "Sewjerna Koreja" },
				{ LanguageId.hu, "Észak-Korea" },
				{ LanguageId.hy, "Հյուսիսային Կորեա" },
				{ LanguageId.ia, "Corea del Nord" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Korea Utara" },
				{ LanguageId.ig, "North Korea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Norður-Kórea" },
				{ LanguageId.it, "Corea del Nord" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "北朝鮮" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Korea Kaskazini" },
				{ LanguageId.jv, "Korea Lor" },
				{ LanguageId.ka, "ჩრდილოეთ კორეა" },
				{ LanguageId.kab, "Kurya, Ufella" },
				{ LanguageId.kam, "Korea Kaskazini" },
				{ LanguageId.kde, "Kolea Kasikazini" },
				{ LanguageId.kea, "Koreia di Norti" },
				{ LanguageId.khq, "Kooree, Gurma" },
				{ LanguageId.ki, "Korea Kaskazini" },
				{ LanguageId.kk, "Солтүстік Корея" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Korea nebo murot katam" },
				{ LanguageId.km, "កូរ៉េ​ខាង​ជើង" },
				{ LanguageId.kn, "ಉತ್ತರ ಕೊರಿಯಾ" },
				{ LanguageId.ko, "북한" },
				{ LanguageId.kok, "उत्तर कोरिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "شُمٲلی کورِیا" },
				{ LanguageId.ksb, "Kolea Kaskazini" },
				{ LanguageId.ksf, "korɛanɔ́r" },
				{ LanguageId.ksh, "Nood-Koreja" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түндүк Корея" },
				{ LanguageId.la, "Popularis Populi Reipublicae Coreae" },
				{ LanguageId.lag, "Koréa yʉ ʉtʉrʉko" },
				{ LanguageId.lb, "Nordkorea" },
				{ LanguageId.lg, "Koreya ey’omumambuka" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Korɛ ya nɔ́rdi" },
				{ LanguageId.lo, "ເກົາຫລີເໜືອ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šiaurės Korėja" },
				{ LanguageId.luo, "Korea Masawa" },
				{ LanguageId.luy, "Korea Kaskazini" },
				{ LanguageId.lv, "Ziemeļkoreja" },
				{ LanguageId.mai, "उत्तर कोरिया" },
				{ LanguageId.mas, "Korea Kaskazini" },
				{ LanguageId.mer, "Korea Nothi" },
				{ LanguageId.mfe, "Lakore-dinor" },
				{ LanguageId.mg, "Korea Avaratra" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Kōrea ki te Raki" },
				{ LanguageId.mk, "Северна Кореја" },
				{ LanguageId.ml, "ഉത്തരകൊറിയ" },
				{ LanguageId.mn, "Хойд Солонгос" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "उत्तर कोरिया" },
				{ LanguageId.ms, "Korea Utara" },
				{ LanguageId.mt, "il-Korea ta’ Fuq" },
				{ LanguageId.mua, "Sǝr Kore fah sǝŋ" },
				{ LanguageId.my, "မြောက်ကိုရီးယား" },
				{ LanguageId.mzn, "شمالی کُره" },
				{ LanguageId.naq, "Koreab, Noord" },
				{ LanguageId.nb, "Nord-Korea" },
				{ LanguageId.nd, "North Korea" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "उत्तर कोरिया" },
				{ LanguageId.nl, "Noord-Korea" },
				{ LanguageId.nmg, "Koré yí bvuɔ" },
				{ LanguageId.nn, "Nord-Korea" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߐ߬ߘߎ߮ ߞߏ߯ߙߋ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Koreya Amatemba" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Kooriyaa Kaaba" },
				{ LanguageId.or, "ଉତ୍ତର କୋରିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਉੱਤਰੀ ਕੋਰੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Nọ́t Koria" },
				{ LanguageId.pl, "Korea Północna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "شمالی کوریا" },
				{ LanguageId.pt, "Coreia do Norte" },
				{ LanguageId.qu, "Corea del Norte" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Corea dal Nord" },
				{ LanguageId.rn, "Koreya y’amajaruguru" },
				{ LanguageId.ro, "Coreea de Nord" },
				{ LanguageId.rof, "Korea Kaskazini" },
				{ LanguageId.ru, "КНДР" },
				{ LanguageId.rw, "Repubulika Iharanira Demokarasi ya Koreya" },
				{ LanguageId.rwk, "Korea Kaskazini" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Korea Kaskazini" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Koleya ya luvala lwa Kunyamande" },
				{ LanguageId.sd, "اتر ڪوريا" },
				{ LanguageId.se, "Davvi-Korea" },
				{ LanguageId.seh, "Coréia do Norte" },
				{ LanguageId.ses, "Kooree, Gurma" },
				{ LanguageId.sg, "Korëe tî Banga" },
				{ LanguageId.shi, "ⴽⵓⵔⵢⴰ ⵏ ⵉⵥⵥⵍⵎⴹ" },
				{ LanguageId.si, "උතුරු කොරියාව" },
				{ LanguageId.sk, "Severná Kórea" },
				{ LanguageId.sl, "Severna Koreja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Tave-Korea" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Korea, North" },
				{ LanguageId.so, "Kuuriyada Waqooyi" },
				{ LanguageId.sq, "Kore e Veriut" },
				{ LanguageId.sr, "Северна Кореја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Democratic People's Republic of Korea" },
				{ LanguageId.su, "Républik Rahayat Démokratik Koréa" },
				{ LanguageId.sv, "Nordkorea" },
				{ LanguageId.sw, "Korea Kaskazini" },
				{ LanguageId.syr, "ܟܘܪܝܐ ܓܪܒܝܝܬܐ" },
				{ LanguageId.ta, "வட கொரியா" },
				{ LanguageId.te, "ఉత్తర కొరియా" },
				{ LanguageId.teo, "Korea Kaskazini" },
				{ LanguageId.tg, "Кореяи Шимолӣ" },
				{ LanguageId.th, "เกาหลีเหนือ" },
				{ LanguageId.ti, "ሰሜን ኮርያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Demirgazyk Koreýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Kōlea tokelau" },
				{ LanguageId.tr, "Kuzey Kore" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Төньяк Корея" },
				{ LanguageId.twq, "Kooree, Gurma" },
				{ LanguageId.tzm, "Kurya Tugafat" },
				{ LanguageId.ug, "چاۋشيەن" },
				{ LanguageId.uk, "Північна Корея" },
				{ LanguageId.ur, "شمالی کوریا" },
				{ LanguageId.uz, "Shimoliy Koreya" },
				{ LanguageId.vai, "ꖏꔸꕩ ꗛꔤ ꕪꘋꗒ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Triều Tiên" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Korea Kaskazini" },
				{ LanguageId.wae, "Nordkorea" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Kore Noor" },
				{ LanguageId.xh, "EMntla Korea" },
				{ LanguageId.xog, "Koreya eya mumambuka" },
				{ LanguageId.yav, "kɔlé u muɛnɛ́" },
				{ LanguageId.yi, "דעמאָקראַטיש מענטשן ס רעפובליק פון קארעע" },
				{ LanguageId.yo, "Guusu Kọria" },
				{ LanguageId.zgh, "ⴽⵓⵔⵢⴰ ⵏ ⵉⵥⵥⵍⵎⴹ" },
				{ LanguageId.zh, "朝鲜" },
				{ LanguageId.zu, "i-North Korea" },
			}
		);
	}
}
