using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class KP
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "850",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Den Demokratiske Folkerepublik Korea" },
				{ LanguageId.af, "Demokratiese Volksrepubliek van Korea" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የኮሪያ ዲሞክራሲያዊ ህዝቦች ሪፐብሊክ" },
				{ LanguageId.ar, "جمهورية كوريا الديمقراطية االشعبية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Koreya Xalq Demokratik Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Карэйская Народна-Дэмакратычная Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Корейска народнодемократична република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "গণতান্ত্রিক গণপ্রজাতন্ত্রী কোরিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Demokratska Narodna Republika Koreja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Popular Democràtica de Corea" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Republikang Demokratiko sa Katawhan sa Korea" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Republica Populari Democràtica di Corea" },
				{ LanguageId.cs, "Korejská lidově demokratická republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Ddemocrataidd Pobl Corea" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Demokratische Volksrepublik Korea" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Λαϊκή Δημοκρατία της Κορέας" },
				{ LanguageId.en, "Democratic People's Republic of Korea" },
				{ LanguageId.eo, "Korea Popola Demokratia Respubliko" },
				{ LanguageId.es, "República Popular Democrática de Corea" },
				{ LanguageId.et, "Korea Rahvademokraatlik Vabariik" },
				{ LanguageId.eu, "Koreako Herri Errepublika Demokratikoa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری دموکراتیک خلق کره" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Korean demokraattinen kansantasavalta" },
				{ LanguageId.fil, "Demokratikong Republika ng Korea" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République Populaire Démocratique de Corée" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Demokratyske Folksrepublyk Korea" },
				{ LanguageId.ga, "Daon-Phoblacht Dhaonlathach na Cóiré" },
				{ LanguageId.gd, "Poblachd Sluagh Dheamocratach Korea" },
				{ LanguageId.gl, "República Popular Democrática de Corea" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ડેમોક્રેટિક પીપલ્સ રિપબ્લિક ઓફ કોરિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Dimokaradiyyar Koriya" },
				{ LanguageId.haw, "Lepupalika Makaainana Demokarata o Korea" },
				{ LanguageId.he, "הרפובליקה הדמוקרטית של קוריאה" },
				{ LanguageId.hi, "कोरिया डेमोक्रेटिक पीपुल्स रिपब्लिक" },
				{ LanguageId.hr, "Demokratska Narodna Republika Koreja" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Koreai Népi Demokratikus Köztársaság" },
				{ LanguageId.hy, "Կորեայի Ժողովրդադեմոկրատական ​​Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Demokratik Rakyat Korea" },
				{ LanguageId.ig, "Democratic People's Republic of Korea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Alþýðulýðveldið Kóreu" },
				{ LanguageId.it, "Repubblica Democratica Popolare di Corea" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "朝鮮民主主義人民共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Rakyat Demokratik Korea" },
				{ LanguageId.ka, "კორეის სახალხო დემოკრატიული რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Корея Халық Демократиялық Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋប្រជាធិបតេយ្យប្រជាមានិតកូរ៉េ" },
				{ LanguageId.kn, "ಡೆಮಾಕ್ರಟಿಕ್ ಪೀಪಲ್ಸ್ ರಿಪಬ್ಲಿಕ್ ಆಫ್ ಕೊರಿಯಾ" },
				{ LanguageId.ko, "조선 민주주의 인민 공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кореянын Элдик Демократиялык Республикасы" },
				{ LanguageId.la, "Popularis Populi Reipublicae Coreae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Demokratesch Volleksrepublik Korea" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາທາລະນະ​ລັດ ປະຊາທິປະ​ໄຕ ​ເກົາຫຼີ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Korėjos Liaudies Demokratinė Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Korejas Tautas Demokrātiskā Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Demokratikan'i Korea" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Manapori Tangata Republic of Korea" },
				{ LanguageId.mk, "Демократска Народна Република Кореја" },
				{ LanguageId.ml, "ഡെമോക്രാറ്റിക് പീപ്പിൾസ് റിപ്പബ്ലിക് ഓഫ് കൊറിയ" },
				{ LanguageId.mn, "Бүгд Найрамдах Ардчилсан Солонгос Ард Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "डेमोक्रॅटिक पीपल्स रिपब्लिक ऑफ कोरिया" },
				{ LanguageId.ms, "Republik Demokratik Rakyat Korea" },
				{ LanguageId.mt, "Repubblika Demokratika Popolari tal-Korea" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကိုရီးယား ဒီမိုကရက်တစ် ပြည်သူ့သမ္မတနိုင်ငံ၊" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Den demokratiske folkerepublikken Korea" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोरियाको लोकतान्त्रिक जनवादी गणतन्त्र" },
				{ LanguageId.nl, "Democratische Volksrepubliek Korea" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଡେମୋକ୍ରାଟିକ୍ ପିପୁଲ୍ସ ରିପବ୍ଲିକ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਡੈਮੋਕਰੇਟਿਕ ਪੀਪਲਜ਼ ਰੀਪਬਲਿਕ ਆਫ ਕੋਰੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Koreańska Republika Ludowo-Demokratyczna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د کوریا د خلکو دیموکراتیک جمهوریت" },
				{ LanguageId.pt, "República Popular Democrática da Coreia" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Populară Democrată Coreea" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Корейская Народно-Демократическая Республика" },
				{ LanguageId.rw, "Repubulika Iharanira Demokarasi ya Koreya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪوريا جي جمهوري عوامي جمهوريه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කොරියානු ප්‍රජාතන්ත්‍රවාදී මහජන ජනරජය" },
				{ LanguageId.sk, "Kórejská ľudovodemokratická republika" },
				{ LanguageId.sl, "Demokratična ljudska republika Koreja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Democratic People's Republic of Korea" },
				{ LanguageId.so, "Jamhuuriyadda Dimuqraadiga ah ee Kuuriya" },
				{ LanguageId.sq, "Republika Popullore Demokratike e Koresë" },
				{ LanguageId.sr, "Демократска Народна Република Кореја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Democratic People's Republic of Korea" },
				{ LanguageId.su, "Républik Rahayat Démokratik Koréa" },
				{ LanguageId.sv, "Demokratiska folkrepubliken Korea" },
				{ LanguageId.sw, "Jamhuri ya Kidemokrasia ya Watu wa Korea" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கொரியா ஜனநாயக மக்கள் குடியரசு" },
				{ LanguageId.te, "డెమొక్రాటిక్ పీపుల్స్ రిపబ్లిక్ ఆఫ్ కొరియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Республикаи Халкии Демократии Корея" },
				{ LanguageId.th, "สาธารณรัฐประชาธิปไตยประชาชนเกาหลี" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Koreýa Demokratik Halk Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Kore Demokratik Halk Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Корея Демократик Халык Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "كورېيە دېموكراتىك خەلق جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Корейська Народно-Демократична Республіка" },
				{ LanguageId.ur, "جمہوری عوامی جمہوریہ کوریا" },
				{ LanguageId.uz, "Koreya Xalq Demokratik Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Dân chủ Nhân dân Triều Tiên" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IRiphabhlikhi yabantu baseDemokhrasi yaseKorea" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "דעמאָקראַטיש מענטשן ס רעפובליק פון קארעע" },
				{ LanguageId.yo, "Democratic People ká Republic of Korea" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "朝鲜民主主义人民共和国" },
				{ LanguageId.zu, "I-Democratic People's Republic of Korea" },
			}
		);
	}
}
