// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class KR
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "82",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sydkorea" },
				{ LanguageId.af, "Suid-Korea" },
				{ LanguageId.agq, "Kùulîa, Emàm" },
				{ LanguageId.ak, "Korea Anaafoɔ" },
				{ LanguageId.am, "ደቡብ ኮሪያ" },
				{ LanguageId.ar, "كوريا الجنوبية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "দক্ষিণ কোৰিয়া" },
				{ LanguageId.asa, "Korea Kuthini" },
				{ LanguageId.ast, "Corea del Sur" },
				{ LanguageId.az, "Cənubi Koreya" },
				{ LanguageId.ba, "Көньяҡ Корея" },
				{ LanguageId.bas, "Kɔ̀re ì Ŋ̀wɛ̀lmbɔk" },
				{ LanguageId.be, "Паўднёвая Карэя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hukolea Kusini" },
				{ LanguageId.bg, "Южна Корея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Worodugu Kore" },
				{ LanguageId.bn, "দক্ষিণ কোরিয়া" },
				{ LanguageId.bo, "ལྷོ་ཀོ་རི་ཡ།" },
				{ LanguageId.br, "Sukorea" },
				{ LanguageId.brx, "खोला करिया" },
				{ LanguageId.bs, "Južna Koreja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Corea del Sud" },
				{ LanguageId.ccp, "𑄘𑄧𑄉𑄨𑄚𑄴 𑄇𑄮𑄢𑄨𑄠" },
				{ LanguageId.ce, "Къилба Корей" },
				{ LanguageId.ceb, "South Korea" },
				{ LanguageId.cgg, "Koreya Amashuuma" },
				{ LanguageId.chr, "ᏧᎦᏃᏮ ᎪᎵᎠ" },
				{ LanguageId.ckb, "کۆریای باشوور" },
				{ LanguageId.co, "Republica di Corea" },
				{ LanguageId.cs, "Jižní Korea" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "De Corea" },
				{ LanguageId.dav, "Korea Kusini" },
				{ LanguageId.de, "Südkorea" },
				{ LanguageId.dje, "Hawsa Kooree" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódpołdnjowa Koreja" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ལྷོ་ ཀོ་རི་ཡ" },
				{ LanguageId.ebu, "Korea Kusini" },
				{ LanguageId.ee, "Anyiehe Korea nutome" },
				{ LanguageId.el, "Νότια Κορέα" },
				{ LanguageId.en, "South Korea" },
				{ LanguageId.eo, "Sud-Koreujo" },
				{ LanguageId.es, "Corea del Sur" },
				{ LanguageId.et, "Lõuna-Korea" },
				{ LanguageId.eu, "Hego Korea" },
				{ LanguageId.ewo, "Koré yá Súd" },
				{ LanguageId.fa, "کرهٔ جنوبی" },
				{ LanguageId.ff, "Koree Worgo" },
				{ LanguageId.fi, "Etelä-Korea" },
				{ LanguageId.fil, "Timog Korea" },
				{ LanguageId.fo, "Suðurkorea" },
				{ LanguageId.fr, "Corée du Sud" },
				{ LanguageId.fur, "Coree dal sud" },
				{ LanguageId.fy, "Sûd-Korea" },
				{ LanguageId.ga, "an Chóiré Theas" },
				{ LanguageId.gd, "Coirèa" },
				{ LanguageId.gl, "Corea do Sur" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Republik Koreea" },
				{ LanguageId.gu, "દક્ષિણ કોરિયા" },
				{ LanguageId.guz, "Korea Kusini" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Koriya Ta Kudu" },
				{ LanguageId.haw, "Repubalika o Korea" },
				{ LanguageId.he, "קוריאה הדרומית" },
				{ LanguageId.hi, "दक्षिण कोरिया" },
				{ LanguageId.hr, "Južna Koreja" },
				{ LanguageId.hsb, "Južna Koreja" },
				{ LanguageId.hu, "Dél-Korea" },
				{ LanguageId.hy, "Հարավային Կորեա" },
				{ LanguageId.ia, "Corea del Sud" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Korea Selatan" },
				{ LanguageId.ig, "South Korea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Suður-Kórea" },
				{ LanguageId.it, "Corea del Sud" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "韓国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Korea Kusini" },
				{ LanguageId.jv, "Koréa Kidul" },
				{ LanguageId.ka, "სამხრეთ კორეა" },
				{ LanguageId.kab, "Kurya, Wadda" },
				{ LanguageId.kam, "Korea Kusini" },
				{ LanguageId.kde, "Kolea Kusini" },
				{ LanguageId.kea, "Koreia di Sul" },
				{ LanguageId.khq, "Kooree, Hawsa" },
				{ LanguageId.ki, "Korea Kusini" },
				{ LanguageId.kk, "Оңтүстік Корея" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab korea nebo murot tai" },
				{ LanguageId.km, "កូរ៉េ​ខាង​ត្បូង" },
				{ LanguageId.kn, "ದಕ್ಷಿಣ ಕೊರಿಯಾ" },
				{ LanguageId.ko, "대한민국" },
				{ LanguageId.kok, "दक्षिण कोरिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "جنوٗبی کورِیا" },
				{ LanguageId.ksb, "Kolea Kusini" },
				{ LanguageId.ksf, "korɛasud" },
				{ LanguageId.ksh, "Söd-Koreja" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түштүк Корея" },
				{ LanguageId.la, "Respublica Coreae" },
				{ LanguageId.lag, "Koréa ya Saame" },
				{ LanguageId.lb, "Südkorea" },
				{ LanguageId.lg, "Koreya ey’omumaserengeta" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Korɛ ya súdi" },
				{ LanguageId.lo, "ເກົາຫລີໃຕ້" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Pietų Korėja" },
				{ LanguageId.luo, "Korea Milambo" },
				{ LanguageId.luy, "Korea Kusini" },
				{ LanguageId.lv, "Dienvidkoreja" },
				{ LanguageId.mai, "दक्षिण कोरिया" },
				{ LanguageId.mas, "Korea Kusini" },
				{ LanguageId.mer, "Korea Saũthi" },
				{ LanguageId.mfe, "Lakore-disid" },
				{ LanguageId.mg, "Korea Atsimo" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Kōrea ki te Tonga" },
				{ LanguageId.mk, "Јужна Кореја" },
				{ LanguageId.ml, "ദക്ഷിണകൊറിയ" },
				{ LanguageId.mn, "Өмнөд Солонгос" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "दक्षिण कोरिया" },
				{ LanguageId.ms, "Korea Selatan" },
				{ LanguageId.mt, "il-Korea t’Isfel" },
				{ LanguageId.mua, "Sǝr Kore nekǝsǝŋ" },
				{ LanguageId.my, "တောင်ကိုရီးယား" },
				{ LanguageId.mzn, "جنوبی کُره" },
				{ LanguageId.naq, "Koreab, Suid" },
				{ LanguageId.nb, "Sør-Korea" },
				{ LanguageId.nd, "South Korea" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "दक्षिण कोरिया" },
				{ LanguageId.nl, "Zuid-Korea" },
				{ LanguageId.nmg, "Koré yí sí" },
				{ LanguageId.nn, "Sør-Korea" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߕߟߋ߬ߓߋ ߞߏ߯ߙߋ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Koreya Amashuuma" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Kooriyaa Kibbaa" },
				{ LanguageId.or, "ଦକ୍ଷିଣ କୋରିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਦੱਖਣੀ ਕੋਰੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Saút Koria" },
				{ LanguageId.pl, "Korea Południowa" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سویلي کوریا" },
				{ LanguageId.pt, "Coreia do Sul" },
				{ LanguageId.qu, "Corea del Sur" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Corea dal Sid" },
				{ LanguageId.rn, "Koreya y’amajepfo" },
				{ LanguageId.ro, "Coreea de Sud" },
				{ LanguageId.rof, "Korea Kusini" },
				{ LanguageId.ru, "Республика Корея" },
				{ LanguageId.rw, "Repubulika ya Koreya" },
				{ LanguageId.rwk, "Korea Kusini" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Korea Kusini" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Koleya ya Kusini" },
				{ LanguageId.sd, "ڏکڻ ڪوريا" },
				{ LanguageId.se, "Mátta-Korea" },
				{ LanguageId.seh, "Coréia do Sul" },
				{ LanguageId.ses, "Kooree, Hawsa" },
				{ LanguageId.sg, "Korëe tî Mbongo" },
				{ LanguageId.shi, "ⴽⵓⵔⵢⴰ ⵏ ⵉⴼⴼⵓⵙ" },
				{ LanguageId.si, "දකුණු කොරියාව" },
				{ LanguageId.sk, "Južná Kórea" },
				{ LanguageId.sl, "Južna Koreja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Maadâ-Korea" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Korea, South" },
				{ LanguageId.so, "Kuuriyada Koonfureed" },
				{ LanguageId.sq, "Kore e Jugut" },
				{ LanguageId.sr, "Јужна Кореја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Rephabliki ea Korea" },
				{ LanguageId.su, "Républik Koréa" },
				{ LanguageId.sv, "Sydkorea" },
				{ LanguageId.sw, "Korea Kusini" },
				{ LanguageId.syr, "ܟܘܪܝܐ ܬܝܡܢܝܬܐ" },
				{ LanguageId.ta, "தென் கொரியா" },
				{ LanguageId.te, "దక్షిణ కొరియా" },
				{ LanguageId.teo, "Korea Kusini" },
				{ LanguageId.tg, "Кореяи Ҷанубӣ" },
				{ LanguageId.th, "เกาหลีใต้" },
				{ LanguageId.ti, "ደቡብ ኮርያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günorta Koreýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Kōlea tonga" },
				{ LanguageId.tr, "Güney Kore" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көньяк Корея" },
				{ LanguageId.twq, "Kooree, Hawsa" },
				{ LanguageId.tzm, "Kurya Tunẓult" },
				{ LanguageId.ug, "كورېيە" },
				{ LanguageId.uk, "Південна Корея" },
				{ LanguageId.ur, "جنوبی کوریا" },
				{ LanguageId.uz, "Janubiy Koreya" },
				{ LanguageId.vai, "ꖏꔸꕩ ꗛꔤ ꔒꘋꗣ ꗏ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hàn Quốc" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Korea Kusini" },
				{ LanguageId.wae, "Südkorea" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Corée du Sud" },
				{ LanguageId.xh, "EMzantsi Korea" },
				{ LanguageId.xog, "Koreya eya mumaserengeta" },
				{ LanguageId.yav, "kɔlé wu mbát" },
				{ LanguageId.yi, "רעפובליק פון קארעע" },
				{ LanguageId.yo, "Ariwa Kọria" },
				{ LanguageId.zgh, "ⴽⵓⵔⵢⴰ ⵏ ⵉⴼⴼⵓⵙ" },
				{ LanguageId.zh, "韩国" },
				{ LanguageId.zu, "i-South Korea" },
			}
		);
	}
}
