using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class KR
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "82",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Republikken Korea" },
				{ LanguageId.af, "Republiek van Korea" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የኮሪያ ሪፐብሊክ" },
				{ LanguageId.ar, "جمهورية كوريا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Koreya Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Рэспубліка Карэя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Република Корея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "দক্ষিণ কোরিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Korea ar Su" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "republika Koreja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República de Corea" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Republika sa Korea" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Republica di Corea" },
				{ LanguageId.cs, "Korejská republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Corea" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Republik Korea" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Δημοκρατία της Κορέας" },
				{ LanguageId.en, "Republic of Korea" },
				{ LanguageId.eo, "Korea Respubliko" },
				{ LanguageId.es, "República de Corea" },
				{ LanguageId.et, "Korea Vabariik" },
				{ LanguageId.eu, "Koreako Errepublika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری کره" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Korean tasavalta" },
				{ LanguageId.fil, "Republika ng Korea" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République de Corée" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Republyk Korea" },
				{ LanguageId.ga, "Poblacht na Cóiré" },
				{ LanguageId.gd, "Poblachd Chorea" },
				{ LanguageId.gl, "República de Corea" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "કોરિયા પ્રજાસત્તાક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Koriya" },
				{ LanguageId.haw, "Repubalika o Korea" },
				{ LanguageId.he, "הרפובליקה של קוריאה" },
				{ LanguageId.hi, "कोरियान गणतन्त्र" },
				{ LanguageId.hr, "Republika Koreja" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Koreai Köztársaság" },
				{ LanguageId.hy, "Կորեայի Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Korea" },
				{ LanguageId.ig, "Republic of Korea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Lýðveldið Kórea" },
				{ LanguageId.it, "Repubblica di Corea" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "大韓民国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Korea" },
				{ LanguageId.ka, "კორეის რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Корея Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណៈ​រដ្ឋ​កូរ៉េ" },
				{ LanguageId.kn, "ರಿಪಬ್ಲಿಕ್ ಆಫ್ ಕೊರಿಯಾ" },
				{ LanguageId.ko, "대한민국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Корея Республикасы" },
				{ LanguageId.la, "Respublica Coreae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Republik Korea" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "​ເກົາຫຼີ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Korėjos Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Korejas republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblikan'i Korea" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Republic of Korea" },
				{ LanguageId.mk, "Република Кореа" },
				{ LanguageId.ml, "റിപ്പബ്ലിക് ഓഫ് കൊറിയ" },
				{ LanguageId.mn, "Бүгд Найрамдах Солонгос Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "कोरिया प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Korea" },
				{ LanguageId.mt, "Repubblika tal-Korea" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကိုရီးယားသမ္မတနိုင်ငံ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Republikken, Korea" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "कोरिया गणतन्त्र" },
				{ LanguageId.nl, "Republiek Korea" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କୋରିଆ ଗଣତନ୍ତ୍ର" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੋਰੀਆ ਗਣਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Republika Korei" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د کوریا جمهوریت" },
				{ LanguageId.pt, "República da Coreia" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Coreea" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Республика Корея" },
				{ LanguageId.rw, "Repubulika ya Koreya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪوريا جي جمهوريه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කොරියානු ජනරජය" },
				{ LanguageId.sk, "Kórejská republika" },
				{ LanguageId.sl, "Republika Koreja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Republic of Korea" },
				{ LanguageId.so, "Jamhuuriyadda Kuuriya" },
				{ LanguageId.sq, "Republika e Koresë" },
				{ LanguageId.sr, "Република Кореја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Rephabliki ea Korea" },
				{ LanguageId.su, "Républik Koréa" },
				{ LanguageId.sv, "Republiken Korea" },
				{ LanguageId.sw, "Jamhuri ya Korea" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கொரிய குடியரசு" },
				{ LanguageId.te, "రిపబ్లిక్ ఆఫ్ కొరియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷумҳурии Корея" },
				{ LanguageId.th, "สาธารณรัฐเกาหลี" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Koreýa Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Kore Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Корея Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "كورېيە جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Республіка Корея" },
				{ LanguageId.ur, "جمہوریہ کوریا" },
				{ LanguageId.uz, "Koreya Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hàn Quốc" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IRiphabhlikhi yaseKorea" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "רעפובליק פון קארעע" },
				{ LanguageId.yo, "Orile-ede Koria" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "大韩民国" },
				{ LanguageId.zu, "IRiphabhulikhi yaseKorea" },
			}
		);
	}
}
