using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class KY
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Caymanøerne" },
				{ LanguageId.af, "Cayman Eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኬይማን አይስላንድ" },
				{ LanguageId.ar, "جزر كايمان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Kayman adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Кайманавы астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Кайманови острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "কেম্যান দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Kajmanska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Caiman" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "isla sa Cayman" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Caiman" },
				{ LanguageId.cs, "Kajmanské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd y Cayman" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Cayman Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησιά Κέιμαν" },
				{ LanguageId.en, "Cayman Islands" },
				{ LanguageId.eo, "Kajmanaj Insuloj" },
				{ LanguageId.es, "Islas Caimán" },
				{ LanguageId.et, "Kaimani saared" },
				{ LanguageId.eu, "Kaiman Uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر کیمن" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Caymansaaret" },
				{ LanguageId.fil, "Mga Isla ng Cayman" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Îles Caïmans" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Kaaimaneilannen" },
				{ LanguageId.ga, "Oileáin Cayman" },
				{ LanguageId.gd, "Na h-Eileanan Cayman" },
				{ LanguageId.gl, "Illas Caimán" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "કેમેન ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Cayman" },
				{ LanguageId.haw, "Nā ʻAilana o Keimana" },
				{ LanguageId.he, "איי קיימן" },
				{ LanguageId.hi, "केमन द्वीपसमूह" },
				{ LanguageId.hr, "Kajmanski otoci" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Kajmán-szigetek" },
				{ LanguageId.hy, "Կայման կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Pulau cayman" },
				{ LanguageId.ig, "Cayman Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Caymaneyjar" },
				{ LanguageId.it, "Isole Cayman" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ケイマン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Cayman" },
				{ LanguageId.ka, "კაიმანის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Кайман аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះកៃម៉ាន" },
				{ LanguageId.kn, "ಕೇಮನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "케이맨 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кайман аралдары" },
				{ LanguageId.la, "Insulae Cayman" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Cayman Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະເຄແມນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kaimanų salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Kaimanu salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Cayman" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Nga Moutere o Cayman" },
				{ LanguageId.mk, "Кајмански Острови" },
				{ LanguageId.ml, "കേമാൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Кайманы арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "केमन बेटे" },
				{ LanguageId.ms, "Pulau Cayman" },
				{ LanguageId.mt, "Gżejjer Kajman" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ကေမန်ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Caymanøyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "केम्यान टापुहरू" },
				{ LanguageId.nl, "Kaaiman Eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "କେମାନ୍ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੇਮੈਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Kajmany" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کیمان ټاپوګان" },
				{ LanguageId.pt, "Ilhas Cayman" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Cayman" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Каймановы острова" },
				{ LanguageId.rw, "Ibirwa bya Cayman" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڪيمن آئيلينڊ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "කේමන් දූපත්" },
				{ LanguageId.sk, "Kajmanské ostrovy" },
				{ LanguageId.sl, "Kajmanski otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa Keyimeni" },
				{ LanguageId.so, "Jasiiradaha Cayman" },
				{ LanguageId.sq, "Ishujt Kajman" },
				{ LanguageId.sr, "Кајманска острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Cayman" },
				{ LanguageId.su, "Kapuloan Cayman" },
				{ LanguageId.sv, "Caymanöarna" },
				{ LanguageId.sw, "Visiwa vya Cayman" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கெய்மன் தீவுகள்" },
				{ LanguageId.te, "కేమాన్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Кайман" },
				{ LanguageId.th, "หมู่เกาะเคย์เเมน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kaýman adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Cayman Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Кайман утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "كايمان ئارىلى" },
				{ LanguageId.uk, "Кайманові острови" },
				{ LanguageId.ur, "جزائر کیمن" },
				{ LanguageId.uz, "Kayman orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Cayman" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Isiqithi saseKheyman" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "קיימאַן אינזלען" },
				{ LanguageId.yo, "Awọn erekusu Cayman" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "开曼群岛" },
				{ LanguageId.zu, "Iziqhingi zaseCayman" },
			}
		);
	}
}
