// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class KY
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Caymanøerne" },
				{ LanguageId.af, "Kaaimanseilande" },
				{ LanguageId.agq, "Chwɨlà ŋ̀ Kaemàn" },
				{ LanguageId.ak, "Kemanfo Islands" },
				{ LanguageId.am, "ካይማን ደሴቶች" },
				{ LanguageId.ar, "جزر كايمان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "কেইমেন দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Kayman" },
				{ LanguageId.ast, "Islles Caimán" },
				{ LanguageId.az, "Kayman adaları" },
				{ LanguageId.ba, "Кайман утрауҙары" },
				{ LanguageId.bas, "Bìòn bi Kaymàn" },
				{ LanguageId.be, "Кайманавы астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Kayman" },
				{ LanguageId.bg, "Кайманови острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Bama Gun" },
				{ LanguageId.bn, "কেম্যান দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Cayman" },
				{ LanguageId.brx, "कैमेन द्वीपफोर" },
				{ LanguageId.bs, "Kajmanska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Caiman" },
				{ LanguageId.ccp, "𑄇𑄬𑄟𑄳𑄠𑄚𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Кайман гӀайренаш" },
				{ LanguageId.ceb, "Cayman Islands" },
				{ LanguageId.cgg, "Ebizinga bya Kayimani" },
				{ LanguageId.chr, "ᎨᎢᎹᏂ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی کایمان" },
				{ LanguageId.co, "Isule Caiman" },
				{ LanguageId.cs, "Kajmanské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Cayman" },
				{ LanguageId.dav, "Visiwa vya Kayman" },
				{ LanguageId.de, "Kaimaninseln" },
				{ LanguageId.dje, "Kayman gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Kajmaniske kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཁེ་མེན་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Visiwa vya Kayman" },
				{ LanguageId.ee, "Kayman ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Κέιμαν" },
				{ LanguageId.en, "Cayman Islands" },
				{ LanguageId.eo, "Kajmana Insularo" },
				{ LanguageId.es, "Islas Caimán" },
				{ LanguageId.et, "Kaimanisaared" },
				{ LanguageId.eu, "Kaiman uharteak" },
				{ LanguageId.ewo, "Minlán Mí Kalimáŋ" },
				{ LanguageId.fa, "جزایر کِیمن" },
				{ LanguageId.ff, "Duuɗe Kaymaa" },
				{ LanguageId.fi, "Caymansaaret" },
				{ LanguageId.fil, "Cayman Islands" },
				{ LanguageId.fo, "Caymanoyggjar" },
				{ LanguageId.fr, "Îles Caïmans" },
				{ LanguageId.fur, "Isulis Cayman" },
				{ LanguageId.fy, "Caymaneilannen" },
				{ LanguageId.ga, "Oileáin Cayman" },
				{ LanguageId.gd, "Na h-Eileanan Caimean" },
				{ LanguageId.gl, "Illas Caimán" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Käimän-Insle" },
				{ LanguageId.gu, "કેમેન આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Kayman" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Kaiman" },
				{ LanguageId.haw, "Nā ʻAilana o Keimana" },
				{ LanguageId.he, "איי קיימן" },
				{ LanguageId.hi, "कैमेन द्वीपसमूह" },
				{ LanguageId.hr, "Kajmanski Otoci" },
				{ LanguageId.hsb, "Kajmanske kupy" },
				{ LanguageId.hu, "Kajmán-szigetek" },
				{ LanguageId.hy, "Կայմանյան կղզիներ" },
				{ LanguageId.ia, "Insulas de Caiman" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Cayman" },
				{ LanguageId.ig, "Cayman Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Caymaneyjar" },
				{ LanguageId.it, "Isole Cayman" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ケイマン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Kayman" },
				{ LanguageId.jv, "Kapuloan Kéman" },
				{ LanguageId.ka, "კაიმანის კუნძულები" },
				{ LanguageId.kab, "Tigzirin n Kamyan" },
				{ LanguageId.kam, "Isiwa sya Kayman" },
				{ LanguageId.kde, "Chisiwa cha Kemen" },
				{ LanguageId.kea, "Ilhas Kaimon" },
				{ LanguageId.khq, "Kayman gungey" },
				{ LanguageId.ki, "Visiwa vya Kayman" },
				{ LanguageId.kk, "Кайман аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeyotab Cayman" },
				{ LanguageId.km, "កោះ​កៃម៉ង់" },
				{ LanguageId.kn, "ಕೇಮನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "케이맨 제도" },
				{ LanguageId.kok, "केमॅन जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "کیمَن جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Kayman" },
				{ LanguageId.ksf, "zǝ i gan" },
				{ LanguageId.ksh, "de Kaiman-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кайман аралдары" },
				{ LanguageId.la, "Insulae Cayman" },
				{ LanguageId.lag, "Visíiwa vya Kayimani" },
				{ LanguageId.lb, "Kaimaninselen" },
				{ LanguageId.lg, "Bizinga ebya Kayimaani" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Kayíma" },
				{ LanguageId.lo, "ໝູ່ເກາະ ເຄແມນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Kaimanų Salos" },
				{ LanguageId.luo, "Cayman Islands" },
				{ LanguageId.luy, "Visiwa vya Kayman" },
				{ LanguageId.lv, "Kaimanu salas" },
				{ LanguageId.mai, "कैमेन द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Kayman" },
				{ LanguageId.mer, "Aĩrandi cia Kayman" },
				{ LanguageId.mfe, "Zil Kayman" },
				{ LanguageId.mg, "Nosy Kayman" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Motu Keimana" },
				{ LanguageId.mk, "Кајмански Острови" },
				{ LanguageId.ml, "കേയ്മാൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Кайманы арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "केमन बेटे" },
				{ LanguageId.ms, "Kepulauan Cayman" },
				{ LanguageId.mt, "il-Gżejjer Cayman" },
				{ LanguageId.mua, "kayman ma laŋne" },
				{ LanguageId.my, "ကေမန် ကျွန်းစု" },
				{ LanguageId.mzn, "کیمن جزیره‌ئون" },
				{ LanguageId.naq, "Cayman Islands" },
				{ LanguageId.nb, "Caymanøyene" },
				{ LanguageId.nd, "Cayman Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "केयमान टापु" },
				{ LanguageId.nl, "Kaaimaneilanden" },
				{ LanguageId.nmg, "Maŋ́ má kumbi" },
				{ LanguageId.nn, "Caymanøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߓߊ߲߬ߓߊ߬-ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Kaymɛn ɣa̱ylɛn" },
				{ LanguageId.nyn, "Ebizinga bya Kayimani" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Saaymaan" },
				{ LanguageId.or, "କେମ୍ୟାନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਕੇਮੈਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Kéman Aílands" },
				{ LanguageId.pl, "Kajmany" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "کیمان ټاپوګان" },
				{ LanguageId.pt, "Ilhas Cayman" },
				{ LanguageId.qu, "Islas Caimán" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Cayman" },
				{ LanguageId.rn, "Ibirwa bya Keyimani" },
				{ LanguageId.ro, "Insulele Cayman" },
				{ LanguageId.rof, "Visiwa vya Kaimai" },
				{ LanguageId.ru, "о-ва Кайман" },
				{ LanguageId.rw, "Ibirwa bya Cayman" },
				{ LanguageId.rwk, "Visiwa vya Kayman" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Kayman" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli ifya Kayimayi" },
				{ LanguageId.sd, "ڪي مين ٻيٽ" },
				{ LanguageId.se, "Cayman-sullot" },
				{ LanguageId.seh, "Ilhas Caiman" },
				{ LanguageId.ses, "Kayman gungey" },
				{ LanguageId.sg, "Âzûâ Ngundë, Kaimäni" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⵢⵎⴰⵏ" },
				{ LanguageId.si, "කේමන් දූපත්" },
				{ LanguageId.sk, "Kajmanie ostrovy" },
				{ LanguageId.sl, "Kajmanji otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Caymansuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveCayman" },
				{ LanguageId.so, "Cayman Islands" },
				{ LanguageId.sq, "Ishujt Kajman" },
				{ LanguageId.sr, "Кајманска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Cayman" },
				{ LanguageId.su, "Kapuloan Cayman" },
				{ LanguageId.sv, "Caymanöarna" },
				{ LanguageId.sw, "Visiwa vya Cayman" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܟܐܝܡܐܢ" },
				{ LanguageId.ta, "கெய்மென் தீவுகள்" },
				{ LanguageId.te, "కేమాన్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Kayman" },
				{ LanguageId.tg, "Ҷазираҳои Кайман" },
				{ LanguageId.th, "หมู่เกาะเคย์แมน" },
				{ LanguageId.ti, "ደሴታት ካይማን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Kaýman adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Keimeni" },
				{ LanguageId.tr, "Cayman Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Кайман утраулары" },
				{ LanguageId.twq, "Kayman gungey" },
				{ LanguageId.tzm, "Tigzirin n Kayman" },
				{ LanguageId.ug, "كايمان ئاراللىرى" },
				{ LanguageId.uk, "Кайманові Острови" },
				{ LanguageId.ur, "کیمین آئلینڈز" },
				{ LanguageId.uz, "Kayman orollari" },
				{ LanguageId.vai, "ꔞꔀꕮꘋ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Cayman" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Kayman" },
				{ LanguageId.wae, "Kaimaninslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Kaymaŋ" },
				{ LanguageId.xh, "ECayman Islands" },
				{ LanguageId.xog, "Ebizinga bya Kayimaani" },
				{ LanguageId.yav, "Káyímanɛ" },
				{ LanguageId.yi, "קיימאַן אינזלען" },
				{ LanguageId.yo, "Etíokun Kámánì" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⵢⵎⴰⵏ" },
				{ LanguageId.zh, "开曼群岛" },
				{ LanguageId.zu, "i-Cayman Islands" },
			}
		);
	}
}
