using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class LA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "856",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Laos Demokratiske Folkerepublik" },
				{ LanguageId.af, "Laos Demokratiese Volksrepubliek" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የላኦ ህዝቦች ዲሞክራቲክ ሪፐብሊክ" },
				{ LanguageId.ar, "جمهورية لاو الديمقراطية الشعبية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Laos Xalq Demokratik Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Лаоская Народна-Дэмакратычная Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Лаоска народнодемократична република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "লাও পিপলস ডেমোক্রেটিক রিপাবলিক" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Laos" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Laoska Narodna Demokratska Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Democràtica Popular Lao" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Republikang Demokratiko sa Katawhan sa Lao" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Repubblica Democràtica Populare Lao" },
				{ LanguageId.cs, "Laoská lidově demokratická republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Ddemocrataidd Pobl Lao" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Demokratische Volksrepublik Laos" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Λαϊκή Δημοκρατία του Λάος" },
				{ LanguageId.en, "Lao People's Democratic Republic" },
				{ LanguageId.eo, "Laa Popola Demokratia Respubliko" },
				{ LanguageId.es, "República Democrática Popular Lao" },
				{ LanguageId.et, "Laose Demokraatlik Rahvavabariik" },
				{ LanguageId.eu, "Laosko Herri Errepublika Demokratikoa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری دموکراتیک خلق لائوس" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Laon Kansan Demokraattinen Tasavalta" },
				{ LanguageId.fil, "Demokratikong Republika ng Lao" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "République démocratique populaire lao" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Lao Folksdemokratyske Republyk" },
				{ LanguageId.ga, "Daon-Phoblacht Dhaonlathach Lao" },
				{ LanguageId.gd, "Poblachd Dheamocratach Sluagh Lao" },
				{ LanguageId.gl, "República Democrática Popular Lao" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "લાઓ પીપલ્સ ડેમોક્રેટિક રિપબ્લિક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Demokradiyyar Jama'ar Lao" },
				{ LanguageId.haw, "Lepupalika Demokalaka o Lao" },
				{ LanguageId.he, "הרפובליקה הדמוקרטית העממית של לאו" },
				{ LanguageId.hi, "लाओ पीपुल्स डेमोक्रेटिक रिपब्लिक" },
				{ LanguageId.hr, "Narodna Demokratska Republika Laos" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Laoszi Népi Demokratikus Köztársaság" },
				{ LanguageId.hy, "Լաոսի Ժողովրդադեմոկրատական ​​Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Demokratik Rakyat Laos" },
				{ LanguageId.ig, "Ndị Lao Democratic Republic" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Alþýðulýðveldið Lao" },
				{ LanguageId.it, "Repubblica Democratica Popolare del Laos" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ラオス人民民主共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Demokratik Rakyat Lao" },
				{ LanguageId.ka, "ლაოს სახალხო დემოკრატიული რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Лаос Халық Демократиялық Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋប្រជាធិបតេយ្យប្រជាមានិតឡាវ" },
				{ LanguageId.kn, "ಲಾವೊ ಪೀಪಲ್ಸ್ ಡೆಮಾಕ್ರಟಿಕ್ ರಿಪಬ್ಲಿಕ್" },
				{ LanguageId.ko, "라오스 인민민주공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Лаос Элдик Демократиялык Республикасы" },
				{ LanguageId.la, "Laomedonteae Popularis Respublica Populi" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Laos Demokratesch Volleksrepublik" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Laoso Liaudies Demokratinė Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Laosas Tautas Demokrātiskā Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Demokratikan'i Lao" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Repupiripia Manapori Tangata o Lao" },
				{ LanguageId.mk, "Народна Демократска Република Лао" },
				{ LanguageId.ml, "ലാവോ പീപ്പിൾസ് ഡെമോക്രാറ്റിക് റിപ്പബ്ലിക്" },
				{ LanguageId.mn, "Бүгд Найрамдах Ардчилсан Лаос Ард Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "लाओ पीपल्स डेमोक्रॅटिक रिपब्लिक" },
				{ LanguageId.ms, "Republik Demokratik Rakyat Lao" },
				{ LanguageId.mt, "Ir-Repubblika Demokratika Popolari tal-Laos" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "လာအိုပြည်သူ့ဒီမိုကရက်တစ်သမ္မတနိုင်ငံ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Lao folkets Demokratiske Republikk" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "लाओ जनवादी लोकतान्त्रिक गणतन्त्र" },
				{ LanguageId.nl, "Lao Democratische Volksrepubliek" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଲାଓ ପିପୁଲ୍ସ ଡେମୋକ୍ରାଟିକ୍ ରିପବ୍ଲିକ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਲਾਓ ਪੀਪਲਜ਼ ਡੈਮੋਕਰੇਟਿਕ ਰੀਪਬਲਿਕ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Laotańska Republika Ludowo-Demokratyczna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د لاو د خلکو دیموکراتیک جمهوریت" },
				{ LanguageId.pt, "República Democrática Popular do Laos" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Populară Democrată Laos" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Лаосская Народно-Демократическая Республика" },
				{ LanguageId.rw, "Repubulika Iharanira Demokarasi ya rubanda" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "لاؤ پيپلز ڊيموڪريٽڪ ريپبلڪ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ලාඕ මහජන ප්‍රජාතන්ත්‍රවාදී ජනරජය" },
				{ LanguageId.sk, "Laoská ľudovodemokratická republika" },
				{ LanguageId.sl, "Laoška ​​ljudska demokratična republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Lao People's Democratic Republic" },
				{ LanguageId.so, "Jamhuuriyadda Dimuqraadiga Dadka Lao" },
				{ LanguageId.sq, "Republika Popullore Demokratike e Laos" },
				{ LanguageId.sr, "Лао Народна Демократска Република" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lao People's Democratic Republic" },
				{ LanguageId.su, "Républik Démokratik Rahayat Lao" },
				{ LanguageId.sv, "Demokratiska folkrepubliken Laos" },
				{ LanguageId.sw, "Jamhuri ya Kidemokrasia ya Watu wa Lao" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "லாவோ மக்கள் ஜனநாயக குடியரசு" },
				{ LanguageId.te, "లావో పీపుల్స్ డెమోక్రటిక్ రిపబ్లిక్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Республикам Халкии Демократии Лаос" },
				{ LanguageId.th, "สาธารณรัฐประชาธิปไตยประชาชนลาว" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Laos Halk Demokratik Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Lao Demokratik Halk Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Лаос Халык Демократик Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "لائوس خەلق دېموكراتىك جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Лаоська Народно-Демократична Республіка" },
				{ LanguageId.ur, "لاؤ پیپلز ڈیموکریٹک ریپبلک" },
				{ LanguageId.uz, "Laos Xalq Demokratik Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng hòa Dân chủ nhân dân Lào" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IRiphabhlikhi yeDemokhrasi yaseLao" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "לאַו מענטשן ס דעמאָקראַטיש רעפובליק" },
				{ LanguageId.yo, "Lao People ká Democratic Republic" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "老挝人民民主共和国" },
				{ LanguageId.zu, "I-Lao People's Democratic Republic" },
			}
		);
	}
}
