// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class LC
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Lucia" },
				{ LanguageId.af, "Sint Lucia" },
				{ LanguageId.agq, "Sɛ̀n Lushìa" },
				{ LanguageId.ak, "Saint Lucia" },
				{ LanguageId.am, "ሴንት ሉቺያ" },
				{ LanguageId.ar, "سانت لوسيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট লুচিয়া" },
				{ LanguageId.asa, "Thantaluthia" },
				{ LanguageId.ast, "Santa Llucía" },
				{ LanguageId.az, "Sent-Lusiya" },
				{ LanguageId.ba, "Сент-Люсия" },
				{ LanguageId.bas, "Nûmpubi Lusì" },
				{ LanguageId.be, "Сент-Люсія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husantalusia" },
				{ LanguageId.bg, "Сейнт Лусия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Lusi-Senu" },
				{ LanguageId.bn, "সেন্ট লুসিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Saint Lucia" },
				{ LanguageId.brx, "सैन्ट लुसिया" },
				{ LanguageId.bs, "Sveta Lucija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint Lucia" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄣𑄪𑄥𑄨𑄠" },
				{ LanguageId.ce, "Сент-Люси" },
				{ LanguageId.ceb, "St. Lucia" },
				{ LanguageId.cgg, "Senti Rusiya" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᎷᏏᏯ" },
				{ LanguageId.ckb, "سەن لووسیا" },
				{ LanguageId.co, "Santa Lucia" },
				{ LanguageId.cs, "Svatá Lucie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Lucia" },
				{ LanguageId.dav, "Santalusia" },
				{ LanguageId.de, "St. Lucia" },
				{ LanguageId.dje, "Seŋ Lussia" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Lucia" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ ལུ་སི་ཡ" },
				{ LanguageId.ebu, "Santalusia" },
				{ LanguageId.ee, "Saint Lusia nutome" },
				{ LanguageId.el, "Αγία Λουκία" },
				{ LanguageId.en, "St. Lucia" },
				{ LanguageId.eo, "Sankta Lucio" },
				{ LanguageId.es, "Santa Lucía" },
				{ LanguageId.et, "Saint Lucia" },
				{ LanguageId.eu, "Santa Luzia" },
				{ LanguageId.ewo, "Ǹfúfúb-Lúsia" },
				{ LanguageId.fa, "سنت لوسیا" },
				{ LanguageId.ff, "Sent Lusiyaa" },
				{ LanguageId.fi, "Saint Lucia" },
				{ LanguageId.fil, "Saint Lucia" },
				{ LanguageId.fo, "St. Lusia" },
				{ LanguageId.fr, "Sainte-Lucie" },
				{ LanguageId.fur, "Sante Lusie" },
				{ LanguageId.fy, "Saint Lucia" },
				{ LanguageId.ga, "Saint Lucia" },
				{ LanguageId.gd, "Naomh Lùisea" },
				{ LanguageId.gl, "Santa Lucía" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Lutschiia" },
				{ LanguageId.gu, "સેંટ લુસિયા" },
				{ LanguageId.guz, "Santalusia" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Lusiya" },
				{ LanguageId.haw, "Kāna Lukia" },
				{ LanguageId.he, "סנט לוסיה" },
				{ LanguageId.hi, "सेंट लूसिया" },
				{ LanguageId.hr, "Sveta Lucija" },
				{ LanguageId.hsb, "St. Lucia" },
				{ LanguageId.hu, "Saint Lucia" },
				{ LanguageId.hy, "Սենթ Լյուսիա" },
				{ LanguageId.ia, "Sancte Lucia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Lucia" },
				{ LanguageId.ig, "St. Lucia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Lúsía" },
				{ LanguageId.it, "Saint Lucia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントルシア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Santalusia" },
				{ LanguageId.jv, "Santa Lusia" },
				{ LanguageId.ka, "სენტ-ლუსია" },
				{ LanguageId.kab, "San Lučya" },
				{ LanguageId.kam, "Santalusia" },
				{ LanguageId.kde, "Santalusia" },
				{ LanguageId.kea, "Santa Lúsia" },
				{ LanguageId.khq, "Seŋ Lussia" },
				{ LanguageId.ki, "Santalusia" },
				{ LanguageId.kk, "Сент-Люсия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Lucia Ne" },
				{ LanguageId.km, "សាំងលូស៊ី" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಲೂಸಿಯಾ" },
				{ LanguageId.ko, "세인트루시아" },
				{ LanguageId.kok, "सांता लूसिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ لوٗسِیا" },
				{ LanguageId.ksb, "Santalusia" },
				{ LanguageId.ksf, "sɛntlísí" },
				{ LanguageId.ksh, "de Ensel Zint-Lutscha" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Люсия" },
				{ LanguageId.la, "Sancta Lucia" },
				{ LanguageId.lag, "Mʉtakatíifu Lusíia" },
				{ LanguageId.lb, "St. Lucia" },
				{ LanguageId.lg, "Senti Luciya" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu lisi" },
				{ LanguageId.lo, "ເຊນ ລູເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sent Lusija" },
				{ LanguageId.luo, "Saint Lucia" },
				{ LanguageId.luy, "Santalusia" },
				{ LanguageId.lv, "Sentlūsija" },
				{ LanguageId.mai, "सेंट लूसिया" },
				{ LanguageId.mas, "Santalusia" },
				{ LanguageId.mer, "Santalusia" },
				{ LanguageId.mfe, "Sainte-Lucie" },
				{ LanguageId.mg, "Sainte-Lucie" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Ruhia" },
				{ LanguageId.mk, "Сент Лусија" },
				{ LanguageId.ml, "സെന്റ് ലൂസിയ" },
				{ LanguageId.mn, "Сент Люсиа" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट ल्यूसिया" },
				{ LanguageId.ms, "Saint Lucia" },
				{ LanguageId.mt, "Saint Lucia" },
				{ LanguageId.mua, "Sǝr Lucia" },
				{ LanguageId.my, "စိန့်လူစီယာ" },
				{ LanguageId.mzn, "سنت لوسیا" },
				{ LanguageId.naq, "Saint Lucia" },
				{ LanguageId.nb, "St. Lucia" },
				{ LanguageId.nd, "Saint Lucia" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट लुसिया" },
				{ LanguageId.nl, "Saint Lucia" },
				{ LanguageId.nmg, "Saint Lucia" },
				{ LanguageId.nn, "St. Lucia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߟߎ߳ߛߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Senti Rusiya" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Suusiyaa" },
				{ LanguageId.or, "ସେଣ୍ଟ ଲୁସିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਲੂਸੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Lúshia" },
				{ LanguageId.pl, "Saint Lucia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ لوسیا" },
				{ LanguageId.pt, "Santa Lúcia" },
				{ LanguageId.qu, "Santa Lucia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sontga Lucia" },
				{ LanguageId.rn, "Selusiya" },
				{ LanguageId.ro, "Sfânta Lucia" },
				{ LanguageId.rof, "Santalusia" },
				{ LanguageId.ru, "Сент-Люсия" },
				{ LanguageId.rw, "Mutagatifu Lusiya" },
				{ LanguageId.rwk, "Santalusia" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Santalusia" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Santalusiya" },
				{ LanguageId.sd, "سينٽ لوسيا" },
				{ LanguageId.se, "Saint Lucia" },
				{ LanguageId.seh, "Santa Lúcia" },
				{ LanguageId.ses, "Seŋ Lussia" },
				{ LanguageId.sg, "Sênt-Lisïi" },
				{ LanguageId.shi, "ⵙⴰⵏⵜⵍⵓⵙⵉ" },
				{ LanguageId.si, "ශාන්ත ලුසියා" },
				{ LanguageId.sk, "Svätá Lucia" },
				{ LanguageId.sl, "Sveta Lucija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Lucia" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saint Lucia" },
				{ LanguageId.so, "St. Lusia" },
				{ LanguageId.sq, "Shën-Luçia" },
				{ LanguageId.sr, "Света Луција" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Mohalaleli Lucia" },
				{ LanguageId.su, "Saint Lucia" },
				{ LanguageId.sv, "S:t Lucia" },
				{ LanguageId.sw, "St. Lucia" },
				{ LanguageId.syr, "ܡܪܬܝ ܠܘܫܐ" },
				{ LanguageId.ta, "செயின்ட் லூசியா" },
				{ LanguageId.te, "సెయింట్ లూసియా" },
				{ LanguageId.teo, "Santalusia" },
				{ LanguageId.tg, "Сент-Люсия" },
				{ LanguageId.th, "เซนต์ลูเซีย" },
				{ LanguageId.ti, "ቅድስቲ ሉስያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sent-Lýusiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Lūsia" },
				{ LanguageId.tr, "Saint Lucia" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент-Люсия" },
				{ LanguageId.twq, "Seŋ Lussia" },
				{ LanguageId.tzm, "Santelusya" },
				{ LanguageId.ug, "ساينت لۇسىيە" },
				{ LanguageId.uk, "Сент-Люсія" },
				{ LanguageId.ur, "سینٹ لوسیا" },
				{ LanguageId.uz, "Sent-Lyusiya" },
				{ LanguageId.vai, "ꔻꘋ ꖨꔻꕩ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Lucia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Santalusia" },
				{ LanguageId.wae, "St. Lucia" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Lusi" },
				{ LanguageId.xh, "ESt. Lucia" },
				{ LanguageId.xog, "Senti Luciya" },
				{ LanguageId.yav, "sɛ́ŋtɛ́lusí" },
				{ LanguageId.yi, "סיינט לוסיאַ" },
				{ LanguageId.yo, "Luṣia" },
				{ LanguageId.zgh, "ⵙⴰⵏⵜⵍⵓⵙⵉ" },
				{ LanguageId.zh, "圣卢西亚" },
				{ LanguageId.zu, "i-Saint Lucia" },
			}
		);
	}
}
