using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class LC
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sankt Lucia" },
				{ LanguageId.af, "Saint Lucia" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሰይንት ሉካስ" },
				{ LanguageId.ar, "القديسة لوسيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Müqəddəs Lusiya" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сэнт-Люсія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сейнт Лусия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট লুসিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Santez-Lusia" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sveta Lucija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Santa Llúcia" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "San Lucia" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Santa Lucia" },
				{ LanguageId.cs, "Svatá Lucie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sant Lucia" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Lucia" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Αγία Λουκία" },
				{ LanguageId.en, "Saint Lucia" },
				{ LanguageId.eo, "Sankta Lucio" },
				{ LanguageId.es, "Santa Lucía" },
				{ LanguageId.et, "Püha Lucia" },
				{ LanguageId.eu, "Santa Luzia" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت لوسیا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saint Lucia" },
				{ LanguageId.fil, "San Lucia" },
				{ LanguageId.fo, "Saint Lusia" },
				{ LanguageId.fr, "Sainte-Lucie" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint-Lusia" },
				{ LanguageId.ga, "Naomh Lucia" },
				{ LanguageId.gd, "Naomh Lucia" },
				{ LanguageId.gl, "Santa Lucía" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ લુસિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saint Lucia" },
				{ LanguageId.haw, "Kāna Lukia" },
				{ LanguageId.he, "סנט לוסיה" },
				{ LanguageId.hi, "सेंट लूसिया" },
				{ LanguageId.hr, "Sveta Lucija" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Szent Lucia" },
				{ LanguageId.hy, "Սուրբ Լուչիա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Santo Lusia" },
				{ LanguageId.ig, "Saint Lucia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Lúsía" },
				{ LanguageId.it, "Santa Lucia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントルシア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Saint Lucia" },
				{ LanguageId.ka, "წმინდა ლუსია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сент-Люсия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "លោក Saint Lucia" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಲೂಸಿಯಾ" },
				{ LanguageId.ko, "세인트 루시아" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Люсия" },
				{ LanguageId.la, "Sancta Lucia" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saint Lucia" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊນລູເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sent Liucija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sentlūsija" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Saint Lucia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Ruhia" },
				{ LanguageId.mk, "Света Луција" },
				{ LanguageId.ml, "സെൻ്റ് ലൂസിയ" },
				{ LanguageId.mn, "Гэгээн Люсиа" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट लुसिया" },
				{ LanguageId.ms, "Saint Lucia" },
				{ LanguageId.mt, "Santa Luċija" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စိန့်လူစီယာ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saint Lucia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट लुसिया" },
				{ LanguageId.nl, "Sint Lucia" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Saint Lucia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଣ୍ଟ ଲୁସିଆ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਲੂਸੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "święta Lucia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سانت لیوکا" },
				{ LanguageId.pt, "Santa Lúcia" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sfânta Lucia" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Санкт-Люсия" },
				{ LanguageId.rw, "Mutagatifu Lusiya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ لوسيا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත ලුසියා" },
				{ LanguageId.sk, "Svätá Lucia" },
				{ LanguageId.sl, "Sveta Lucija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sendi Rusiya" },
				{ LanguageId.so, "Saint Lucia" },
				{ LanguageId.sq, "Shën Luçia" },
				{ LanguageId.sr, "Света Луција" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Mohalaleli Lucia" },
				{ LanguageId.su, "Saint Lucia" },
				{ LanguageId.sv, "Saint Lucia" },
				{ LanguageId.sw, "Mtakatifu Lucia" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "செயின்ட் லூசியா" },
				{ LanguageId.te, "సెయింట్ లూసియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент Люсия" },
				{ LanguageId.th, "เซนต์ลูเซีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Lýusiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Aziz Lucia" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Изге Люция" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Saint Lucia" },
				{ LanguageId.uk, "Сент-Люсія" },
				{ LanguageId.ur, "سینٹ لوسیا" },
				{ LanguageId.uz, "Sent-Lyusiya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thánh Lucia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Seyint Lushiya" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיינט לוסיאַ" },
				{ LanguageId.yo, "Saint Lucia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣卢西亚" },
				{ LanguageId.zu, "I-Saint Lucia" },
			}
		);
	}
}
