// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class LK
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "94",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sri Lanka" },
				{ LanguageId.af, "Sri Lanka" },
				{ LanguageId.agq, "Sɨ̀le Laŋkà" },
				{ LanguageId.ak, "Sri Lanka" },
				{ LanguageId.am, "ሲሪላንካ" },
				{ LanguageId.ar, "سريلانكا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "শ্রীলংকা" },
				{ LanguageId.asa, "Thirilanka" },
				{ LanguageId.ast, "Sri Lanka" },
				{ LanguageId.az, "Şri-Lanka" },
				{ LanguageId.ba, "Шри-Ланка" },
				{ LanguageId.bas, "Srìlaŋkà" },
				{ LanguageId.be, "Шры-Ланка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husirilanka" },
				{ LanguageId.bg, "Шри Ланка" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Sirilanka" },
				{ LanguageId.bn, "শ্রীলঙ্কা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sri Lanka" },
				{ LanguageId.brx, "श्रीलंका" },
				{ LanguageId.bs, "Šri Lanka" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sri Lanka" },
				{ LanguageId.ccp, "𑄥𑄳𑄢𑄨𑄣𑄧𑄁𑄇" },
				{ LanguageId.ce, "Шри-Ланка" },
				{ LanguageId.ceb, "Sri Lanka" },
				{ LanguageId.cgg, "Siriranka" },
				{ LanguageId.chr, "ᏍᎵ ᎳᏂᎧ" },
				{ LanguageId.ckb, "سریلانکا" },
				{ LanguageId.co, "Sri Lanka" },
				{ LanguageId.cs, "Srí Lanka" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sri Lanka" },
				{ LanguageId.dav, "Sirilanka" },
				{ LanguageId.de, "Sri Lanka" },
				{ LanguageId.dje, "Srilanka" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Sri Lanka" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཤྲཱི་ལང་ཀ" },
				{ LanguageId.ebu, "Sirilanka" },
				{ LanguageId.ee, "Sri Lanka nutome" },
				{ LanguageId.el, "Σρι Λάνκα" },
				{ LanguageId.en, "Sri Lanka" },
				{ LanguageId.eo, "Srilanko" },
				{ LanguageId.es, "Sri Lanka" },
				{ LanguageId.et, "Sri Lanka" },
				{ LanguageId.eu, "Sri Lanka" },
				{ LanguageId.ewo, "Səri Laŋká" },
				{ LanguageId.fa, "سری‌لانکا" },
				{ LanguageId.ff, "Siri Lanka" },
				{ LanguageId.fi, "Sri Lanka" },
				{ LanguageId.fil, "Sri Lanka" },
				{ LanguageId.fo, "Sri Lanka" },
				{ LanguageId.fr, "Sri Lanka" },
				{ LanguageId.fur, "Sri Lanka" },
				{ LanguageId.fy, "Sri Lanka" },
				{ LanguageId.ga, "Srí Lanca" },
				{ LanguageId.gd, "Sri Lanca" },
				{ LanguageId.gl, "Sri Lanka" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Schri Lanka" },
				{ LanguageId.gu, "શ્રીલંકા" },
				{ LanguageId.guz, "Sirilanka" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Siri Lanka" },
				{ LanguageId.haw, "Sililanaka" },
				{ LanguageId.he, "סרי לנקה" },
				{ LanguageId.hi, "श्रीलंका" },
				{ LanguageId.hr, "Šri Lanka" },
				{ LanguageId.hsb, "Sri Lanka" },
				{ LanguageId.hu, "Srí Lanka" },
				{ LanguageId.hy, "Շրի Լանկա" },
				{ LanguageId.ia, "Sri Lanka" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sri Lanka" },
				{ LanguageId.ig, "Sri Lanka" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Srí Lanka" },
				{ LanguageId.it, "Sri Lanka" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "スリランカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Sirilanka" },
				{ LanguageId.jv, "Sri Lanka" },
				{ LanguageId.ka, "შრი-ლანკა" },
				{ LanguageId.kab, "Sri Lanka" },
				{ LanguageId.kam, "Sirilanka" },
				{ LanguageId.kde, "Sililanka" },
				{ LanguageId.kea, "Sri Lanka" },
				{ LanguageId.khq, "Srilanka" },
				{ LanguageId.ki, "Sirilanka" },
				{ LanguageId.kk, "Шри-Ланка" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Sri Lanka" },
				{ LanguageId.km, "ស្រីលង្កា" },
				{ LanguageId.kn, "ಶ್ರೀಲಂಕಾ" },
				{ LanguageId.ko, "스리랑카" },
				{ LanguageId.kok, "श्री लंका" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سری لنکا" },
				{ LanguageId.ksb, "Sililanka" },
				{ LanguageId.ksf, "srílaŋka" },
				{ LanguageId.ksh, "Sri Lanka" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Шри-Ланка" },
				{ LanguageId.la, "Sri Lanka" },
				{ LanguageId.lag, "Siriláanka" },
				{ LanguageId.lb, "Sri Lanka" },
				{ LanguageId.lg, "Sirilanka" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sirilanka" },
				{ LanguageId.lo, "ສີລັງກາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šri Lanka" },
				{ LanguageId.luo, "Sri Lanka" },
				{ LanguageId.luy, "Sirilanka" },
				{ LanguageId.lv, "Šrilanka" },
				{ LanguageId.mai, "श्रीलंका" },
				{ LanguageId.mas, "Sirilanka" },
				{ LanguageId.mer, "Sirilanka" },
				{ LanguageId.mfe, "Sri Lanka" },
				{ LanguageId.mg, "Sri Lanka" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hiri Rānaka" },
				{ LanguageId.mk, "Шри Ланка" },
				{ LanguageId.ml, "ശ്രീലങ്ക" },
				{ LanguageId.mn, "Шри-Ланка" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "श्रीलंका" },
				{ LanguageId.ms, "Sri Lanka" },
				{ LanguageId.mt, "is-Sri Lanka" },
				{ LanguageId.mua, "Sǝr Lanka" },
				{ LanguageId.my, "သီရိလင်္ကာ" },
				{ LanguageId.mzn, "سریلانکا" },
				{ LanguageId.naq, "Sri Lankab" },
				{ LanguageId.nb, "Sri Lanka" },
				{ LanguageId.nd, "Sri Lanka" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "श्रीलङ्का" },
				{ LanguageId.nl, "Sri Lanka" },
				{ LanguageId.nmg, "Sri Lanka" },
				{ LanguageId.nn, "Sri Lanka" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߙߌߟߊ߲ߞߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Siriranka" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Siri Laankaa" },
				{ LanguageId.or, "ଶ୍ରୀଲଙ୍କା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸ੍ਰੀ ਲੰਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sri Lánka" },
				{ LanguageId.pl, "Sri Lanka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سريلنکا" },
				{ LanguageId.pt, "Sri Lanka" },
				{ LanguageId.qu, "Sri Lanka" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sri Lanka" },
				{ LanguageId.rn, "Sirilanka" },
				{ LanguageId.ro, "Sri Lanka" },
				{ LanguageId.rof, "Sirilanka" },
				{ LanguageId.ru, "Шри-Ланка" },
				{ LanguageId.rw, "Sri Lanka" },
				{ LanguageId.rwk, "Sirilanka" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Sirilanka" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Sililanka" },
				{ LanguageId.sd, "سري لنڪا" },
				{ LanguageId.se, "Sri Lanka" },
				{ LanguageId.seh, "Sri Lanka" },
				{ LanguageId.ses, "Srilanka" },
				{ LanguageId.sg, "Sirî-Lanka" },
				{ LanguageId.shi, "ⵙⵔⵉⵍⴰⵏⴽⴰ" },
				{ LanguageId.si, "ශ්‍රී ලංකාව" },
				{ LanguageId.sk, "Srí Lanka" },
				{ LanguageId.sl, "Šrilanka" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Sri Lanka" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sri Lanka" },
				{ LanguageId.so, "Sirilaanka" },
				{ LanguageId.sq, "Sri-Lankë" },
				{ LanguageId.sr, "Шри Ланка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sri Lanka" },
				{ LanguageId.su, "Sri Lanka" },
				{ LanguageId.sv, "Sri Lanka" },
				{ LanguageId.sw, "Sri Lanka" },
				{ LanguageId.syr, "ܫܪܝ ܠܐܢܟܐ" },
				{ LanguageId.ta, "இலங்கை" },
				{ LanguageId.te, "శ్రీలంక" },
				{ LanguageId.teo, "Sirilanka" },
				{ LanguageId.tg, "Шри-Ланка" },
				{ LanguageId.th, "ศรีลังกา" },
				{ LanguageId.ti, "ስሪ ላንካ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Şri-Lanka" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sīlangikā" },
				{ LanguageId.tr, "Sri Lanka" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Шри-Ланка" },
				{ LanguageId.twq, "Srilanka" },
				{ LanguageId.tzm, "Srilanka" },
				{ LanguageId.ug, "سىرىلانكا" },
				{ LanguageId.uk, "Шрі-Ланка" },
				{ LanguageId.ur, "سری لنکا" },
				{ LanguageId.uz, "Shri-Lanka" },
				{ LanguageId.vai, "ꖬꔸ ꕞꘋꕪ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sri Lanka" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Sirilanka" },
				{ LanguageId.wae, "Sri Lanka" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Siri Lànka" },
				{ LanguageId.xh, "ESri Lanka" },
				{ LanguageId.xog, "Sirilanka" },
				{ LanguageId.yav, "silíláŋka" },
				{ LanguageId.yi, "סרי־לאַנקאַ" },
				{ LanguageId.yo, "Siri Lanka" },
				{ LanguageId.zgh, "ⵙⵔⵉⵍⴰⵏⴽⴰ" },
				{ LanguageId.zh, "斯里兰卡" },
				{ LanguageId.zu, "i-Sri Lanka" },
			}
		);
	}
}
