using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class LK
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "94",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sri Lanka" },
				{ LanguageId.af, "Sri Lanka" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሲሪላንካ" },
				{ LanguageId.ar, "سيريلانكا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Şri Lanka" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Шры Ланка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Шри Ланка" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "শ্রীলংকা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Šri Lanka" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sri Lanka" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Sri Lanka" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Sri Lanka" },
				{ LanguageId.cs, "Srí Lanka" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sri Lanca" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Sri Lanka" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σρι Λάνκα" },
				{ LanguageId.en, "Sri Lanka" },
				{ LanguageId.eo, "Srilanko" },
				{ LanguageId.es, "Sri Lanka" },
				{ LanguageId.et, "Sri Lanka" },
				{ LanguageId.eu, "Sri Lanka" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سری لانکا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Sri Lanka" },
				{ LanguageId.fil, "Sri Lanka" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Sri Lanka" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sry Lanka" },
				{ LanguageId.ga, "Srí Lanca" },
				{ LanguageId.gd, "Sri Lanka" },
				{ LanguageId.gl, "Sri Lanka" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "શ્રિલંકા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Sri Lanka" },
				{ LanguageId.haw, "Sililanaka" },
				{ LanguageId.he, "סרי לנקה" },
				{ LanguageId.hi, "श्रीलंका" },
				{ LanguageId.hr, "Šri Lanka" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Sri Lanka" },
				{ LanguageId.hy, "Շրի Լանկա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Srilanka" },
				{ LanguageId.ig, "Sri Lanka" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sri Lanka" },
				{ LanguageId.it, "Sri Lanka" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "スリランカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sri Lanka" },
				{ LanguageId.ka, "შრი ლანკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Шри-Ланка" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ស្រី​លង្កា" },
				{ LanguageId.kn, "ಶ್ರೀಲಂಕಾ" },
				{ LanguageId.ko, "스리랑카" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Шри Ланка" },
				{ LanguageId.la, "Sri Lanka" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Sri Lanka" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສີ​ລັງ​ກາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šri Lanka" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Šrilanka" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Sri Lanka" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Sri Lanka" },
				{ LanguageId.mk, "Шри Ланка" },
				{ LanguageId.ml, "ശ്രീ ലങ്ക" },
				{ LanguageId.mn, "Шри Ланка" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "श्रीलंका" },
				{ LanguageId.ms, "Sri Lanka" },
				{ LanguageId.mt, "Sri Lanka" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "သီရိလင်္ကာ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sri Lanka" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "श्रीलंका" },
				{ LanguageId.nl, "Sri Lanka" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଶ୍ରୀ ଲଙ୍କା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸ਼ਿਰੀਲੰਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Sri Lanka" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سري لنکا" },
				{ LanguageId.pt, "Sri Lanka" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sri Lanka" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Шри-Ланка" },
				{ LanguageId.rw, "Sri Lanka" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سري لنڪا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශ්රී ලංකාව" },
				{ LanguageId.sk, "Srí Lanka" },
				{ LanguageId.sl, "Šrilanka" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Shiri Ranga" },
				{ LanguageId.so, "Sirilaanka" },
				{ LanguageId.sq, "Sri Lanka" },
				{ LanguageId.sr, "Шри Ланка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sri Lanka" },
				{ LanguageId.su, "Sri Lanka" },
				{ LanguageId.sv, "Sri Lanka" },
				{ LanguageId.sw, "Sri Lanka" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "இலங்கை" },
				{ LanguageId.te, "శ్రీలంక" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Шри-Ланка" },
				{ LanguageId.th, "ศรีลังกา" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Şri-Lanka" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Sri Lanka" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Шри-Ланка" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سىرىلانكا" },
				{ LanguageId.uk, "Шрі Ланка" },
				{ LanguageId.ur, "سری لنکا" },
				{ LanguageId.uz, "Shri-Lanka" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sri Lanka" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Shri Lanka" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סרי לאנקא" },
				{ LanguageId.yo, "Siri Lanka" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "斯里兰卡" },
				{ LanguageId.zu, "i-Sri Lanka" },
			}
		);
	}
}
