// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class ME
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "382",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Montenegro" },
				{ LanguageId.af, "Montenegro" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Mɔntenegro" },
				{ LanguageId.am, "ሞንተኔግሮ" },
				{ LanguageId.ar, "الجبل الأسود" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মণ্টেনেগ্ৰু" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Montenegru" },
				{ LanguageId.az, "Monteneqro" },
				{ LanguageId.ba, "Черногория" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Чарнагорыя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Черна гора" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "মন্টিনিগ্রো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Montenegro" },
				{ LanguageId.brx, "मन्टेनेग्र’" },
				{ LanguageId.bs, "Crna Gora" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Montenegro" },
				{ LanguageId.ccp, "𑄟𑄧𑄚𑄴𑄑𑄨𑄚𑄨𑄉𑄳𑄢𑄮" },
				{ LanguageId.ce, "Ӏаьржаламанчоь" },
				{ LanguageId.ceb, "Montenegro" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᎼᏂᏔᏁᎦᎶ" },
				{ LanguageId.ckb, "مۆنتینیگرۆ" },
				{ LanguageId.co, "Montenegro" },
				{ LanguageId.cs, "Černá Hora" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Montenegro" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Montenegro" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Carna Góra" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "མོན་ཊི་ནེག་རོ" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Montenegro nutome" },
				{ LanguageId.el, "Μαυροβούνιο" },
				{ LanguageId.en, "Montenegro" },
				{ LanguageId.eo, "Montenegro" },
				{ LanguageId.es, "Montenegro" },
				{ LanguageId.et, "Montenegro" },
				{ LanguageId.eu, "Montenegro" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "مونته‌نگرو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Montenegro" },
				{ LanguageId.fil, "Montenegro" },
				{ LanguageId.fo, "Montenegro" },
				{ LanguageId.fr, "Monténégro" },
				{ LanguageId.fur, "Montenegro" },
				{ LanguageId.fy, "Montenegro" },
				{ LanguageId.ga, "Montainéagró" },
				{ LanguageId.gd, "Am Monadh Neagrach" },
				{ LanguageId.gl, "Montenegro" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Monteneegro" },
				{ LanguageId.gu, "મૉન્ટેનેગ્રો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Manteneguro" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "מונטנגרו" },
				{ LanguageId.hi, "मोंटेनेग्रो" },
				{ LanguageId.hr, "Crna Gora" },
				{ LanguageId.hsb, "Montenegro" },
				{ LanguageId.hu, "Montenegró" },
				{ LanguageId.hy, "Չեռնոգորիա" },
				{ LanguageId.ia, "Montenegro" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Montenegro" },
				{ LanguageId.ig, "Montenegro" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Svartfjallaland" },
				{ LanguageId.it, "Montenegro" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "モンテネグロ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Montenégro" },
				{ LanguageId.ka, "მონტენეგრო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Montenegru" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Черногория" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ម៉ុងតេណេហ្គ្រោ" },
				{ LanguageId.kn, "ಮೊಂಟೆನೆಗ್ರೋ" },
				{ LanguageId.ko, "몬테네그로" },
				{ LanguageId.kok, "मोंटेनेग्रो" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "موٹونیگِریو" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "et Monteneejro" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Черногория" },
				{ LanguageId.la, "Montenegro" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Montenegro" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Monténégro" },
				{ LanguageId.lo, "ມອນເຕເນໂກຣ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Juodkalnija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Melnkalne" },
				{ LanguageId.mai, "मोंटेनीग्रो" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Montenegro" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Maungakororiko" },
				{ LanguageId.mk, "Црна Гора" },
				{ LanguageId.ml, "മോണ്ടെനെഗ്രോ" },
				{ LanguageId.mn, "Монтенегро" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मोंटेनेग्रो" },
				{ LanguageId.ms, "Montenegro" },
				{ LanguageId.mt, "il-Montenegro" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "မွန်တီနိဂရိုး" },
				{ LanguageId.mzn, "مونته‌نگرو" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Montenegro" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "मोन्टेनिग्रो" },
				{ LanguageId.nl, "Montenegro" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Montenegro" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߐ߲ߕߣߋߜ߭ߙߏ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Montenegiroo" },
				{ LanguageId.or, "ମଣ୍ଟେନିଗ୍ରୋ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮੋਂਟੇਨੇਗਰੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Mọntinígro" },
				{ LanguageId.pl, "Czarnogóra" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "مونټینیګرو" },
				{ LanguageId.pt, "Montenegro" },
				{ LanguageId.qu, "Montenegro" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Montenegro" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Muntenegru" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Черногория" },
				{ LanguageId.rw, "Montenegro" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "مونٽي نيگرو" },
				{ LanguageId.se, "Montenegro" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "මොන්ටෙනීග්‍රෝ" },
				{ LanguageId.sk, "Čierna Hora" },
				{ LanguageId.sl, "Črna gora" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Montenegro" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Montenegro" },
				{ LanguageId.so, "Moontenegro" },
				{ LanguageId.sq, "Mal i Zi" },
				{ LanguageId.sr, "Црна Гора" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "Monténégro" },
				{ LanguageId.sv, "Montenegro" },
				{ LanguageId.sw, "Montenegro" },
				{ LanguageId.syr, "ܡܘܢܛܝܢܝܓܪܘ" },
				{ LanguageId.ta, "மான்டேனெக்ரோ" },
				{ LanguageId.te, "మాంటెనెగ్రో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Черногория" },
				{ LanguageId.th, "มอนเตเนโกร" },
				{ LanguageId.ti, "ሞንተኔግሮ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Çernogoriýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Monitenikalo" },
				{ LanguageId.tr, "Karadağ" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Черногория" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "قارا تاغ" },
				{ LanguageId.uk, "Чорногорія" },
				{ LanguageId.ur, "مونٹے نیگرو" },
				{ LanguageId.uz, "Chernogoriya" },
				{ LanguageId.vai, "ꗞꔳꕇꖶꖄ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Montenegro" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "Montenegro" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Montenegoro" },
				{ LanguageId.xh, "EMontenegro" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מאנטענעגרא" },
				{ LanguageId.yo, "Montenégrò" },
				{ LanguageId.zgh, "ⵎⵓⵏⵜⵉⵏⵉⴳⵔⵓ" },
				{ LanguageId.zh, "黑山" },
				{ LanguageId.zu, "i-Montenegro" },
			}
		);
	}
}
