// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "590",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Martin" },
				{ LanguageId.af, "Sint Martin" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "St. Maatin" },
				{ LanguageId.am, "ሴንት ማርቲን" },
				{ LanguageId.ar, "سان مارتن" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট মাৰ্টিন" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Saint Martin" },
				{ LanguageId.az, "Sent Martin" },
				{ LanguageId.ba, "Сен-Мартен" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сен-Мартэн" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сен Мартен" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট মার্টিন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sant-Martin" },
				{ LanguageId.brx, "सैन्ट मार्तिन" },
				{ LanguageId.bs, "Sveti Martin" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint Martin" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄟𑄢𑄴𑄑𑄨𑄚𑄴" },
				{ LanguageId.ce, "Сен-Мартен" },
				{ LanguageId.ceb, "St. Martin" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᏡᏡ" },
				{ LanguageId.ckb, "سەن مارتین" },
				{ LanguageId.co, "" },
				{ LanguageId.cs, "Svatý Martin (Francie)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Martin" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Martin" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Martin" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ མཱར་ཊིན" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Saint Martin nutome" },
				{ LanguageId.el, "Άγιος Μαρτίνος (Γαλλικό τμήμα)" },
				{ LanguageId.en, "St. Martin" },
				{ LanguageId.eo, "Saint-Martin" },
				{ LanguageId.es, "San Martín" },
				{ LanguageId.et, "Saint-Martin" },
				{ LanguageId.eu, "San Martin" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت مارتین" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saint-Martin" },
				{ LanguageId.fil, "Saint Martin" },
				{ LanguageId.fo, "St-Martin" },
				{ LanguageId.fr, "Saint-Martin" },
				{ LanguageId.fur, "Sant Martin" },
				{ LanguageId.fy, "Saint-Martin" },
				{ LanguageId.ga, "Saint-Martin" },
				{ LanguageId.gd, "Naomh Màrtainn" },
				{ LanguageId.gl, "Saint Martin" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Martin" },
				{ LanguageId.gu, "સેંટ માર્ટિન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Martin" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "סן מרטן" },
				{ LanguageId.hi, "सेंट मार्टिन" },
				{ LanguageId.hr, "Saint Martin" },
				{ LanguageId.hsb, "St. Martin" },
				{ LanguageId.hu, "Saint Martin" },
				{ LanguageId.hy, "Սեն Մարտեն" },
				{ LanguageId.ia, "Sancte Martino francese" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Martin" },
				{ LanguageId.ig, "St. Martin" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Saint-Martin" },
				{ LanguageId.it, "Saint Martin" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サン・マルタン" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Santa Martin" },
				{ LanguageId.ka, "სენ-მარტენი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "San Martinhu (Fransa)" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сен-Мартен" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាំង​ម៉ាទីន" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಮಾರ್ಟಿನ್" },
				{ LanguageId.ko, "생마르탱" },
				{ LanguageId.kok, "सॅंट मार्टिन" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ مارٹِن" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "de Zint-Määtes-Ensel" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Мартин" },
				{ LanguageId.la, "" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "St. Martin" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊນ ມາທິນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sen Martenas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Senmartēna" },
				{ LanguageId.mai, "सेंट मार्टिन" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Mātene" },
				{ LanguageId.mk, "Сент Мартин" },
				{ LanguageId.ml, "സെന്റ് മാർട്ടിൻ" },
				{ LanguageId.mn, "Сент-Мартин" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट मार्टिन" },
				{ LanguageId.ms, "Saint Martin" },
				{ LanguageId.mt, "Saint Martin" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စိန့်မာတင်" },
				{ LanguageId.mzn, "سنت مارتین" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saint-Martin" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट मार्टिन" },
				{ LanguageId.nl, "Saint-Martin" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Saint-Martin" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߡߊߙߑߕߍ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Martiin" },
				{ LanguageId.or, "ସେଣ୍ଟ ମାର୍ଟିନ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਮਾਰਟਿਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Mátin" },
				{ LanguageId.pl, "Saint-Martin" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ مارټن" },
				{ LanguageId.pt, "São Martinho" },
				{ LanguageId.qu, "San Martín" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Saint Martin" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sfântul Martin" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сен-Мартен" },
				{ LanguageId.rw, "" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ مارٽن" },
				{ LanguageId.se, "Frankriikka Saint Martin" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත මාර්ටින්" },
				{ LanguageId.sk, "Svätý Martin (fr.)" },
				{ LanguageId.sl, "Francoski Sveti Martin" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Martin" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "" },
				{ LanguageId.so, "St. Maartin" },
				{ LanguageId.sq, "Sen-Marten" },
				{ LanguageId.sr, "Свети Мартин (Француска)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "" },
				{ LanguageId.sv, "Saint-Martin" },
				{ LanguageId.sw, "St. Martin" },
				{ LanguageId.syr, "ܣܐܢܬ ܡܐܪܬܝܢ" },
				{ LanguageId.ta, "செயின்ட் மார்ட்டீன்" },
				{ LanguageId.te, "సెయింట్ మార్టిన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираи Сент-Мартин" },
				{ LanguageId.th, "เซนต์มาร์ติน" },
				{ LanguageId.ti, "ቅዱስ ማርቲን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sen-Marten" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Mātini (fakafalanisē)" },
				{ LanguageId.tr, "Saint Martin" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент-Мартин" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ساينت مارتىن" },
				{ LanguageId.uk, "Сен-Мартен" },
				{ LanguageId.ur, "سینٹ مارٹن" },
				{ LanguageId.uz, "Sent-Martin" },
				{ LanguageId.vai, "ꕪꘋꕓ ꗞꗢ ꕮꕊꔳꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Martin" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "St. Martin" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Marteŋ" },
				{ LanguageId.xh, "ESt. Martin" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "" },
				{ LanguageId.yo, "Ìlú Màtìnì" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "法属圣马丁" },
				{ LanguageId.zu, "i-Saint Martin" },
			}
		);
	}
}
