// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "692",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Marshalløerne" },
				{ LanguageId.af, "Marshalleilande" },
				{ LanguageId.agq, "Chwɨlà fɨ Mashà" },
				{ LanguageId.ak, "Mahyaa Aeland" },
				{ LanguageId.am, "ማርሻል ደሴቶች" },
				{ LanguageId.ar, "جزر مارشال" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মাৰ্শ্বাল দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Marshal" },
				{ LanguageId.ast, "Islles Marshall" },
				{ LanguageId.az, "Marşal adaları" },
				{ LanguageId.ba, "Маршалл утрауҙары" },
				{ LanguageId.bas, "Bìòn bi Marcàl" },
				{ LanguageId.be, "Маршалавы астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Marshal" },
				{ LanguageId.bg, "Маршалови острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Marisali Gun" },
				{ LanguageId.bn, "মার্শাল দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Marshall" },
				{ LanguageId.brx, "मार्शेल द्वीप" },
				{ LanguageId.bs, "Maršalova ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Marshall" },
				{ LanguageId.ccp, "𑄟𑄢𑄴𑄥𑄣𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Маршаллан гӀайренаш" },
				{ LanguageId.ceb, "Marshall Islands" },
				{ LanguageId.cgg, "Ebizinga bya Marshaa" },
				{ LanguageId.chr, "ᎹᏌᎵ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی مارشاڵ" },
				{ LanguageId.co, "Isule Marshal" },
				{ LanguageId.cs, "Marshallovy ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Marshall" },
				{ LanguageId.dav, "Visiwa vya Marshal" },
				{ LanguageId.de, "Marshallinseln" },
				{ LanguageId.dje, "Maršal gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Marshallowe kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "མར་ཤེལ་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Visiwa vya Marshal" },
				{ LanguageId.ee, "Marshal ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Μάρσαλ" },
				{ LanguageId.en, "Marshall Islands" },
				{ LanguageId.eo, "Marŝaloj" },
				{ LanguageId.es, "Islas Marshall" },
				{ LanguageId.et, "Marshalli Saared" },
				{ LanguageId.eu, "Marshall Uharteak" },
				{ LanguageId.ewo, "Minlán Mí Maresál" },
				{ LanguageId.fa, "جزایر مارشال" },
				{ LanguageId.ff, "Duuɗe Marsaal" },
				{ LanguageId.fi, "Marshallinsaaret" },
				{ LanguageId.fil, "Marshall Islands" },
				{ LanguageId.fo, "Marshalloyggjar" },
				{ LanguageId.fr, "Îles Marshall" },
				{ LanguageId.fur, "Isulis Marshall" },
				{ LanguageId.fy, "Marshalleilannen" },
				{ LanguageId.ga, "Oileáin Marshall" },
				{ LanguageId.gd, "Eileanan Mharshall" },
				{ LanguageId.gl, "Illas Marshall" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Marshallinsle" },
				{ LanguageId.gu, "માર્શલ આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Marshal" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Marshal" },
				{ LanguageId.haw, "Mākala ʻAilana" },
				{ LanguageId.he, "איי מרשל" },
				{ LanguageId.hi, "मार्शल द्वीपसमूह" },
				{ LanguageId.hr, "Maršalovi Otoci" },
				{ LanguageId.hsb, "Marshallowe kupy" },
				{ LanguageId.hu, "Marshall-szigetek" },
				{ LanguageId.hy, "Մարշալյան կղզիներ" },
				{ LanguageId.ia, "Insulas Marshall" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Marshall" },
				{ LanguageId.ig, "Agwaetiti Marshall" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Marshalleyjar" },
				{ LanguageId.it, "Isole Marshall" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "マーシャル諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Marshal" },
				{ LanguageId.jv, "Kapuloan Marshall" },
				{ LanguageId.ka, "მარშალის კუნძულები" },
				{ LanguageId.kab, "Tigzirin n Marcal" },
				{ LanguageId.kam, "Visiwa vya Marshal" },
				{ LanguageId.kde, "Chisiwa cha Malushal" },
				{ LanguageId.kea, "Ilhas Marxal" },
				{ LanguageId.khq, "Maršal gungey" },
				{ LanguageId.ki, "Visiwa vya Marshal" },
				{ LanguageId.kk, "Маршалл аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeiyotab Marshall" },
				{ LanguageId.km, "កោះ​ម៉ាស់សល" },
				{ LanguageId.kn, "ಮಾರ್ಷಲ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "마셜 제도" },
				{ LanguageId.kok, "मार्शल जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مارشَل جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Mashal" },
				{ LanguageId.ksf, "zǝ i marcál" },
				{ LanguageId.ksh, "de Machschall-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Маршалл аралдары" },
				{ LanguageId.la, "Insulae Marsalienses" },
				{ LanguageId.lag, "Visíiwa vya Marisháali" },
				{ LanguageId.lb, "Marshallinselen" },
				{ LanguageId.lg, "Bizinga bya Mariso" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Marishalɛ" },
				{ LanguageId.lo, "ຫມູ່ເກາະມາແຊວ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Maršalo Salos" },
				{ LanguageId.luo, "Chuia mar Marshall" },
				{ LanguageId.luy, "Visiwa vya Marshal" },
				{ LanguageId.lv, "Māršala salas" },
				{ LanguageId.mai, "मार्शल द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Marshal" },
				{ LanguageId.mer, "Aĩrandi cia Marshal" },
				{ LanguageId.mfe, "Zil Marshall" },
				{ LanguageId.mg, "Nosy Marshall" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Motu Māhara" },
				{ LanguageId.mk, "Маршалски Острови" },
				{ LanguageId.ml, "മാർഷൽ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Маршаллын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मार्शल बेटे" },
				{ LanguageId.ms, "Kepulauan Marshall" },
				{ LanguageId.mt, "Gżejjer Marshall" },
				{ LanguageId.mua, "Sǝr Marshall ma laŋne" },
				{ LanguageId.my, "မာရှယ် ကျွန်းစု" },
				{ LanguageId.mzn, "مارشال جزایر" },
				{ LanguageId.naq, "Marshall Islands" },
				{ LanguageId.nb, "Marshalløyene" },
				{ LanguageId.nd, "Marshall Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "मार्शल टापुहरु" },
				{ LanguageId.nl, "Marshalleilanden" },
				{ LanguageId.nmg, "Maŋ́ má Marshall" },
				{ LanguageId.nn, "Marshalløyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߊߙߑߛߊߟ ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ebizinga bya Marshaa" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Maarshaal" },
				{ LanguageId.or, "ମାର୍ଶାଲ୍ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮਾਰਸ਼ਲ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Máshál Aílands" },
				{ LanguageId.pl, "Wyspy Marshalla" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "مارشل ټاپوګان" },
				{ LanguageId.pt, "Ilhas Marshall" },
				{ LanguageId.qu, "Islas Marshall" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas da Marshall" },
				{ LanguageId.rn, "Izinga rya Marishari" },
				{ LanguageId.ro, "Insulele Marshall" },
				{ LanguageId.rof, "Visiwa vya Marshal" },
				{ LanguageId.ru, "Маршалловы о-ва" },
				{ LanguageId.rw, "Ibirwa bya Marshall" },
				{ LanguageId.rwk, "Visiwa vya Marshal" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Marshal" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli ifya Malishali" },
				{ LanguageId.sd, "مارشل ٻيٽ" },
				{ LanguageId.se, "Marshallsullot" },
				{ LanguageId.seh, "Ilhas Marshall" },
				{ LanguageId.ses, "Maršal gungey" },
				{ LanguageId.sg, "Âzûâ Märshâl" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵔⵛⴰⵍ" },
				{ LanguageId.si, "මාෂල් දූපත්" },
				{ LanguageId.sk, "Marshallove ostrovy" },
				{ LanguageId.sl, "Marshallovi otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Marshallsuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveMarshall" },
				{ LanguageId.so, "Jasiiradda Maarshal" },
				{ LanguageId.sq, "Ishujt Marshall" },
				{ LanguageId.sr, "Маршалска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Marshall" },
				{ LanguageId.su, "Kapuloan Marshall" },
				{ LanguageId.sv, "Marshallöarna" },
				{ LanguageId.sw, "Visiwa vya Marshall" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܡܐܪܫܐܠ" },
				{ LanguageId.ta, "மார்ஷல் தீவுகள்" },
				{ LanguageId.te, "మార్షల్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Marshal" },
				{ LanguageId.tg, "Ҷазираҳои Маршалл" },
				{ LanguageId.th, "หมู่เกาะมาร์แชลล์" },
				{ LanguageId.ti, "ደሴታት ማርሻል" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Marşall adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Māsolo" },
				{ LanguageId.tr, "Marshall Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Маршалл утраулары" },
				{ LanguageId.twq, "Maršal gungey" },
				{ LanguageId.tzm, "Tigzirin n Marcal" },
				{ LanguageId.ug, "مارشال ئاراللىرى" },
				{ LanguageId.uk, "Маршаллові Острови" },
				{ LanguageId.ur, "مارشل آئلینڈز" },
				{ LanguageId.uz, "Marshall orollari" },
				{ LanguageId.vai, "ꕮꕊꕣ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Marshall" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Marshal" },
				{ LanguageId.wae, "Maršalinslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Marsaal" },
				{ LanguageId.xh, "EMarshall Islands" },
				{ LanguageId.xog, "Bizinga bya Mariso" },
				{ LanguageId.yav, "ílmalasáal" },
				{ LanguageId.yi, "מאַרשאַל אינזלען" },
				{ LanguageId.yo, "Etikun Máṣali" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵔⵛⴰⵍ" },
				{ LanguageId.zh, "马绍尔群岛" },
				{ LanguageId.zu, "i-Marshall Islands" },
			}
		);
	}
}
