using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class MH
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "692",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Marshalløerne" },
				{ LanguageId.af, "Marshall-eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ማርሻል አይስላንድ" },
				{ LanguageId.ar, "جزر مارشال" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Marşal adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Маршалавы Астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Маршалови острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "মার্শাল দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Marshall Islands" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Marshall" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga isla sa Marshall" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Marshal" },
				{ LanguageId.cs, "Marshallovy ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Marshall" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Marshallinseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νήσοι Μάρσαλ" },
				{ LanguageId.en, "Marshall Islands" },
				{ LanguageId.eo, "Marŝala Insularo" },
				{ LanguageId.es, "Islas Marshall" },
				{ LanguageId.et, "Marshalli saared" },
				{ LanguageId.eu, "Marshall Uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر مارشال" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Marshallsaaret" },
				{ LanguageId.fil, "Marshall Islands" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Iles Marshall" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Marshalleilannen" },
				{ LanguageId.ga, "Oileáin Mharshall" },
				{ LanguageId.gd, "Na h-Eileanan Marshall" },
				{ LanguageId.gl, "Illas Marshall" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "માર્શલ ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Marshall" },
				{ LanguageId.haw, "Mākala ʻAilana" },
				{ LanguageId.he, "איי מרשל" },
				{ LanguageId.hi, "मार्शल द्वीपसमूह" },
				{ LanguageId.hr, "Maršalovi otoci" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Marshall-szigetek" },
				{ LanguageId.hy, "Մարշալյան կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Pulau Marshall" },
				{ LanguageId.ig, "Marshall Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Marshall-eyjar" },
				{ LanguageId.it, "Isole Marshall" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "マーシャル諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Marshall" },
				{ LanguageId.ka, "მარშალის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Маршалл аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Marshall" },
				{ LanguageId.kn, "ಮಾರ್ಷಲ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "마샬 군도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Маршал аралдары" },
				{ LanguageId.la, "Insulae Marsalienses" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Marshallinselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະມາແຊລ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Maršalo salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Māršala salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Marshall" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Moutere o Māhara" },
				{ LanguageId.mk, "Маршалските Острови" },
				{ LanguageId.ml, "മാർഷൽ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Маршаллын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मार्शल बेटे" },
				{ LanguageId.ms, "Pulau Marshall" },
				{ LanguageId.mt, "Gżejjer Marshall" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "မာရှယ်ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Marshalløyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "मार्शल टापुहरू" },
				{ LanguageId.nl, "Marshall eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ମାର୍ଶଲ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮਾਰਸ਼ਲ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Marshalla" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "مارشال ټاپو" },
				{ LanguageId.pt, "Ilhas Marshall" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Marshall" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Маршалловы острова" },
				{ LanguageId.rw, "Ibirwa bya Marshall" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "مارشل ڀيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "මාෂල් දූපත්" },
				{ LanguageId.sk, "Maršalove ostrovy" },
				{ LanguageId.sl, "Marshallovi otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa Masharo" },
				{ LanguageId.so, "Jasiiradaha Marshall" },
				{ LanguageId.sq, "Ishujt Marshall" },
				{ LanguageId.sr, "Маршалска острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Marshall" },
				{ LanguageId.su, "Kapuloan Marshall" },
				{ LanguageId.sv, "Marshallöarna" },
				{ LanguageId.sw, "Visiwa vya Marshall" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "மார்ஷல் தீவுகள்" },
				{ LanguageId.te, "మార్షల్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Маршалл" },
				{ LanguageId.th, "หมู่เกาะมาร์แชลล์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Marşal adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Marşal Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Маршалл утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "مارشال تاقىم ئاراللىرى" },
				{ LanguageId.uk, "Маршаллові острови" },
				{ LanguageId.ur, "مارشل جزائر" },
				{ LanguageId.uz, "Marshall orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "đảo Marshall" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Isiqithi saseMashal" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מאַרשאַל אינזלען" },
				{ LanguageId.yo, "Awọn erekusu Marshall" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "马绍尔群岛" },
				{ LanguageId.zu, "Iziqhingi zaseMarshall" },
			}
		);
	}
}
