// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MK
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "389",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Nordmakedonien" },
				{ LanguageId.af, "Noord-Macedonië" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Mesidonia Atifi" },
				{ LanguageId.am, "ሰሜን መቄዶንያ" },
				{ LanguageId.ar, "مقدونيا الشمالية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "উত্তৰ মেচিডোনীয়া" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Şimali Makedoniya" },
				{ LanguageId.ba, "Төньяҡ Македония" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Паўночная Македонія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Северна Македония" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "উত্তর ম্যাসেডোনিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Makedonia an Norzh" },
				{ LanguageId.brx, "साहा मेसेड’निया" },
				{ LanguageId.bs, "Sjeverna Makedonija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Macedònia del Nord" },
				{ LanguageId.ccp, "𑄟𑄳𑄠𑄥𑄓𑄮𑄚𑄨𑄠" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "North Macedonia" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏧᏴᏜ ᎹᏎᏙᏂᏯ" },
				{ LanguageId.ckb, "مەکدۆنیای باکوور" },
				{ LanguageId.co, "Maccedonia" },
				{ LanguageId.cs, "Severní Makedonie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gogledd Macedonia" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Nordmazedonien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódpołnocna Makedańska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Βόρεια Μακεδονία" },
				{ LanguageId.en, "North Macedonia" },
				{ LanguageId.eo, "Nord-Makedonujo" },
				{ LanguageId.es, "Macedonia del Norte" },
				{ LanguageId.et, "Põhja-Makedoonia" },
				{ LanguageId.eu, "Ipar Mazedonia" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "مقدونیهٔ شمالی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Pohjois-Makedonia" },
				{ LanguageId.fil, "North Macedonia" },
				{ LanguageId.fo, "Norður Makedónia" },
				{ LanguageId.fr, "Macédoine du Nord" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Massedoanje" },
				{ LanguageId.ga, "an Mhacadóin Thuaidh" },
				{ LanguageId.gd, "A’ Mhasadon a Tuath" },
				{ LanguageId.gl, "Macedonia do Norte" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ઉત્તર મેસેડોનિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Macedonia ta Arewa" },
				{ LanguageId.haw, "Makekonia" },
				{ LanguageId.he, "מקדוניה הצפונית" },
				{ LanguageId.hi, "उत्तरी मकदूनिया" },
				{ LanguageId.hr, "Sjeverna Makedonija" },
				{ LanguageId.hsb, "Serwjerna Makedonska" },
				{ LanguageId.hu, "Észak-Macedónia" },
				{ LanguageId.hy, "Հյուսիսային Մակեդոնիա" },
				{ LanguageId.ia, "Macedonia del Nord" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Makedonia Utara" },
				{ LanguageId.ig, "North Macedonia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Norður-Makedónía" },
				{ LanguageId.it, "Macedonia del Nord" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "北マケドニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Républik Makédonia Lor" },
				{ LanguageId.ka, "ჩრდილოეთ მაკედონია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Masidónia di Norti" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Солтүстік Македония" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ម៉ាសេដ្វានខាងជើង" },
				{ LanguageId.kn, "ಉತ್ತರ ಮ್ಯಾಸಿಡೋನಿಯಾ" },
				{ LanguageId.ko, "북마케도니아" },
				{ LanguageId.kok, "उत्तर मॅसिडोनिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "شُمالی میسڈونیا" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түндүк Македония" },
				{ LanguageId.la, "macedonicum" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Nordmazedonien" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ແມຊິໂດເນຍເໜືອ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šiaurės Makedonija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Ziemeļmaķedonija" },
				{ LanguageId.mai, "उत्तरी मकदूनिया" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Makedonia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Makerōnia ki te Raki" },
				{ LanguageId.mk, "Северна Македонија" },
				{ LanguageId.ml, "നോർത്ത് മാസിഡോണിയ" },
				{ LanguageId.mn, "Хойд Македон" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "उत्तर मॅसेडोनिया" },
				{ LanguageId.ms, "Macedonia Utara" },
				{ LanguageId.mt, "il-Maċedonja ta’ Fuq" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "မြောက် မက်ဆီဒိုးနီးယား" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Nord-Makedonia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "उत्तर म्यासेडोनिया" },
				{ LanguageId.nl, "Noord-Macedonië" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Nord-Makedonia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߐ߬ߘߎ߮ ߡߊߛߋߘߏߣߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Maqdooniyaa Kaabaa" },
				{ LanguageId.or, "ଉତ୍ତର ମାସେଡୋନିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਉੱਤਰੀ ਮੈਕਡੋਨੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Nọ́t Masidónia" },
				{ LanguageId.pl, "Macedonia Północna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "شمالي مقدونيه" },
				{ LanguageId.pt, "Macedônia do Norte" },
				{ LanguageId.qu, "Macedonia del Norte" },
				{ LanguageId.quc, "Macedonia del Norte" },
				{ LanguageId.rm, "Macedonia dal Nord" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Macedonia de Nord" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Северная Македония" },
				{ LanguageId.rw, "Masedoniya y’Amajyaruguru" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "اتر مقدونيا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "උතුරු මැසිඩෝනියාව" },
				{ LanguageId.sk, "Severné Macedónsko" },
				{ LanguageId.sl, "Severna Makedonija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Masedhoniya" },
				{ LanguageId.so, "Masedooniya Waqooyi" },
				{ LanguageId.sq, "Maqedonia e Veriut" },
				{ LanguageId.sr, "Северна Македонија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Macedonia" },
				{ LanguageId.su, "Makédonia" },
				{ LanguageId.sv, "Nordmakedonien" },
				{ LanguageId.sw, "Masedonia ya Kaskazini" },
				{ LanguageId.syr, "ܓܪܒܝ ܡܩܕܘܢܝܐ" },
				{ LanguageId.ta, "வடக்கு மாசிடோனியா" },
				{ LanguageId.te, "ఉత్తర మాసిడోనియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Македонияи Шимолӣ" },
				{ LanguageId.th, "มาซิโดเนียเหนือ" },
				{ LanguageId.ti, "ሰሜን መቄዶንያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Demirgazyk Makedoniýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Masetōnia fakatokelau" },
				{ LanguageId.tr, "Kuzey Makedonya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Төньяк Македония" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "شىمالىي ماكېدونىيە" },
				{ LanguageId.uk, "Північна Македонія" },
				{ LanguageId.ur, "شمالی مقدونیہ" },
				{ LanguageId.uz, "Shimoliy Makedoniya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Bắc Macedonia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Maseduwaan bëj Gànnaar" },
				{ LanguageId.xh, "EMntla Macedonia" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מאַסעדאָניאַ" },
				{ LanguageId.yo, "Àríwá Macedonia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "北马其顿" },
				{ LanguageId.zu, "i-North Macedonia" },
			}
		);
	}
}
