// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "95",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Myanmar" },
				{ LanguageId.da, "Myanmar (Burma)" },
				{ LanguageId.af, "Mianmar (Birma)" },
				{ LanguageId.agq, "Mǐanmà" },
				{ LanguageId.ak, "Mayaama (Bɛɛma)" },
				{ LanguageId.am, "ማይናማር(በርማ)" },
				{ LanguageId.ar, "ميانمار (بورما)" },
				{ LanguageId.arn, "Myanmar" },
				{ LanguageId.@as, "ম্যানমাৰ (বাৰ্মা)" },
				{ LanguageId.asa, "Myama" },
				{ LanguageId.ast, "Myanmar (Birmania)" },
				{ LanguageId.az, "Myanma" },
				{ LanguageId.ba, "Мьянма (Бирма)" },
				{ LanguageId.bas, "Myànmâr" },
				{ LanguageId.be, "М’янма (Бірма)" },
				{ LanguageId.bem, "Myanmar" },
				{ LanguageId.bez, "Humyama" },
				{ LanguageId.bg, "Мианмар (Бирма)" },
				{ LanguageId.bin, "Myanmar" },
				{ LanguageId.bm, "Myanimari" },
				{ LanguageId.bn, "মায়ানমার (বার্মা)" },
				{ LanguageId.bo, "མེ་མར།" },
				{ LanguageId.br, "Myanmar (Birmania)" },
				{ LanguageId.brx, "म्यानमार" },
				{ LanguageId.bs, "Mijanmar" },
				{ LanguageId.byn, "Myanmar" },
				{ LanguageId.ca, "Myanmar (Birmània)" },
				{ LanguageId.ccp, "𑄟𑄠𑄚𑄴𑄟𑄢𑄴 (𑄝𑄢𑄴𑄟)" },
				{ LanguageId.ce, "Мьянма (Бирма)" },
				{ LanguageId.ceb, "Myanmar (Burma)" },
				{ LanguageId.cgg, "Myanamar" },
				{ LanguageId.chr, "ᎹᏯᎹᎵ (ᏇᎵᎹ)" },
				{ LanguageId.ckb, "میانمار" },
				{ LanguageId.co, "Birmania" },
				{ LanguageId.cs, "Myanmar (Barma)" },
				{ LanguageId.cu, "Мѷанмар" },
				{ LanguageId.cy, "Myanmar (Burma)" },
				{ LanguageId.dav, "Myama" },
				{ LanguageId.de, "Myanmar" },
				{ LanguageId.dje, "Maynamar" },
				{ LanguageId.doi, "म्यांमार" },
				{ LanguageId.dsb, "Myanmar" },
				{ LanguageId.dua, "Myanmar" },
				{ LanguageId.dv, "ބަރުމާ" },
				{ LanguageId.dz, "མི་ཡཱན་མར་ (བྷར་མ)" },
				{ LanguageId.ebu, "Myama" },
				{ LanguageId.ee, "Myanmar (Burma) nutome" },
				{ LanguageId.el, "Μιανμάρ (Βιρμανία)" },
				{ LanguageId.en, "Myanmar (Burma)" },
				{ LanguageId.eo, "Birmo" },
				{ LanguageId.es, "Myanmar (Birmania)" },
				{ LanguageId.et, "Myanmar (Birma)" },
				{ LanguageId.eu, "Myanmar (Birmania)" },
				{ LanguageId.ewo, "Mianəmár" },
				{ LanguageId.fa, "میانمار (برمه)" },
				{ LanguageId.ff, "Miyamaar" },
				{ LanguageId.fi, "Myanmar (Burma)" },
				{ LanguageId.fil, "Myanmar (Burma)" },
				{ LanguageId.fo, "Myanmar (Burma)" },
				{ LanguageId.fr, "Myanmar (Birmanie)" },
				{ LanguageId.fur, "Birmanie" },
				{ LanguageId.fy, "Myanmar (Birma)" },
				{ LanguageId.ga, "Maenmar (Burma)" },
				{ LanguageId.gd, "Miànmar" },
				{ LanguageId.gl, "Myanmar (Birmania)" },
				{ LanguageId.gn, "Myanmar" },
				{ LanguageId.gsw, "Myanmar (Burma)" },
				{ LanguageId.gu, "મ્યાંમાર (બર્મા)" },
				{ LanguageId.guz, "Myama" },
				{ LanguageId.gv, "Myanmar" },
				{ LanguageId.ha, "Burma, Miyamar" },
				{ LanguageId.haw, "Maianamara" },
				{ LanguageId.he, "מיאנמר (בורמה)" },
				{ LanguageId.hi, "म्यांमार (बर्मा)" },
				{ LanguageId.hr, "Mjanmar (Burma)" },
				{ LanguageId.hsb, "Myanmar" },
				{ LanguageId.hu, "Mianmar" },
				{ LanguageId.hy, "Մյանմա (Բիրմա)" },
				{ LanguageId.ia, "Myanmar (Birmania)" },
				{ LanguageId.ibb, "Myanmar" },
				{ LanguageId.id, "Myanmar (Burma)" },
				{ LanguageId.ig, "Myanmar (Burma)" },
				{ LanguageId.ii, "ꂼꀗꂸ" },
				{ LanguageId.@is, "Mjanmar (Búrma)" },
				{ LanguageId.it, "Myanmar (Birmania)" },
				{ LanguageId.iu, "ᒥᐊᓐᒪᕐ" },
				{ LanguageId.ja, "ミャンマー (ビルマ)" },
				{ LanguageId.jgo, "Myanmar" },
				{ LanguageId.jmc, "Myama" },
				{ LanguageId.jv, "Myanmar (Burma)" },
				{ LanguageId.ka, "მიანმარი (ბირმა)" },
				{ LanguageId.kab, "Myanmar" },
				{ LanguageId.kam, "Myama" },
				{ LanguageId.kde, "Myama" },
				{ LanguageId.kea, "Mianmar (Birmánia)" },
				{ LanguageId.khq, "Maynamar" },
				{ LanguageId.ki, "Myama" },
				{ LanguageId.kk, "Мьянма (Бирма)" },
				{ LanguageId.kkj, "Myanmar" },
				{ LanguageId.kl, "Myanmar" },
				{ LanguageId.kln, "Emetab Myanmar" },
				{ LanguageId.km, "មីយ៉ាន់ម៉ា (ភូមា)" },
				{ LanguageId.kn, "ಮಯನ್ಮಾರ್ (ಬರ್ಮಾ)" },
				{ LanguageId.ko, "미얀마" },
				{ LanguageId.kok, "म्यानमार" },
				{ LanguageId.kr, "Myanmar" },
				{ LanguageId.ks, "میانمار (برما)" },
				{ LanguageId.ksb, "Myama" },
				{ LanguageId.ksf, "myanmár" },
				{ LanguageId.ksh, "Birma" },
				{ LanguageId.kw, "Myanmar" },
				{ LanguageId.ky, "Мьянма (Бирма)" },
				{ LanguageId.la, "Myanmar" },
				{ LanguageId.lag, "Miáama" },
				{ LanguageId.lb, "Myanmar" },
				{ LanguageId.lg, "Myanima" },
				{ LanguageId.lkt, "Myanmar" },
				{ LanguageId.ln, "Birmanie" },
				{ LanguageId.lo, "ມຽນມາ (ເບີມາ)" },
				{ LanguageId.lrc, "میانمار" },
				{ LanguageId.lt, "Mianmaras (Birma)" },
				{ LanguageId.luo, "Myanmar" },
				{ LanguageId.luy, "Myama" },
				{ LanguageId.lv, "Mjanma (Birma)" },
				{ LanguageId.mai, "मयनमार (बर्मा)" },
				{ LanguageId.mas, "Myama" },
				{ LanguageId.mer, "Myanima" },
				{ LanguageId.mfe, "Myanmar" },
				{ LanguageId.mg, "Myanmar" },
				{ LanguageId.mgo, "Myanmar" },
				{ LanguageId.mi, "Pēma" },
				{ LanguageId.mk, "Мјанмар (Бурма)" },
				{ LanguageId.ml, "മ്യാൻമാർ (ബർമ്മ)" },
				{ LanguageId.mn, "Мьянмар" },
				{ LanguageId.mni, "মিয়ানমার" },
				{ LanguageId.moh, "Myanmar" },
				{ LanguageId.mr, "म्यानमार (बर्मा)" },
				{ LanguageId.ms, "Myanmar (Burma)" },
				{ LanguageId.mt, "il-Myanmar/Burma" },
				{ LanguageId.mua, "Sǝr Myanmar" },
				{ LanguageId.my, "မြန်မာ" },
				{ LanguageId.mzn, "میانمار" },
				{ LanguageId.naq, "Myanmar" },
				{ LanguageId.nb, "Myanmar (Burma)" },
				{ LanguageId.nd, "Myanmar" },
				{ LanguageId.nds, "Myanmar" },
				{ LanguageId.ne, "म्यान्मार (बर्मा)" },
				{ LanguageId.nl, "Myanmar (Birma)" },
				{ LanguageId.nmg, "Myanmar" },
				{ LanguageId.nn, "Myanmar (Burma)" },
				{ LanguageId.nnh, "Myanmar" },
				{ LanguageId.nqo, "ߡߌߦߊߡߊ߯ߙ ( ߓߙߌߡߊߣߌ߫ )" },
				{ LanguageId.nr, "Myanmar" },
				{ LanguageId.nso, "Myanmar" },
				{ LanguageId.nus, "Myanmar" },
				{ LanguageId.nyn, "Myanamar" },
				{ LanguageId.oc, "Birmania" },
				{ LanguageId.om, "Maayinaamar (Burma)" },
				{ LanguageId.or, "ମିଆଁମାର" },
				{ LanguageId.os, "Мьянмæ" },
				{ LanguageId.pa, "ਮਿਆਂਮਾਰ (ਬਰਮਾ)" },
				{ LanguageId.pap, "Myanmar" },
				{ LanguageId.pcm, "Miánma (Bọ́ma)" },
				{ LanguageId.pl, "Mjanma (Birma)" },
				{ LanguageId.prg, "Myanmar" },
				{ LanguageId.ps, "ميانمار (برما)" },
				{ LanguageId.pt, "Mianmar (Birmânia)" },
				{ LanguageId.qu, "Myanmar" },
				{ LanguageId.quc, "Myanmar" },
				{ LanguageId.rm, "Myanmar (Burma)" },
				{ LanguageId.rn, "Birimaniya" },
				{ LanguageId.ro, "Myanmar (Birmania)" },
				{ LanguageId.rof, "Myama" },
				{ LanguageId.ru, "Мьянма (Бирма)" },
				{ LanguageId.rw, "Miyanimari" },
				{ LanguageId.rwk, "Myama" },
				{ LanguageId.sa, "म्यान्मार" },
				{ LanguageId.sah, "Мьянма" },
				{ LanguageId.saq, "Myama" },
				{ LanguageId.sat, "ᱢᱤᱭᱟᱱᱢᱟᱨ" },
				{ LanguageId.sbp, "Muyama" },
				{ LanguageId.sd, "ميانمار (برما)" },
				{ LanguageId.se, "Burma" },
				{ LanguageId.seh, "Mianmar" },
				{ LanguageId.ses, "Maynamar" },
				{ LanguageId.sg, "Myämâra" },
				{ LanguageId.shi, "ⵎⵢⴰⵏⵎⴰⵔ" },
				{ LanguageId.si, "මියන්මාරය (බුරුමය)" },
				{ LanguageId.sk, "Mjanmarsko" },
				{ LanguageId.sl, "Mjanmar (Burma)" },
				{ LanguageId.sma, "Myanmar" },
				{ LanguageId.smj, "Myanmar" },
				{ LanguageId.smn, "Myanmar (Burma)" },
				{ LanguageId.sms, "Myanmar" },
				{ LanguageId.sn, "Myanmar" },
				{ LanguageId.so, "Mayanmar" },
				{ LanguageId.sq, "Mianmar (Burmë)" },
				{ LanguageId.sr, "Мијанмар (Бурма)" },
				{ LanguageId.ss, "Myanmar" },
				{ LanguageId.ssy, "Myanmar" },
				{ LanguageId.st, "Myanmar" },
				{ LanguageId.su, "Myanmar" },
				{ LanguageId.sv, "Myanmar (Burma)" },
				{ LanguageId.sw, "Myanmar (Burma)" },
				{ LanguageId.syr, "ܡܝܐܢܡܐܪ (ܒܘܪܡܐ)" },
				{ LanguageId.ta, "மியான்மர் (பர்மா)" },
				{ LanguageId.te, "మయన్మార్" },
				{ LanguageId.teo, "Myama" },
				{ LanguageId.tg, "Мянма" },
				{ LanguageId.th, "เมียนมา (พม่า)" },
				{ LanguageId.ti, "ሚያንማር (በርማ)" },
				{ LanguageId.tig, "Myanmar" },
				{ LanguageId.tk, "Mýanma (Birma)" },
				{ LanguageId.tn, "Myanmar" },
				{ LanguageId.to, "Mianimā (Pema)" },
				{ LanguageId.tr, "Myanmar (Burma)" },
				{ LanguageId.ts, "Myanmar" },
				{ LanguageId.tt, "Мьянма (Бирма)" },
				{ LanguageId.twq, "Maynamar" },
				{ LanguageId.tzm, "Myanmar" },
				{ LanguageId.ug, "بىرما" },
				{ LanguageId.uk, "Мʼянма (Бірма)" },
				{ LanguageId.ur, "میانمار (برما)" },
				{ LanguageId.uz, "Myanma (Birma)" },
				{ LanguageId.vai, "ꕆꕩꘋꕮ" },
				{ LanguageId.ve, "Myanmar" },
				{ LanguageId.vi, "Myanmar (Miến Điện)" },
				{ LanguageId.vo, "Mianmarän" },
				{ LanguageId.vun, "Myama" },
				{ LanguageId.wae, "Burma" },
				{ LanguageId.wal, "Myanmar" },
				{ LanguageId.wo, "Miyanmaar" },
				{ LanguageId.xh, "EMyanmar (Burma)" },
				{ LanguageId.xog, "Myanima" },
				{ LanguageId.yav, "miaŋmáal" },
				{ LanguageId.yi, "מיאַנמאַר" },
				{ LanguageId.yo, "Manamari" },
				{ LanguageId.zgh, "ⵎⵢⴰⵏⵎⴰⵔ" },
				{ LanguageId.zh, "缅甸" },
				{ LanguageId.zu, "i-Myanmar (Burma)" },
			}
		);
	}
}
