// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MO
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "853",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Macao" },
				{ LanguageId.da, "SAR Macao" },
				{ LanguageId.af, "Macau SAS China" },
				{ LanguageId.agq, "Macao" },
				{ LanguageId.ak, "Makaw Kyaena" },
				{ LanguageId.am, "ማካኦ ልዩ የአስተዳደር ክልል ቻይና" },
				{ LanguageId.ar, "منطقة ماكاو الإدارية الخاصة" },
				{ LanguageId.arn, "Macao" },
				{ LanguageId.@as, "মাকাও এছ. এ. আৰ. চীন" },
				{ LanguageId.asa, "Macao" },
				{ LanguageId.ast, "ARE China de Macáu" },
				{ LanguageId.az, "Makao XİR Çin" },
				{ LanguageId.ba, "Макао, Ҡытай МАР-ы" },
				{ LanguageId.bas, "Macao" },
				{ LanguageId.be, "Макаа, САР (Кітай)" },
				{ LanguageId.bem, "Macao" },
				{ LanguageId.bez, "Macao" },
				{ LanguageId.bg, "Макао, САР на Китай" },
				{ LanguageId.bin, "Macao" },
				{ LanguageId.bm, "Macao" },
				{ LanguageId.bn, "ম্যাকাও এসএআর চীন" },
				{ LanguageId.bo, "མ་ཁའོ།" },
				{ LanguageId.br, "Makao RMD Sina" },
				{ LanguageId.brx, "माकाउ एस.ए.आर चाइना" },
				{ LanguageId.bs, "Makao (SAR Kina)" },
				{ LanguageId.byn, "Macao" },
				{ LanguageId.ca, "Macau (RAE Xina)" },
				{ LanguageId.ccp, "𑄟𑄳𑄠𑄇𑄃𑄮 𑄆𑄌𑄴𑄃𑄬𑄃𑄢𑄴 𑄌𑄩𑄚" },
				{ LanguageId.ce, "Макао (ша-къаьстина кӀошт)" },
				{ LanguageId.ceb, "Macao SAR China" },
				{ LanguageId.cgg, "Macao" },
				{ LanguageId.chr, "ᎹᎧᎣ (ᎤᏓᏤᎵᏓ ᏧᏂᎸᏫᏍᏓᏁᏗ ᎢᎬᎾᏕᎾ) ᏣᎢ" },
				{ LanguageId.ckb, "ماکائۆ" },
				{ LanguageId.co, "Macao" },
				{ LanguageId.cs, "Macao – ZAO Číny" },
				{ LanguageId.cu, "Макао" },
				{ LanguageId.cy, "Macau SAR Tsieina" },
				{ LanguageId.dav, "Macao" },
				{ LanguageId.de, "Sonderverwaltungsregion Macau" },
				{ LanguageId.dje, "Macao" },
				{ LanguageId.doi, "मकाओ" },
				{ LanguageId.dsb, "Wósebna zastojnstwowa cona Macao" },
				{ LanguageId.dua, "Macao" },
				{ LanguageId.dv, "މަކާއޫ" },
				{ LanguageId.dz, "མཀ་ཨའུ་ཅཱའི་ན" },
				{ LanguageId.ebu, "Macao" },
				{ LanguageId.ee, "Macau SAR Tsaina nutome" },
				{ LanguageId.el, "Μακάο ΕΔΠ Κίνας" },
				{ LanguageId.en, "Macao SAR China" },
				{ LanguageId.eo, "Makao (SAR de Ĉinujo)" },
				{ LanguageId.es, "RAE de Macao (China)" },
				{ LanguageId.et, "Macau erihalduspiirkond" },
				{ LanguageId.eu, "Macau Txinako AEB" },
				{ LanguageId.ewo, "Macao" },
				{ LanguageId.fa, "ماکائو، منطقهٔ ویژهٔ اداری چین" },
				{ LanguageId.ff, "Macao" },
				{ LanguageId.fi, "Macao – Kiinan erityishallintoalue" },
				{ LanguageId.fil, "Macau SAR China" },
				{ LanguageId.fo, "Makao SAR Kina" },
				{ LanguageId.fr, "R.A.S. chinoise de Macao" },
				{ LanguageId.fur, "Regjon aministrative speciâl de Cine di Macao" },
				{ LanguageId.fy, "Macao SAR van Sina" },
				{ LanguageId.ga, "Sainréigiún Riaracháin Macao, Daonphoblacht na Síne" },
				{ LanguageId.gd, "Macàthu SAR na Sìne" },
				{ LanguageId.gl, "Macau RAE da China" },
				{ LanguageId.gn, "Macao" },
				{ LanguageId.gsw, "Sonderverwaltigszone Macao" },
				{ LanguageId.gu, "મકાઉ SAR ચીન" },
				{ LanguageId.guz, "Macao" },
				{ LanguageId.gv, "Macau" },
				{ LanguageId.ha, "Babban Yankin Mulkin Macao na Ƙasar Sin" },
				{ LanguageId.haw, "Makao" },
				{ LanguageId.he, "מקאו (אזור מנהלי מיוחד של סין)" },
				{ LanguageId.hi, "मकाऊ (विशेष प्रशासनिक क्षेत्र चीन)" },
				{ LanguageId.hr, "PUP Makao Kina" },
				{ LanguageId.hsb, "Wosebita zarjadniska cona Macao" },
				{ LanguageId.hu, "Makaó KKT" },
				{ LanguageId.hy, "Չինաստանի Մակաո ՀՎՇ" },
				{ LanguageId.ia, "Macao, R.A.S. de China" },
				{ LanguageId.ibb, "Macao" },
				{ LanguageId.id, "Makau DAK Tiongkok" },
				{ LanguageId.ig, "Macao SAR China" },
				{ LanguageId.ii, "ꀠꇭ" },
				{ LanguageId.@is, "sérstjórnarsvæðið Makaó" },
				{ LanguageId.it, "RAS di Macao" },
				{ LanguageId.iu, "ᒫᑲᐅ" },
				{ LanguageId.ja, "中華人民共和国マカオ特別行政区" },
				{ LanguageId.jgo, "Macao" },
				{ LanguageId.jmc, "Macao" },
				{ LanguageId.jv, "Laladan Administratif Astamiwa Makau" },
				{ LanguageId.ka, "მაკაოს სპეციალური ადმინისტრაციული რეგიონი, ჩინეთი" },
				{ LanguageId.kab, "Makaw" },
				{ LanguageId.kam, "Macao" },
				{ LanguageId.kde, "Macao" },
				{ LanguageId.kea, "Makau, Rejion Administrativu Spesial di Xina" },
				{ LanguageId.khq, "Macao" },
				{ LanguageId.ki, "Macao" },
				{ LanguageId.kk, "Макао АӘА" },
				{ LanguageId.kkj, "Macao" },
				{ LanguageId.kl, "Makau" },
				{ LanguageId.kln, "Macao" },
				{ LanguageId.km, "ម៉ាកាវ តំបន់រដ្ឋបាលពិសេសចិន" },
				{ LanguageId.kn, "ಮಕಾವು ಎಸ್ಎಆರ್ ಚೈನಾ" },
				{ LanguageId.ko, "마카오(중국 특별행정구)" },
				{ LanguageId.kok, "मकाव" },
				{ LanguageId.kr, "Macao" },
				{ LanguageId.ks, "مَکاوو ایس اے آر چیٖن" },
				{ LanguageId.ksb, "Macao" },
				{ LanguageId.ksf, "Macao" },
				{ LanguageId.ksh, "Makau" },
				{ LanguageId.kw, "Makao" },
				{ LanguageId.ky, "Макао Кытай ААА" },
				{ LanguageId.la, "Macao" },
				{ LanguageId.lag, "Macao" },
				{ LanguageId.lb, "Spezialverwaltungszon Macau" },
				{ LanguageId.lg, "Macao" },
				{ LanguageId.lkt, "Macao" },
				{ LanguageId.ln, "Macao" },
				{ LanguageId.lo, "ມາກາວ ເຂດປົກຄອງພິເສດ ຈີນ" },
				{ LanguageId.lrc, "ماکائو" },
				{ LanguageId.lt, "Ypatingasis Administracinis Kinijos Regionas Makao" },
				{ LanguageId.luo, "Macao" },
				{ LanguageId.luy, "Macao" },
				{ LanguageId.lv, "ĶTR īpašais administratīvais reģions Makao" },
				{ LanguageId.mai, "मकाउ (विशेष प्रशासनिक क्षेत्र चीन)" },
				{ LanguageId.mas, "Macao" },
				{ LanguageId.mer, "Macao" },
				{ LanguageId.mfe, "Macao" },
				{ LanguageId.mg, "Macao" },
				{ LanguageId.mgo, "Macao" },
				{ LanguageId.mi, "Makau Haina" },
				{ LanguageId.mk, "Макао САР" },
				{ LanguageId.ml, "മക്കാവു എസ്.എ.ആർ. ചൈന" },
				{ LanguageId.mn, "БНХАУ-ын Тусгай захиргааны бүс Макао" },
				{ LanguageId.mni, "মাকাও" },
				{ LanguageId.moh, "Macao" },
				{ LanguageId.mr, "मकाओ एसएआर चीन" },
				{ LanguageId.ms, "Macau SAR China" },
				{ LanguageId.mt, "ir-Reġjun Amministrattiv Speċjali tal-Macao tar-Repubblika tal-Poplu taċ-Ċina" },
				{ LanguageId.mua, "Macao" },
				{ LanguageId.my, "မကာအို (တရုတ်ပြည်)" },
				{ LanguageId.mzn, "ماکائو (چین دله)" },
				{ LanguageId.naq, "Macao" },
				{ LanguageId.nb, "Macao SAR Kina" },
				{ LanguageId.nd, "Macao" },
				{ LanguageId.nds, "Macao" },
				{ LanguageId.ne, "मकाउ चिनियाँ विशेष प्रशासनिक क्षेत्र" },
				{ LanguageId.nl, "Macau SAR van China" },
				{ LanguageId.nmg, "Macao" },
				{ LanguageId.nn, "Macao SAR Kina" },
				{ LanguageId.nnh, "Macao" },
				{ LanguageId.nqo, "ߛߌߣ ߕߌ߲߬ߞߎߘߎ߲߫ ߡߊߡߙߊ߬ߣߍ߲ ߡߞߊߥߏ߫" },
				{ LanguageId.nr, "Macao" },
				{ LanguageId.nso, "Macao" },
				{ LanguageId.nus, "Macao" },
				{ LanguageId.nyn, "Macao" },
				{ LanguageId.oc, "Macau" },
				{ LanguageId.om, "Maka’oo SAR Chaayinaa" },
				{ LanguageId.or, "ମାକାଉ ଏସଏଆର୍‌ ଚାଇନା" },
				{ LanguageId.os, "Макао" },
				{ LanguageId.pa, "ਮਕਾਉ ਐਸਏਆਰ ਚੀਨ" },
				{ LanguageId.pap, "Makau" },
				{ LanguageId.pcm, "Makáo SAR Chaína" },
				{ LanguageId.pl, "SRA Makau (Chiny)" },
				{ LanguageId.prg, "Makao" },
				{ LanguageId.ps, "مکاو SAR چین" },
				{ LanguageId.pt, "Macau, RAE da China" },
				{ LanguageId.qu, "Macao RAE China" },
				{ LanguageId.quc, "Macao" },
				{ LanguageId.rm, "Regiun d’administraziun speziala Macao, China" },
				{ LanguageId.rn, "Macao" },
				{ LanguageId.ro, "R.A.S. Macao, China" },
				{ LanguageId.rof, "Macao" },
				{ LanguageId.ru, "Макао (САР)" },
				{ LanguageId.rw, "Makao" },
				{ LanguageId.rwk, "Macao" },
				{ LanguageId.sa, "मकाओ" },
				{ LanguageId.sah, "Макао" },
				{ LanguageId.saq, "Macao" },
				{ LanguageId.sat, "ᱢᱟᱠᱟᱶ" },
				{ LanguageId.sbp, "Macao" },
				{ LanguageId.sd, "مڪائو SAR چين" },
				{ LanguageId.se, "Makáo" },
				{ LanguageId.seh, "Macao" },
				{ LanguageId.ses, "Macao" },
				{ LanguageId.sg, "Macao" },
				{ LanguageId.shi, "ⵎⴰⴽⴰⵡ" },
				{ LanguageId.si, "මැකාවු විශේෂ පරිපාලන කලාපය චීනය" },
				{ LanguageId.sk, "Macao – OAO Číny" },
				{ LanguageId.sl, "Posebno upravno območje Kitajske Makav" },
				{ LanguageId.sma, "Macao" },
				{ LanguageId.smj, "Macao" },
				{ LanguageId.smn, "Macao - – Kiina e.h.k." },
				{ LanguageId.sms, "Macao" },
				{ LanguageId.sn, "Macao" },
				{ LanguageId.so, "Makaaw" },
				{ LanguageId.sq, "RPA i Makaos" },
				{ LanguageId.sr, "САР Макао (Кина)" },
				{ LanguageId.ss, "Macao" },
				{ LanguageId.ssy, "Macao" },
				{ LanguageId.st, "Macao" },
				{ LanguageId.su, "Macao" },
				{ LanguageId.sv, "Macao SAR" },
				{ LanguageId.sw, "Makau SAR China" },
				{ LanguageId.syr, "ܐܬܪܐ ܡܕܒܪܢܝܐ ܦܪܝܫܐ ܕܡܐܟܐܘ" },
				{ LanguageId.ta, "மகாவ் எஸ்ஏஆர் சீனா" },
				{ LanguageId.te, "మకావ్ SAR చైనా" },
				{ LanguageId.teo, "Macao" },
				{ LanguageId.tg, "Макао (МММ)" },
				{ LanguageId.th, "เขตปกครองพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน" },
				{ LanguageId.ti, "ፍሉይ ምምሕዳራዊ ዞባ ማካው (ቻይና)" },
				{ LanguageId.tig, "ማካው" },
				{ LanguageId.tk, "Makao AAS Hytaý" },
				{ LanguageId.tn, "Macao" },
				{ LanguageId.to, "Makau SAR Siaina" },
				{ LanguageId.tr, "Çin Makao ÖİB" },
				{ LanguageId.ts, "Macao" },
				{ LanguageId.tt, "Макао Махсус Идарәле Төбәге" },
				{ LanguageId.twq, "Macao" },
				{ LanguageId.tzm, "ⵎⴰⴽⴰⵡ" },
				{ LanguageId.ug, "ئاۋمېن ئالاھىدە مەمۇرىي رايونى" },
				{ LanguageId.uk, "Макао, ОАР Китаю" },
				{ LanguageId.ur, "مکاؤ SAR چین" },
				{ LanguageId.uz, "Makao (Xitoy MMH)" },
				{ LanguageId.vai, "ꕮꗛꖺ" },
				{ LanguageId.ve, "Macao" },
				{ LanguageId.vi, "Đặc khu Hành chính Macao, Trung Quốc" },
				{ LanguageId.vo, "Makao" },
				{ LanguageId.vun, "Macao" },
				{ LanguageId.wae, "Sonderverwaltigszona Makau" },
				{ LanguageId.wal, "Macao" },
				{ LanguageId.wo, "Makaawo" },
				{ LanguageId.xh, "EMacao SAR China" },
				{ LanguageId.xog, "Macao" },
				{ LanguageId.yav, "Macao" },
				{ LanguageId.yi, "מאַקאַו" },
				{ LanguageId.yo, "Agbègbè Ìṣàkóso Pàtàkì Macao" },
				{ LanguageId.zgh, "ⵎⴰⴽⴰⵡ" },
				{ LanguageId.zh, "中国澳门特别行政区" },
				{ LanguageId.zu, "i-Macau SAR China" },
			}
		);
	}
}
