// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MU
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "230",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Mauritius" },
				{ LanguageId.af, "Mauritius" },
				{ LanguageId.agq, "Mùleshwɨ̀s" },
				{ LanguageId.ak, "Mɔrehyeɔs" },
				{ LanguageId.am, "ሞሪሸስ" },
				{ LanguageId.ar, "موريشيوس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মৰিছাছ" },
				{ LanguageId.asa, "Morithi" },
				{ LanguageId.ast, "Mauriciu" },
				{ LanguageId.az, "Mavriki" },
				{ LanguageId.ba, "Маврикий" },
				{ LanguageId.bas, "Mòrîs" },
				{ LanguageId.be, "Маўрыкій" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Humolisi" },
				{ LanguageId.bg, "Мавриций" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Morisi" },
				{ LanguageId.bn, "মরিশাস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Moris" },
				{ LanguageId.brx, "मरिसियास" },
				{ LanguageId.bs, "Mauricijus" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Maurici" },
				{ LanguageId.ccp, "𑄟𑄧𑄢𑄨𑄥𑄥𑄴" },
				{ LanguageId.ce, "Маврики" },
				{ LanguageId.ceb, "Mauritius" },
				{ LanguageId.cgg, "Maurishiasi" },
				{ LanguageId.chr, "ᎼᎵᏏᎥᏍ" },
				{ LanguageId.ckb, "مووریتیووس" },
				{ LanguageId.co, "Mauritius" },
				{ LanguageId.cs, "Mauricius" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Mauritius" },
				{ LanguageId.dav, "Morisi" },
				{ LanguageId.de, "Mauritius" },
				{ LanguageId.dje, "Mooris gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Mauritius" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "མོ་རི་ཤཱས" },
				{ LanguageId.ebu, "Morisi" },
				{ LanguageId.ee, "mauritiusdukɔ" },
				{ LanguageId.el, "Μαυρίκιος" },
				{ LanguageId.en, "Mauritius" },
				{ LanguageId.eo, "Maŭricio" },
				{ LanguageId.es, "Mauricio" },
				{ LanguageId.et, "Mauritius" },
				{ LanguageId.eu, "Maurizio" },
				{ LanguageId.ewo, "Morís" },
				{ LanguageId.fa, "موریس" },
				{ LanguageId.ff, "Moriis" },
				{ LanguageId.fi, "Mauritius" },
				{ LanguageId.fil, "Mauritius" },
				{ LanguageId.fo, "Móritius" },
				{ LanguageId.fr, "Maurice" },
				{ LanguageId.fur, "Maurizi" },
				{ LanguageId.fy, "Mauritius" },
				{ LanguageId.ga, "Oileán Mhuirís" },
				{ LanguageId.gd, "Na h-Eileanan Mhoiriseas" },
				{ LanguageId.gl, "Mauricio" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Mauriizius" },
				{ LanguageId.gu, "મોરિશિયસ" },
				{ LanguageId.guz, "Morisi" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Moritus" },
				{ LanguageId.haw, "Mauritiusa" },
				{ LanguageId.he, "מאוריציוס" },
				{ LanguageId.hi, "मॉरीशस" },
				{ LanguageId.hr, "Mauricijus" },
				{ LanguageId.hsb, "Mauritius" },
				{ LanguageId.hu, "Mauritius" },
				{ LanguageId.hy, "Մավրիկիոս" },
				{ LanguageId.ia, "Mauritio" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Mauritius" },
				{ LanguageId.ig, "Mauritius" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Máritíus" },
				{ LanguageId.it, "Mauritius" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "モーリシャス" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Morisi" },
				{ LanguageId.jv, "Mauritius" },
				{ LanguageId.ka, "მავრიკი" },
				{ LanguageId.kab, "Muris" },
				{ LanguageId.kam, "Morisi" },
				{ LanguageId.kde, "Molisi" },
				{ LanguageId.kea, "Maurísia" },
				{ LanguageId.khq, "Mooris gungey" },
				{ LanguageId.ki, "Morisi" },
				{ LanguageId.kk, "Маврикий" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Mauritius" },
				{ LanguageId.km, "ម៉ូរីស" },
				{ LanguageId.kn, "ಮಾರಿಷಸ್" },
				{ LanguageId.ko, "모리셔스" },
				{ LanguageId.kok, "मॉरिशस" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مورِشَس" },
				{ LanguageId.ksb, "Molisi" },
				{ LanguageId.ksf, "mwarís" },
				{ LanguageId.ksh, "Maurizijus" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Маврикий" },
				{ LanguageId.la, "Mauritius" },
				{ LanguageId.lag, "Moríisi" },
				{ LanguageId.lb, "Mauritius" },
				{ LanguageId.lg, "Mawulisyasi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Morisɛ" },
				{ LanguageId.lo, "ມົວຣິຊຽສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Mauricijus" },
				{ LanguageId.luo, "Mauritius" },
				{ LanguageId.luy, "Morisi" },
				{ LanguageId.lv, "Maurīcija" },
				{ LanguageId.mai, "मारीशस" },
				{ LanguageId.mas, "Morisi" },
				{ LanguageId.mer, "Maurĩtiasi" },
				{ LanguageId.mfe, "Moris" },
				{ LanguageId.mg, "Maorisy" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Marihi" },
				{ LanguageId.mk, "Маврициус" },
				{ LanguageId.ml, "മൗറീഷ്യസ്" },
				{ LanguageId.mn, "Маврикий" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मॉरिशस" },
				{ LanguageId.ms, "Mauritius" },
				{ LanguageId.mt, "Mauritius" },
				{ LanguageId.mua, "Sǝr Mauricǝ" },
				{ LanguageId.my, "မောရစ်ရှ" },
				{ LanguageId.mzn, "مورى تيوس" },
				{ LanguageId.naq, "Mauritius" },
				{ LanguageId.nb, "Mauritius" },
				{ LanguageId.nd, "Mauritius" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "मौरिसियस" },
				{ LanguageId.nl, "Mauritius" },
				{ LanguageId.nmg, "Morisse" },
				{ LanguageId.nn, "Mauritius" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߏߙߌߛ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Maurishiasi" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Moorishiyees" },
				{ LanguageId.or, "ମରିସସ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮੌਰੀਸ਼ਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Mọríshọs" },
				{ LanguageId.pl, "Mauritius" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "موریشیس" },
				{ LanguageId.pt, "Maurício" },
				{ LanguageId.qu, "Mauricio" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Mauritius" },
				{ LanguageId.rn, "Izinga rya Morise" },
				{ LanguageId.ro, "Mauritius" },
				{ LanguageId.rof, "Morisi" },
				{ LanguageId.ru, "Маврикий" },
				{ LanguageId.rw, "Maurice" },
				{ LanguageId.rwk, "Morisi" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Morisi" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Molisi" },
				{ LanguageId.sd, "موريشس" },
				{ LanguageId.se, "Mauritius" },
				{ LanguageId.seh, "Maurício" },
				{ LanguageId.ses, "Mooris gungey" },
				{ LanguageId.sg, "Mörîsi" },
				{ LanguageId.shi, "ⵎⵓⵔⵉⵙ" },
				{ LanguageId.si, "මුරුසිය" },
				{ LanguageId.sk, "Maurícius" },
				{ LanguageId.sl, "Mavricij" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Mauritius" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Mauritius" },
				{ LanguageId.so, "Mawrishiyaas" },
				{ LanguageId.sq, "Mauritius" },
				{ LanguageId.sr, "Маурицијус" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Mauritius" },
				{ LanguageId.su, "Mauritius" },
				{ LanguageId.sv, "Mauritius" },
				{ LanguageId.sw, "Morisi" },
				{ LanguageId.syr, "ܡܘܪܝܛܝܘܣ" },
				{ LanguageId.ta, "மொரிசியஸ்" },
				{ LanguageId.te, "మారిషస్" },
				{ LanguageId.teo, "Morisi" },
				{ LanguageId.tg, "Маврикий" },
				{ LanguageId.th, "มอริเชียส" },
				{ LanguageId.ti, "ማውሪሸስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Mawrikiý" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Maulitiusi" },
				{ LanguageId.tr, "Mauritius" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Маврикий" },
				{ LanguageId.twq, "Mooris gungey" },
				{ LanguageId.tzm, "Muris" },
				{ LanguageId.ug, "ماۋرىتىيۇس" },
				{ LanguageId.uk, "Маврикій" },
				{ LanguageId.ur, "ماریشس" },
				{ LanguageId.uz, "Mavrikiy" },
				{ LanguageId.vai, "ꗞꔓꗔ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Mauritius" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Morisi" },
				{ LanguageId.wae, "Mauritius" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Moriis" },
				{ LanguageId.xh, "EMauritius" },
				{ LanguageId.xog, "Mawulisyasi" },
				{ LanguageId.yav, "molís" },
				{ LanguageId.yi, "מאריציוס" },
				{ LanguageId.yo, "Maritiusi" },
				{ LanguageId.zgh, "ⵎⵓⵔⵉⵙ" },
				{ LanguageId.zh, "毛里求斯" },
				{ LanguageId.zu, "i-Mauritius" },
			}
		);
	}
}
