// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class MV
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "960",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Maldiverne" },
				{ LanguageId.af, "Maledive" },
				{ LanguageId.agq, "Màdivè" },
				{ LanguageId.ak, "Maldives" },
				{ LanguageId.am, "ማልዲቭስ" },
				{ LanguageId.ar, "جزر المالديف" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মালদ্বীপ" },
				{ LanguageId.asa, "Modivu" },
				{ LanguageId.ast, "Les Maldives" },
				{ LanguageId.az, "Maldiv adaları" },
				{ LanguageId.ba, "Мальдив утрауҙары" },
				{ LanguageId.bas, "Màldîf" },
				{ LanguageId.be, "Мальдывы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Humodivu" },
				{ LanguageId.bg, "Малдиви" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Maldivi" },
				{ LanguageId.bn, "মালদ্বীপ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Maldivez" },
				{ LanguageId.brx, "मालदीव" },
				{ LanguageId.bs, "Maldivi" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Maldives" },
				{ LanguageId.ccp, "𑄟𑄣𑄴𑄘𑄨𑄛𑄴" },
				{ LanguageId.ce, "Мальдиваш" },
				{ LanguageId.ceb, "Maldives" },
				{ LanguageId.cgg, "Maridives" },
				{ LanguageId.chr, "ᎹᎵᏗᏫᏍ" },
				{ LanguageId.ckb, "مالدیڤ" },
				{ LanguageId.co, "Maldive" },
				{ LanguageId.cs, "Maledivy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Maldives" },
				{ LanguageId.dav, "Modivu" },
				{ LanguageId.de, "Malediven" },
				{ LanguageId.dje, "Maldiivu" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Malediwy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "ދިވެހިރާއްޖޭގެ" },
				{ LanguageId.dz, "མཱལ་དིབས" },
				{ LanguageId.ebu, "Modivu" },
				{ LanguageId.ee, "maldivesdukɔ" },
				{ LanguageId.el, "Μαλδίβες" },
				{ LanguageId.en, "Maldives" },
				{ LanguageId.eo, "Maldivoj" },
				{ LanguageId.es, "Maldivas" },
				{ LanguageId.et, "Maldiivid" },
				{ LanguageId.eu, "Maldivak" },
				{ LanguageId.ewo, "Malədívə" },
				{ LanguageId.fa, "مالدیو" },
				{ LanguageId.ff, "Maldiiwe" },
				{ LanguageId.fi, "Malediivit" },
				{ LanguageId.fil, "Maldives" },
				{ LanguageId.fo, "Maldivoyggjar" },
				{ LanguageId.fr, "Maldives" },
				{ LanguageId.fur, "Maldivis" },
				{ LanguageId.fy, "Maldiven" },
				{ LanguageId.ga, "Oileáin Mhaildíve" },
				{ LanguageId.gd, "Na h-Eileanan Mhaladaibh" },
				{ LanguageId.gl, "Maldivas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Malediiwe" },
				{ LanguageId.gu, "માલદિવ્સ" },
				{ LanguageId.guz, "Modivu" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Maldibi" },
				{ LanguageId.haw, "Maladiwa" },
				{ LanguageId.he, "האיים המלדיביים" },
				{ LanguageId.hi, "मालदीव" },
				{ LanguageId.hr, "Maldivi" },
				{ LanguageId.hsb, "Malediwy" },
				{ LanguageId.hu, "Maldív-szigetek" },
				{ LanguageId.hy, "Մալդիվներ" },
				{ LanguageId.ia, "Maldivas" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Maladewa" },
				{ LanguageId.ig, "Maldivesa" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Maldíveyjar" },
				{ LanguageId.it, "Maldive" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "モルディブ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Modivu" },
				{ LanguageId.jv, "Maladéwa" },
				{ LanguageId.ka, "მალდივები" },
				{ LanguageId.kab, "Maldib" },
				{ LanguageId.kam, "Modivu" },
				{ LanguageId.kde, "Modivu" },
				{ LanguageId.kea, "Maldivas" },
				{ LanguageId.khq, "Maldiivu" },
				{ LanguageId.ki, "Modivu" },
				{ LanguageId.kk, "Мальдив аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Maldives" },
				{ LanguageId.km, "ម៉ាល់ឌីវ" },
				{ LanguageId.kn, "ಮಾಲ್ಡೀವ್ಸ್" },
				{ LanguageId.ko, "몰디브" },
				{ LanguageId.kok, "मालदीव" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "مالدیٖو" },
				{ LanguageId.ksb, "Modivu" },
				{ LanguageId.ksf, "maldivǝ" },
				{ LanguageId.ksh, "Mallediive" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Мальдив" },
				{ LanguageId.la, "Maldivae" },
				{ LanguageId.lag, "Modíivu" },
				{ LanguageId.lb, "Maldiven" },
				{ LanguageId.lg, "Bizinga by’eMalidive" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Madívɛ" },
				{ LanguageId.lo, "ມັນດິຟ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Maldyvai" },
				{ LanguageId.luo, "Maldives" },
				{ LanguageId.luy, "Modivu" },
				{ LanguageId.lv, "Maldīvija" },
				{ LanguageId.mai, "मालदीब" },
				{ LanguageId.mas, "Modivu" },
				{ LanguageId.mer, "Modivu" },
				{ LanguageId.mfe, "Maldiv" },
				{ LanguageId.mg, "Maldiva" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Māratiri" },
				{ LanguageId.mk, "Малдиви" },
				{ LanguageId.ml, "മാലിദ്വീപ്" },
				{ LanguageId.mn, "Мальдив" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "मालदीव" },
				{ LanguageId.ms, "Maldives" },
				{ LanguageId.mt, "il-Maldivi" },
				{ LanguageId.mua, "Maldivǝ" },
				{ LanguageId.my, "မော်လ်ဒိုက်" },
				{ LanguageId.mzn, "مالدیو" },
				{ LanguageId.naq, "Maldives" },
				{ LanguageId.nb, "Maldivene" },
				{ LanguageId.nd, "Maldives" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "माल्दिभ्स" },
				{ LanguageId.nl, "Maldiven" },
				{ LanguageId.nmg, "Maldivia" },
				{ LanguageId.nn, "Maldivane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߊߟߑߘߌߝ߭" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Maridives" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Maaldiivs" },
				{ LanguageId.or, "ମାଲଦିଭସ୍‌" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਮਾਲਦੀਵ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Mọ́ldivs" },
				{ LanguageId.pl, "Malediwy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "مالديپ" },
				{ LanguageId.pt, "Maldivas" },
				{ LanguageId.qu, "Maldivas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Maledivas" },
				{ LanguageId.rn, "Moludave" },
				{ LanguageId.ro, "Maldive" },
				{ LanguageId.rof, "Modivu" },
				{ LanguageId.ru, "Мальдивы" },
				{ LanguageId.rw, "Malidiya" },
				{ LanguageId.rwk, "Modivu" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Modivu" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Modivu" },
				{ LanguageId.sd, "مالديپ" },
				{ LanguageId.se, "Malediivvat" },
				{ LanguageId.seh, "Maldivas" },
				{ LanguageId.ses, "Maldiivu" },
				{ LanguageId.sg, "Maldîva" },
				{ LanguageId.shi, "ⵎⴰⵍⴷⵉⴼ" },
				{ LanguageId.si, "මාල දිවයින" },
				{ LanguageId.sk, "Maldivy" },
				{ LanguageId.sl, "Maldivi" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Malediveh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Maldives" },
				{ LanguageId.so, "Maaldiifis" },
				{ LanguageId.sq, "Maldive" },
				{ LanguageId.sr, "Малдиви" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Maldives" },
				{ LanguageId.su, "Maladéwa" },
				{ LanguageId.sv, "Maldiverna" },
				{ LanguageId.sw, "Maldivi" },
				{ LanguageId.syr, "ܓܙܪܬܐ ܡܐܠܕܝܒܝܬܐ" },
				{ LanguageId.ta, "மாலத்தீவு" },
				{ LanguageId.te, "మాల్దీవులు" },
				{ LanguageId.teo, "Modivu" },
				{ LanguageId.tg, "Малдив" },
				{ LanguageId.th, "มัลดีฟส์" },
				{ LanguageId.ti, "ማልዲቭስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Maldiwler" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Malativisi" },
				{ LanguageId.tr, "Maldivler" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Мальдив утраулары" },
				{ LanguageId.twq, "Maldiivu" },
				{ LanguageId.tzm, "Maldiv" },
				{ LanguageId.ug, "مالدىۋې" },
				{ LanguageId.uk, "Мальдіви" },
				{ LanguageId.ur, "مالدیپ" },
				{ LanguageId.uz, "Maldiv orollari" },
				{ LanguageId.vai, "ꕮꔷꕜꔍ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Maldives" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Modivu" },
				{ LanguageId.wae, "Malediwe" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Maldiiw" },
				{ LanguageId.xh, "EMaldives" },
				{ LanguageId.xog, "Ebizinga bya Malidive" },
				{ LanguageId.yav, "maletíif" },
				{ LanguageId.yi, "מאַלדיוון" },
				{ LanguageId.yo, "Maladifi" },
				{ LanguageId.zgh, "ⵎⴰⵍⴷⵉⴼ" },
				{ LanguageId.zh, "马尔代夫" },
				{ LanguageId.zu, "i-Maldives" },
			}
		);
	}
}
