// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class NC
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "687",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Ny Kaledonien" },
				{ LanguageId.af, "Nieu-Kaledonië" },
				{ LanguageId.agq, "Kàlèdonyìa È fūghū" },
				{ LanguageId.ak, "Kaledonia Foforo" },
				{ LanguageId.am, "ኒው ካሌዶኒያ" },
				{ LanguageId.ar, "كاليدونيا الجديدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "নিউ কেলিডোনিয়া" },
				{ LanguageId.asa, "Nyukaledonia" },
				{ LanguageId.ast, "Nueva Caledonia" },
				{ LanguageId.az, "Yeni Kaledoniya" },
				{ LanguageId.ba, "Яңы Каледония" },
				{ LanguageId.bas, "Kàlèdonìà Yɔ̀ndɔ" },
				{ LanguageId.be, "Новая Каледонія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hunyukaledonia" },
				{ LanguageId.bg, "Нова Каледония" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kaledoni Koura" },
				{ LanguageId.bn, "নিউ ক্যালেডোনিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Kaledonia-Nevez" },
				{ LanguageId.brx, "निउ केलेडनिया" },
				{ LanguageId.bs, "Nova Kaledonija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Nova Caledònia" },
				{ LanguageId.ccp, "𑄚𑄱 𑄇𑄳𑄠𑄣𑄬𑄓𑄮𑄚𑄨𑄠" },
				{ LanguageId.ce, "Керла Каледони" },
				{ LanguageId.ceb, "New Caledonia" },
				{ LanguageId.cgg, "Niukaredonia" },
				{ LanguageId.chr, "ᎢᏤ ᎧᎵᏙᏂᎠᏂ" },
				{ LanguageId.ckb, "نیووکالێدۆنیا" },
				{ LanguageId.co, "Nova Caledonia" },
				{ LanguageId.cs, "Nová Kaledonie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Caledonia Newydd" },
				{ LanguageId.dav, "Nyukaledonia" },
				{ LanguageId.de, "Neukaledonien" },
				{ LanguageId.dje, "Kaaledooni Taagaa" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Nowa Kaledoniska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ནིའུ་ཀ་ལི་དོ་ནི་ཡ" },
				{ LanguageId.ebu, "Nyukaledonia" },
				{ LanguageId.ee, "New Kaledonia nutome" },
				{ LanguageId.el, "Νέα Καληδονία" },
				{ LanguageId.en, "New Caledonia" },
				{ LanguageId.eo, "Nov-Kaledonio" },
				{ LanguageId.es, "Nueva Caledonia" },
				{ LanguageId.et, "Uus-Kaledoonia" },
				{ LanguageId.eu, "Kaledonia Berria" },
				{ LanguageId.ewo, "Ǹkpámɛn Kaledónia" },
				{ LanguageId.fa, "کالدونیای جدید" },
				{ LanguageId.ff, "Nuwel Kaledonii" },
				{ LanguageId.fi, "Uusi-Kaledonia" },
				{ LanguageId.fil, "New Caledonia" },
				{ LanguageId.fo, "Nýkaledónia" },
				{ LanguageId.fr, "Nouvelle-Calédonie" },
				{ LanguageId.fur, "Gnove Caledonie" },
				{ LanguageId.fy, "Nij-Caledonië" },
				{ LanguageId.ga, "an Nua-Chaladóin" },
				{ LanguageId.gd, "Cailleann Nuadh" },
				{ LanguageId.gl, "Nova Caledonia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Nöikaledoonie" },
				{ LanguageId.gu, "ન્યુ સેલેડોનિયા" },
				{ LanguageId.guz, "Nyukaledonia" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Kaledoniya Sabuwa" },
				{ LanguageId.haw, "Nu Kaledonia" },
				{ LanguageId.he, "קלדוניה החדשה" },
				{ LanguageId.hi, "न्यू कैलेडोनिया" },
				{ LanguageId.hr, "Nova Kaledonija" },
				{ LanguageId.hsb, "Nowa Kaledoniska" },
				{ LanguageId.hu, "Új-Kaledónia" },
				{ LanguageId.hy, "Նոր Կալեդոնիա" },
				{ LanguageId.ia, "Nove Caledonia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kaledonia Baru" },
				{ LanguageId.ig, "New Caledonia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Nýja-Kaledónía" },
				{ LanguageId.it, "Nuova Caledonia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ニューカレドニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Nyukaledonia" },
				{ LanguageId.jv, "Kalédonia Anyar" },
				{ LanguageId.ka, "ახალი კალედონია" },
				{ LanguageId.kab, "Kalidunya Tamaynut" },
				{ LanguageId.kam, "Nyukaledonia" },
				{ LanguageId.kde, "Nyukaledonia" },
				{ LanguageId.kea, "Nova Kalidónia" },
				{ LanguageId.khq, "Kaaledooni Taagaa" },
				{ LanguageId.ki, "Nyukaledonia" },
				{ LanguageId.kk, "Жаңа Каледония" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab New Caledonia" },
				{ LanguageId.km, "នូវែល​កាឡេដូនី" },
				{ LanguageId.kn, "ನ್ಯೂ ಕ್ಯಾಲಿಡೋನಿಯಾ" },
				{ LanguageId.ko, "뉴칼레도니아" },
				{ LanguageId.kok, "नोवो कॅलेडोनिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "نِو کیلِڑونِیا" },
				{ LanguageId.ksb, "Nyukaledonia" },
				{ LanguageId.ksf, "kalɛdoní anyɔ́n" },
				{ LanguageId.ksh, "Neuschottland" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Жаңы Каледония" },
				{ LanguageId.la, "Nova Caledonia" },
				{ LanguageId.lag, "Kaledónia Ifya" },
				{ LanguageId.lb, "Neikaledonien" },
				{ LanguageId.lg, "Kaledonya mupya" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Kaledoni ya sika" },
				{ LanguageId.lo, "ນິວ ຄາເລໂດເນຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Naujoji Kaledonija" },
				{ LanguageId.luo, "New Caledonia" },
				{ LanguageId.luy, "Nyukaledonia" },
				{ LanguageId.lv, "Jaunkaledonija" },
				{ LanguageId.mai, "न्यू कैलेडोनिया" },
				{ LanguageId.mas, "Nyukaledonia" },
				{ LanguageId.mer, "Kalendoia Ĩnjeru" },
				{ LanguageId.mfe, "Nouvel-Kaledoni" },
				{ LanguageId.mg, "Nouvelle-Calédonie" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Whenua Kanaki" },
				{ LanguageId.mk, "Нова Каледонија" },
				{ LanguageId.ml, "ന്യൂ കാലിഡോണിയ" },
				{ LanguageId.mn, "Шинэ Каледони" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "न्यू कॅलेडोनिया" },
				{ LanguageId.ms, "New Caledonia" },
				{ LanguageId.mt, "New Caledonia" },
				{ LanguageId.mua, "Kaledoniya mafuu" },
				{ LanguageId.my, "နယူး ကယ်လီဒိုနီးယား" },
				{ LanguageId.mzn, "نیو کالیدونیا" },
				{ LanguageId.naq, "New Caledonia" },
				{ LanguageId.nb, "Ny-Caledonia" },
				{ LanguageId.nd, "New Caledonia" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "न्यु क्यालेडोनिया" },
				{ LanguageId.nl, "Nieuw-Caledonië" },
				{ LanguageId.nmg, "Kaledoni nwanah" },
				{ LanguageId.nn, "Ny-Caledonia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߊߟߋߘߏߣߌ߫-ߞߎߘߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Niukaredonia" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Neewu Kaaleedoniyaa" },
				{ LanguageId.or, "ନୂତନ କାଲେଡୋନିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨਿਊ ਕੈਲੇਡੋਨੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Niú Kalẹdónia" },
				{ LanguageId.pl, "Nowa Kaledonia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "نوی کالیډونیا" },
				{ LanguageId.pt, "Nova Caledônia" },
				{ LanguageId.qu, "Nueva Caledonia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Nova Caledonia" },
				{ LanguageId.rn, "Niyukaledoniya" },
				{ LanguageId.ro, "Noua Caledonie" },
				{ LanguageId.rof, "Nyukaledonia" },
				{ LanguageId.ru, "Новая Каледония" },
				{ LanguageId.rw, "Caledoniya Nshya" },
				{ LanguageId.rwk, "Nyukaledonia" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Nyukaledonia" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Nyukaledoniya" },
				{ LanguageId.sd, "نیو ڪالیڊونیا" },
				{ LanguageId.se, "Ođđa-Kaledonia" },
				{ LanguageId.seh, "Nova Caledônia" },
				{ LanguageId.ses, "Kaaledooni Taagaa" },
				{ LanguageId.sg, "Finî Kaledonïi" },
				{ LanguageId.shi, "ⴽⴰⵍⵉⴷⵓⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ" },
				{ LanguageId.si, "නව කැලිඩෝනියාව" },
				{ LanguageId.sk, "Nová Kaledónia" },
				{ LanguageId.sl, "Nova Kaledonija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Uđđâ-Kaledonia" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "New Caledonia" },
				{ LanguageId.so, "Jasiiradda Niyuu Kaledooniya" },
				{ LanguageId.sq, "Kaledoni e Re" },
				{ LanguageId.sr, "Нова Каледонија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "New Caledonia" },
				{ LanguageId.su, "Kalédonia Anyar" },
				{ LanguageId.sv, "Nya Kaledonien" },
				{ LanguageId.sw, "New Caledonia" },
				{ LanguageId.syr, "ܢܝܘ ܟܠܝܕܘܢܝܐ" },
				{ LanguageId.ta, "நியூ கேலிடோனியா" },
				{ LanguageId.te, "కొత్త కాలెడోనియా" },
				{ LanguageId.teo, "Nyukaledonia" },
				{ LanguageId.tg, "Каледонияи Нав" },
				{ LanguageId.th, "นิวแคลิโดเนีย" },
				{ LanguageId.ti, "ኒው ካለዶንያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Täze Kaledoniýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Niu Kaletōnia" },
				{ LanguageId.tr, "Yeni Kaledonya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Яңа Каледония" },
				{ LanguageId.twq, "Kaaledooni Taagaa" },
				{ LanguageId.tzm, "kalidunya Tamaynut" },
				{ LanguageId.ug, "يېڭى كالېدونىيە" },
				{ LanguageId.uk, "Нова Каледонія" },
				{ LanguageId.ur, "نیو کلیڈونیا" },
				{ LanguageId.uz, "Yangi Kaledoniya" },
				{ LanguageId.vai, "ꕪꔷꖁꕇꕰ ꕯꕮꕊ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "New Caledonia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Nyukaledonia" },
				{ LanguageId.wae, "Niwkaledonie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Nuwel Kaledoni" },
				{ LanguageId.xh, "ENew Caledonia" },
				{ LanguageId.xog, "Kaledonya mupya" },
				{ LanguageId.yav, "nufɛ́l kaletoní" },
				{ LanguageId.yi, "נײַ קאַלעדאניע" },
				{ LanguageId.yo, "Kaledonia Titun" },
				{ LanguageId.zgh, "ⴽⴰⵍⵉⴷⵓⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ" },
				{ LanguageId.zh, "新喀里多尼亚" },
				{ LanguageId.zu, "i-New Caledonia" },
			}
		);
	}
}
