using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class NC
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "687",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Ny Kaledonien" },
				{ LanguageId.af, "Nieu-Kaledonië" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኒው ካሌዶኒያ" },
				{ LanguageId.ar, "كاليدونيا الجديدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Yeni Kaledoniya" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Новая Каледонія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Нова Каледония" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "নতুন ক্যালেডোনিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Kaledonia-Nevez" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Nova Kaledonija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Nova Caledònia" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "New Caledonia" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Nova Caledonia" },
				{ LanguageId.cs, "Nová Kaledonie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Caledonia Newydd" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Neu-Kaledonien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νέα Καληδονία" },
				{ LanguageId.en, "New Caledonia" },
				{ LanguageId.eo, "Nov-Kaledonio" },
				{ LanguageId.es, "Nueva Caledonia" },
				{ LanguageId.et, "Uus-Kaledoonia" },
				{ LanguageId.eu, "Kaledonia Berria" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "کالدونیای جدید" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Uusi-Caledonia" },
				{ LanguageId.fil, "New Caledonia" },
				{ LanguageId.fo, "Nýkaledonia" },
				{ LanguageId.fr, "Nouvelle Calédonie" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Nij Kaledoanje" },
				{ LanguageId.ga, "An Nua-Chaladóin" },
				{ LanguageId.gd, "Caledonia Nuadh" },
				{ LanguageId.gl, "Nova Caledonia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ન્યૂ કેલેડોનિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "New Caledonia" },
				{ LanguageId.haw, "Nu Kaledonia" },
				{ LanguageId.he, "קלדוניה החדשה" },
				{ LanguageId.hi, "नया केलडोनिया" },
				{ LanguageId.hr, "nova Kaledonija" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Új-Kaledónia" },
				{ LanguageId.hy, "Նոր Կալեդոնիա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kaledonia Baru" },
				{ LanguageId.ig, "New Caledonia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Nýja Kaledónía" },
				{ LanguageId.it, "Nuova Caledonia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ニューカレドニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kaledonia Anyar" },
				{ LanguageId.ka, "ახალი კალედონია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Жаңа Каледония" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កាឡេដូនៀថ្មី។" },
				{ LanguageId.kn, "ನ್ಯೂ ಕ್ಯಾಲೆಡೋನಿಯಾ" },
				{ LanguageId.ko, "뉴 칼레도니아" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Жаңы Каледония" },
				{ LanguageId.la, "Nova Caledonia" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Nei Kaledonien" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ນິວຄາລິໂດເນຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Naujoji Kaledonija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Jaunkaledonija" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nouvelle-Calédonia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "New Caledonia" },
				{ LanguageId.mk, "Нова Каледонија" },
				{ LanguageId.ml, "ന്യൂ കാലിഡോണിയ" },
				{ LanguageId.mn, "Шинэ Каледони" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "न्यू कॅलेडोनिया" },
				{ LanguageId.ms, "New Caledonia" },
				{ LanguageId.mt, "il-Kaledonja l-Ġdida" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "နယူးကယ်လီဒိုးနီးယား" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Ny Caledonia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "न्यू क्यालेडोनिया" },
				{ LanguageId.nl, "Nieuw-Caledonië" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Ny-Caledonia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ନୂତନ କାଲେଡୋନିଆ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨਿਊ ਕੈਲੇਡੋਨੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Nowa Kaledonia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "نیو کالیډونیا" },
				{ LanguageId.pt, "Nova Caledônia" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Noua Caledonie" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Новая Каледония" },
				{ LanguageId.rw, "Caledoniya Nshya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "نيو ڪيليڊونيا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නව කැලිඩෝනියාව" },
				{ LanguageId.sk, "Nová Kaledónia" },
				{ LanguageId.sl, "Nova Kaledonija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "New Caledonia" },
				{ LanguageId.so, "New Caledonia" },
				{ LanguageId.sq, "Kaledonia e Re" },
				{ LanguageId.sr, "Нова Каледонија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "New Caledonia" },
				{ LanguageId.su, "Kalédonia Anyar" },
				{ LanguageId.sv, "Nya Kaledonien" },
				{ LanguageId.sw, "Caledonia Mpya" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "புதிய கலிடோனியா" },
				{ LanguageId.te, "న్యూ కాలెడోనియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Каледонияи Нав" },
				{ LanguageId.th, "นิวแคลิโดเนีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Täze Kaledoniýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Yeni Kaledonya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Яңа Каледония" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "يېڭى كالېدونىيە" },
				{ LanguageId.uk, "Нова Каледонія" },
				{ LanguageId.ur, "نیو کیلیڈونیا" },
				{ LanguageId.uz, "Yangi Kaledoniya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Tân Caledonia" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "New Caledonia" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "ניו קאַלעדאָניאַ" },
				{ LanguageId.yo, "New Caledonia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "新喀里多尼亚" },
				{ LanguageId.zu, "New Caledonia" },
			}
		);
	}
}
