// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class NF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "672",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Norfolk Island" },
				{ LanguageId.af, "Norfolkeiland" },
				{ LanguageId.agq, "Chwɨlà fɨ Nufòʔ" },
				{ LanguageId.ak, "Norfold Supɔ" },
				{ LanguageId.am, "ኖርፎልክ ደሴት" },
				{ LanguageId.ar, "جزيرة نورفولك" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ন’ৰফ’ক দ্বীপ" },
				{ LanguageId.asa, "Kithiwa cha Norfok" },
				{ LanguageId.ast, "Islla Norfolk" },
				{ LanguageId.az, "Norfolk adası" },
				{ LanguageId.ba, "Норфолк утрауы" },
				{ LanguageId.bas, "Òn i Nɔrfɔ̂k" },
				{ LanguageId.be, "Востраў Норфалк" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ihisima sha Norfok" },
				{ LanguageId.bg, "остров Норфолк" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Nɔrofoliki Gun" },
				{ LanguageId.bn, "নরফোক দ্বীপ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Enez Norfolk" },
				{ LanguageId.brx, "नर्फ’क द्वीप" },
				{ LanguageId.bs, "Ostrvo Norfolk" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illa Norfolk" },
				{ LanguageId.ccp, "𑄚𑄨𑄢𑄴𑄜𑄮𑄇𑄴 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Норфолк гӀайре" },
				{ LanguageId.ceb, "Norfolk Island" },
				{ LanguageId.cgg, "Ekizinga Norifoko" },
				{ LanguageId.chr, "ᏃᎵᏬᎵᎩ ᎤᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەی نۆرفۆڵک" },
				{ LanguageId.co, "Isule Norfolk" },
				{ LanguageId.cs, "Norfolk" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynys Norfolk" },
				{ LanguageId.dav, "Kisiwa cha Norfok" },
				{ LanguageId.de, "Norfolkinsel" },
				{ LanguageId.dje, "Norfolk Gungoo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Norfolkowa kupa" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ནོར་ཕོལཀ་མཚོ་གླིང༌" },
				{ LanguageId.ebu, "Kisiwa cha Norfok" },
				{ LanguageId.ee, "Norfolk ƒudomekpo nutome" },
				{ LanguageId.el, "Νήσος Νόρφολκ" },
				{ LanguageId.en, "Norfolk Island" },
				{ LanguageId.eo, "Norfolkinsulo" },
				{ LanguageId.es, "Isla Norfolk" },
				{ LanguageId.et, "Norfolk" },
				{ LanguageId.eu, "Norfolk uhartea" },
				{ LanguageId.ewo, "Minlán Nɔrəfɔ́ləkə" },
				{ LanguageId.fa, "جزیرهٔ نورفولک" },
				{ LanguageId.ff, "Duuɗe Norfolk" },
				{ LanguageId.fi, "Norfolkinsaari" },
				{ LanguageId.fil, "Norfolk Island" },
				{ LanguageId.fo, "Norfolksoyggj" },
				{ LanguageId.fr, "Île Norfolk" },
				{ LanguageId.fur, "Isole Norfolk" },
				{ LanguageId.fy, "Norfolkeilân" },
				{ LanguageId.ga, "Oileán Norfolk" },
				{ LanguageId.gd, "Eilean Norfolk" },
				{ LanguageId.gl, "Illa Norfolk" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Norfolk-Insle" },
				{ LanguageId.gu, "નોરફોક આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Kisiwa cha Norfok" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Narfalk" },
				{ LanguageId.haw, "Nolepoka ʻAilana" },
				{ LanguageId.he, "האי נורפוק" },
				{ LanguageId.hi, "नॉरफ़ॉक द्वीप" },
				{ LanguageId.hr, "Otok Norfolk" },
				{ LanguageId.hsb, "Norfolkowa kupa" },
				{ LanguageId.hu, "Norfolk-sziget" },
				{ LanguageId.hy, "Նորֆոլկ կղզի" },
				{ LanguageId.ia, "Insula Norfolk" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Norfolk" },
				{ LanguageId.ig, "Agwaetiti Norfolk" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Norfolkeyja" },
				{ LanguageId.it, "Isola Norfolk" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ノーフォーク島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Kisiwa cha Norfok" },
				{ LanguageId.jv, "Pulo Norfolk" },
				{ LanguageId.ka, "ნორფოლკის კუნძული" },
				{ LanguageId.kab, "Tigzirin Tinawfukin" },
				{ LanguageId.kam, "Kisiwa cha Norfok" },
				{ LanguageId.kde, "Chisiwa cha Nolufok" },
				{ LanguageId.kea, "Ilhas Norfolk" },
				{ LanguageId.khq, "Norfolk Gungoo" },
				{ LanguageId.ki, "Kisiwa cha Norfok" },
				{ LanguageId.kk, "Норфолк аралы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeiyotab Norfork" },
				{ LanguageId.km, "កោះ​ណ័រហ្វក់" },
				{ LanguageId.kn, "ನಾರ್ಫೋಕ್ ದ್ವೀಪ" },
				{ LanguageId.ko, "노퍽섬" },
				{ LanguageId.kok, "नॉरफोक जुंवो" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "نارفاک جٔزیٖرٕ" },
				{ LanguageId.ksb, "Kisiwa cha Nolfok" },
				{ LanguageId.ksf, "zɛ nɔ́fɔlk" },
				{ LanguageId.ksh, "de Noofok-Ensel" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Норфолк аралы" },
				{ LanguageId.la, "Insula Norfolcia" },
				{ LanguageId.lag, "Kisíiwa cha Nofifóoki" },
				{ LanguageId.lb, "Norfolkinsel" },
				{ LanguageId.lg, "Kizinga ky’eNorofoko" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Esanga Norfokɛ" },
				{ LanguageId.lo, "ເກາະນໍໂຟກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Norfolko sala" },
				{ LanguageId.luo, "Chuia mar Norfolk" },
				{ LanguageId.luy, "Kisiwa cha Norfok" },
				{ LanguageId.lv, "Norfolkas sala" },
				{ LanguageId.mai, "नौरफोक द्वीप" },
				{ LanguageId.mas, "Kisiwa cha Norfok" },
				{ LanguageId.mer, "Aĩrandi cia Norfok" },
				{ LanguageId.mfe, "Lil Norfolk" },
				{ LanguageId.mg, "Nosy Norfolk" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Moutere Nōpoke" },
				{ LanguageId.mk, "Норфолшки Остров" },
				{ LanguageId.ml, "നോർഫോക് ദ്വീപ്" },
				{ LanguageId.mn, "Норфолк арал" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "नॉरफॉक बेट" },
				{ LanguageId.ms, "Pulau Norfolk" },
				{ LanguageId.mt, "Gżira Norfolk" },
				{ LanguageId.mua, "Norfolk ma laŋne" },
				{ LanguageId.my, "နောဖုတ်ကျွန်း" },
				{ LanguageId.mzn, "نورفولک جزیره" },
				{ LanguageId.naq, "Norfolk Island" },
				{ LanguageId.nb, "Norfolkøya" },
				{ LanguageId.nd, "Norfolk Island" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "नोरफोल्क टापु" },
				{ LanguageId.nl, "Norfolk" },
				{ LanguageId.nmg, "Maŋ́ má Nɔrfɔrk" },
				{ LanguageId.nn, "Norfolkøya" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߣߐߙߑߝߐߟߑߞ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ekizinga Norifoko" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odola Noorfoolk" },
				{ LanguageId.or, "ନର୍ଫକ୍ ଦ୍ଵୀପ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨੋਰਫੌਕ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Nọ́fọlk Aíland" },
				{ LanguageId.pl, "Norfolk" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "نارفولک ټاپوګان" },
				{ LanguageId.pt, "Ilha Norfolk" },
				{ LanguageId.qu, "Isla Norfolk" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Insla Norfolk" },
				{ LanguageId.rn, "izinga rya Norufoluke" },
				{ LanguageId.ro, "Insula Norfolk" },
				{ LanguageId.rof, "Kisiwa cha Norfok" },
				{ LanguageId.ru, "о-в Норфолк" },
				{ LanguageId.rw, "Ikirwa cya Norfolk" },
				{ LanguageId.rwk, "Kisiwa cha Norfok" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Kisiwa cha Norfok" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Shigunguli sha Nolifoki" },
				{ LanguageId.sd, "نورفوڪ ٻيٽ" },
				{ LanguageId.se, "Norfolksullot" },
				{ LanguageId.seh, "Ilhas Norfolk" },
				{ LanguageId.ses, "Norfolk Gungoo" },
				{ LanguageId.sg, "Zûâ Nôrfôlko" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵏⵓⵔⴼⵓⵍⴽ" },
				{ LanguageId.si, "නෝෆෝක් දූපත" },
				{ LanguageId.sk, "Norfolk" },
				{ LanguageId.sl, "Norfolški otok" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Norfolksuálui" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Chitsuwa cheNorfolk" },
				{ LanguageId.so, "Jasiiradda Noorfolk" },
				{ LanguageId.sq, "Ishulli Norfolk" },
				{ LanguageId.sr, "Острво Норфок" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Norfolk Island" },
				{ LanguageId.su, "Pulo Norfolk" },
				{ LanguageId.sv, "Norfolkön" },
				{ LanguageId.sw, "Kisiwa cha Norfolk" },
				{ LanguageId.syr, "ܓܙܪܬܐ ܕܢܘܪܦܘܠܟ" },
				{ LanguageId.ta, "நார்ஃபோக் தீவு" },
				{ LanguageId.te, "నార్ఫోక్ దీవి" },
				{ LanguageId.teo, "Kisiwa cha Norfok" },
				{ LanguageId.tg, "Ҷазираи Норфолк" },
				{ LanguageId.th, "เกาะนอร์ฟอล์ก" },
				{ LanguageId.ti, "ደሴት ኖርፎልክ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Norfolk adasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Motu Nōfoliki" },
				{ LanguageId.tr, "Norfolk Adası" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Норфолк утравы" },
				{ LanguageId.twq, "Norfolk Gungoo" },
				{ LanguageId.tzm, "Tigzirt Nurfulk" },
				{ LanguageId.ug, "نورفولك ئارىلى" },
				{ LanguageId.uk, "Острів Норфолк" },
				{ LanguageId.ur, "نارفوک آئلینڈ" },
				{ LanguageId.uz, "Norfolk oroli" },
				{ LanguageId.vai, "ꗟꖺꗉ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Đảo Norfolk" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Kisiwa cha Norfok" },
				{ LanguageId.wae, "Norfolkinsla" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Dunu Norfolk" },
				{ LanguageId.xh, "ENorfolk Island" },
				{ LanguageId.xog, "Kizinga ky’eNorofoko" },
				{ LanguageId.yav, "il nɔ́lfɔ́lɔk" },
				{ LanguageId.yi, "נארפֿאלק אינזל" },
				{ LanguageId.yo, "Erékùsù Nọ́úfókì" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵏⵓⵔⴼⵓⵍⴽ" },
				{ LanguageId.zh, "诺福克岛" },
				{ LanguageId.zu, "i-Norfolk Island" },
			}
		);
	}
}
