using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class NF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "672",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Norfolk Island" },
				{ LanguageId.af, "Norfolk-eiland" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኖርፎልክ አይስላንድስ" },
				{ LanguageId.ar, "جزيرة نورفولك" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Norfolk adası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Востраў Норфалк" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Остров Норфолк" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "নরফোক দ্বীপ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Enez Norfolk" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ostrvo Norfolk" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illa Norfolk" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Pulo ang Norfolk Island" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Norfolk" },
				{ LanguageId.cs, "Ostrov Norfolk" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynys Norfolk" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Norfolkinsel" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησί Νόρφολκ" },
				{ LanguageId.en, "Norfolk Island" },
				{ LanguageId.eo, "Norfolkinsulo" },
				{ LanguageId.es, "Isla Norfolk" },
				{ LanguageId.et, "Norfolki saar" },
				{ LanguageId.eu, "Norfolk uhartea" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزیره نورفولک" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Norfolkin saari" },
				{ LanguageId.fil, "Isla ng Norfolk" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "l'ile de Norfolk" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Norfolkeilannen" },
				{ LanguageId.ga, "Oileán Norfolk" },
				{ LanguageId.gd, "Eilean Norfolk" },
				{ LanguageId.gl, "Illa Norfolk" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "નોર્ફોક આઇલેન્ડ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Norfolk" },
				{ LanguageId.haw, "Nolepoka ʻAilana" },
				{ LanguageId.he, "האי נורפוק" },
				{ LanguageId.hi, "नॉरफ़ॉक द्वीप" },
				{ LanguageId.hr, "Otok Norfolk" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Norfolk-sziget" },
				{ LanguageId.hy, "Նորֆոլկ կղզի" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Pulau Norfolk" },
				{ LanguageId.ig, "Norfolk Island" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Norfolk Island" },
				{ LanguageId.it, "Isola Norfolk" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ノーフォーク島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Pulo Norfolk" },
				{ LanguageId.ka, "ნორფოლკის კუნძული" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Норфолк аралы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Norfolk" },
				{ LanguageId.kn, "ನಾರ್ಫೋಕ್ ದ್ವೀಪ" },
				{ LanguageId.ko, "노퍽 섬" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Норфолк аралы" },
				{ LanguageId.la, "Insula Norfolcia" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Norfolk Insel" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເກາະ Norfolk" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Norfolko sala" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Norfolkas sala" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Norfolk" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Moutere o Norfolk" },
				{ LanguageId.mk, "Островот Норфолк" },
				{ LanguageId.ml, "നോർഫോക്ക് ദ്വീപ്" },
				{ LanguageId.mn, "Норфолк арал" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "नॉरफोक बेट" },
				{ LanguageId.ms, "Pulau Norfolk" },
				{ LanguageId.mt, "Gżira Norfolk" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Norfolk ကျွန်း" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Norfolkøya" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "नोर्फोक द्वीप" },
				{ LanguageId.nl, "Norfolkeiland" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ନର୍ଫାଲ୍କ ଦ୍ୱୀପ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨਾਰਫੋਕ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspa Norfolk" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "نارفولک ټاپوګان" },
				{ LanguageId.pt, "Ilha Norfolk" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insula Norfolk" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Остров Норфолк" },
				{ LanguageId.rw, "Ikirwa cya Norfolk" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "نيرو فيڪا ٻيٽَ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නොර්ෆොක් දූපත" },
				{ LanguageId.sk, "Ostrov Norfolk" },
				{ LanguageId.sl, "Otok Norfolk" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Tsitsuwa Nofoku" },
				{ LanguageId.so, "Jasiiradda Norfolk" },
				{ LanguageId.sq, "Ishulli Norfolk" },
				{ LanguageId.sr, "острво Норфолк" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Norfolk Island" },
				{ LanguageId.su, "Pulo Norfolk" },
				{ LanguageId.sv, "Norfolkön" },
				{ LanguageId.sw, "Kisiwa cha Norfolk" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "நார்போக் தீவு" },
				{ LanguageId.te, "నార్ఫోక్ ద్వీపం" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираи Норфолк" },
				{ LanguageId.th, "เกาะนอร์ฟอล์ก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Norfolk adasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Norfolk Adası" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Норфолк утравы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "نورفولك ئارىلى" },
				{ LanguageId.uk, "Острів Норфолк" },
				{ LanguageId.ur, "نورفولک جزیرہ" },
				{ LanguageId.uz, "Norfolk oroli" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Đảo Norfolk" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Isiqithi saseNofolkh" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "נאָרפאָלק אינזל" },
				{ LanguageId.yo, "Norfolk Island" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "诺福克岛" },
				{ LanguageId.zu, "Isiqhingi saseNorfolk" },
			}
		);
	}
}
