// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class NL
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "31",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Nederlandene" },
				{ LanguageId.af, "Nederland" },
				{ LanguageId.agq, "Nedàlân" },
				{ LanguageId.ak, "Nɛdɛland" },
				{ LanguageId.am, "ኔዘርላንድ" },
				{ LanguageId.ar, "هولندا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "নেডাৰলেণ্ড" },
				{ LanguageId.asa, "Uholandhi" },
				{ LanguageId.ast, "Países Baxos" },
				{ LanguageId.az, "Niderland" },
				{ LanguageId.ba, "Нидерланд" },
				{ LanguageId.bas, "Ǹlɛndi" },
				{ LanguageId.be, "Нідэрланды" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huuholanzi" },
				{ LanguageId.bg, "Нидерландия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Peyiba" },
				{ LanguageId.bn, "নেদারল্যান্ডস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Izelvroioù" },
				{ LanguageId.brx, "नेदारलेण्ड" },
				{ LanguageId.bs, "Nizozemska" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Països Baixos" },
				{ LanguageId.ccp, "𑄚𑄬𑄘𑄢𑄴𑄣𑄳𑄠𑄚𑄴𑄓𑄴𑄥𑄴" },
				{ LanguageId.ce, "Нидерландаш" },
				{ LanguageId.ceb, "Netherlands" },
				{ LanguageId.cgg, "Hoorandi" },
				{ LanguageId.chr, "ᏁᏛᎳᏂ" },
				{ LanguageId.ckb, "ھۆڵەندا" },
				{ LanguageId.co, "Paesi Bassi" },
				{ LanguageId.cs, "Nizozemsko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Yr Iseldiroedd" },
				{ LanguageId.dav, "Uholanzi" },
				{ LanguageId.de, "Niederlande" },
				{ LanguageId.dje, "Hollandu" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Nižozemska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ནེ་དར་ལནཌས྄" },
				{ LanguageId.ebu, "Uholanzi" },
				{ LanguageId.ee, "Netherlands nutome" },
				{ LanguageId.el, "Κάτω Χώρες" },
				{ LanguageId.en, "Netherlands" },
				{ LanguageId.eo, "Nederlando" },
				{ LanguageId.es, "Países Bajos" },
				{ LanguageId.et, "Holland" },
				{ LanguageId.eu, "Herbehereak" },
				{ LanguageId.ewo, "Pɛíbá" },
				{ LanguageId.fa, "هلند" },
				{ LanguageId.ff, "Nederlannda" },
				{ LanguageId.fi, "Alankomaat" },
				{ LanguageId.fil, "Netherlands" },
				{ LanguageId.fo, "Niðurlond" },
				{ LanguageId.fr, "Pays-Bas" },
				{ LanguageId.fur, "Paîs bas" },
				{ LanguageId.fy, "Nederlân" },
				{ LanguageId.ga, "an Ísiltír" },
				{ LanguageId.gd, "Na Tìrean Ìsle" },
				{ LanguageId.gl, "Países Baixos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Holland" },
				{ LanguageId.gu, "નેધરલેન્ડ્સ" },
				{ LanguageId.guz, "Uholanzi" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Holan" },
				{ LanguageId.haw, "Hōlani" },
				{ LanguageId.he, "הולנד" },
				{ LanguageId.hi, "नीदरलैंड" },
				{ LanguageId.hr, "Nizozemska" },
				{ LanguageId.hsb, "Nižozemska" },
				{ LanguageId.hu, "Hollandia" },
				{ LanguageId.hy, "Նիդեռլանդներ" },
				{ LanguageId.ia, "Nederlandia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Belanda" },
				{ LanguageId.ig, "Netherlands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Holland" },
				{ LanguageId.it, "Paesi Bassi" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "オランダ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Uholanzi" },
				{ LanguageId.jv, "Walanda" },
				{ LanguageId.ka, "ნიდერლანდები" },
				{ LanguageId.kab, "Timura-Yessakesren" },
				{ LanguageId.kam, "Uholanzi" },
				{ LanguageId.kde, "Uholanzi" },
				{ LanguageId.kea, "Olanda" },
				{ LanguageId.khq, "Hollandu" },
				{ LanguageId.ki, "Uholanzi" },
				{ LanguageId.kk, "Нидерланд" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Holand" },
				{ LanguageId.km, "ហូឡង់" },
				{ LanguageId.kn, "ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್" },
				{ LanguageId.ko, "네덜란드" },
				{ LanguageId.kok, "नॅदरलँड" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "نیٖدَرلینڑ" },
				{ LanguageId.ksb, "Uholanzi" },
				{ LanguageId.ksf, "kǝlɔŋ kǝ ázǝ" },
				{ LanguageId.ksh, "de Nederläng" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Нидерланд" },
				{ LanguageId.la, "Nederlandia" },
				{ LanguageId.lag, "Ʉholáanzi" },
				{ LanguageId.lb, "Holland" },
				{ LanguageId.lg, "Holandi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Olandɛ" },
				{ LanguageId.lo, "ເນເທີແລນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Nyderlandai" },
				{ LanguageId.luo, "Netherlands" },
				{ LanguageId.luy, "Uholanzi" },
				{ LanguageId.lv, "Nīderlande" },
				{ LanguageId.mai, "नीदरलैंड" },
				{ LanguageId.mas, "Uholanzi" },
				{ LanguageId.mer, "Holandi" },
				{ LanguageId.mfe, "Oland" },
				{ LanguageId.mg, "Holanda" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hōrana" },
				{ LanguageId.mk, "Холандија" },
				{ LanguageId.ml, "നെതർലാൻഡ്‌സ്" },
				{ LanguageId.mn, "Нидерланд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "नेदरलँड" },
				{ LanguageId.ms, "Belanda" },
				{ LanguageId.mt, "in-Netherlands" },
				{ LanguageId.mua, "Sǝr ma kasǝŋ" },
				{ LanguageId.my, "နယ်သာလန်" },
				{ LanguageId.mzn, "هلند" },
				{ LanguageId.naq, "Netherlands" },
				{ LanguageId.nb, "Nederland" },
				{ LanguageId.nd, "Netherlands" },
				{ LanguageId.nds, "Nedderlannen" },
				{ LanguageId.ne, "नेदरल्याण्ड" },
				{ LanguageId.nl, "Nederland" },
				{ LanguageId.nmg, "Nedɛrland" },
				{ LanguageId.nn, "Nederland" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߤߏߟߊ߲ߘ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Hoorandi" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Neezerlaand" },
				{ LanguageId.or, "ନେଦରଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨੀਦਰਲੈਂਡ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Nẹ́dalands" },
				{ LanguageId.pl, "Holandia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "هالېنډ" },
				{ LanguageId.pt, "Países Baixos" },
				{ LanguageId.qu, "Países Bajos" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Pajais Bass" },
				{ LanguageId.rn, "Ubuholandi" },
				{ LanguageId.ro, "Țările de Jos" },
				{ LanguageId.rof, "Uholanzi" },
				{ LanguageId.ru, "Нидерланды" },
				{ LanguageId.rw, "Ubuholandi" },
				{ LanguageId.rwk, "Uholanzi" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Uholanzi" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Wuholansi" },
				{ LanguageId.sd, "نيدرلينڊ" },
				{ LanguageId.se, "Vuolleeatnamat" },
				{ LanguageId.seh, "Holanda" },
				{ LanguageId.ses, "Hollandu" },
				{ LanguageId.sg, "Holände" },
				{ LanguageId.shi, "ⵀⵓⵍⴰⵏⴷⴰ" },
				{ LanguageId.si, "නෙදර්ලන්තය" },
				{ LanguageId.sk, "Holandsko" },
				{ LanguageId.sl, "Nizozemska" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Vuáládâhenâmeh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Netherlands" },
				{ LanguageId.so, "Nederlaands" },
				{ LanguageId.sq, "Holandë" },
				{ LanguageId.sr, "Холандија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Netherlands" },
				{ LanguageId.su, "Walanda" },
				{ LanguageId.sv, "Nederländerna" },
				{ LanguageId.sw, "Uholanzi" },
				{ LanguageId.syr, "ܗܘܠܢܕܐ" },
				{ LanguageId.ta, "நெதர்லாந்து" },
				{ LanguageId.te, "నెదర్లాండ్స్" },
				{ LanguageId.teo, "Uholanzi" },
				{ LanguageId.tg, "Нидерландия" },
				{ LanguageId.th, "เนเธอร์แลนด์" },
				{ LanguageId.ti, "ኔዘርላንድ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Niderlandlar" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Hōlani" },
				{ LanguageId.tr, "Hollanda" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Нидерланд" },
				{ LanguageId.twq, "Hollandu" },
				{ LanguageId.tzm, "Hulanḍa" },
				{ LanguageId.ug, "گوللاندىيە" },
				{ LanguageId.uk, "Нідерланди" },
				{ LanguageId.ur, "نیدر لینڈز" },
				{ LanguageId.uz, "Niderlandiya" },
				{ LanguageId.vai, "ꘉꕜ ꖨꕮꕊ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hà Lan" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Uholanzi" },
				{ LanguageId.wae, "Holand" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Peyi Baa" },
				{ LanguageId.xh, "ENetherlands" },
				{ LanguageId.xog, "Holandi" },
				{ LanguageId.yav, "nitililáand" },
				{ LanguageId.yi, "האלאַנד" },
				{ LanguageId.yo, "Nedalandi" },
				{ LanguageId.zgh, "ⵀⵓⵍⴰⵏⴷⴰ" },
				{ LanguageId.zh, "荷兰" },
				{ LanguageId.zu, "i-Netherlands" },
			}
		);
	}
}
