using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class NZ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "64",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "New Zealand" },
				{ LanguageId.af, "Nieu-Seeland" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኒውዚላንድ" },
				{ LanguageId.ar, "نيوزيلندا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Yeni Zelandiya" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Новая Зеландыя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Нова Зеландия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "নিউজিল্যান্ড" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Zeland-Nevez" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Novi Zeland" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Nova Zelanda" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "New Zealand" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Nova Zelanda" },
				{ LanguageId.cs, "Nový Zéland" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Seland Newydd" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Neuseeland" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νέα Ζηλανδία" },
				{ LanguageId.en, "New Zealand" },
				{ LanguageId.eo, "Nov-Zelando" },
				{ LanguageId.es, "Nueva Zelanda" },
				{ LanguageId.et, "Uus-Meremaa" },
				{ LanguageId.eu, "Zelanda Berria" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "نیوزلند" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Uusi Seelanti" },
				{ LanguageId.fil, "New Zealand" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Nouvelle-Zélande" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Nij Seelân" },
				{ LanguageId.ga, "An Nua-Shéalainn" },
				{ LanguageId.gd, "Na Seulan Nuadh" },
				{ LanguageId.gl, "Nova Zelandia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ન્યૂઝીલેન્ડ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "New Zealand" },
				{ LanguageId.haw, "Aotearoa" },
				{ LanguageId.he, "ניו זילנד" },
				{ LanguageId.hi, "न्यूज़ीलैंड" },
				{ LanguageId.hr, "Novi Zeland" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Új Zéland" },
				{ LanguageId.hy, "Նոր Զելանդիա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Selandia Baru" },
				{ LanguageId.ig, "New Zealand" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Nýja Sjáland" },
				{ LanguageId.it, "Nuova Zelanda" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ニュージーランド" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Selandia Anyar" },
				{ LanguageId.ka, "Ახალი ზელანდია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Жаңа зеландия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "នូវែលសេឡង់" },
				{ LanguageId.kn, "ನ್ಯೂಜಿಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "뉴질랜드" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Жаңы Зеландия" },
				{ LanguageId.la, "Novus Zealand" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Neiséiland" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ນິວ​ຊີ​ແລນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Naujoji Zelandija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Jaunzēlande" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Novely zelandy" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Aotearoa" },
				{ LanguageId.mk, "Нов Зеланд" },
				{ LanguageId.ml, "ന്യൂസിലാന്റ്" },
				{ LanguageId.mn, "Шинэ Зеланд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "न्युझीलँड" },
				{ LanguageId.ms, "New Zealand" },
				{ LanguageId.mt, "New Zealand" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "နယူးဇီလန်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "New Zealand" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "न्युजिल्याण्ड" },
				{ LanguageId.nl, "Nieuw-Zeeland" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ନିଉଜିଲାଣ୍ଡ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਨਿਊਜ਼ੀਲੈਂਡ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Nowa Zelandia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "نيوزيلنډ" },
				{ LanguageId.pt, "Nova Zelândia" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Noua Zeelandă" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Новая Зеландия" },
				{ LanguageId.rw, "Nouvelle-Zélande" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "نيو زيلينڊ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නවසීලන්තය" },
				{ LanguageId.sk, "Nový Zéland" },
				{ LanguageId.sl, "Nova Zelandija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Nyuzirendi" },
				{ LanguageId.so, "New Zealand" },
				{ LanguageId.sq, "Zelanda e Re" },
				{ LanguageId.sr, "Нови Зеланд" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "New zealand" },
				{ LanguageId.su, "Selandia Baru" },
				{ LanguageId.sv, "Nya Zeeland" },
				{ LanguageId.sw, "New Zealand" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "நியூசிலாந்து" },
				{ LanguageId.te, "న్యూజిలాండ్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Зеландияи Нав" },
				{ LanguageId.th, "นิวซีแลนด์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Täze Zelandiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Yeni Zelanda" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Яңа Зеландия" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "يېڭى زېلاندىيە" },
				{ LanguageId.uk, "Нова Зеландія" },
				{ LanguageId.ur, "نیوزی لینڈ" },
				{ LanguageId.uz, "Yangi Zelandiya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "New Zealand" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "I-New Zealand" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "ניו זילאַנד" },
				{ LanguageId.yo, "Ilu Niu silandii" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "新西兰" },
				{ LanguageId.zu, "E-New Zealand" },
			}
		);
	}
}
