using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class NZ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "64",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "New Zealand" },
				{ LanguageId.da, "New Zealand" },
				{ LanguageId.af, "Nieu-Seeland" },
				{ LanguageId.agq, "New Zealand" },
				{ LanguageId.ak, "New Zealand" },
				{ LanguageId.am, "ኒውዚላንድ" },
				{ LanguageId.ar, "نيوزيلندا" },
				{ LanguageId.arn, "New Zealand" },
				{ LanguageId.@as, "নিউজিলেণ্ড" },
				{ LanguageId.asa, "New Zealand" },
				{ LanguageId.ast, "Nueva Zelanda" },
				{ LanguageId.az, "Yeni Zelandiya" },
				{ LanguageId.ba, "Яңа Зеландия" },
				{ LanguageId.bas, "New Zealand" },
				{ LanguageId.be, "Новая Зеландыя" },
				{ LanguageId.bem, "New Zealand" },
				{ LanguageId.bez, "New Zealand" },
				{ LanguageId.bg, "Нова Зеландия" },
				{ LanguageId.bin, "New Zealand" },
				{ LanguageId.bm, "New Zealand" },
				{ LanguageId.bn, "নিউজিল্যান্ড" },
				{ LanguageId.bo, "ནིའུ་ཛི་ལེནཌ།" },
				{ LanguageId.br, "Zeland-Nevez" },
				{ LanguageId.brx, "न्यू जीलैंड" },
				{ LanguageId.bs, "Novi Zeland" },
				{ LanguageId.byn, "New Zealand" },
				{ LanguageId.ca, "Nova Zelanda" },
				{ LanguageId.ccp, "𑄚𑄨𑄃𑄪 𑄎𑄨𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Керла Зеландия" },
				{ LanguageId.ceb, "New Zealand" },
				{ LanguageId.cgg, "New Zealand" },
				{ LanguageId.chr, "ᎢᏤ ᏏᎢᎴᏂᏗ" },
				{ LanguageId.ckb, "نیوزیلەند" },
				{ LanguageId.co, "Nova Zelanda" },
				{ LanguageId.cs, "Nový Zéland" },
				{ LanguageId.cu, "Новаꙗ Зєландїꙗ" },
				{ LanguageId.cy, "Seland Newydd" },
				{ LanguageId.dav, "New Zealand" },
				{ LanguageId.de, "Neuseeland" },
				{ LanguageId.dje, "New Zealand" },
				{ LanguageId.doi, "न्यूज़ीलैंड" },
				{ LanguageId.dsb, "Nowoseelandska" },
				{ LanguageId.dua, "New Zealand" },
				{ LanguageId.dv, "ނިއުޒިލޭންޑު" },
				{ LanguageId.dz, "ནིའུ་ཛི་ལེནཌ།" },
				{ LanguageId.ebu, "New Zealand" },
				{ LanguageId.ee, "New Zealand" },
				{ LanguageId.el, "Νέα Ζηλανδία" },
				{ LanguageId.en, "New Zealand" },
				{ LanguageId.eo, "Nov-Zelando" },
				{ LanguageId.es, "Nueva Zelanda" },
				{ LanguageId.et, "Uus-Meremaa" },
				{ LanguageId.eu, "Zelanda Berria" },
				{ LanguageId.ewo, "New Zealand" },
				{ LanguageId.fa, "نیوزلند" },
				{ LanguageId.ff, "Nuwel Selande" },
				{ LanguageId.fi, "Uusi Seelanti" },
				{ LanguageId.fil, "New Zealand" },
				{ LanguageId.fo, "Nýsæland" },
				{ LanguageId.fr, "Nouvelle-Zélande" },
				{ LanguageId.fur, "Gnove Zelande" },
				{ LanguageId.fy, "Nij Seelân" },
				{ LanguageId.ga, "An Nua-Shéalainn" },
				{ LanguageId.gd, "Na Seulan Nuadh" },
				{ LanguageId.gl, "Nova Zelandia" },
				{ LanguageId.gn, "Selandia Pyahu" },
				{ LanguageId.gsw, "Neuseeland" },
				{ LanguageId.gu, "ન્યૂઝીલેન્ડ" },
				{ LanguageId.guz, "New Zealand" },
				{ LanguageId.gv, "Yn Teelynn Noa" },
				{ LanguageId.ha, "New Zealand" },
				{ LanguageId.haw, "Aotearoa" },
				{ LanguageId.he, "ניו זילנד" },
				{ LanguageId.hi, "न्यूज़ीलैंड" },
				{ LanguageId.hr, "Novi Zeland" },
				{ LanguageId.hsb, "Nowoseelandska" },
				{ LanguageId.hu, "Új Zéland" },
				{ LanguageId.hy, "Նոր Զելանդիա" },
				{ LanguageId.ia, "Nove Zelanda" },
				{ LanguageId.ibb, "New Zealand" },
				{ LanguageId.id, "Selandia Baru" },
				{ LanguageId.ig, "New Zealand" },
				{ LanguageId.ii, "ꆏꑭꀮ" },
				{ LanguageId.@is, "Nýja Sjáland" },
				{ LanguageId.it, "Nuova Zelanda" },
				{ LanguageId.iu, "ᓄᑦᓯᓚᓐ" },
				{ LanguageId.ja, "ニュージーランド" },
				{ LanguageId.jgo, "New Zealand" },
				{ LanguageId.jmc, "New Zealand" },
				{ LanguageId.jv, "Selandia Anyar" },
				{ LanguageId.ka, "ახალი ზელანდია" },
				{ LanguageId.kab, "Ziland Tamaynut" },
				{ LanguageId.kam, "New Zealand" },
				{ LanguageId.kde, "New Zealand" },
				{ LanguageId.kea, "Nova Zelándia" },
				{ LanguageId.khq, "Zeelandu taaga" },
				{ LanguageId.ki, "New Zealand" },
				{ LanguageId.kk, "Жаңа зеландия" },
				{ LanguageId.kkj, "New Zealand" },
				{ LanguageId.kl, "Nutaaq Zeelandi" },
				{ LanguageId.kln, "New Zealand" },
				{ LanguageId.km, "នូវែលសេឡង់" },
				{ LanguageId.kn, "ನ್ಯೂಜಿಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "뉴질랜드" },
				{ LanguageId.kok, "न्यूझीलँड" },
				{ LanguageId.kr, "New Zealand" },
				{ LanguageId.ks, "نیوزی لینڈ" },
				{ LanguageId.ksb, "New Zealand" },
				{ LanguageId.ksf, "New Zealand" },
				{ LanguageId.ksh, "Neuseeland" },
				{ LanguageId.kw, "Mordir Nowydh" },
				{ LanguageId.ky, "Жаңы Зеландия" },
				{ LanguageId.la, "Novus Zealand" },
				{ LanguageId.lag, "New Zealand" },
				{ LanguageId.lb, "Neiséiland" },
				{ LanguageId.lg, "New Zealand" },
				{ LanguageId.lkt, "New Zealand" },
				{ LanguageId.ln, "Zelandɛ ya sika" },
				{ LanguageId.lo, "ນິວ​ຊີ​ແລນ" },
				{ LanguageId.lrc, "زلاند نو" },
				{ LanguageId.lt, "Naujoji Zelandija" },
				{ LanguageId.luo, "New Zealand" },
				{ LanguageId.luy, "New Zealand" },
				{ LanguageId.lv, "Jaunzēlande" },
				{ LanguageId.mai, "न्यूजीलैंड" },
				{ LanguageId.mas, "New Zealand" },
				{ LanguageId.mer, "New Zealand" },
				{ LanguageId.mfe, "Nouvel Zelann" },
				{ LanguageId.mg, "Novely zelandy" },
				{ LanguageId.mgo, "New Zealand" },
				{ LanguageId.mi, "Aotearoa" },
				{ LanguageId.mk, "Нов Зеланд" },
				{ LanguageId.ml, "ന്യൂസിലാന്റ്" },
				{ LanguageId.mn, "Шинэ Зеланд" },
				{ LanguageId.mni, "ন্যু জিলেন্দ" },
				{ LanguageId.moh, "New Zealand" },
				{ LanguageId.mr, "न्युझीलँड" },
				{ LanguageId.ms, "New Zealand" },
				{ LanguageId.mt, "New Zealand" },
				{ LanguageId.mua, "New Zealand" },
				{ LanguageId.my, "နယူးဇီလန်" },
				{ LanguageId.mzn, "نیوزیلند" },
				{ LanguageId.naq, "New Zealand" },
				{ LanguageId.nb, "New Zealand" },
				{ LanguageId.nd, "New Zealand" },
				{ LanguageId.nds, "Niegseeland" },
				{ LanguageId.ne, "न्युजिल्याण्ड" },
				{ LanguageId.nl, "Nieuw-Zeeland" },
				{ LanguageId.nmg, "New Zealand" },
				{ LanguageId.nn, "New Zealand" },
				{ LanguageId.nnh, "New Zealand" },
				{ LanguageId.nqo, "ߒߞߏ ߖ߭ߋߟߊ߲ߘߌ߬" },
				{ LanguageId.nr, "New Zealand" },
				{ LanguageId.nso, "New Zealand" },
				{ LanguageId.nus, "New Zealand" },
				{ LanguageId.nyn, "New Zealand" },
				{ LanguageId.oc, "Nòva Zelanda" },
				{ LanguageId.om, "Niw Zilaandi" },
				{ LanguageId.or, "ନିଉଜିଲାଣ୍ଡ୍" },
				{ LanguageId.os, "Ног Зеланди" },
				{ LanguageId.pa, "ਨਿਊਜ਼ੀਲੈਂਡ" },
				{ LanguageId.pap, "Nèiw Seland" },
				{ LanguageId.pcm, "Niú Zíland" },
				{ LanguageId.pl, "Nowa Zelandia" },
				{ LanguageId.prg, "New Zealand" },
				{ LanguageId.ps, "نيوزيلنډ" },
				{ LanguageId.pt, "Nova Zelândia" },
				{ LanguageId.qu, "Musuq Zilanda" },
				{ LanguageId.quc, "New Zealand" },
				{ LanguageId.rm, "Nova Zelanda" },
				{ LanguageId.rn, "Nouvelle-Zélande" },
				{ LanguageId.ro, "Noua Zeelandă" },
				{ LanguageId.rof, "New Zealand" },
				{ LanguageId.ru, "Новая Зеландия" },
				{ LanguageId.rw, "Nouvelle-Zélande" },
				{ LanguageId.rwk, "New Zealand" },
				{ LanguageId.sa, "न्यूजीलैंड" },
				{ LanguageId.sah, "Саҥа Зеландия" },
				{ LanguageId.saq, "New Zealand" },
				{ LanguageId.sat, "ᱱᱤᱣ ᱡᱤᱞᱟᱱᱰ" },
				{ LanguageId.sbp, "New Zealand" },
				{ LanguageId.sd, "نيو زيلينڊ" },
				{ LanguageId.se, "Ođđa-Selánda" },
				{ LanguageId.seh, "Nova Zelândia" },
				{ LanguageId.ses, "Zeelandu taaga" },
				{ LanguageId.sg, "Finî Zelânde" },
				{ LanguageId.shi, "ⵏⵢⵓ ⵣⵉⵍⴰⵏⴷⴰ" },
				{ LanguageId.si, "නවසීලන්තය" },
				{ LanguageId.sk, "Nový Zéland" },
				{ LanguageId.sl, "Nova Zelandija" },
				{ LanguageId.sma, "New Zealand" },
				{ LanguageId.smj, "New Zealand" },
				{ LanguageId.smn, "New Zealand" },
				{ LanguageId.sms, "New Zealand" },
				{ LanguageId.sn, "Nyuzirendi" },
				{ LanguageId.so, "New Zealand" },
				{ LanguageId.sq, "Zelanda e Re" },
				{ LanguageId.sr, "Нови Зеланд" },
				{ LanguageId.ss, "New Zealand" },
				{ LanguageId.ssy, "New Zealand" },
				{ LanguageId.st, "New zealand" },
				{ LanguageId.su, "Selandia Baru" },
				{ LanguageId.sv, "Nya Zeeland" },
				{ LanguageId.sw, "New Zealand" },
				{ LanguageId.syr, "ܢܝܘ ܙܝܠܢܕ" },
				{ LanguageId.ta, "நியூசிலாந்து" },
				{ LanguageId.te, "న్యూజిలాండ్" },
				{ LanguageId.teo, "New Zealand" },
				{ LanguageId.tg, "Зеландияи Нав" },
				{ LanguageId.th, "นิวซีแลนด์" },
				{ LanguageId.ti, "ኒው ዚላንድ" },
				{ LanguageId.tig, "New Zealand" },
				{ LanguageId.tk, "Täze Zelandiýa" },
				{ LanguageId.tn, "New Zealand" },
				{ LanguageId.to, "Nuʻusila" },
				{ LanguageId.tr, "Yeni Zelanda" },
				{ LanguageId.ts, "New Zealand" },
				{ LanguageId.tt, "Яңа Зеландия" },
				{ LanguageId.twq, "Zeelandu taaga" },
				{ LanguageId.tzm, "ⵏⵢⵓ ⵣⵉⵍⴰⵏⴷⴰ" },
				{ LanguageId.ug, "يېڭى زېلاندىيە" },
				{ LanguageId.uk, "Нова Зеландія" },
				{ LanguageId.ur, "نیوزی لینڈ" },
				{ LanguageId.uz, "Yangi Zelandiya" },
				{ LanguageId.vai, "ꘌꕌ ꔛꔤꘋꔗ" },
				{ LanguageId.ve, "New Zealand" },
				{ LanguageId.vi, "New Zealand" },
				{ LanguageId.vo, "Nula-Seleäns" },
				{ LanguageId.vun, "New Zealand" },
				{ LanguageId.wae, "Neuseeland" },
				{ LanguageId.wal, "New Zealand" },
				{ LanguageId.wo, "Seland-Gu-Bees" },
				{ LanguageId.xh, "I-New Zealand" },
				{ LanguageId.xog, "New Zealand" },
				{ LanguageId.yav, "New Zealand" },
				{ LanguageId.yi, "ניו זילאַנד" },
				{ LanguageId.yo, "Ilu Niu silandii" },
				{ LanguageId.zgh, "ⵏⵢⵓⵣⵉⵍⴰⵏⴷⴰ" },
				{ LanguageId.zh, "新西兰" },
				{ LanguageId.zu, "E-New Zealand" },
			}
		);
	}
}
