// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class NZ
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "64",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "New Zealand" },
				{ LanguageId.da, "New Zealand" },
				{ LanguageId.af, "Nieu-Seeland" },
				{ LanguageId.agq, "Zìlân È fūghū" },
				{ LanguageId.ak, "Ziland Foforo" },
				{ LanguageId.am, "ኒው ዚላንድ" },
				{ LanguageId.ar, "نيوزيلندا" },
				{ LanguageId.arn, "New Zealand" },
				{ LanguageId.@as, "নিউজিলেণ্ড" },
				{ LanguageId.asa, "Nyudhilandi" },
				{ LanguageId.ast, "Nueva Zelanda" },
				{ LanguageId.az, "Yeni Zelandiya" },
				{ LanguageId.ba, "Яңы Зеландия" },
				{ LanguageId.bas, "Sìlând Yɔ̀ndɔ" },
				{ LanguageId.be, "Новая Зеландыя" },
				{ LanguageId.bem, "New Zealand" },
				{ LanguageId.bez, "Hunyuzilandi" },
				{ LanguageId.bg, "Нова Зеландия" },
				{ LanguageId.bin, "New Zealand" },
				{ LanguageId.bm, "Zelandi Koura" },
				{ LanguageId.bn, "নিউজিল্যান্ড" },
				{ LanguageId.bo, "ནིའུ་ཛི་ལེནཌ།" },
				{ LanguageId.br, "Zeland-Nevez" },
				{ LanguageId.brx, "न्यूजीलेण्ड" },
				{ LanguageId.bs, "Novi Zeland" },
				{ LanguageId.byn, "New Zealand" },
				{ LanguageId.ca, "Nova Zelanda" },
				{ LanguageId.ccp, "𑄚𑄨𑄃𑄪𑄎𑄨𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Керла Зеланди" },
				{ LanguageId.ceb, "New Zealand" },
				{ LanguageId.cgg, "Niuzirandi" },
				{ LanguageId.chr, "ᎢᏤ ᏏᎢᎴᏂᏗ" },
				{ LanguageId.ckb, "نیوزیلاند" },
				{ LanguageId.co, "Nova Zelanda" },
				{ LanguageId.cs, "Nový Zéland" },
				{ LanguageId.cu, "Новаꙗ Зєландїꙗ" },
				{ LanguageId.cy, "Seland Newydd" },
				{ LanguageId.dav, "Nyuzilandi" },
				{ LanguageId.de, "Neuseeland" },
				{ LanguageId.dje, "Zeelandu Taaga" },
				{ LanguageId.doi, "न्यूज़ीलैंड" },
				{ LanguageId.dsb, "Nowoseelandska" },
				{ LanguageId.dua, "New Zealand" },
				{ LanguageId.dv, "ނިއުޒިލޭންޑު" },
				{ LanguageId.dz, "ནིའུ་ཛི་ལེནཌ" },
				{ LanguageId.ebu, "Nyuzilandi" },
				{ LanguageId.ee, "New Zealand nutome" },
				{ LanguageId.el, "Νέα Ζηλανδία" },
				{ LanguageId.en, "New Zealand" },
				{ LanguageId.eo, "Nov-Zelando" },
				{ LanguageId.es, "Nueva Zelanda" },
				{ LanguageId.et, "Uus-Meremaa" },
				{ LanguageId.eu, "Zeelanda Berria" },
				{ LanguageId.ewo, "Ǹkpámɛn Zeláŋ" },
				{ LanguageId.fa, "نیوزیلند" },
				{ LanguageId.ff, "Nuwel Selannda" },
				{ LanguageId.fi, "Uusi-Seelanti" },
				{ LanguageId.fil, "New Zealand" },
				{ LanguageId.fo, "Nýsæland" },
				{ LanguageId.fr, "Nouvelle-Zélande" },
				{ LanguageId.fur, "Gnove Zelande" },
				{ LanguageId.fy, "Nij-Seelân" },
				{ LanguageId.ga, "an Nua-Shéalainn" },
				{ LanguageId.gd, "Sealainn Nuadh" },
				{ LanguageId.gl, "Nova Zelandia" },
				{ LanguageId.gn, "Selandia Pyahu" },
				{ LanguageId.gsw, "Nöiseeland" },
				{ LanguageId.gu, "ન્યુઝીલૅન્ડ" },
				{ LanguageId.guz, "Nyuzilandi" },
				{ LanguageId.gv, "Yn Teelynn Noa" },
				{ LanguageId.ha, "Nuzilan" },
				{ LanguageId.haw, "Aotearoa" },
				{ LanguageId.he, "ניו זילנד" },
				{ LanguageId.hi, "न्यूज़ीलैंड" },
				{ LanguageId.hr, "Novi Zeland" },
				{ LanguageId.hsb, "Nowoseelandska" },
				{ LanguageId.hu, "Új-Zéland" },
				{ LanguageId.hy, "Նոր Զելանդիա" },
				{ LanguageId.ia, "Nove Zelanda" },
				{ LanguageId.ibb, "New Zealand" },
				{ LanguageId.id, "Selandia Baru" },
				{ LanguageId.ig, "New Zealand" },
				{ LanguageId.ii, "ꆏꑭꀮ" },
				{ LanguageId.@is, "Nýja-Sjáland" },
				{ LanguageId.it, "Nuova Zelanda" },
				{ LanguageId.iu, "ᓄᑦᓯᓚᓐ" },
				{ LanguageId.ja, "ニュージーランド" },
				{ LanguageId.jgo, "New Zealand" },
				{ LanguageId.jmc, "Nyuzilandi" },
				{ LanguageId.jv, "Selandia Anyar" },
				{ LanguageId.ka, "ახალი ზელანდია" },
				{ LanguageId.kab, "Ziland Tamaynut" },
				{ LanguageId.kam, "Nyuzilandi" },
				{ LanguageId.kde, "Nyuzilandi" },
				{ LanguageId.kea, "Nova Zilándia" },
				{ LanguageId.khq, "Zeelandu Taaga" },
				{ LanguageId.ki, "Nyuzilandi" },
				{ LanguageId.kk, "Жаңа Зеландия" },
				{ LanguageId.kkj, "New Zealand" },
				{ LanguageId.kl, "Nutaaq Zeelandi" },
				{ LanguageId.kln, "Emetab New Zealand" },
				{ LanguageId.km, "នូវែល​សេឡង់" },
				{ LanguageId.kn, "ನ್ಯೂಜಿಲೆಂಡ್" },
				{ LanguageId.ko, "뉴질랜드" },
				{ LanguageId.kok, "नोवो झीलॅंड" },
				{ LanguageId.kr, "New Zealand" },
				{ LanguageId.ks, "نیوزی لینڈ" },
				{ LanguageId.ksb, "Nyuzilandi" },
				{ LanguageId.ksf, "zɛlan anyɔ́n" },
				{ LanguageId.ksh, "Neuseeland" },
				{ LanguageId.kw, "Mordir Nowydh" },
				{ LanguageId.ky, "Жаңы Зеландия" },
				{ LanguageId.la, "Novus Zealand" },
				{ LanguageId.lag, "Nyuzílandi" },
				{ LanguageId.lb, "Neiséiland" },
				{ LanguageId.lg, "Niyuziirandi" },
				{ LanguageId.lkt, "New Zealand" },
				{ LanguageId.ln, "Zelandɛ ya sika" },
				{ LanguageId.lo, "ນິວຊີແລນ" },
				{ LanguageId.lrc, "زلاند نو" },
				{ LanguageId.lt, "Naujoji Zelandija" },
				{ LanguageId.luo, "New Zealand" },
				{ LanguageId.luy, "Nyuzilandi" },
				{ LanguageId.lv, "Jaunzēlande" },
				{ LanguageId.mai, "न्यूजीलैंड" },
				{ LanguageId.mas, "Nyuzilandi" },
				{ LanguageId.mer, "Niuzilandi" },
				{ LanguageId.mfe, "Nouvel Zeland" },
				{ LanguageId.mg, "Nouvelle-Zélande" },
				{ LanguageId.mgo, "New Zealand" },
				{ LanguageId.mi, "Aotearoa" },
				{ LanguageId.mk, "Нов Зеланд" },
				{ LanguageId.ml, "ന്യൂസിലൻഡ്" },
				{ LanguageId.mn, "Шинэ Зеланд" },
				{ LanguageId.mni, "ন্যু জিলেন্দ" },
				{ LanguageId.moh, "New Zealand" },
				{ LanguageId.mr, "न्यूझीलंड" },
				{ LanguageId.ms, "New Zealand" },
				{ LanguageId.mt, "New Zealand" },
				{ LanguageId.mua, "Zeland mafuu" },
				{ LanguageId.my, "နယူးဇီလန်" },
				{ LanguageId.mzn, "نیوزلند" },
				{ LanguageId.naq, "New Zealandi" },
				{ LanguageId.nb, "New Zealand" },
				{ LanguageId.nd, "New Zealand" },
				{ LanguageId.nds, "Niegseeland" },
				{ LanguageId.ne, "न्युजिल्याण्ड" },
				{ LanguageId.nl, "Nieuw-Zeeland" },
				{ LanguageId.nmg, "Zeland nwanah" },
				{ LanguageId.nn, "New Zealand" },
				{ LanguageId.nnh, "New Zealand" },
				{ LanguageId.nqo, "ߖ߭ߋߟߊ߲ߘߌ߫-ߞߎߘߊ߫" },
				{ LanguageId.nr, "New Zealand" },
				{ LanguageId.nso, "New Zealand" },
				{ LanguageId.nus, "New Zealand" },
				{ LanguageId.nyn, "Niuzirandi" },
				{ LanguageId.oc, "Nòva Zelanda" },
				{ LanguageId.om, "Neewu Zilaand" },
				{ LanguageId.or, "ନ୍ୟୁଜିଲାଣ୍ଡ" },
				{ LanguageId.os, "Ног Зеланди" },
				{ LanguageId.pa, "ਨਿਊਜ਼ੀਲੈਂਡ" },
				{ LanguageId.pap, "Nèiw Seland" },
				{ LanguageId.pcm, "Niú Zíland" },
				{ LanguageId.pl, "Nowa Zelandia" },
				{ LanguageId.prg, "New Zealand" },
				{ LanguageId.ps, "نیوزیلنډ" },
				{ LanguageId.pt, "Nova Zelândia" },
				{ LanguageId.qu, "Nueva Zelanda" },
				{ LanguageId.quc, "New Zealand" },
				{ LanguageId.rm, "Nova Zelanda" },
				{ LanguageId.rn, "Nuvelizelandi" },
				{ LanguageId.ro, "Noua Zeelandă" },
				{ LanguageId.rof, "Nyuzilandi" },
				{ LanguageId.ru, "Новая Зеландия" },
				{ LanguageId.rw, "Nouvelle-Zélande" },
				{ LanguageId.rwk, "Nyuzilandi" },
				{ LanguageId.sa, "न्यूजीलैंड" },
				{ LanguageId.sah, "Саҥа Зеландия" },
				{ LanguageId.saq, "Nyuzilandi" },
				{ LanguageId.sat, "ᱱᱤᱣ ᱡᱤᱞᱟᱱᱰ" },
				{ LanguageId.sbp, "Nyusilendi" },
				{ LanguageId.sd, "نيو زيلينڊ" },
				{ LanguageId.se, "Ođđa-Selánda" },
				{ LanguageId.seh, "Nova Zelândia" },
				{ LanguageId.ses, "Zeelandu Taaga" },
				{ LanguageId.sg, "Finî Zelânde" },
				{ LanguageId.shi, "ⵏⵢⵓⵣⵉⵍⴰⵏⴷⴰ" },
				{ LanguageId.si, "නවසීලන්තය" },
				{ LanguageId.sk, "Nový Zéland" },
				{ LanguageId.sl, "Nova Zelandija" },
				{ LanguageId.sma, "New Zealand" },
				{ LanguageId.smj, "New Zealand" },
				{ LanguageId.smn, "Uđđâ-Seeland" },
				{ LanguageId.sms, "New Zealand" },
				{ LanguageId.sn, "New Zealand" },
				{ LanguageId.so, "Niyuusiilaand" },
				{ LanguageId.sq, "Zelandë e Re" },
				{ LanguageId.sr, "Нови Зеланд" },
				{ LanguageId.ss, "New Zealand" },
				{ LanguageId.ssy, "New Zealand" },
				{ LanguageId.st, "New zealand" },
				{ LanguageId.su, "Selandia Baru" },
				{ LanguageId.sv, "Nya Zeeland" },
				{ LanguageId.sw, "Nyuzilandi" },
				{ LanguageId.syr, "ܢܝܘ ܙܝܠܢܕ" },
				{ LanguageId.ta, "நியூசிலாந்து" },
				{ LanguageId.te, "న్యూజిలాండ్" },
				{ LanguageId.teo, "Nyuzilandi" },
				{ LanguageId.tg, "Зеландияи Нав" },
				{ LanguageId.th, "นิวซีแลนด์" },
				{ LanguageId.ti, "ኒው ዚላንድ" },
				{ LanguageId.tig, "New Zealand" },
				{ LanguageId.tk, "Täze Zelandiýa" },
				{ LanguageId.tn, "New Zealand" },
				{ LanguageId.to, "Nuʻusila" },
				{ LanguageId.tr, "Yeni Zelanda" },
				{ LanguageId.ts, "New Zealand" },
				{ LanguageId.tt, "Яңа Зеландия" },
				{ LanguageId.twq, "Zeelandu Taaga" },
				{ LanguageId.tzm, "Zilanḍa Tamaynut" },
				{ LanguageId.ug, "يېڭى زېلاندىيە" },
				{ LanguageId.uk, "Нова Зеландія" },
				{ LanguageId.ur, "نیوزی لینڈ" },
				{ LanguageId.uz, "Yangi Zelandiya" },
				{ LanguageId.vai, "ꔽꔤ ꖨꕮ ꕯꕮꕊ" },
				{ LanguageId.ve, "New Zealand" },
				{ LanguageId.vi, "New Zealand" },
				{ LanguageId.vo, "Nula-Seleäns" },
				{ LanguageId.vun, "Nyuzilandi" },
				{ LanguageId.wae, "Niwséland" },
				{ LanguageId.wal, "New Zealand" },
				{ LanguageId.wo, "Nuwel Selànd" },
				{ LanguageId.xh, "ENew Zealand" },
				{ LanguageId.xog, "Niyuziirandi" },
				{ LanguageId.yav, "nufɛ́l seláand" },
				{ LanguageId.yi, "ניו זילאַנד" },
				{ LanguageId.yo, "Ṣilandi Titun" },
				{ LanguageId.zgh, "ⵏⵢⵓⵣⵉⵍⴰⵏⴷⴰ" },
				{ LanguageId.zh, "新西兰" },
				{ LanguageId.zu, "i-New Zealand" },
			}
		);
	}
}
