using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class PF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "689",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Fransk Polynesien" },
				{ LanguageId.af, "Frans-Polynesië" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የፈረንሳይ ፖሊኔዥያ" },
				{ LanguageId.ar, "بولينيزيا الفرنسية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Fransız Polineziyası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Французская Палінезія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Френска полинезия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ফরাসি পলিনেশিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Polinezia C'hall" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Francuska Polinezija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Polinèsia Francesa" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "French Polynesia" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Polinesia francese" },
				{ LanguageId.cs, "Francouzská Polynésie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Polynesia Ffrainc" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Französisch Polynesien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Γαλλική Πολυνησία" },
				{ LanguageId.en, "French Polynesia" },
				{ LanguageId.eo, "Franca Polinezio" },
				{ LanguageId.es, "Polinesia francés" },
				{ LanguageId.et, "Prantsuse Polüneesia" },
				{ LanguageId.eu, "Polinesia frantsesa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "پلینزی فرانسه" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Ranskan Polynesia" },
				{ LanguageId.fil, "French Polynesia" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Polynésie française" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Frânsk Polyneezje" },
				{ LanguageId.ga, "Polainéis na Fraince" },
				{ LanguageId.gd, "Polynesia na Frainge" },
				{ LanguageId.gl, "Polinesia Francesa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ફ્રેન્ચ પોલિનેશિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Faransa Polynesia" },
				{ LanguageId.haw, "Polenekia Farani" },
				{ LanguageId.he, "פולינזיה הצרפתית" },
				{ LanguageId.hi, "फ़्रेंच पोलिनेशिया" },
				{ LanguageId.hr, "Francuska Polinezija" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Francia Polinézia" },
				{ LanguageId.hy, "Ֆրանսիական Պոլինեզիա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Polinesia Perancis" },
				{ LanguageId.ig, "French Polynesia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Franska Pólýnesía" },
				{ LanguageId.it, "Polinesia francese" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フランス領ポリネシア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Polinesia Prancis" },
				{ LanguageId.ka, "ფრანგული პოლინეზია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Француз Полинезиясы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ប៉ូលីនេស៊ីបារាំង" },
				{ LanguageId.kn, "ಫ್ರೆಂಚ್ ಪಾಲಿನೇಷ್ಯಾ" },
				{ LanguageId.ko, "프랑스 령 폴리네시아의" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Француз Полинезиясы" },
				{ LanguageId.la, "Polynesia Gallica" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Franséisch Polynesien" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຝຣັ່ງໂພລີນີເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Prancūzų Polinezija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Franču Polinēzija" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Polinezia frantsay" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Poronīhia Wīwī" },
				{ LanguageId.mk, "Француска Полинезија" },
				{ LanguageId.ml, "ഫ്രഞ്ച് പോളിനേഷ്യ" },
				{ LanguageId.mn, "Францын Полинез" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फ्रेंच पॉलिनेशिया" },
				{ LanguageId.ms, "Polynesia Perancis" },
				{ LanguageId.mt, "Polinesja Franċiża" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ပြင်သစ်ပိုလီနီးရှား" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Fransk Polynesia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फ्रेन्च पोलिनेसिया" },
				{ LanguageId.nl, "Frans-Polynesië" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଫରାସୀ ପଲିନେସିଆ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫ੍ਰੈਂਚ ਪੋਲੀਨੇਸ਼ੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Polinezja Francuska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فرانسوی پولینیشیا" },
				{ LanguageId.pt, "Polinésia Francesa" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Polinezia Franceză" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Французская Полинезия" },
				{ LanguageId.rw, "Polineziya y'Abafaransa" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "فرينچ پولينيشيا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ප්රංශ පොලිනීසියාව" },
				{ LanguageId.sk, "Francúzska Polynézia" },
				{ LanguageId.sl, "Francoska Polinezija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "French Polynesia" },
				{ LanguageId.so, "Faransiiska Polynesia" },
				{ LanguageId.sq, "Polinezia Franceze" },
				{ LanguageId.sr, "Француска Полинезија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "French Polynesia" },
				{ LanguageId.su, "Polinésia Perancis" },
				{ LanguageId.sv, "Franska Polynesien" },
				{ LanguageId.sw, "Polynesia ya Ufaransa" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "பிரெஞ்சு பாலினேசியா" },
				{ LanguageId.te, "ఫ్రెంచ్ పాలినేషియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Полинезияи Фаронса" },
				{ LanguageId.th, "เฟรนช์โปลินีเซีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Fransuz polineziýasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Fransız Polinezyası" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Француз Полинезиясе" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "French Polynesia" },
				{ LanguageId.uk, "Французька Полінезія" },
				{ LanguageId.ur, "فرانسیسی پولینیشیا" },
				{ LanguageId.uz, "Fransuz Polineziyasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Polynesia thuộc Pháp" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IFrench Polynesia" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פראנצויזיש פּאָלינעסיאַ" },
				{ LanguageId.yo, "French Polinisia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "法属波利尼西亚" },
				{ LanguageId.zu, "I-French Polynesia" },
			}
		);
	}
}
