// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "689",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Fransk Polynesien" },
				{ LanguageId.af, "Frans-Polinesië" },
				{ LanguageId.agq, "Kpoleneshìa è Fàlâŋnsì" },
				{ LanguageId.ak, "Frɛnkye Pɔlenehyia" },
				{ LanguageId.am, "የፈረንሳይ ፖሊኔዢያ" },
				{ LanguageId.ar, "بولينيزيا الفرنسية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ফ্ৰান্স পোলেনচিয়া" },
				{ LanguageId.asa, "Polinesia ya Ufarantha" },
				{ LanguageId.ast, "Polinesia Francesa" },
				{ LanguageId.az, "Fransa Polineziyası" },
				{ LanguageId.ba, "Француз Полинезияһы" },
				{ LanguageId.bas, "Pòlìnesìà Pùlàsi" },
				{ LanguageId.be, "Французская Палінезія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hupolinesia ya Huufaransa" },
				{ LanguageId.bg, "Френска Полинезия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Faransi ka polinezi" },
				{ LanguageId.bn, "ফরাসী পলিনেশিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Polinezia Cʼhall" },
				{ LanguageId.brx, "फ्रेन्च पलिनेशिया" },
				{ LanguageId.bs, "Francuska Polinezija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Polinèsia Francesa" },
				{ LanguageId.ccp, "𑄜𑄧𑄢𑄥𑄩 𑄛𑄧𑄣𑄨𑄚𑄬𑄥𑄨𑄠" },
				{ LanguageId.ce, "Французийн Полинези" },
				{ LanguageId.ceb, "French Polynesia" },
				{ LanguageId.cgg, "Polinesia ya Bufaransa" },
				{ LanguageId.chr, "ᎠᏂᎦᎸᏥ ᏆᎵᏂᏏᎠ" },
				{ LanguageId.ckb, "پۆلینیسیای فەرەنسا" },
				{ LanguageId.co, "Polinesia francese" },
				{ LanguageId.cs, "Francouzská Polynésie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Polynesia Ffrengig" },
				{ LanguageId.dav, "Polinesia ya Ufaransa" },
				{ LanguageId.de, "Französisch-Polynesien" },
				{ LanguageId.dje, "Faransi Polineezi" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Francojska Polyneziska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཕྲཱནས྄་ཀྱི་པོ་ལི་ནི་ཤི་ཡ" },
				{ LanguageId.ebu, "Polinesia ya Ufaransa" },
				{ LanguageId.ee, "Frentsi Pɔlinesia nutome" },
				{ LanguageId.el, "Γαλλική Πολυνησία" },
				{ LanguageId.en, "French Polynesia" },
				{ LanguageId.eo, "Franca Polinezio" },
				{ LanguageId.es, "Polinesia Francesa" },
				{ LanguageId.et, "Prantsuse Polüneesia" },
				{ LanguageId.eu, "Polinesia Frantsesa" },
				{ LanguageId.ewo, "Polinesí yá Fulɛnsí" },
				{ LanguageId.fa, "پلی‌نزی فرانسه" },
				{ LanguageId.ff, "Polinesii Farayse" },
				{ LanguageId.fi, "Ranskan Polynesia" },
				{ LanguageId.fil, "French Polynesia" },
				{ LanguageId.fo, "Franska Polynesia" },
				{ LanguageId.fr, "Polynésie française" },
				{ LanguageId.fur, "Polinesie francês" },
				{ LanguageId.fy, "Frans-Polynesië" },
				{ LanguageId.ga, "Polainéis na Fraince" },
				{ LanguageId.gd, "Poilinèis na Frainge" },
				{ LanguageId.gl, "Polinesia Francesa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Französisch-Polineesie" },
				{ LanguageId.gu, "ફ્રેંચ પોલિનેશિયા" },
				{ LanguageId.guz, "Polinesia ya Ufaransa" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Folinesiya Ta Faransa" },
				{ LanguageId.haw, "Polenekia Farani" },
				{ LanguageId.he, "פולינזיה הצרפתית" },
				{ LanguageId.hi, "फ़्रेंच पोलिनेशिया" },
				{ LanguageId.hr, "Francuska Polinezija" },
				{ LanguageId.hsb, "Francoska Polyneziska" },
				{ LanguageId.hu, "Francia Polinézia" },
				{ LanguageId.hy, "Ֆրանսիական Պոլինեզիա" },
				{ LanguageId.ia, "Polynesia francese" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Polinesia Prancis" },
				{ LanguageId.ig, "French Polynesia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Franska Pólýnesía" },
				{ LanguageId.it, "Polinesia Francese" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "仏領ポリネシア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Polinesia ya Ufaransa" },
				{ LanguageId.jv, "Polinesia Prancis" },
				{ LanguageId.ka, "საფრანგეთის პოლინეზია" },
				{ LanguageId.kab, "Pulunizi tafransist" },
				{ LanguageId.kam, "Polinesia ya Ufaransa" },
				{ LanguageId.kde, "Polinesia ya Ufalansa" },
				{ LanguageId.kea, "Polinézia Franseza" },
				{ LanguageId.khq, "Faransi Polineezi" },
				{ LanguageId.ki, "Polinesia ya Ufaransa" },
				{ LanguageId.kk, "Француз Полинезиясы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Polynesia nebo ufaransa" },
				{ LanguageId.km, "ប៉ូលី​ណេស៊ី​បារាំង" },
				{ LanguageId.kn, "ಫ್ರೆಂಚ್ ಪಾಲಿನೇಷ್ಯಾ" },
				{ LanguageId.ko, "프랑스령 폴리네시아" },
				{ LanguageId.kok, "फ्रांसेझ पॉलिनिशिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "فرانسی پولِنیشِیا" },
				{ LanguageId.ksb, "Polinesia ya Ufalansa" },
				{ LanguageId.ksf, "pɔlinɛsí a pɛrɛsǝ́" },
				{ LanguageId.ksh, "Franzüüsesch Pollineesije" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Полинезия (франциялык)" },
				{ LanguageId.la, "Polynesia Gallica" },
				{ LanguageId.lag, "Polinésia yʉ Ʉfaráansa" },
				{ LanguageId.lb, "Franséisch-Polynesien" },
				{ LanguageId.lg, "Polinesiya enfalansa" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Polinezi ya Falánsɛ" },
				{ LanguageId.lo, "ເຟຣນຊ໌ ໂພລິນີເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Prancūzijos Polinezija" },
				{ LanguageId.luo, "French Polynesia" },
				{ LanguageId.luy, "Polinesia ya Ufaransa" },
				{ LanguageId.lv, "Francijas Polinēzija" },
				{ LanguageId.mai, "फ्रेंच पोलिनेशिया" },
				{ LanguageId.mas, "Polinesia ya Ufaransa" },
				{ LanguageId.mer, "Polinesia ya Fransi" },
				{ LanguageId.mfe, "Polinezi franse" },
				{ LanguageId.mg, "Polynezia frantsay" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Poronēhia Wīwī" },
				{ LanguageId.mk, "Француска Полинезија" },
				{ LanguageId.ml, "ഫ്രഞ്ച് പോളിനേഷ്യ" },
				{ LanguageId.mn, "Францын Полинез" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फ्रेंच पॉलिनेशिया" },
				{ LanguageId.ms, "Polinesia Perancis" },
				{ LanguageId.mt, "Polineżja Franċiża" },
				{ LanguageId.mua, "Sǝr Polynesiya ma Franssǝ" },
				{ LanguageId.my, "ပြင်သစ် ပေါ်လီနီးရှား" },
				{ LanguageId.mzn, "فرانسه‌ی پولی‌نزی" },
				{ LanguageId.naq, "French Polynesia" },
				{ LanguageId.nb, "Fransk Polynesia" },
				{ LanguageId.nd, "Pholinesiya ye Fulansi" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फ्रान्सेली पोलिनेसिया" },
				{ LanguageId.nl, "Frans-Polynesië" },
				{ LanguageId.nmg, "Polynesia Fala" },
				{ LanguageId.nn, "Fransk Polynesia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߝߊ߬ߙߊ߲߬ߛߌ߫ ߔߏߟߌߣߋߖ߭ߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Polinesia ya Bufaransa" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Polineeshiyaa Faransaay" },
				{ LanguageId.or, "ଫ୍ରେଞ୍ଚ ପଲିନେସିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫਰੈਂਚ ਪੋਲੀਨੇਸ਼ੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Frẹ́nch Poliníshia" },
				{ LanguageId.pl, "Polinezja Francuska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فرانسوي پولينيسيا" },
				{ LanguageId.pt, "Polinésia Francesa" },
				{ LanguageId.qu, "Polinesia Francesa" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Polinesia Franzosa" },
				{ LanguageId.rn, "Polineziya y’Abafaransa" },
				{ LanguageId.ro, "Polinezia Franceză" },
				{ LanguageId.rof, "Polinesia ya Ufaransa" },
				{ LanguageId.ru, "Французская Полинезия" },
				{ LanguageId.rw, "Polineziya y'Abafaransa" },
				{ LanguageId.rwk, "Polinesia ya Ufaransa" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Polinesia ya Ufaransa" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Polinesiya ya Wufalansa" },
				{ LanguageId.sd, "فرانسيسي پولينيشيا" },
				{ LanguageId.se, "Frankriikka Polynesia" },
				{ LanguageId.seh, "Polinésia Francesa" },
				{ LanguageId.ses, "Faransi Polineezi" },
				{ LanguageId.sg, "Polinezïi tî farânzi" },
				{ LanguageId.shi, "ⴱⵓⵍⵉⵏⵉⵣⵢⴰ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.si, "ප්‍රංශ පොලිනීසියාව" },
				{ LanguageId.sk, "Francúzska Polynézia" },
				{ LanguageId.sl, "Francoska Polinezija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Ranska Polynesia" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "French Polynesia" },
				{ LanguageId.so, "Booliyneesiya Faransiiska" },
				{ LanguageId.sq, "Polinezia Franceze" },
				{ LanguageId.sr, "Француска Полинезија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "French Polynesia" },
				{ LanguageId.su, "Polinésia Perancis" },
				{ LanguageId.sv, "Franska Polynesien" },
				{ LanguageId.sw, "Polynesia ya Ufaransa" },
				{ LanguageId.syr, "ܦܘܠܝܢܝܣܝܐ ܦܪܢܣܝܬܐ" },
				{ LanguageId.ta, "பிரெஞ்சு பாலினேஷியா" },
				{ LanguageId.te, "ఫ్రెంచ్ పోలినీషియా" },
				{ LanguageId.teo, "Polinesia ya Ufaransa" },
				{ LanguageId.tg, "Полинезияи Фаронса" },
				{ LanguageId.th, "เฟรนช์โปลินีเซีย" },
				{ LanguageId.ti, "ፈረንሳዊት ፖሊነዥያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Fransuz Polineziýasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Polinisia fakafalanisē" },
				{ LanguageId.tr, "Fransız Polinezyası" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Француз Полинезиясе" },
				{ LanguageId.twq, "Faransi Polineezi" },
				{ LanguageId.tzm, "Pulinizya Tafransist" },
				{ LanguageId.ug, "فىرانسىيەگە قاراشلىق پولىنېزىيە" },
				{ LanguageId.uk, "Французька Полінезія" },
				{ LanguageId.ur, "فرانسیسی پولینیشیا" },
				{ LanguageId.uz, "Fransuz Polineziyasi" },
				{ LanguageId.vai, "ꗱꘋꔻ ꕶꔷꕇꔻꕩ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Polynesia thuộc Pháp" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Polinesia ya Ufaransa" },
				{ LanguageId.wae, "Französiš Polinesie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Polinesi Farañse" },
				{ LanguageId.xh, "EFrench Polynesia" },
				{ LanguageId.xog, "Polinesiya enfalansa" },
				{ LanguageId.yav, "polinesí u felensí" },
				{ LanguageId.yi, "פֿראַנצויזישע פּאלינעזיע" },
				{ LanguageId.yo, "Firenṣi Polinesia" },
				{ LanguageId.zgh, "ⴱⵓⵍⵉⵏⵉⵣⵢⴰ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ" },
				{ LanguageId.zh, "法属波利尼西亚" },
				{ LanguageId.zu, "i-French Polynesia" },
			}
		);
	}
}
