using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class PG
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "675",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Papua Ny Guinea" },
				{ LanguageId.af, "Papoea-Nieu-Guinee" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ፓፓያ ኒው ጊኒ" },
				{ LanguageId.ar, "بابوا غينيا الجديدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Papua Yeni Qvineya" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Папуа-Новая Гвінея" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Папуа-Нова Гвинея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পাপুয়া নিউ গিনি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Papua Nova Gvineja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Papua Nova Guinea" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Papua New Guinea" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Nova Guinea Papua" },
				{ LanguageId.cs, "Papua-Nová Guinea" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Papwa Gini Newydd" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Papua Neu-Guinea" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Παπούα Νέα Γουινέα" },
				{ LanguageId.en, "Papua New Guinea" },
				{ LanguageId.eo, "Papua Nova Gvineo" },
				{ LanguageId.es, "Papúa Nueva Guinea" },
				{ LanguageId.et, "Paapua Uus-Guinea" },
				{ LanguageId.eu, "Papua Ginea Berria" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "پاپوآ گینه نو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Papua-Uusi-Guinea" },
				{ LanguageId.fil, "Papua New Guinea" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Papouasie Nouvelle Guinée" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Papoea Nij-Guineä" },
				{ LanguageId.ga, "Nua-Ghuine Phapua" },
				{ LanguageId.gd, "Papua New Guinea" },
				{ LanguageId.gl, "Papúa Nova Guinea" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "પાપુઆ ન્યુ ગિની" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Papua New Guinea" },
				{ LanguageId.haw, "Pāpua Nūkini" },
				{ LanguageId.he, "פפואה גינאה החדשה" },
				{ LanguageId.hi, "पापुआ न्यू गिनी" },
				{ LanguageId.hr, "Papua Nova Gvineja" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Pápua Új-Guinea" },
				{ LanguageId.hy, "Պապուա Նոր Գվինեա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Papua Nugini" },
				{ LanguageId.ig, "Papua New Guinea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Papúa Nýja-Gínea" },
				{ LanguageId.it, "Papua Nuova Guinea" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "パプアニューギニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Papua Nugini" },
				{ LanguageId.ka, "პაპუა ახალი გვინეა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Папуа Жаңа Гвинея" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ប៉ាពួញូហ្គីណេ" },
				{ LanguageId.kn, "ಪಪುವಾ ನ್ಯೂ ಗಿನಿಯಾ" },
				{ LanguageId.ko, "파푸아 뉴기니" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Папуа Жаңы Гвинея" },
				{ LanguageId.la, "Papua Novus Guinea" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Papua-Neuguinea" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ປາປົວນິວກີນີ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Papua Naujoji Gvinėja" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Papua Jaungvineja" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Papouasie-Nouvelle-Guinée" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Papua New Guinea" },
				{ LanguageId.mk, "Папуа Нова Гвинеја" },
				{ LanguageId.ml, "പാപുവ ന്യൂ ഗ്വിനിയ" },
				{ LanguageId.mn, "Папуа Шинэ Гвиней" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पापुआ न्यू गिनी" },
				{ LanguageId.ms, "Papua New Guinea" },
				{ LanguageId.mt, "Papwa Ginea Ġdida" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ပါပူဝါနယူးဂီနီ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Papua Ny Guinea" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पपुवा न्यू गिनी" },
				{ LanguageId.nl, "Papoea-Nieuw-Guinea" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ପାପୁଆ ନ୍ୟୁ ଗିନି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪਾਪੂਆ ਨਿਊ ਗਿਨੀ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Papua Nowa Gwinea" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "پاپوا نوی ګینه" },
				{ LanguageId.pt, "Papua Nova Guiné" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Papua Noua Guinee" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Папуа - Новая Гвинея" },
				{ LanguageId.rw, "Papouasie-Nouvelle-Guinée" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "پوپا نيو گائينا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "පැපුවා නිව්ගීනියාව" },
				{ LanguageId.sk, "Papua-Nová Guinea" },
				{ LanguageId.sl, "Papua Nova Gvineja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Papa Nyu Gini" },
				{ LanguageId.so, "Papua New Guinea" },
				{ LanguageId.sq, "Papua Guinea e Re" },
				{ LanguageId.sr, "Папуа Нова Гвинеја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Papua New Guinea" },
				{ LanguageId.su, "Papua Nugini" },
				{ LanguageId.sv, "Papua Nya Guinea" },
				{ LanguageId.sw, "Papua Guinea Mpya" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "பப்புவா நியூ கினி" },
				{ LanguageId.te, "పాపువా న్యూ గినియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Папуа Гвинеяи Нав" },
				{ LanguageId.th, "ปาปัวนิวกินี" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Papua Täze Gwineýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Papua Yeni Gine" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Папуа Яңа Гвинея" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "پاپۇئا يېڭى گۋىنىيىسى" },
				{ LanguageId.uk, "Папуа-Нова Гвінея" },
				{ LanguageId.ur, "پاپوا نیو گنی" },
				{ LanguageId.uz, "Papua-Yangi Gvineya" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Papua New Guinea" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Gini eNtsha yasePapuwa" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פּאַפּואַ ניו גיני" },
				{ LanguageId.yo, "Papua New Guinea" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "巴布亚新几内亚" },
				{ LanguageId.zu, "I-Papua New Guinea" },
			}
		);
	}
}
