// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PG
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "675",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Papua Ny Guinea" },
				{ LanguageId.af, "Papoea-Nieu-Guinee" },
				{ LanguageId.agq, "Kpakpua Ginè È fūghū" },
				{ LanguageId.ak, "Papua Gini Foforɔ" },
				{ LanguageId.am, "ፓፑዋ ኒው ጊኒ" },
				{ LanguageId.ar, "بابوا غينيا الجديدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "পাপুৱা নিউ গিনি" },
				{ LanguageId.asa, "Papua" },
				{ LanguageId.ast, "Papúa Nueva Guinea" },
				{ LanguageId.az, "Papua-Yeni Qvineya" },
				{ LanguageId.ba, "Папуа – Яңы Гвинея" },
				{ LanguageId.bas, "Gìne ì Pàpu" },
				{ LanguageId.be, "Папуа-Новая Гвінея" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hupapua" },
				{ LanguageId.bg, "Папуа-Нова Гвинея" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Papuwasi-Gine-Koura" },
				{ LanguageId.bn, "পাপুয়া নিউ গিনি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Papoua Ginea-Nevez" },
				{ LanguageId.brx, "पापुआ निउ गिनी" },
				{ LanguageId.bs, "Papua Nova Gvineja" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Papua Nova Guinea" },
				{ LanguageId.ccp, "𑄛𑄛𑄪𑄠 𑄚𑄨𑄃𑄪 𑄉𑄨𑄚𑄨" },
				{ LanguageId.ce, "Папуа — Керла Гвиней" },
				{ LanguageId.ceb, "Papua New Guinea" },
				{ LanguageId.cgg, "Papua" },
				{ LanguageId.chr, "ᏆᏇ ᎢᏤ ᎩᎢᏂ" },
				{ LanguageId.ckb, "پاپوا گینێی نوێ" },
				{ LanguageId.co, "Nova Guinea Papua" },
				{ LanguageId.cs, "Papua-Nová Guinea" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Papua Guinea Newydd" },
				{ LanguageId.dav, "Papua" },
				{ LanguageId.de, "Papua-Neuguinea" },
				{ LanguageId.dje, "Papua Ginee Taaga" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Papua-Neuguinea" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "པ་པུ་ ནིའུ་གི་ནི" },
				{ LanguageId.ebu, "Papua" },
				{ LanguageId.ee, "Papua New Gini nutome" },
				{ LanguageId.el, "Παπούα Νέα Γουινέα" },
				{ LanguageId.en, "Papua New Guinea" },
				{ LanguageId.eo, "Papuo-Nov-Gvineo" },
				{ LanguageId.es, "Papúa Nueva Guinea" },
				{ LanguageId.et, "Paapua Uus-Guinea" },
				{ LanguageId.eu, "Papua Ginea Berria" },
				{ LanguageId.ewo, "Papwazi yá Ǹkpámɛ́n Giné" },
				{ LanguageId.fa, "پاپوا گینهٔ نو" },
				{ LanguageId.ff, "Papuwaa Nuwel Gine" },
				{ LanguageId.fi, "Papua-Uusi-Guinea" },
				{ LanguageId.fil, "Papua New Guinea" },
				{ LanguageId.fo, "Papua Nýguinea" },
				{ LanguageId.fr, "Papouasie-Nouvelle-Guinée" },
				{ LanguageId.fur, "Papue Gnove Guinee" },
				{ LanguageId.fy, "Papoea-Nij-Guinea" },
				{ LanguageId.ga, "Nua-Ghuine Phapua" },
				{ LanguageId.gd, "Gini Nuadh Phaputhach" },
				{ LanguageId.gl, "Papúa-Nova Guinea" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Papua-Neuguinea" },
				{ LanguageId.gu, "પાપુઆ ન્યૂ ગિની" },
				{ LanguageId.guz, "Papua" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Papuwa Nugini" },
				{ LanguageId.haw, "Pāpua Nūkini" },
				{ LanguageId.he, "פפואה גינאה החדשה" },
				{ LanguageId.hi, "पापुआ न्यू गिनी" },
				{ LanguageId.hr, "Papua Nova Gvineja" },
				{ LanguageId.hsb, "Papuwa-Nowa Gineja" },
				{ LanguageId.hu, "Pápua Új-Guinea" },
				{ LanguageId.hy, "Պապուա Նոր Գվինեա" },
				{ LanguageId.ia, "Papua Nove Guinea" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Papua Nugini" },
				{ LanguageId.ig, "Papua New Guinea" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Papúa Nýja-Gínea" },
				{ LanguageId.it, "Papua Nuova Guinea" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "パプアニューギニア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Papua" },
				{ LanguageId.jv, "Papua Nugini" },
				{ LanguageId.ka, "პაპუა-ახალი გვინეა" },
				{ LanguageId.kab, "Ɣinya Tamaynut Tapaput" },
				{ LanguageId.kam, "Papua" },
				{ LanguageId.kde, "Papua" },
				{ LanguageId.kea, "Papua-Nova Gine" },
				{ LanguageId.khq, "Papua Ginee Taaga" },
				{ LanguageId.ki, "Papua" },
				{ LanguageId.kk, "Папуа — Жаңа Гвинея" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Papua New Guinea" },
				{ LanguageId.km, "ប៉ាពូអាស៊ី​នូវែលហ្គីណេ" },
				{ LanguageId.kn, "ಪಪುವಾ ನ್ಯೂಗಿನಿಯಾ" },
				{ LanguageId.ko, "파푸아뉴기니" },
				{ LanguageId.kok, "पापुआ नोवो गिनी" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "پاپُوا نیوٗ گیٖنی" },
				{ LanguageId.ksb, "Papua" },
				{ LanguageId.ksf, "papwazí ginɛ́ anyɔ́n" },
				{ LanguageId.ksh, "Papuwa Neujineeja" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Папуа-Жаңы Гвинея" },
				{ LanguageId.la, "Papua Novus Guinea" },
				{ LanguageId.lag, "Papúua" },
				{ LanguageId.lb, "Papua-Neiguinea" },
				{ LanguageId.lg, "Papwa Nyugini" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Papwazi Ginɛ ya sika" },
				{ LanguageId.lo, "ປາປົວນິວກີນີ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Papua Naujoji Gvinėja" },
				{ LanguageId.luo, "Papua New Guinea" },
				{ LanguageId.luy, "Papua" },
				{ LanguageId.lv, "Papua-Jaungvineja" },
				{ LanguageId.mai, "पापुआ न्यू गिनी" },
				{ LanguageId.mas, "Papua" },
				{ LanguageId.mer, "Papua" },
				{ LanguageId.mfe, "Papouazi-Nouvel-Gine" },
				{ LanguageId.mg, "Papouasie-Nouvelle-Guinée" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Papua Nūkini" },
				{ LanguageId.mk, "Папуа Нова Гвинеја" },
				{ LanguageId.ml, "പാപ്പുവ ന്യൂ ഗിനിയ" },
				{ LanguageId.mn, "Папуа Шинэ Гвиней" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पापुआ न्यू गिनी" },
				{ LanguageId.ms, "Papua New Guinea" },
				{ LanguageId.mt, "Papua New Guinea" },
				{ LanguageId.mua, "Papuasiya Guine mafuu" },
				{ LanguageId.my, "ပါပူအာ နယူးဂီနီ" },
				{ LanguageId.mzn, "پاپوا نو گینه" },
				{ LanguageId.naq, "Papua New Guineab" },
				{ LanguageId.nb, "Papua Ny-Guinea" },
				{ LanguageId.nd, "Papua New Guinea" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पपुआ न्यू गाइनिया" },
				{ LanguageId.nl, "Papoea-Nieuw-Guinea" },
				{ LanguageId.nmg, "Guine Papuasi" },
				{ LanguageId.nn, "Papua Ny-Guinea" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߡߊߡߎߥߊߖ߭ߌ߫ ߖߌ߬ߣߍ߬-ߞߎߘߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Papua" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Papuwa Neawu Giinii" },
				{ LanguageId.or, "ପପୁଆ ନ୍ୟୁ ଗିନି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪਾਪੂਆ ਨਿਊ ਗਿਨੀ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Pápuá Niú Gíni" },
				{ LanguageId.pl, "Papua-Nowa Gwinea" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "پاپوا نيو ګيني" },
				{ LanguageId.pt, "Papua-Nova Guiné" },
				{ LanguageId.qu, "Papúa Nueva Guinea" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Papua Nova Guinea" },
				{ LanguageId.rn, "Papuwa Niyugineya" },
				{ LanguageId.ro, "Papua-Noua Guinee" },
				{ LanguageId.rof, "Papua" },
				{ LanguageId.ru, "Папуа — Новая Гвинея" },
				{ LanguageId.rw, "Papouasie-Nouvelle-Guinée" },
				{ LanguageId.rwk, "Papua" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Papua" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Papuwa" },
				{ LanguageId.sd, "پاپوا نیو گني" },
				{ LanguageId.se, "Papua-Ođđa-Guinea" },
				{ LanguageId.seh, "Papua-Nova Guiné" },
				{ LanguageId.ses, "Papua Ginee Taaga" },
				{ LanguageId.sg, "Papû Finî Ginëe, Papuazïi" },
				{ LanguageId.shi, "ⴱⴰⴱⵡⴰ ⵖⵉⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ" },
				{ LanguageId.si, "පැපුවා නිව් ගිනියාව" },
				{ LanguageId.sk, "Papua-Nová Guinea" },
				{ LanguageId.sl, "Papua Nova Gvineja" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Papua-Uđđâ-Guinea" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Papua New Guinea" },
				{ LanguageId.so, "Babwa Niyuu Gini" },
				{ LanguageId.sq, "Guineja e Re-Papua" },
				{ LanguageId.sr, "Папуа Нова Гвинеја" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Papua New Guinea" },
				{ LanguageId.su, "Papua Nugini" },
				{ LanguageId.sv, "Papua Nya Guinea" },
				{ LanguageId.sw, "Papua New Guinea" },
				{ LanguageId.syr, "ܦܐܦܘܐ ܓܝܢܝܐ ܚܕܬܐ" },
				{ LanguageId.ta, "பப்புவா நியூ கினியா" },
				{ LanguageId.te, "పాపువా న్యూ గినియా" },
				{ LanguageId.teo, "Papua" },
				{ LanguageId.tg, "Папуа Гвинеяи Нав" },
				{ LanguageId.th, "ปาปัวนิวกินี" },
				{ LanguageId.ti, "ፓፕዋ ኒው ጊኒ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Papua - Täze Gwineýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Papuaniukini" },
				{ LanguageId.tr, "Papua Yeni Gine" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Папуа - Яңа Гвинея" },
				{ LanguageId.twq, "Papua Ginee Taaga" },
				{ LanguageId.tzm, "Papwa Ɣinya Tamaynut" },
				{ LanguageId.ug, "پاپۇئا يېڭى گىۋىنىيەسى" },
				{ LanguageId.uk, "Папуа-Нова Гвінея" },
				{ LanguageId.ur, "پاپوآ نیو گنی" },
				{ LanguageId.uz, "Papua – Yangi Gvineya" },
				{ LanguageId.vai, "ꕐꖛꕎ ꕅꔤꕇ ꕯꕮꕊ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Papua New Guinea" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Papua" },
				{ LanguageId.wae, "Papua Niwginea" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Papuwasi Gine Gu Bees" },
				{ LanguageId.xh, "EPapua New Guinea" },
				{ LanguageId.xog, "Papwa Nyugini" },
				{ LanguageId.yav, "papuasí nufɛ́l kiiné" },
				{ LanguageId.yi, "פּאַפּואַ נײַ גינע" },
				{ LanguageId.yo, "Paapu ti Giini" },
				{ LanguageId.zgh, "ⴱⴰⴱⵡⴰ ⵖⵉⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ" },
				{ LanguageId.zh, "巴布亚新几内亚" },
				{ LanguageId.zu, "i-Papua New Guinea" },
			}
		);
	}
}
