// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "63",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Filippinerne" },
				{ LanguageId.af, "Filippyne" },
				{ LanguageId.agq, "Felèkpî" },
				{ LanguageId.ak, "Filipin" },
				{ LanguageId.am, "ፊሊፒንስ" },
				{ LanguageId.ar, "الفلبين" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ফিলিপাইনছ" },
				{ LanguageId.asa, "Filipino" },
				{ LanguageId.ast, "Filipines" },
				{ LanguageId.az, "Filippin" },
				{ LanguageId.ba, "Филиппин" },
				{ LanguageId.bas, "Fìlìpîn" },
				{ LanguageId.be, "Філіпіны" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hufilipino" },
				{ LanguageId.bg, "Филипини" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Filipini" },
				{ LanguageId.bn, "ফিলিপাইন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Filipinez" },
				{ LanguageId.brx, "फिलीपिन्स" },
				{ LanguageId.bs, "Filipini" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Filipines" },
				{ LanguageId.ccp, "𑄜𑄨𑄣𑄨𑄛𑄭𑄚𑄴" },
				{ LanguageId.ce, "Филиппинаш" },
				{ LanguageId.ceb, "Philippines" },
				{ LanguageId.cgg, "Firipino" },
				{ LanguageId.chr, "ᎠᏂᏈᎵᎩᏃ" },
				{ LanguageId.ckb, "فلیپین" },
				{ LanguageId.co, "Filippine" },
				{ LanguageId.cs, "Filipíny" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Philipinau" },
				{ LanguageId.dav, "Filipino" },
				{ LanguageId.de, "Philippinen" },
				{ LanguageId.dje, "Filipine" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Filipiny" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཕི་ལི་པིནས" },
				{ LanguageId.ebu, "Filipino" },
				{ LanguageId.ee, "Filipini nutome" },
				{ LanguageId.el, "Φιλιππίνες" },
				{ LanguageId.en, "Philippines" },
				{ LanguageId.eo, "Filipinoj" },
				{ LanguageId.es, "Filipinas" },
				{ LanguageId.et, "Filipiinid" },
				{ LanguageId.eu, "Filipinak" },
				{ LanguageId.ewo, "Filipín" },
				{ LanguageId.fa, "فیلیپین" },
				{ LanguageId.ff, "Filipiin" },
				{ LanguageId.fi, "Filippiinit" },
				{ LanguageId.fil, "Pilipinas" },
				{ LanguageId.fo, "Filipsoyggjar" },
				{ LanguageId.fr, "Philippines" },
				{ LanguageId.fur, "Filipinis" },
				{ LanguageId.fy, "Filipijnen" },
				{ LanguageId.ga, "Na hOileáin Fhilipíneacha" },
				{ LanguageId.gd, "Na h-Eileanan Filipineach" },
				{ LanguageId.gl, "Filipinas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Philippiine" },
				{ LanguageId.gu, "ફિલિપિન્સ" },
				{ LanguageId.guz, "Filipino" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Filipin" },
				{ LanguageId.haw, "ʻĀina Pilipino" },
				{ LanguageId.he, "הפיליפינים" },
				{ LanguageId.hi, "फ़िलिपींस" },
				{ LanguageId.hr, "Filipini" },
				{ LanguageId.hsb, "Filipiny" },
				{ LanguageId.hu, "Fülöp-szigetek" },
				{ LanguageId.hy, "Ֆիլիպիններ" },
				{ LanguageId.ia, "Philippinas" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Filipina" },
				{ LanguageId.ig, "Philippines" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Filippseyjar" },
				{ LanguageId.it, "Filippine" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "フィリピン" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Filipino" },
				{ LanguageId.jv, "Pilipina" },
				{ LanguageId.ka, "ფილიპინები" },
				{ LanguageId.kab, "Filipin" },
				{ LanguageId.kam, "Filipino" },
				{ LanguageId.kde, "Filipino" },
				{ LanguageId.kea, "Filipinas" },
				{ LanguageId.khq, "Filipine" },
				{ LanguageId.ki, "Filipino" },
				{ LanguageId.kk, "Филиппин аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Philippines" },
				{ LanguageId.km, "ហ្វ៊ីលីពីន" },
				{ LanguageId.kn, "ಫಿಲಿಫೈನ್ಸ್" },
				{ LanguageId.ko, "필리핀" },
				{ LanguageId.kok, "फिलिपीन्स" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "فلپائن" },
				{ LanguageId.ksb, "Filipino" },
				{ LanguageId.ksf, "filipǝ́n" },
				{ LanguageId.ksh, "Fillipiine" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Филиппин" },
				{ LanguageId.la, "Philippinae" },
				{ LanguageId.lag, "Ufilipíino" },
				{ LanguageId.lb, "Philippinnen" },
				{ LanguageId.lg, "Bizinga bya Firipino" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Filipinɛ" },
				{ LanguageId.lo, "ຟິລິບປິນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Filipinai" },
				{ LanguageId.luo, "Philippines" },
				{ LanguageId.luy, "Filipino" },
				{ LanguageId.lv, "Filipīnas" },
				{ LanguageId.mai, "फिलिपींस" },
				{ LanguageId.mas, "Filipino" },
				{ LanguageId.mer, "Filipino" },
				{ LanguageId.mfe, "Filipinn" },
				{ LanguageId.mg, "Filipina" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Piripīni" },
				{ LanguageId.mk, "Филипини" },
				{ LanguageId.ml, "ഫിലിപ്പീൻസ്" },
				{ LanguageId.mn, "Филиппин" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "फिलिपिन्स" },
				{ LanguageId.ms, "Filipina" },
				{ LanguageId.mt, "il-Filippini" },
				{ LanguageId.mua, "Filipiŋ" },
				{ LanguageId.my, "ဖိလစ်ပိုင်" },
				{ LanguageId.mzn, "فیلیپین" },
				{ LanguageId.naq, "Philippinni" },
				{ LanguageId.nb, "Filippinene" },
				{ LanguageId.nd, "Philippines" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "फिलिपिन्स" },
				{ LanguageId.nl, "Filipijnen" },
				{ LanguageId.nmg, "Filipin" },
				{ LanguageId.nn, "Filippinane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߝߟߌߔߌ߲ߣ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Firipino" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Filippiins" },
				{ LanguageId.or, "ଫିଲିପାଇନସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਫਿਲੀਪੀਨਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Fílípins" },
				{ LanguageId.pl, "Filipiny" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "فلپين" },
				{ LanguageId.pt, "Filipinas" },
				{ LanguageId.qu, "Filipinas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Filippinas" },
				{ LanguageId.rn, "Amazinga ya Filipine" },
				{ LanguageId.ro, "Filipine" },
				{ LanguageId.rof, "Filipino" },
				{ LanguageId.ru, "Филиппины" },
				{ LanguageId.rw, "Philippines" },
				{ LanguageId.rwk, "Filipino" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Filipino" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Filipino" },
				{ LanguageId.sd, "فلپائن" },
				{ LanguageId.se, "Filippiinnat" },
				{ LanguageId.seh, "Filipinas" },
				{ LanguageId.ses, "Filipine" },
				{ LanguageId.sg, "Filipîni" },
				{ LanguageId.shi, "ⴼⵉⵍⵉⴱⴱⵉⵏ" },
				{ LanguageId.si, "පිලිපීනය" },
				{ LanguageId.sk, "Filipíny" },
				{ LanguageId.sl, "Filipini" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Filipineh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Philippines" },
				{ LanguageId.so, "Filibiin" },
				{ LanguageId.sq, "Filipine" },
				{ LanguageId.sr, "Филипини" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Philippines" },
				{ LanguageId.su, "Filipina" },
				{ LanguageId.sv, "Filippinerna" },
				{ LanguageId.sw, "Ufilipino" },
				{ LanguageId.syr, "ܦܝܠܝܦܝܢܝܐ" },
				{ LanguageId.ta, "பிலிப்பைன்ஸ்" },
				{ LanguageId.te, "ఫిలిప్పైన్స్" },
				{ LanguageId.teo, "Filipino" },
				{ LanguageId.tg, "Филиппин" },
				{ LanguageId.th, "ฟิลิปปินส์" },
				{ LanguageId.ti, "ፊሊፒንስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Filippinler" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Filipaini" },
				{ LanguageId.tr, "Filipinler" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Филиппин" },
				{ LanguageId.twq, "Filipine" },
				{ LanguageId.tzm, "Filippin" },
				{ LanguageId.ug, "فىلىپپىن" },
				{ LanguageId.uk, "Філіппіни" },
				{ LanguageId.ur, "فلپائن" },
				{ LanguageId.uz, "Filippin" },
				{ LanguageId.vai, "ꔱꔒꔪꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Philippines" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Filipino" },
				{ LanguageId.wae, "Philippine" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Filipin" },
				{ LanguageId.xh, "EPhilippines" },
				{ LanguageId.xog, "Ebizinga bya Firipino" },
				{ LanguageId.yav, "filipíin" },
				{ LanguageId.yi, "פֿיליפּינען" },
				{ LanguageId.yo, "Filipini" },
				{ LanguageId.zgh, "ⴼⵉⵍⵉⴱⴱⵉⵏ" },
				{ LanguageId.zh, "菲律宾" },
				{ LanguageId.zu, "i-Philippines" },
			}
		);
	}
}
