// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "508",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Pierre og Miquelon" },
				{ LanguageId.af, "Sint Pierre en Miquelon" },
				{ LanguageId.agq, "Sɛ̀n Kpiyɛ̀ à Mikelɔŋ" },
				{ LanguageId.ak, "Saint Pierre ne Miquelon" },
				{ LanguageId.am, "ሴንት ፒዬር እና ሚኩኤሎን" },
				{ LanguageId.ar, "سان بيير ومكويلون" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট পিয়েৰে আৰু মিকিউৱেলন" },
				{ LanguageId.asa, "Thantapieri na Mikeloni" },
				{ LanguageId.ast, "Saint Pierre y Miquelon" },
				{ LanguageId.az, "Müqəddəs Pyer və Mikelon" },
				{ LanguageId.ba, "Сен-Пьер һәм Микелон" },
				{ LanguageId.bas, "Nûmpubi Petrò nì Mikèlôn" },
				{ LanguageId.be, "Сен-П’ер і Мікелон" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husantapieri na Humikeloni" },
				{ LanguageId.bg, "Сен Пиер и Микелон" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Piyɛri-Senu-ni-Mikelɔŋ" },
				{ LanguageId.bn, "সেন্ট পিয়ের ও মিকুয়েলন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sant-Pêr-ha-Mikelon" },
				{ LanguageId.brx, "सैन्ट. पिएर आरो मिकैलन" },
				{ LanguageId.bs, "Sveti Petar i Mikelon" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄛𑄨𑄠𑄬𑄢𑄴 𑄃𑄮 𑄟𑄨𑄢𑄪𑄠𑄬𑄣𑄧𑄚𑄴" },
				{ LanguageId.ce, "Сен-Пьер а, Микелон а" },
				{ LanguageId.ceb, "St. Pierre & Miquelon" },
				{ LanguageId.cgg, "Senti Piyerre na Mikweron" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᏈᏰ ᎠᎴ ᎻᏇᎶᏂ" },
				{ LanguageId.ckb, "سەن پیێر و میکێلۆن" },
				{ LanguageId.co, "San Pierre è Miquelonu" },
				{ LanguageId.cs, "Saint-Pierre a Miquelon" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.dav, "Santapieri na Mikeloni" },
				{ LanguageId.de, "St. Pierre und Miquelon" },
				{ LanguageId.dje, "Seŋ Piyer nda Mikelon" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Pierre a Miquelon" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སིནཊ་པི་ཡེར་ ཨེནཌ་ མིཀོ་ལེན" },
				{ LanguageId.ebu, "Santapieri na Mikeloni" },
				{ LanguageId.ee, "Saint Pierre kple Mikelɔn nutome" },
				{ LanguageId.el, "Σεν Πιερ και Μικελόν" },
				{ LanguageId.en, "St. Pierre & Miquelon" },
				{ LanguageId.eo, "Sankta Piero kaj Mikelono" },
				{ LanguageId.es, "San Pedro y Miquelón" },
				{ LanguageId.et, "Saint-Pierre ja Miquelon" },
				{ LanguageId.eu, "Saint-Pierre eta Mikelune" },
				{ LanguageId.ewo, "Ǹfúfúb-Píɛr-ai-Mikəlɔ́ŋ" },
				{ LanguageId.fa, "سن پیر و میکلن" },
				{ LanguageId.ff, "See Piyeer e Mikeloo" },
				{ LanguageId.fi, "Saint-Pierre ja Miquelon" },
				{ LanguageId.fil, "St. Pierre & Miquelon" },
				{ LanguageId.fo, "Saint Pierre & Miquelon" },
				{ LanguageId.fr, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.fur, "San Pierre e Miquelon" },
				{ LanguageId.fy, "Saint-Pierre en Miquelon" },
				{ LanguageId.ga, "San Pierre agus Miquelon" },
				{ LanguageId.gd, "Saint Pierre agus Miquelon" },
				{ LanguageId.gl, "Saint Pierre et Miquelon" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Pierr und Miggelo" },
				{ LanguageId.gu, "સેંટ પીએરી અને મિક્યુલોન" },
				{ LanguageId.guz, "Santapieri na Mikeloni" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Piyar da Mikelan" },
				{ LanguageId.haw, "St. Pierre a me Miquelon" },
				{ LanguageId.he, "סנט פייר ומיקלון" },
				{ LanguageId.hi, "सेंट पिएरे और मिक्वेलान" },
				{ LanguageId.hr, "Sveti Petar i Mikelon" },
				{ LanguageId.hsb, "St. Pierre a Miquelon" },
				{ LanguageId.hu, "Saint-Pierre és Miquelon" },
				{ LanguageId.hy, "Սեն Պիեռ և Միքելոն" },
				{ LanguageId.ia, "St. Pierre e Miquelon" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Pierre dan Miquelon" },
				{ LanguageId.ig, "St. Pierre & Miquelon" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Pierre og Miquelon" },
				{ LanguageId.it, "Saint-Pierre e Miquelon" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サンピエール島・ミクロン島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Santapieri na Mikeloni" },
				{ LanguageId.jv, "Saint Pièr lan Mikuélon" },
				{ LanguageId.ka, "სენ-პიერი და მიკელონი" },
				{ LanguageId.kab, "San Pyar d Miklun" },
				{ LanguageId.kam, "Santapieri na Mikeloni" },
				{ LanguageId.kde, "Santapieli na Mikeloni" },
				{ LanguageId.kea, "San Piere i Mikelon" },
				{ LanguageId.khq, "Seŋ Piyer nda Mikelon" },
				{ LanguageId.ki, "Santapieri na Mikeloni" },
				{ LanguageId.kk, "Сен-Пьер және Микелон" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Peter Ne titil ak Miquelon" },
				{ LanguageId.km, "សង់ព្យែរ និង​មីគីឡុង" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಪಿಯರ್ ಮತ್ತು ಮಿಕ್ವೆಲನ್" },
				{ LanguageId.ko, "생피에르 미클롱" },
				{ LanguageId.kok, "सांव पेद्रु आनी मिकेलांव" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ پیٖری تہٕ موکیلِیَن" },
				{ LanguageId.ksb, "Santapieli na Mikeloni" },
				{ LanguageId.ksf, "sɛnpyɛr ri mikɛlɔŋ" },
				{ LanguageId.ksh, "Zint Pjäär un Mikelong" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сен-Пьер жана Микелон" },
				{ LanguageId.la, "Petrus et Miquelon" },
				{ LanguageId.lag, "Mʉtakatíifu Peéteri na Mɨkaéeli" },
				{ LanguageId.lb, "St. Pierre a Miquelon" },
				{ LanguageId.lg, "Senti Piyere ne Mikeloni" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu pététo mpé Mikelɔ" },
				{ LanguageId.lo, "ເຊນ ປີແອ ມິເກວລອນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sen Pjeras ir Mikelonas" },
				{ LanguageId.luo, "Saint Pierre gi Miquelon" },
				{ LanguageId.luy, "Santapieri na Mikeloni" },
				{ LanguageId.lv, "Senpjēra un Mikelona" },
				{ LanguageId.mai, "सेंट पियरे आ मिक्वेलान" },
				{ LanguageId.mas, "Santapieri na Mikeloni" },
				{ LanguageId.mer, "Santapieri na Mikeloni" },
				{ LanguageId.mfe, "Saint-Pierre-ek-Miquelon" },
				{ LanguageId.mg, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Piere & Mikerona" },
				{ LanguageId.mk, "Сент Пјер и Микелан" },
				{ LanguageId.ml, "സെന്റ് പിയറി ആൻഡ് മിക്വലൻ" },
				{ LanguageId.mn, "Сент-Пьер ба Микело" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट पियरे आणि मिक्वेलोन" },
				{ LanguageId.ms, "Saint Pierre dan Miquelon" },
				{ LanguageId.mt, "Saint Pierre u Miquelon" },
				{ LanguageId.mua, "Sǝr Pǝtar ne Mikǝlon" },
				{ LanguageId.my, "စိန့်ပီအဲရ်နှင့် မီကွီလွန်" },
				{ LanguageId.mzn, "سن پییر و میکلن" },
				{ LanguageId.naq, "Saint Pierre and Miquelon" },
				{ LanguageId.nb, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.nd, "Saint Pierre and Miquelon" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट पिर्रे र मिक्केलोन" },
				{ LanguageId.nl, "Saint-Pierre en Miquelon" },
				{ LanguageId.nmg, "Saint Peter ba Mikelɔn" },
				{ LanguageId.nn, "Saint-Pierre-et-Miquelon" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߔߍ߯ߙ ߣߌ߫ ߡߌ߲ߞߋߟߐ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Senti Piyerre na Mikweron" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Ql. Piyeeree fi Mikuyelon" },
				{ LanguageId.or, "ସେଣ୍ଟ ପିଏରେ ଏବଂ ମିକ୍ୱେଲନ୍‌" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਪੀਅਰੇ ਐਂਡ ਮਿਕੇਲਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Piẹr & Míkẹlọn" },
				{ LanguageId.pl, "Saint-Pierre i Miquelon" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ پییر او میکولون" },
				{ LanguageId.pt, "São Pedro e Miquelão" },
				{ LanguageId.qu, "San Pedro y Miquelón" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Saint Pierre e Miquelon" },
				{ LanguageId.rn, "Sempiyeri na Mikeloni" },
				{ LanguageId.ro, "Saint-Pierre și Miquelon" },
				{ LanguageId.rof, "Santapieri na Mikeloni" },
				{ LanguageId.ru, "Сен-Пьер и Микелон" },
				{ LanguageId.rw, "Mutagatifu Pierre na Miquelon" },
				{ LanguageId.rwk, "Santapieri na Mikeloni" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Santapieri na Mikeloni" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Santapieli ni Mikeloni" },
				{ LanguageId.sd, "سينٽ پيئر ۽ ميڪيلون" },
				{ LanguageId.se, "Saint Pierre ja Miquelon" },
				{ LanguageId.seh, "Saint Pierre e Miquelon" },
				{ LanguageId.ses, "Seŋ Piyer nda Mikelon" },
				{ LanguageId.sg, "Sên-Pyêre na Mikelöon" },
				{ LanguageId.shi, "ⵙⴰⵏⴱⵢⵉⵔ ⴷ ⵎⵉⴽⵍⵓⵏ" },
				{ LanguageId.si, "ශාන්ත පියරේ සහ මැකෝලන්" },
				{ LanguageId.sk, "Saint Pierre a Miquelon" },
				{ LanguageId.sl, "Sveta Peter in Mihael" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Pierre já Miquelon" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saint Pierre and Miquelon" },
				{ LanguageId.so, "St. Pierre iyo Miquelon" },
				{ LanguageId.sq, "Shën-Pier dhe Mikelon" },
				{ LanguageId.sr, "Сен Пјер и Микелон" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "St. Pierre le Miquelon" },
				{ LanguageId.su, "St Piér jeung Miquelon" },
				{ LanguageId.sv, "S:t Pierre och Miquelon" },
				{ LanguageId.sw, "Santapierre na Miquelon" },
				{ LanguageId.syr, "ܡܪܝ ܦܛܪܘܣ ܘܡܝܩܝܠܘܢ" },
				{ LanguageId.ta, "செயின்ட் பியர் & மிக்வேலான்" },
				{ LanguageId.te, "సెయింట్ పియెర్ మరియు మికెలాన్" },
				{ LanguageId.teo, "Santapieri na Mikeloni" },
				{ LanguageId.tg, "Сент-Пер ва Микелон" },
				{ LanguageId.th, "แซงปีแยร์และมีเกอลง" },
				{ LanguageId.ti, "ቅዱስ ፕየርን ሚከሎንን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sen-Pýer we Mikelon" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Piea mo Mikeloni" },
				{ LanguageId.tr, "Saint Pierre ve Miquelon" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сен-Пьер һәм Микелон" },
				{ LanguageId.twq, "Seŋ Piyer nda Mikelon" },
				{ LanguageId.tzm, "Santepyir d Mikelun" },
				{ LanguageId.ug, "ساينت پىيېر ۋە مىكېلون ئاراللىرى" },
				{ LanguageId.uk, "Сен-Пʼєр і Мікелон" },
				{ LanguageId.ur, "سینٹ پیئر اور میکلیئون" },
				{ LanguageId.uz, "Sen-Pyer va Mikelon" },
				{ LanguageId.vai, "ꔻꘋ ꔪꘂ ꗪ ꕆꔞꗏꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Saint Pierre và Miquelon" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Santapieri na Mikeloni" },
				{ LanguageId.wae, "St. Pierre und Miquelon" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Peer ak Mikeloŋ" },
				{ LanguageId.xh, "ESt. Pierre & Miquelon" },
				{ LanguageId.xog, "Senti Piyere ni Mikeloni" },
				{ LanguageId.yav, "sɛ́ŋpiɛ́l e mikelɔ́ŋ" },
				{ LanguageId.yi, "סט פּיער און מיקוועלאָן" },
				{ LanguageId.yo, "Pẹẹri ati mikuloni" },
				{ LanguageId.zgh, "ⵙⴰⵏⴱⵢⵉⵔ ⴷ ⵎⵉⴽⵍⵓⵏ" },
				{ LanguageId.zh, "圣皮埃尔和密克隆群岛" },
				{ LanguageId.zu, "i-Saint Pierre kanye ne-Miquelon" },
			}
		);
	}
}
