using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class PM
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "508",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "St. Pierre og Miquelon" },
				{ LanguageId.af, "St Pierre en Miquelon" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሴንት ፒየር እና ሚኬሎን" },
				{ LanguageId.ar, "سانت بيير وميكلون" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Müqəddəs Pyer və Mikelon" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сен-П'ер і Мікелон" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сен Пиер и Микелон" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট পিয়ের এবং মিকেলন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "St. Pierre i Miquelon" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sant Pere i Miqueló" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "St. Pierre ug Miquelon" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "San Pierre è Miquelonu" },
				{ LanguageId.cs, "St. Pierre a Miquelon" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "St. Pierre a Miquelon" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Pierre und Miquelon" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σεντ Πιέρ και Μικελόν" },
				{ LanguageId.en, "St. Pierre and Miquelon" },
				{ LanguageId.eo, "Sanktaj Petro kaj Mikelono" },
				{ LanguageId.es, "San Pedro y Miquelón" },
				{ LanguageId.et, "St Pierre ja Miquelon" },
				{ LanguageId.eu, "San Pierre eta Miquelon" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت پیر و میکلون" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "St. Pierre ja Miquelon" },
				{ LanguageId.fil, "St. Pierre at Miquelon" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Saint-Pierre et Miquelon" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint-Pierre en Miquelon" },
				{ LanguageId.ga, "St Pierre agus Miquelon" },
				{ LanguageId.gd, "Naomh Pierre agus Miquelon" },
				{ LanguageId.gl, "San Pedro e Miquelón" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ પિયર અને મિકેલન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "St. Pierre da Miquelon" },
				{ LanguageId.haw, "St. Pierre a me Miquelon" },
				{ LanguageId.he, "סנט פייר ומיקלון" },
				{ LanguageId.hi, "सेंट पियरे और मिकेलॉन" },
				{ LanguageId.hr, "St. Pierre i Miquelon" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "St. Pierre és Miquelon" },
				{ LanguageId.hy, "Սուրբ Պիեռ և Միկելոն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "St Pierre dan Miquelon" },
				{ LanguageId.ig, "St. Pierre na Miquelon" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "St Pierre og Miquelon" },
				{ LanguageId.it, "San Pietro e Miquelon" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サンピエール島ミクロン島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "St Pierre lan Miquelon" },
				{ LanguageId.ka, "წმინდა პიერი და მიკელონი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Әулие Пьер және Микелон" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាំង Pierre និង Miquelon" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಪಿಯರ್ ಮತ್ತು ಮಿಕ್ವೆಲಾನ್" },
				{ LanguageId.ko, "생피에르앤미클롱" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Пьер жана Микелон" },
				{ LanguageId.la, "Petrus et Miquelon" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "St Pierre a Miquelon" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊນ Pierre ແລະ Miquelon" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šv. Pjeras ir Mikelonas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Senpjērs un Mikelona" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Md Pierre sy Miquelon" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Pierre raua ko Miquelon" },
				{ LanguageId.mk, "Сент Пјер и Микелон" },
				{ LanguageId.ml, "സെൻ്റ് പിയറി ആൻഡ് മിക്വലോൺ" },
				{ LanguageId.mn, "Гэгээн Пьер ба Микелон" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट पियरे आणि मिकेलॉन" },
				{ LanguageId.ms, "St Pierre dan Miquelon" },
				{ LanguageId.mt, "San Pietru u Miquelon" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စိန့် Pierre နှင့် Miquelon" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "St. Pierre og Miquelon" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट पियरे र मिकेलोन" },
				{ LanguageId.nl, "St. Pierre en Miquelon" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଣ୍ଟ୍ ପିଆର ଏବଂ ମିକେଲନ୍ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਪੀਅਰੇ ਅਤੇ ਮਿਕਲੋਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Saint-Pierre i Miquelon" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ پییر او میکیلون" },
				{ LanguageId.pt, "São Pedro e Miquelon" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sf. Pierre și Miquelon" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сен-Пьер и Микелон" },
				{ LanguageId.rw, "Mutagatifu Pierre na Miquelon" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ پيئر ۽ ميڪيلون" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත Pierre සහ Miquelon" },
				{ LanguageId.sk, "Svätý Pierre a Miquelon" },
				{ LanguageId.sl, "St. Pierre in Miquelon" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "St. Pierre naMiquelon" },
				{ LanguageId.so, "St. Pierre iyo Miquelon" },
				{ LanguageId.sq, "Shën Pierre dhe Mikelon" },
				{ LanguageId.sr, "Сент Пјер и Микелон" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "St. Pierre le Miquelon" },
				{ LanguageId.su, "St Piér jeung Miquelon" },
				{ LanguageId.sv, "St Pierre och Miquelon" },
				{ LanguageId.sw, "St. Pierre na Miquelon" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "செயின்ட் பியர் மற்றும் மிக்குலோன்" },
				{ LanguageId.te, "సెయింట్ పియర్ మరియు మిక్వెలాన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент-Пьер ва Микелон" },
				{ LanguageId.th, "นักบุญปิแอร์และมีเกอลง" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Pýer we Mikelon" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "St.Pierre ve Miquelon" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент-Пьер һәм Микелон" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سانت پيېر ۋە مىكېلون" },
				{ LanguageId.uk, "Сен-П'єр і Мікелон" },
				{ LanguageId.ur, "سینٹ پیئر اور میکیلون" },
				{ LanguageId.uz, "Sent-Pyer va Mikelon" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thánh Pierre và Miquelon" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "eSt. Pierre naseMiquelon" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סט פּיער און מיקוועלאָן" },
				{ LanguageId.yo, "St. Pierre ati Miquelon" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣皮埃尔和密克隆群岛" },
				{ LanguageId.zu, "I-St. Pierre ne-Miquelon" },
			}
		);
	}
}
