// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PN
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "64",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Pitcairn" },
				{ LanguageId.af, "Pitcairneilande" },
				{ LanguageId.agq, "Kpitɨ̀kalè" },
				{ LanguageId.ak, "Pitkaan Nsupɔ" },
				{ LanguageId.am, "ፒትካኢርን ደሴቶች" },
				{ LanguageId.ar, "جزر بيتكيرن" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "পিটকেইৰ্ণ দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Pitkairni" },
				{ LanguageId.ast, "Islles Pitcairn" },
				{ LanguageId.az, "Pitkern adaları" },
				{ LanguageId.ba, "Питкэрн утрауҙары" },
				{ LanguageId.bas, "Pìdkaìrn" },
				{ LanguageId.be, "Астравы Піткэрн" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hupitkaini" },
				{ LanguageId.bg, "Острови Питкерн" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Pitikarini" },
				{ LanguageId.bn, "পিটকেয়ার্ন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Enez Pitcairn" },
				{ LanguageId.brx, "पिटकाईर्न द्वीप" },
				{ LanguageId.bs, "Pitkernska Ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Pitcairn" },
				{ LanguageId.ccp, "𑄛𑄨𑄇𑄴𑄇𑄬𑄠𑄢𑄴𑄚𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Питкэрн гӀайренаш" },
				{ LanguageId.ceb, "Pitcairn Islands" },
				{ LanguageId.cgg, "Pitkaini" },
				{ LanguageId.chr, "ᏈᎧᎵᏂ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی پیتکەرن" },
				{ LanguageId.co, "Pitcairn" },
				{ LanguageId.cs, "Pitcairnovy ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Pitcairn" },
				{ LanguageId.dav, "Pitkairni" },
				{ LanguageId.de, "Pitcairninseln" },
				{ LanguageId.dje, "Pitikarin" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pitcairnowe kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "པིཊ་ཀེ་ཡེརན་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Pitkairni" },
				{ LanguageId.ee, "Pitkairn ƒudomekpo nutome" },
				{ LanguageId.el, "Νήσοι Πίτκερν" },
				{ LanguageId.en, "Pitcairn Islands" },
				{ LanguageId.eo, "Pitkarna Insulo" },
				{ LanguageId.es, "Islas Pitcairn" },
				{ LanguageId.et, "Pitcairni saared" },
				{ LanguageId.eu, "Pitcairn uharteak" },
				{ LanguageId.ewo, "Pítə́kɛ́rɛnə" },
				{ LanguageId.fa, "جزایر پیت‌کرن" },
				{ LanguageId.ff, "Pitkern" },
				{ LanguageId.fi, "Pitcairn" },
				{ LanguageId.fil, "Pitcairn Islands" },
				{ LanguageId.fo, "Pitcairnoyggjar" },
				{ LanguageId.fr, "Îles Pitcairn" },
				{ LanguageId.fur, "Pitcairn" },
				{ LanguageId.fy, "Pitcairneilannen" },
				{ LanguageId.ga, "Oileáin Pitcairn" },
				{ LanguageId.gd, "Eileanan Pheit a’ Chàirn" },
				{ LanguageId.gl, "Illas Pitcairn" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Pitggäärn" },
				{ LanguageId.gu, "પીટકૈર્ન આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Pitkairni" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Pitcairn" },
				{ LanguageId.haw, "Pitcairn" },
				{ LanguageId.he, "איי פיטקרן" },
				{ LanguageId.hi, "पिटकैर्न द्वीपसमूह" },
				{ LanguageId.hr, "Pitcairnovi Otoci" },
				{ LanguageId.hsb, "Pitcairnowe kupy" },
				{ LanguageId.hu, "Pitcairn-szigetek" },
				{ LanguageId.hy, "Պիտկեռն կղզիներ" },
				{ LanguageId.ia, "Insulas Pitcairn" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Pitcairn" },
				{ LanguageId.ig, "Agwaetiti Pitcairn" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Pitcairn-eyjar" },
				{ LanguageId.it, "Isole Pitcairn" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ピトケアン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Pitkairni" },
				{ LanguageId.jv, "Kapuloan Pitcairn" },
				{ LanguageId.ka, "პიტკერნის კუნძულები" },
				{ LanguageId.kab, "Pitkarin" },
				{ LanguageId.kam, "Pitkairni" },
				{ LanguageId.kde, "Pitikeluni" },
				{ LanguageId.kea, "Ilhas Pitkairn" },
				{ LanguageId.khq, "Pitikarin" },
				{ LanguageId.ki, "Pitkairni" },
				{ LanguageId.kk, "Питкэрн аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Pitcairn" },
				{ LanguageId.km, "កោះ​ភីតកាន" },
				{ LanguageId.kn, "ಪಿಟ್‌ಕೈರ್ನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "핏케언 제도" },
				{ LanguageId.kok, "पिटकॅर्न जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "پِٹکیرٕنؠ جٔزیٖرٕ" },
				{ LanguageId.ksb, "Pitkailni" },
				{ LanguageId.ksf, "pitkɛ́n" },
				{ LanguageId.ksh, "de Pitkärn-Ensel" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Питкэрн аралдары" },
				{ LanguageId.la, "Pitcairn" },
				{ LanguageId.lag, "Patikaírini" },
				{ LanguageId.lb, "Pitcairninselen" },
				{ LanguageId.lg, "Pitikeeni" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Pikairni" },
				{ LanguageId.lo, "ໝູ່ເກາະພິດແຄນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Pitkerno salos" },
				{ LanguageId.luo, "Pitcairn" },
				{ LanguageId.luy, "Pitkairni" },
				{ LanguageId.lv, "Pitkērnas salas" },
				{ LanguageId.mai, "पिटकेयर्न द्वीपसमूह" },
				{ LanguageId.mas, "Pitkairni" },
				{ LanguageId.mer, "Pitkairni" },
				{ LanguageId.mfe, "Pitcairn" },
				{ LanguageId.mg, "Pitkairn" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Pitikeina" },
				{ LanguageId.mk, "Питкернски Острови" },
				{ LanguageId.ml, "പിറ്റ്‌കെയ്‌ൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Питкэрн арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पिटकैर्न बेटे" },
				{ LanguageId.ms, "Kepulauan Pitcairn" },
				{ LanguageId.mt, "Gżejjer Pitcairn" },
				{ LanguageId.mua, "Pitkairn" },
				{ LanguageId.my, "ပစ်တ်ကိန်းကျွန်းစု" },
				{ LanguageId.mzn, "پیتکارین جزایر" },
				{ LanguageId.naq, "Pitcairn" },
				{ LanguageId.nb, "Pitcairnøyene" },
				{ LanguageId.nd, "Pitcairn" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पिटकाइर्न टापुहरु" },
				{ LanguageId.nl, "Pitcairneilanden" },
				{ LanguageId.nmg, "Pitkairn" },
				{ LanguageId.nn, "Pitcairn" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߔߌߕߑߞߍ߲ ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Pitkaini" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Pitikaayirin" },
				{ LanguageId.or, "ପିଟକାଇରିନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪਿਟਕੇਰਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Pítkén Aílands" },
				{ LanguageId.pl, "Pitcairn" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "پيټکيرن ټاپوګان" },
				{ LanguageId.pt, "Ilhas Pitcairn" },
				{ LanguageId.qu, "Islas Pitcairn" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Pitcairn" },
				{ LanguageId.rn, "Pitikeyirini" },
				{ LanguageId.ro, "Insulele Pitcairn" },
				{ LanguageId.rof, "Pitkairni" },
				{ LanguageId.ru, "о-ва Питкэрн" },
				{ LanguageId.rw, "Pitcairn" },
				{ LanguageId.rwk, "Pitkairni" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Pitkairni" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Pitikailini" },
				{ LanguageId.sd, "پٽڪئرن ٻيٽ" },
				{ LanguageId.se, "Pitcairn" },
				{ LanguageId.seh, "Pitcairn" },
				{ LanguageId.ses, "Pitikarin" },
				{ LanguageId.sg, "Pitikêrni" },
				{ LanguageId.shi, "ⴱⵉⵜⴽⴰⵢⵔⵏ" },
				{ LanguageId.si, "පිට්කෙය්න් දූපත්" },
				{ LanguageId.sk, "Pitcairnove ostrovy" },
				{ LanguageId.sl, "Pitcairn" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Pitcairn" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Pitcairn" },
				{ LanguageId.so, "Bitkairn" },
				{ LanguageId.sq, "Ishujt Pitkern" },
				{ LanguageId.sr, "Питкерн" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Pitcairn" },
				{ LanguageId.su, "Pitcairn" },
				{ LanguageId.sv, "Pitcairnöarna" },
				{ LanguageId.sw, "Visiwa vya Pitcairn" },
				{ LanguageId.syr, "ܓܙܝܪ̈ܬܐ ܕܦܝܬܟܐܪܢ" },
				{ LanguageId.ta, "பிட்கெய்ர்ன் தீவுகள்" },
				{ LanguageId.te, "పిట్‌కెయిర్న్ దీవులు" },
				{ LanguageId.teo, "Pitkairni" },
				{ LanguageId.tg, "Ҷазираҳои Питкейрн" },
				{ LanguageId.th, "หมู่เกาะพิตแคร์น" },
				{ LanguageId.ti, "ደሴታት ፒትካርን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Pitkern adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Pitikeni" },
				{ LanguageId.tr, "Pitcairn Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Питкэрн утраулары" },
				{ LanguageId.twq, "Pitikarin" },
				{ LanguageId.tzm, "Pitkirn" },
				{ LanguageId.ug, "پىتكايرن ئاراللىرى" },
				{ LanguageId.uk, "Острови Піткерн" },
				{ LanguageId.ur, "پٹکائرن جزائر" },
				{ LanguageId.uz, "Pitkern orollari" },
				{ LanguageId.vai, "ꔪꔳꕪꕆ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Pitcairn" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Pitkairni" },
				{ LanguageId.wae, "Pitcairn" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Pitkayirn" },
				{ LanguageId.xh, "EPitcairn Islands" },
				{ LanguageId.xog, "Pitikeeni" },
				{ LanguageId.yav, "pitikɛ́ɛlínɛ́" },
				{ LanguageId.yi, "פּיטקערן אינזלען" },
				{ LanguageId.yo, "Pikarini" },
				{ LanguageId.zgh, "ⴱⵉⵜⴽⴰⵢⵔⵏ" },
				{ LanguageId.zh, "皮特凯恩群岛" },
				{ LanguageId.zu, "i-Pitcairn Islands" },
			}
		);
	}
}
