using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class PR
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Puerto Rico" },
				{ LanguageId.af, "Puerto Rico" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ፑኤርቶ ሪኮ" },
				{ LanguageId.ar, "بورتوريكو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Puerto Riko" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Пуэрта-Рыка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Пуерто Рико" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পুয়ের্তো রিকো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Puerto Rico" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Puerto Rico" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Puerto Rico" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Puerto Rico" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Portu Riccu" },
				{ LanguageId.cs, "Portoriko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Puerto Rico" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Puerto Rico" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Πουέρτο Ρίκο" },
				{ LanguageId.en, "Puerto Rico" },
				{ LanguageId.eo, "Porto-Riko" },
				{ LanguageId.es, "Puerto Rico" },
				{ LanguageId.et, "Puerto Rico" },
				{ LanguageId.eu, "Puerto Rico" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "پورتوریکو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Puerto Rico" },
				{ LanguageId.fil, "Puerto Rico" },
				{ LanguageId.fo, "Puerto Riko" },
				{ LanguageId.fr, "Porto Rico" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Porto Riko" },
				{ LanguageId.ga, "Pórtó Ríce" },
				{ LanguageId.gd, "Puerto Rico" },
				{ LanguageId.gl, "Porto Rico" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "પ્યુઅર્ટો રિકો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Puerto Rico" },
				{ LanguageId.haw, "Pokoliko" },
				{ LanguageId.he, "פוארטו ריקו" },
				{ LanguageId.hi, "प्यूर्टो रिको" },
				{ LanguageId.hr, "Portoriko" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Puerto Rico" },
				{ LanguageId.hy, "Պուերտո Ռիկո" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Puerto Riko" },
				{ LanguageId.ig, "Puerto Rico" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Púertó Ríkó" },
				{ LanguageId.it, "Porto Rico" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "プエルトリコ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Puerto Rico" },
				{ LanguageId.ka, "პუერტო რიკო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Пуэрто-Рико" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ព័រតូរីកូ" },
				{ LanguageId.kn, "ಪೋರ್ಟೊ ರಿಕೊ" },
				{ LanguageId.ko, "푸에르토 리코" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Пуэрто Рико" },
				{ LanguageId.la, "Puerto Rico" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Puerto Rico" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເປີໂຕຣິໂກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Puerto Rikas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Puertoriko" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Puerto Rico" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Puerto Rico" },
				{ LanguageId.mk, "Порторико" },
				{ LanguageId.ml, "പ്യൂർട്ടോ റിക്കോ" },
				{ LanguageId.mn, "Пуэрто-Рико" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पोर्तु रिको" },
				{ LanguageId.ms, "Puerto Rico" },
				{ LanguageId.mt, "Puerto Rico" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ပွာတိုရီကို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Puerto Rico" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पोर्टो रिको" },
				{ LanguageId.nl, "Puerto Rico" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Puerto Rico" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ପୁଏର୍ତୋ ରିକୋ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪੋਰਟੋ ਰੀਕੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Portoryko" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "پورتو ریکو" },
				{ LanguageId.pt, "Porto Rico" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Puerto Rico" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Пуэрто-Рико" },
				{ LanguageId.rw, "Porto Rico" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "پروٽو رائڪو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "පෝටෝ රිකෝ" },
				{ LanguageId.sk, "Portoriko" },
				{ LanguageId.sl, "Portoriko" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Pota Riko" },
				{ LanguageId.so, "Puerto Rico" },
				{ LanguageId.sq, "Porto Riko" },
				{ LanguageId.sr, "Порторико" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Puerto Rico" },
				{ LanguageId.su, "Puerto Rico" },
				{ LanguageId.sv, "Puerto Rico" },
				{ LanguageId.sw, "Puerto Rico" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "போர்ட்டோ ரிக்கோ" },
				{ LanguageId.te, "ప్యూర్టో రికో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Пуэрто-Рико" },
				{ LanguageId.th, "เปอร์โตริโก้" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Puerto Riko" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Porto Riko" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Пуэрто-Рико" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "پورتو رىكو" },
				{ LanguageId.uk, "Пуерто Ріко" },
				{ LanguageId.ur, "پورٹو ریکو" },
				{ LanguageId.uz, "Puerto-Riko" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Puerto Rico" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Poto Rikho" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פּאָרטאַ ריקאָ" },
				{ LanguageId.yo, "Puẹto Riko" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "波多黎各" },
				{ LanguageId.zu, "E-Puerto Rico" },
			}
		);
	}
}
