// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PR
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Puerto Rico" },
				{ LanguageId.af, "Puerto Rico" },
				{ LanguageId.agq, "Kpǒto Leko" },
				{ LanguageId.ak, "Puɛto Riko" },
				{ LanguageId.am, "ፑዌርቶ ሪኮ" },
				{ LanguageId.ar, "بورتوريكو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "পুৱেৰ্টো ৰিকো" },
				{ LanguageId.asa, "Pwetoriko" },
				{ LanguageId.ast, "Puertu Ricu" },
				{ LanguageId.az, "Puerto Riko" },
				{ LanguageId.ba, "Пуэрто-Рико" },
				{ LanguageId.bas, "Pɔ̀rtò Rikò" },
				{ LanguageId.be, "Пуэрта-Рыка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hupwetoriko" },
				{ LanguageId.bg, "Пуерто Рико" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Pɔrotoriko" },
				{ LanguageId.bn, "পুয়ের্তো রিকো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Puerto Rico" },
				{ LanguageId.brx, "पुवेर्ट’ रीक’" },
				{ LanguageId.bs, "Porto Riko" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Puerto Rico" },
				{ LanguageId.ccp, "𑄛𑄪𑄠𑄬𑄢𑄴𑄖𑄮 𑄢𑄨𑄇𑄮" },
				{ LanguageId.ce, "Пуэрто-Рико" },
				{ LanguageId.ceb, "Puerto Rico" },
				{ LanguageId.cgg, "Pwetoriko" },
				{ LanguageId.chr, "ᏇᎡᏙ ᎵᎢᎪ" },
				{ LanguageId.ckb, "پۆرتۆڕیکۆ" },
				{ LanguageId.co, "Portu Riccu" },
				{ LanguageId.cs, "Portoriko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Puerto Rico" },
				{ LanguageId.dav, "Pwetoriko" },
				{ LanguageId.de, "Puerto Rico" },
				{ LanguageId.dje, "Porto Riko" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Puerto Rico" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "པུ་འེར་ཊོ་རི་ཁོ" },
				{ LanguageId.ebu, "Pwetoriko" },
				{ LanguageId.ee, "Puerto Riko nutome" },
				{ LanguageId.el, "Πουέρτο Ρίκο" },
				{ LanguageId.en, "Puerto Rico" },
				{ LanguageId.eo, "Puertoriko" },
				{ LanguageId.es, "Puerto Rico" },
				{ LanguageId.et, "Puerto Rico" },
				{ LanguageId.eu, "Puerto Rico" },
				{ LanguageId.ewo, "Pwɛrəto Ríko" },
				{ LanguageId.fa, "پورتوریکو" },
				{ LanguageId.ff, "Porto Rikoo" },
				{ LanguageId.fi, "Puerto Rico" },
				{ LanguageId.fil, "Puerto Rico" },
				{ LanguageId.fo, "Puerto Riko" },
				{ LanguageId.fr, "Porto Rico" },
				{ LanguageId.fur, "Porto Rico" },
				{ LanguageId.fy, "Puerto Rico" },
				{ LanguageId.ga, "Pórtó Ríce" },
				{ LanguageId.gd, "Porto Rìceo" },
				{ LanguageId.gl, "Porto Rico" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Puerto Riggo" },
				{ LanguageId.gu, "પ્યુઅર્ટો રિકો" },
				{ LanguageId.guz, "Pwetoriko" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Porto Riko" },
				{ LanguageId.haw, "Pokoliko" },
				{ LanguageId.he, "פוארטו ריקו" },
				{ LanguageId.hi, "पोर्टो रिको" },
				{ LanguageId.hr, "Portoriko" },
				{ LanguageId.hsb, "Puerto Rico" },
				{ LanguageId.hu, "Puerto Rico" },
				{ LanguageId.hy, "Պուերտո Ռիկո" },
				{ LanguageId.ia, "Porto Rico" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Puerto Riko" },
				{ LanguageId.ig, "Puerto Rico" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Púertó Ríkó" },
				{ LanguageId.it, "Portorico" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "プエルトリコ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Pwetoriko" },
				{ LanguageId.jv, "Puèrto Riko" },
				{ LanguageId.ka, "პუერტო-რიკო" },
				{ LanguageId.kab, "Purtu Riku" },
				{ LanguageId.kam, "Pwetoriko" },
				{ LanguageId.kde, "Pwetoliko" },
				{ LanguageId.kea, "Portu Riku" },
				{ LanguageId.khq, "Porto Riko" },
				{ LanguageId.ki, "Pwetoriko" },
				{ LanguageId.kk, "Пуэрто-Рико" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Puerto Rico" },
				{ LanguageId.km, "ព័រតូរីកូ" },
				{ LanguageId.kn, "ಪ್ಯೂರ್ಟೋ ರಿಕೊ" },
				{ LanguageId.ko, "푸에르토리코" },
				{ LanguageId.kok, "पोर्टो रिको" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "پٔرٹو رِکو" },
				{ LanguageId.ksb, "Pwetoliko" },
				{ LanguageId.ksf, "pɔtoríko" },
				{ LanguageId.ksh, "Pochtoriko" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Пуэрто-Рико" },
				{ LanguageId.la, "Puerto Rico" },
				{ LanguageId.lag, "Pwetorɨ́ɨko" },
				{ LanguageId.lb, "Puerto Rico" },
				{ LanguageId.lg, "Potoriko" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Pɔtoriko" },
				{ LanguageId.lo, "ເພືອໂຕ ຣິໂກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Puerto Rikas" },
				{ LanguageId.luo, "Puerto Rico" },
				{ LanguageId.luy, "Pwetoriko" },
				{ LanguageId.lv, "Puertoriko" },
				{ LanguageId.mai, "प्योर्टो रिको" },
				{ LanguageId.mas, "Pwetoriko" },
				{ LanguageId.mer, "Pwetoriko" },
				{ LanguageId.mfe, "Porto Rico" },
				{ LanguageId.mg, "Pôrtô Rikô" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Peta Riko" },
				{ LanguageId.mk, "Порторико" },
				{ LanguageId.ml, "പോർട്ടോ റിക്കോ" },
				{ LanguageId.mn, "Пуэрто-Рико" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "प्युएर्तो रिको" },
				{ LanguageId.ms, "Puerto Rico" },
				{ LanguageId.mt, "Puerto Rico" },
				{ LanguageId.mua, "Porto Riko" },
				{ LanguageId.my, "ပေါ်တိုရီကို" },
				{ LanguageId.mzn, "پورتوریکو" },
				{ LanguageId.naq, "Puerto Rico" },
				{ LanguageId.nb, "Puerto Rico" },
				{ LanguageId.nd, "Puerto Rico" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पुएर्टो रिको" },
				{ LanguageId.nl, "Puerto Rico" },
				{ LanguageId.nmg, "Puɛrto Riko" },
				{ LanguageId.nn, "Puerto Rico" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߔߐߙߑߕߏ߫-ߙߌߞߏ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Pwetoriko" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Poortaar Riikoo" },
				{ LanguageId.or, "ପୁଏର୍ତ୍ତୋ ରିକୋ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪਿਊਰਟੋ ਰਿਕੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Puẹ́rto Ríkọ" },
				{ LanguageId.pl, "Portoryko" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "پورتو ریکو" },
				{ LanguageId.pt, "Porto Rico" },
				{ LanguageId.qu, "Puerto Rico" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Puerto Rico" },
				{ LanguageId.rn, "Puwetoriko" },
				{ LanguageId.ro, "Puerto Rico" },
				{ LanguageId.rof, "Pwetoriko" },
				{ LanguageId.ru, "Пуэрто-Рико" },
				{ LanguageId.rw, "Porto Rico" },
				{ LanguageId.rwk, "Pwetoriko" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Pwetoriko" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Pwetoliko" },
				{ LanguageId.sd, "پيوئرٽو ريڪو" },
				{ LanguageId.se, "Puerto Rico" },
				{ LanguageId.seh, "Porto Rico" },
				{ LanguageId.ses, "Porto Riko" },
				{ LanguageId.sg, "Porto Rîko" },
				{ LanguageId.shi, "ⴱⵓⵔⵜⵓ ⵔⵉⴽⵓ" },
				{ LanguageId.si, "පුවර්ටෝ රිකෝ" },
				{ LanguageId.sk, "Portoriko" },
				{ LanguageId.sl, "Portoriko" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Puerto Rico" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Puerto Rico" },
				{ LanguageId.so, "Bueerto Riiko" },
				{ LanguageId.sq, "Porto-Riko" },
				{ LanguageId.sr, "Порторико" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Puerto Rico" },
				{ LanguageId.su, "Puerto Rico" },
				{ LanguageId.sv, "Puerto Rico" },
				{ LanguageId.sw, "Puerto Rico" },
				{ LanguageId.syr, "ܦܘܐܪܛܘ ܪܝܩܘ" },
				{ LanguageId.ta, "பியூர்டோ ரிகோ" },
				{ LanguageId.te, "ప్యూర్టో రికో" },
				{ LanguageId.teo, "Pwetoriko" },
				{ LanguageId.tg, "Пуэрто-Рико" },
				{ LanguageId.th, "เปอร์โตริโก" },
				{ LanguageId.ti, "ፖርቶ ሪኮ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Puerto-Riko" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Puēto Liko" },
				{ LanguageId.tr, "Porto Riko" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Пуэрто-Рико" },
				{ LanguageId.twq, "Porto Riko" },
				{ LanguageId.tzm, "Purturiku" },
				{ LanguageId.ug, "پۇئېرتو رىكو" },
				{ LanguageId.uk, "Пуерто-Рико" },
				{ LanguageId.ur, "پیورٹو ریکو" },
				{ LanguageId.uz, "Puerto-Riko" },
				{ LanguageId.vai, "ꔪꖳꕿ ꔸꖏ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Puerto Rico" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Pwetoriko" },
				{ LanguageId.wae, "Puerto Rico" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Porto Riko" },
				{ LanguageId.xh, "EPuerto Rico" },
				{ LanguageId.xog, "Potoriko" },
				{ LanguageId.yav, "pólótolíko" },
				{ LanguageId.yi, "פּארטא־ריקא" },
				{ LanguageId.yo, "Pọto Riko" },
				{ LanguageId.zgh, "ⴱⵓⵔⵜⵓ ⵔⵉⴽⵓ" },
				{ LanguageId.zh, "波多黎各" },
				{ LanguageId.zu, "i-Puerto Rico" },
			}
		);
	}
}
