// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class PS
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "970",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "Falastiin" },
				{ LanguageId.da, "De palæstinensiske områder" },
				{ LanguageId.af, "Palestynse Grondgebiede" },
				{ LanguageId.agq, "Adzɨmā kɨ ŋgùŋ kɨ Palɛsɨtɨnyia à kɨ Gazà kò" },
				{ LanguageId.ak, "Palestaen West Bank ne Gaza" },
				{ LanguageId.am, "የፍልስጤም ግዛት" },
				{ LanguageId.ar, "الأراضي الفلسطينية" },
				{ LanguageId.arn, "Palestina" },
				{ LanguageId.@as, "ফিলিস্তিন অঞ্চল" },
				{ LanguageId.asa, "Palestina" },
				{ LanguageId.ast, "Territorios Palestinos" },
				{ LanguageId.az, "Fələstin Əraziləri" },
				{ LanguageId.ba, "Фәләстин территориялары" },
				{ LanguageId.bas, "Pàlɛ̀htinà Hyɔ̀ŋg nì Gazà" },
				{ LanguageId.be, "Палесцінскія Тэрыторыі" },
				{ LanguageId.bem, "Palestine" },
				{ LanguageId.bez, "Ulubali lwa Magharibi nu Gaza wa Hupalestina" },
				{ LanguageId.bg, "Палестински територии" },
				{ LanguageId.bin, "Palestine" },
				{ LanguageId.bm, "Palesitini" },
				{ LanguageId.bn, "প্যালেস্টাইন ভূখণ্ড" },
				{ LanguageId.bo, "པ་ལེ་སི་ཊན" },
				{ LanguageId.br, "Tiriadoù Palestina" },
				{ LanguageId.brx, "पेलेस्ताइननि ओनसोलफोर" },
				{ LanguageId.bs, "Palestinska Teritorija" },
				{ LanguageId.byn, "Palestine" },
				{ LanguageId.ca, "Territoris palestins" },
				{ LanguageId.ccp, "𑄜𑄨𑄣𑄨𑄌𑄴𑄖𑄨𑄚𑄴 𑄎𑄉𑄊𑄚𑄨" },
				{ LanguageId.ce, "ПалестӀинан латтанаш" },
				{ LanguageId.ceb, "Palestinian Territories" },
				{ LanguageId.cgg, "Palestine" },
				{ LanguageId.chr, "ᏆᎴᏍᏗᏂᎠᏂ ᏄᎬᏫᏳᏌᏕᎩ" },
				{ LanguageId.ckb, "ناوچە فەلەستینیەکان" },
				{ LanguageId.co, "Palestina" },
				{ LanguageId.cs, "Palestinská území" },
				{ LanguageId.cu, "Палестина" },
				{ LanguageId.cy, "Tiriogaethau Palesteinaidd" },
				{ LanguageId.dav, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.de, "Palästinensische Autonomiegebiete" },
				{ LanguageId.dje, "Palestine Dangay nda Gaaza" },
				{ LanguageId.doi, "Palestine" },
				{ LanguageId.dsb, "Palestinski awtonomny teritorium" },
				{ LanguageId.dua, "Palestine" },
				{ LanguageId.dv, "ފަލަސްތީން" },
				{ LanguageId.dz, "པེ་ལིསི་ཊི་ནི་ཡན་ཊེ་རི་ཐོ་རི" },
				{ LanguageId.ebu, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.ee, "Palestinia nutome" },
				{ LanguageId.el, "Παλαιστινιακά Εδάφη" },
				{ LanguageId.en, "Palestinian Territories" },
				{ LanguageId.eo, "Palestinaj teritorioj" },
				{ LanguageId.es, "Territorios Palestinos" },
				{ LanguageId.et, "Palestiina alad" },
				{ LanguageId.eu, "Palestinar Lurralde Okupatuak" },
				{ LanguageId.ewo, "Ǹnam Palɛsətín" },
				{ LanguageId.fa, "سرزمین‌های فلسطینی" },
				{ LanguageId.ff, "Palestiin Sisjordani e Gaasaa" },
				{ LanguageId.fi, "Palestiinalaisalue" },
				{ LanguageId.fil, "Palestinian Territories" },
				{ LanguageId.fo, "Palestinskt landøki" },
				{ LanguageId.fr, "Territoires palestiniens" },
				{ LanguageId.fur, "Teritoris palestinês" },
				{ LanguageId.fy, "Palestynske gebieten" },
				{ LanguageId.ga, "na Críocha Palaistíneacha" },
				{ LanguageId.gd, "Ùghdarras nam Palastaineach" },
				{ LanguageId.gl, "Territorios Palestinos" },
				{ LanguageId.gn, "Palestina" },
				{ LanguageId.gsw, "Paläschtinänsischi Gebiet" },
				{ LanguageId.gu, "પેલેસ્ટિનિયન ટેરિટરી" },
				{ LanguageId.guz, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.gv, "Palesteen" },
				{ LanguageId.ha, "Yankunan Palasɗinu" },
				{ LanguageId.haw, "Palesetine" },
				{ LanguageId.he, "השטחים הפלסטיניים" },
				{ LanguageId.hi, "फ़िलिस्तीनी क्षेत्र" },
				{ LanguageId.hr, "Palestinsko područje" },
				{ LanguageId.hsb, "Palestinski awtonomny teritorij" },
				{ LanguageId.hu, "Palesztin Autonómia" },
				{ LanguageId.hy, "Պաղեստինյան տարածքներ" },
				{ LanguageId.ia, "Territorios palestin" },
				{ LanguageId.ibb, "Palestine" },
				{ LanguageId.id, "Wilayah Palestina" },
				{ LanguageId.ig, "Mpaghara ndị Palestine" },
				{ LanguageId.ii, "Palestine" },
				{ LanguageId.@is, "Heimastjórnarsvæði Palestínumanna" },
				{ LanguageId.it, "Territori Palestinesi" },
				{ LanguageId.iu, "Palestine" },
				{ LanguageId.ja, "パレスチナ自治区" },
				{ LanguageId.jgo, "Palestine" },
				{ LanguageId.jmc, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.jv, "Tlatah Palèstina" },
				{ LanguageId.ka, "პალესტინის ტერიტორიები" },
				{ LanguageId.kab, "Falisṭin d Ɣezza" },
				{ LanguageId.kam, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.kde, "Nchingu wa Magalibi wa Mpanda wa kuGaza wa kuPales" },
				{ LanguageId.kea, "Tiritóriu palistinianu" },
				{ LanguageId.khq, "Palestine Dangay nda Gaaza" },
				{ LanguageId.ki, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.kk, "Палестина аймақтары" },
				{ LanguageId.kkj, "Palestine" },
				{ LanguageId.kl, "Palestina" },
				{ LanguageId.kln, "Emetab Palestine" },
				{ LanguageId.km, "ដែនដីប៉ាឡេស្ទីន" },
				{ LanguageId.kn, "ಪ್ಯಾಲೇಸ್ಟೇನಿಯನ್ ಪ್ರದೇಶಗಳು" },
				{ LanguageId.ko, "팔레스타인 지구" },
				{ LanguageId.kok, "पालेसटीन" },
				{ LanguageId.kr, "Palestine" },
				{ LanguageId.ks, "فلسطینی علاقٕہ" },
				{ LanguageId.ksb, "Ukingo wa Maghalibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.ksf, "zǝ palɛstínǝ" },
				{ LanguageId.ksh, "Palästina" },
				{ LanguageId.kw, "Palestina" },
				{ LanguageId.ky, "Палестина аймактары" },
				{ LanguageId.la, "Palaestina" },
				{ LanguageId.lag, "Mweemberera wa kʉmweeri wa Gáaza" },
				{ LanguageId.lb, "Palestinensesch Autonomiegebidder" },
				{ LanguageId.lg, "Palesitayini" },
				{ LanguageId.lkt, "Palestine" },
				{ LanguageId.ln, "Palɛsine" },
				{ LanguageId.lo, "ດິນແດນປາເລດສະຕິນ" },
				{ LanguageId.lrc, "فلستین" },
				{ LanguageId.lt, "Palestinos teritorija" },
				{ LanguageId.luo, "Palestinian West Bank gi Gaza" },
				{ LanguageId.luy, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.lv, "Palestīnas teritorijas" },
				{ LanguageId.mai, "फिलिस्तीनी क्षेत्र" },
				{ LanguageId.mas, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.mer, "Rũtere rwa Westi banki na Gaza cia Palestina" },
				{ LanguageId.mfe, "Teritwar Palestinn" },
				{ LanguageId.mg, "Palestina" },
				{ LanguageId.mgo, "Palestine" },
				{ LanguageId.mi, "Ngā Rohe o Parihitini" },
				{ LanguageId.mk, "Палестински Територии" },
				{ LanguageId.ml, "പാലസ്‌തീൻ പ്രദേശങ്ങൾ" },
				{ LanguageId.mn, "Палестины нутаг дэвсгэр" },
				{ LanguageId.mni, "Palestine" },
				{ LanguageId.moh, "Palestine" },
				{ LanguageId.mr, "पॅलेस्टिनियन प्रदेश" },
				{ LanguageId.ms, "Wilayah Palestin" },
				{ LanguageId.mt, "it-Territorji Palestinjani" },
				{ LanguageId.mua, "Sǝr Palestiniya" },
				{ LanguageId.my, "ပါလက်စတိုင်း ပိုင်နက်" },
				{ LanguageId.mzn, "فلسطین ِسرزمین" },
				{ LanguageId.naq, "Palestinian West Bank and Gaza" },
				{ LanguageId.nb, "Det palestinske området" },
				{ LanguageId.nd, "Palestinian West Bank and Gaza" },
				{ LanguageId.nds, "Palästina" },
				{ LanguageId.ne, "प्यालेस्टिनी भू-भागहरू" },
				{ LanguageId.nl, "Palestijnse gebieden" },
				{ LanguageId.nmg, "Palɛstin" },
				{ LanguageId.nn, "Det palestinske området" },
				{ LanguageId.nnh, "Palestine" },
				{ LanguageId.nqo, "ߔߊߟߍߛߑߕߌߣ ߞߣߍ" },
				{ LanguageId.nr, "Palestine" },
				{ LanguageId.nso, "Palestine" },
				{ LanguageId.nus, "Palestine" },
				{ LanguageId.nyn, "Parestiina na Gaza" },
				{ LanguageId.oc, "Palestina" },
				{ LanguageId.om, "Daangaawwan Paalestaayin" },
				{ LanguageId.or, "ପାଲେଷ୍ଟେନିୟ ଭୂଭାଗ" },
				{ LanguageId.os, "Палестинæ" },
				{ LanguageId.pa, "ਫਿਲਸਤੀਨੀ ਖਿੱਤੇ" },
				{ LanguageId.pap, "Palestina" },
				{ LanguageId.pcm, "Pálẹ́staín Éria-dẹm" },
				{ LanguageId.pl, "Terytoria Palestyńskie" },
				{ LanguageId.prg, "Palestina" },
				{ LanguageId.ps, "فلسطیني سيمې" },
				{ LanguageId.pt, "Territórios palestinos" },
				{ LanguageId.qu, "Palestina Kamachikuq" },
				{ LanguageId.quc, "Palestine" },
				{ LanguageId.rm, "Territori Palestinais" },
				{ LanguageId.rn, "Palesitina Wesitibanka na Gaza" },
				{ LanguageId.ro, "Teritoriile Palestiniene" },
				{ LanguageId.rof, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.ru, "Палестинские территории" },
				{ LanguageId.rw, "Palesitina" },
				{ LanguageId.rwk, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.sa, "फलस्तीन" },
				{ LanguageId.sah, "Палестина" },
				{ LanguageId.saq, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.sat, "Palestine" },
				{ LanguageId.sbp, "Munjema gwa Kusikha nu Luvala lwa Gasa lwa Palesit" },
				{ LanguageId.sd, "فلسطيني علائقا" },
				{ LanguageId.se, "Palestina" },
				{ LanguageId.seh, "Território da Palestina" },
				{ LanguageId.ses, "Palestine Dangay nda Gaaza" },
				{ LanguageId.sg, "Sêse tî Palestîni" },
				{ LanguageId.shi, "ⴰⴳⵎⵎⴰⴹ ⵏ ⵜⴰⴳⵓⵜ ⴷ ⵖⵣⵣⴰ" },
				{ LanguageId.si, "පලස්තීන රාජ්‍යය" },
				{ LanguageId.sk, "Palestínske územia" },
				{ LanguageId.sl, "Palestinsko ozemlje" },
				{ LanguageId.sma, "Palestina" },
				{ LanguageId.smj, "Palestina" },
				{ LanguageId.smn, "Palestina" },
				{ LanguageId.sms, "Palestina" },
				{ LanguageId.sn, "Palestine" },
				{ LanguageId.so, "Dhulka Falastiiniyiinta daanta galbeed iyo marinka qasa" },
				{ LanguageId.sq, "Territoret Palestineze" },
				{ LanguageId.sr, "Палестинске територије" },
				{ LanguageId.ss, "Palestine" },
				{ LanguageId.ssy, "Palestine" },
				{ LanguageId.st, "Palestine" },
				{ LanguageId.su, "Paléstina" },
				{ LanguageId.sv, "Palestinska territorierna" },
				{ LanguageId.sw, "Maeneo ya Palestina" },
				{ LanguageId.syr, "ܐܬܪ̈ܘܬܐ ܕܦܠܣܛܝܢ" },
				{ LanguageId.ta, "பாலஸ்தீனிய பிரதேசங்கள்" },
				{ LanguageId.te, "పాలస్తీనియన్ ప్రాంతాలు" },
				{ LanguageId.teo, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.tg, "Қаламравҳои Фаластинӣ" },
				{ LanguageId.th, "ดินแดนปาเลสไตน์" },
				{ LanguageId.ti, "ግዝኣታት ፍልስጤም" },
				{ LanguageId.tig, "Palestine" },
				{ LanguageId.tk, "Palestina territoriýasy" },
				{ LanguageId.tn, "Palestine" },
				{ LanguageId.to, "Potu Palesitaine" },
				{ LanguageId.tr, "Filistin Bölgeleri" },
				{ LanguageId.ts, "Palestine" },
				{ LanguageId.tt, "Фәләстин территорияләре" },
				{ LanguageId.twq, "Palestine Dangay nda Gaaza" },
				{ LanguageId.tzm, "Agemmaḍ Ugut d Ɣazza Ifilisṭiniyen" },
				{ LanguageId.ug, "پەلەستىن زېمىنى" },
				{ LanguageId.uk, "Палестинські території" },
				{ LanguageId.ur, "فلسطینی خطے" },
				{ LanguageId.uz, "Falastin hududlari" },
				{ LanguageId.vai, "ꕐꔒꔻꔳꕯ ꔎꔒ ꕀꔤ ꗛꔤ ꕞ ꗱ ꗪ ꕭꕌꕤ" },
				{ LanguageId.ve, "Palestine" },
				{ LanguageId.vi, "Lãnh thổ Palestine" },
				{ LanguageId.vo, "Palestän" },
				{ LanguageId.vun, "Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina" },
				{ LanguageId.wae, "Paleština" },
				{ LanguageId.wal, "Palestine" },
				{ LanguageId.wo, "réew yu Palestine" },
				{ LanguageId.xh, "IPalestinian Territories" },
				{ LanguageId.xog, "Palesitayini ni Gaza" },
				{ LanguageId.yav, "kitɔŋ ki palɛstíin" },
				{ LanguageId.yi, "פּאַלעסטינע" },
				{ LanguageId.yo, "Agbègbè ara Palẹsítínì" },
				{ LanguageId.zgh, "ⴰⴳⵎⵎⴰⴹ ⵏ ⵜⴰⴳⵓⵜ ⴷ ⵖⵣⵣⴰ" },
				{ LanguageId.zh, "巴勒斯坦领土" },
				{ LanguageId.zu, "i-Palestinian Territories" },
			}
		);
	}
}
