using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class RE
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "262",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Genforening" },
				{ LanguageId.af, "Reünie" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "እንደገና መገናኘት" },
				{ LanguageId.ar, "جمع شمل" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Yenidən birləşmə" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Уз'яднанне" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Обединение" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পুনর্মিলন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Reünion" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Reunion" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Reunió" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Reunion" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Riunione" },
				{ LanguageId.cs, "Shledání" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Aduniad" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Wiedervereinigung" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Επανένωση" },
				{ LanguageId.en, "Reunion" },
				{ LanguageId.eo, "Reunuiĝo" },
				{ LanguageId.es, "Reunión" },
				{ LanguageId.et, "Kokkutulek" },
				{ LanguageId.eu, "Bilera" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "تجدید دیدار" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "jälleennäkeminen" },
				{ LanguageId.fil, "Reunion" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Réunion" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Reuny" },
				{ LanguageId.ga, "teacht le chéile" },
				{ LanguageId.gd, "Coinneamh" },
				{ LanguageId.gl, "Reunión" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "રિયુનિયન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "haduwa" },
				{ LanguageId.haw, "Hui hou" },
				{ LanguageId.he, "איחוד" },
				{ LanguageId.hi, "रीयूनियन" },
				{ LanguageId.hr, "Ponovno sjedinjenje" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Reunion" },
				{ LanguageId.hy, "Վերամիավորում" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Reuni" },
				{ LanguageId.ig, "Nchikota" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Reunion" },
				{ LanguageId.it, "Riunione" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "再会" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Reuni" },
				{ LanguageId.ka, "გაერთიანება" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Кездесу" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ការជួបជុំគ្នា។" },
				{ LanguageId.kn, "ಪುನರ್ಮಿಲನ" },
				{ LanguageId.ko, "재결합" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Reunion" },
				{ LanguageId.la, "Reunion" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Reunioun" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Reunion" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Susijungimas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Atkalapvienošanās" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Reunion" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Huihuinga" },
				{ LanguageId.mk, "Повторно обединување" },
				{ LanguageId.ml, "റീയൂണിയൻ" },
				{ LanguageId.mn, "Дахин нэгдэх" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पुनर्मिलन" },
				{ LanguageId.ms, "Perjumpaan semula" },
				{ LanguageId.mt, "Reunion" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ပြန်လည်ဆုံဆည်းခြင်း။" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Gjenforening" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पुनर्मिलन" },
				{ LanguageId.nl, "Bijeenkomst" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ପୁନ un ମିଳନ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਰੀਯੂਨੀਅਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Zjazd" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بیا یوځای کیدل" },
				{ LanguageId.pt, "Reunião" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Reuniune" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Воссоединение" },
				{ LanguageId.rw, "Guhura" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ٻيهر اتحاد" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නැවත එක්වීම" },
				{ LanguageId.sk, "Reunion" },
				{ LanguageId.sl, "Ponovno srečanje" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Reunion" },
				{ LanguageId.so, "Isu imaatinka" },
				{ LanguageId.sq, "Ribashkim" },
				{ LanguageId.sr, "Реунион" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Ho kopana hape" },
				{ LanguageId.su, "Reuni" },
				{ LanguageId.sv, "Återförening" },
				{ LanguageId.sw, "Muungano" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "மீண்டும் இணைதல்" },
				{ LanguageId.te, "రీయూనియన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Боздид" },
				{ LanguageId.th, "เรอูนียง" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Duşuşyk" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Yeniden Birleşme" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Очрашу" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Reunion" },
				{ LanguageId.uk, "Возз'єднання" },
				{ LanguageId.ur, "ری یونین" },
				{ LanguageId.uz, "Uchrashuv" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Đoàn tụ" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Ukudibana kwakhona" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "רעוניאָן" },
				{ LanguageId.yo, "Ijọpọ" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "团圆" },
				{ LanguageId.zu, "Ukuhlangana kabusha" },
			}
		);
	}
}
