// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class RE
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "262",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Réunion" },
				{ LanguageId.af, "Réunion" },
				{ LanguageId.agq, "Lèyunyɔ̀ŋ" },
				{ LanguageId.ak, "Reyuniɔn" },
				{ LanguageId.am, "ሪዩኒየን" },
				{ LanguageId.ar, "روينيون" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ৰিইউনিয়ন" },
				{ LanguageId.asa, "Riyunioni" },
				{ LanguageId.ast, "Reunión" },
				{ LanguageId.az, "Reyunyon" },
				{ LanguageId.ba, "Реюньон" },
				{ LanguageId.bas, "Rèunyɔ̂ŋ" },
				{ LanguageId.be, "Рэюньён" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huliyunioni" },
				{ LanguageId.bg, "Реюнион" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Reyuɲɔŋ" },
				{ LanguageId.bn, "রিইউনিয়ন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Ar Reünion" },
				{ LanguageId.brx, "रेयूनियन" },
				{ LanguageId.bs, "Reunion" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illa de la Reunió" },
				{ LanguageId.ccp, "𑄢𑄨𑄃𑄨𑄃𑄪𑄚𑄨𑄠𑄧𑄚𑄴" },
				{ LanguageId.ce, "Реюньон" },
				{ LanguageId.ceb, "Reunion" },
				{ LanguageId.cgg, "Riyuniyoni" },
				{ LanguageId.chr, "ᎴᏳᏂᎠᏂ" },
				{ LanguageId.ckb, "ڕییوونیەن" },
				{ LanguageId.co, "Riunione" },
				{ LanguageId.cs, "Réunion" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Réunion" },
				{ LanguageId.dav, "Riyunioni" },
				{ LanguageId.de, "Réunion" },
				{ LanguageId.dje, "Reenioŋ" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Réunion" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "རེ་ཡུ་ནི་ཡོན" },
				{ LanguageId.ebu, "Riyunioni" },
				{ LanguageId.ee, "Réunion nutome" },
				{ LanguageId.el, "Ρεϊνιόν" },
				{ LanguageId.en, "Réunion" },
				{ LanguageId.eo, "Reunio" },
				{ LanguageId.es, "Reunión" },
				{ LanguageId.et, "Réunion" },
				{ LanguageId.eu, "Reunion" },
				{ LanguageId.ewo, "Reuniɔ́ŋ" },
				{ LanguageId.fa, "رئونیون" },
				{ LanguageId.ff, "Rewiñoo" },
				{ LanguageId.fi, "Réunion" },
				{ LanguageId.fil, "Réunion" },
				{ LanguageId.fo, "Réunion" },
				{ LanguageId.fr, "La Réunion" },
				{ LanguageId.fur, "Reunion" },
				{ LanguageId.fy, "Réunion" },
				{ LanguageId.ga, "La Réunion" },
				{ LanguageId.gd, "Réunion" },
				{ LanguageId.gl, "Reunión" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Reünioon" },
				{ LanguageId.gu, "રીયુનિયન" },
				{ LanguageId.guz, "Riyunioni" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Rawuniyan" },
				{ LanguageId.haw, "Hui hou" },
				{ LanguageId.he, "ראוניון" },
				{ LanguageId.hi, "रियूनियन" },
				{ LanguageId.hr, "Réunion" },
				{ LanguageId.hsb, "Réunion" },
				{ LanguageId.hu, "Réunion" },
				{ LanguageId.hy, "Ռեյունիոն" },
				{ LanguageId.ia, "Reunion" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Réunion" },
				{ LanguageId.ig, "Réunion" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Réunion" },
				{ LanguageId.it, "Riunione" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "レユニオン" },
				{ LanguageId.jgo, "Lɛ́uniyɔ̂n" },
				{ LanguageId.jmc, "Riyunioni" },
				{ LanguageId.jv, "Réunion" },
				{ LanguageId.ka, "რეუნიონი" },
				{ LanguageId.kab, "Timlilit" },
				{ LanguageId.kam, "Riyunioni" },
				{ LanguageId.kde, "Liyunioni" },
				{ LanguageId.kea, "Runion" },
				{ LanguageId.khq, "Reenioŋ" },
				{ LanguageId.ki, "Riyunioni" },
				{ LanguageId.kk, "Реюньон" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Réunion" },
				{ LanguageId.km, "រេអុយញ៉ុង" },
				{ LanguageId.kn, "ರಿಯೂನಿಯನ್" },
				{ LanguageId.ko, "레위니옹" },
				{ LanguageId.kok, "रेयुनियांव" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "رِیوٗنِیَن" },
				{ LanguageId.ksb, "Liyunioni" },
				{ LanguageId.ksf, "rɛunyɔŋ" },
				{ LanguageId.ksh, "Rehunjohn" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Реюньон" },
				{ LanguageId.la, "Reunion" },
				{ LanguageId.lag, "Reyunióoni" },
				{ LanguageId.lb, "Réunion" },
				{ LanguageId.lg, "Leyunyoni" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Lenyo" },
				{ LanguageId.lo, "ເຣອູນິຍົງ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Reunjonas" },
				{ LanguageId.luo, "Réunion" },
				{ LanguageId.luy, "Riyunioni" },
				{ LanguageId.lv, "Reinjona" },
				{ LanguageId.mai, "रियूनियन" },
				{ LanguageId.mas, "Riyunioni" },
				{ LanguageId.mer, "Riyunioni" },
				{ LanguageId.mfe, "Larenion" },
				{ LanguageId.mg, "Larenion" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Reūnio" },
				{ LanguageId.mk, "Рејунион" },
				{ LanguageId.ml, "റീയൂണിയൻ" },
				{ LanguageId.mn, "Реюнион" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "रियुनियन" },
				{ LanguageId.ms, "Reunion" },
				{ LanguageId.mt, "Réunion" },
				{ LanguageId.mua, "Sǝr Reunion" },
				{ LanguageId.my, "ရီယူနီယန်" },
				{ LanguageId.mzn, "رئونیون" },
				{ LanguageId.naq, "Réunion" },
				{ LanguageId.nb, "Réunion" },
				{ LanguageId.nd, "Réunion" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "रियुनियन" },
				{ LanguageId.nl, "Réunion" },
				{ LanguageId.nmg, "Réuniɔn" },
				{ LanguageId.nn, "Réunion" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߟߊ߬ߘߍ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Riyuniyoni" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Riyuuniyeen" },
				{ LanguageId.or, "ରିୟୁନିଅନ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਰਿਯੂਨੀਅਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Réyúniọn" },
				{ LanguageId.pl, "Reunion" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ریونین" },
				{ LanguageId.pt, "Reunião" },
				{ LanguageId.qu, "Reunión" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Réunion" },
				{ LanguageId.rn, "Amazinga ya Reyiniyo" },
				{ LanguageId.ro, "Réunion" },
				{ LanguageId.rof, "Riyunioni" },
				{ LanguageId.ru, "Реюньон" },
				{ LanguageId.rw, "Guhura" },
				{ LanguageId.rwk, "Riyunioni" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Riyunioni" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Liyunioni" },
				{ LanguageId.sd, "ري يونين" },
				{ LanguageId.se, "Réunion" },
				{ LanguageId.seh, "Reunião" },
				{ LanguageId.ses, "Reenioŋ" },
				{ LanguageId.sg, "Reinïon" },
				{ LanguageId.shi, "ⵔⵉⵢⵓⵏⵢⵓⵏ" },
				{ LanguageId.si, "රීයුනියන්" },
				{ LanguageId.sk, "Réunion" },
				{ LanguageId.sl, "Reunion" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Réunion" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Réunion" },
				{ LanguageId.so, "Riyuuniyon" },
				{ LanguageId.sq, "Reunion" },
				{ LanguageId.sr, "Реинион" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Ho kopana hape" },
				{ LanguageId.su, "Reuni" },
				{ LanguageId.sv, "Réunion" },
				{ LanguageId.sw, "Reunion" },
				{ LanguageId.syr, "ܪܝܘܢܝܘܢ" },
				{ LanguageId.ta, "ரீயூனியன்" },
				{ LanguageId.te, "రీయూనియన్" },
				{ LanguageId.teo, "Riyunioni" },
				{ LanguageId.tg, "Реюнион" },
				{ LanguageId.th, "เรอูนียง" },
				{ LanguageId.ti, "ርዩንየን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Reýunýon" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Lēunioni" },
				{ LanguageId.tr, "Reunion" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Реюньон" },
				{ LanguageId.twq, "Reenioŋ" },
				{ LanguageId.tzm, "Riyyunyun" },
				{ LanguageId.ug, "رېيۇنىيون" },
				{ LanguageId.uk, "Реюньйон" },
				{ LanguageId.ur, "ری یونین" },
				{ LanguageId.uz, "Reyunion" },
				{ LanguageId.vai, "ꔓꗠꖻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Réunion" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Riyunioni" },
				{ LanguageId.wae, "Réunion" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Reeñoo" },
				{ LanguageId.xh, "ERéunion" },
				{ LanguageId.xog, "Leyunyoni" },
				{ LanguageId.yav, "elewuniɔ́ŋ" },
				{ LanguageId.yi, "רעאוניאן" },
				{ LanguageId.yo, "Riuniyan" },
				{ LanguageId.zgh, "ⵔⵉⵢⵓⵏⵢⵓⵏ" },
				{ LanguageId.zh, "留尼汪" },
				{ LanguageId.zu, "i-Réunion" },
			}
		);
	}
}
