// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class RU
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "7",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Rusland" },
				{ LanguageId.af, "Rusland" },
				{ LanguageId.agq, "Loshìa" },
				{ LanguageId.ak, "Rɔhyea" },
				{ LanguageId.am, "ሩስያ" },
				{ LanguageId.ar, "روسيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ৰাছিয়া" },
				{ LanguageId.asa, "Uruthi" },
				{ LanguageId.ast, "Rusia" },
				{ LanguageId.az, "Rusiya" },
				{ LanguageId.ba, "Рәсәй" },
				{ LanguageId.bas, "Ruslànd" },
				{ LanguageId.be, "Расія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huulusi" },
				{ LanguageId.bg, "Русия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Irisi" },
				{ LanguageId.bn, "রাশিয়া" },
				{ LanguageId.bo, "ཨུ་རུ་སུ་" },
				{ LanguageId.br, "Rusia" },
				{ LanguageId.brx, "रासिया" },
				{ LanguageId.bs, "Rusija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Rússia" },
				{ LanguageId.ccp, "𑄢𑄥𑄨𑄠" },
				{ LanguageId.ce, "Росси" },
				{ LanguageId.ceb, "Russia" },
				{ LanguageId.cgg, "Rrasha" },
				{ LanguageId.chr, "ᏲᏂᎢ" },
				{ LanguageId.ckb, "ڕووسیا" },
				{ LanguageId.co, "Federazione Russa" },
				{ LanguageId.cs, "Rusko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Rwsia" },
				{ LanguageId.dav, "Urusi" },
				{ LanguageId.de, "Russland" },
				{ LanguageId.dje, "Iriši laboo" },
				{ LanguageId.doi, "रूस" },
				{ LanguageId.dsb, "Ruska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཨུ་རུ་སུ" },
				{ LanguageId.ebu, "Urusi" },
				{ LanguageId.ee, "Russia nutome" },
				{ LanguageId.el, "Ρωσία" },
				{ LanguageId.en, "Russia" },
				{ LanguageId.eo, "Rusujo" },
				{ LanguageId.es, "Rusia" },
				{ LanguageId.et, "Venemaa" },
				{ LanguageId.eu, "Errusia" },
				{ LanguageId.ewo, "Rúsian" },
				{ LanguageId.fa, "روسیه" },
				{ LanguageId.ff, "Riisii" },
				{ LanguageId.fi, "Venäjä" },
				{ LanguageId.fil, "Russia" },
				{ LanguageId.fo, "Russland" },
				{ LanguageId.fr, "Russie" },
				{ LanguageId.fur, "Russie" },
				{ LanguageId.fy, "Ruslân" },
				{ LanguageId.ga, "an Rúis" },
				{ LanguageId.gd, "An Ruis" },
				{ LanguageId.gl, "Rusia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Russland" },
				{ LanguageId.gu, "રશિયા" },
				{ LanguageId.guz, "Urusi" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Rasha" },
				{ LanguageId.haw, "Lūkia" },
				{ LanguageId.he, "רוסיה" },
				{ LanguageId.hi, "रूस" },
				{ LanguageId.hr, "Rusija" },
				{ LanguageId.hsb, "Ruska" },
				{ LanguageId.hu, "Oroszország" },
				{ LanguageId.hy, "Ռուսաստան" },
				{ LanguageId.ia, "Russia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Rusia" },
				{ LanguageId.ig, "Russia" },
				{ LanguageId.ii, "ꊉꇆꌦ" },
				{ LanguageId.@is, "Rússland" },
				{ LanguageId.it, "Russia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ロシア" },
				{ LanguageId.jgo, "Lusî" },
				{ LanguageId.jmc, "Urusi" },
				{ LanguageId.jv, "Rusia" },
				{ LanguageId.ka, "რუსეთი" },
				{ LanguageId.kab, "Rrus" },
				{ LanguageId.kam, "Urusi" },
				{ LanguageId.kde, "Ulusi" },
				{ LanguageId.kea, "Rúsia" },
				{ LanguageId.khq, "Iriši laboo" },
				{ LanguageId.ki, "Urusi" },
				{ LanguageId.kk, "Ресей" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Russia" },
				{ LanguageId.km, "រុស្ស៊ី" },
				{ LanguageId.kn, "ರಷ್ಯಾ" },
				{ LanguageId.ko, "러시아" },
				{ LanguageId.kok, "रूस" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "روٗس" },
				{ LanguageId.ksb, "Ulusi" },
				{ LanguageId.ksf, "risí" },
				{ LanguageId.ksh, "Rußland" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Россия" },
				{ LanguageId.la, "Foedus Russicum" },
				{ LanguageId.lag, "Urúusi" },
				{ LanguageId.lb, "Russland" },
				{ LanguageId.lg, "Lasa" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Risí" },
				{ LanguageId.lo, "ຣັດເຊຍ" },
				{ LanguageId.lrc, "روٙسیە" },
				{ LanguageId.lt, "Rusija" },
				{ LanguageId.luo, "Russia" },
				{ LanguageId.luy, "Urusi" },
				{ LanguageId.lv, "Krievija" },
				{ LanguageId.mai, "रूस" },
				{ LanguageId.mas, "Urusi" },
				{ LanguageId.mer, "Rashia" },
				{ LanguageId.mfe, "Larisi" },
				{ LanguageId.mg, "Rosia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Rūhia" },
				{ LanguageId.mk, "Русија" },
				{ LanguageId.ml, "റഷ്യ" },
				{ LanguageId.mn, "Орос" },
				{ LanguageId.mni, "রুসিয়া" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "रशिया" },
				{ LanguageId.ms, "Rusia" },
				{ LanguageId.mt, "ir-Russja" },
				{ LanguageId.mua, "Russiya" },
				{ LanguageId.my, "ရုရှား" },
				{ LanguageId.mzn, "روسیه" },
				{ LanguageId.naq, "Rasiab" },
				{ LanguageId.nb, "Russland" },
				{ LanguageId.nd, "Rashiya" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "रूस" },
				{ LanguageId.nl, "Rusland" },
				{ LanguageId.nmg, "Russi" },
				{ LanguageId.nn, "Russland" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߌߙߌ߬ߛߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Rrasha" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Raashiyaa" },
				{ LanguageId.or, "ରୁଷିଆ" },
				{ LanguageId.os, "Уӕрӕсе" },
				{ LanguageId.pa, "ਰੂਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Rọ́shia" },
				{ LanguageId.pl, "Rosja" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "روسیه" },
				{ LanguageId.pt, "Rússia" },
				{ LanguageId.qu, "Rusia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Russia" },
				{ LanguageId.rn, "Uburusiya" },
				{ LanguageId.ro, "Rusia" },
				{ LanguageId.rof, "Urusi" },
				{ LanguageId.ru, "Россия" },
				{ LanguageId.rw, "Uburusiya" },
				{ LanguageId.rwk, "Urusi" },
				{ LanguageId.sa, "रष्यदेश:" },
				{ LanguageId.sah, "Арассыыйа" },
				{ LanguageId.saq, "Urusi" },
				{ LanguageId.sat, "ᱨᱩᱥ" },
				{ LanguageId.sbp, "Wulusi" },
				{ LanguageId.sd, "روس" },
				{ LanguageId.se, "Ruošša" },
				{ LanguageId.seh, "Rússia" },
				{ LanguageId.ses, "Iriši laboo" },
				{ LanguageId.sg, "Rusïi" },
				{ LanguageId.shi, "ⵔⵓⵙⵢⴰ" },
				{ LanguageId.si, "රුසියාව" },
				{ LanguageId.sk, "Rusko" },
				{ LanguageId.sl, "Rusija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Ruoššâ" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Russia" },
				{ LanguageId.so, "Ruush" },
				{ LanguageId.sq, "Rusi" },
				{ LanguageId.sr, "Русија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Russia Federation" },
				{ LanguageId.su, "Rusia" },
				{ LanguageId.sv, "Ryssland" },
				{ LanguageId.sw, "Urusi" },
				{ LanguageId.syr, "ܪܘܣܝܐ" },
				{ LanguageId.ta, "ரஷ்யா" },
				{ LanguageId.te, "రష్యా" },
				{ LanguageId.teo, "Urusi" },
				{ LanguageId.tg, "Русия" },
				{ LanguageId.th, "รัสเซีย" },
				{ LanguageId.ti, "ሩስያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Russiýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Lūsia" },
				{ LanguageId.tr, "Rusya" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Россия" },
				{ LanguageId.twq, "Iriši laboo" },
				{ LanguageId.tzm, "Rusya" },
				{ LanguageId.ug, "رۇسىيە" },
				{ LanguageId.uk, "Росія" },
				{ LanguageId.ur, "روس" },
				{ LanguageId.uz, "Rossiya" },
				{ LanguageId.vai, "ꗐꖺꔻꕩ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Nga" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Urusi" },
				{ LanguageId.wae, "Russland" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Risi" },
				{ LanguageId.xh, "ERashiya" },
				{ LanguageId.xog, "Lasa" },
				{ LanguageId.yav, "ulusí" },
				{ LanguageId.yi, "רוסלאַנד" },
				{ LanguageId.yo, "Rọṣia" },
				{ LanguageId.zgh, "ⵔⵓⵙⵢⴰ" },
				{ LanguageId.zh, "俄罗斯" },
				{ LanguageId.zu, "i-Russia" },
			}
		);
	}
}
