using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class RU
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "7",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Den Russiske Føderation" },
				{ LanguageId.af, "Russiese Federasie" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የራሺያ ፌዴሬሽን" },
				{ LanguageId.ar, "الاتحاد الروسي" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Rusiya Federasiyası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Расійская Федэрацыя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Руска федерация" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "রাশিয়ান ফেডারেশন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ruska Federacija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Federació Russa" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Russian Federation" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Federazione Russa" },
				{ LanguageId.cs, "Ruská Federace" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ffederasiwn Rwseg" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Russische Föderation" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ρωσική Ομοσπονδία" },
				{ LanguageId.en, "Russian Federation" },
				{ LanguageId.eo, "Rusa Federacio" },
				{ LanguageId.es, "Federación Rusa" },
				{ LanguageId.et, "Venemaa Föderatsioon" },
				{ LanguageId.eu, "Errusiako Federazioa" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "فدراسیون روسیه" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Venäjän federaatio" },
				{ LanguageId.fil, "Pederasyon ng Russia" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Fédération Russe" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Russyske Federaasje" },
				{ LanguageId.ga, "Cónaidhm na Rúise" },
				{ LanguageId.gd, "Russian Federation" },
				{ LanguageId.gl, "Federación Rusa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "રશિયન ફેડરેશન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tarayyar Rasha" },
				{ LanguageId.haw, "Hui Lūkini" },
				{ LanguageId.he, "הפדרציה הרוסית" },
				{ LanguageId.hi, "रूसी संघ" },
				{ LanguageId.hr, "Ruska Federacija" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Orosz Föderáció" },
				{ LanguageId.hy, "Ռուսաստանի Դաշնություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Federasi Rusia" },
				{ LanguageId.ig, "Russian Federation" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Rússland" },
				{ LanguageId.it, "Federazione Russa" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ロシア連邦" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Russian Federation" },
				{ LanguageId.ka, "რუსეთის ფედერაცია" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Ресей Федерациясы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សហព័ន្ធរុស្ស៊ី" },
				{ LanguageId.kn, "ರಷ್ಯ ಒಕ್ಕೂಟ" },
				{ LanguageId.ko, "러시아 연방" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Орус Федерациясы" },
				{ LanguageId.la, "Foedus Russicum" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Russesch Federatioun" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສະຫະພັນລັດເຊຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Rusijos Federacija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Krievijas Federācija" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Federasiona Rosiana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Russian Federation" },
				{ LanguageId.mk, "Руска Федерација" },
				{ LanguageId.ml, "റഷ്യൻ ഫെഡറേഷൻ" },
				{ LanguageId.mn, "Оросын Холбооны Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "रशियाचे संघराज्य" },
				{ LanguageId.ms, "Persekutuan Russia" },
				{ LanguageId.mt, "Federazzjoni Russa" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ရုရှားပြည်ထောင်စု" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Den russiske føderasjonen" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "रूसी संघ" },
				{ LanguageId.nl, "Russische Federatie" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ରୁଷିଆ ମହାସଙ୍ଘ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਰਸ਼ੀਅਨ ਫੈਡਰੇਸ਼ਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Federacja Rosyjska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د روسیې فدراسیون" },
				{ LanguageId.pt, "Federação Russa" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Federația Rusă" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Российская Федерация" },
				{ LanguageId.rw, "Uburusiya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "روسي وفاق" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "රුසියානු සමූහාණ්ඩුව" },
				{ LanguageId.sk, "Ruská federácia" },
				{ LanguageId.sl, "Ruska federacija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Russian Federation" },
				{ LanguageId.so, "Xiriirka Ruushka" },
				{ LanguageId.sq, "Federata Ruse" },
				{ LanguageId.sr, "Руска Федерација" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Russia Federation" },
				{ LanguageId.su, "Féderasi Rusia" },
				{ LanguageId.sv, "Ryska Federationen" },
				{ LanguageId.sw, "Shirikisho la Urusi" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "இரஷ்ய கூட்டமைப்பு" },
				{ LanguageId.te, "రష్యన్ ఫెడరేషన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Федератсияи Россия" },
				{ LanguageId.th, "สหพันธรัฐรัสเซีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Russiýa Federasiýasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Rusya Federasyonu" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Россия Федерациясе" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "رۇسىيە فېدېراتسىيەسى" },
				{ LanguageId.uk, "Російська Федерація" },
				{ LanguageId.ur, "روسی فیڈریشن" },
				{ LanguageId.uz, "Rossiya Federatsiyasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Liên Bang Nga" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IRussian Federation" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "רוסיש פעדעריישאַן" },
				{ LanguageId.yo, "Gbogboogbo ilu Russia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "俄罗斯联邦" },
				{ LanguageId.zu, "Inhlangano yase Russia" },
			}
		);
	}
}
