// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SA
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "966",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saudi-Arabien" },
				{ LanguageId.af, "Saoedi-Arabië" },
				{ LanguageId.agq, "Sawudi Alabi" },
				{ LanguageId.ak, "Saudi Arabia" },
				{ LanguageId.am, "ሳውድአረቢያ" },
				{ LanguageId.ar, "المملكة العربية السعودية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চৌডি আৰবিয়া" },
				{ LanguageId.asa, "Thaudi" },
				{ LanguageId.ast, "Arabia Saudita" },
				{ LanguageId.az, "Səudiyyə Ərəbistanı" },
				{ LanguageId.ba, "Сәғүд Ғәрәбстаны" },
				{ LanguageId.bas, "Sàudi Àrabìà" },
				{ LanguageId.be, "Саудаўская Аравія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husaudi" },
				{ LanguageId.bg, "Саудитска Арабия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Arabiya Sawudiya" },
				{ LanguageId.bn, "সৌদি আরব" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Arabia Saoudat" },
				{ LanguageId.brx, "साउदि आराबिया" },
				{ LanguageId.bs, "Saudijska Arabija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Aràbia Saudí" },
				{ LanguageId.ccp, "𑄥𑄯𑄘𑄨 𑄃𑄢𑄧𑄝𑄴" },
				{ LanguageId.ce, "СаӀудийн Ӏаьрбийчоь" },
				{ LanguageId.ceb, "Saudi Arabia" },
				{ LanguageId.cgg, "Saudi Areebiya" },
				{ LanguageId.chr, "ᏌᎤᏗ ᎡᎴᏈᎠ" },
				{ LanguageId.ckb, "عەرەبستانی سەعوودی" },
				{ LanguageId.co, "Arabia Saudita" },
				{ LanguageId.cs, "Saúdská Arábie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saudi Arabia" },
				{ LanguageId.dav, "Saudi" },
				{ LanguageId.de, "Saudi-Arabien" },
				{ LanguageId.dje, "Saudiya" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Saudi-Arabiska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སཱཝ་དི་ ཨ་རེ་བྷི་ཡ" },
				{ LanguageId.ebu, "Saudi" },
				{ LanguageId.ee, "Saudi Arabia nutome" },
				{ LanguageId.el, "Σαουδική Αραβία" },
				{ LanguageId.en, "Saudi Arabia" },
				{ LanguageId.eo, "Sauda Arabujo" },
				{ LanguageId.es, "Arabia Saudí" },
				{ LanguageId.et, "Saudi Araabia" },
				{ LanguageId.eu, "Saudi Arabia" },
				{ LanguageId.ewo, "Arabí Saudí" },
				{ LanguageId.fa, "عربستان سعودی" },
				{ LanguageId.ff, "Arabii Sawdit" },
				{ LanguageId.fi, "Saudi-Arabia" },
				{ LanguageId.fil, "Saudi Arabia" },
				{ LanguageId.fo, "Saudiarabia" },
				{ LanguageId.fr, "Arabie saoudite" },
				{ LanguageId.fur, "Arabie Saudide" },
				{ LanguageId.fy, "Saoedi-Arabië" },
				{ LanguageId.ga, "an Araib Shádach" },
				{ LanguageId.gd, "Aràibia nan Sabhd" },
				{ LanguageId.gl, "Arabia Saudita" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Saudi-Araabie" },
				{ LanguageId.gu, "સાઉદી અરેબિયા" },
				{ LanguageId.guz, "Saudi" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saudiyya" },
				{ LanguageId.haw, "Saudi ʻAlapia" },
				{ LanguageId.he, "ערב הסעודית" },
				{ LanguageId.hi, "सऊदी अरब" },
				{ LanguageId.hr, "Saudijska Arabija" },
				{ LanguageId.hsb, "Sawdi-Arabska" },
				{ LanguageId.hu, "Szaúd-Arábia" },
				{ LanguageId.hy, "Սաուդյան Արաբիա" },
				{ LanguageId.ia, "Arabia Saudita" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Arab Saudi" },
				{ LanguageId.ig, "Saudi Arabia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sádi-Arabía" },
				{ LanguageId.it, "Arabia Saudita" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サウジアラビア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Saudi" },
				{ LanguageId.jv, "Arab Saudi" },
				{ LanguageId.ka, "საუდის არაბეთი" },
				{ LanguageId.kab, "Suɛudiya Taɛrabt" },
				{ LanguageId.kam, "Saudi" },
				{ LanguageId.kde, "Saudia" },
				{ LanguageId.kea, "Arábia Saudita" },
				{ LanguageId.khq, "Saudiya" },
				{ LanguageId.ki, "Saudi" },
				{ LanguageId.kk, "Сауд Арабиясы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Saudi Arabia" },
				{ LanguageId.km, "អារ៉ាប៊ីសាអូឌីត" },
				{ LanguageId.kn, "ಸೌದಿ ಅರೇಬಿಯಾ" },
				{ LanguageId.ko, "사우디아라비아" },
				{ LanguageId.kok, "साउदी अरब" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سعودی عرب" },
				{ LanguageId.ksb, "Saudi" },
				{ LanguageId.ksf, "arabí saodí" },
				{ LanguageId.ksh, "Saudi Arraabije" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сауд Арабиясы" },
				{ LanguageId.la, "Saudi Arabia" },
				{ LanguageId.lag, "Saudíia Arabíia" },
				{ LanguageId.lb, "Saudi-Arabien" },
				{ LanguageId.lg, "Sawudarebya - Buwarabu" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Alabi Sawuditɛ" },
				{ LanguageId.lo, "ຊາອຸດິ ອາຣາເບຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Saudo Arabija" },
				{ LanguageId.luo, "Saudi Arabia" },
				{ LanguageId.luy, "Saudi" },
				{ LanguageId.lv, "Saūda Arābija" },
				{ LanguageId.mai, "सऊदी अरब" },
				{ LanguageId.mas, "Saudi" },
				{ LanguageId.mer, "Saudi" },
				{ LanguageId.mfe, "Larabi Saoudit" },
				{ LanguageId.mg, "Arabia saodita" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hauri Arāpia" },
				{ LanguageId.mk, "Саудиска Арабија" },
				{ LanguageId.ml, "സൗദി അറേബ്യ" },
				{ LanguageId.mn, "Саудын Араб" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सौदी अरब" },
				{ LanguageId.ms, "Arab Saudi" },
				{ LanguageId.mt, "l-Arabja Sawdija" },
				{ LanguageId.mua, "Sǝr Arabiya" },
				{ LanguageId.my, "ဆော်ဒီအာရေးဘီးယား" },
				{ LanguageId.mzn, "عربستون" },
				{ LanguageId.naq, "Saudi Arabiab" },
				{ LanguageId.nb, "Saudi-Arabia" },
				{ LanguageId.nd, "Saudi Arabia" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "साउदी अरब" },
				{ LanguageId.nl, "Saoedi-Arabië" },
				{ LanguageId.nmg, "Saudi Arabia" },
				{ LanguageId.nn, "Saudi-Arabia" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߎ߰ߘߎ߬ߟߊ߫-ߡߊ߲߬ߛߊ߬ߟߊ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Saudi Areebiya" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Saawud Arabiyaa" },
				{ LanguageId.or, "ସାଉଦି ଆରବିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਾਊਦੀ ਅਰਬ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Saúdí Arébia" },
				{ LanguageId.pl, "Arabia Saudyjska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سعودي عربستان" },
				{ LanguageId.pt, "Arábia Saudita" },
				{ LanguageId.qu, "Arabia Saudí" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Arabia Saudita" },
				{ LanguageId.rn, "Arabiya Sawudite" },
				{ LanguageId.ro, "Arabia Saudită" },
				{ LanguageId.rof, "Saudi" },
				{ LanguageId.ru, "Саудовская Аравия" },
				{ LanguageId.rw, "Arabiya Sawudite" },
				{ LanguageId.rwk, "Saudi" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Saudi" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Sawudi" },
				{ LanguageId.sd, "سعودي عرب" },
				{ LanguageId.se, "Saudi-Arábia" },
				{ LanguageId.seh, "Arábia Saudita" },
				{ LanguageId.ses, "Saudiya" },
				{ LanguageId.sg, "Saûdi Arabïi" },
				{ LanguageId.shi, "ⵙⵙⴰⵄⵓⴷⵉⵢⴰ" },
				{ LanguageId.si, "සෞදි අරාබිය" },
				{ LanguageId.sk, "Saudská Arábia" },
				{ LanguageId.sl, "Saudova Arabija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Saudi Arabia" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saudi Arabia" },
				{ LanguageId.so, "Sacuudi Carabiya" },
				{ LanguageId.sq, "Arabi Saudite" },
				{ LanguageId.sr, "Саудијска Арабија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saudi Arabia" },
				{ LanguageId.su, "Arab Saudi" },
				{ LanguageId.sv, "Saudiarabien" },
				{ LanguageId.sw, "Saudia" },
				{ LanguageId.syr, "ܣܥܘܕܝܐ" },
				{ LanguageId.ta, "சவுதி அரேபியா" },
				{ LanguageId.te, "సౌదీ అరేబియా" },
				{ LanguageId.teo, "Saudi" },
				{ LanguageId.tg, "Арабистони Саудӣ" },
				{ LanguageId.th, "ซาอุดีอาระเบีย" },
				{ LanguageId.ti, "ስዑዲ ዓረብ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Saud Arabystany" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Saute ʻAlepea" },
				{ LanguageId.tr, "Suudi Arabistan" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Согуд Гарәбстаны" },
				{ LanguageId.twq, "Saudiya" },
				{ LanguageId.tzm, "Ssaεudiyya Taεrabt" },
				{ LanguageId.ug, "سەئۇدىي ئەرەبىستان" },
				{ LanguageId.uk, "Саудівська Аравія" },
				{ LanguageId.ur, "سعودی عرب" },
				{ LanguageId.uz, "Saudiya Arabistoni" },
				{ LanguageId.vai, "ꕞꕌꖝ ꕸꖃꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Ả Rập Xê-út" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Saudi" },
				{ LanguageId.wae, "Saudi Arabie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Arabi Sawudi" },
				{ LanguageId.xh, "ESaudi Arabia" },
				{ LanguageId.xog, "Sawudarebya" },
				{ LanguageId.yav, "alapísawutíit" },
				{ LanguageId.yi, "סאודיע אראביע" },
				{ LanguageId.yo, "Saudi Arabia" },
				{ LanguageId.zgh, "ⵙⵙⴰⵄⵓⴷⵉⵢⴰ" },
				{ LanguageId.zh, "沙特阿拉伯" },
				{ LanguageId.zu, "i-Saudi Arabia" },
			}
		);
	}
}
