using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "966",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saudi Arabien" },
				{ LanguageId.af, "Saoedi-Arabië" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሳውዲ ዓረቢያ" },
				{ LanguageId.ar, "المملكة العربية السعودية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Səudiyyə Ərəbistanı" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Саўдаўская Аравія" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Саудитска Арабия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সৌদি আরব" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Arabia Saoudat" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Saudijska Arabija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Aràbia Saudita" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Saudi Arabia" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Arabia Saudita" },
				{ LanguageId.cs, "Saudská arábie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sawdi Arabia" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Saudi-Arabien" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σαουδική Αραβία" },
				{ LanguageId.en, "Saudi Arabia" },
				{ LanguageId.eo, "Saŭdiarabio" },
				{ LanguageId.es, "Arabia Saudita" },
				{ LanguageId.et, "Saudi Araabia" },
				{ LanguageId.eu, "Saudi Arabia" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "عربستان سعودی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saudi-Arabia" },
				{ LanguageId.fil, "Saudi Arabia" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Arabie Saoudite" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Saûdi-Araabje" },
				{ LanguageId.ga, "An Araib Shádach" },
				{ LanguageId.gd, "Saudi Arabia" },
				{ LanguageId.gl, "Arabia Saudita" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સાઉદી અરેબિયા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saudi Arabia" },
				{ LanguageId.haw, "Saudi ʻAlapia" },
				{ LanguageId.he, "ערב הסעודית" },
				{ LanguageId.hi, "सऊदी अरब" },
				{ LanguageId.hr, "Saudijska Arabija" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Szaud-Arábia" },
				{ LanguageId.hy, "Սաուդյան Արաբիա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Arab Saudi" },
				{ LanguageId.ig, "Saudi Arabia" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sádí-Arabía" },
				{ LanguageId.it, "Arabia Saudita" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サウジアラビア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Arab Saudi" },
				{ LanguageId.ka, "საუდის არაბეთი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сауд Арабиясы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "អារ៉ាប៊ីសាអូឌីត" },
				{ LanguageId.kn, "ಸೌದಿ ಅರೇಬಿಯಾ" },
				{ LanguageId.ko, "사우디 아라비아" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сауд Арабиясы" },
				{ LanguageId.la, "Saudi Arabia" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saudi Arabien" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊາ​ອຸ​ດິ​ອາ​ຣາ​ເບຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Saudo Arabija" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Saūda Arābija" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Arabia Saodita" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hauti Arapia" },
				{ LanguageId.mk, "Саудиска Арабија" },
				{ LanguageId.ml, "സൗദി അറേബ്യ" },
				{ LanguageId.mn, "Саудын Араб" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सौदी अरेबिया" },
				{ LanguageId.ms, "Arab Saudi" },
				{ LanguageId.mt, "Għarabja Sawdija" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆော်ဒီအာရေဗျ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saudi-Arabia" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "साउदी अरेबिया" },
				{ LanguageId.nl, "Saoedi-Arabië" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସାଉଦି ଆରବ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਊਦੀ ਅਰਬ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Arabia Saudyjska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سعودي عربستان" },
				{ LanguageId.pt, "Arábia Saudita" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Arabia Saudită" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Саудовская Аравия" },
				{ LanguageId.rw, "Arabiya Sawudite" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سعودي عرب" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සවුදි අරාබිය" },
				{ LanguageId.sk, "Saudská Arábia" },
				{ LanguageId.sl, "Savdska Arabija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saudhi Arabhiya" },
				{ LanguageId.so, "Sacuudi Carabiya" },
				{ LanguageId.sq, "Arabia Saudite" },
				{ LanguageId.sr, "Саудијска Арабија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saudi Arabia" },
				{ LanguageId.su, "Arab Saudi" },
				{ LanguageId.sv, "Saudiarabien" },
				{ LanguageId.sw, "Saudi Arabia" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சவூதி அரேபியா" },
				{ LanguageId.te, "సౌదీ అరేబియా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Арабистони Саудӣ" },
				{ LanguageId.th, "ซาอุดิอาราเบีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Saud Arabystany" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Suudi Arabistan" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Согуд Гарәбстаны" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سەئۇدى ئەرەبىستان" },
				{ LanguageId.uk, "Саудівська Аравія" },
				{ LanguageId.ur, "سعودی عرب" },
				{ LanguageId.uz, "Saudiya Arabistoni" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Ả Rập Saudi" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "ISaudi Arabia" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סאודיע אראביע" },
				{ LanguageId.yo, "Saudi Arebia" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "沙特阿拉伯" },
				{ LanguageId.zu, "I-Saudi Arabia" },
			}
		);
	}
}
