using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SB
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "677",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Salomonøerne" },
				{ LanguageId.af, "Salomonseilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የሰሎሞን አይስላንድስ" },
				{ LanguageId.ar, "جزر سليمان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Solomon adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Саламонавы астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Соломоновите острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সলোমান দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Solomonova ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Salomó" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga Isla sa Solomon" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Salomone" },
				{ LanguageId.cs, "Solomonovy ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Solomon" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Salomon-Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησιά του Σολομώντα" },
				{ LanguageId.en, "Solomon Islands" },
				{ LanguageId.eo, "Salomonoj" },
				{ LanguageId.es, "Islas Salomón" },
				{ LanguageId.et, "Saalomoni Saared" },
				{ LanguageId.eu, "Salomon Uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر سلیمان" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Solomonsaaret" },
				{ LanguageId.fil, "Solomon Islands" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Les îles Salomon" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Salomonseilannen" },
				{ LanguageId.ga, "Oileáin Sholamón" },
				{ LanguageId.gd, "Na h-Eileanan Solomon" },
				{ LanguageId.gl, "Illas Salomón" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સોલોમન ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Solomon" },
				{ LanguageId.haw, "Solomona ʻAilana" },
				{ LanguageId.he, "איי שלמה" },
				{ LanguageId.hi, "सोलोमन इस्लैंडस" },
				{ LanguageId.hr, "Solomonski otoci" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Salamon-szigetek" },
				{ LanguageId.hy, "Սողոմոնի կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Pulau Solomon" },
				{ LanguageId.ig, "Solomon Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Salómonseyjar" },
				{ LanguageId.it, "Isole Salomone" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ソロモン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Solomon" },
				{ LanguageId.ka, "სოლომონის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Соломон аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះសាឡូម៉ូន" },
				{ LanguageId.kn, "ಸೊಲೊಮನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "솔로몬 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Соломон Аралдары" },
				{ LanguageId.la, "Insulae Salomonis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Solomon Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະໂຊໂລມອນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Saliamono salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Zālamana salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Salomon" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Moutere Horomona" },
				{ LanguageId.mk, "Соломонови Острови" },
				{ LanguageId.ml, "സോളമൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Соломоны арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सॉलोमन बेटे" },
				{ LanguageId.ms, "Kepulauan Solomon" },
				{ LanguageId.mt, "Gżejjer Solomon" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆော်လမွန်ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Solomon øyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सोलोमन टापुहरू" },
				{ LanguageId.nl, "Solomon eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଶଲୋମନ ଦ୍ୱୀପପୁ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੋਲੋਮਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Salomona" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سلیمان ټاپو" },
				{ LanguageId.pt, "Ilhas Salomão" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Solomon" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Соломоновы острова" },
				{ LanguageId.rw, "Ibirwa bya Salomo" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سولومون ٻيٽَ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සොලමන් දූපත්" },
				{ LanguageId.sk, "Šalamúnove ostrovy" },
				{ LanguageId.sl, "Salomonovi otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa Soromoni" },
				{ LanguageId.so, "Solomon Islands" },
				{ LanguageId.sq, "Ishujt Solomon" },
				{ LanguageId.sr, "Соломонска острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke Tsa Solomon" },
				{ LanguageId.su, "Kapuloan Solomon" },
				{ LanguageId.sv, "Salomonöarna" },
				{ LanguageId.sw, "Visiwa vya Solomon" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சாலமன் தீவுகள்" },
				{ LanguageId.te, "సోలమన్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Соломон" },
				{ LanguageId.th, "หมู่เกาะโซโลมอน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Süleýman adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Solomon Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сөләйман утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سۇلايمان تاقىم ئاراللىرى" },
				{ LanguageId.uk, "Соломонові острови" },
				{ LanguageId.ur, "جزائر سلیمان" },
				{ LanguageId.uz, "Solomon orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Solomon" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Isiqithi saseSolomon" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "שלמה אינזלען" },
				{ LanguageId.yo, "Solomon Islands" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "所罗门群岛" },
				{ LanguageId.zu, "Iziqhingi zaseSolomon" },
			}
		);
	}
}
