// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SB
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "677",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Salomonøerne" },
				{ LanguageId.af, "Salomonseilande" },
				{ LanguageId.agq, "Chwɨlà fɨ Solomwɨ̀n" },
				{ LanguageId.ak, "Solomɔn Aeland" },
				{ LanguageId.am, "ሰለሞን ደሴቶች" },
				{ LanguageId.ar, "جزر سليمان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চোলোমোন দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Tholomon" },
				{ LanguageId.ast, "Islles Salomón" },
				{ LanguageId.az, "Solomon adaları" },
				{ LanguageId.ba, "Соломон утрауҙары" },
				{ LanguageId.bas, "Bìòn bi Salōmò" },
				{ LanguageId.be, "Саламонавы астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Solomon" },
				{ LanguageId.bg, "Соломонови острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Salomo Gun" },
				{ LanguageId.bn, "সলোমন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Salomon" },
				{ LanguageId.brx, "सल’मन द्वीप" },
				{ LanguageId.bs, "Solomonska Ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Salomó" },
				{ LanguageId.ccp, "𑄥𑄧𑄣𑄮𑄟𑄚𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Соломонан гӀайренаш" },
				{ LanguageId.ceb, "Solomon Islands" },
				{ LanguageId.cgg, "Ebizinga bya Surimaani" },
				{ LanguageId.chr, "ᏐᎶᎹᏂ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی سلێمان" },
				{ LanguageId.co, "Isule Salomone" },
				{ LanguageId.cs, "Šalamounovy ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Solomon" },
				{ LanguageId.dav, "Visiwa vya Solomon" },
				{ LanguageId.de, "Salomonen" },
				{ LanguageId.dje, "Solomon Gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Salomony" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སོ་ལོ་མོན་ གླིང་ཚོམ" },
				{ LanguageId.ebu, "Visiwa vya Solomon" },
				{ LanguageId.ee, "Solomon ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Σολομώντος" },
				{ LanguageId.en, "Solomon Islands" },
				{ LanguageId.eo, "Salomonoj" },
				{ LanguageId.es, "Islas Salomón" },
				{ LanguageId.et, "Saalomoni Saared" },
				{ LanguageId.eu, "Salomon Uharteak" },
				{ LanguageId.ewo, "Minlán Mí Solomɔ́n" },
				{ LanguageId.fa, "جزایر سلیمان" },
				{ LanguageId.ff, "Duuɗe Solomon" },
				{ LanguageId.fi, "Salomonsaaret" },
				{ LanguageId.fil, "Solomon Islands" },
				{ LanguageId.fo, "Salomonoyggjar" },
				{ LanguageId.fr, "Îles Salomon" },
				{ LanguageId.fur, "Isulis Salomon" },
				{ LanguageId.fy, "Salomonseilannen" },
				{ LanguageId.ga, "Oileáin Sholaimh" },
				{ LanguageId.gd, "Eileanan Sholaimh" },
				{ LanguageId.gl, "Illas Salomón" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Salomoone" },
				{ LanguageId.gu, "સોલોમન આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Solomon" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Salaman" },
				{ LanguageId.haw, "Solomona ʻAilana" },
				{ LanguageId.he, "איי שלמה" },
				{ LanguageId.hi, "सोलोमन द्वीपसमूह" },
				{ LanguageId.hr, "Salomonovi Otoci" },
				{ LanguageId.hsb, "Salomony" },
				{ LanguageId.hu, "Salamon-szigetek" },
				{ LanguageId.hy, "Սողոմոնյան կղզիներ" },
				{ LanguageId.ia, "Insulas Solomon" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Solomon" },
				{ LanguageId.ig, "Agwaetiti Solomon" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Salómonseyjar" },
				{ LanguageId.it, "Isole Salomone" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ソロモン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Solomon" },
				{ LanguageId.jv, "Kapuloan Suleman" },
				{ LanguageId.ka, "სოლომონის კუნძულები" },
				{ LanguageId.kab, "Tigzirin n Sulumun" },
				{ LanguageId.kam, "Isiwa sya Solomon" },
				{ LanguageId.kde, "Chisiwa cha Solomon" },
				{ LanguageId.kea, "Ilhas Salumãu" },
				{ LanguageId.khq, "Solomon Gungey" },
				{ LanguageId.ki, "Visiwa vya Solomon" },
				{ LanguageId.kk, "Соломон аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeiyotab Solomon" },
				{ LanguageId.km, "កោះ​សូឡូម៉ុង" },
				{ LanguageId.kn, "ಸಾಲೊಮನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "솔로몬 제도" },
				{ LanguageId.kok, "सोलोमन जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سولامان جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Solomon" },
				{ LanguageId.ksf, "zǝ salomɔ́n" },
				{ LanguageId.ksh, "de Solomone-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Соломон аралдары" },
				{ LanguageId.la, "Insulae Salomonis" },
				{ LanguageId.lag, "Visíiwa vya Solomóoni" },
				{ LanguageId.lb, "Salomonen" },
				{ LanguageId.lg, "Bizanga by’eSolomooni" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga Solomɔ" },
				{ LanguageId.lo, "ຫມູ່ເກາະໂຊໂລມອນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Saliamono Salos" },
				{ LanguageId.luo, "Solomon Islands" },
				{ LanguageId.luy, "Visiwa vya Solomon" },
				{ LanguageId.lv, "Zālamana salas" },
				{ LanguageId.mai, "सोलोमन द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Solomon" },
				{ LanguageId.mer, "Airandi Cia Solomon" },
				{ LanguageId.mfe, "Zil Salomon" },
				{ LanguageId.mg, "Nosy Salomona" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Motu Horomona" },
				{ LanguageId.mk, "Соломонски Острови" },
				{ LanguageId.ml, "സോളമൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Соломоны арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सोलोमन बेटे" },
				{ LanguageId.ms, "Kepulauan Solomon" },
				{ LanguageId.mt, "il-Gżejjer Solomon" },
				{ LanguageId.mua, "Sǝr Salomon ma laŋne" },
				{ LanguageId.my, "ဆော်လမွန်ကျွန်းစု" },
				{ LanguageId.mzn, "سلیمون جزیره" },
				{ LanguageId.naq, "Solomon Islands" },
				{ LanguageId.nb, "Salomonøyene" },
				{ LanguageId.nd, "Solomon Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सोलोमन टापुहरू" },
				{ LanguageId.nl, "Salomonseilanden" },
				{ LanguageId.nmg, "Maŋ́ má Salomɔn" },
				{ LanguageId.nn, "Salomonøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߊߟߏߡߐ߲߫ ߕߌ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ebizinga bya Surimaani" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Solomoon" },
				{ LanguageId.or, "ସୋଲୋମନ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੋਲੋਮਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sólómọ́n Aílands" },
				{ LanguageId.pl, "Wyspy Salomona" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سليمان ټاپوګان" },
				{ LanguageId.pt, "Ilhas Salomão" },
				{ LanguageId.qu, "Islas Salomón" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas da Salomon" },
				{ LanguageId.rn, "Amazinga ya Salumoni" },
				{ LanguageId.ro, "Insulele Solomon" },
				{ LanguageId.rof, "Visiwa vya Solomon" },
				{ LanguageId.ru, "Соломоновы о-ва" },
				{ LanguageId.rw, "Ibirwa bya Salomo" },
				{ LanguageId.rwk, "Visiwa vya Solomon" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Solomon" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli fya Solomoni" },
				{ LanguageId.sd, "سولومون ٻيٽَ" },
				{ LanguageId.se, "Salomon-sullot" },
				{ LanguageId.seh, "Ilhas Salomão" },
				{ LanguageId.ses, "Solomon Gungey" },
				{ LanguageId.sg, "Zûâ Salomöon" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵙⴰⵍⵓⵎⴰⵏ" },
				{ LanguageId.si, "සොලමන් දූපත්" },
				{ LanguageId.sk, "Šalamúnove ostrovy" },
				{ LanguageId.sl, "Salomonovi otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Salomosuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zvaSolomon" },
				{ LanguageId.so, "Jasiiradda Solomon" },
				{ LanguageId.sq, "Ishujt Solomon" },
				{ LanguageId.sr, "Соломонска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke Tsa Solomon" },
				{ LanguageId.su, "Kapuloan Solomon" },
				{ LanguageId.sv, "Salomonöarna" },
				{ LanguageId.sw, "Visiwa vya Solomon" },
				{ LanguageId.syr, "ܓܙܪܬܐ ܕܫܠܝܡܘܢ" },
				{ LanguageId.ta, "சாலமன் தீவுகள்" },
				{ LanguageId.te, "సోలమన్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Solomon" },
				{ LanguageId.tg, "Ҷазираҳои Соломон" },
				{ LanguageId.th, "หมู่เกาะโซโลมอน" },
				{ LanguageId.ti, "ደሴታት ሰሎሞን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Solomon adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Solomone" },
				{ LanguageId.tr, "Solomon Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сөләйман утраулары" },
				{ LanguageId.twq, "Solomon Gungey" },
				{ LanguageId.tzm, "Tigzirin n Salumun" },
				{ LanguageId.ug, "سولومون ئاراللىرى" },
				{ LanguageId.uk, "Соломонові Острови" },
				{ LanguageId.ur, "سولومن آئلینڈز" },
				{ LanguageId.uz, "Solomon orollari" },
				{ LanguageId.vai, "ꖬꕞꔤꕮꕊꕯ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Solomon" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Solomon" },
				{ LanguageId.wae, "Salomone" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Salmoon" },
				{ LanguageId.xh, "ESolomon Islands" },
				{ LanguageId.xog, "Ebizanga bya Solomooni" },
				{ LanguageId.yav, "il salomɔ́ŋ" },
				{ LanguageId.yi, "סאלאמאן אינזלען" },
				{ LanguageId.yo, "Etikun Solomoni" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵙⴰⵍⵓⵎⴰⵏ" },
				{ LanguageId.zh, "所罗门群岛" },
				{ LanguageId.zu, "i-Solomon Islands" },
			}
		);
	}
}
