using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SC
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "248",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Seychellerne" },
				{ LanguageId.af, "Seychelle" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሲሼልስ" },
				{ LanguageId.ar, "سيشيل" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Seyşel adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сейшэльскія выспы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сейшели" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেশেলস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sechelez" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sejšeli" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Seychelles" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Seychelles" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Seychelles" },
				{ LanguageId.cs, "Seychely" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Seychelles" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Seychellen" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σεϋχέλλες" },
				{ LanguageId.en, "Seychelles" },
				{ LanguageId.eo, "Sejŝeloj" },
				{ LanguageId.es, "Seychelles" },
				{ LanguageId.et, "Seišellid" },
				{ LanguageId.eu, "Seychelles" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سیشل" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Seychellit" },
				{ LanguageId.fil, "Seychelles" },
				{ LanguageId.fo, "Seychelloyggjar" },
				{ LanguageId.fr, "les Seychelles" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "de Seysjellen" },
				{ LanguageId.ga, "Na Séiséil" },
				{ LanguageId.gd, "Seychelles" },
				{ LanguageId.gl, "Seychelles" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેશેલ્સ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Seychelles" },
				{ LanguageId.haw, "Ka Pae Moku ʻo Sekele" },
				{ LanguageId.he, "איי סיישל" },
				{ LanguageId.hi, "सेशल्स" },
				{ LanguageId.hr, "Sejšeli" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Seychelle-szigetek" },
				{ LanguageId.hy, "Սեյշելներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Seychelles" },
				{ LanguageId.ig, "Seychelles" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Seychelles" },
				{ LanguageId.it, "Seychelles" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セーシェル" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Seychelles" },
				{ LanguageId.ka, "სეიშელის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сейшель аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សីស្ហែល" },
				{ LanguageId.kn, "ಸೀಶೆಲ್ಸ್" },
				{ LanguageId.ko, "세이셸" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сейшел аралдары" },
				{ LanguageId.la, "Seisellenses" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Seychellen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Seychelles" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Seišeliai" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Seišelu salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Seychelles" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Heychelles" },
				{ LanguageId.mk, "Сејшели" },
				{ LanguageId.ml, "സീഷെൽസ്" },
				{ LanguageId.mn, "Сейшелийн арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेशेल्स" },
				{ LanguageId.ms, "Seychelles" },
				{ LanguageId.mt, "Seychelles" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆေးရှဲလ်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Seychellene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेशेल्स" },
				{ LanguageId.nl, "Seychellen" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Seychellane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଚେଲସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਸ਼ੇਲਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Seszele" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سیچیلیس" },
				{ LanguageId.pt, "Seicheles" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Seychelles" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сейшельские острова" },
				{ LanguageId.rw, "Seychelles" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سيليڪاز" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සීෂෙල්ස්" },
				{ LanguageId.sk, "Seychely" },
				{ LanguageId.sl, "Sejšeli" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Secheres" },
				{ LanguageId.so, "Seychelles" },
				{ LanguageId.sq, "Seychelles" },
				{ LanguageId.sr, "Сејшели" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Seychelles" },
				{ LanguageId.su, "Seychelles" },
				{ LanguageId.sv, "Seychellerna" },
				{ LanguageId.sw, "Shelisheli" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சீஷெல்ஸ்" },
				{ LanguageId.te, "సీషెల్స్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Сейшел" },
				{ LanguageId.th, "เซเชลส์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Seýşel adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Seyşeller" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сейшел утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "Seychelles" },
				{ LanguageId.uk, "Сейшельські острови" },
				{ LanguageId.ur, "سیشلز" },
				{ LanguageId.uz, "Seyshel orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Seychelles" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Seytshels" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סייטשעלס" },
				{ LanguageId.yo, "Seychelles" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "塞舌尔" },
				{ LanguageId.zu, "I-Seychelles" },
			}
		);
	}
}
