// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SC
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "248",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Seychellerne" },
				{ LanguageId.af, "Seychelle" },
				{ LanguageId.agq, "Sɛchɛ̀lɛ̀s" },
				{ LanguageId.ak, "Seyhyɛl" },
				{ LanguageId.am, "ሲሼልስ" },
				{ LanguageId.ar, "سيشل" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছিচিলিছ" },
				{ LanguageId.asa, "Shelisheli" },
				{ LanguageId.ast, "Les Seixeles" },
				{ LanguageId.az, "Seyşel adaları" },
				{ LanguageId.ba, "Сейшель утрауҙары" },
				{ LanguageId.bas, "Sèsɛ̂l" },
				{ LanguageId.be, "Сейшэльскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hushelisheli" },
				{ LanguageId.bg, "Сейшели" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Sesɛli" },
				{ LanguageId.bn, "সিসিলি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sechelez" },
				{ LanguageId.brx, "सैशेल्लेस" },
				{ LanguageId.bs, "Sejšeli" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Seychelles" },
				{ LanguageId.ccp, "𑄥𑄨𑄥𑄨𑄣𑄨" },
				{ LanguageId.ce, "Сейшелан гӀайренаш" },
				{ LanguageId.ceb, "Seychelles" },
				{ LanguageId.cgg, "Shesheresi" },
				{ LanguageId.chr, "ᏏᎡᏥᎵᏍ" },
				{ LanguageId.ckb, "سیشێل" },
				{ LanguageId.co, "Seychelles" },
				{ LanguageId.cs, "Seychely" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Seychelles" },
				{ LanguageId.dav, "Shelisheli" },
				{ LanguageId.de, "Seychellen" },
				{ LanguageId.dje, "Seešel" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Seychelle" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེ་ཤཱལས" },
				{ LanguageId.ebu, "Shelisheli" },
				{ LanguageId.ee, "Seshɛls nutome" },
				{ LanguageId.el, "Σεϋχέλλες" },
				{ LanguageId.en, "Seychelles" },
				{ LanguageId.eo, "Sejŝeloj" },
				{ LanguageId.es, "Seychelles" },
				{ LanguageId.et, "Seišellid" },
				{ LanguageId.eu, "Seychelleak" },
				{ LanguageId.ewo, "Sɛsɛ́l" },
				{ LanguageId.fa, "سیشل" },
				{ LanguageId.ff, "Seysel" },
				{ LanguageId.fi, "Seychellit" },
				{ LanguageId.fil, "Seychelles" },
				{ LanguageId.fo, "Seyskelloyggjar" },
				{ LanguageId.fr, "Seychelles" },
				{ LanguageId.fur, "Seychelles" },
				{ LanguageId.fy, "Seychellen" },
				{ LanguageId.ga, "na Séiséil" },
				{ LanguageId.gd, "Na h-Eileanan Sheiseall" },
				{ LanguageId.gl, "Seychelles" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Seischälle" },
				{ LanguageId.gu, "સેશેલ્સ" },
				{ LanguageId.guz, "Shelisheli" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Seychelles" },
				{ LanguageId.haw, "Ka Pae Moku ʻo Sekele" },
				{ LanguageId.he, "איי סיישל" },
				{ LanguageId.hi, "सेशेल्स" },
				{ LanguageId.hr, "Sejšeli" },
				{ LanguageId.hsb, "Seychelle" },
				{ LanguageId.hu, "Seychelle-szigetek" },
				{ LanguageId.hy, "Սեյշելներ" },
				{ LanguageId.ia, "Seychelles" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Seychelles" },
				{ LanguageId.ig, "Seychelles" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Seychelles-eyjar" },
				{ LanguageId.it, "Seychelles" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セーシェル" },
				{ LanguageId.jgo, "Pɛsɛ́shɛl" },
				{ LanguageId.jmc, "Shelisheli" },
				{ LanguageId.jv, "Sésèl" },
				{ LanguageId.ka, "სეიშელის კუნძულები" },
				{ LanguageId.kab, "Seycel" },
				{ LanguageId.kam, "Shelisheli" },
				{ LanguageId.kde, "Shelisheli" },
				{ LanguageId.kea, "Seixelis" },
				{ LanguageId.khq, "Seešel" },
				{ LanguageId.ki, "Shelisheli" },
				{ LanguageId.kk, "Сейшель аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Seychelles" },
				{ LanguageId.km, "សីស្ហែល" },
				{ LanguageId.kn, "ಸೀಶೆಲ್ಲೆಸ್" },
				{ LanguageId.ko, "세이셸" },
				{ LanguageId.kok, "सेशेल्स" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سیشَلِس" },
				{ LanguageId.ksb, "Shelisheli" },
				{ LanguageId.ksf, "sɛcɛl" },
				{ LanguageId.ksh, "de Seischälle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сейшел аралдары" },
				{ LanguageId.la, "Seisellenses" },
				{ LanguageId.lag, "Shelishéeli" },
				{ LanguageId.lb, "Seychellen" },
				{ LanguageId.lg, "Sesere" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sɛshɛlɛ" },
				{ LanguageId.lo, "ເຊເຊວເລສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Seišeliai" },
				{ LanguageId.luo, "Seychelles" },
				{ LanguageId.luy, "Shelisheli" },
				{ LanguageId.lv, "Seišelu salas" },
				{ LanguageId.mai, "सेशेल्स" },
				{ LanguageId.mas, "Shelisheli" },
				{ LanguageId.mer, "Shelisheli" },
				{ LanguageId.mfe, "Sesel" },
				{ LanguageId.mg, "Seyshela" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Heikere" },
				{ LanguageId.mk, "Сејшели" },
				{ LanguageId.ml, "സീഷെൽസ്" },
				{ LanguageId.mn, "Сейшелийн арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेशेल्स" },
				{ LanguageId.ms, "Seychelles" },
				{ LanguageId.mt, "is-Seychelles" },
				{ LanguageId.mua, "Saichel" },
				{ LanguageId.my, "ဆေးရှဲ" },
				{ LanguageId.mzn, "سیشل" },
				{ LanguageId.naq, "Seychelles" },
				{ LanguageId.nb, "Seychellene" },
				{ LanguageId.nd, "Seychelles" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेचेलेस" },
				{ LanguageId.nl, "Seychellen" },
				{ LanguageId.nmg, "Seychɛlle" },
				{ LanguageId.nn, "Seychellane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߋߦߌߛߍߟ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Shesheresi" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Siisheels" },
				{ LanguageId.or, "ସେଚେଲସ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਸ਼ਲਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sẹ́chẹls" },
				{ LanguageId.pl, "Seszele" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سیچیلیس" },
				{ LanguageId.pt, "Seicheles" },
				{ LanguageId.qu, "Seychelles" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Seychellas" },
				{ LanguageId.rn, "Amazinga ya Seyisheli" },
				{ LanguageId.ro, "Seychelles" },
				{ LanguageId.rof, "Shelisheli" },
				{ LanguageId.ru, "Сейшельские о-ва" },
				{ LanguageId.rw, "Seychelles" },
				{ LanguageId.rwk, "Shelisheli" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Shelisheli" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Shelisheli" },
				{ LanguageId.sd, "شي شلز" },
				{ LanguageId.se, "Seychellsullot" },
				{ LanguageId.seh, "Seychelles" },
				{ LanguageId.ses, "Seešel" },
				{ LanguageId.sg, "Sëyshêle" },
				{ LanguageId.shi, "ⵙⵙⵉⵛⵉⵍ" },
				{ LanguageId.si, "සීශෙල්ස්" },
				{ LanguageId.sk, "Seychely" },
				{ LanguageId.sl, "Sejšeli" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Seychelleh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Seychelles" },
				{ LanguageId.so, "Sishelis" },
				{ LanguageId.sq, "Sejshelle" },
				{ LanguageId.sr, "Сејшели" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Seychelles" },
				{ LanguageId.su, "Seychelles" },
				{ LanguageId.sv, "Seychellerna" },
				{ LanguageId.sw, "Ushelisheli" },
				{ LanguageId.syr, "ܣܐܝܫܝܠ" },
				{ LanguageId.ta, "சீஷெல்ஸ்" },
				{ LanguageId.te, "సీషెల్స్" },
				{ LanguageId.teo, "Shelisheli" },
				{ LanguageId.tg, "Сейшел" },
				{ LanguageId.th, "เซเชลส์" },
				{ LanguageId.ti, "ሲሸልስ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Seýşel adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Seiseli" },
				{ LanguageId.tr, "Seyşeller" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сейшел утраулары" },
				{ LanguageId.twq, "Seešel" },
				{ LanguageId.tzm, "Ssicil" },
				{ LanguageId.ug, "سېيشېل" },
				{ LanguageId.uk, "Сейшельські Острови" },
				{ LanguageId.ur, "سشلیز" },
				{ LanguageId.uz, "Seyshel orollari" },
				{ LanguageId.vai, "ꔖꗼꔷ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Seychelles" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Shelisheli" },
				{ LanguageId.wae, "Sečelle" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Seysel" },
				{ LanguageId.xh, "ESeychelles" },
				{ LanguageId.xog, "Sesere" },
				{ LanguageId.yav, "sesɛ́ɛl" },
				{ LanguageId.yi, "סיישעל" },
				{ LanguageId.yo, "Ṣeṣẹlẹsi" },
				{ LanguageId.zgh, "ⵙⵙⵉⵛⵉⵍ" },
				{ LanguageId.zh, "塞舌尔" },
				{ LanguageId.zu, "i-Seychelles" },
			}
		);
	}
}
