using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SH
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "290",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sankt Helena" },
				{ LanguageId.af, "St Helena" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቅድስት ሄለና" },
				{ LanguageId.ar, "سانت هيلانة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Müqəddəs Yelena" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Святой Алены" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Света Елена" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট হেলেনা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sveta Helena" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Santa Helena" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "St. Helena" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Santa Elena" },
				{ LanguageId.cs, "Svatá Helena" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "St Helena" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Helena" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Αγία Ελένη" },
				{ LanguageId.en, "St. Helena" },
				{ LanguageId.eo, "Sankta Heleno" },
				{ LanguageId.es, "santa elena" },
				{ LanguageId.et, "Püha Helena" },
				{ LanguageId.eu, "Santa Helena" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت هلنا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Pyhä Helena" },
				{ LanguageId.fil, "St. Helena" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Sainte-Hélène" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint Helena" },
				{ LanguageId.ga, "San Héilin" },
				{ LanguageId.gd, "Naomh Eilidh" },
				{ LanguageId.gl, "Santa Helena" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ હેલેના" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "St. Helena" },
				{ LanguageId.haw, "St. Helena" },
				{ LanguageId.he, "סנט הלנה" },
				{ LanguageId.hi, "सेंट हेलेना" },
				{ LanguageId.hr, "Sveta Helena" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Szent Ilona" },
				{ LanguageId.hy, "Սուրբ Հելենա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "St.Helena" },
				{ LanguageId.ig, "St. Helena" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Helena" },
				{ LanguageId.it, "Sant'Elena" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントヘレナ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "St Helena" },
				{ LanguageId.ka, "წმინდა ელენა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Әулие Елена" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាំងហេលេណា" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಹೆಲೆನಾ" },
				{ LanguageId.ko, "세인트 헬레나" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Ыйык Елена" },
				{ LanguageId.la, "S. Helenae" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saint Helena" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊນ ເຮເລນາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šv. Elena" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Svētā Helēna" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "St. Helena" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Helena" },
				{ LanguageId.mk, "Света Елена" },
				{ LanguageId.ml, "സെൻ്റ് ഹെലീന" },
				{ LanguageId.mn, "Гэгээн Елена" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट हेलेना" },
				{ LanguageId.ms, "St Helena" },
				{ LanguageId.mt, "Sant Elena" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စိန့်ဟယ်လီနာ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "St. Helena" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट हेलेना" },
				{ LanguageId.nl, "Sint-Helena" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଣ୍ଟ ହେଲେନା |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਹੇਲੇਨਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Święta Helena" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ هیلینا" },
				{ LanguageId.pt, "Santa Helena" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sf. Elena" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Святая Елена" },
				{ LanguageId.rw, "Mutagatifu Helena" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ هيلينا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත හෙලේනා" },
				{ LanguageId.sk, "Svätá Helena" },
				{ LanguageId.sl, "Sveta Helena" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "St. Helena" },
				{ LanguageId.so, "St. Helena" },
				{ LanguageId.sq, "Shën Helena" },
				{ LanguageId.sr, "Света Хелена" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "St. Helena" },
				{ LanguageId.su, "St Héléna" },
				{ LanguageId.sv, "S:ta Helena" },
				{ LanguageId.sw, "Mtakatifu Helena" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "புனித ஹெலினா" },
				{ LanguageId.te, "సెయింట్ హెలెనా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент Елена" },
				{ LanguageId.th, "เซนต์เฮเลน่า" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Helenaelena" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Aziz Helena" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Изге Елена" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "St. Helena" },
				{ LanguageId.uk, "Святої Єлени" },
				{ LanguageId.ur, "سینٹ ہیلینا" },
				{ LanguageId.uz, "Muqaddas Yelena" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thánh Helena" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "eSt. Helena" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סט העלענאַ" },
				{ LanguageId.yo, "Helena St" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣赫勒拿岛" },
				{ LanguageId.zu, "St. Helena" },
			}
		);
	}
}
