// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "290",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "St. Helena" },
				{ LanguageId.af, "Sint Helena" },
				{ LanguageId.agq, "Sɛ̀n Èlenà" },
				{ LanguageId.ak, "Saint Helena" },
				{ LanguageId.am, "ሴንት ሄለና" },
				{ LanguageId.ar, "سانت هيلينا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট হেলেনা" },
				{ LanguageId.asa, "Thantahelena" },
				{ LanguageId.ast, "Santa Helena" },
				{ LanguageId.az, "Müqəddəs Yelena" },
				{ LanguageId.ba, "Изге Елена утрауы" },
				{ LanguageId.bas, "Nûmpubi Ɛlēnà" },
				{ LanguageId.be, "Востраў Святой Алены" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husantahelena" },
				{ LanguageId.bg, "Света Елена" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Ɛlɛni Senu" },
				{ LanguageId.bn, "সেন্ট হেলেনা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Saint-Helena" },
				{ LanguageId.brx, "सैन्ट हेलेना" },
				{ LanguageId.bs, "Sveta Helena" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Santa Helena" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄦𑄬𑄣𑄬𑄚" },
				{ LanguageId.ce, "Сийлахьчу Еленин гӀайре" },
				{ LanguageId.ceb, "St. Helena" },
				{ LanguageId.cgg, "Senti Herena" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᎮᎵᎾ" },
				{ LanguageId.ckb, "سەن هێلێنا" },
				{ LanguageId.co, "Santa Elena" },
				{ LanguageId.cs, "Svatá Helena" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Helena" },
				{ LanguageId.dav, "Santahelena" },
				{ LanguageId.de, "St. Helena" },
				{ LanguageId.dje, "Seŋ Helena" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Helena" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ ཧེ་ལི་ན" },
				{ LanguageId.ebu, "Santahelena" },
				{ LanguageId.ee, "Saint Helena nutome" },
				{ LanguageId.el, "Αγία Ελένη" },
				{ LanguageId.en, "St. Helena" },
				{ LanguageId.eo, "Sankta Heleno" },
				{ LanguageId.es, "Santa Elena" },
				{ LanguageId.et, "Saint Helena" },
				{ LanguageId.eu, "Santa Helena" },
				{ LanguageId.ewo, "Ǹfúfúb-Ɛlɛ́na" },
				{ LanguageId.fa, "سنت هلن" },
				{ LanguageId.ff, "Sent Helen" },
				{ LanguageId.fi, "Saint Helena" },
				{ LanguageId.fil, "St. Helena" },
				{ LanguageId.fo, "St. Helena" },
				{ LanguageId.fr, "Sainte-Hélène" },
				{ LanguageId.fur, "Sante Eline" },
				{ LanguageId.fy, "Sint-Helena" },
				{ LanguageId.ga, "San Héilin" },
				{ LanguageId.gd, "Eilean Naomh Eilidh" },
				{ LanguageId.gl, "Santa Helena" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Helena" },
				{ LanguageId.gu, "સેંટ હેલેના" },
				{ LanguageId.guz, "Santahelena" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Helena" },
				{ LanguageId.haw, "St. Helena" },
				{ LanguageId.he, "סנט הלנה" },
				{ LanguageId.hi, "सेंट हेलेना" },
				{ LanguageId.hr, "Sveta Helena" },
				{ LanguageId.hsb, "St. Helena" },
				{ LanguageId.hu, "Szent Ilona" },
				{ LanguageId.hy, "Սուրբ Հեղինեի կղզի" },
				{ LanguageId.ia, "Sancte Helena" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Helena" },
				{ LanguageId.ig, "St. Helena" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Helena" },
				{ LanguageId.it, "Sant’Elena" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントヘレナ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Santahelena" },
				{ LanguageId.jv, "Saint Héléna" },
				{ LanguageId.ka, "წმინდა ელენეს კუნძული" },
				{ LanguageId.kab, "Sant Ilina" },
				{ LanguageId.kam, "Santahelena" },
				{ LanguageId.kde, "Santahelena" },
				{ LanguageId.kea, "Santa Ilena" },
				{ LanguageId.khq, "Seŋ Helena" },
				{ LanguageId.ki, "Santahelena" },
				{ LanguageId.kk, "Әулие Елена аралы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Helena Ne tilil" },
				{ LanguageId.km, "សង់​ហេឡេណា" },
				{ LanguageId.kn, "ಸೇಂಟ್ ಹೆಲೆನಾ" },
				{ LanguageId.ko, "세인트헬레나" },
				{ LanguageId.kok, "सांता हेलेना" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ ہؠلِنا" },
				{ LanguageId.ksb, "Santahelena" },
				{ LanguageId.ksf, "sɛntɛ́len" },
				{ LanguageId.ksh, "de Ensel Zint Hellena" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Ыйык Елена" },
				{ LanguageId.la, "S. Helenae" },
				{ LanguageId.lag, "Mʉtakatíifu Heléena" },
				{ LanguageId.lb, "St. Helena" },
				{ LanguageId.lg, "Senti Herena" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu eleni" },
				{ LanguageId.lo, "ເຊນ ເຮເລນາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šv. Elenos Sala" },
				{ LanguageId.luo, "Saint Helena" },
				{ LanguageId.luy, "Santahelena" },
				{ LanguageId.lv, "Sv.Helēnas sala" },
				{ LanguageId.mai, "सेंट हेलेना" },
				{ LanguageId.mas, "Santahelena" },
				{ LanguageId.mer, "Santahelena" },
				{ LanguageId.mfe, "Sainte-Hélène" },
				{ LanguageId.mg, "Sainte-Hélène" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Hērena" },
				{ LanguageId.mk, "Света Елена" },
				{ LanguageId.ml, "സെന്റ് ഹെലീന" },
				{ LanguageId.mn, "Сент Хелена" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट हेलेना" },
				{ LanguageId.ms, "Saint Helena" },
				{ LanguageId.mt, "Saint Helena" },
				{ LanguageId.mua, "Sǝr Helena" },
				{ LanguageId.my, "စိန့်ဟယ်လယ်နာ" },
				{ LanguageId.mzn, "سنت هلنا" },
				{ LanguageId.naq, "Saint Helena" },
				{ LanguageId.nb, "St. Helena" },
				{ LanguageId.nd, "Saint Helena" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट हेलेना" },
				{ LanguageId.nl, "Sint-Helena" },
				{ LanguageId.nmg, "Saint Lina" },
				{ LanguageId.nn, "Saint Helena" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߋߟߍߣ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Senti Herena" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Helenaa" },
				{ LanguageId.or, "ସେଣ୍ଟ ହେଲେନା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਹੇਲੇਨਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Hẹlẹ́na" },
				{ LanguageId.pl, "Wyspa Świętej Heleny" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ هیلینا" },
				{ LanguageId.pt, "Santa Helena" },
				{ LanguageId.qu, "Santa Elena" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sontg’Elena" },
				{ LanguageId.rn, "Sehelene" },
				{ LanguageId.ro, "Sfânta Elena" },
				{ LanguageId.rof, "Santahelena" },
				{ LanguageId.ru, "о-в Св. Елены" },
				{ LanguageId.rw, "Mutagatifu Helena" },
				{ LanguageId.rwk, "Santahelena" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Santahelena" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Santahelena" },
				{ LanguageId.sd, "سينٽ ھيلينا" },
				{ LanguageId.se, "Saint Helena" },
				{ LanguageId.seh, "Santa Helena" },
				{ LanguageId.ses, "Seŋ Helena" },
				{ LanguageId.sg, "Sênt-Helêna" },
				{ LanguageId.shi, "ⵙⴰⵏⵜⵉⵍⵉⵏ" },
				{ LanguageId.si, "ශාන්ත හෙලේනා" },
				{ LanguageId.sk, "Svätá Helena" },
				{ LanguageId.sl, "Sveta Helena" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Saint Helena" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saint Helena" },
				{ LanguageId.so, "Saynt Helena" },
				{ LanguageId.sq, "Shën-Elenë" },
				{ LanguageId.sr, "Света Јелена" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "St. Helena" },
				{ LanguageId.su, "St Héléna" },
				{ LanguageId.sv, "S:t Helena" },
				{ LanguageId.sw, "St. Helena" },
				{ LanguageId.syr, "ܡܪܬܝ ܗܝܠܝܢܐ" },
				{ LanguageId.ta, "செயின்ட் ஹெலெனா" },
				{ LanguageId.te, "సెయింట్ హెలెనా" },
				{ LanguageId.teo, "Santahelena" },
				{ LanguageId.tg, "Сент Елена" },
				{ LanguageId.th, "เซนต์เฮเลนา" },
				{ LanguageId.ti, "ቅድስቲ ሄለና" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Ýelena adasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Helena" },
				{ LanguageId.tr, "Saint Helena" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Изге Елена утравы" },
				{ LanguageId.twq, "Seŋ Helena" },
				{ LanguageId.tzm, "Santehilin" },
				{ LanguageId.ug, "ساينىت ھېلېنا" },
				{ LanguageId.uk, "Острів Святої Єлени" },
				{ LanguageId.ur, "سینٹ ہیلینا" },
				{ LanguageId.uz, "Muqaddas Yelena oroli" },
				{ LanguageId.vai, "ꔻꘋ ꗥꔷꕯ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Helena" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Santahelena" },
				{ LanguageId.wae, "St. Helena" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Eleen" },
				{ LanguageId.xh, "ESt. Helena" },
				{ LanguageId.xog, "Senti Herena" },
				{ LanguageId.yav, "sɛ́ŋtɛ́ elɛ́ɛnɛ" },
				{ LanguageId.yi, "סט העלענע" },
				{ LanguageId.yo, "Hẹlena" },
				{ LanguageId.zgh, "ⵙⴰⵏⵜⵉⵍⵉⵏ" },
				{ LanguageId.zh, "圣赫勒拿" },
				{ LanguageId.zu, "i-St. Helena" },
			}
		);
	}
}
