using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SJ
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "47",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Svalbard og Jan Mayen øerne" },
				{ LanguageId.af, "Svalbard- en Jan Mayen-eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ስቫልባርድ እና ጃን ማየን ደሴቶች" },
				{ LanguageId.ar, "جزر سفالبارد وجان ماين" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Svalbard və Yan Mayen adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Астравы Шпіцберген і Ян-Майен" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Острови Свалбард и Ян Майен" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "স্বালবার্ড এবং জান মায়েন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Svalbard ha Jan Mayen" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ostrva Svalbard i Jan Majen" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Svalbard i Jan Mayen" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga Isla sa Svalbard ug Jan Mayen" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isule Svalbard è Jan Mayen" },
				{ LanguageId.cs, "Ostrovy Svalbard a Jan Mayen" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Svalbard a Jan Mayen" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Spitzbergen und Jan-Mayen-Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησιά Σβάλμπαρντ και Γιαν Μάγιεν" },
				{ LanguageId.en, "Svalbard and Jan Mayen Islands" },
				{ LanguageId.eo, "Insuloj Svalbardo kaj Jan Mayen" },
				{ LanguageId.es, "Islas Svalbard y Jan Mayen" },
				{ LanguageId.et, "Svalbardi ja Jan Mayeni saared" },
				{ LanguageId.eu, "Svalbard eta Jan Mayen uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر سوالبارد و یان ماین" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Huippuvuoret ja Jan Mayen saaret" },
				{ LanguageId.fil, "Svalbard at Jan Mayen Islands" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Îles Svalbard et Jan Mayen" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Svalbard- en Jan Mayen-eilannen" },
				{ LanguageId.ga, "Oileáin Svalbard agus Jan Mayen" },
				{ LanguageId.gd, "Eileanan Svalbard agus Jan Mayen" },
				{ LanguageId.gl, "Illas Svalbard e Jan Mayen" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સ્વાલબાર્ડ અને જાન માયેન ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Svalbard da Jan Mayen Islands" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Svalbard a me Jan Mayen" },
				{ LanguageId.he, "איי סבאלברד ויאן מאין" },
				{ LanguageId.hi, "स्वालबार्ड और जान मायेन द्वीप समूह" },
				{ LanguageId.hr, "Otoci Svalbard i Jan Mayen" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Svalbard és Jan Mayen-szigetek" },
				{ LanguageId.hy, "Սվալբարդ և Յան Մայեն կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Svalbard dan Jan Mayen" },
				{ LanguageId.ig, "Svalbard na Jan Mayen Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Svalbarða og Jan Mayen eyjar" },
				{ LanguageId.it, "Isole Svalbard e Jan Mayen" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "スバールバル諸島とヤンマイエン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Svalbard lan Jan Mayen" },
				{ LanguageId.ka, "სვალბარდი და იან მაიენის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Шпицберген және Ян-Майен аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Svalbard និង Jan Mayen" },
				{ LanguageId.kn, "ಸ್ವಾಲ್ಬಾರ್ಡ್ ಮತ್ತು ಜಾನ್ ಮಾಯೆನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "스발바르 제도와 얀마옌 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Шпицберген жана Ян-Майен аралдары" },
				{ LanguageId.la, "Insulae Svalbard et Jan Mayen" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Svalbard a Jan Mayen Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະ Svalbard ແລະ Jan Mayen" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Svalbardo ir Jano Majeno salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Svalbāras un Jana Majena salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Svalbard sy Jan Mayen" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Nga Moutere o Svalbard me Jan Mayen" },
				{ LanguageId.mk, "Островите Свалбард и Јан Мајен" },
				{ LanguageId.ml, "സ്വാൽബാർഡും ജാൻ മായൻ ദ്വീപുകളും" },
				{ LanguageId.mn, "Шпицберген ба Ян Майен арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "स्वालबार्ड आणि जॅन मायन बेटे" },
				{ LanguageId.ms, "Kepulauan Svalbard dan Jan Mayen" },
				{ LanguageId.mt, "Gżejjer Svalbard u Jan Mayen" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Svalbard နှင့် Jan Mayen ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Svalbard og Jan Mayen" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "स्वाल्बार्ड र जान मायन टापुहरू" },
				{ LanguageId.nl, "Svalbard- en Jan Mayen-eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସ୍ val ାଲବାର୍ଡ ଏବଂ ଜାନ ମାୟେନ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਵੈਲਬਾਰਡ ਅਤੇ ਜਾਨ ਮਾਯੇਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Svalbard i Jan Mayen" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سویلبارډ او جان میین ټاپوګان" },
				{ LanguageId.pt, "Ilhas Svalbard e Jan Mayen" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Svalbard și Jan Mayen" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Острова Шпицберген и Ян-Майен" },
				{ LanguageId.rw, "Ibirwa bya Svalbard na Jan Mayen" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سوالبارڊ ۽ جان ميين ٻيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "Svalbard සහ Jan Mayen දූපත්" },
				{ LanguageId.sk, "Svalbard a ostrovy Jan Mayen" },
				{ LanguageId.sl, "Otoki Svalbard in Jan Mayen" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveSvalbard neJan Mayen" },
				{ LanguageId.so, "Svalbard iyo Jan Mayen Islands" },
				{ LanguageId.sq, "Ishujt Svalbard dhe Jan Mayen" },
				{ LanguageId.sr, "Острва Свалбард и Јан Мајен" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Svalbard le Jan Mayen" },
				{ LanguageId.su, "Kapuloan Svalbard jeung Jan Mayen" },
				{ LanguageId.sv, "Svalbard och Jan Mayenöarna" },
				{ LanguageId.sw, "Visiwa vya Svalbard na Jan Mayen" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "ஸ்வால்பார்ட் மற்றும் ஜான் மேயன் தீவுகள்" },
				{ LanguageId.te, "స్వాల్బార్డ్ మరియు జాన్ మాయెన్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Шпицберд ва Ян Майен" },
				{ LanguageId.th, "หมู่เกาะสฟาลบาร์และยานไมเอน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Swalbard we Mayan Maýen adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Svalbard ve Jan Mayen Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Свальбард һәм Ян Майен утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سۋالبارد ۋە يان مايېن ئارىلى" },
				{ LanguageId.uk, "Острови Шпіцберген і Ян-Майен" },
				{ LanguageId.ur, "سوالبارڈ اور جان ماین جزائر" },
				{ LanguageId.uz, "Svalbard va Yan Mayen orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Svalbard và Jan Mayen" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseSvalbard kunye neJan Mayen" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סוואַלבאַרד און Jan Mayen אינזלען" },
				{ LanguageId.yo, "Svalbard ati Jan Mayen Islands" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "斯瓦尔巴群岛和扬马延群岛" },
				{ LanguageId.zu, "Iziqhingi zaseSvalbard naseJan Mayen" },
			}
		);
	}
}
