// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SJ
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "47",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Svalbard og Jan Mayen" },
				{ LanguageId.af, "Spitsbergen en Jan Mayen" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Svalbard ne Jan Mayen" },
				{ LanguageId.am, "ስቫልባርድ እና ጃን ማየን" },
				{ LanguageId.ar, "سفالبارد وجان ماين" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চাভালবাৰ্ড আৰু জন মেয়ন" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Svalbard ya Islla Jan Mayen" },
				{ LanguageId.az, "Svalbard və Yan-Mayen" },
				{ LanguageId.ba, "Шпицберген һәм Ян-Майен" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Шпіцберген і Ян-Маен" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Свалбард и Ян Майен" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "স্বালবার্ড ও জান মেয়েন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Svalbard" },
				{ LanguageId.brx, "स्भालबार्ड आरो जान मायेन" },
				{ LanguageId.bs, "Svalbard i Jan Mayen" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Svalbard i Jan Mayen" },
				{ LanguageId.ccp, "𑄥𑄣𑄴𑄝𑄢𑄴𑄓𑄴 𑄃𑄮 𑄎𑄚𑄴 𑄟𑄬𑄠𑄬𑄚𑄴" },
				{ LanguageId.ce, "Шпицберген а, Ян-Майен а" },
				{ LanguageId.ceb, "Svalbard & Jan Mayen" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏍᏩᎵᏆᎵᏗ ᎠᎴ ᏤᏂ ᎹᏰᏂ" },
				{ LanguageId.ckb, "سڤالبارد و یان مایەن" },
				{ LanguageId.co, "Isule Svalbard è Jan Mayen" },
				{ LanguageId.cs, "Špicberky a Jan Mayen" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Svalbard a Jan Mayen" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Spitzbergen und Jan Mayen" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Svalbard a Jan Mayen" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སྭཱལ་བྷརྡ་ ཨེནཌ་ ཇཱན་མ་ཡེན" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "Svalbard kple Yan Mayen nutome" },
				{ LanguageId.el, "Σβάλμπαρντ και Γιαν Μαγιέν" },
				{ LanguageId.en, "Svalbard & Jan Mayen" },
				{ LanguageId.eo, "Svalbardo kaj Janmajeno" },
				{ LanguageId.es, "Svalbard y Jan Mayen" },
				{ LanguageId.et, "Svalbard ja Jan Mayen" },
				{ LanguageId.eu, "Svalbard eta Jan Mayen uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سوالبارد و یان ماین" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Huippuvuoret ja Jan Mayen" },
				{ LanguageId.fil, "Svalbard & Jan Mayen" },
				{ LanguageId.fo, "Svalbard & Jan Mayen" },
				{ LanguageId.fr, "Svalbard et Jan Mayen" },
				{ LanguageId.fur, "Svalbard e Jan Mayen" },
				{ LanguageId.fy, "Spitsbergen en Jan Mayen" },
				{ LanguageId.ga, "Svalbard agus Jan Mayen" },
				{ LanguageId.gd, "Svalbard is Jan Mayen" },
				{ LanguageId.gl, "Svalbard e Jan Mayen" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Svalbard und Jaan Määie" },
				{ LanguageId.gu, "સ્વાલબર્ડ અને જેન મેયન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Svalbard da Jan Mayen" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Svalbard a me Jan Mayen" },
				{ LanguageId.he, "סבאלברד ויאן מאיין" },
				{ LanguageId.hi, "स्वालबार्ड और जान मायेन" },
				{ LanguageId.hr, "Svalbard i Jan Mayen" },
				{ LanguageId.hsb, "Svalbard a Jan Mayen" },
				{ LanguageId.hu, "Svalbard és Jan Mayen" },
				{ LanguageId.hy, "Սվալբարդ և Յան Մայեն" },
				{ LanguageId.ia, "Svalbard e Jan Mayen" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Svalbard dan Jan Mayen" },
				{ LanguageId.ig, "Svalbard & Jan Mayen" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Svalbarði og Jan Mayen" },
				{ LanguageId.it, "Svalbard e Jan Mayen" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "スバールバル諸島・ヤンマイエン島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Svalbard lan Jan Mayen" },
				{ LanguageId.ka, "შპიცბერგენი და იან-მაიენი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Svalbard i Jan Maien" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Шпицберген және Ян-Майен" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ស្វាលបាដ និង ហ្សង់ម៉ាយេន" },
				{ LanguageId.kn, "ಸ್ವಾಲ್ಬಾರ್ಡ್ ಮತ್ತು ಜಾನ್ ಮೆಯನ್" },
				{ LanguageId.ko, "스발바르제도-얀마웬섬" },
				{ LanguageId.kok, "स्वालबार्ड आनी यान मायेन" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سَوالبریڑ تہٕ جان ماییڑ" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "de Enselle Svalbard un Jan Mayen" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Шпицберген жана Ян-Майен" },
				{ LanguageId.la, "Insulae Svalbard et Jan Mayen" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Svalbard a Jan Mayen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສະວາບາ ແລະ ແຢນ ມາເຢນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Svalbardas ir Janas Majenas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Svalbāra un Jana Majena sala" },
				{ LanguageId.mai, "स्वालबार्ड आ जान मायेन" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Svalbard sy Jan Mayen" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Heopara me Iana Maiana" },
				{ LanguageId.mk, "Свалбард и Јан Мајен" },
				{ LanguageId.ml, "സ്വാൽബാഡും ജാൻ മായേനും" },
				{ LanguageId.mn, "Свалбард ба Ян Майен" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "स्वालबर्ड आणि जान मायेन" },
				{ LanguageId.ms, "Svalbard dan Jan Mayen" },
				{ LanguageId.mt, "Svalbard u Jan Mayen" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စဗိုလ်ဘတ်နှင့်ဂျန်မေရန်" },
				{ LanguageId.mzn, "سوالبارد و يان ماين" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Svalbard og Jan Mayen" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सभाल्बार्ड र जान मायेन" },
				{ LanguageId.nl, "Spitsbergen en Jan Mayen" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Svalbard og Jan Mayen" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߊߟߑߓߊߙ ߣߌ߫ ߖ߭ߊ߲ ߡߊߦߍ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Isvaalbaard fi Jan Mayeen" },
				{ LanguageId.or, "ସାଲବାର୍ଡ ଏବଂ ଜାନ୍‌ ମାୟେନ୍‌" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਵਾਲਬਰਡ ਅਤੇ ਜਾਨ ਮਾਯੇਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sválbad & Jén Meyẹn" },
				{ LanguageId.pl, "Svalbard i Jan Mayen" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سوالبارد او جان ميين" },
				{ LanguageId.pt, "Svalbard e Jan Mayen" },
				{ LanguageId.qu, "Svalbard y Jan Mayen" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Svalbard e Jan Mayen" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Svalbard și Jan Mayen" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Шпицберген и Ян-Майен" },
				{ LanguageId.rw, "Ibirwa bya Svalbard na Jan Mayen" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سوالبارڊ ۽ يان ماین" },
				{ LanguageId.se, "Svalbárda ja Jan Mayen" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ස්වෙල්බර්ඩ් සහ ජේන් මයේන්" },
				{ LanguageId.sk, "Svalbard a Jan Mayen" },
				{ LanguageId.sl, "Svalbard in Jan Mayen" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Čokkeväärih já Jan Mayen" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveSvalbard neJan Mayen" },
				{ LanguageId.so, "Jasiiradda Sfaldbaad & Jaan Mayen" },
				{ LanguageId.sq, "Svalbard e Jan-Majen" },
				{ LanguageId.sr, "Свалбард и Јан Мајен" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Svalbard le Jan Mayen" },
				{ LanguageId.su, "Kapuloan Svalbard jeung Jan Mayen" },
				{ LanguageId.sv, "Svalbard och Jan Mayen" },
				{ LanguageId.sw, "Svalbard na Jan Mayen" },
				{ LanguageId.syr, "ܣܒܠܕܒܪܕ ܘܓܐܢ ܡܐܝܝܢ" },
				{ LanguageId.ta, "ஸ்வல்பார்டு & ஜான் மேயன்" },
				{ LanguageId.te, "స్వాల్‌బార్డ్ మరియు జాన్ మాయెన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Шпитсберген ва Ян Майен" },
				{ LanguageId.th, "สฟาลบาร์และยานไมเอน" },
				{ LanguageId.ti, "ስቫልባርድን ጃን ማየንን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Şpisbergen we Ýan-Maýen" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sivolopāti mo Sani Maieni" },
				{ LanguageId.tr, "Svalbard ve Jan Mayen" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Шпицберген һәм Ян-Майен" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سىۋالبارد ۋە يان مايېن" },
				{ LanguageId.uk, "Шпіцберген та Ян-Маєн" },
				{ LanguageId.ur, "سوالبرڈ اور جان ماین" },
				{ LanguageId.uz, "Shpitsbergen va Yan-Mayen" },
				{ LanguageId.vai, "ꔻꕙꕒꔵ ꗪ ꕧꘋ ꕮꘂꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Svalbard và Jan Mayen" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "Svalbard und Jan Mayen" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Swalbaar ak Jan Mayen" },
				{ LanguageId.xh, "ESvalbard & Jan Mayen" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סוואַלבאַרד און Jan Mayen אינזלען" },
				{ LanguageId.yo, "Sífábáàdì àti Jánì Máyẹ̀nì" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "斯瓦尔巴和扬马延" },
				{ LanguageId.zu, "i-Svalbard ne-Jan Mayen" },
			}
		);
	}
}
