// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SL
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "232",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sierra Leone" },
				{ LanguageId.af, "Sierra Leone" },
				{ LanguageId.agq, "Silìa lûŋ" },
				{ LanguageId.ak, "Sɛra Liɔn" },
				{ LanguageId.am, "ሴራሊዮን" },
				{ LanguageId.ar, "سيراليون" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চিয়েৰা লিঅ’ন" },
				{ LanguageId.asa, "Thiera Leoni" },
				{ LanguageId.ast, "Sierra Lleona" },
				{ LanguageId.az, "Syerra-Leone" },
				{ LanguageId.ba, "Сьерра-Леоне" },
				{ LanguageId.bas, "Sièra Lèɔ̂n" },
				{ LanguageId.be, "Сьера-Леонэ" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husiela Lioni" },
				{ LanguageId.bg, "Сиера Леоне" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Siyera Lewɔni" },
				{ LanguageId.bn, "সিয়েরা লিওন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sierra Leone" },
				{ LanguageId.brx, "सियेरा लेओन" },
				{ LanguageId.bs, "Sijera Leone" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sierra Leone" },
				{ LanguageId.ccp, "𑄥𑄨𑄠𑄬𑄢𑄣𑄨𑄃𑄮𑄚𑄴" },
				{ LanguageId.ce, "Сьерра- Леоне" },
				{ LanguageId.ceb, "Sierra Leone" },
				{ LanguageId.cgg, "Sirra Riyooni" },
				{ LanguageId.chr, "ᏏᎡᎳ ᎴᎣᏂ" },
				{ LanguageId.ckb, "سیەرالیۆن" },
				{ LanguageId.co, "Sierra Leone" },
				{ LanguageId.cs, "Sierra Leone" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sierra Leone" },
				{ LanguageId.dav, "Siera Leoni" },
				{ LanguageId.de, "Sierra Leone" },
				{ LanguageId.dje, "Seera Leon" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Sierra Leone" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སི་ར་ ལི་འོན" },
				{ LanguageId.ebu, "Siera Leoni" },
				{ LanguageId.ee, "Sierra Leone nutome" },
				{ LanguageId.el, "Σιέρα Λεόνε" },
				{ LanguageId.en, "Sierra Leone" },
				{ LanguageId.eo, "Sieraleono" },
				{ LanguageId.es, "Sierra Leona" },
				{ LanguageId.et, "Sierra Leone" },
				{ LanguageId.eu, "Sierra Leona" },
				{ LanguageId.ewo, "Sierá-leónə" },
				{ LanguageId.fa, "سیرالئون" },
				{ LanguageId.ff, "Seraa liyon" },
				{ LanguageId.fi, "Sierra Leone" },
				{ LanguageId.fil, "Sierra Leone" },
				{ LanguageId.fo, "Sierra Leona" },
				{ LanguageId.fr, "Sierra Leone" },
				{ LanguageId.fur, "Sierra Leone" },
				{ LanguageId.fy, "Sierra Leone" },
				{ LanguageId.ga, "Siarra Leon" },
				{ LanguageId.gd, "Siarra Leòmhann" },
				{ LanguageId.gl, "Serra Leoa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Sierra Leoone" },
				{ LanguageId.gu, "સીએરા લેઓન" },
				{ LanguageId.guz, "Siera Leoni" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Salewo" },
				{ LanguageId.haw, "Sielaleone" },
				{ LanguageId.he, "סיירה לאון" },
				{ LanguageId.hi, "सिएरा लियोन" },
				{ LanguageId.hr, "Sijera Leone" },
				{ LanguageId.hsb, "Sierra Leone" },
				{ LanguageId.hu, "Sierra Leone" },
				{ LanguageId.hy, "Սիեռա Լեոնե" },
				{ LanguageId.ia, "Sierra Leone" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sierra Leone" },
				{ LanguageId.ig, "Sierra Leone" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Síerra Leóne" },
				{ LanguageId.it, "Sierra Leone" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シエラレオネ" },
				{ LanguageId.jgo, "Siyɛ́la Lɛɔ̂n" },
				{ LanguageId.jmc, "Siera Leoni" },
				{ LanguageId.jv, "Siéra Léoné" },
				{ LanguageId.ka, "სიერა-ლეონე" },
				{ LanguageId.kab, "Sira Lyun" },
				{ LanguageId.kam, "Siera Leoni" },
				{ LanguageId.kde, "Siela Leoni" },
				{ LanguageId.kea, "Sera Lioa" },
				{ LanguageId.khq, "Seera Leon" },
				{ LanguageId.ki, "Siera Leoni" },
				{ LanguageId.kk, "Сьерра-Леоне" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Sierra Leone" },
				{ LanguageId.km, "សៀរ៉ាឡេអូន" },
				{ LanguageId.kn, "ಸಿಯೆರ್ರಾ ಲಿಯೋನ್" },
				{ LanguageId.ko, "시에라리온" },
				{ LanguageId.kok, "सेर्रा लेओं" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سیرا لیون" },
				{ LanguageId.ksb, "Siela Leoni" },
				{ LanguageId.ksf, "syɛraleon" },
				{ LanguageId.ksh, "Sjärra Lejone" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сьерра-Леоне" },
				{ LanguageId.la, "Mons Leoninus" },
				{ LanguageId.lag, "Seraleóoni" },
				{ LanguageId.lb, "Sierra Leone" },
				{ LanguageId.lg, "Siyeralewone" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Siera Leonɛ" },
				{ LanguageId.lo, "ເຊຍຣາ ລີໂອນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Siera Leonė" },
				{ LanguageId.luo, "Sierra Leone" },
				{ LanguageId.luy, "Siera Leoni" },
				{ LanguageId.lv, "Sjerraleone" },
				{ LanguageId.mai, "सियरा लियोन" },
				{ LanguageId.mas, "Siera Leoni" },
				{ LanguageId.mer, "Siera Leoni" },
				{ LanguageId.mfe, "Sierra Leone" },
				{ LanguageId.mg, "Sierra Leone" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Araone" },
				{ LanguageId.mk, "Сиера Леоне" },
				{ LanguageId.ml, "സിയെറ ലിയോൺ" },
				{ LanguageId.mn, "Сьерра-Леоне" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सिएरा लिओन" },
				{ LanguageId.ms, "Sierra Leone" },
				{ LanguageId.mt, "Sierra Leone" },
				{ LanguageId.mua, "Sierra Leonǝ" },
				{ LanguageId.my, "ဆီယာရာ လီယွန်း" },
				{ LanguageId.mzn, "سیرالئون" },
				{ LanguageId.naq, "Sierra Leone" },
				{ LanguageId.nb, "Sierra Leone" },
				{ LanguageId.nd, "Sierra Leone" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सिएर्रा लिओन" },
				{ LanguageId.nl, "Sierra Leone" },
				{ LanguageId.nmg, "Sierra Leɔn" },
				{ LanguageId.nn, "Sierra Leone" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߙߊ߬ߟߏ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Sirra Riyooni" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Seeraaliyoon" },
				{ LanguageId.or, "ସିଏରା ଲିଓନ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਿਏਰਾ ਲਿਓਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Siẹ́ra Líon" },
				{ LanguageId.pl, "Sierra Leone" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سییرا لیون" },
				{ LanguageId.pt, "Serra Leoa" },
				{ LanguageId.qu, "Sierra Leona" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sierra Leone" },
				{ LanguageId.rn, "Siyeralewone" },
				{ LanguageId.ro, "Sierra Leone" },
				{ LanguageId.rof, "Siera Leoni" },
				{ LanguageId.ru, "Сьерра-Леоне" },
				{ LanguageId.rw, "Siyera Lewone" },
				{ LanguageId.rwk, "Siera Leoni" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Siera Leoni" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Siela Liyoni" },
				{ LanguageId.sd, "سيرا ليون" },
				{ LanguageId.se, "Sierra Leone" },
				{ LanguageId.seh, "Serra Leoa" },
				{ LanguageId.ses, "Seera Leon" },
				{ LanguageId.sg, "Sierä-Leône" },
				{ LanguageId.shi, "ⵙⵙⵉⵔⴰⵍⵢⵓⵏ" },
				{ LanguageId.si, "සියරාලියෝන්" },
				{ LanguageId.sk, "Sierra Leone" },
				{ LanguageId.sl, "Sierra Leone" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Sierra Leone" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sierra Leone" },
				{ LanguageId.so, "Siraaliyoon" },
				{ LanguageId.sq, "Sierra-Leone" },
				{ LanguageId.sr, "Сијера Леоне" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sierra Leone" },
				{ LanguageId.su, "Sierra Leone" },
				{ LanguageId.sv, "Sierra Leone" },
				{ LanguageId.sw, "Siera Leoni" },
				{ LanguageId.syr, "ܣܝܝܪܐ ܠܝܐܘܢܝ" },
				{ LanguageId.ta, "சியாரா லியோன்" },
				{ LanguageId.te, "సియెర్రా లియాన్" },
				{ LanguageId.teo, "Siera Leoni" },
				{ LanguageId.tg, "Сиерра-Леоне" },
				{ LanguageId.th, "เซียร์ราลีโอน" },
				{ LanguageId.ti, "ሴራ ልዮን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sýerra-Leone" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Siela Leone" },
				{ LanguageId.tr, "Sierra Leone" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сьерра-Леоне" },
				{ LanguageId.twq, "Seera Leon" },
				{ LanguageId.tzm, "Siralyun" },
				{ LanguageId.ug, "سېررالېئون" },
				{ LanguageId.uk, "Сьєрра-Леоне" },
				{ LanguageId.ur, "سیرالیون" },
				{ LanguageId.uz, "Syerra-Leone" },
				{ LanguageId.vai, "ꔋꕩ ꕒꕌꖺ ꕸꖃꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sierra Leone" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Siera Leoni" },
				{ LanguageId.wae, "Sierra Leone" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Siyera Lewon" },
				{ LanguageId.xh, "ESierra Leone" },
				{ LanguageId.xog, "Siyeralewone" },
				{ LanguageId.yav, "sieláleyɔ́ɔn" },
				{ LanguageId.yi, "סיערע לעאנע" },
				{ LanguageId.yo, "Siria looni" },
				{ LanguageId.zgh, "ⵙⵙⵉⵔⴰⵍⵢⵓⵏ" },
				{ LanguageId.zh, "塞拉利昂" },
				{ LanguageId.zu, "i-Sierra Leone" },
			}
		);
	}
}
