using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SL
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "232",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sierra Leone" },
				{ LanguageId.af, "Sierra Leone" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሰራሊዮን" },
				{ LanguageId.ar, "سيرا ليون" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Sierra Leone" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сьера-Леонэ" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сиера Леоне" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সিয়েরা লিওন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sierra Leone" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sierra Leone" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sierra Leone" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Sierra Leone" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Sierra Leone" },
				{ LanguageId.cs, "Sierra Leone" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sierra Leone" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Sierra Leone" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σιέρρα Λεόνε" },
				{ LanguageId.en, "Sierra Leone" },
				{ LanguageId.eo, "Siera-Leono" },
				{ LanguageId.es, "Sierra Leona" },
				{ LanguageId.et, "Sierra Leone" },
				{ LanguageId.eu, "Sierra Leona" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سیرا لئون" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Sierra Leone" },
				{ LanguageId.fil, "Sierra Leone" },
				{ LanguageId.fo, "Sierra Leona" },
				{ LanguageId.fr, "Sierra Leone" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sierra Leöane" },
				{ LanguageId.ga, "Siarra Leon" },
				{ LanguageId.gd, "Sierra Leone" },
				{ LanguageId.gl, "Serra Leoa" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સિએરા લિયોન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saliyo" },
				{ LanguageId.haw, "Sielaleone" },
				{ LanguageId.he, "סיירה לאון" },
				{ LanguageId.hi, "सेरा लिओन" },
				{ LanguageId.hr, "Sijera Leone" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Sierra Leone" },
				{ LanguageId.hy, "Սիերա Լեոնե" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sierra Leone" },
				{ LanguageId.ig, "Sierra Leone" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sierra Leone" },
				{ LanguageId.it, "Sierra Leone" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シエラレオネ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sierra Leone" },
				{ LanguageId.ka, "სიერა ლეონე" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сьерра-Леоне" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សៀរ៉ាឡេអូន" },
				{ LanguageId.kn, "ಸಿಯೆರಾ ಲಿಯೋನ್" },
				{ LanguageId.ko, "시에라리온" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сьерра-Леоне" },
				{ LanguageId.la, "Mons Leoninus" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Sierra Leone" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ເຊຍຣາລີໂອນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Siera Leonė" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sjerraleone" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Sierra Leone" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Sierra Leone" },
				{ LanguageId.mk, "Сиера Леоне" },
				{ LanguageId.ml, "സിയറ ലിയോൺ" },
				{ LanguageId.mn, "Сьерра-Леон" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सिएरा लिओन" },
				{ LanguageId.ms, "Sierra Leone" },
				{ LanguageId.mt, "Sierra Leone" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆီးရီးယားလီယွန်း" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sierra Leone" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सियरा लियोन" },
				{ LanguageId.nl, "Sierra Leone" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Sierra Leone" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସିଆରପିଏଫ୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੀਅਰਾ ਲਿਓਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Sierra Leone" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سییرا لیون" },
				{ LanguageId.pt, "Serra Leoa" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sierra Leone" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сьерра-Леоне" },
				{ LanguageId.rw, "Siyera Lewone" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سيري لون" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සියාරා ලියොන්" },
				{ LanguageId.sk, "Sierra Leone" },
				{ LanguageId.sl, "Sierra Leone" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Siyera Riyoni" },
				{ LanguageId.so, "Siiraaliyoon" },
				{ LanguageId.sq, "Sierra Leone" },
				{ LanguageId.sr, "Сијера Леоне" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sierra Leone" },
				{ LanguageId.su, "Sierra Leone" },
				{ LanguageId.sv, "Sierra Leone" },
				{ LanguageId.sw, "Sierra Leone" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சியரா லியோன்" },
				{ LanguageId.te, "సియర్రా లియోన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Серра-Леоне" },
				{ LanguageId.th, "เซียร์ราลีโอน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sierra Leone" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Sierra Leone" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сьерра-Леоне" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سېررالېئون" },
				{ LanguageId.uk, "Сьєрра-Леоне" },
				{ LanguageId.ur, "سیرا لیون" },
				{ LanguageId.uz, "Syerra-Leone" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sierra Leone" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Sira Liyoni " },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיעראַ ליאָון" },
				{ LanguageId.yo, "Sierra Leone" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "塞拉利昂" },
				{ LanguageId.zu, "eSierra Leone" },
			}
		);
	}
}
