// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SM
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "378",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "San Marino" },
				{ LanguageId.af, "San Marino" },
				{ LanguageId.agq, "Sàn Màlenù" },
				{ LanguageId.ak, "San Marino" },
				{ LanguageId.am, "ሳን ማሪኖ" },
				{ LanguageId.ar, "سان مارينو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চান মাৰিনো" },
				{ LanguageId.asa, "Thamarino" },
				{ LanguageId.ast, "San Marín" },
				{ LanguageId.az, "San-Marino" },
				{ LanguageId.ba, "Сан-Марино" },
				{ LanguageId.bas, "Nûmpubi Māatìn" },
				{ LanguageId.be, "Сан-Марына" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husamalino" },
				{ LanguageId.bg, "Сан Марино" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Marini-Senu" },
				{ LanguageId.bn, "সান মারিনো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "San Marino" },
				{ LanguageId.brx, "सान मेरिन’" },
				{ LanguageId.bs, "San Marino" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "San Marino" },
				{ LanguageId.ccp, "𑄥𑄚𑄴 𑄟𑄢𑄨𑄚𑄮" },
				{ LanguageId.ce, "Сан-Марино" },
				{ LanguageId.ceb, "San Marino" },
				{ LanguageId.cgg, "Samarino" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᎹᎵᎢᏃ" },
				{ LanguageId.ckb, "سان مارینۆ" },
				{ LanguageId.co, "San Marinu" },
				{ LanguageId.cs, "San Marino" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "San Marino" },
				{ LanguageId.dav, "Samarino" },
				{ LanguageId.de, "San Marino" },
				{ LanguageId.dje, "San Marino" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "San Marino" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སཱན་མ་རི་ནོ" },
				{ LanguageId.ebu, "Samarino" },
				{ LanguageId.ee, "San Marino nutome" },
				{ LanguageId.el, "Άγιος Μαρίνος" },
				{ LanguageId.en, "San Marino" },
				{ LanguageId.eo, "Sanmarino" },
				{ LanguageId.es, "San Marino" },
				{ LanguageId.et, "San Marino" },
				{ LanguageId.eu, "San Marino" },
				{ LanguageId.ewo, "Ǹfúfúb Maríno" },
				{ LanguageId.fa, "سان‌مارینو" },
				{ LanguageId.ff, "See Maree" },
				{ LanguageId.fi, "San Marino" },
				{ LanguageId.fil, "San Marino" },
				{ LanguageId.fo, "San Marino" },
				{ LanguageId.fr, "Saint-Marin" },
				{ LanguageId.fur, "San Marin" },
				{ LanguageId.fy, "San Marino" },
				{ LanguageId.ga, "San Mairíne" },
				{ LanguageId.gd, "San Marino" },
				{ LanguageId.gl, "San Marino" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "San Mariino" },
				{ LanguageId.gu, "સૅન મેરિનો" },
				{ LanguageId.guz, "Samarino" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Marino" },
				{ LanguageId.haw, "Sana Marino" },
				{ LanguageId.he, "סן מרינו" },
				{ LanguageId.hi, "सैन मेरीनो" },
				{ LanguageId.hr, "San Marino" },
				{ LanguageId.hsb, "San Marino" },
				{ LanguageId.hu, "San Marino" },
				{ LanguageId.hy, "Սան Մարինո" },
				{ LanguageId.ia, "San Marino" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "San Marino" },
				{ LanguageId.ig, "San Marino" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "San Marínó" },
				{ LanguageId.it, "San Marino" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サンマリノ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Samarino" },
				{ LanguageId.jv, "San Marino" },
				{ LanguageId.ka, "სან-მარინო" },
				{ LanguageId.kab, "San Marinu" },
				{ LanguageId.kam, "Samarino" },
				{ LanguageId.kde, "Samalino" },
				{ LanguageId.kea, "San Marinu" },
				{ LanguageId.khq, "San Marino" },
				{ LanguageId.ki, "Samarino" },
				{ LanguageId.kk, "Сан-Марино" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab San Marino" },
				{ LanguageId.km, "សាន​ម៉ារីណូ" },
				{ LanguageId.kn, "ಸ್ಯಾನ್ ಮೆರಿನೋ" },
				{ LanguageId.ko, "산마리노" },
				{ LanguageId.kok, "सान मारीनो" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سین میرِنو" },
				{ LanguageId.ksb, "Samalino" },
				{ LanguageId.ksf, "sɛnmarǝn" },
				{ LanguageId.ksh, "San-Marino" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сан Марино" },
				{ LanguageId.la, "San Marino" },
				{ LanguageId.lag, "Samaríino" },
				{ LanguageId.lb, "San Marino" },
				{ LanguageId.lg, "Sanimarino" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu Marinɛ" },
				{ LanguageId.lo, "ແຊນ ມາຣິໂນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "San Marinas" },
				{ LanguageId.luo, "San Marino" },
				{ LanguageId.luy, "Samarino" },
				{ LanguageId.lv, "Sanmarīno" },
				{ LanguageId.mai, "सेन मरीनो" },
				{ LanguageId.mas, "Samarino" },
				{ LanguageId.mer, "Samarino" },
				{ LanguageId.mfe, "Saint-Marin" },
				{ LanguageId.mg, "Saint-Marin" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hana Marino" },
				{ LanguageId.mk, "Сан Марино" },
				{ LanguageId.ml, "സാൻ മറിനോ" },
				{ LanguageId.mn, "Сан-Марино" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सॅन मरीनो" },
				{ LanguageId.ms, "San Marino" },
				{ LanguageId.mt, "San Marino" },
				{ LanguageId.mua, "Sǝr Marino" },
				{ LanguageId.my, "ဆန်မာရီနို" },
				{ LanguageId.mzn, "سن مارینو" },
				{ LanguageId.naq, "San Marino" },
				{ LanguageId.nb, "San Marino" },
				{ LanguageId.nd, "San Marino" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सान् मारिनो" },
				{ LanguageId.nl, "San Marino" },
				{ LanguageId.nmg, "San Marino" },
				{ LanguageId.nn, "San Marino" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍߕ-ߡߊߙߍ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Samarino" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Saan Mariinoo" },
				{ LanguageId.or, "ସାନ୍ ମାରିନୋ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੈਨ ਮਰੀਨੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "San Maríno" },
				{ LanguageId.pl, "San Marino" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سان مارینو" },
				{ LanguageId.pt, "San Marino" },
				{ LanguageId.qu, "San Marino" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Son Marin" },
				{ LanguageId.rn, "Sanimarino" },
				{ LanguageId.ro, "San Marino" },
				{ LanguageId.rof, "Samarino" },
				{ LanguageId.ru, "Сан-Марино" },
				{ LanguageId.rw, "San Marino" },
				{ LanguageId.rwk, "Samarino" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Samarino" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Samalino" },
				{ LanguageId.sd, "سان مرینو" },
				{ LanguageId.se, "San Marino" },
				{ LanguageId.seh, "San Marino" },
				{ LanguageId.ses, "San Marino" },
				{ LanguageId.sg, "Sên-Marëen" },
				{ LanguageId.shi, "ⵙⴰⵏⵎⴰⵔⵉⵏⵓ" },
				{ LanguageId.si, "සැන් මැරිනෝ" },
				{ LanguageId.sk, "San Maríno" },
				{ LanguageId.sl, "San Marino" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "San Marino" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "San Marino" },
				{ LanguageId.so, "San Marino" },
				{ LanguageId.sq, "San-Marino" },
				{ LanguageId.sr, "Сан Марино" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "San Marino" },
				{ LanguageId.su, "San Marino" },
				{ LanguageId.sv, "San Marino" },
				{ LanguageId.sw, "San Marino" },
				{ LanguageId.syr, "ܣܢ ܡܪܝܢܘ" },
				{ LanguageId.ta, "சான் மரினோ" },
				{ LanguageId.te, "శాన్ మారినో" },
				{ LanguageId.teo, "Samarino" },
				{ LanguageId.tg, "Сан-Марино" },
				{ LanguageId.th, "ซานมาริโน" },
				{ LanguageId.ti, "ሳን ማሪኖ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "San-Marino" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Malino" },
				{ LanguageId.tr, "San Marino" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сан-Марино" },
				{ LanguageId.twq, "San Marino" },
				{ LanguageId.tzm, "Sanmarinu" },
				{ LanguageId.ug, "سان مارىنو" },
				{ LanguageId.uk, "Сан-Марино" },
				{ LanguageId.ur, "سان مارینو" },
				{ LanguageId.uz, "San-Marino" },
				{ LanguageId.vai, "ꕮꔸꖆ ꕢꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "San Marino" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Samarino" },
				{ LanguageId.wae, "San Marino" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "San Marino" },
				{ LanguageId.xh, "ESan Marino" },
				{ LanguageId.xog, "Sanimarino" },
				{ LanguageId.yav, "san malíno" },
				{ LanguageId.yi, "סאַן מאַרינא" },
				{ LanguageId.yo, "Sani Marino" },
				{ LanguageId.zgh, "ⵙⴰⵏⵎⴰⵔⵉⵏⵓ" },
				{ LanguageId.zh, "圣马力诺" },
				{ LanguageId.zu, "i-San Marino" },
			}
		);
	}
}
