using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SM
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "378",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "San Marino" },
				{ LanguageId.af, "San Marino" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሳን ማሪኖ" },
				{ LanguageId.ar, "سان مارينو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "San Marino" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сан-Марына" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сан Марино" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সান মারিনো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "San Marino" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "San Marino" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "San Marino" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "San Marinu" },
				{ LanguageId.cs, "San Marino" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "San Marino" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "San Marino" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σαν Μαρίνο" },
				{ LanguageId.en, "San Marino" },
				{ LanguageId.eo, "San Marino" },
				{ LanguageId.es, "San Marino" },
				{ LanguageId.et, "San Marino" },
				{ LanguageId.eu, "San Marino" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سن مارینو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "San Marino" },
				{ LanguageId.fil, "San Marino" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Saint Marin" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "San Marino" },
				{ LanguageId.ga, "San Mairíne" },
				{ LanguageId.gd, "San Marino" },
				{ LanguageId.gl, "San Mariño" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સાન મેરિનો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Marino" },
				{ LanguageId.haw, "Sana Marino" },
				{ LanguageId.he, "סן מרינו" },
				{ LanguageId.hi, "सैन मारिनो" },
				{ LanguageId.hr, "San Marino" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "San Marino" },
				{ LanguageId.hy, "Սան Մարինո" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "San Marino" },
				{ LanguageId.ig, "San Marino" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "San Marínó" },
				{ LanguageId.it, "San Marino" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サンマリノ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "San Marino" },
				{ LanguageId.ka, "სან მარინო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сан-Марино" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាន់ម៉ារីណូ" },
				{ LanguageId.kn, "ಸ್ಯಾನ್ ಮರಿನೋ" },
				{ LanguageId.ko, "산 마리노" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сан Марино" },
				{ LanguageId.la, "San Marino" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "San Marino" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊານມາຣິໂນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "San Marinas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sanmarīno" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "San Marino" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "San Marino" },
				{ LanguageId.mk, "Сан Марино" },
				{ LanguageId.ml, "സാൻ മറിനോ" },
				{ LanguageId.mn, "Сан Марино" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सॅन मारिनो" },
				{ LanguageId.ms, "San Marino" },
				{ LanguageId.mt, "San Marino" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆန်မာရီနို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "San Marino" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सान मारिनो" },
				{ LanguageId.nl, "San Marino" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସାନ୍ ମାରିନୋ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੈਨ ਮਾਰੀਨੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "San Marino" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سان مارینو" },
				{ LanguageId.pt, "São Marino" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "San Marino" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сан-Марино" },
				{ LanguageId.rw, "San Marino" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سان ميرينو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සැන් මරිනෝ" },
				{ LanguageId.sk, "San Maríno" },
				{ LanguageId.sl, "San Marino" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sani Marino" },
				{ LanguageId.so, "San Marino" },
				{ LanguageId.sq, "San Marino" },
				{ LanguageId.sr, "Сан-Марино" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "San Marino" },
				{ LanguageId.su, "San Marino" },
				{ LanguageId.sv, "San Marino" },
				{ LanguageId.sw, "San Marino" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சான் மரினோ" },
				{ LanguageId.te, "శాన్ మారినో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сан-Марино" },
				{ LanguageId.th, "ซานมารีโน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "San Marino" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "San Marino" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сан-Марино" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "San Marino" },
				{ LanguageId.uk, "Сан-Марино" },
				{ LanguageId.ur, "سان مارینو" },
				{ LanguageId.uz, "San-Marino" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "San Marino" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Sen Marino" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סאַן מאַרינאָ" },
				{ LanguageId.yo, "San Marino" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣马力诺" },
				{ LanguageId.zu, "San Marino" },
			}
		);
	}
}
