// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SS
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "211",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sydsudan" },
				{ LanguageId.af, "Suid-Soedan" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Sudan Anaafoɔ" },
				{ LanguageId.am, "ደቡብ ሱዳን" },
				{ LanguageId.ar, "جنوب السودان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "দক্ষিণ চুডান" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Sudán del Sur" },
				{ LanguageId.az, "Cənubi Sudan" },
				{ LanguageId.ba, "Көньяҡ Судан" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Паўднёвы Судан" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Южен Судан" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "দক্ষিণ সুদান" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Soudan ar Su" },
				{ LanguageId.brx, "खोला सुदान" },
				{ LanguageId.bs, "Južni Sudan" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sudan del Sud" },
				{ LanguageId.ccp, "𑄘𑄧𑄉𑄨𑄚𑄴 𑄥𑄪𑄘𑄚𑄴" },
				{ LanguageId.ce, "Къилба Судан" },
				{ LanguageId.ceb, "South Sudan" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏧᎦᎾᏮ ᏑᏕᏂ" },
				{ LanguageId.ckb, "سوودانی باشوور" },
				{ LanguageId.co, "" },
				{ LanguageId.cs, "Jižní Súdán" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "De Swdan" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Südsudan" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódpołdnjowy Sudan" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སཱའུཐ་ སུ་ཌཱན" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νότιο Σουδάν" },
				{ LanguageId.en, "South Sudan" },
				{ LanguageId.eo, "Sud-Sudano" },
				{ LanguageId.es, "Sudán del Sur" },
				{ LanguageId.et, "Lõuna-Sudaan" },
				{ LanguageId.eu, "Hego Sudan" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سودان جنوبی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Etelä-Sudan" },
				{ LanguageId.fil, "Timog Sudan" },
				{ LanguageId.fo, "Suðursudan" },
				{ LanguageId.fr, "Soudan du Sud" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sûd-Soedan" },
				{ LanguageId.ga, "an tSúdáin Theas" },
				{ LanguageId.gd, "Sudàn a Deas" },
				{ LanguageId.gl, "Sudán do Sur" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "દક્ષિણ સુદાન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Sudan ta Kudu" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "דרום סודן" },
				{ LanguageId.hi, "दक्षिण सूडान" },
				{ LanguageId.hr, "Južni Sudan" },
				{ LanguageId.hsb, "Južny Sudan" },
				{ LanguageId.hu, "Dél-Szudán" },
				{ LanguageId.hy, "Հարավային Սուդան" },
				{ LanguageId.ia, "Sudan del Sud" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sudan Selatan" },
				{ LanguageId.ig, "South Sudan" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Suður-Súdan" },
				{ LanguageId.it, "Sud Sudan" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "南スーダン" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sudan Kidul" },
				{ LanguageId.ka, "სამხრეთ სუდანი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "Sudon di Sul" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Оңтүстік Судан" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ស៊ូដង់​ខាង​ត្បូង" },
				{ LanguageId.kn, "ದಕ್ಷಿಣ ಸುಡಾನ್" },
				{ LanguageId.ko, "남수단" },
				{ LanguageId.kok, "दक्षिण सुदान" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "جنوبی سوڈان" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "Södsudahn" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түштүк Судан" },
				{ LanguageId.la, "" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Südsudan" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊູດານໃຕ້" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Pietų Sudanas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Dienvidsudāna" },
				{ LanguageId.mai, "दक्षिण सुडान" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hūtāne ki te Tonga" },
				{ LanguageId.mk, "Јужен Судан" },
				{ LanguageId.ml, "ദക്ഷിണ സുഡാൻ" },
				{ LanguageId.mn, "Өмнөд Судан" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "दक्षिण सुदान" },
				{ LanguageId.ms, "Sudan Selatan" },
				{ LanguageId.mt, "is-Sudan t’Isfel" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "တောင် ဆူဒန်" },
				{ LanguageId.mzn, "جنوبی سودان" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sør-Sudan" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "दक्षिण सुडान" },
				{ LanguageId.nl, "Zuid-Soedan" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Sør-Sudan" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߥߙߏ߬ߘߎ߮ ߛߎ߬ߘߊ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Sudaan Kibbaa" },
				{ LanguageId.or, "ଦକ୍ଷିଣ ସୁଦାନ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਦੱਖਣ ਸੁਡਾਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Saút Sudan" },
				{ LanguageId.pl, "Sudan Południowy" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سويلي سوډان" },
				{ LanguageId.pt, "Sudão do Sul" },
				{ LanguageId.qu, "Sudán del Sur" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sudan dal Sid" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sudanul de Sud" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Южный Судан" },
				{ LanguageId.rw, "" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڏکڻ سوڊان" },
				{ LanguageId.se, "Máttasudan" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "දකුණු සුඩානය" },
				{ LanguageId.sk, "Južný Sudán" },
				{ LanguageId.sl, "Južni Sudan" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Maadâ-Sudan" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "" },
				{ LanguageId.so, "Koonfur Suudaan" },
				{ LanguageId.sq, "Sudani i Jugut" },
				{ LanguageId.sr, "Јужни Судан" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "" },
				{ LanguageId.sv, "Sydsudan" },
				{ LanguageId.sw, "Sudan Kusini" },
				{ LanguageId.syr, "ܬܝܡܢ ܣܘܕܐܢ" },
				{ LanguageId.ta, "தெற்கு சூடான்" },
				{ LanguageId.te, "దక్షిణ సూడాన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Судони Ҷанубӣ" },
				{ LanguageId.th, "ซูดานใต้" },
				{ LanguageId.ti, "ደቡብ ሱዳን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günorta Sudan" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sūtani fakatonga" },
				{ LanguageId.tr, "Güney Sudan" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көньяк Судан" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "جەنۇبىي سۇدان" },
				{ LanguageId.uk, "Південний Судан" },
				{ LanguageId.ur, "جنوبی سوڈان" },
				{ LanguageId.uz, "Janubiy Sudan" },
				{ LanguageId.vai, "ꖬꕜꘋ ꗛꔤ ꔒꘋꗣ ꗏ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Nam Sudan" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Sudaŋ di Sid" },
				{ LanguageId.xh, "ESouth Sudan" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "דרום־סודאַן" },
				{ LanguageId.yo, "Gúúsù Sudan" },
				{ LanguageId.zgh, "ⵙⵙⵓⴷⴰⵏ ⵏ ⵉⴼⴼⵓⵙ" },
				{ LanguageId.zh, "南苏丹" },
				{ LanguageId.zu, "i-South Sudan" },
			}
		);
	}
}
