// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class ST
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "239",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "São Tomé og Príncipe" },
				{ LanguageId.af, "São Tomé en Príncipe" },
				{ LanguageId.agq, "Sawo Tɔ̀me à Kpèlènsikpɛ̀" },
				{ LanguageId.ak, "São Tomé ne Príncipe" },
				{ LanguageId.am, "ሳኦ ቶሜ እና ፕሪንሲፔ" },
				{ LanguageId.ar, "ساو تومي وبرينسيبي" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চাও টোমে আৰু প্ৰিনচিপে" },
				{ LanguageId.asa, "Thao Tome na Principe" },
				{ LanguageId.ast, "Santu Tomé y Príncipe" },
				{ LanguageId.az, "San-Tome və Prinsipi" },
				{ LanguageId.ba, "Сан-Томе һәм Принсипи" },
				{ LanguageId.bas, "Sào Tòme ɓɔ Prɛ̀ŋcipè" },
				{ LanguageId.be, "Сан-Тамэ і Прынсіпі" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husaotome na Huprinsipe" },
				{ LanguageId.bg, "Сао Томе и Принсипи" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Sawo Tome-ni-Prinicipe" },
				{ LanguageId.bn, "সাওটোমা ও প্রিন্সিপি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "São-Tomé-ha-Príncipe" },
				{ LanguageId.brx, "साऊ तमे आरो प्रिन्सिप" },
				{ LanguageId.bs, "Sao Tome i Principe" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "São Tomé i Príncipe" },
				{ LanguageId.ccp, "𑄥𑄃𑄮𑄑𑄟 𑄃𑄮 𑄛𑄳𑄢𑄨𑄚𑄴𑄥𑄨𑄛𑄨" },
				{ LanguageId.ce, "Сан-Томе а, Принсипи а" },
				{ LanguageId.ceb, "Sao Tome & Principe" },
				{ LanguageId.cgg, "Sawo Tome na Purinsipo" },
				{ LanguageId.chr, "ᏌᎣ ᏙᎺ ᎠᎴ ᏈᏂᏏᏇ" },
				{ LanguageId.ckb, "ساوتۆمێ و پرینسیپی" },
				{ LanguageId.co, "Sao Tome è Principe" },
				{ LanguageId.cs, "Svatý Tomáš a Princův ostrov" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "São Tomé a Príncipe" },
				{ LanguageId.dav, "Sao Tome na Principe" },
				{ LanguageId.de, "São Tomé und Príncipe" },
				{ LanguageId.dje, "Sao Tome nda Prinsipe" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "São Tomé a Príncipe" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སཝ་ ཊོ་མེ་ ཨེནཌ་ པྲྀན་སི་པེ" },
				{ LanguageId.ebu, "Sao Tome na Principe" },
				{ LanguageId.ee, "São Tomé kple Príncipe nutome" },
				{ LanguageId.el, "Σάο Τομέ και Πρίνσιπε" },
				{ LanguageId.en, "São Tomé & Príncipe" },
				{ LanguageId.eo, "Santomeo kaj Principeo" },
				{ LanguageId.es, "Santo Tomé y Príncipe" },
				{ LanguageId.et, "São Tomé ja Príncipe" },
				{ LanguageId.eu, "Sao Tome eta Principe" },
				{ LanguageId.ewo, "Saó Tomé ai Pəlinəsípe" },
				{ LanguageId.fa, "سائوتومه و پرینسیپ" },
				{ LanguageId.ff, "Sawo Tome e Perensipe" },
				{ LanguageId.fi, "São Tomé ja Príncipe" },
				{ LanguageId.fil, "São Tomé & Príncipe" },
				{ LanguageId.fo, "Sao Tome & Prinsipi" },
				{ LanguageId.fr, "Sao Tomé-et-Principe" },
				{ LanguageId.fur, "Sao Tomè e Principe" },
				{ LanguageId.fy, "Sao Tomé en Principe" },
				{ LanguageId.ga, "São Tomé agus Príncipe" },
				{ LanguageId.gd, "São Tomé agus Príncipe" },
				{ LanguageId.gl, "San Tomé e Príncipe" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Sao Tome und Prinssipe" },
				{ LanguageId.gu, "સાઓ ટૉમ અને પ્રિંસિપે" },
				{ LanguageId.guz, "Sao Tome na Principe" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Sawo Tome Da Paransip" },
				{ LanguageId.haw, "Saotome me Panikipe" },
				{ LanguageId.he, "סאו טומה ופרינסיפה" },
				{ LanguageId.hi, "साओ टोम और प्रिंसिपे" },
				{ LanguageId.hr, "Sveti Toma i Princip" },
				{ LanguageId.hsb, "São Tomé a Príncipe" },
				{ LanguageId.hu, "São Tomé és Príncipe" },
				{ LanguageId.hy, "Սան Տոմե և Փրինսիպի" },
				{ LanguageId.ia, "São Tomé e Príncipe" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sao Tome dan Principe" },
				{ LanguageId.ig, "São Tomé & Príncipe" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Saó Tóme og Prinsípe" },
				{ LanguageId.it, "São Tomé e Príncipe" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サントメ・プリンシペ" },
				{ LanguageId.jgo, "Sáwɔŋ Tɔmɛ́ nɛ́ Pɛlínsipɛ" },
				{ LanguageId.jmc, "Sao Tome na Principe" },
				{ LanguageId.jv, "Sao Tomé lan Principé" },
				{ LanguageId.ka, "სან-ტომე და პრინსიპი" },
				{ LanguageId.kab, "Saw Tumi d Pransip" },
				{ LanguageId.kam, "Sao Tome na Principe" },
				{ LanguageId.kde, "Saotome na Prinsipe" },
				{ LanguageId.kea, "San Tume i Prínsipi" },
				{ LanguageId.khq, "Sao Tome nda Prinsipe" },
				{ LanguageId.ki, "Sao Tome na Principe" },
				{ LanguageId.kk, "Сан-Томе және Принсипи" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab São Tomé and Príncipe" },
				{ LanguageId.km, "សៅតូម៉េ និង ប្រាំងស៊ីប" },
				{ LanguageId.kn, "ಸಾವೋ ಟೋಮ್ ಮತ್ತು ಪ್ರಿನ್ಸಿಪಿ" },
				{ LanguageId.ko, "상투메 프린시페" },
				{ LanguageId.kok, "सांव टोमे आनी प्रिंसिपे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ساو توم تہٕ پرنسِپی" },
				{ LanguageId.ksb, "Sao Tome na Plincipe" },
				{ LanguageId.ksf, "saotomɛ́ ri priŋsib" },
				{ LanguageId.ksh, "Zint Tommeh un Printschipe" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сан-Томе жана Принсипи" },
				{ LanguageId.la, "Velit ante" },
				{ LanguageId.lag, "Sao Tóome na Pirinsipe" },
				{ LanguageId.lb, "São Tomé a Príncipe" },
				{ LanguageId.lg, "Sanitome ne Purincipe" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sao Tomé mpé Presipɛ" },
				{ LanguageId.lo, "ເຊົາທູເມ ແລະ ພຣິນຊິບ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "San Tomė ir Prinsipė" },
				{ LanguageId.luo, "São Tomé gi Príncipe" },
				{ LanguageId.luy, "Sao Tome na Principe" },
				{ LanguageId.lv, "Santome un Prinsipi" },
				{ LanguageId.mai, "साओ टोम आ प्रिंसिप" },
				{ LanguageId.mas, "Sao Tome na Principe" },
				{ LanguageId.mer, "Sao Tome na Principe" },
				{ LanguageId.mfe, "São Tome-ek-Prínsip" },
				{ LanguageId.mg, "São Tomé-et-Príncipe" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Tomei me Pirinipei" },
				{ LanguageId.mk, "Саун Томе и Принсип" },
				{ LanguageId.ml, "സാവോ ടോമും പ്രിൻസിപെയും" },
				{ LanguageId.mn, "Сан-Томе ба Принсипи" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "साओ टोम आणि प्रिंसिपे" },
				{ LanguageId.ms, "Sao Tome dan Principe" },
				{ LanguageId.mt, "São Tomé u Príncipe" },
				{ LanguageId.mua, "Sao Tome ne Principe" },
				{ LanguageId.my, "ဆောင်တူမေးနှင့် ပရင်စီပီ" },
				{ LanguageId.mzn, "سائوتومه و پرینسیپ" },
				{ LanguageId.naq, "São Tomé and Príncipe" },
				{ LanguageId.nb, "São Tomé og Príncipe" },
				{ LanguageId.nd, "São Tomé and Príncipe" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "साओ टोमे र प्रिन्सिप" },
				{ LanguageId.nl, "Sao Tomé en Principe" },
				{ LanguageId.nmg, "Sao Tomé ba Prinship" },
				{ LanguageId.nn, "São Tomé og Príncipe" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߊߥߕߏߡߋ߫ ߣߌ߫ ߔߑߙߍ߲ߛߌߔ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Sawo Tome na Purinsipo" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Sa’oo Toomee fi Prinsippee" },
				{ LanguageId.or, "ସାଓ ଟୋମେ ଏବଂ ପ୍ରିନସିପି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਾਓ ਟੋਮ ਅਤੇ ਪ੍ਰਿੰਸੀਪੇ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sao Tómé & Prínsípẹ" },
				{ LanguageId.pl, "Wyspy Świętego Tomasza i Książęca" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ساو ټیم او پرنسیپ" },
				{ LanguageId.pt, "São Tomé e Príncipe" },
				{ LanguageId.qu, "Santo Tomé y Príncipe" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "São Tomé e Príncipe" },
				{ LanguageId.rn, "Sawotome na Perensipe" },
				{ LanguageId.ro, "São Tomé și Príncipe" },
				{ LanguageId.rof, "Sao Tome na Principe" },
				{ LanguageId.ru, "Сан-Томе и Принсипи" },
				{ LanguageId.rw, "Sao Tome na Principe" },
				{ LanguageId.rwk, "Sao Tome na Principe" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Sao Tome na Principe" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Sayo Tome ni Pilinikipe" },
				{ LanguageId.sd, "سائو ٽومي ۽ پرنسپیي" },
				{ LanguageId.se, "São Tomé ja Príncipe" },
				{ LanguageId.seh, "São Tomé e Príncipe" },
				{ LanguageId.ses, "Sao Tome nda Prinsipe" },
				{ LanguageId.sg, "Sâô Tömê na Prinsîpe" },
				{ LanguageId.shi, "ⵙⴰⵡⵟⵓⵎⵉ ⴷ ⴱⵔⴰⵏⵙⵉⴱ" },
				{ LanguageId.si, "සාඕ තෝම් සහ ප්‍රින්සිප්" },
				{ LanguageId.sk, "Svätý Tomáš a Princov ostrov" },
				{ LanguageId.sl, "Sveti Tomaž in Princ" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "São Tomé já Príncipe" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "São Tomé and Príncipe" },
				{ LanguageId.so, "Sao Tome & Birincibal" },
				{ LanguageId.sq, "Sao-Tome e Principe" },
				{ LanguageId.sr, "Сао Томе и Принципе" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sao Tome le Principe" },
				{ LanguageId.su, "Sao Tomé jeung Principe" },
				{ LanguageId.sv, "São Tomé och Príncipe" },
				{ LanguageId.sw, "Sao Tome na Principe" },
				{ LanguageId.syr, "ܣܐܘ ܛܘܡܝ ܘܦܪܝܢܣܝܦܝ" },
				{ LanguageId.ta, "சாவ் தோம் & ப்ரின்சிபி" },
				{ LanguageId.te, "సావో టోమ్ మరియు ప్రిన్సిపి" },
				{ LanguageId.teo, "Sao Tome na Principe" },
				{ LanguageId.tg, "Сан Томе ва Принсипи" },
				{ LanguageId.th, "เซาตูเมและปรินซิปี" },
				{ LanguageId.ti, "ሳኦ ቶመን ፕሪንሲፐን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "San-Tome we Prinsipi" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sao Tomē mo Pilinisipe" },
				{ LanguageId.tr, "Sao Tome ve Principe" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сан-Томе һәм Принсипи" },
				{ LanguageId.twq, "Sao Tome nda Prinsipe" },
				{ LanguageId.tzm, "Sawṭumi d Prinsip" },
				{ LanguageId.ug, "سان تومې ۋە پرىنسىپې" },
				{ LanguageId.uk, "Сан-Томе і Принсіпі" },
				{ LanguageId.ur, "ساؤ ٹومے اور پرنسپے" },
				{ LanguageId.uz, "San-Tome va Prinsipi" },
				{ LanguageId.vai, "ꕢꕴ ꕿꔈ ꗪ ꕉ ꕮꔧ ꕗꕴꔀ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "São Tomé và Príncipe" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Sao Tome na Principe" },
				{ LanguageId.wae, "São Tomé and Príncipe" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Sawo Tome ak Pirinsipe" },
				{ LanguageId.xh, "ESão Tomé & Príncipe" },
				{ LanguageId.xog, "Sanitome ni Purincipe" },
				{ LanguageId.yav, "sáwó tomé e pelensípe" },
				{ LanguageId.yi, "סאַא טאמע און פּרינסיפּע" },
				{ LanguageId.yo, "Sao tomi ati piriiṣipi" },
				{ LanguageId.zgh, "ⵙⴰⵡⵟⵓⵎⵉ ⴷ ⴱⵔⴰⵏⵙⵉⴱ" },
				{ LanguageId.zh, "圣多美和普林西比" },
				{ LanguageId.zu, "i-São Tomé kanye ne-Príncipe" },
			}
		);
	}
}
