using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class ST
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "239",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sao Tome og Principe" },
				{ LanguageId.af, "Sao Tome en Prinsipe" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሳኦ ቶሜ እና ፕሪንቺፔ" },
				{ LanguageId.ar, "سان تومي وبرينسيبي" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Sao Tome və Prinsipi" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сан-Тамэ і Прынсіпі" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сао Томе и Принсипи" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সাও টোমে এবং প্রিনসিপে" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "São Tomé ha Príncipe" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sao Tome i Principe" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Santo Tomé i Príncep" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Sao Tome ug Principe" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Sao Tome è Principe" },
				{ LanguageId.cs, "Svatý Tomáš a Princův ostrov" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sao Tome a Principe" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "São Tomé und Príncipe" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Σάο Τομέ και Πρίνσιπε" },
				{ LanguageId.en, "Sao Tome and Principe" },
				{ LanguageId.eo, "Sao Tome kaj Principe" },
				{ LanguageId.es, "Santo Tomé y Príncipe" },
				{ LanguageId.et, "São Tome ja Principe" },
				{ LanguageId.eu, "Sao Tome eta Principe" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سائوتومه و پرنسیپ" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Sao Tome ja Principe" },
				{ LanguageId.fil, "Sao Tome at Principe" },
				{ LanguageId.fo, "São Tomé og Prínsipe" },
				{ LanguageId.fr, "Sao Tomé et Principe" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sao Tomee en Prinsipe" },
				{ LanguageId.ga, "Sao Tome agus Principe" },
				{ LanguageId.gd, "Sao Tome agus Principe" },
				{ LanguageId.gl, "Santo Tomé e Príncipe" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સાઓ ટોમ અને પ્રિન્સિપે" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Sao Tome da Principe" },
				{ LanguageId.haw, "Saotome me Panikipe" },
				{ LanguageId.he, "סאו טומה ופרינסיפה" },
				{ LanguageId.hi, "साओ टोमे और प्रिंसिपे" },
				{ LanguageId.hr, "Sao Tome i Principe" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "São Tome és Príncipe" },
				{ LanguageId.hy, "Սան Տոմե և Պրինսիպ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sao Tome dan Principe" },
				{ LanguageId.ig, "Sao Tome na Principe" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Saó Tóme og Prinsípe" },
				{ LanguageId.it, "Sao Tomé e Principe" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "サントメ・プリンシペ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sao Tome lan Principe" },
				{ LanguageId.ka, "სან-ტომე და პრინსიპი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сан-Томе және Принсипи" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Sao Tome និង Principe" },
				{ LanguageId.kn, "ಸಾವೊ ಟೋಮ್ ಮತ್ತು ಪ್ರಿನ್ಸಿಪಿ" },
				{ LanguageId.ko, "상투메 프린시페" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сан-Томе жана Принсипи" },
				{ LanguageId.la, "Velit ante" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Sao Tome a Principe" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Sao Tome ແລະ Principe" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "San Tomė ir Prinsipė" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Santome un Prinsipi" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Sao Tome sy Principe" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Sao Tome me Principe" },
				{ LanguageId.mk, "Сао Томе и Принципе" },
				{ LanguageId.ml, "സാവോ ടോമും പ്രിൻസിപ്പും" },
				{ LanguageId.mn, "Сан Томе ба Принсипи" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "साओ टोम आणि प्रिंसिपे" },
				{ LanguageId.ms, "Sao Tome dan Principe" },
				{ LanguageId.mt, "Sao Tome u Principe" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Sao Tome နှင့် Principe" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sao Tome og Principe" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "साओ टोम र प्रिन्सिपे" },
				{ LanguageId.nl, "Sao Tomé en Principe" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "São Tomé og Príncipe" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସାଓ ଟୋମ୍ ଏବଂ ପ୍ରିନ୍ସିପ୍ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਾਓ ਟੋਮ ਅਤੇ ਪ੍ਰਿੰਸੀਪੇ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Świętego Tomasza i Książęca" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ساو ټوم او پرنسیپ" },
				{ LanguageId.pt, "São Tomé e Príncipe" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sao Tome și Principe" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сан-Томе и Принсипи" },
				{ LanguageId.rw, "Sao Tome na Principe" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سائو ٽوم ۽ پرنسپي" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "Sao Tome සහ Principe" },
				{ LanguageId.sk, "Svätý Tomáš a Princov ostrov" },
				{ LanguageId.sl, "Sao Tome in Principe" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sayo Tomu nePurinzipu" },
				{ LanguageId.so, "Sao Tome iyo Principe" },
				{ LanguageId.sq, "Sao Tome dhe Principe" },
				{ LanguageId.sr, "Сао Томе и Принципе" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Sao Tome le Principe" },
				{ LanguageId.su, "Sao Tomé jeung Principe" },
				{ LanguageId.sv, "Sao Tomé och Principe" },
				{ LanguageId.sw, "Sao Tome na Principe" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சாவோ டோம் மற்றும் பிரின்சிபி" },
				{ LanguageId.te, "సావో టోమ్ మరియు ప్రిన్సిపీ" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сан-Томе ва Принсипи" },
				{ LanguageId.th, "เซาตูเมและปรินซิปี" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sao Tome we Prinsip" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Sao Tome ve Principe" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сан Томе һәм Принсип" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سان توم ۋە پرىنسىپ" },
				{ LanguageId.uk, "Сан-Томе і Принсіпі" },
				{ LanguageId.ur, "ساؤ ٹوم اور پرنسپے۔" },
				{ LanguageId.uz, "San-Tome va Prinsipi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sao Tome và Principe" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Sawo Tome nePrinsipe" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סאַו טאָמע און פּרינסיפּע" },
				{ LanguageId.yo, "Sao Tome ati Principe" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣多美和普林西比" },
				{ LanguageId.zu, "Sao Tome and Principe" },
			}
		);
	}
}
