using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SV
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "503",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "El Salvador" },
				{ LanguageId.af, "El Salvador" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ኤልሳልቫዶር" },
				{ LanguageId.ar, "السلفادور" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "El Salvador" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сальвадор" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Ел Салвадор" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "এল সালভাদর" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "El Salvador" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "El Salvador" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "El Salvador" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "El Salvador" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "El Salvador" },
				{ LanguageId.cs, "El Salvador" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "El Salvador" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "El Salvador" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ελ Σαλβαδόρ" },
				{ LanguageId.en, "El Salvador" },
				{ LanguageId.eo, "Salvadoro" },
				{ LanguageId.es, "El Salvador" },
				{ LanguageId.et, "El Salvador" },
				{ LanguageId.eu, "El Salvador" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "السالوادور" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "El Salvador" },
				{ LanguageId.fil, "El Salvador" },
				{ LanguageId.fo, "El Salvador" },
				{ LanguageId.fr, "Le Salvador" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "El Salvador" },
				{ LanguageId.ga, "El Salvador" },
				{ LanguageId.gd, "El Salvador" },
				{ LanguageId.gl, "O Salvador" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "એલ સાલ્વાડોર" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "El Salvador" },
				{ LanguageId.haw, "ʻEla Salavadora" },
				{ LanguageId.he, "אל סלבדור" },
				{ LanguageId.hi, "अल साल्वाडोर" },
				{ LanguageId.hr, "El Salvador" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "El Salvador" },
				{ LanguageId.hy, "Էլ Սալվադոր" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "El Salvador" },
				{ LanguageId.ig, "El Salvador" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "El Salvador" },
				{ LanguageId.it, "El Salvador" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "エルサルバドル" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "El Salvador" },
				{ LanguageId.ka, "ელ სალვადორი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сальвадор" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "អែលសាល់វ៉ាឌ័រ" },
				{ LanguageId.kn, "ಎಲ್ ಸಾಲ್ವಡಾರ್" },
				{ LanguageId.ko, "엘살바도르" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сальвадор" },
				{ LanguageId.la, "Salvatoria" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "El Salvador" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "El Salvador" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Salvadoras" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Salvadora" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "El Salvador" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "El Salvador" },
				{ LanguageId.mk, "Ел Салвадор" },
				{ LanguageId.ml, "എൽ സാൽവഡോർ" },
				{ LanguageId.mn, "Эль Сальвадор" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "एल साल्वाडोर" },
				{ LanguageId.ms, "El Salvador" },
				{ LanguageId.mt, "El Salvador" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အယ်လ်ဆာဗေဒို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "El Salvador" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "एल साल्भाडोर" },
				{ LanguageId.nl, "El Salvador" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "El Salvador" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଏଲ ସାଲଭାଡୋର |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਅਲ ਸੈਲਵਾਡੋਰ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Salwador" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "السلوادور" },
				{ LanguageId.pt, "El Salvador" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "El Salvador" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сальвадор" },
				{ LanguageId.rw, "El Salvador" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ايل سلواڊور" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "එල් සැල්වදෝරය" },
				{ LanguageId.sk, "El Salvador" },
				{ LanguageId.sl, "El Salvador" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "E Savhadho" },
				{ LanguageId.so, "El Salvador" },
				{ LanguageId.sq, "El Salvador" },
				{ LanguageId.sr, "Ел Салвадор" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "El Salvador" },
				{ LanguageId.su, "Él Salvador" },
				{ LanguageId.sv, "El Salvador" },
				{ LanguageId.sw, "El Salvador" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "எல் சல்வடோர்" },
				{ LanguageId.te, "ఎల్ సల్వడార్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сальвадор" },
				{ LanguageId.th, "เอลซัลวาดอร์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "El Salwador" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "El Salvador" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сальвадор" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سالۋادور" },
				{ LanguageId.uk, "Сальвадор" },
				{ LanguageId.ur, "ال سلواڈور" },
				{ LanguageId.uz, "El Salvador" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "El Salvador" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "El Salvado " },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "על סאַלוואַדאָר" },
				{ LanguageId.yo, "El Salvador" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "萨尔瓦多" },
				{ LanguageId.zu, "El Salvador" },
			}
		);
	}
}
