// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SV
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "503",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "El Salvador" },
				{ LanguageId.af, "El Salvador" },
				{ LanguageId.agq, "Esàvadò" },
				{ LanguageId.ak, "Ɛl Salvadɔ" },
				{ LanguageId.am, "ኤል ሳልቫዶር" },
				{ LanguageId.ar, "السلفادور" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "এল ছেলভেড’ৰ" },
				{ LanguageId.asa, "Elsavado" },
				{ LanguageId.ast, "El Salvador" },
				{ LanguageId.az, "Salvador" },
				{ LanguageId.ba, "Сальвадор" },
				{ LanguageId.bas, "Sàlvàdɔ̂r" },
				{ LanguageId.be, "Сальвадор" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huelsavado" },
				{ LanguageId.bg, "Салвадор" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Salivadɔr" },
				{ LanguageId.bn, "এল সালভেদর" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Salvador" },
				{ LanguageId.brx, "एल साल्भाड’र" },
				{ LanguageId.bs, "Salvador" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "El Salvador" },
				{ LanguageId.ccp, "𑄆𑄣𑄴 𑄥𑄣𑄴𑄞𑄬𑄘𑄧𑄢𑄴" },
				{ LanguageId.ce, "Сальвадор" },
				{ LanguageId.ceb, "El Salvador" },
				{ LanguageId.cgg, "Eri Salivado" },
				{ LanguageId.chr, "ᎡᎵᏌᎵᏆᏙᎵ" },
				{ LanguageId.ckb, "ئێلسالڤادۆر" },
				{ LanguageId.co, "El Salvador" },
				{ LanguageId.cs, "Salvador" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "El Salvador" },
				{ LanguageId.dav, "Elsavado" },
				{ LanguageId.de, "El Salvador" },
				{ LanguageId.dje, "Salvador laboo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "El Salvador" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཨེལ་སལ་བ་ཌོར" },
				{ LanguageId.ebu, "Elsavado" },
				{ LanguageId.ee, "El Salvadɔ nutome" },
				{ LanguageId.el, "Ελ Σαλβαδόρ" },
				{ LanguageId.en, "El Salvador" },
				{ LanguageId.eo, "Salvadoro" },
				{ LanguageId.es, "El Salvador" },
				{ LanguageId.et, "El Salvador" },
				{ LanguageId.eu, "El Salvador" },
				{ LanguageId.ewo, "Saləvadór" },
				{ LanguageId.fa, "السالوادور" },
				{ LanguageId.ff, "El Salwador" },
				{ LanguageId.fi, "El Salvador" },
				{ LanguageId.fil, "El Salvador" },
				{ LanguageId.fo, "El Salvador" },
				{ LanguageId.fr, "Salvador" },
				{ LanguageId.fur, "El Salvador" },
				{ LanguageId.fy, "El Salvador" },
				{ LanguageId.ga, "An tSalvadóir" },
				{ LanguageId.gd, "An Salbhador" },
				{ LanguageId.gl, "O Salvador" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "El Salvador" },
				{ LanguageId.gu, "એલ સેલ્વાડોર" },
				{ LanguageId.guz, "Elsavado" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "El Salbador" },
				{ LanguageId.haw, "ʻEla Salavadora" },
				{ LanguageId.he, "אל סלבדור" },
				{ LanguageId.hi, "अल सल्वाडोर" },
				{ LanguageId.hr, "Salvador" },
				{ LanguageId.hsb, "El Salvador" },
				{ LanguageId.hu, "Salvador" },
				{ LanguageId.hy, "Սալվադոր" },
				{ LanguageId.ia, "El Salvador" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "El Salvador" },
				{ LanguageId.ig, "El Salvador" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "El Salvador" },
				{ LanguageId.it, "El Salvador" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "エルサルバドル" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Elsavado" },
				{ LanguageId.jv, "Èl Salvador" },
				{ LanguageId.ka, "სალვადორი" },
				{ LanguageId.kab, "Salvadur" },
				{ LanguageId.kam, "Elsavado" },
				{ LanguageId.kde, "Elsavado" },
				{ LanguageId.kea, "El Salvador" },
				{ LanguageId.khq, "Salvador laboo" },
				{ LanguageId.ki, "Elsavado" },
				{ LanguageId.kk, "Сальвадор" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab El Salvador" },
				{ LanguageId.km, "អែលសាល់វ៉ាឌ័រ" },
				{ LanguageId.kn, "ಎಲ್ ಸಾಲ್ವೇಡಾರ್" },
				{ LanguageId.ko, "엘살바도르" },
				{ LanguageId.kok, "एल साल्वाडोर" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ایل سلویڈر" },
				{ LanguageId.ksb, "Elsavado" },
				{ LanguageId.ksf, "salvadɔr" },
				{ LanguageId.ksh, "Äl Slavadohr" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Эль-Сальвадор" },
				{ LanguageId.la, "Salvatoria" },
				{ LanguageId.lag, "Elisalivado" },
				{ LanguageId.lb, "El Salvador" },
				{ LanguageId.lg, "El salivado" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Savadɔrɛ" },
				{ LanguageId.lo, "ເອວ ຊໍວາດໍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Salvadoras" },
				{ LanguageId.luo, "El Salvador" },
				{ LanguageId.luy, "Elsavado" },
				{ LanguageId.lv, "Salvadora" },
				{ LanguageId.mai, "अल सल्वाडोर" },
				{ LanguageId.mas, "Elsavado" },
				{ LanguageId.mer, "Elsavado" },
				{ LanguageId.mfe, "Salvador" },
				{ LanguageId.mg, "El Salvador" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Whakaora" },
				{ LanguageId.mk, "Ел Салвадор" },
				{ LanguageId.ml, "എൽ സാൽവദോർ" },
				{ LanguageId.mn, "Эль Сальвадор" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "अल साल्वाडोर" },
				{ LanguageId.ms, "El Salvador" },
				{ LanguageId.mt, "El Salvador" },
				{ LanguageId.mua, "Sǝr Salvador" },
				{ LanguageId.my, "အယ်လ်ဆာဗေးဒိုး" },
				{ LanguageId.mzn, "السالوادور" },
				{ LanguageId.naq, "El Salvadori" },
				{ LanguageId.nb, "El Salvador" },
				{ LanguageId.nd, "El Salvador" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "एल् साल्भाडोर" },
				{ LanguageId.nl, "El Salvador" },
				{ LanguageId.nmg, "Salvadɔr" },
				{ LanguageId.nn, "El Salvador" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߊߟߑߝ߭ߊߘߐߙ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Eri Salivado" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "El Salvaadoor" },
				{ LanguageId.or, "ଏଲ୍ ସାଲଭାଡୋର୍" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਅਲ ਸਲਵਾਡੋਰ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "El Sálvádọ" },
				{ LanguageId.pl, "Salwador" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سالوېډور" },
				{ LanguageId.pt, "El Salvador" },
				{ LanguageId.qu, "El Salvador" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "El Salvador" },
				{ LanguageId.rn, "Eli Saluvatori" },
				{ LanguageId.ro, "El Salvador" },
				{ LanguageId.rof, "Elsavado" },
				{ LanguageId.ru, "Сальвадор" },
				{ LanguageId.rw, "El Salvador" },
				{ LanguageId.rwk, "Elsavado" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Elsavado" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Elisavado" },
				{ LanguageId.sd, "ال سلواڊور" },
				{ LanguageId.se, "El Salvador" },
				{ LanguageId.seh, "El Salvador" },
				{ LanguageId.ses, "Salvador laboo" },
				{ LanguageId.sg, "Salvadöro" },
				{ LanguageId.shi, "ⵙⴰⵍⴼⴰⴷⵓⵔ" },
				{ LanguageId.si, "එල් සැල්වදෝරය" },
				{ LanguageId.sk, "Salvádor" },
				{ LanguageId.sl, "Salvador" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "El Salvador" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "El Salvador" },
				{ LanguageId.so, "El Salfadoor" },
				{ LanguageId.sq, "Salvador" },
				{ LanguageId.sr, "Салвадор" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "El Salvador" },
				{ LanguageId.su, "Él Salvador" },
				{ LanguageId.sv, "El Salvador" },
				{ LanguageId.sw, "El Salvador" },
				{ LanguageId.syr, "ܐܠ ܣܠܒܐܕܘܪ" },
				{ LanguageId.ta, "எல் சால்வடார்" },
				{ LanguageId.te, "ఎల్ సాల్వడోర్" },
				{ LanguageId.teo, "Elsavado" },
				{ LanguageId.tg, "Эл-Салвадор" },
				{ LanguageId.th, "เอลซัลวาดอร์" },
				{ LanguageId.ti, "ኤል ሳልቫዶር" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Salwador" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻEle Salavatoa" },
				{ LanguageId.tr, "El Salvador" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сальвадор" },
				{ LanguageId.twq, "Salvador laboo" },
				{ LanguageId.tzm, "Salvaḍur" },
				{ LanguageId.ug, "سالۋادور" },
				{ LanguageId.uk, "Сальвадор" },
				{ LanguageId.ur, "ال سلواڈور" },
				{ LanguageId.uz, "Salvador" },
				{ LanguageId.vai, "ꗡꗷ ꕢꔍꗍꖺ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "El Salvador" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Elsavado" },
				{ LanguageId.wae, "El Salvador" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "El Salwadoor" },
				{ LanguageId.xh, "E-El Salvador" },
				{ LanguageId.xog, "El salivado" },
				{ LanguageId.yav, "salfatɔ́ɔl" },
				{ LanguageId.yi, "על סאַלוואַדאר" },
				{ LanguageId.yo, "Ẹẹsáfádò" },
				{ LanguageId.zgh, "ⵙⴰⵍⴼⴰⴷⵓⵔ" },
				{ LanguageId.zh, "萨尔瓦多" },
				{ LanguageId.zu, "i-El Salvador" },
			}
		);
	}
}
