using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SX
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "" },
				{ LanguageId.af, "" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "" },
				{ LanguageId.ar, "سينت مارتن" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sint Maarten" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "" },
				{ LanguageId.cs, "Svatý Martin (Nizozemsko)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Sint Maarten" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "" },
				{ LanguageId.en, "Sint Maarten" },
				{ LanguageId.eo, "" },
				{ LanguageId.es, "Sint Maarten" },
				{ LanguageId.et, "Sint Maarten" },
				{ LanguageId.eu, "" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Sint Maarten" },
				{ LanguageId.fil, "" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Saint-Martin" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "" },
				{ LanguageId.ga, "" },
				{ LanguageId.gd, "" },
				{ LanguageId.gl, "" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "" },
				{ LanguageId.hi, "" },
				{ LanguageId.hr, "Sveti Martin" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Sint Maarten" },
				{ LanguageId.hy, "" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "" },
				{ LanguageId.ig, "" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "" },
				{ LanguageId.it, "Sint Maarten" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シント・マールテン" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "" },
				{ LanguageId.ka, "" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "" },
				{ LanguageId.kn, "" },
				{ LanguageId.ko, "신트마르턴" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "" },
				{ LanguageId.la, "" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "" },
				{ LanguageId.mk, "" },
				{ LanguageId.ml, "" },
				{ LanguageId.mn, "" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "" },
				{ LanguageId.ms, "" },
				{ LanguageId.mt, "" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "" },
				{ LanguageId.nl, "Sint Maarten" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Sint Maarten" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "" },
				{ LanguageId.pt, "São Martinho" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Синт-Мартен" },
				{ LanguageId.rw, "" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "" },
				{ LanguageId.sk, "Sint Maarten" },
				{ LanguageId.sl, "" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "" },
				{ LanguageId.so, "" },
				{ LanguageId.sq, "" },
				{ LanguageId.sr, "Sveti Martin" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "" },
				{ LanguageId.sv, "Sint Maarten" },
				{ LanguageId.sw, "" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "" },
				{ LanguageId.te, "" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "" },
				{ LanguageId.th, "" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Sint Maarten" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "" },
				{ LanguageId.uk, "" },
				{ LanguageId.ur, "سنٹ مارٹن" },
				{ LanguageId.uz, "" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "" },
				{ LanguageId.yo, "" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣马丁岛" },
				{ LanguageId.zu, "" },
			}
		);
	}
}
