// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SX
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sint Maarten" },
				{ LanguageId.af, "Sint Maarten" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "Sint Maaten" },
				{ LanguageId.am, "ሲንት ማርተን" },
				{ LanguageId.ar, "سانت مارتن" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চিণ্ট মাৰ্টেন" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "Sint Maarten" },
				{ LanguageId.az, "Sint-Marten" },
				{ LanguageId.ba, "Синт-Мартен" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сінт-Мартэн" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Синт Мартен" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সিন্ট মার্টেন" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sint Maarten" },
				{ LanguageId.brx, "सिन्त मार्तेन" },
				{ LanguageId.bs, "Sint Marten" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sint Maarten" },
				{ LanguageId.ccp, "𑄥𑄨𑄚𑄴𑄑𑄴 𑄟𑄢𑄴𑄑𑄬𑄚𑄴" },
				{ LanguageId.ce, "Синт-Мартен" },
				{ LanguageId.ceb, "Sint Maarten" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "ᏏᏂᏘ ᎹᏘᏂ" },
				{ LanguageId.ckb, "سینت مارتن" },
				{ LanguageId.co, "" },
				{ LanguageId.cs, "Svatý Martin (Nizozemsko)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sint Maarten" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Sint Maarten" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Sint Maarten" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སིནཊ་ མཱར་ཊེན" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Άγιος Μαρτίνος (Ολλανδικό τμήμα)" },
				{ LanguageId.en, "Sint Maarten" },
				{ LanguageId.eo, "Sint-Maarten" },
				{ LanguageId.es, "Sint Maarten" },
				{ LanguageId.et, "Sint Maarten" },
				{ LanguageId.eu, "Sint Maarten" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت مارتن" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Sint Maarten" },
				{ LanguageId.fil, "Sint Maarten" },
				{ LanguageId.fo, "Sint Maarten" },
				{ LanguageId.fr, "Saint-Martin (partie néerlandaise)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint-Maarten" },
				{ LanguageId.ga, "Sint Maarten" },
				{ LanguageId.gd, "Sint Maarten" },
				{ LanguageId.gl, "Sint Maarten" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સિંટ માર્ટેન" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Maarten" },
				{ LanguageId.haw, "" },
				{ LanguageId.he, "סנט מארטן" },
				{ LanguageId.hi, "सिंट मार्टिन" },
				{ LanguageId.hr, "Sint Maarten" },
				{ LanguageId.hsb, "Sint Maarten" },
				{ LanguageId.hu, "Sint Maarten" },
				{ LanguageId.hy, "Սինտ Մարտեն" },
				{ LanguageId.ia, "Sancte Martino nederlandese" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Sint Maarten" },
				{ LanguageId.ig, "Sint Maarten" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sint Maarten" },
				{ LanguageId.it, "Sint Maarten" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シント・マールテン" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Sint Martén" },
				{ LanguageId.ka, "სინტ-მარტენი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "San Martinhu (Olanda)" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Синт-Мартен" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សីង​ម៉ាធីន" },
				{ LanguageId.kn, "ಸಿಂಟ್ ಮಾರ್ಟೆನ್" },
				{ LanguageId.ko, "신트마르턴" },
				{ LanguageId.kok, "सांव मोर्टिन (नॅदरलँड)" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سِنٹ مارٹِن" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "Zint Maarten" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Синт-Мартен" },
				{ LanguageId.la, "" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Sint Maarten" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຊິນ ມາເທັນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sint Martenas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sintmārtena" },
				{ LanguageId.mai, "सिंट मार्टेन" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hiti Mātene" },
				{ LanguageId.mk, "Свети Мартин" },
				{ LanguageId.ml, "സിന്റ് മാർട്ടെൻ" },
				{ LanguageId.mn, "Синт Мартен" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सिंट मार्टेन" },
				{ LanguageId.ms, "Sint Maarten" },
				{ LanguageId.mt, "Sint Maarten" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "စင့်မာတင်" },
				{ LanguageId.mzn, "سنت مارتن" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sint Maarten" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सिन्ट मार्टेन" },
				{ LanguageId.nl, "Sint-Maarten" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Sint Maarten" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߡߊߙߑߕߍ߲߫ ( ߤߏߟߊ߲ߘ ߝߊ߲߭ߝߍ߬ )" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Siint Maarteen" },
				{ LanguageId.or, "ସିଣ୍ଟ ମାର୍ଟୀନ୍‌" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸਿੰਟ ਮਾਰਟੀਨ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sint Mátin" },
				{ LanguageId.pl, "Sint Maarten" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ مارټین" },
				{ LanguageId.pt, "Sint Maarten" },
				{ LanguageId.qu, "Sint Maarten" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Sint Maarten" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Sint-Maarten" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Синт-Мартен" },
				{ LanguageId.rw, "" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سنٽ مارٽن" },
				{ LanguageId.se, "Vuolleeatnamat Saint Martin" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත මාර්ටෙන්" },
				{ LanguageId.sk, "Svätý Martin (hol.)" },
				{ LanguageId.sl, "Nizozemski Sveti Martin" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Sint Maarten" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "" },
				{ LanguageId.so, "Siint Maarteen" },
				{ LanguageId.sq, "Sint-Marten" },
				{ LanguageId.sr, "Свети Мартин (Холандија)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "" },
				{ LanguageId.su, "" },
				{ LanguageId.sv, "Sint Maarten" },
				{ LanguageId.sw, "Sint Maarten" },
				{ LanguageId.syr, "ܣܢܬ ܡܐܪܬܝܢ" },
				{ LanguageId.ta, "சின்ட் மார்டென்" },
				{ LanguageId.te, "సింట్ మార్టెన్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Синт-Маартен" },
				{ LanguageId.th, "ซินต์มาร์เทน" },
				{ LanguageId.ti, "ሲንት ማርተን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sint-Marten" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Mātini (fakahōlani)" },
				{ LanguageId.tr, "Sint Maarten" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Синт-Мартен" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سىنت مارتېن" },
				{ LanguageId.uk, "Сінт-Мартен" },
				{ LanguageId.ur, "سنٹ مارٹن" },
				{ LanguageId.uz, "Sint-Marten" },
				{ LanguageId.vai, "ꔻꘋꔳ ꕮꕊꗳꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Sint Maarten" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Sin Marten" },
				{ LanguageId.xh, "ESint Maarten" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "" },
				{ LanguageId.yo, "Síntì Mátẹ́ẹ̀nì" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "荷属圣马丁" },
				{ LanguageId.zu, "i-Sint Maarten" },
			}
		);
	}
}
