// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class SY
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "963",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Syrien" },
				{ LanguageId.af, "Sirië" },
				{ LanguageId.agq, "Silîa" },
				{ LanguageId.ak, "Siria" },
				{ LanguageId.am, "ሶሪያ" },
				{ LanguageId.ar, "سوريا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "চিৰিয়া" },
				{ LanguageId.asa, "Thiria" },
				{ LanguageId.ast, "Siria" },
				{ LanguageId.az, "Suriya" },
				{ LanguageId.ba, "Сүриә" },
				{ LanguageId.bas, "Sirìà" },
				{ LanguageId.be, "Сірыя" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husilia" },
				{ LanguageId.bg, "Сирия" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Siri" },
				{ LanguageId.bn, "সিরিয়া" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Siria" },
				{ LanguageId.brx, "सीरिया" },
				{ LanguageId.bs, "Sirija" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Síria" },
				{ LanguageId.ccp, "𑄥𑄨𑄢𑄨𑄠" },
				{ LanguageId.ce, "Шема" },
				{ LanguageId.ceb, "Syria" },
				{ LanguageId.cgg, "Siriya" },
				{ LanguageId.chr, "ᏏᎵᎠ" },
				{ LanguageId.ckb, "سووریا" },
				{ LanguageId.co, "Repubblica Araba Siriana" },
				{ LanguageId.cs, "Sýrie" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Syria" },
				{ LanguageId.dav, "Siria" },
				{ LanguageId.de, "Syrien" },
				{ LanguageId.dje, "Suuria" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Syriska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སི་རི་ཡ" },
				{ LanguageId.ebu, "Siria" },
				{ LanguageId.ee, "Siria nutome" },
				{ LanguageId.el, "Συρία" },
				{ LanguageId.en, "Syria" },
				{ LanguageId.eo, "Sirio" },
				{ LanguageId.es, "Siria" },
				{ LanguageId.et, "Süüria" },
				{ LanguageId.eu, "Siria" },
				{ LanguageId.ewo, "Sirí" },
				{ LanguageId.fa, "سوریه" },
				{ LanguageId.ff, "Sirii" },
				{ LanguageId.fi, "Syyria" },
				{ LanguageId.fil, "Syria" },
				{ LanguageId.fo, "Sýria" },
				{ LanguageId.fr, "Syrie" },
				{ LanguageId.fur, "Sirie" },
				{ LanguageId.fy, "Syrië" },
				{ LanguageId.ga, "an tSiria" },
				{ LanguageId.gd, "Siridhea" },
				{ LanguageId.gl, "Siria" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Süürie" },
				{ LanguageId.gu, "સીરિયા" },
				{ LanguageId.guz, "Siria" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Sham, Siriya" },
				{ LanguageId.haw, "Lepupalika ʻAlapia Suria" },
				{ LanguageId.he, "סוריה" },
				{ LanguageId.hi, "सीरिया" },
				{ LanguageId.hr, "Sirija" },
				{ LanguageId.hsb, "Syriska" },
				{ LanguageId.hu, "Szíria" },
				{ LanguageId.hy, "Սիրիա" },
				{ LanguageId.ia, "Syria" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Suriah" },
				{ LanguageId.ig, "Syria" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sýrland" },
				{ LanguageId.it, "Siria" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シリア" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Siria" },
				{ LanguageId.jv, "Suriah" },
				{ LanguageId.ka, "სირია" },
				{ LanguageId.kab, "Surya" },
				{ LanguageId.kam, "Siria" },
				{ LanguageId.kde, "Silia" },
				{ LanguageId.kea, "Síria" },
				{ LanguageId.khq, "Suuria" },
				{ LanguageId.ki, "Siria" },
				{ LanguageId.kk, "Сирия" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Syria" },
				{ LanguageId.km, "ស៊ីរី" },
				{ LanguageId.kn, "ಸಿರಿಯಾ" },
				{ LanguageId.ko, "시리아" },
				{ LanguageId.kok, "सिरिया" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "شام" },
				{ LanguageId.ksb, "Silia" },
				{ LanguageId.ksf, "sirí" },
				{ LanguageId.ksh, "Sürije" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сирия" },
				{ LanguageId.la, "Respublica Syriaca" },
				{ LanguageId.lag, "Síria" },
				{ LanguageId.lb, "Syrien" },
				{ LanguageId.lg, "Siriya" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sirí" },
				{ LanguageId.lo, "ຊີເຣຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sirija" },
				{ LanguageId.luo, "Syria" },
				{ LanguageId.luy, "Siria" },
				{ LanguageId.lv, "Sīrija" },
				{ LanguageId.mai, "सीरिया" },
				{ LanguageId.mas, "Siria" },
				{ LanguageId.mer, "Siria" },
				{ LanguageId.mfe, "Lasiri" },
				{ LanguageId.mg, "Syria" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hiria" },
				{ LanguageId.mk, "Сирија" },
				{ LanguageId.ml, "സിറിയ" },
				{ LanguageId.mn, "Сири" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सीरिया" },
				{ LanguageId.ms, "Syria" },
				{ LanguageId.mt, "is-Sirja" },
				{ LanguageId.mua, "Syria" },
				{ LanguageId.my, "ဆီးရီးယား" },
				{ LanguageId.mzn, "سوریه" },
				{ LanguageId.naq, "Syriab" },
				{ LanguageId.nb, "Syria" },
				{ LanguageId.nd, "Syria" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सिरिया" },
				{ LanguageId.nl, "Syrië" },
				{ LanguageId.nmg, "Syria" },
				{ LanguageId.nn, "Syria" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߙߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Siriya" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Sooriyaa" },
				{ LanguageId.or, "ସିରିଆ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੀਰੀਆ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Síria" },
				{ LanguageId.pl, "Syria" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سوریه" },
				{ LanguageId.pt, "Síria" },
				{ LanguageId.qu, "Siria" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Siria" },
				{ LanguageId.rn, "Siriya" },
				{ LanguageId.ro, "Siria" },
				{ LanguageId.rof, "Siria" },
				{ LanguageId.ru, "Сирия" },
				{ LanguageId.rw, "Repubulika y'Abarabu ya Siriya" },
				{ LanguageId.rwk, "Siria" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Siria" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Siliya" },
				{ LanguageId.sd, "شام" },
				{ LanguageId.se, "Syria" },
				{ LanguageId.seh, "Síria" },
				{ LanguageId.ses, "Suuria" },
				{ LanguageId.sg, "Sirïi" },
				{ LanguageId.shi, "ⵙⵓⵔⵢⴰ" },
				{ LanguageId.si, "සිරියාව" },
				{ LanguageId.sk, "Sýria" },
				{ LanguageId.sl, "Sirija" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Syria" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Syria" },
				{ LanguageId.so, "Suuriya" },
				{ LanguageId.sq, "Siri" },
				{ LanguageId.sr, "Сирија" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Syrian Arab Republic" },
				{ LanguageId.su, "Républik Arab Siria" },
				{ LanguageId.sv, "Syrien" },
				{ LanguageId.sw, "Syria" },
				{ LanguageId.syr, "ܣܘܪܝܐ" },
				{ LanguageId.ta, "சிரியா" },
				{ LanguageId.te, "సిరియా" },
				{ LanguageId.teo, "Siria" },
				{ LanguageId.tg, "Сурия" },
				{ LanguageId.th, "ซีเรีย" },
				{ LanguageId.ti, "ሶርያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Siriýa" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sīlia" },
				{ LanguageId.tr, "Suriye" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сүрия" },
				{ LanguageId.twq, "Suuria" },
				{ LanguageId.tzm, "Surya" },
				{ LanguageId.ug, "سۇرىيە" },
				{ LanguageId.uk, "Сирія" },
				{ LanguageId.ur, "شام" },
				{ LanguageId.uz, "Suriya" },
				{ LanguageId.vai, "ꔻꕩꘋ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Syria" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Siria" },
				{ LanguageId.wae, "Sürie" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Siri" },
				{ LanguageId.xh, "ESiriya" },
				{ LanguageId.xog, "Siriya" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיריע" },
				{ LanguageId.yo, "Siria" },
				{ LanguageId.zgh, "ⵙⵓⵔⵢⴰ" },
				{ LanguageId.zh, "叙利亚" },
				{ LanguageId.zu, "i-Syria" },
			}
		);
	}
}
