using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class SY
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "963",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Den Syriske Arabiske Republik" },
				{ LanguageId.af, "Siriese Arabiese Republiek" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የሶሪያ አረብ ሪፐብሊክ" },
				{ LanguageId.ar, "الجمهورية العربية السورية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Suriya Ərəb Respublikası" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сірыйская Арабская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сирийска Арабска Република" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সিরিয় আরব প্রজাতন্ত্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Siria" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sirijska Arapska Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "República Àrab Síriana" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Syrian Arab Republic" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Repubblica Araba Siriana" },
				{ LanguageId.cs, "Syrská Arabská republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gweriniaeth Arabaidd Syria" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Syrische Arabische Republik" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Αραβική Δημοκρατία της Συρίας" },
				{ LanguageId.en, "Syrian Arab Republic" },
				{ LanguageId.eo, "Siria Araba Respubliko" },
				{ LanguageId.es, "República Árabe Siria" },
				{ LanguageId.et, "Süüria Araabia Vabariik" },
				{ LanguageId.eu, "Siriako Arabiar Errepublika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جمهوری عربی سوریه" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Syyria" },
				{ LanguageId.fil, "Syrian Arab Republic" },
				{ LanguageId.fo, "Sýria" },
				{ LanguageId.fr, "République arabe syrienne" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Syryske Arabyske Republyk" },
				{ LanguageId.ga, "Poblacht Arabach na Siria" },
				{ LanguageId.gd, "Poblachd Arabach Siria" },
				{ LanguageId.gl, "República Árabe Siria" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સીરિયન આરબ રિપબ્લિક" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jamhuriyar Larabawa Syria" },
				{ LanguageId.haw, "Lepupalika ʻAlapia Suria" },
				{ LanguageId.he, "הרפובליקה הערבית של סוריה" },
				{ LanguageId.hi, "सीरियाई अरब गणराज्य" },
				{ LanguageId.hr, "Sirijska Arapska Republika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Szíriai Arab Köztársaság" },
				{ LanguageId.hy, "Սիրիայի Արաբական Հանրապետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Republik Arab Syria" },
				{ LanguageId.ig, "Siria Arab Republic" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sýrlenska arabíska lýðveldið" },
				{ LanguageId.it, "Repubblica Araba Siriana" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "シリア・アラブ共和国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Republik Arab Suriah" },
				{ LanguageId.ka, "სირიის არაბული რესპუბლიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сирия Араб Республикасы" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សាធារណរដ្ឋអារ៉ាប់ស៊ីរី" },
				{ LanguageId.kn, "ಸಿರಿಯನ್ ಅರಬ್ ಗಣರಾಜ್ಯ" },
				{ LanguageId.ko, "시리아 아랍 공화국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сирия Араб Республикасы" },
				{ LanguageId.la, "Respublica Syriaca" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Syrien Arabesch Republik" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສາທາລະນະລັດ ອາຣັບຊີເຣຍ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sirijos Arabų Respublika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sīrijas Arābu Republika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Repoblika Arabo Syriana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hiriani Arapi Republic" },
				{ LanguageId.mk, "Сириска Арапска Република" },
				{ LanguageId.ml, "സിറിയൻ അറബ് റിപ്പബ്ലിക്" },
				{ LanguageId.mn, "Арабын Бүгд Найрамдах Сири" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सीरियन अरब प्रजासत्ताक" },
				{ LanguageId.ms, "Republik Arab Syria" },
				{ LanguageId.mt, "Repubblika Għarbija Sirjana" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဆီးရီးယား အာရပ်သမ္မတနိုင်ငံ၊" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Den syriske arabiske republikk" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सिरियाली अरब गणतन्त्र" },
				{ LanguageId.nl, "Syrische Arabische Republiek" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Syria" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସିରିଆ ଆରବ ଗଣତନ୍ତ୍ର" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੀਰੀਅਨ ਅਰਬ ਗਣਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Republika Syryjsko-Arabska" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د سوریې عربي جمهوریت" },
				{ LanguageId.pt, "República Árabe da Síria" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Republica Araba Siriana" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Сирийская Арабская Республика" },
				{ LanguageId.rw, "Repubulika y'Abarabu ya Siriya" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "شام جي عرب جمهوريه" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සිරියානු අරාබි ජනරජය" },
				{ LanguageId.sk, "Sýrska arabská republika" },
				{ LanguageId.sl, "Sirska arabska republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Syrian Arab Republic" },
				{ LanguageId.so, "Jamhuuriyadda Carabta Suuriya" },
				{ LanguageId.sq, "Republika Arabe Siriane" },
				{ LanguageId.sr, "Сиријска Арапска Република" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Syrian Arab Republic" },
				{ LanguageId.su, "Républik Arab Siria" },
				{ LanguageId.sv, "Syrien Arabrepubliken" },
				{ LanguageId.sw, "Jamhuri ya Kiarabu ya Syria" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "சிரிய அரபு குடியரசு" },
				{ LanguageId.te, "సిరియన్ అరబ్ రిపబ్లిక్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Республикаи Сурияи Араб" },
				{ LanguageId.th, "สาธารณรัฐอาหรับซีเรีย" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Siriýa Arap Respublikasy" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Suriye Arap Cumhuriyeti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сүрия Гарәп Республикасы" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "سۈرىيە ئەرەب جۇمھۇرىيىتى" },
				{ LanguageId.uk, "Сирійська Арабська Республіка" },
				{ LanguageId.ur, "شامی عرب جمہوریہ" },
				{ LanguageId.uz, "Suriya Arab Respublikasi" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Cộng Hòa Arab Syrian" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IRiphabhlikhi yaseSiriya yaseSiriya" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיריאַן אַראַבער רעפובליק" },
				{ LanguageId.yo, "Siria Arab Republic" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "阿拉伯叙利亚共和国" },
				{ LanguageId.zu, "I-Syria Arab Republic" },
			}
		);
	}
}
