// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class TC
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Turks- og Caicosøerne" },
				{ LanguageId.af, "Turks- en Caicoseilande" },
				{ LanguageId.agq, "Chwɨla n Tɨtê à Kaekùs" },
				{ LanguageId.ak, "Turks ne Caicos Islands" },
				{ LanguageId.am, "የቱርኮችና የካኢኮስ ደሴቶች" },
				{ LanguageId.ar, "جزر توركس وكايكوس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "টাৰ্কছ অৰু কেইক’ছ দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Turki na Kaiko" },
				{ LanguageId.ast, "Islles Turques y Caicos" },
				{ LanguageId.az, "Törks və Kaykos adaları" },
				{ LanguageId.ba, "Төркс һәм Кайкос утрауҙары" },
				{ LanguageId.bas, "Bìòn bi Tûrks nì Kalkòs" },
				{ LanguageId.be, "Астравы Цёркс і Кайкас" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Turki na Kaiko" },
				{ LanguageId.bg, "острови Търкс и Кайкос" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Turiki Gun ni Kayiki" },
				{ LanguageId.bn, "তুর্কস ও কাইকোস দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Turks-ha-Caicos" },
				{ LanguageId.brx, "तुर्की आरो काईक’ज द्वीपफोर" },
				{ LanguageId.bs, "Ostrva Turks i Kaikos" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Turks i Caicos" },
				{ LanguageId.ccp, "𑄖𑄪𑄢𑄴𑄇𑄧𑄌𑄴 𑄃𑄮 𑄇𑄭𑄇𑄮𑄌𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Тёркс а, Кайкос а гӀайренаш" },
				{ LanguageId.ceb, "Turks & Caicos Islands" },
				{ LanguageId.cgg, "Ebizinga bya Buturuki na Kaiko" },
				{ LanguageId.chr, "ᎠᏂᏛᎵᎩ ᎠᎴ ᎨᎢᎪ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی تورکس و کایکۆس" },
				{ LanguageId.co, "Isole Turks è Caicos" },
				{ LanguageId.cs, "Turks a Caicos" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Turks a Caicos" },
				{ LanguageId.dav, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.de, "Turks- und Caicosinseln" },
				{ LanguageId.dje, "Turk nda Kayikos Gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Turks a Caicos kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཏུརྐས྄་ ཨེནཌ་ ཀ་ཀོས་གླིང་ཚོམ" },
				{ LanguageId.ebu, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.ee, "Tɛks kple Kaikos ƒudomekpowo nutome" },
				{ LanguageId.el, "Νήσοι Τερκς και Κάικος" },
				{ LanguageId.en, "Turks & Caicos Islands" },
				{ LanguageId.eo, "Turkoj kaj Kajkoj" },
				{ LanguageId.es, "Islas Turcas y Caicos" },
				{ LanguageId.et, "Turks ja Caicos" },
				{ LanguageId.eu, "Turk eta Caico uharteak" },
				{ LanguageId.ewo, "Minlán Mí túrə́g-ai-Kaíg" },
				{ LanguageId.fa, "جزایر تورکس و کایکوس" },
				{ LanguageId.ff, "Duuɗe Turke e Keikoos" },
				{ LanguageId.fi, "Turks- ja Caicossaaret" },
				{ LanguageId.fil, "Turks & Caicos Islands" },
				{ LanguageId.fo, "Turks- og Caicosoyggjar" },
				{ LanguageId.fr, "Îles Turques-et-Caïques" },
				{ LanguageId.fur, "Isulis Turks e Caicos" },
				{ LanguageId.fy, "Turks- en Caicoseilannen" },
				{ LanguageId.ga, "Oileáin na dTurcach agus Caicos" },
				{ LanguageId.gd, "Na h-Eileanan Turcach is Caiceo" },
				{ LanguageId.gl, "Illas Turks e Caicos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Törks- und Gaiggos-Insle" },
				{ LanguageId.gu, "તુર્ક્સ અને કેકોઝ આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Turkis Da Tsibiran Kaikwas" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Turks a me Caicos" },
				{ LanguageId.he, "איי טרקס וקייקוס" },
				{ LanguageId.hi, "तुर्क और कैकोज़ द्वीपसमूह" },
				{ LanguageId.hr, "Otoci Turks i Caicos" },
				{ LanguageId.hsb, "kupy Turks a Caicos" },
				{ LanguageId.hu, "Turks- és Caicos-szigetek" },
				{ LanguageId.hy, "Թըրքս և Կայկոս կղզիներ" },
				{ LanguageId.ia, "Insulas Turcos e Caicos" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Turks dan Caicos" },
				{ LanguageId.ig, "Turks & Caicos Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Turks- og Caicoseyjar" },
				{ LanguageId.it, "Isole Turks e Caicos" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "タークス・カイコス諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.jv, "Turks lan Kapuloan Kaikos" },
				{ LanguageId.ka, "თერქს-ქაიქოსის კუნძულები" },
				{ LanguageId.kab, "Ṭurk d Tegzirin n Kaykus" },
				{ LanguageId.kam, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.kde, "Chisiwa cha Tuluchi na Kaiko" },
				{ LanguageId.kea, "Ilhas Turkas i Kaikus" },
				{ LanguageId.khq, "Turk nda Kayikos Gungey" },
				{ LanguageId.ki, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.kk, "Теркс және Кайкос аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeiyotab Turks ak Caicos" },
				{ LanguageId.km, "កោះ​ទួគ និង កៃកូស" },
				{ LanguageId.kn, "ಟರ್ಕ್ಸ್ ಮತ್ತು ಕೈಕೋಸ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "터크스 케이커스 제도" },
				{ LanguageId.kok, "तुर्क आनी कायकोस जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "تُرکس تٕہ کیکو جزیرٕ" },
				{ LanguageId.ksb, "Visiwa vya Tulki na Kaiko" },
				{ LanguageId.ksf, "zǝ tirk ri kakɔs" },
				{ LanguageId.ksh, "de Enselle Turks un Kaikos" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түркс жана Кайкос аралдары" },
				{ LanguageId.la, "Turcae et insulae Caicos" },
				{ LanguageId.lag, "Visíiwa vya Turíiki na Kaíiko" },
				{ LanguageId.lb, "Turks- a Caicosinselen" },
				{ LanguageId.lg, "Bizinga by’eTaaka ne Kayikosi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Turki mpé Kaiko" },
				{ LanguageId.lo, "ໝູ່ເກາະ ເທີກ ແລະ ໄຄໂຄສ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Terkso ir Kaikoso Salos" },
				{ LanguageId.luo, "Turks gi Caicos Islands" },
				{ LanguageId.luy, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.lv, "Tērksas un Kaikosas salas" },
				{ LanguageId.mai, "तुर्क आ कैकोज द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.mer, "Aĩrandi cia Takĩ na Kaiko" },
				{ LanguageId.mfe, "Zil Tirk ek Caïcos" },
				{ LanguageId.mg, "Nosy Turks sy Caïques" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Koru-Kākoa" },
				{ LanguageId.mk, "Острови Туркс и Каикос" },
				{ LanguageId.ml, "ടർക്ക്‌സും കെയ്‌ക്കോ ദ്വീപുകളും" },
				{ LanguageId.mn, "Турк ба Кайкосын Арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "टर्क्स आणि कैकोस बेटे" },
				{ LanguageId.ms, "Kepulauan Turks dan Caicos" },
				{ LanguageId.mt, "il-Gżejjer Turks u Caicos" },
				{ LanguageId.mua, "Turkiya ne kaicos ma laŋne" },
				{ LanguageId.my, "တခ်စ်နှင့်ကာအီကိုစ်ကျွန်းစု" },
				{ LanguageId.mzn, "تورکس و کایکوس جزایر" },
				{ LanguageId.naq, "Turks and Caicos Islands" },
				{ LanguageId.nb, "Turks- og Caicosøyene" },
				{ LanguageId.nd, "Turks and Caicos Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "तुर्क र काइकोस टापु" },
				{ LanguageId.nl, "Turks- en Caicoseilanden" },
				{ LanguageId.nmg, "Maŋ́ má Turk na Kaiko" },
				{ LanguageId.nn, "Turks- og Caicosøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߕߎߙߑߞߌ߫ ߣߌ߫ ߞߊߦߌߞ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ebizinga bya Buturuki na Kaiko" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Turkis fi Odoloota Kaayikos" },
				{ LanguageId.or, "ତୁର୍କସ୍‌ ଏବଂ କାଇକୋସ୍‌ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਟੁਰਕਸ ਅਤੇ ਕੈਕੋਸ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Tọks an Kaíkọ́s Aílands" },
				{ LanguageId.pl, "Turks i Caicos" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د ترکیې او کیکاسو ټاپو" },
				{ LanguageId.pt, "Ilhas Turcas e Caicos" },
				{ LanguageId.qu, "Islas Turcas y Caicos" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Turks e Caicos" },
				{ LanguageId.rn, "Amazinga ya Turkisi na Cayikosi" },
				{ LanguageId.ro, "Insulele Turks și Caicos" },
				{ LanguageId.rof, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.ru, "Тёркс и Кайкос" },
				{ LanguageId.rw, "Turukiya n'ibirwa bya Caicos" },
				{ LanguageId.rwk, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli fya Tuliki ni Kaiko" },
				{ LanguageId.sd, "ترڪ ۽ ڪيڪوس ٻيٽ" },
				{ LanguageId.se, "Turks ja Caicos-sullot" },
				{ LanguageId.seh, "Ilhas Turks e Caicos" },
				{ LanguageId.ses, "Turk nda Kayikos Gungey" },
				{ LanguageId.sg, "Âzûâ Turku na Kaîki" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵜⵓⵔⴽⵢⴰ ⴷ ⴽⴰⵢⴽ" },
				{ LanguageId.si, "ටර්ක්ස් සහ කයිකොස් දූපත්" },
				{ LanguageId.sk, "Turks a Caicos" },
				{ LanguageId.sl, "Otoki Turks in Caicos" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Turks- já Caicossuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveTurk neCaico" },
				{ LanguageId.so, "Turks & Kaikos Island" },
				{ LanguageId.sq, "Ishujt Turks dhe Kaikos" },
				{ LanguageId.sr, "Острва Туркс и Каикос" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Turks le Caicos" },
				{ LanguageId.su, "Kapuloan Turks jeung Caicos" },
				{ LanguageId.sv, "Turks- och Caicosöarna" },
				{ LanguageId.sw, "Visiwa vya Turks na Caicos" },
				{ LanguageId.syr, "ܓܙܝܪ̈ܐ ܕܬܘܪܟܣ ܘܟܐܝܟܘܣ" },
				{ LanguageId.ta, "டர்க்ஸ் & கைகோஸ் தீவுகள்" },
				{ LanguageId.te, "టర్క్స్ & కైకోస్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.tg, "Ҷазираҳои Теркс ва Кайкос" },
				{ LanguageId.th, "หมู่เกาะเติกส์และหมู่เกาะเคคอส" },
				{ LanguageId.ti, "ደሴታት ቱርካትን ካይኮስን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Terks we Kaýkos adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Tuki mo Kaikosi" },
				{ LanguageId.tr, "Turks ve Caicos Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Теркс һәм Кайкос утраулары" },
				{ LanguageId.twq, "Turk nda Kayikos Gungey" },
				{ LanguageId.tzm, "Tigzirin Turkiyyin d Tikaykusin" },
				{ LanguageId.ug, "تۇركس ۋە كايكوس ئاراللىرى" },
				{ LanguageId.uk, "Острови Теркс і Кайкос" },
				{ LanguageId.ur, "ٹرکس اور کیکوس جزائر" },
				{ LanguageId.uz, "Turks va Kaykos orollari" },
				{ LanguageId.vai, "ꗋꖺꕃꔻ ꗪ ꕪꔤꖏꔻ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Turks và Caicos" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Turki na Kaiko" },
				{ LanguageId.wae, "Turks- und Caicosinslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Tirk ak Kaykos" },
				{ LanguageId.xh, "ETurks & Caicos Islands" },
				{ LanguageId.xog, "Ebizinga bya Taaka ni Kayikosi" },
				{ LanguageId.yav, "túluk na káyiik" },
				{ LanguageId.yi, "טורקס און קאַיקאָס אינזלען" },
				{ LanguageId.yo, "Tọọki ati Etikun Kakọsi" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵜⵓⵔⴽⵢⴰ ⴷ ⴽⴰⵢⴽ" },
				{ LanguageId.zh, "特克斯和凯科斯群岛" },
				{ LanguageId.zu, "i-Turks ne-Caicos Islands" },
			}
		);
	}
}
