using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class TC
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Turks- og Caicosøerne" },
				{ LanguageId.af, "Turks- en Caicos-eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የቱርኮች እና የካይኮስ ደሴቶች" },
				{ LanguageId.ar, "جزر تركس وكايكوس" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Turks və Kaykos adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Астравы Тэркс і Кайкас" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "острови Търкс и Кайкос" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "টার্কস্ ও কেইকোস দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Turks ha Caicos" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ostrva Turks i Kaikos" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Turks i Caicos" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga dapit nga gitawag Turks ug Caicos Islands" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isole Turks è Caicos" },
				{ LanguageId.cs, "ostrovy Turks a Cacois" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Turks a Caicos" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Turks- und Caicosinseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νήσοι Τερκς και Κάικος" },
				{ LanguageId.en, "Turks and Caicos Islands" },
				{ LanguageId.eo, "Turkoj kaj Kajkoj" },
				{ LanguageId.es, "Islas Turcas y Caicos" },
				{ LanguageId.et, "Turksi ja Caicose saared" },
				{ LanguageId.eu, "Turks eta Caicos uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر تورکس و کایکوس" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Turks-ja Caicossaaret" },
				{ LanguageId.fil, "Mga Isla ng Turks at Caicos" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "îles Turques-et-Caïques" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Turks- en Kaikoseilannen" },
				{ LanguageId.ga, "Oileáin na dTurcach agus na Caicos" },
				{ LanguageId.gd, "Eileanan Turcaich agus Caicos" },
				{ LanguageId.gl, "Illas Turcas e Caicos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ટર્ક્સ અને કેકોસ ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Turkawa da tsibirin Caicos" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Turks a me Caicos" },
				{ LanguageId.he, "איי טורקס וקאיקוס" },
				{ LanguageId.hi, "तुर्क और कैकोस द्वीप समूह" },
				{ LanguageId.hr, "Otoci Turks i Caicos" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Turks-és Caicos-szigetek" },
				{ LanguageId.hy, "Թերքս և Կայկոս կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Turks dan Caicos" },
				{ LanguageId.ig, "Ndị Turks na Caicos Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Turks- og Caicoseyjar" },
				{ LanguageId.it, "Isole Turks e Caicos" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "タークス・カイコス諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Turks lan Caicos" },
				{ LanguageId.ka, "ტერქსისა და კაიკოსის კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Теркс және Кайкос аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Turks និង Caicos" },
				{ LanguageId.kn, "ಟರ್ಕ್ಸ್ ಮತ್ತು ಕೈಕೋಸ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "터크스 케이커스 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Теркс жана Кайкос аралдары" },
				{ LanguageId.la, "Turcae et insulae Caicos" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Tierken a Caicosinselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະ Turks ແລະ Caicos" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Terkso ir Kaikoso salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Tērksas un Kaikosas salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Turks sy Caicos" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Nga Moutere o Turks me Caicos" },
				{ LanguageId.mk, "Островите Туркс и Каикос" },
				{ LanguageId.ml, "ടർക്കുകളും കൈക്കോസ് ദ്വീപുകളും" },
				{ LanguageId.mn, "Туркс ба Кайкосын арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "तुर्क आणि कैकोस बेटे" },
				{ LanguageId.ms, "Kepulauan Turks dan Caicos" },
				{ LanguageId.mt, "Il-Gżejjer Turks u Caicos" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Turks နှင့် Caicos ကျွန်းစုများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Turks- og Caicosøyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "टर्क्स र काइकोस टापुहरू" },
				{ LanguageId.nl, "Turks- en Caicoseilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ତୁର୍କ ଏବଂ କାଇକୋସ୍ ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਤੁਰਕਸ ਅਤੇ ਕੈਕੋਸ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Turks i Caicos" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د ترکیې او کیکوس ټاپوګان" },
				{ LanguageId.pt, "Ilhas Turcas e Caicos" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Turks și Caicos" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Острова Тёркс и Кайкос" },
				{ LanguageId.rw, "Turukiya n'ibirwa bya Caicos" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ترڪ ۽ ڪيڪوس ٻيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ටර්ක්ස් සහ කයිකෝස් දූපත්" },
				{ LanguageId.sk, "Ostrovy Turks a Caicos" },
				{ LanguageId.sl, "Otoki Turks in Caicos" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Turks neCaicos Islands" },
				{ LanguageId.so, "Turki iyo Jasiiradaha Caicos" },
				{ LanguageId.sq, "Ishujt Turks dhe Kaikos" },
				{ LanguageId.sr, "Острва Туркс и Каикос" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Turks le Caicos" },
				{ LanguageId.su, "Kapuloan Turks jeung Caicos" },
				{ LanguageId.sv, "Turks- och Caicosöarna" },
				{ LanguageId.sw, "Visiwa vya Turks na Caicos" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "டர்க்ஸ் மற்றும் கைகோஸ் தீவுகள்" },
				{ LanguageId.te, "టర్క్స్ మరియు కైకోస్ దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Туркс ва Кайкос" },
				{ LanguageId.th, "หมู่เกาะเติกส์และหมู่เกาะเคคอส" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Türkler we Kaýkos adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Turks ve Caicos Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Төрекләр һәм Кайкос утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "تۈركلەر ۋە كايكوس ئارىلى" },
				{ LanguageId.uk, "Острови Теркс і Кайкос" },
				{ LanguageId.ur, "ترک اور کیکوس جزائر" },
				{ LanguageId.uz, "Turks va Kaykos orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Turks và Caicos" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseTurks kunye neCaicos" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "טורקס און קאַיקאָס אינזלען" },
				{ LanguageId.yo, "Turks ati Caicos Islands" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "特克斯和凯科斯群岛" },
				{ LanguageId.zu, "Iziqhingi zaseTurks naseCaicos" },
			}
		);
	}
}
