using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class TG
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "228",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "At gå" },
				{ LanguageId.af, "Togo" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቶጎ" },
				{ LanguageId.ar, "توجو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Getmək" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Ісці" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Да отида" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "যাও" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ići" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Anar" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Togo" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Andà" },
				{ LanguageId.cs, "Jít" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "I fynd" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Gehen" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Να πάω" },
				{ LanguageId.en, "Togo" },
				{ LanguageId.eo, "Iri" },
				{ LanguageId.es, "Ir" },
				{ LanguageId.et, "Minema" },
				{ LanguageId.eu, "Joan" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "رفتن" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Mennä" },
				{ LanguageId.fil, "Togo" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Aller" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Gean" },
				{ LanguageId.ga, "Tóga" },
				{ LanguageId.gd, "Gu bhith a’ dol" },
				{ LanguageId.gl, "Ir" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "જાઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Togo" },
				{ LanguageId.haw, "Tōkō" },
				{ LanguageId.he, "ללכת" },
				{ LanguageId.hi, "चल देना" },
				{ LanguageId.hr, "Ići" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Menni" },
				{ LanguageId.hy, "Գնալ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Untuk pergi" },
				{ LanguageId.ig, "Togo" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Að fara" },
				{ LanguageId.it, "Andare" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "持ち帰り" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Tindak ning" },
				{ LanguageId.ka, "Წასვლა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Бару" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "តូហ្គោ" },
				{ LanguageId.kn, "ಹೋಗಲು" },
				{ LanguageId.ko, "토고" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Того" },
				{ LanguageId.la, "Ire" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Togo" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໄປ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Eiti" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Iet" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Mandeha" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Togo" },
				{ LanguageId.mk, "Да оди" },
				{ LanguageId.ml, "ടോഗോ" },
				{ LanguageId.mn, "Явах" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "जाण्यासाठी" },
				{ LanguageId.ms, "Untuk pergi" },
				{ LanguageId.mt, "Biex tmur" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "သွားရန်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Å gå" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "टोगो" },
				{ LanguageId.nl, "Gaan" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଯିବା କୁ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਜਾਣਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Iść" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "توګو" },
				{ LanguageId.pt, "Ir" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "A merge" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Идти" },
				{ LanguageId.rw, "Kugenda" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "وڃڻ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "යාමට" },
				{ LanguageId.sk, "Ísť" },
				{ LanguageId.sl, "Iti" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Togo" },
				{ LanguageId.so, "Togo" },
				{ LanguageId.sq, "Togo" },
				{ LanguageId.sr, "Да иде" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Togo" },
				{ LanguageId.su, "Togo" },
				{ LanguageId.sv, "Togo" },
				{ LanguageId.sw, "Togo" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "போவதற்கு" },
				{ LanguageId.te, "వెళ్ళడానికి" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Рафтан" },
				{ LanguageId.th, "ไป" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Togo" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Gitmek" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Барырга" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "توگو" },
				{ LanguageId.uk, "Йти" },
				{ LanguageId.ur, "جانے کے لئے" },
				{ LanguageId.uz, "Bormoq" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Đi" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Thogo" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "צו גיין" },
				{ LanguageId.yo, "Lati lọ" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "多哥" },
				{ LanguageId.zu, "Ukuhamba" },
			}
		);
	}
}
