// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class TH
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "66",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Thailand" },
				{ LanguageId.af, "Thailand" },
				{ LanguageId.agq, "Taelàn" },
				{ LanguageId.ak, "Taeland" },
				{ LanguageId.am, "ታይላንድ" },
				{ LanguageId.ar, "تايلاند" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "থাইলেণ্ড" },
				{ LanguageId.asa, "Tailandi" },
				{ LanguageId.ast, "Tailandia" },
				{ LanguageId.az, "Tailand" },
				{ LanguageId.ba, "Тайланд" },
				{ LanguageId.bas, "Taylànd" },
				{ LanguageId.be, "Тайланд" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hutailandi" },
				{ LanguageId.bg, "Тайланд" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Tayilandi" },
				{ LanguageId.bn, "থাইল্যান্ড" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Thailand" },
				{ LanguageId.brx, "थाइलेण्ड" },
				{ LanguageId.bs, "Tajland" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Tailàndia" },
				{ LanguageId.ccp, "𑄗𑄭𑄣𑄳𑄠𑄚𑄴𑄓𑄴" },
				{ LanguageId.ce, "Таиланд" },
				{ LanguageId.ceb, "Thailand" },
				{ LanguageId.cgg, "Tairandi" },
				{ LanguageId.chr, "ᏔᏯᎴᏂ" },
				{ LanguageId.ckb, "تایلەند" },
				{ LanguageId.co, "Tailanda" },
				{ LanguageId.cs, "Thajsko" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Gwlad Thai" },
				{ LanguageId.dav, "Tailandi" },
				{ LanguageId.de, "Thailand" },
				{ LanguageId.dje, "Taayiland" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Thailandska" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཐཱའི་ལེནཌ" },
				{ LanguageId.ebu, "Tailandi" },
				{ LanguageId.ee, "Thailand nutome" },
				{ LanguageId.el, "Ταϊλάνδη" },
				{ LanguageId.en, "Thailand" },
				{ LanguageId.eo, "Tajlando" },
				{ LanguageId.es, "Tailandia" },
				{ LanguageId.et, "Tai" },
				{ LanguageId.eu, "Thailandia" },
				{ LanguageId.ewo, "Tailán" },
				{ LanguageId.fa, "تایلند" },
				{ LanguageId.ff, "Taylannda" },
				{ LanguageId.fi, "Thaimaa" },
				{ LanguageId.fil, "Thailand" },
				{ LanguageId.fo, "Tailand" },
				{ LanguageId.fr, "Thaïlande" },
				{ LanguageId.fur, "Tailandie" },
				{ LanguageId.fy, "Thailân" },
				{ LanguageId.ga, "an Téalainn" },
				{ LanguageId.gd, "Dùthaich nan Tàidh" },
				{ LanguageId.gl, "Tailandia" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Thailand" },
				{ LanguageId.gu, "થાઇલેંડ" },
				{ LanguageId.guz, "Tailandi" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tailan" },
				{ LanguageId.haw, "Tailani" },
				{ LanguageId.he, "תאילנד" },
				{ LanguageId.hi, "थाईलैंड" },
				{ LanguageId.hr, "Tajland" },
				{ LanguageId.hsb, "Thailandska" },
				{ LanguageId.hu, "Thaiföld" },
				{ LanguageId.hy, "Թաիլանդ" },
				{ LanguageId.ia, "Thailandia" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Thailand" },
				{ LanguageId.ig, "Thailand" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Taíland" },
				{ LanguageId.it, "Thailandia" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "タイ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Tailandi" },
				{ LanguageId.jv, "Tanah Thai" },
				{ LanguageId.ka, "ტაილანდი" },
				{ LanguageId.kab, "Ṭayland" },
				{ LanguageId.kam, "Tailandi" },
				{ LanguageId.kde, "Tailandi" },
				{ LanguageId.kea, "Tailándia" },
				{ LanguageId.khq, "Taayiland" },
				{ LanguageId.ki, "Tailandi" },
				{ LanguageId.kk, "Таиланд" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Thailand" },
				{ LanguageId.km, "ថៃ" },
				{ LanguageId.kn, "ಥೈಲ್ಯಾಂಡ್" },
				{ LanguageId.ko, "태국" },
				{ LanguageId.kok, "थायलँड" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "تھائی لینڈ" },
				{ LanguageId.ksb, "Tailandi" },
				{ LanguageId.ksf, "tɛlan" },
				{ LanguageId.ksh, "Tailand" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Тайланд" },
				{ LanguageId.la, "Thailand" },
				{ LanguageId.lag, "Táilandi" },
				{ LanguageId.lb, "Thailand" },
				{ LanguageId.lg, "Tayirandi" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Tailandɛ" },
				{ LanguageId.lo, "ໄທ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Tailandas" },
				{ LanguageId.luo, "Thailand" },
				{ LanguageId.luy, "Tailandi" },
				{ LanguageId.lv, "Taizeme" },
				{ LanguageId.mai, "थाईलैंड" },
				{ LanguageId.mas, "Tailandi" },
				{ LanguageId.mer, "Thaĩlandi" },
				{ LanguageId.mfe, "Thayland" },
				{ LanguageId.mg, "Thailandy" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Tairanga" },
				{ LanguageId.mk, "Тајланд" },
				{ LanguageId.ml, "തായ്‌ലാൻഡ്" },
				{ LanguageId.mn, "Тайланд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "थायलंड" },
				{ LanguageId.ms, "Thailand" },
				{ LanguageId.mt, "it-Tajlandja" },
				{ LanguageId.mua, "Tailand" },
				{ LanguageId.my, "ထိုင်း" },
				{ LanguageId.mzn, "تایلند" },
				{ LanguageId.naq, "Thailandi" },
				{ LanguageId.nb, "Thailand" },
				{ LanguageId.nd, "Thayilandi" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "थाइल्याण्ड" },
				{ LanguageId.nl, "Thailand" },
				{ LanguageId.nmg, "Taïland" },
				{ LanguageId.nn, "Thailand" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߕߊߦߌߘߎ߯" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Tairandi" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Taayilaand" },
				{ LanguageId.or, "ଥାଇଲ୍ୟାଣ୍ଡ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਥਾਈਲੈਂਡ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Taíland" },
				{ LanguageId.pl, "Tajlandia" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "تهايلنډ" },
				{ LanguageId.pt, "Tailândia" },
				{ LanguageId.qu, "Tailandia" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Tailanda" },
				{ LanguageId.rn, "Tayilandi" },
				{ LanguageId.ro, "Thailanda" },
				{ LanguageId.rof, "Tailandi" },
				{ LanguageId.ru, "Таиланд" },
				{ LanguageId.rw, "Tayilande" },
				{ LanguageId.rwk, "Tailandi" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Tailandi" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Tailandi" },
				{ LanguageId.sd, "ٿائيليند" },
				{ LanguageId.se, "Thaieana" },
				{ LanguageId.seh, "Tailândia" },
				{ LanguageId.ses, "Taayiland" },
				{ LanguageId.sg, "Tailânde" },
				{ LanguageId.shi, "ⵟⴰⵢⵍⴰⵏⴷ" },
				{ LanguageId.si, "තායිලන්තය" },
				{ LanguageId.sk, "Thajsko" },
				{ LanguageId.sl, "Tajska" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Thaieennâm" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Thailand" },
				{ LanguageId.so, "Taylaand" },
				{ LanguageId.sq, "Tajlandë" },
				{ LanguageId.sr, "Тајланд" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Thailand" },
				{ LanguageId.su, "Thailand" },
				{ LanguageId.sv, "Thailand" },
				{ LanguageId.sw, "Tailandi" },
				{ LanguageId.syr, "ܬܐܝܠܢܕ" },
				{ LanguageId.ta, "தாய்லாந்து" },
				{ LanguageId.te, "థాయిలాండ్" },
				{ LanguageId.teo, "Tailandi" },
				{ LanguageId.tg, "Таиланд" },
				{ LanguageId.th, "ไทย" },
				{ LanguageId.ti, "ታይላንድ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Taýland" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Tailani" },
				{ LanguageId.tr, "Tayland" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Тайланд" },
				{ LanguageId.twq, "Taayiland" },
				{ LanguageId.tzm, "Ṭaylanḍa" },
				{ LanguageId.ug, "تايلاند" },
				{ LanguageId.uk, "Таїланд" },
				{ LanguageId.ur, "تھائی لینڈ" },
				{ LanguageId.uz, "Tailand" },
				{ LanguageId.vai, "ꕚꔤ ꖨꕮꕊ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thái Lan" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Tailandi" },
				{ LanguageId.wae, "Thailand" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Taylànd" },
				{ LanguageId.xh, "EThailand" },
				{ LanguageId.xog, "Tayirandi" },
				{ LanguageId.yav, "tayiláand" },
				{ LanguageId.yi, "טיילאַנד" },
				{ LanguageId.yo, "Tailandi" },
				{ LanguageId.zgh, "ⵟⴰⵢⵍⴰⵏⴷ" },
				{ LanguageId.zh, "泰国" },
				{ LanguageId.zu, "i-Thailand" },
			}
		);
	}
}
