// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class TL
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "670",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Timor-Leste" },
				{ LanguageId.af, "Oos-Timor" },
				{ LanguageId.agq, "Ês Taemò" },
				{ LanguageId.ak, "Timɔ Boka" },
				{ LanguageId.am, "ቲሞር ሌስቴ" },
				{ LanguageId.ar, "تيمور - ليشتي" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "টিমোৰ-লেচটে" },
				{ LanguageId.asa, "Timori ya Mashariki" },
				{ LanguageId.ast, "Timor Oriental" },
				{ LanguageId.az, "Şərqi Timor" },
				{ LanguageId.ba, "Тимор-Лесте" },
				{ LanguageId.bas, "Tìmɔ̂r lìkòl" },
				{ LanguageId.be, "Тымор-Лешці" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hutimori ya Mashariki" },
				{ LanguageId.bg, "Тимор Лесте" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Kɔrɔn Timɔr" },
				{ LanguageId.bn, "তিমুর-লেস্তে" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Timor-Leste" },
				{ LanguageId.brx, "तिमर-लेस्ते" },
				{ LanguageId.bs, "Istočni Timor" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Timor-Leste" },
				{ LanguageId.ccp, "𑄖𑄨𑄟𑄪𑄢𑄴-𑄣𑄬𑄌𑄴𑄖𑄬" },
				{ LanguageId.ce, "Малхбален Тимор" },
				{ LanguageId.ceb, "Timor-Leste" },
				{ LanguageId.cgg, "Burugweizooba bwa Timori" },
				{ LanguageId.chr, "ᏘᎼᎵ-ᎴᏍᏖ" },
				{ LanguageId.ckb, "تیمۆری ڕۆژھەڵات" },
				{ LanguageId.co, "Timor Orientale" },
				{ LanguageId.cs, "Východní Timor" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Timor-Leste" },
				{ LanguageId.dav, "Timori ya Mashariki" },
				{ LanguageId.de, "Timor-Leste" },
				{ LanguageId.dje, "Timoor hawsa" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Timor-Leste" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཏི་་མོར་ལེ་ཨེསཊ" },
				{ LanguageId.ebu, "Timori ya Mashariki" },
				{ LanguageId.ee, "Timor-Leste nutome" },
				{ LanguageId.el, "Τιμόρ-Λέστε" },
				{ LanguageId.en, "Timor-Leste" },
				{ LanguageId.eo, "Orienta Timoro" },
				{ LanguageId.es, "Timor-Leste" },
				{ LanguageId.et, "Ida-Timor" },
				{ LanguageId.eu, "Ekialdeko Timor" },
				{ LanguageId.ewo, "Timôr" },
				{ LanguageId.fa, "تیمور-لسته" },
				{ LanguageId.ff, "Timoor Fuɗnaange" },
				{ LanguageId.fi, "Itä-Timor" },
				{ LanguageId.fil, "Timor-Leste" },
				{ LanguageId.fo, "Eysturtimor" },
				{ LanguageId.fr, "Timor oriental" },
				{ LanguageId.fur, "Timor orientâl" },
				{ LanguageId.fy, "East-Timor" },
				{ LanguageId.ga, "Tíomór Thoir" },
				{ LanguageId.gd, "Timor-Leste" },
				{ LanguageId.gl, "Timor Leste" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Oschttimor" },
				{ LanguageId.gu, "તિમોર-લેસ્તે" },
				{ LanguageId.guz, "Timori ya Mashariki" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Timor-Leste" },
				{ LanguageId.haw, "Timora Kahikina" },
				{ LanguageId.he, "טימור-לסטה" },
				{ LanguageId.hi, "तिमोर-लेस्त" },
				{ LanguageId.hr, "Timor-Leste" },
				{ LanguageId.hsb, "Timor-Leste" },
				{ LanguageId.hu, "Kelet-Timor" },
				{ LanguageId.hy, "Թիմոր Լեշտի" },
				{ LanguageId.ia, "Timor del Est" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Timor Leste" },
				{ LanguageId.ig, "Timor-Leste" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Tímor-Leste" },
				{ LanguageId.it, "Timor Est" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "東ティモール" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Timori ya Mashariki" },
				{ LanguageId.jv, "Timor Leste" },
				{ LanguageId.ka, "ტიმორ-ლესტე" },
				{ LanguageId.kab, "Tumur Asamar" },
				{ LanguageId.kam, "Timori ya Mashariki" },
				{ LanguageId.kde, "Timoli ya Mashaliki" },
				{ LanguageId.kea, "Timor Lesti" },
				{ LanguageId.khq, "Timoor hawsa" },
				{ LanguageId.ki, "Timori ya Mashariki" },
				{ LanguageId.kk, "Тимор-Лесте" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Timor nebo Murot tai" },
				{ LanguageId.km, "ទីម័រលេស្តេ" },
				{ LanguageId.kn, "ಟಿಮೋರ್ ಲೆಸ್ಟೆ" },
				{ LanguageId.ko, "동티모르" },
				{ LanguageId.kok, "तिमोर-लेस्ते" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "تیمور-لیسٹ" },
				{ LanguageId.ksb, "Timoli ya Mashaliki" },
				{ LanguageId.ksf, "timor anǝ á ɛst" },
				{ LanguageId.ksh, "Oß-Timor" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Тимор-Лесте" },
				{ LanguageId.la, "Timoria Orientalis" },
				{ LanguageId.lag, "Timóori yi Itʉʉmba" },
				{ LanguageId.lb, "Osttimor" },
				{ LanguageId.lg, "Timowa" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Timorɛ ya Moniɛlɛ" },
				{ LanguageId.lo, "ທິມໍ-ເລສເຕ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Rytų Timoras" },
				{ LanguageId.luo, "East Timor" },
				{ LanguageId.luy, "Timori ya Mashariki" },
				{ LanguageId.lv, "Austrumtimora" },
				{ LanguageId.mai, "तिमोर-लेस्त" },
				{ LanguageId.mas, "Timori ya Mashariki" },
				{ LanguageId.mer, "Timori ya Isti" },
				{ LanguageId.mfe, "Timor oriantal" },
				{ LanguageId.mg, "Timor Atsinanana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Tīmoa ki te Rāwhiti" },
				{ LanguageId.mk, "Тимор Лесте" },
				{ LanguageId.ml, "തിമോർ-ലെസ്റ്റെ" },
				{ LanguageId.mn, "Тимор-Лесте" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "तिमोर-लेस्ते" },
				{ LanguageId.ms, "Timor-Leste" },
				{ LanguageId.mt, "Timor Leste" },
				{ LanguageId.mua, "Timoriya" },
				{ LanguageId.my, "အရှေ့တီမော" },
				{ LanguageId.mzn, "تیمور شرقی" },
				{ LanguageId.naq, "East Timor" },
				{ LanguageId.nb, "Øst-Timor" },
				{ LanguageId.nd, "East Timor" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "टिमोर-लेस्टे" },
				{ LanguageId.nl, "Oost-Timor" },
				{ LanguageId.nmg, "Timɔr tsindikēh" },
				{ LanguageId.nn, "Aust-Timor" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߕߌߡߐߙ ߕߟߋ߬ߓߐ߬ߝߊ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Burugweizooba bwa Timori" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Tiimoor-Leestee" },
				{ LanguageId.or, "ତିମୋର୍-ଲେଷ୍ଟେ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਤਿਮੋਰ-ਲੇਸਤੇ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Íst Tímọ" },
				{ LanguageId.pl, "Timor Wschodni" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "تيمور-ليسټ" },
				{ LanguageId.pt, "Timor-Leste" },
				{ LanguageId.qu, "Timor-Leste" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Timor da l’Ost" },
				{ LanguageId.rn, "Timoru y’iburasirazuba" },
				{ LanguageId.ro, "Timor-Leste" },
				{ LanguageId.rof, "Timori ya Mashariki" },
				{ LanguageId.ru, "Восточный Тимор" },
				{ LanguageId.rw, "Iburasirazuba" },
				{ LanguageId.rwk, "Timori ya Mashariki" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Timori ya Mashariki" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Timoli ya kunena" },
				{ LanguageId.sd, "تيمور ليستي" },
				{ LanguageId.se, "Nuorta-Timor" },
				{ LanguageId.seh, "Timor Leste" },
				{ LanguageId.ses, "Timoor hawsa" },
				{ LanguageId.sg, "Timôro tî Tö" },
				{ LanguageId.shi, "ⵜⵉⵎⵓⵔ ⵏ ⵍⵇⴱⵍⵜ" },
				{ LanguageId.si, "ටිමෝර් - ලෙස්ත්" },
				{ LanguageId.sk, "Východný Timor" },
				{ LanguageId.sl, "Timor-Leste" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Timor-Leste" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "East Timor" },
				{ LanguageId.so, "Timor-Leste" },
				{ LanguageId.sq, "Timor-Leste" },
				{ LanguageId.sr, "Тимор-Лесте (Источни Тимор)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Timor Bochabela" },
				{ LanguageId.su, "Timor Wétan" },
				{ LanguageId.sv, "Östtimor" },
				{ LanguageId.sw, "Timor-Leste" },
				{ LanguageId.syr, "ܡܕܢܚ ܬܝܡܘܪ" },
				{ LanguageId.ta, "திமோர்-லெஸ்தே" },
				{ LanguageId.te, "టిమోర్-లెస్టె" },
				{ LanguageId.teo, "Timori ya Mashariki" },
				{ LanguageId.tg, "Тимор-Лесте" },
				{ LanguageId.th, "ติมอร์-เลสเต" },
				{ LanguageId.ti, "ቲሞር-ለስተ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Timor-Leste" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Timoa fakahahake" },
				{ LanguageId.tr, "Timor-Leste" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Тимор-Лесте" },
				{ LanguageId.twq, "Timoor hawsa" },
				{ LanguageId.tzm, "Timur Tagmuṭ" },
				{ LanguageId.ug, "شەرقىي تىمور" },
				{ LanguageId.uk, "Тимор-Лешті" },
				{ LanguageId.ur, "تیمور لیسٹ" },
				{ LanguageId.uz, "Timor-Leste" },
				{ LanguageId.vai, "ꔎꔒ ꗃ ꔳꗞꖻ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Timor-Leste" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Timori ya Mashariki" },
				{ LanguageId.wae, "Ošttimor" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Timor Leste" },
				{ LanguageId.xh, "ETimor-Leste" },
				{ LanguageId.xog, "Timowa" },
				{ LanguageId.yav, "timɔ́ɔl u nipálɛ́n" },
				{ LanguageId.yi, "מזרח טימאר" },
				{ LanguageId.yo, "Tímọ̀ Lẹsiti" },
				{ LanguageId.zgh, "ⵜⵉⵎⵓⵔ ⵏ ⵍⵇⴱⵍⵜ" },
				{ LanguageId.zh, "东帝汶" },
				{ LanguageId.zu, "i-Timor-Leste" },
			}
		);
	}
}
