using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class TL
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "670",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Øst Timor" },
				{ LanguageId.af, "Oos Timor" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ምስራቅ ቲሞር" },
				{ LanguageId.ar, "تيمور الشرقية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Şərqi Timor" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Усходні Тымор" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Източен Тимор" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "পূর্ব তিমুর" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Timor ar Reter" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Istočni Timor" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Timor Oriental" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "East Timor" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Timor Orientale" },
				{ LanguageId.cs, "Východní Timor" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Dwyrain Timor" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Osttimor" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ανατολικό Τιμόρ" },
				{ LanguageId.en, "East Timor" },
				{ LanguageId.eo, "Orienta Timoro" },
				{ LanguageId.es, "Timor Oriental" },
				{ LanguageId.et, "Ida-Timor" },
				{ LanguageId.eu, "Ekialdeko Timor" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "تیمور شرقی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Itä-Timor" },
				{ LanguageId.fil, "Silangang Timor" },
				{ LanguageId.fo, "Eysturtimor" },
				{ LanguageId.fr, "Timor oriental" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "East-Timor" },
				{ LanguageId.ga, "Tíomór Thoir" },
				{ LanguageId.gd, "Timor an Ear" },
				{ LanguageId.gl, "Timor Oriental" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "પૂર્વ તિમોર" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Gabashin Timor" },
				{ LanguageId.haw, "Timora Kahikina" },
				{ LanguageId.he, "מזרח טימור" },
				{ LanguageId.hi, "ईस्ट तिमोर" },
				{ LanguageId.hr, "Istočni Timor" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Kelet-Timor" },
				{ LanguageId.hy, "Արևելյան Թիմոր" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Timor Timur" },
				{ LanguageId.ig, "East Timor" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Austur-Tímor" },
				{ LanguageId.it, "Timor Est" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "東ティモール" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Timor Timur" },
				{ LanguageId.ka, "აღმოსავლეთ ტიმორი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Шығыс Тимор" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ទីម័រខាងកើត" },
				{ LanguageId.kn, "ಪೂರ್ವ ಟಿಮೋರ್" },
				{ LanguageId.ko, "동 티모르" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Батыш Тимор" },
				{ LanguageId.la, "Timoria Orientalis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Osttimor" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຕີມໍຕາເວັນອອກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Rytų Timoras" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Austrumtimora" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Timor Atsinanana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Timor Rawhiti" },
				{ LanguageId.mk, "Источен Тимор" },
				{ LanguageId.ml, "കിഴക്കൻ തിമോർ" },
				{ LanguageId.mn, "Зүүн Тимор" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "पूर्व तिमोर" },
				{ LanguageId.ms, "Timor Timur" },
				{ LanguageId.mt, "Timor tal-Lvant" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "အရှေ့တီမော" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Øst-Timor" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "पूर्वी टिमोर" },
				{ LanguageId.nl, "Oost Timor" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Aust-Timor" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ପୂର୍ବ ତିମୋର |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਪੂਰਬੀ ਤਿਮੋਰ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wschodni Timor" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ختیځ تیمور" },
				{ LanguageId.pt, "Timor Leste" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Timorul de Est" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Восточный Тимор" },
				{ LanguageId.rw, "Iburasirazuba" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "مشرقي تيمور" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "නැගෙනහිර ටිමෝරය" },
				{ LanguageId.sk, "Východný Timor" },
				{ LanguageId.sl, "Vzhodni Timor" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Mabvazuva Timo" },
				{ LanguageId.so, "Bariga Timor" },
				{ LanguageId.sq, "Timori Lindor" },
				{ LanguageId.sr, "Источни Тимор" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Timor Bochabela" },
				{ LanguageId.su, "Timor Wétan" },
				{ LanguageId.sv, "Östtimor" },
				{ LanguageId.sw, "Timor ya Mashariki" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "கிழக்கு திமோர்" },
				{ LanguageId.te, "తూర్పు తైమూర్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Тимори Шарқӣ" },
				{ LanguageId.th, "ติมอร์ตะวันออก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Gündogar Timor" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Doğu Timor" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көнчыгыш Тимор" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "East Timor" },
				{ LanguageId.uk, "Східний Тимор" },
				{ LanguageId.ur, "مشرقی تیمور" },
				{ LanguageId.uz, "Sharqiy Timor" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Đông Timor" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "iThimo eseMpuma" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "מזרח טימאָר" },
				{ LanguageId.yo, "East Timor" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "东帝汶" },
				{ LanguageId.zu, "I-East Timor" },
			}
		);
	}
}
