// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class TT
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Trinidad og Tobago" },
				{ LanguageId.af, "Trinidad en Tobago" },
				{ LanguageId.agq, "Tèlenedà à Tòbagù" },
				{ LanguageId.ak, "Trinidad ne Tobago" },
				{ LanguageId.am, "ትሪናዳድ እና ቶቤጎ" },
				{ LanguageId.ar, "ترينيداد وتوباغو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ট্ৰিনিডাড আৰু টোবাগো" },
				{ LanguageId.asa, "Trinidad na Tobago" },
				{ LanguageId.ast, "Trinidá y Tobagu" },
				{ LanguageId.az, "Trinidad və Tobaqo" },
				{ LanguageId.ba, "Тринидад һәм Тобаго" },
				{ LanguageId.bas, "Trìnidàd ɓɔ Tòbagò" },
				{ LanguageId.be, "Трынідад і Табага" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Hutrinad na Hutobago" },
				{ LanguageId.bg, "Тринидад и Тобаго" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Trinite-ni-Tobago" },
				{ LanguageId.bn, "ত্রিনিদাদ ও টোবাগো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Trinidad-ha-Tobago" },
				{ LanguageId.brx, "त्रिनिडाड आरो तबेग’" },
				{ LanguageId.bs, "Trinidad i Tobago" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Trinidad i Tobago" },
				{ LanguageId.ccp, "𑄖𑄳𑄢𑄨𑄚𑄨𑄚𑄘𑄴 𑄃𑄮 𑄑𑄮𑄝𑄳𑄠𑄉𑄮" },
				{ LanguageId.ce, "Тринидад а, Тобаго а" },
				{ LanguageId.ceb, "Trinidad & Tobago" },
				{ LanguageId.cgg, "Turinidad na Tobago" },
				{ LanguageId.chr, "ᏟᏂᏕᏗ ᎠᎴ ᏙᏆᎪ" },
				{ LanguageId.ckb, "ترینیداد و تۆباگو" },
				{ LanguageId.co, "Trinidad è Tobago" },
				{ LanguageId.cs, "Trinidad a Tobago" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Trinidad a Tobago" },
				{ LanguageId.dav, "Trinidad na Tobago" },
				{ LanguageId.de, "Trinidad und Tobago" },
				{ LanguageId.dje, "Trinidad nda Tobaago" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Trinidad a Tobago" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཊི་ནི་ཌཱཌ་ ཨེནཌ་ ཊོ་བྷེ་གྷོ" },
				{ LanguageId.ebu, "Trinidad na Tobago" },
				{ LanguageId.ee, "Trinidad kple Tobago nutome" },
				{ LanguageId.el, "Τρινιντάντ και Τομπάγκο" },
				{ LanguageId.en, "Trinidad & Tobago" },
				{ LanguageId.eo, "Trinidado kaj Tobago" },
				{ LanguageId.es, "Trinidad y Tobago" },
				{ LanguageId.et, "Trinidad ja Tobago" },
				{ LanguageId.eu, "Trinidad eta Tobago" },
				{ LanguageId.ewo, "Təlinité-ai-Tobágo" },
				{ LanguageId.fa, "ترینیداد و توباگو" },
				{ LanguageId.ff, "Tirnidaad e Tobaago" },
				{ LanguageId.fi, "Trinidad ja Tobago" },
				{ LanguageId.fil, "Trinidad & Tobago" },
				{ LanguageId.fo, "Trinidad & Tobago" },
				{ LanguageId.fr, "Trinité-et-Tobago" },
				{ LanguageId.fur, "Trinidad e Tobago" },
				{ LanguageId.fy, "Trinidad en Tobago" },
				{ LanguageId.ga, "Oileán na Tríonóide agus Tobága" },
				{ LanguageId.gd, "Trianaid agus Tobago" },
				{ LanguageId.gl, "Trinidad e Tobago" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Trinidad und Tobaago" },
				{ LanguageId.gu, "ટ્રિનીદાદ અને ટોબેગો" },
				{ LanguageId.guz, "Trinidad na Tobago" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tirinidad Da Tobago" },
				{ LanguageId.haw, "Tirinipapa me Topako" },
				{ LanguageId.he, "טרינידד וטובגו" },
				{ LanguageId.hi, "त्रिनिदाद और टोबैगो" },
				{ LanguageId.hr, "Trinidad i Tobago" },
				{ LanguageId.hsb, "Trinidad a Tobago" },
				{ LanguageId.hu, "Trinidad és Tobago" },
				{ LanguageId.hy, "Տրինիդադ և Տոբագո" },
				{ LanguageId.ia, "Trinidad e Tobago" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Trinidad dan Tobago" },
				{ LanguageId.ig, "Trinidad na Tobago" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Trínidad og Tóbagó" },
				{ LanguageId.it, "Trinidad e Tobago" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "トリニダード・トバゴ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Trinidad na Tobago" },
				{ LanguageId.jv, "Trinidad lan Tobago" },
				{ LanguageId.ka, "ტრინიდადი და ტობაგო" },
				{ LanguageId.kab, "Ṭrindad d Ṭubagu" },
				{ LanguageId.kam, "Trinidad na Tobago" },
				{ LanguageId.kde, "Tilinidad na Tobago" },
				{ LanguageId.kea, "Trinidad i Tobagu" },
				{ LanguageId.khq, "Trinidad nda Tobaago" },
				{ LanguageId.ki, "Trinidad na Tobago" },
				{ LanguageId.kk, "Тринидад және Тобаго" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Trinidad ak Tobago" },
				{ LanguageId.km, "ទ្រីនីដាត និង​តូបាហ្គោ" },
				{ LanguageId.kn, "ಟ್ರಿನಿಡಾಡ್ ಮತ್ತು ಟೊಬಾಗೊ" },
				{ LanguageId.ko, "트리니다드 토바고" },
				{ LanguageId.kok, "त्रिनदाड आनी तोबाग" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ٹرنِنداد تہٕ ٹوبیگو" },
				{ LanguageId.ksb, "Tlinidad na Tobago" },
				{ LanguageId.ksf, "tɛrinitɛ ri tobago" },
				{ LanguageId.ksh, "Trinidad un Tobähjo" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Тринидад жана Тобаго" },
				{ LanguageId.la, "Trinitas et Tabacum" },
				{ LanguageId.lag, "Tiriníida ya Tobáago" },
				{ LanguageId.lb, "Trinidad an Tobago" },
				{ LanguageId.lg, "Turindaadi ne Tobago" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Tinidadɛ mpé Tobago" },
				{ LanguageId.lo, "ທຣິນິແດດ ແລະ ໂທແບໂກ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Trinidadas ir Tobagas" },
				{ LanguageId.luo, "Trinidad gi Tobago" },
				{ LanguageId.luy, "Trinidad na Tobago" },
				{ LanguageId.lv, "Trinidāda un Tobāgo" },
				{ LanguageId.mai, "ट्रिनिदाद आ टोबैगो" },
				{ LanguageId.mas, "Trinidad na Tobago" },
				{ LanguageId.mer, "Trinidad na Tobago" },
				{ LanguageId.mfe, "Trinite-ek-Tobago" },
				{ LanguageId.mg, "Trinidad sy Tobagô" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Tirinaki Tōpako" },
				{ LanguageId.mk, "Тринидад и Тобаго" },
				{ LanguageId.ml, "ട്രിനിഡാഡും ടുബാഗോയും" },
				{ LanguageId.mn, "Тринидад ба Тобаго" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "त्रिनिदाद आणि टोबॅगो" },
				{ LanguageId.ms, "Trinidad dan Tobago" },
				{ LanguageId.mt, "Trinidad u Tobago" },
				{ LanguageId.mua, "Trinite ne Tobago" },
				{ LanguageId.my, "ထရီနီဒတ်နှင့် တိုဘက်ဂို" },
				{ LanguageId.mzn, "ترینیداد و توباگو" },
				{ LanguageId.naq, "Trinidad and Tobago" },
				{ LanguageId.nb, "Trinidad og Tobago" },
				{ LanguageId.nd, "Trinidad le Tobago" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "त्रिनिडाड एण्ड टोबागो" },
				{ LanguageId.nl, "Trinidad en Tobago" },
				{ LanguageId.nmg, "Trinidad ba Tobágó" },
				{ LanguageId.nn, "Trinidad og Tobago" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߕߙߌߣߌߕߋ߫ ߣߌ߫ ߕߏߓߊߜ߭ߏ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Turinidad na Tobago" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Tirinidan fi Tobaagoo" },
				{ LanguageId.or, "ତ୍ରିନିଦାଦ୍ ଏବଂ ଟୋବାଗୋ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਟ੍ਰਿਨੀਡਾਡ ਅਤੇ ਟੋਬਾਗੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Trínídad & Tobágo" },
				{ LanguageId.pl, "Trynidad i Tobago" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ټرينيډاډ او ټوباګو" },
				{ LanguageId.pt, "Trinidad e Tobago" },
				{ LanguageId.qu, "Trinidad y Tobago" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Trinidad e Tobago" },
				{ LanguageId.rn, "Tirinidadi na Tobago" },
				{ LanguageId.ro, "Trinidad și Tobago" },
				{ LanguageId.rof, "Trinidad na Tobago" },
				{ LanguageId.ru, "Тринидад и Тобаго" },
				{ LanguageId.rw, "Trinidad na Tobago" },
				{ LanguageId.rwk, "Trinidad na Tobago" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Trinidad na Tobago" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Tilinidadi ni Tobago" },
				{ LanguageId.sd, "ٽرينيڊاڊ ۽ ٽوباگو" },
				{ LanguageId.se, "Trinidad ja Tobago" },
				{ LanguageId.seh, "Trinidad e Tobago" },
				{ LanguageId.ses, "Trinidad nda Tobaago" },
				{ LanguageId.sg, "Trinitùee na Tobagö" },
				{ LanguageId.shi, "ⵜⵔⵉⵏⵉⴷⴰⴷ ⴷ ⵟⵓⴱⴰⴳⵓ" },
				{ LanguageId.si, "ට්‍රිනිඩෑඩ් සහ ටොබැගෝ" },
				{ LanguageId.sk, "Trinidad a Tobago" },
				{ LanguageId.sl, "Trinidad in Tobago" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Trinidad já Tobago" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Trinidad and Tobago" },
				{ LanguageId.so, "Tirinidaad & Tobago" },
				{ LanguageId.sq, "Trinidad e Tobago" },
				{ LanguageId.sr, "Тринидад и Тобаго" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Trinidad le Tobago" },
				{ LanguageId.su, "Trinidad jeung Tobago" },
				{ LanguageId.sv, "Trinidad och Tobago" },
				{ LanguageId.sw, "Trinidad na Tobago" },
				{ LanguageId.syr, "ܬܪܝܢܝܕܐܕ ܘܬܘܒܐܓܘ" },
				{ LanguageId.ta, "டிரினிடாட் & டொபாகோ" },
				{ LanguageId.te, "ట్రినిడాడ్ మరియు టొబాగో" },
				{ LanguageId.teo, "Trinidad na Tobago" },
				{ LanguageId.tg, "Тринидад ва Тобаго" },
				{ LanguageId.th, "ตรินิแดดและโตเบโก" },
				{ LanguageId.ti, "ትሪኒዳድን ቶባጎን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Trinidad we Tobago" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Tilinitati mo Topako" },
				{ LanguageId.tr, "Trinidad ve Tobago" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Тринидад һәм Тобаго" },
				{ LanguageId.twq, "Trinidad nda Tobaago" },
				{ LanguageId.tzm, "Trinidad d Ṭubagu" },
				{ LanguageId.ug, "تىرىنىداد ۋە توباگو" },
				{ LanguageId.uk, "Тринідад і Тобаго" },
				{ LanguageId.ur, "ترینیداد اور ٹوباگو" },
				{ LanguageId.uz, "Trinidad va Tobago" },
				{ LanguageId.vai, "ꖤꔸꔕꕜ ꗪ ꕿꔆꖑ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Trinidad và Tobago" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Trinidad na Tobago" },
				{ LanguageId.wae, "Trinidad und Tobago" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Tirinite ak Tobago" },
				{ LanguageId.xh, "ETrinidad & Tobago" },
				{ LanguageId.xog, "Turindaadi ni Tobago" },
				{ LanguageId.yav, "tilinitáat na tupákɔ" },
				{ LanguageId.yi, "טרינידאַד און טאבאַגא" },
				{ LanguageId.yo, "Tirinida ati Tobaga" },
				{ LanguageId.zgh, "ⵜⵔⵉⵏⵉⴷⴰⴷ ⴷ ⵟⵓⴱⴰⴳⵓ" },
				{ LanguageId.zh, "特立尼达和多巴哥" },
				{ LanguageId.zu, "i-Trinidad ne-Tobago" },
			}
		);
	}
}
