using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class TT
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Trinidad og Tobago" },
				{ LanguageId.af, "Trinidad en Tobago" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ትሪኒዳድ እና ቶባጎ" },
				{ LanguageId.ar, "ترينداد وتوباغو" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Trinidad və Tobaqo" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Трынідад і Табага" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Тринидад и Тобаго" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ত্রিনিদাদ ও টোবাগো" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Trinidad ha Tobago" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Trinidad i Tobago" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Trinitat i Tobago" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Trinidad ug Tobago" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Trinidad è Tobago" },
				{ LanguageId.cs, "Trinidad a Tobago" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Trinidad a Tobago" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Trinidad und Tobago" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Τρινιντάντ και Τομπάγκο" },
				{ LanguageId.en, "Trinidad and Tobago" },
				{ LanguageId.eo, "Trinidado kaj Tobago" },
				{ LanguageId.es, "Trinidad y Tobago" },
				{ LanguageId.et, "Trinidad ja Tobago" },
				{ LanguageId.eu, "Trinidad eta Tobago" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "ترینیداد و توباگو" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Trinidad ja Tobago" },
				{ LanguageId.fil, "Trinidad at Tobago" },
				{ LanguageId.fo, "Trinidad og Tobago" },
				{ LanguageId.fr, "Trinité-et-Tobago" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Trinidad en Tobago" },
				{ LanguageId.ga, "Oileán na Tríonóide agus Tobága" },
				{ LanguageId.gd, "Trinidad is Tobago" },
				{ LanguageId.gl, "Trindade e Tobago" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ત્રિનિદાદ અને ટોબેગો" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Trinidad da Tobago" },
				{ LanguageId.haw, "Tirinipapa me Topako" },
				{ LanguageId.he, "טרינידד וטובגו" },
				{ LanguageId.hi, "त्रिनिदाद और टोबैगो" },
				{ LanguageId.hr, "Trinidad i Tobago" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Trinidad és Tobago" },
				{ LanguageId.hy, "Տրինիդադ և Տոբագո" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Trinidad dan Tobago" },
				{ LanguageId.ig, "Trinidad na Tobago" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Trínidad og Tóbagó" },
				{ LanguageId.it, "Trinidad e Tobago" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "トリニダード・トバゴ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Trinidad lan Tobago" },
				{ LanguageId.ka, "ტრინიდადი და ტობაგო" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Тринидад және Тобаго" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "ទ្រី​នី​ដា​ដ​និង​តូបាហ្គោ" },
				{ LanguageId.kn, "ಟ್ರಿನಿಡಾಡ್ ಮತ್ತು ಟೊಬಾಗೊ" },
				{ LanguageId.ko, "트리니다드 토바고" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Тринидад жана Тобаго" },
				{ LanguageId.la, "Trinitas et Tabacum" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Tinidad an Tobago" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Trinidad ແລະ Tobago" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Trinidadas ir Tobagas" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Trinidada un Tobāgo" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Trinidad sy Tobago" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Trinidad me Tobago" },
				{ LanguageId.mk, "Тринидад и Тобаго" },
				{ LanguageId.ml, "ട്രിനിഡാഡ് ആൻഡ് ടൊബാഗോ" },
				{ LanguageId.mn, "Тринидад Тобаго" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "त्रिनिदाद आणि टोबॅगो" },
				{ LanguageId.ms, "Trinidad dan Tobago" },
				{ LanguageId.mt, "Trinidad u Tobago" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ထရီနီဒက်နှင့်တိုဘာဂို" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Trinidad og Tobago" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "ट्रिनिडाड र टोबागो" },
				{ LanguageId.nl, "Trinidad en Tobago" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Trinidad og Tobago" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ତ୍ରିନିଦାଦ ଏବଂ ଟୋବାଗୋ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਤ੍ਰਿਨੀਦਾਦ ਅਤੇ ਟੋਬੈਗੋ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Trynidad i Tobago" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ترینیداد او توباګو" },
				{ LanguageId.pt, "Trinidad e Tobago" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Trinidad și Tobago" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Тринидад и Тобаго" },
				{ LanguageId.rw, "Trinidad na Tobago" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ٽرينڊڊ ۽ ٽوباگو" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ට්රිනිඩෑඩ් සහ ටොබැගෝ" },
				{ LanguageId.sk, "Trinidad a Tobago" },
				{ LanguageId.sl, "Trinidad in Tobago" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Trinidhadhi neTobhago" },
				{ LanguageId.so, "Trinidad iyo Tobago" },
				{ LanguageId.sq, "Trinidad dhe Tobago" },
				{ LanguageId.sr, "Тринидад и Тобаго" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Trinidad le Tobago" },
				{ LanguageId.su, "Trinidad jeung Tobago" },
				{ LanguageId.sv, "Trinidad och Tobago" },
				{ LanguageId.sw, "Trinidad na Tobago" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "டிரினிடாட் மற்றும் டொபாகோ" },
				{ LanguageId.te, "ట్రినిడాడ్ మరియు టొబాగో" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Тринидад ва Тобаго" },
				{ LanguageId.th, "ตรินิแดดและโตเบโก" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Trinidad we Tobago" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Trinidad ve Tobago" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Тринидад һәм Тобаго" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "تىرىنىداد ۋە توباگو" },
				{ LanguageId.uk, "Тринідад і Тобаго" },
				{ LanguageId.ur, "ٹرینیڈاڈ اور ٹوباگو" },
				{ LanguageId.uz, "Trinidad va Tobago" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Trinidad và Tobago" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Thrinidadi neThubhago" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "טרינידאַד און טאָבאַגאָ" },
				{ LanguageId.yo, "Trinidad ati Tobago" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "特立尼达和多巴哥" },
				{ LanguageId.zu, "I-Trinidad ne-Tobago" },
			}
		);
	}
}
