// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class US
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "USA" },
				{ LanguageId.af, "Verenigde State van Amerika" },
				{ LanguageId.agq, "USA" },
				{ LanguageId.ak, "Amɛrika" },
				{ LanguageId.am, "ዩናይትድ ስቴትስ" },
				{ LanguageId.ar, "الولايات المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "মাৰ্কিন যুক্তৰাষ্ট্ৰ" },
				{ LanguageId.asa, "Marekani" },
				{ LanguageId.ast, "Estaos Xuníos" },
				{ LanguageId.az, "Amerika Birləşmiş Ştatları" },
				{ LanguageId.ba, "Америка Ҡушма Штаттары" },
				{ LanguageId.bas, "Àdnà i Bilɔ̀ŋ bi Amerkà" },
				{ LanguageId.be, "Злучаныя Штаты Амерыкі" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Humalekani" },
				{ LanguageId.bg, "Съединени щати" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Ameriki" },
				{ LanguageId.bn, "মার্কিন যুক্তরাষ্ট্র" },
				{ LanguageId.bo, "ཨ་མེ་རི་ཀ།" },
				{ LanguageId.br, "Stadoù-Unanet" },
				{ LanguageId.brx, "जथाय हादोर आमेरिका" },
				{ LanguageId.bs, "Sjedinjene Države" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Estats Units" },
				{ LanguageId.ccp, "𑄟𑄢𑄴𑄇𑄨𑄚𑄴 𑄎𑄧𑄙𑄢𑄬𑄌𑄴𑄎𑄮" },
				{ LanguageId.ce, "Цхьанатоьхна Штаташ" },
				{ LanguageId.ceb, "United States" },
				{ LanguageId.cgg, "Amerika" },
				{ LanguageId.chr, "ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᏍᎦᏚᎩ" },
				{ LanguageId.ckb, "ویلایەتە یەکگرتووەکان" },
				{ LanguageId.co, "Stati Uniti" },
				{ LanguageId.cs, "Spojené státy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Yr Unol Daleithiau" },
				{ LanguageId.dav, "Marekani" },
				{ LanguageId.de, "Vereinigte Staaten" },
				{ LanguageId.dje, "Ameriki Laabu Margantey" },
				{ LanguageId.doi, "यूएस" },
				{ LanguageId.dsb, "Zjadnośone staty Ameriki" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཡུ་ཨེས་ཨེ" },
				{ LanguageId.ebu, "Marekani" },
				{ LanguageId.ee, "USA nutome" },
				{ LanguageId.el, "Ηνωμένες Πολιτείες" },
				{ LanguageId.en, "United States" },
				{ LanguageId.eo, "Usono" },
				{ LanguageId.es, "Estados Unidos" },
				{ LanguageId.et, "Ameerika Ühendriigid" },
				{ LanguageId.eu, "Ameriketako Estatu Batuak" },
				{ LanguageId.ewo, "Ǹnam Amɛrəkə" },
				{ LanguageId.fa, "ایالات متحده" },
				{ LanguageId.ff, "Dowlaaji Dentuɗi Amerik" },
				{ LanguageId.fi, "Yhdysvallat" },
				{ LanguageId.fil, "Estados Unidos" },
				{ LanguageId.fo, "Sambandsríki Amerika" },
				{ LanguageId.fr, "États-Unis" },
				{ LanguageId.fur, "Stâts Unîts" },
				{ LanguageId.fy, "Ferienigde Staten" },
				{ LanguageId.ga, "Stáit Aontaithe Mheiriceá" },
				{ LanguageId.gd, "Na Stàitean Aonaichte" },
				{ LanguageId.gl, "Estados Unidos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Veräinigti Schtaate" },
				{ LanguageId.gu, "યુનાઇટેડ સ્ટેટ્સ" },
				{ LanguageId.guz, "Marekani" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Amurka" },
				{ LanguageId.haw, "ʻAmelika Hui Pū ʻIa" },
				{ LanguageId.he, "ארצות הברית" },
				{ LanguageId.hi, "संयुक्त राज्य" },
				{ LanguageId.hr, "Sjedinjene Američke Države" },
				{ LanguageId.hsb, "Zjednoćene staty Ameriki" },
				{ LanguageId.hu, "Egyesült Államok" },
				{ LanguageId.hy, "Միացյալ Նահանգներ" },
				{ LanguageId.ia, "Statos Unite" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Amerika Serikat" },
				{ LanguageId.ig, "United States" },
				{ LanguageId.ii, "ꂰꇩ" },
				{ LanguageId.@is, "Bandaríkin" },
				{ LanguageId.it, "Stati Uniti" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アメリカ合衆国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Marekani" },
				{ LanguageId.jv, "Amérika Sarékat" },
				{ LanguageId.ka, "ამერიკის შეერთებული შტატები" },
				{ LanguageId.kab, "WDM" },
				{ LanguageId.kam, "Marekani" },
				{ LanguageId.kde, "Malekani" },
				{ LanguageId.kea, "Stadus Unidos di Merka" },
				{ LanguageId.khq, "Ameriki Laabu Margantey" },
				{ LanguageId.ki, "Amerika" },
				{ LanguageId.kk, "Америка Құрама Штаттары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab amerika" },
				{ LanguageId.km, "សហរដ្ឋអាមេរិក" },
				{ LanguageId.kn, "ಯುನೈಟೆಡ್ ಸ್ಟೇಟ್ಸ್" },
				{ LanguageId.ko, "미국" },
				{ LanguageId.kok, "युनायटेड स्टेट्स" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "یوٗنایٹِڑ سِٹیٹِس" },
				{ LanguageId.ksb, "Malekani" },
				{ LanguageId.ksf, "amɛrika" },
				{ LanguageId.ksh, "de vereineschte Schtaate vun Ammärrika" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Кошмо Штаттар" },
				{ LanguageId.la, "United States" },
				{ LanguageId.lag, "Amerɨka" },
				{ LanguageId.lb, "Vereenegt Staaten" },
				{ LanguageId.lg, "Amerika" },
				{ LanguageId.lkt, "Mílahaŋska Tȟamákȟočhe" },
				{ LanguageId.ln, "Ameriki" },
				{ LanguageId.lo, "ສະຫະລັດ" },
				{ LanguageId.lrc, "ڤولاتیا یأکاگئرتە" },
				{ LanguageId.lt, "Jungtinės Valstijos" },
				{ LanguageId.luo, "USA" },
				{ LanguageId.luy, "Marekani" },
				{ LanguageId.lv, "Amerikas Savienotās Valstis" },
				{ LanguageId.mai, "संयुक्त राज्य" },
				{ LanguageId.mas, "Marekani" },
				{ LanguageId.mer, "Amerika" },
				{ LanguageId.mfe, "Lamerik" },
				{ LanguageId.mg, "Etazonia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hononga o Amerika" },
				{ LanguageId.mk, "Соединети Американски Држави" },
				{ LanguageId.ml, "അമേരിക്കൻ ഐക്യനാടുകൾ" },
				{ LanguageId.mn, "Америкийн Нэгдсэн Улс" },
				{ LanguageId.mni, "য়ুনাইটেদ ষ্টেটস" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "युनायटेड स्टेट्स" },
				{ LanguageId.ms, "Amerika Syarikat" },
				{ LanguageId.mt, "l-Istati Uniti" },
				{ LanguageId.mua, "Amerika" },
				{ LanguageId.my, "အမေရိကန် ပြည်ထောင်စု" },
				{ LanguageId.mzn, "متحده ایالات" },
				{ LanguageId.naq, "Amerikab" },
				{ LanguageId.nb, "USA" },
				{ LanguageId.nd, "Amelika" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त राज्य" },
				{ LanguageId.nl, "Verenigde Staten" },
				{ LanguageId.nmg, "Amɛŕka" },
				{ LanguageId.nn, "USA" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߊ߬ߝߏ߫ ߘߍ߬ߣߍ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Amerika" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Yiinaayitid Isteet" },
				{ LanguageId.or, "ଯୁକ୍ତ ରାଷ୍ଟ୍ର" },
				{ LanguageId.os, "АИШ" },
				{ LanguageId.pa, "ਸੰਯੁਕਤ ਰਾਜ (ਅਮਰੀਕਾ)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Yunaítẹ́d Stets" },
				{ LanguageId.pl, "Stany Zjednoczone" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "متحده آيالات" },
				{ LanguageId.pt, "Estados Unidos" },
				{ LanguageId.qu, "Estados Unidos" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Stadis Unids da l’America" },
				{ LanguageId.rn, "Leta Zunze Ubumwe za Amerika" },
				{ LanguageId.ro, "Statele Unite ale Americii" },
				{ LanguageId.rof, "Marekani" },
				{ LanguageId.ru, "Соединенные Штаты" },
				{ LanguageId.rw, "Leta zunz'ubumwe" },
				{ LanguageId.rwk, "Marekani" },
				{ LanguageId.sa, "संयुक्त राज्य:" },
				{ LanguageId.sah, "Америка Холбоһуктаах Штааттара" },
				{ LanguageId.saq, "Marekani" },
				{ LanguageId.sat, "ᱭᱩᱱᱟᱭᱴᱮᱰ ᱮᱥᱴᱮᱴ" },
				{ LanguageId.sbp, "Malekani" },
				{ LanguageId.sd, "آمريڪا جون گڏيل رياستون" },
				{ LanguageId.se, "Amerihká ovttastuvvan stáhtat" },
				{ LanguageId.seh, "Estados Unidos" },
				{ LanguageId.ses, "Ameriki Laabu Margantey" },
				{ LanguageId.sg, "ÂLeaa-Ôko tî Amerika" },
				{ LanguageId.shi, "ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ ⵏ ⵎⵉⵔⵉⴽⴰⵏ" },
				{ LanguageId.si, "එක්සත් ජනපදය" },
				{ LanguageId.sk, "Spojené štáty" },
				{ LanguageId.sl, "Združene države Amerike" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Ovtâstum Staatah" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Amerika" },
				{ LanguageId.so, "Maraykanka" },
				{ LanguageId.sq, "SHBA" },
				{ LanguageId.sr, "Сједињене Државе" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "United States" },
				{ LanguageId.su, "Amérika Sarikat" },
				{ LanguageId.sv, "USA" },
				{ LanguageId.sw, "Marekani" },
				{ LanguageId.syr, "ܐܘܚܕ̈ܢܐ ܡܚܝܕ̈ܐ" },
				{ LanguageId.ta, "அமெரிக்கா" },
				{ LanguageId.te, "యునైటెడ్ స్టేట్స్" },
				{ LanguageId.teo, "Marekani" },
				{ LanguageId.tg, "Иёлоти Муттаҳида" },
				{ LanguageId.th, "สหรัฐอเมริกา" },
				{ LanguageId.ti, "ኣመሪካ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Amerikanyň Birleşen Ştatlary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Puleʻanga fakatahataha ʻAmelika" },
				{ LanguageId.tr, "Amerika Birleşik Devletleri" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "АКШ" },
				{ LanguageId.twq, "Ameriki Laabu Margantey" },
				{ LanguageId.tzm, "Iwunak Idduklen n Amirika" },
				{ LanguageId.ug, "ئامېرىكا قوشما ئىشتاتلىرى" },
				{ LanguageId.uk, "Сполучені Штати" },
				{ LanguageId.ur, "ریاست ہائے متحدہ امریکہ" },
				{ LanguageId.uz, "Amerika Qo‘shma Shtatlari" },
				{ LanguageId.vai, "ꕶꕱ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hoa Kỳ" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Marekani" },
				{ LanguageId.wae, "Amerika" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Etaa Sini" },
				{ LanguageId.xh, "EMelika" },
				{ LanguageId.xog, "Amerika" },
				{ LanguageId.yav, "amálíka" },
				{ LanguageId.yi, "פֿאַראייניגטע שטאַטן" },
				{ LanguageId.yo, "Amẹrikà" },
				{ LanguageId.zgh, "ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ ⵏ ⵎⵉⵔⵉⴽⴰⵏ" },
				{ LanguageId.zh, "美国" },
				{ LanguageId.zu, "i-United States" },
			}
		);
	}
}
