using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class US
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Forenede Stater" },
				{ LanguageId.af, "Verenigde State" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዩናይትድ ስቴተት" },
				{ LanguageId.ar, "الولايات المتحدة" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Amerika Birləşmiş Ştatları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Злучаныя Штаты" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Съединени щати" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "যুক্তরাষ্ট্র" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Stadoù-Unanet" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sjedinjene Države" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Estats Units" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Estados Unidos" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Stati Uniti" },
				{ LanguageId.cs, "Spojené státy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Unol Daleithiau" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Vereinigte Staaten" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ηνωμένες Πολιτείες" },
				{ LanguageId.en, "United States" },
				{ LanguageId.eo, "Usono" },
				{ LanguageId.es, "Estados Unidos" },
				{ LanguageId.et, "Ühendriigid" },
				{ LanguageId.eu, "Ameriketako Estatu Batuak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "ایالات متحده" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Yhdysvallat" },
				{ LanguageId.fil, "Estados Unidos" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "États-Unis" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Feriene Steaten" },
				{ LanguageId.ga, "Stáit Aontaithe" },
				{ LanguageId.gd, "Na Stàitean Aonaichte" },
				{ LanguageId.gl, "Estados Unidos" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "યુનાઈટેડ સ્ટેટ્સ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Amurka" },
				{ LanguageId.haw, "ʻAmelika Hui Pū ʻIa" },
				{ LanguageId.he, "ארצות הברית" },
				{ LanguageId.hi, "संयुक्त राज्य अमेरिका" },
				{ LanguageId.hr, "Ujedinjene države" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Egyesült Államok" },
				{ LanguageId.hy, "Միացյալ Նահանգներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Amerika Serikat" },
				{ LanguageId.ig, "United States" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bandaríkin" },
				{ LanguageId.it, "stati Uniti" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "アメリカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Amerika Serikat" },
				{ LanguageId.ka, "შეერთებული შტატები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "АҚШ" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "សហរដ្ឋអាមេរិក" },
				{ LanguageId.kn, "ಯುನೈಟೆಡ್ ಸ್ಟೇಟ್ಸ್" },
				{ LanguageId.ko, "미국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Америка Кошмо Штаттары" },
				{ LanguageId.la, "United States" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Vereenegt Staaten" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ສະ​ຫະ​ລັດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jungtinės Valstijos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Savienotās Valstis" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Etazonia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "United States" },
				{ LanguageId.mk, "Соединети Држави" },
				{ LanguageId.ml, "അമേരിക്ക" },
				{ LanguageId.mn, "Нэгдсэн Улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "संयुक्त राष्ट्र" },
				{ LanguageId.ms, "Amerika Syarikat" },
				{ LanguageId.mt, "Stati Uniti" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ယူအက်စ်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "forente stater" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त राज्य अमेरिका" },
				{ LanguageId.nl, "Verenigde Staten" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଯୁକ୍ତ ରାଷ୍ଟ୍ର" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੰਯੁਕਤ ਪ੍ਰਾਂਤ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Stany Zjednoczone" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "متحده ایالات" },
				{ LanguageId.pt, "Estados Unidos" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Statele Unite" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Соединенные Штаты" },
				{ LanguageId.rw, "Leta zunz'ubumwe" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "آمريڪا" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "එක්සත් ජනපදය" },
				{ LanguageId.sk, "Spojené štáty" },
				{ LanguageId.sl, "Združene države" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Nyika dzakabatana" },
				{ LanguageId.so, "Maraykanka" },
				{ LanguageId.sq, "Shtetet e Bashkuara" },
				{ LanguageId.sr, "Америка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "United States" },
				{ LanguageId.su, "Amérika Sarikat" },
				{ LanguageId.sv, "Förenta staterna" },
				{ LanguageId.sw, "Marekani" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "அமெரிக்கா" },
				{ LanguageId.te, "సంయుక్త రాష్ట్రాలు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Штатхои Муттахида" },
				{ LanguageId.th, "สหรัฐ" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Birleşen Ştatlar" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Amerika Birleşik Devletleri" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Кушма Штатлар" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "United States" },
				{ LanguageId.uk, "Сполучені Штати" },
				{ LanguageId.ur, "ریاستہائے متحدہ" },
				{ LanguageId.uz, "Qo'shma Shtatlar" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Hoa Kỳ" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Amazwe Amanyene " },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "פֿאַראייניקטע שטאַטן" },
				{ LanguageId.yo, "Orilẹ Amẹrika" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "美国" },
				{ LanguageId.zu, "I-united states" },
			}
		);
	}
}
