using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class VA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "379",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Vatikanstaten" },
				{ LanguageId.af, "Vatikaanstad staat" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "የቫቲካን ከተማ ግዛት" },
				{ LanguageId.ar, "دولة مدينة الفاتيكان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Vatikan Dövləti" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Горад-дзяржава Ватыкан" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Град-държава Ватикана" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ভ্যাটিকান সিটি স্টেট" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Država Vatikan" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Estat de la Ciutat del Vaticà" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Estado sa Vatican City" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Statu di a cità di u Vaticanu" },
				{ LanguageId.cs, "Vatikánský městský stát" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Dinas-wladwriaeth y Fatican" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Staat Vatikanstadt" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Κράτος της Πόλης του Βατικανού" },
				{ LanguageId.en, "Vatican City State" },
				{ LanguageId.eo, "Ŝtato de Vatikanurbo" },
				{ LanguageId.es, "Estado de la Ciudad del Vaticano" },
				{ LanguageId.et, "Vatikani Linnriik" },
				{ LanguageId.eu, "Vatikano Hiriko Estatua" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "ایالت شهر واتیکان" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Vatikaanivaltio" },
				{ LanguageId.fil, "Estado ng Lungsod ng Vatican" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "État de la Cité du Vatican" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Fatikaanstêd" },
				{ LanguageId.ga, "Stát Chathair na Vatacáine" },
				{ LanguageId.gd, "Cathair-bhaile na Bhatacain" },
				{ LanguageId.gl, "Estado da Cidade do Vaticano" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "વેટિકન સિટી રાજ્ય" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Jihar Vatican" },
				{ LanguageId.haw, "Mokuʻāina ʻo Vatican City" },
				{ LanguageId.he, "מדינת הוותיקן" },
				{ LanguageId.hi, "वेटिकन सिटी राज्य" },
				{ LanguageId.hr, "Država Vatikan" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Vatikánvárosi Állam" },
				{ LanguageId.hy, "Վատիկան քաղաք պետություն" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Negara Kota Vatikan" },
				{ LanguageId.ig, "Obodo Vatican State" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Ríki Vatíkansins" },
				{ LanguageId.it, "Stato della Città del Vaticano" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "バチカン市国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Negara Kutha Vatikan" },
				{ LanguageId.ka, "ვატიკანის ქალაქი" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Ватикан мемлекеті" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "រដ្ឋវ៉ាទីកង់" },
				{ LanguageId.kn, "ವ್ಯಾಟಿಕನ್ ಸಿಟಿ ರಾಜ್ಯ" },
				{ LanguageId.ko, "바티칸 시국" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Ватикан мамлекети" },
				{ LanguageId.la, "Civitas Vaticana" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Vatikan Stad Staat" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ລັດວາຕິກັນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Vatikano Miesto Valstybė" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Vatikāna Pilsētvalsts" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Fanjakana Tanànan'i Vatican" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Vatican City State" },
				{ LanguageId.mk, "Државата на градот Ватикан" },
				{ LanguageId.ml, "വത്തിക്കാൻ സിറ്റി സ്റ്റേറ്റ്" },
				{ LanguageId.mn, "Ватикан муж" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "व्हॅटिकन सिटी राज्य" },
				{ LanguageId.ms, "Negara Kota Vatican" },
				{ LanguageId.mt, "Stat tal-Belt tal-Vatikan" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဗာတီကန်စီးတီးပြည်နယ်" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Vatikanstaten" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भ्याटिकन सिटी राज्य" },
				{ LanguageId.nl, "Vaticaanstad staat" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଭାଟିକାନ୍ ସିଟି ରାଜ୍ୟ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵੈਟੀਕਨ ਸਿਟੀ ਰਾਜ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Państwo Watykańskie" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د واتیکان ښار ایالت" },
				{ LanguageId.pt, "Estado da Cidade do Vaticano" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Statul Vatican" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Город-государство Ватикан" },
				{ LanguageId.rw, "Umujyi wa Vatikani" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ويٽيڪن سٽي رياست" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "වතිකානු රාජ්‍යය" },
				{ LanguageId.sk, "Vatikánsky mestský štát" },
				{ LanguageId.sl, "Država Vatikan" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Vatican City State" },
				{ LanguageId.so, "Gobolka Vatican-ka" },
				{ LanguageId.sq, "Shteti i qytetit të Vatikanit" },
				{ LanguageId.sr, "Држава Ватикан" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Vatican City State" },
				{ LanguageId.su, "Nagara Kota Vatikan" },
				{ LanguageId.sv, "Vatikanstaten" },
				{ LanguageId.sw, "Jimbo la Vatican" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "வாடிகன் நகர மாநிலம்" },
				{ LanguageId.te, "వాటికన్ సిటీ రాష్ట్రం" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Давлати шаҳри Ватикан" },
				{ LanguageId.th, "นครรัฐวาติกัน" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Watikan şäheri" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Vatikan Şehir Devleti" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Ватикан шәһәре" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ۋاتىكان شەھىرى" },
				{ LanguageId.uk, "Місто-держава Ватикан" },
				{ LanguageId.ur, "ویٹیکن سٹی اسٹیٹ" },
				{ LanguageId.uz, "Vatikan shahri davlati" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thành phố Vatican" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Isixeko saseVatican" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "וואַטיקאַן סיטי שטאַט" },
				{ LanguageId.yo, "Vatican City State" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "梵蒂冈城国" },
				{ LanguageId.zu, "I-Vatican City State" },
			}
		);
	}
}
