// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class VA
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "379",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Vatikanstaten" },
				{ LanguageId.af, "Vatikaanstad" },
				{ LanguageId.agq, "Vatikàn Sɨ̀tɛ̂" },
				{ LanguageId.ak, "Vatican Man" },
				{ LanguageId.am, "ቫቲካን ከተማ" },
				{ LanguageId.ar, "الفاتيكان" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ভেটিকান চিটি" },
				{ LanguageId.asa, "Vatikani" },
				{ LanguageId.ast, "Ciudá del Vaticanu" },
				{ LanguageId.az, "Vatikan" },
				{ LanguageId.ba, "Ватикан" },
				{ LanguageId.bas, "Vàtìkâŋ" },
				{ LanguageId.be, "Ватыкан" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huvatikani" },
				{ LanguageId.bg, "Ватикан" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Vatikaŋ" },
				{ LanguageId.bn, "ভ্যাটিকান সিটি" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Vatikan" },
				{ LanguageId.brx, "भेटिकान नोगोर" },
				{ LanguageId.bs, "Vatikan" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Ciutat del Vaticà" },
				{ LanguageId.ccp, "𑄞𑄳𑄠𑄑𑄨𑄇𑄚𑄴 𑄥𑄨𑄑𑄨" },
				{ LanguageId.ce, "Ватикан" },
				{ LanguageId.ceb, "Vatican City" },
				{ LanguageId.cgg, "Vatikani" },
				{ LanguageId.chr, "ᎠᏥᎳᏁᏠ ᎦᏚᎲ" },
				{ LanguageId.ckb, "ڤاتیکان" },
				{ LanguageId.co, "Statu di a cità di u Vaticanu" },
				{ LanguageId.cs, "Vatikán" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Y Fatican" },
				{ LanguageId.dav, "Vatikani" },
				{ LanguageId.de, "Vatikanstadt" },
				{ LanguageId.dje, "Vaatikan Laama" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Vatikańske město" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "བ་ཊི་ཀཱན་ སི་ཊི" },
				{ LanguageId.ebu, "Vatikani" },
				{ LanguageId.ee, "Vatikandu nutome" },
				{ LanguageId.el, "Βατικανό" },
				{ LanguageId.en, "Vatican City" },
				{ LanguageId.eo, "Vatikano" },
				{ LanguageId.es, "Ciudad del Vaticano" },
				{ LanguageId.et, "Vatikan" },
				{ LanguageId.eu, "Vatikano Hiria" },
				{ LanguageId.ewo, "Ǹnam Vatikán" },
				{ LanguageId.fa, "واتیکان" },
				{ LanguageId.ff, "Dowla Waticaan" },
				{ LanguageId.fi, "Vatikaani" },
				{ LanguageId.fil, "Vatican City" },
				{ LanguageId.fo, "Vatikanbýur" },
				{ LanguageId.fr, "État de la Cité du Vatican" },
				{ LanguageId.fur, "Vatican" },
				{ LanguageId.fy, "Vaticaanstêd" },
				{ LanguageId.ga, "Cathair na Vatacáine" },
				{ LanguageId.gd, "Cathair na Bhatacain" },
				{ LanguageId.gl, "Cidade do Vaticano" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Vatikanstadt" },
				{ LanguageId.gu, "વેટિકન સિટી" },
				{ LanguageId.guz, "Vatikani" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Birnin Batikan" },
				{ LanguageId.haw, "Mokuʻāina ʻo Vatican City" },
				{ LanguageId.he, "הוותיקן" },
				{ LanguageId.hi, "वेटिकन सिटी" },
				{ LanguageId.hr, "Vatikan" },
				{ LanguageId.hsb, "Vatikanske město" },
				{ LanguageId.hu, "Vatikán" },
				{ LanguageId.hy, "Վատիկան" },
				{ LanguageId.ia, "Citate del Vaticano" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Vatikan" },
				{ LanguageId.ig, "Vatican City" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Vatíkanið" },
				{ LanguageId.it, "Città del Vaticano" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "バチカン市国" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Vatikani" },
				{ LanguageId.jv, "Kutha Vatikan" },
				{ LanguageId.ka, "ქალაქი ვატიკანი" },
				{ LanguageId.kab, "Awanek n Vatikan" },
				{ LanguageId.kam, "Vatikani" },
				{ LanguageId.kde, "Vatikani" },
				{ LanguageId.kea, "Vatikanu" },
				{ LanguageId.khq, "Vaatikan Laama" },
				{ LanguageId.ki, "Vatikani" },
				{ LanguageId.kk, "Ватикан" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Vatican" },
				{ LanguageId.km, "បុរី​វ៉ាទីកង់" },
				{ LanguageId.kn, "ವ್ಯಾಟಿಕನ್ ಸಿಟಿ" },
				{ LanguageId.ko, "바티칸 시국" },
				{ LanguageId.kok, "वॅटिकन शार" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "ویٹِکَن سِٹی" },
				{ LanguageId.ksb, "Vatikani" },
				{ LanguageId.ksf, "watikáŋ" },
				{ LanguageId.ksh, "der Vattikahn" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Ватикан" },
				{ LanguageId.la, "Civitas Vaticana" },
				{ LanguageId.lag, "Vatikáani" },
				{ LanguageId.lb, "Vatikanstad" },
				{ LanguageId.lg, "Vatikaani" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Vatiká" },
				{ LanguageId.lo, "ນະຄອນ ວາຕິກັນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Vatikano Miesto Valstybė" },
				{ LanguageId.luo, "Vatican State" },
				{ LanguageId.luy, "Vatikani" },
				{ LanguageId.lv, "Vatikāns" },
				{ LanguageId.mai, "वेटिकन सिटी" },
				{ LanguageId.mas, "Vatikani" },
				{ LanguageId.mer, "Vatikani" },
				{ LanguageId.mfe, "Lata Vatikan" },
				{ LanguageId.mg, "Firenen’i Vatikana" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Te Poho-o-Pita" },
				{ LanguageId.mk, "Ватикан" },
				{ LanguageId.ml, "വത്തിക്കാൻ" },
				{ LanguageId.mn, "Ватикан хот улс" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "व्हॅटिकन सिटी" },
				{ LanguageId.ms, "Kota Vatican" },
				{ LanguageId.mt, "l-Istat tal-Belt tal-Vatikan" },
				{ LanguageId.mua, "Vaticaŋ" },
				{ LanguageId.my, "ဗာတီကန်စီးတီး" },
				{ LanguageId.mzn, "واتیکان" },
				{ LanguageId.naq, "Vatican State" },
				{ LanguageId.nb, "Vatikanstaten" },
				{ LanguageId.nd, "Vatican State" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भेटिकन सिटी" },
				{ LanguageId.nl, "Vaticaanstad" },
				{ LanguageId.nmg, "Vatikaŋ" },
				{ LanguageId.nn, "Vatikanstaten" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߝ߭ߊߕߌߞߊ߲߫ ߞߊ߬ߝߏ" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Vatikani" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Vaatikaan Siitii" },
				{ LanguageId.or, "ଭାଟିକାନ୍ ସିଟି" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵੈਟੀਕਨ ਸਿਟੀ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Vátíkán Síti" },
				{ LanguageId.pl, "Watykan" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "واتیکان ښار" },
				{ LanguageId.pt, "Cidade do Vaticano" },
				{ LanguageId.qu, "Santa Sede (Ciudad del Vaticano)" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Citad dal Vatican" },
				{ LanguageId.rn, "Umurwa wa Vatikani" },
				{ LanguageId.ro, "Statul Cetății Vaticanului" },
				{ LanguageId.rof, "Vatikani" },
				{ LanguageId.ru, "Ватикан" },
				{ LanguageId.rw, "Umujyi wa Vatikani" },
				{ LanguageId.rwk, "Vatikani" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Vatikani" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Vatikani" },
				{ LanguageId.sd, "ويٽڪين سٽي" },
				{ LanguageId.se, "Vatikána" },
				{ LanguageId.seh, "Vaticano" },
				{ LanguageId.ses, "Vaatikan Laama" },
				{ LanguageId.sg, "Letëe tî Vatikäan" },
				{ LanguageId.shi, "ⴰⵡⴰⵏⴽ ⵏ ⴼⴰⵜⵉⴽⴰⵏ" },
				{ LanguageId.si, "වතිකානු නගරය" },
				{ LanguageId.sk, "Vatikán" },
				{ LanguageId.sl, "Vatikan" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Vatikan" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Vatican State" },
				{ LanguageId.so, "Magaalada Faatikaan" },
				{ LanguageId.sq, "Vatikan" },
				{ LanguageId.sr, "Ватикан" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Vatican City State" },
				{ LanguageId.su, "Nagara Kota Vatikan" },
				{ LanguageId.sv, "Vatikanstaten" },
				{ LanguageId.sw, "Mji wa Vatican" },
				{ LanguageId.syr, "ܡܕܝܢܬܐ ܕܘܛܝܩܢ" },
				{ LanguageId.ta, "வாடிகன் நகரம்" },
				{ LanguageId.te, "వాటికన్ నగరం" },
				{ LanguageId.teo, "Vatikani" },
				{ LanguageId.tg, "Шаҳри Вотикон" },
				{ LanguageId.th, "นครวาติกัน" },
				{ LanguageId.ti, "ከተማ ቫቲካን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Watikan" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Kolo Vatikani" },
				{ LanguageId.tr, "Vatikan" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Ватикан" },
				{ LanguageId.twq, "Vaatikan Laama" },
				{ LanguageId.tzm, "Awank iɣrem n Vatikan" },
				{ LanguageId.ug, "ۋاتىكان" },
				{ LanguageId.uk, "Ватикан" },
				{ LanguageId.ur, "ویٹیکن سٹی" },
				{ LanguageId.uz, "Vatikan" },
				{ LanguageId.vai, "ꕙꔳꕪꘋ ꕢꕨꕌ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Thành Vatican" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Vatikani" },
				{ LanguageId.wae, "Vatikan" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Site bu Watikaa" },
				{ LanguageId.xh, "EVatican City" },
				{ LanguageId.xog, "Vatikaani" },
				{ LanguageId.yav, "fatikáaŋ" },
				{ LanguageId.yi, "וואַטיקאַן שטאָט" },
				{ LanguageId.yo, "Ìlú Vatican" },
				{ LanguageId.zgh, "ⴰⵡⴰⵏⴽ ⵏ ⴼⴰⵜⵉⴽⴰⵏ" },
				{ LanguageId.zh, "梵蒂冈" },
				{ LanguageId.zu, "i-Vatican City" },
			}
		);
	}
}
