// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class VC
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Vincent og Grenadinerne" },
				{ LanguageId.af, "Sint Vincent en die Grenadine" },
				{ LanguageId.agq, "Sɛ̀n Vinsɨ̀n à Gɨlenadi Ù tē" },
				{ LanguageId.ak, "Saint Vincent ne Grenadines" },
				{ LanguageId.am, "ሴንት ቪንሴንት እና ግሬናዲንስ" },
				{ LanguageId.ar, "سانت فنسنت وجزر غرينادين" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ছেইণ্ট ভিনচেণ্ট আৰু গ্ৰীণাডাইনছ" },
				{ LanguageId.asa, "Thantavithenti na Grenadini" },
				{ LanguageId.ast, "San Vicente y Granadines" },
				{ LanguageId.az, "Sent-Vinsent və Qrenadinlər" },
				{ LanguageId.ba, "Сент-Винсент һәм Гренадиндар" },
				{ LanguageId.bas, "Nûmpubi Vɛ̂ŋsâŋ nì grènàdîn" },
				{ LanguageId.be, "Сент-Вінсент і Грэнадзіны" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Husantavisenti na Hugrenadini" },
				{ LanguageId.bg, "Сейнт Винсънт и Гренадини" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Vinisɛn-Senu-ni-Grenadini" },
				{ LanguageId.bn, "সেন্ট ভিনসেন্ট ও গ্রেনাডিনস" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sant-Visant hag ar Grenadinez" },
				{ LanguageId.brx, "सैन्ट भिन्सेन्ट आरो ग्रेनादीन्स" },
				{ LanguageId.bs, "Sveti Vinsent i Grenadin" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Saint Vincent i les Grenadines" },
				{ LanguageId.ccp, "𑄥𑄬𑄚𑄴𑄑𑄴 𑄞𑄨𑄚𑄴𑄥𑄬𑄚𑄴𑄑𑄴 𑄃𑄮 𑄘𑄳𑄠 𑄉𑄳𑄢𑄬𑄚𑄓𑄨𑄚𑄴𑄥𑄴" },
				{ LanguageId.ce, "Сент-Винсент а, Гренадинаш а" },
				{ LanguageId.ceb, "St. Vincent & Grenadines" },
				{ LanguageId.cgg, "Senti Vinsent na Gurenadini" },
				{ LanguageId.chr, "ᎤᏓᏅᏘ ᏫᏂᏏᏂᏗ ᎠᎴ ᎾᏍᎩ ᏇᎾᏗᏁᏍ" },
				{ LanguageId.ckb, "سەینت ڤینسەنت و گرینادینز" },
				{ LanguageId.co, "San Vicente è e Grenadine" },
				{ LanguageId.cs, "Svatý Vincenc a Grenadiny" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Saint Vincent a’r Grenadines" },
				{ LanguageId.dav, "Santavisenti na Grenadini" },
				{ LanguageId.de, "St. Vincent und die Grenadinen" },
				{ LanguageId.dje, "Seŋvinsaŋ nda Grenadine" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "St. Vincent a Grenadiny" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སེནཊ་ཝིན་སེནཌ྄ ཨེནཌ་ གི་རེ་ན་དིནས྄" },
				{ LanguageId.ebu, "Santavisenti na Grenadini" },
				{ LanguageId.ee, "Saint Vincent kple Grenadine nutome" },
				{ LanguageId.el, "Άγιος Βικέντιος και Γρεναδίνες" },
				{ LanguageId.en, "St. Vincent & Grenadines" },
				{ LanguageId.eo, "Sankta Vincento kaj Grenadinoj" },
				{ LanguageId.es, "San Vicente y las Granadinas" },
				{ LanguageId.et, "Saint Vincent ja Grenadiinid" },
				{ LanguageId.eu, "Saint Vincent eta Grenadinak" },
				{ LanguageId.ewo, "Ǹfúfúb-Vɛngəsáŋ-ai-Bə Gələnadín" },
				{ LanguageId.fa, "سنت وینسنت و گرنادین" },
				{ LanguageId.ff, "See Weesaa e Garnadiin" },
				{ LanguageId.fi, "Saint Vincent ja Grenadiinit" },
				{ LanguageId.fil, "St. Vincent & Grenadines" },
				{ LanguageId.fo, "St. Vinsent & Grenadinoyggjar" },
				{ LanguageId.fr, "Saint-Vincent-et-les Grenadines" },
				{ LanguageId.fur, "San Vincent e lis Grenadinis" },
				{ LanguageId.fy, "Saint Vincent en de Grenadines" },
				{ LanguageId.ga, "San Uinseann agus na Greanáidíní" },
				{ LanguageId.gd, "Naomh Bhionsant agus Eileanan Greanadach" },
				{ LanguageId.gl, "San Vicente e as Granadinas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "St. Vincent und d’Grönadiine" },
				{ LanguageId.gu, "સેંટ વિન્સેંટ અને ગ્રેનેડાઇંસ" },
				{ LanguageId.guz, "Santavisenti na Grenadini" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "San Binsan Da Girnadin" },
				{ LanguageId.haw, "Kāna Winikeneke a me nā Gerenadine" },
				{ LanguageId.he, "סנט וינסנט והגרנדינים" },
				{ LanguageId.hi, "सेंट विंसेंट और ग्रेनाडाइंस" },
				{ LanguageId.hr, "Sveti Vincent i Grenadini" },
				{ LanguageId.hsb, "St. Vincent a Grenadiny" },
				{ LanguageId.hu, "Saint Vincent és a Grenadine-szigetek" },
				{ LanguageId.hy, "Սենթ Վինսենթ և Գրենադիններ" },
				{ LanguageId.ia, "Sancte Vincente e le Grenadinas" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Vincent dan Grenadine" },
				{ LanguageId.ig, "St. Vincent & Grenadines" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Vinsent og Grenadíneyjar" },
				{ LanguageId.it, "Saint Vincent e Grenadine" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントビンセント及びグレナディーン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Santavisenti na Grenadini" },
				{ LanguageId.jv, "Saint Vinsen lan Grénadin" },
				{ LanguageId.ka, "სენტ-ვინსენტი და გრენადინები" },
				{ LanguageId.kab, "San Vansu d Grunadin" },
				{ LanguageId.kam, "Santavisenti na Grenadini" },
				{ LanguageId.kde, "Santavisenti na Glenadini" },
				{ LanguageId.kea, "San Bisenti i Granadinas" },
				{ LanguageId.khq, "Seŋvinsaŋ nda Grenadine" },
				{ LanguageId.ki, "Santavisenti na Grenadini" },
				{ LanguageId.kk, "Сент-Винсент және Гренадин аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Vincent netilil ak Grenadines" },
				{ LanguageId.km, "សាំង​វ៉ាំងសង់ និង ហ្គ្រេណាឌីន" },
				{ LanguageId.kn, "ಸೇಂಟ್. ವಿನ್ಸೆಂಟ್ ಮತ್ತು ಗ್ರೆನೆಡೈನ್ಸ್" },
				{ LanguageId.ko, "세인트빈센트그레나딘" },
				{ LanguageId.kok, "सांव विसेंट आनी ग्रानाडीनस" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "سینٹ وینسؠٹ تہٕ گریناڑاینٕز" },
				{ LanguageId.ksb, "Santavisenti na Glenadini" },
				{ LanguageId.ksf, "sɛnvǝnsǝŋ ri grɛnadín" },
				{ LanguageId.ksh, "Zint Vinzänz un de Jrenadines-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Винсент жана Гренадиндер" },
				{ LanguageId.la, "Sancti Vincentii de Grenadinen" },
				{ LanguageId.lag, "Mʉtakatíifu Viséenti na Gernadíini" },
				{ LanguageId.lb, "St. Vincent an d’Grenadinnen" },
				{ LanguageId.lg, "Senti Vinsenti ne Gurendadiini" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Sántu vesá mpé Gelenadinɛ" },
				{ LanguageId.lo, "ເຊນ ວິນເຊນ ແລະ ເກຣເນດິນ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Šventasis Vincentas ir Grenadinai" },
				{ LanguageId.luo, "Saint Vincent gi Grenadines" },
				{ LanguageId.luy, "Santavisenti na Grenadini" },
				{ LanguageId.lv, "Sentvinsenta un Grenadīnas" },
				{ LanguageId.mai, "सेंट विंसेंट आ ग्रेनाडाइंस" },
				{ LanguageId.mas, "Santavisenti na Grenadini" },
				{ LanguageId.mer, "Santavisenti na Grenadini" },
				{ LanguageId.mfe, "Saint-Vincent-ek-Grenadines" },
				{ LanguageId.mg, "Saint-Vincent-et-les Grenadines" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Hato Wēneti me Keretīni" },
				{ LanguageId.mk, "Сент Винсент и Гренадини" },
				{ LanguageId.ml, "സെന്റ് വിൻസെന്റും ഗ്രനെഡൈൻസും" },
				{ LanguageId.mn, "Сент-Винсент ба Гренадин" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट व्हिन्सेंट आणि ग्रेनडाइन्स" },
				{ LanguageId.ms, "Saint Vincent dan Grenadines" },
				{ LanguageId.mt, "Saint Vincent u l-Grenadini" },
				{ LanguageId.mua, "Sǝr Vinceŋ ne Grenadiŋ" },
				{ LanguageId.my, "စိန့်ဗင်းဆင့်နှင့် ဂရိနေဒိုင်" },
				{ LanguageId.mzn, "سنت وینسنت و گرنادین" },
				{ LanguageId.naq, "Saint Vincent and the Grenadines" },
				{ LanguageId.nb, "St. Vincent og Grenadinene" },
				{ LanguageId.nd, "Saint Vincent and the Grenadines" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट भिन्सेन्ट र ग्रेनाडिन्स" },
				{ LanguageId.nl, "Saint Vincent en de Grenadines" },
				{ LanguageId.nmg, "Saint Vincent ba Grenadines" },
				{ LanguageId.nn, "St. Vincent og Grenadinane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߛߍ߲ߕ-ߝ߭ߍߛߊ߲ ߜ߭ߙߋߣߊߘߌ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Senti Vinsent na Gurenadini" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "St. Vinseet fi Gireenadines" },
				{ LanguageId.or, "ସେଣ୍ଟ ଭିନସେଣ୍ଟ ଏବଂ ଗ୍ରେନାଡାଇନ୍ସ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਵਿਨਸੈਂਟ ਐਂਡ ਗ੍ਰੇਨਾਡੀਨਸ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Sent Vínsẹnt & Grẹ́nádians" },
				{ LanguageId.pl, "Saint Vincent i Grenadyny" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سینټ ویسنټینټ او ګرینډینز" },
				{ LanguageId.pt, "São Vicente e Granadinas" },
				{ LanguageId.qu, "San Vicente y las Granadinas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Son Vincenz e las Grenadinas" },
				{ LanguageId.rn, "Sevensa na Gerenadine" },
				{ LanguageId.ro, "Saint Vincent și Grenadinele" },
				{ LanguageId.rof, "Santavisenti na Grenadini" },
				{ LanguageId.ru, "Сент-Винсент и Гренадины" },
				{ LanguageId.rw, "Mutagatifu Visenti na Grenadine" },
				{ LanguageId.rwk, "Santavisenti na Grenadini" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Santavisenti na Grenadini" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Santavisenti na Gilenadini" },
				{ LanguageId.sd, "سینٽ ونسنت ۽ گریناڊینز" },
				{ LanguageId.se, "Saint Vincent ja Grenadine" },
				{ LanguageId.seh, "São Vicente e Granadinas" },
				{ LanguageId.ses, "Seŋvinsaŋ nda Grenadine" },
				{ LanguageId.sg, "Sên-Vensäan na âGrenadîni" },
				{ LanguageId.shi, "ⵙⴰⵏⴼⴰⵏⵙⴰⵏ ⴷ ⴳⵔⵉⵏⴰⴷⵉⵏ" },
				{ LanguageId.si, "ශාන්ත වින්සන්ට් සහ ග්‍රෙනඩින්ස්" },
				{ LanguageId.sk, "Svätý Vincent a Grenadíny" },
				{ LanguageId.sl, "Sveti Vincencij in Grenadine" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "St. Vincent já Grenadines" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Saint Vincent and the Grenadines" },
				{ LanguageId.so, "St. Finsent & Girenadiins" },
				{ LanguageId.sq, "Shën-Vincent dhe Grenadine" },
				{ LanguageId.sr, "Сент Винсент и Гренадини" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saint Vincent le Grenadines" },
				{ LanguageId.su, "Saint Vincent jeung Grénadin" },
				{ LanguageId.sv, "S:t Vincent och Grenadinerna" },
				{ LanguageId.sw, "St. Vincent na Grenadines" },
				{ LanguageId.syr, "ܣܐܢܬ ܒܝܢܣܝܢܬ ܘܓܪܝܢܐܕܝܢܐܣ" },
				{ LanguageId.ta, "செயின்ட் வின்சென்ட் & கிரெனடைன்ஸ்" },
				{ LanguageId.te, "సెయింట్ విన్సెంట్ మరియు గ్రెనడీన్స్" },
				{ LanguageId.teo, "Santavisenti na Grenadini" },
				{ LanguageId.tg, "Сент-Винсент ва Гренадина" },
				{ LanguageId.th, "เซนต์วินเซนต์และเกรนาดีนส์" },
				{ LanguageId.ti, "ቅዱስ ቪንሰንትን ግረነዲነዝን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Sent-Winsent we Grenadinler" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "Sā Viniseni mo Kulenatini" },
				{ LanguageId.tr, "Saint Vincent ve Grenadinler" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Сент-Винсент һәм Гренадин" },
				{ LanguageId.twq, "Seŋvinsaŋ nda Grenadine" },
				{ LanguageId.tzm, "Santevinsent d Grinadin" },
				{ LanguageId.ug, "ساينت ۋىنسېنت ۋە گىرېنادىنېس" },
				{ LanguageId.uk, "Сент-Вінсент і Гренадіни" },
				{ LanguageId.ur, "سینٹ ونسنٹ اور گرینیڈائنز" },
				{ LanguageId.uz, "Sent-Vinsent va Grenadin" },
				{ LanguageId.vai, "ꔻꘋ ꔲꘋꔻꘋ ꗪ ꖶꔓꕯꔵꘋ ꖸ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "St. Vincent và Grenadines" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Santavisenti na Grenadini" },
				{ LanguageId.wae, "St. Vincent und d’Grenadine" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Saŋ Weesaa ak Garanadin" },
				{ LanguageId.xh, "ESt. Vincent & Grenadines" },
				{ LanguageId.xog, "Senti Vinsenti ni Gurendadiini" },
				{ LanguageId.yav, "sɛ́ŋ fɛŋsáŋ elekelenatíin" },
				{ LanguageId.yi, "סיינט ווינסענט און די גרענאַדינעס" },
				{ LanguageId.yo, "Fisẹnnti ati Genadina" },
				{ LanguageId.zgh, "ⵙⴰⵏⴼⴰⵏⵙⴰⵏ ⴷ ⴳⵔⵉⵏⴰⴷⵉⵏ" },
				{ LanguageId.zh, "圣文森特和格林纳丁斯" },
				{ LanguageId.zu, "i-Saint Vincent ne-Grenadines" },
			}
		);
	}
}
