using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class VC
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Saint Vincent og Grenadinerne" },
				{ LanguageId.af, "Saint Vincent en die Grenadines" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ሰይንት ቪንሴንት እና ጀሬናዲኔስ" },
				{ LanguageId.ar, "سانت فنسنت وجزر غرينادين" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Sent Vinsent və Qrenadinlər" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Сэнт-Вінсэнт і Грэнадыны" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Сейнт Винсент и Гренадини" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "সেন্ট ভিনসেন্ট ও গ্রেনাডাইন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Sant-Visant hag ar Grenadinez" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Sveti Vincent i Grenadini" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sant Vicenç i les Granadines" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Saint Vincent ug ang Grenadines" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "San Vicente è e Grenadine" },
				{ LanguageId.cs, "Svatý Vincent a Grenadiny" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Sant Vincent a'r Grenadines" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "St. Vincent und die Grenadinen" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Άγιος Βικέντιος και Γρεναδίνες" },
				{ LanguageId.en, "Saint Vincent and the Grenadines" },
				{ LanguageId.eo, "Sankta Vincento kaj Grenadinoj" },
				{ LanguageId.es, "San Vicente y las Granadinas" },
				{ LanguageId.et, "Saint Vincent ja Grenadiinid" },
				{ LanguageId.eu, "Saint Vincent eta Grenadinak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "سنت وینسنت و گرنادین ها" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Saint Vincent ja Grenadiinit" },
				{ LanguageId.fil, "Saint Vincent at ang Grenadines" },
				{ LanguageId.fo, "Saint Vinsent og Grenadinoyggjar" },
				{ LanguageId.fr, "Saint-Vincent-et-les-Grenadines" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Sint-Finsint en de Grenadinen" },
				{ LanguageId.ga, "San Uinseann agus na Greanáidíní" },
				{ LanguageId.gd, "Naomh Vincent agus na Grenadines" },
				{ LanguageId.gl, "San Vicente e as Granadinas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "સેન્ટ વિન્સેન્ટ અને ગ્રેનેડાઇન્સ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Saint Vincent da Grenadines" },
				{ LanguageId.haw, "Kāna Winikeneke a me nā Gerenadine" },
				{ LanguageId.he, "וינסנט הקדוש ו ה - גרנידיים" },
				{ LanguageId.hi, "संत विंसेंट अँड थे ग्रेनडीनेस" },
				{ LanguageId.hr, "Sveti Vincent i Grenadini" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Saint Vincent és a Grenadine-szigetek" },
				{ LanguageId.hy, "Սենթ Վինսենթ և Գրենադիններ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Saint Vincent dan Grenadines" },
				{ LanguageId.ig, "Saint Vincent na ndị Grenadines" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Sankti Vinsent og Grenadíneyjar" },
				{ LanguageId.it, "Saint Vincent e Grenadine" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "セントビンセントおよびグレナディーン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Saint Vincent lan Grenadines" },
				{ LanguageId.ka, "სენტ ვინსენტი და გრენადინები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Сент-Винсент және Гренадин аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Saint Vincent និង Grenadines" },
				{ LanguageId.kn, "ಸೇಂಟ್ ವಿನ್ಸೆಂಟ್ ಮತ್ತು ಗ್ರೆನಡೈನ್ಸ್" },
				{ LanguageId.ko, "세인트 빈센트 그레나딘" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Сент-Винсент жана Гренадиндер" },
				{ LanguageId.la, "Sancti Vincentii de Grenadinen" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Saint Vincent an d'Grenadinnen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Saint Vincent ແລະ Grenadines" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Sent Vincentas ir Grenadinai" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Sentvinsenta un Grenadīnas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Saint Vincent sy ny Grenadines" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Saint Vincent and the Grenadines" },
				{ LanguageId.mk, "Свети Винсент и Гренадини" },
				{ LanguageId.ml, "സെൻ്റ് വിൻസെൻ്റും ഗ്രനേഡൈൻസും" },
				{ LanguageId.mn, "Сент Винсент ба Гренадин" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "सेंट व्हिन्सेंट आणि ग्रेनेडाइन्स" },
				{ LanguageId.ms, "Saint Vincent dan Grenadines" },
				{ LanguageId.mt, "San Vinċenz u l-Grenadini" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Saint Vincent နှင့် Grenadines" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Saint Vincent og Grenadinene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "सेन्ट भिन्सेन्ट र ग्रेनेडाइन्स" },
				{ LanguageId.nl, "Saint Vincent en de Grenadines" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "Saint Vincent og Grenadinane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ସେଣ୍ଟ ଭିନ୍ସେଣ୍ଟ ଏବଂ ଗ୍ରେନାଡାଇନ୍ସ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਸੇਂਟ ਵਿਨਸੈਂਟ ਅਤੇ ਗ੍ਰੇਨਾਡਾਈਨਜ਼" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Saint Vincent i Grenadyny" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سانت وینسنټ او ګریناډینز" },
				{ LanguageId.pt, "São Vicente e Granadinas" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Saint Vincent și Grenadine" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Святой Винсент и Гренадины" },
				{ LanguageId.rw, "Mutagatifu Visenti na Grenadine" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "سينٽ ويڪنٽ ۽ گرينڊنيس" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "ශාන්ත වින්සන්ට් සහ ග්රෙනඩින්ස්" },
				{ LanguageId.sk, "Svätý Vincent a Grenadíny" },
				{ LanguageId.sl, "Sveti Vincent in Grenadini" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Sendi Vincent neGirenadhini" },
				{ LanguageId.so, "Saint Vincent iyo Grenadines" },
				{ LanguageId.sq, "Shën Vincenti dhe Grenadinet" },
				{ LanguageId.sr, "Свети Винцент и Гренадини" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Saint Vincent le Grenadines" },
				{ LanguageId.su, "Saint Vincent jeung Grénadin" },
				{ LanguageId.sv, "Saint Vincent och Grenadinerna" },
				{ LanguageId.sw, "Saint Vincent na Grenadines" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "செயின்ட் வின்சென்ட் மற்றும் கிரெனடைன்ஸ்" },
				{ LanguageId.te, "సెయింట్ విన్సెంట్ మరియు గ్రెనడైన్స్" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Сент-Винсент ва Гренадинҳо" },
				{ LanguageId.th, "เซนต์วินเซนต์และเกรนาดีนส์" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Keramatly Winsent we Grenadinler" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Saint Vincent ve Grenadinler" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Изге Винсент һәм Гренадиннар" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ئەۋلىيا ۋىنسېنت ۋە گرېنادىنلار" },
				{ LanguageId.uk, "Сент-Вінсент і Гренадини" },
				{ LanguageId.ur, "سینٹ ونسنٹ اور گریناڈائنز" },
				{ LanguageId.uz, "Sent-Vinsent va Grenadin orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Saint Vincent và Grenadines" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Seyint Vinsent neGrenadins" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "סיינט ווינסענט און די גרענאַדינעס" },
				{ LanguageId.yo, "Saint Vincent ati awọn Grenadines" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "圣文森特和格林纳丁斯" },
				{ LanguageId.zu, "I-Saint Vincent ne-Grenadines" },
			}
		);
	}
}
