using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class VG
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Jomfruøerne (britiske)" },
				{ LanguageId.af, "Virgin Islands (Brits)" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቨርጂን ደሴቶች (ብሪቲሽ)" },
				{ LanguageId.ar, "جزر العذراء البريطانية)" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Virgin Adaları (Britaniya)" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Віргінскія астравы (Брытанскія)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Вирджински острови (Британски)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ভার্জিন দ্বীপপুঞ্জ (ব্রিটিশ)" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Djevičanska ostrva (britanska)" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Verges (Britàniques)" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Virgin Islands (British)" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isole Vergini (British)" },
				{ LanguageId.cs, "Panenské ostrovy (britské)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd y Wyryf (Prydeinig)" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Virgin Inseln, Britisch)" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Παρθένοι Νήσοι (Βρετανία)" },
				{ LanguageId.en, "Virgin Islands (British)" },
				{ LanguageId.eo, "Virgulininsuloj (britoj)" },
				{ LanguageId.es, "Islas Vírgenes (Británicas)" },
				{ LanguageId.et, "Neitsisaared (Briti)" },
				{ LanguageId.eu, "Birjina uharteak (Britainia Handia)" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر ویرجین (بریتانیا)" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Neitsytsaaret (Britti)" },
				{ LanguageId.fil, "Virgin Islands (British)" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Îles Vierges (britanniques)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Virgin Islands (Britsk)" },
				{ LanguageId.ga, "Oileáin na Maighdean (British)" },
				{ LanguageId.gd, "Eileanan Virgin (Breatannais)" },
				{ LanguageId.gl, "Illas Virxes (británicas)" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "વર્જિન ટાપુઓ (બ્રિટિશ)" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Virgin (British)" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Virgin (Beretania)" },
				{ LanguageId.he, "איי הבתולה (בריטי)" },
				{ LanguageId.hi, "वर्जिन द्वीप समूह (ब्रिटिश)" },
				{ LanguageId.hr, "Djevičanski otoci (britanski)" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Virgin-szigetek (brit)" },
				{ LanguageId.hy, "Վիրջինյան կղզիներ (Բրիտանական)" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Virgin (Inggris)" },
				{ LanguageId.ig, "Agwaetiti Virgin (British)" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Jómfrúareyjar (Breskar)" },
				{ LanguageId.it, "Isole Vergini (britanniche)" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "バージン諸島 (イギリス)" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Virgin (Inggris)" },
				{ LanguageId.ka, "ვირჯინიის კუნძულები (ბრიტანული)" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Виргин аралдары (Британ)" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះវឺជីន (អង់គ្លេស)" },
				{ LanguageId.kn, "ವರ್ಜಿನ್ ದ್ವೀಪಗಳು (ಬ್ರಿಟಿಷ್)" },
				{ LanguageId.ko, "버진 아일랜드(영국)" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Виргин аралдары (Британия)" },
				{ LanguageId.la, "Insulae Virgines (British)" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Virgin Islands (Britesch)" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະເວີຈິນ (ອັງກິດ)" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Mergelių salos (Britų)" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Virdžīnu salas (britu)" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Virijiny (Britanika)" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Moutere Wahine (British)" },
				{ LanguageId.mk, "Девствени острови (британски)" },
				{ LanguageId.ml, "വിർജിൻ ദ്വീപുകൾ (ബ്രിട്ടീഷ്)" },
				{ LanguageId.mn, "Виржиний арлууд (Их Британи)" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "व्हर्जिन बेटे (ब्रिटिश)" },
				{ LanguageId.ms, "Kepulauan Virgin (British)" },
				{ LanguageId.mt, "Gżejjer Verġni (Ingliżi)" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဗာဂျင်ကျွန်းများ (ဗြိတိသျှ)" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Jomfruøyene (britiske)" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भर्जिन टापु (बेलायत)" },
				{ LanguageId.nl, "Maagdeneilanden (Brits)" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଭର୍ଜିନ ଦ୍ୱୀପପୁଞ୍ଜ (ବ୍ରିଟିଶ)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵਰਜਿਨ ਟਾਪੂ (ਬ੍ਰਿਟਿਸ਼)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Dziewicze (brytyjskie)" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ورجن ټاپوګان (بریتانوي)" },
				{ LanguageId.pt, "Ilhas Virgens (britânicas)" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Virgine (britanice)" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Виргинские острова (Британские)" },
				{ LanguageId.rw, "Ibirwa bya Virginie (Abongereza)" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ورجن ٻيٽ (برطانوي)" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "වර්ජින් දූපත් (බ්‍රිතාන්‍ය)" },
				{ LanguageId.sk, "Panenské ostrovy (Britské)" },
				{ LanguageId.sl, "Deviški otoki (britanski)" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Virgin Islands (British)" },
				{ LanguageId.so, "Jasiiradaha Virgin (Ingiriis)" },
				{ LanguageId.sq, "Ishujt e Virgjër (Angleze)" },
				{ LanguageId.sr, "Девичанска острва (британска)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Virgin (Borithane)" },
				{ LanguageId.su, "Kapuloan Virgin (Inggris)" },
				{ LanguageId.sv, "Jungfruöarna (brittiska)" },
				{ LanguageId.sw, "Visiwa vya Virgin (Uingereza)" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "விர்ஜின் தீவுகள் (பிரிட்டிஷ்)" },
				{ LanguageId.te, "వర్జిన్ ఐలాండ్స్ (బ్రిటీష్)" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Вирҷиния (Бритониё)" },
				{ LanguageId.th, "หมู่เกาะเวอร์จิน (อังกฤษ)" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Wirgin adalary (Iňlis)" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Virgin Adaları (İngiliz)" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Виргин утраулары (Британия)" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ۋىرگىن تاقىم ئارىلى (ئەنگىلىيە)" },
				{ LanguageId.uk, "Віргінські острови (Британські)" },
				{ LanguageId.ur, "ورجن جزائر (برطانوی)" },
				{ LanguageId.uz, "Virjiniya orollari (Britaniya)" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Virgin (Anh)" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseVirgin (eBritani)" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "ווירגין אינזלען (בריטיש)" },
				{ LanguageId.yo, "Erékùṣù Wundia (British)" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "维尔京群岛（英属）" },
				{ LanguageId.zu, "I-Virgin Islands (British)" },
			}
		);
	}
}
