// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class VG
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "De Britiske Jomfruøer" },
				{ LanguageId.af, "Britse Maagde-eilande" },
				{ LanguageId.agq, "Chwɨlà m̀ Vidzinyìa m̀ Bɨ̀letì mò" },
				{ LanguageId.ak, "Ngresifoɔ Virgin Island" },
				{ LanguageId.am, "የእንግሊዝ ቨርጂን ደሴቶች" },
				{ LanguageId.ar, "جزر فيرجن البريطانية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ব্ৰিটিছ ভাৰ্জিন দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Virgin vya Uingeredha" },
				{ LanguageId.ast, "Islles Vírxenes Britániques" },
				{ LanguageId.az, "Britaniyanın Virgin adaları" },
				{ LanguageId.ba, "Британия Виргин утрауҙары" },
				{ LanguageId.bas, "Bìòn bi kɔnji bi Ŋgisì" },
				{ LanguageId.be, "Брытанскія Віргінскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Virgin fya Huingereza" },
				{ LanguageId.bg, "Британски Вирджински острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Angilɛ ka Sungurunnin Gun" },
				{ LanguageId.bn, "ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Gwercʼh Breizh-Veur" },
				{ LanguageId.brx, "ब्रिटिश भार्जिन द्वीपफोर" },
				{ LanguageId.bs, "Britanska Djevičanska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Verges Britàniques" },
				{ LanguageId.ccp, "𑄝𑄳𑄢𑄨𑄑𑄨𑄌𑄴 𑄞𑄢𑄴𑄎𑄨𑄚𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Виргинийн гӀайренаш (Британи)" },
				{ LanguageId.ceb, "British Virgin Islands" },
				{ LanguageId.cgg, "Ebizinga bya Virigini ebya Bungyereza" },
				{ LanguageId.chr, "ᏈᏗᏍ ᎠᏒᏂᎸ ᏂᎨᏒᎾ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی ڤیرجنی بەریتانیا" },
				{ LanguageId.co, "Isole Vergini (British)" },
				{ LanguageId.cs, "Britské Panenské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Gwyryf Prydain" },
				{ LanguageId.dav, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.de, "Britische Jungferninseln" },
				{ LanguageId.dje, "Britiši Virgin gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Britiske kněžniske kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཝརཇིན་གླིང་ཚོམ་ བྲཱི་ཊིཤ་མངའ་ཁོངས" },
				{ LanguageId.ebu, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.ee, "Britaintɔwo ƒe Virgin ƒudomekpowo nutome" },
				{ LanguageId.el, "Βρετανικές Παρθένες Νήσοι" },
				{ LanguageId.en, "British Virgin Islands" },
				{ LanguageId.eo, "Britaj Virgulininsuloj" },
				{ LanguageId.es, "Islas Vírgenes Británicas" },
				{ LanguageId.et, "Briti Neitsisaared" },
				{ LanguageId.eu, "Birjina uharte britainiarrak" },
				{ LanguageId.ewo, "ńnam Minlán ɛ́ngəlís" },
				{ LanguageId.fa, "جزایر ویرجین بریتانیا" },
				{ LanguageId.ff, "duuɗe kecce britanii" },
				{ LanguageId.fi, "Brittiläiset Neitsytsaaret" },
				{ LanguageId.fil, "British Virgin Islands" },
				{ LanguageId.fo, "Stóra Bretlands Jomfrúoyggjar" },
				{ LanguageId.fr, "Îles Vierges britanniques" },
				{ LanguageId.fur, "Isulis vergjinis britanichis" },
				{ LanguageId.fy, "Britse Maagdeneilannen" },
				{ LanguageId.ga, "Oileáin Bhriotanacha na Maighdean" },
				{ LanguageId.gd, "Eileanan Breatannach na Maighdinn" },
				{ LanguageId.gl, "Illas Virxes Británicas" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Britischi Jungfere-Insle" },
				{ LanguageId.gu, "બ્રિટિશ વર્જિન આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Birjin Na Birtaniya" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Virgin (Beretania)" },
				{ LanguageId.he, "איי הבתולה הבריטיים" },
				{ LanguageId.hi, "ब्रिटिश वर्जिन द्वीपसमूह" },
				{ LanguageId.hr, "Britanski Djevičanski Otoci" },
				{ LanguageId.hsb, "Britiske knježniske kupy" },
				{ LanguageId.hu, "Brit Virgin-szigetek" },
				{ LanguageId.hy, "Բրիտանական Վիրջինյան կղզիներ" },
				{ LanguageId.ia, "Insulas Virgine britannic" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Virgin Britania Raya" },
				{ LanguageId.ig, "British Virgin Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bresku Jómfrúaeyjar" },
				{ LanguageId.it, "Isole Vergini Britanniche" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "英領ヴァージン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.jv, "Kapuloan Virgin Britania" },
				{ LanguageId.ka, "ბრიტანეთის ვირჯინის კუნძულები" },
				{ LanguageId.kab, "Tigzirin Tiverjiniyin Tigliziyin" },
				{ LanguageId.kam, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.kde, "Chisiwa Chivihi cha Wingalesa" },
				{ LanguageId.kea, "Ilhas Virjens Británikas" },
				{ LanguageId.khq, "Britiši Virgin gungey" },
				{ LanguageId.ki, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.kk, "Британдық Виргин аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwembeyotab British Virgin" },
				{ LanguageId.km, "កោះ​វឺជិន​ចក្រភព​អង់គ្លេស" },
				{ LanguageId.kn, "ಬ್ರಿಟಿಷ್ ವರ್ಜಿನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "영국령 버진아일랜드" },
				{ LanguageId.kok, "ब्रिटनाचे विर्जिन जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "بَرطانوی ؤرجِن جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Vilgin vya Uingeeza" },
				{ LanguageId.ksf, "zǝ bɛ gɔn inɛ a ingɛrís" },
				{ LanguageId.ksh, "de brettesche Juffer-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Виргин аралдары (Британия)" },
				{ LanguageId.la, "Insulae Virgines (British)" },
				{ LanguageId.lag, "Visíiwa vya Vigíini vya Ʉɨngeréesa" },
				{ LanguageId.lb, "Britesch Joffereninselen" },
				{ LanguageId.lg, "Bizinga ebya Virigini ebitwalibwa Bungereza" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Vierzi ya Angɛlɛtɛ́lɛ" },
				{ LanguageId.lo, "ໝູ່ເກາະ ເວີຈິນຂອງອັງກິດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Didžiosios Britanijos Mergelių Salos" },
				{ LanguageId.luo, "British Virgin Islands" },
				{ LanguageId.luy, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.lv, "Britu Virdžīnas" },
				{ LanguageId.mai, "ब्रिटिश वर्जिन द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.mer, "Aĩrandi cia Virgin cia Ngeretha" },
				{ LanguageId.mfe, "Zil vierz britanik" },
				{ LanguageId.mg, "Nosy britanika virijiny" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Moutere Puhi Piritene" },
				{ LanguageId.mk, "Британски Девствени Острови" },
				{ LanguageId.ml, "ബ്രിട്ടീഷ് വെർജിൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "Британийн Виржиний арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "ब्रिटिश व्हर्जिन बेटे" },
				{ LanguageId.ms, "Kepulauan Virgin British" },
				{ LanguageId.mt, "il-Gżejjer Verġni Brittaniċi" },
				{ LanguageId.mua, "ser Anglofon ma laŋne" },
				{ LanguageId.my, "ဗြိတိသျှ ဗာဂျင်း ကျွန်းစု" },
				{ LanguageId.mzn, "بریتانیای ویرجین" },
				{ LanguageId.naq, "British Virgin Islands" },
				{ LanguageId.nb, "De britiske jomfruøyene" },
				{ LanguageId.nd, "British Virgin Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "बेलायती भर्जिन टापुहरू" },
				{ LanguageId.nl, "Britse Maagdeneilanden" },
				{ LanguageId.nmg, "Minsilɛ́ mímaŋ mí ngɛ̄lɛ̄n" },
				{ LanguageId.nn, "Dei britiske Jomfruøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߓߙߌߕߊ߲ߓߊ߫ ߕߌ߲߫ ߞߊߓߊ߲" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "Burutic dhuɔ̱ɔ̱l be̱rgin" },
				{ LanguageId.nyn, "Ebizinga bya Virigini ebya Bungyereza" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Odoloota Varjiin Biritish" },
				{ LanguageId.or, "ବ୍ରିଟିଶ୍‌ ଭର୍ଜିନ୍ ଦ୍ୱୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਬ੍ਰਿਟਿਸ਼ ਵਰਜਿਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Brítísh Vájín Aílands" },
				{ LanguageId.pl, "Brytyjskie Wyspy Dziewicze" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "بریتانوی ویګور ټاپوګان" },
				{ LanguageId.pt, "Ilhas Virgens Britânicas" },
				{ LanguageId.qu, "Islas Vírgenes Británicas" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Virginas Britannicas" },
				{ LanguageId.rn, "Ibirwa by’isugi by’Abongereza" },
				{ LanguageId.ro, "Insulele Virgine Britanice" },
				{ LanguageId.rof, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.ru, "Виргинские о-ва (Великобритания)" },
				{ LanguageId.rw, "Ibirwa bya Virginie (Abongereza)" },
				{ LanguageId.rwk, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli ifya Viliginiya ifya Uwingelesa" },
				{ LanguageId.sd, "برطانوي ورجن ٻيٽ" },
				{ LanguageId.se, "Brittania Virgin-sullot" },
				{ LanguageId.seh, "Ilhas Virgens Britânicas" },
				{ LanguageId.ses, "Britiši Virgin gungey" },
				{ LanguageId.sg, "Âzôâ Viîrîggo tî Anglëe" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵏⵏⴳⵍⵉⵣ" },
				{ LanguageId.si, "බ්‍රිතාන්‍ය වර්ජින් දූපත්" },
				{ LanguageId.sk, "Britské Panenské ostrovy" },
				{ LanguageId.sl, "Britanski Deviški otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Brittiliih Nieidâsuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveHingirandi" },
				{ LanguageId.so, "Biritish Farjin Island" },
				{ LanguageId.sq, "Ishujt e Virgjër Britanikë" },
				{ LanguageId.sr, "Британска Девичанска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Virgin (Borithane)" },
				{ LanguageId.su, "Kapuloan Virgin (Inggris)" },
				{ LanguageId.sv, "Brittiska Jungfruöarna" },
				{ LanguageId.sw, "Visiwa vya Virgin, Uingereza" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܒܬܘ̈ܠܐ ܕܒܪܝܛܢܝܐ" },
				{ LanguageId.ta, "பிரிட்டீஷ் கன்னித் தீவுகள்" },
				{ LanguageId.te, "బ్రిటిష్ వర్జిన్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.tg, "Ҷазираҳои Виргини Британия" },
				{ LanguageId.th, "หมู่เกาะบริติชเวอร์จิน" },
				{ LanguageId.ti, "ደሴታት ደናግል ብሪጣንያ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Britan Wirgin adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Vilikini fakapilitānia" },
				{ LanguageId.tr, "Britanya Virjin Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Британия Виргин утраулары" },
				{ LanguageId.twq, "Britiši Virgin gungey" },
				{ LanguageId.tzm, "Tigzirin (Virgin) Tibṛiṭaniyin" },
				{ LanguageId.ug, "ئەنگلىيە ۋىرگىن ئاراللىرى" },
				{ LanguageId.uk, "Британські Віргінські острови" },
				{ LanguageId.ur, "برٹش ورجن آئلینڈز" },
				{ LanguageId.uz, "Britaniya Virgin orollari" },
				{ LanguageId.vai, "ꔛꔟꔻ ꗩꗡ ꗏ ꖷꖬ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Virgin thuộc Anh" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Virgin vya Uingereza" },
				{ LanguageId.wae, "Britiši Jungfröiwinslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Wirsin yu Brëtaañ" },
				{ LanguageId.xh, "EBritish Virgin Islands" },
				{ LanguageId.xog, "Ebizinga bya Virigini ebitwalibwa Bungereza" },
				{ LanguageId.yav, "Filisíin ungilís" },
				{ LanguageId.yi, "ווירגין אינזלען (בריטיש)" },
				{ LanguageId.yo, "Etíkun Fágínì ti ìlú Bírítísì" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵏⵏⴳⵍⵉⵣ" },
				{ LanguageId.zh, "英属维尔京群岛" },
				{ LanguageId.zu, "i-British Virgin Islands" },
			}
		);
	}
}
