// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class VI
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "De Amerikanske Jomfruøer" },
				{ LanguageId.af, "VSA se Maagde-eilande" },
				{ LanguageId.agq, "U. S. Chwɨlà fɨ Mbuʔmbu" },
				{ LanguageId.ak, "Amɛrika Virgin Islands" },
				{ LanguageId.am, "የአሜሪካ ቨርጂን ደሴቶች" },
				{ LanguageId.ar, "جزر فيرجن الأمريكية" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ইউ. এছ. ভাৰ্জিন দ্বীপপুঞ্জ" },
				{ LanguageId.asa, "Vithiwa vya Virgin vya Marekani" },
				{ LanguageId.ast, "Islles Vírxenes Americanes" },
				{ LanguageId.az, "ABŞ Virgin adaları" },
				{ LanguageId.ba, "АҠШ Виргин утрауҙары" },
				{ LanguageId.bas, "Bìòn bi kɔnji bi U.S." },
				{ LanguageId.be, "Амерыканскія Віргінскія астравы" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Ifisima fya Virgin fya Humelekani" },
				{ LanguageId.bg, "Американски Вирджински острови" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Ameriki ka Sungurunnin Gun" },
				{ LanguageId.bn, "মার্কিন যুক্তরাষ্ট্রীয় ভার্জিন দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Inizi Gwercʼh ar Stadoù-Unanet" },
				{ LanguageId.brx, "इउ. एस भार्जिन द्वीपफोर" },
				{ LanguageId.bs, "Američka Djevičanska ostrva" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Verges dels Estats Units" },
				{ LanguageId.ccp, "𑄟𑄢𑄴𑄇𑄨𑄚𑄴 𑄎𑄧𑄙𑄢𑄬𑄌𑄴𑄎𑄮𑄢𑄴 𑄞𑄢𑄴𑄎𑄨𑄚𑄴 𑄉𑄭 𑄉𑄭 𑄞𑄨𑄘𑄳𑄠" },
				{ LanguageId.ce, "Виргинийн гӀайренаш (АЦШ)" },
				{ LanguageId.ceb, "U.S. Virgin Islands" },
				{ LanguageId.cgg, "Ebizinga bya Virigini ebya Amerika" },
				{ LanguageId.chr, "U.S. ᎠᏒᏂᎸ ᏂᎨᏒᎾ ᏚᎦᏚᏛᎢ" },
				{ LanguageId.ckb, "دوورگەکانی ڤیرجنی ئەمەریکا" },
				{ LanguageId.co, "Isole Vergini (U.S.)" },
				{ LanguageId.cs, "Americké Panenské ostrovy" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Gwyryf yr Unol Daleithiau" },
				{ LanguageId.dav, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.de, "Amerikanische Jungferninseln" },
				{ LanguageId.dje, "Ameerik Virgin Gungey" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Ameriske kněžniske kupy" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཝརཇིན་གླིང་ཚོམ་ ཡུ་ཨེས་ཨེ་མངའ་ཁོངས" },
				{ LanguageId.ebu, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.ee, "U.S. Vɛrgin ƒudomekpowo nutome" },
				{ LanguageId.el, "Αμερικανικές Παρθένες Νήσοι" },
				{ LanguageId.en, "U.S. Virgin Islands" },
				{ LanguageId.eo, "Usonaj Virgulininsuloj" },
				{ LanguageId.es, "Islas Vírgenes de EE. UU." },
				{ LanguageId.et, "USA Neitsisaared" },
				{ LanguageId.eu, "Birjina uharte amerikarrak" },
				{ LanguageId.ewo, "Minlán Mi Amɛrəkə" },
				{ LanguageId.fa, "جزایر ویرجین ایالات متحده" },
				{ LanguageId.ff, "Duuɗe Kecce Amerik" },
				{ LanguageId.fi, "Yhdysvaltain Neitsytsaaret" },
				{ LanguageId.fil, "U.S. Virgin Islands" },
				{ LanguageId.fo, "Sambandsríki Amerikas Jomfrúoyggjar" },
				{ LanguageId.fr, "Îles Vierges des États-Unis" },
				{ LanguageId.fur, "Isulis vergjinis americanis" },
				{ LanguageId.fy, "Amerikaanske Maagdeneilannen" },
				{ LanguageId.ga, "Oileáin Mheiriceánacha na Maighdean" },
				{ LanguageId.gd, "Eileanan na Maighdinn aig na SA" },
				{ LanguageId.gl, "Illas Virxes Estadounidenses" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Amerikaanischi Jungfere-Insle" },
				{ LanguageId.gu, "યુએસ વર્જિન આઇલેન્ડ્સ" },
				{ LanguageId.guz, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibiran Birjin Ta Amurka" },
				{ LanguageId.haw, "Nā Mokupuni Virgin (U.S.)" },
				{ LanguageId.he, "איי הבתולה של ארצות הברית" },
				{ LanguageId.hi, "यू॰एस॰ वर्जिन द्वीपसमूह" },
				{ LanguageId.hr, "Američki Djevičanski Otoci" },
				{ LanguageId.hsb, "Ameriske knježniske kupy" },
				{ LanguageId.hu, "Amerikai Virgin-szigetek" },
				{ LanguageId.hy, "ԱՄՆ Վիրջինյան կղզիներ" },
				{ LanguageId.ia, "Insulas Virgine statounitese" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Virgin Amerika Serikat" },
				{ LanguageId.ig, "U.S. Virgin Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Bandarísku Jómfrúaeyjar" },
				{ LanguageId.it, "Isole Vergini Americane" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "米領ヴァージン諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.jv, "Kapuloan Virgin Amérika" },
				{ LanguageId.ka, "აშშ-ის ვირჯინის კუნძულები" },
				{ LanguageId.kab, "W.D. Tigzirin n Virginya" },
				{ LanguageId.kam, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.kde, "Chisiwa Chivihi cha Malekani" },
				{ LanguageId.kea, "Ilhas Virjens Merkanas" },
				{ LanguageId.khq, "Ameerik Virgin Gungey" },
				{ LanguageId.ki, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.kk, "АҚШ-тың Виргин аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Ikwemweiyotab Amerika" },
				{ LanguageId.km, "កោះ​វឺជីន​អាមេរិក" },
				{ LanguageId.kn, "ಯು.ಎಸ್. ವರ್ಜಿನ್ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "미국령 버진아일랜드" },
				{ LanguageId.kok, "संयुक्त राज्यांचे विर्जिन जुंवे" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "یوٗ ایس ؤرجِن جٔزیٖرٕ" },
				{ LanguageId.ksb, "Visiwa vya Vilgin vya Malekani" },
				{ LanguageId.ksf, "zǝ bɛ gɔn inɛ á amɛrika" },
				{ LanguageId.ksh, "de ammärrikahnesche Juffer-Enselle" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Виргин аралдары (АКШ)" },
				{ LanguageId.la, "Insularum Virginum (US.)" },
				{ LanguageId.lag, "Visíiwa vya Vigíini vya Amerɨ́ka" },
				{ LanguageId.lb, "Amerikanesch Joffereninselen" },
				{ LanguageId.lg, "Bizinga bya Virigini eby’Amerika" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Bisanga bya Vierzi ya Ameriki" },
				{ LanguageId.lo, "ໝູ່ເກາະ ເວີຈິນ ຂອງສະຫະລັດ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jungtinių Valstijų Mergelių Salos" },
				{ LanguageId.luo, "U.S. Virgin Islands" },
				{ LanguageId.luy, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.lv, "ASV Virdžīnas" },
				{ LanguageId.mai, "यू॰एस॰ वर्जिन द्वीपसमूह" },
				{ LanguageId.mas, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.mer, "Aĩrandi cia Virgin cia Amerika" },
				{ LanguageId.mfe, "Zil Vierz Lamerik" },
				{ LanguageId.mg, "Nosy Virijiny Etazonia" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Ngā Moutere Puhi Amerika" },
				{ LanguageId.mk, "Американски Девствени Острови" },
				{ LanguageId.ml, "യു.എസ്. വെർജിൻ ദ്വീപുകൾ" },
				{ LanguageId.mn, "АНУ-ын Виржиний арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "यू.एस. व्हर्जिन बेटे" },
				{ LanguageId.ms, "Kepulauan Virgin A.S." },
				{ LanguageId.mt, "il-Gżejjer Verġni tal-Istati Uniti" },
				{ LanguageId.mua, "Sǝr amerika ma laŋne" },
				{ LanguageId.my, "ယူအက်စ် ဗာဂျင်း ကျွန်းစု" },
				{ LanguageId.mzn, "آمریکای ویرجین" },
				{ LanguageId.naq, "U.S. Virgin Islands" },
				{ LanguageId.nb, "De amerikanske jomfruøyene" },
				{ LanguageId.nd, "U.S. Virgin Islands" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "संयुक्त राज्य भर्जिन टापुहरु" },
				{ LanguageId.nl, "Amerikaanse Maagdeneilanden" },
				{ LanguageId.nmg, "Minsilɛ mí maŋ́ m´Amɛrka" },
				{ LanguageId.nn, "Dei amerikanske Jomfruøyane" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߞߊ߬ߝߏ߫ ߘߍ߬ߣߍ߲ ߕߌ߲߫ ߞߊߓߊ߲߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Ebizinga bya Virigini ebya Amerika" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "U.S. Odoloota Varjiin" },
				{ LanguageId.or, "ଯୁକ୍ତରାଷ୍ଟ୍ର ଭର୍ଜିନ୍ ଦ୍ଵୀପପୁଞ୍ଜ" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਯੂ ਐੱਸ ਵਰਜਿਨ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "U.S. Vájín Aílands" },
				{ LanguageId.pl, "Wyspy Dziewicze Stanów Zjednoczonych" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "د متحده آيالاتو ورجن ټاپوګان" },
				{ LanguageId.pt, "Ilhas Virgens Americanas" },
				{ LanguageId.qu, "EE.UU. Islas Vírgenes" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Inslas Virginas Americanas" },
				{ LanguageId.rn, "Amazinga y’Isugi y’Abanyamerika" },
				{ LanguageId.ro, "Insulele Virgine Americane" },
				{ LanguageId.rof, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.ru, "Виргинские о-ва (США)" },
				{ LanguageId.rw, "Ibirwa bya Virginie (Amerika)" },
				{ LanguageId.rwk, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Figunguli fya Viliginiya ifya Malekani" },
				{ LanguageId.sd, "آمريڪي ورجن ٻيٽ" },
				{ LanguageId.se, "AOS Virgin-sullot" },
				{ LanguageId.seh, "Ilhas Virgens dos EUA" },
				{ LanguageId.ses, "Ameerik Virgin Gungey" },
				{ LanguageId.sg, "Âzûâ Virîgo tî Amerîka" },
				{ LanguageId.shi, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ" },
				{ LanguageId.si, "ඇමරිකානු වර්ජින් දූපත්" },
				{ LanguageId.sk, "Americké Panenské ostrovy" },
				{ LanguageId.sl, "Ameriški Deviški otoki" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Ovtâstum Staatâi Nieidâsuolluuh" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zvitsuwa zveAmerika" },
				{ LanguageId.so, "U.S Fargin Island" },
				{ LanguageId.sq, "Ishujt e Virgjër të SHBA-së" },
				{ LanguageId.sr, "Америчка Девичанска Острва" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Virgin (U.S.)" },
				{ LanguageId.su, "Kapuloan Virgin (A.S.)" },
				{ LanguageId.sv, "Amerikanska Jungfruöarna" },
				{ LanguageId.sw, "Visiwa vya Virgin, Marekani" },
				{ LanguageId.syr, "ܓܙܪ̈ܬܐ ܕܒܬܘ̈ܠܐ ܕܐܡܪܝܟܐ" },
				{ LanguageId.ta, "யூ.எஸ். கன்னித் தீவுகள்" },
				{ LanguageId.te, "యు.ఎస్. వర్జిన్ దీవులు" },
				{ LanguageId.teo, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.tg, "Ҷазираҳои Виргини ИМА" },
				{ LanguageId.th, "หมู่เกาะเวอร์จินของสหรัฐอเมริกา" },
				{ LanguageId.ti, "ደሴታት ደናግል ኣመሪካ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "ABŞ-nyň Wirgin adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻOtumotu Vilikini fakaʻamelika" },
				{ LanguageId.tr, "ABD Virjin Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "АКШ Виргин утраулары" },
				{ LanguageId.twq, "Ameerik Virgin Gungey" },
				{ LanguageId.tzm, "Tigzirin n Virjin n Iwunak Yedduklen" },
				{ LanguageId.ug, "ئا ق ش ۋىرگىن ئاراللىرى" },
				{ LanguageId.uk, "Віргінські Острови (США)" },
				{ LanguageId.ur, "امریکی ورجن آئلینڈز" },
				{ LanguageId.uz, "AQSH Virgin orollari" },
				{ LanguageId.vai, "ꕶꕱ ꗩꗡ ꗏ ꖷꖬ ꔳꘋꗣ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Virgin thuộc Hoa Kỳ" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Visiwa vya Virgin vya Marekani" },
				{ LanguageId.wae, "Amerikaniši Jungfröiwinslä" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Duni Wirsin yu Etaa-sini" },
				{ LanguageId.xh, "E-U.S. Virgin Islands" },
				{ LanguageId.xog, "Ebizinga bya Virigini eby’Amerika" },
				{ LanguageId.yav, "pindisúlɛ́ pi amálíka" },
				{ LanguageId.yi, "ווירגין אינזלען (יו. עס.)" },
				{ LanguageId.yo, "Etikun Fagini ti Amẹrika" },
				{ LanguageId.zgh, "ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ" },
				{ LanguageId.zh, "美属维尔京群岛" },
				{ LanguageId.zu, "i-U.S. Virgin Islands" },
			}
		);
	}
}
