using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class VI
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "1",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Jomfruøerne (USA)" },
				{ LanguageId.af, "Virgin Islands (VSA)" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ቨርጂን ደሴቶች (አሜሪካ)" },
				{ LanguageId.ar, "جزر فيرجن (الولايات المتحدة)" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Virgin Adaları (ABŞ)" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Віргінскія астравы (ЗША)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Вирджински острови (САЩ)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ভার্জিন দ্বীপপুঞ্জ (মার্কিন যুক্তরাষ্ট্র)" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Djevičanska ostrva (SAD)" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Verges (EUA)" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Virgin Islands (U.S.)" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isole Vergini (U.S.)" },
				{ LanguageId.cs, "Panenské ostrovy (USA)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd y Wyryf (UDA)" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Jungferninseln (USA)" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Παρθένοι Νήσοι (Η.Π.Α.)" },
				{ LanguageId.en, "Virgin Islands (U.S.)" },
				{ LanguageId.eo, "Virgulininsuloj (Usono)" },
				{ LanguageId.es, "Islas Vírgenes (EE.UU.)" },
				{ LanguageId.et, "Neitsisaared (USA)" },
				{ LanguageId.eu, "Birjina uharteak (AEB)" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر ویرجین (ایالات متحده آمریکا)" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Neitsytsaaret (USA)" },
				{ LanguageId.fil, "Virgin Islands (U.S.)" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Îles Vierges (États-Unis)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Virgin Islands (FS)" },
				{ LanguageId.ga, "Oileáin na Maighdean (S.A.)" },
				{ LanguageId.gd, "Eileanan Virgin (S.A.)" },
				{ LanguageId.gl, "Illas Virxes (EUA)" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "વર્જિન ટાપુઓ (યુ.એસ.)" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Tsibirin Virgin (Amurka)" },
				{ LanguageId.haw, "Nā Mokupuni Virgin (U.S.)" },
				{ LanguageId.he, "" },
				{ LanguageId.hi, "वर्जिन आइलैंड्स (यू.एस.)" },
				{ LanguageId.hr, "Djevičanski otoci (SAD)" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Virgin-szigetek (USA)" },
				{ LanguageId.hy, "Վիրջինյան կղզիներ (ԱՄՆ)" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Virgin (AS)" },
				{ LanguageId.ig, "Virgin Islands (U.S.)" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Jómfrúareyjar (Bandaríkin)" },
				{ LanguageId.it, "Isole Vergini (Stati Uniti)" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ヴァージン諸島 (米国)" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kepulauan Virgin (AS)" },
				{ LanguageId.ka, "ვირჯინიის კუნძულები (აშშ)" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Виргин аралдары (АҚШ)" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះវឺជីន (សហរដ្ឋអាមេរិក)" },
				{ LanguageId.kn, "ವರ್ಜಿನ್ ದ್ವೀಪಗಳು (ಯುಎಸ್)" },
				{ LanguageId.ko, "버진 아일랜드(미국)" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Виргин аралдары (АКШ)" },
				{ LanguageId.la, "Insularum Virginum (US.)" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Virgin Islands (USA)" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະເວີຈິນ (ສະຫະລັດ)" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Mergelių salos (JAV)" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Virdžīnu salas (ASV)" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Virijiny (Etazonia)" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Moutere Wahine (U.S.)" },
				{ LanguageId.mk, "Девствени Острови (САД)" },
				{ LanguageId.ml, "വിർജിൻ ദ്വീപുകൾ (യു.എസ്.)" },
				{ LanguageId.mn, "Виржиний арлууд (АНУ)" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "व्हर्जिन बेटे (यू.एस.)" },
				{ LanguageId.ms, "Kepulauan Virgin (A.S.)" },
				{ LanguageId.mt, "Gżejjer Verġni (U.S.)" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ဗာဂျင်ကျွန်းများ (အမေရိကန်)" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Jomfruøyene (USA)" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "भर्जिन टापु (संयुक्त राज्य अमेरिका)" },
				{ LanguageId.nl, "Maagdeneilanden (VS)" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଭର୍ଜିନ ଦ୍ୱୀପପୁଞ୍ଜ (ଯୁକ୍ତରାଷ୍ଟ୍ର)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵਰਜਿਨ ਟਾਪੂ (ਯੂ.ਐਸ.)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Dziewicze (Stany Zjednoczone)" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "ورجن ټاپوګان (امريکا)" },
				{ LanguageId.pt, "Ilhas Virgens (EUA)" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Virgine (S.U.A.)" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Виргинские острова (США)" },
				{ LanguageId.rw, "Ibirwa bya Virginie (Amerika)" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ورجن ٻيٽ (يو ايس)" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "වර්ජින් දූපත් (එක්සත් ජනපදය)" },
				{ LanguageId.sk, "Panenské ostrovy (USA)" },
				{ LanguageId.sl, "Deviški otoki (ZDA)" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Virgin Islands (U.S.)" },
				{ LanguageId.so, "Jasiiradaha Virgin (Mareykanka)" },
				{ LanguageId.sq, "Ishujt e Virgjër (SHBA)" },
				{ LanguageId.sr, "Девичанска острва (САД)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Virgin (U.S.)" },
				{ LanguageId.su, "Kapuloan Virgin (A.S.)" },
				{ LanguageId.sv, "Jungfruöarna (USA)" },
				{ LanguageId.sw, "Visiwa vya Virgin (U.S.)" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "விர்ஜின் தீவுகள் (யு.எஸ்.)" },
				{ LanguageId.te, "వర్జిన్ దీవులు (U.S.)" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Вирҷиния (ИМА)" },
				{ LanguageId.th, "หมู่เกาะเวอร์จิน (สหรัฐอเมริกา)" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Wirjin adalary (ABŞ)" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Virgin Adaları (ABD)" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Виргин утраулары (АКШ)" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ۋىرگىنىيە تاقىم ئارىلى (ئامېرىكا)" },
				{ LanguageId.uk, "Віргінські острови (США)" },
				{ LanguageId.ur, "ورجن جزائر (امریکہ)" },
				{ LanguageId.uz, "Virjiniya orollari (AQSh)" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Virgin (Mỹ)" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IZiqithi zaseVirgin (eU.S.)" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "ווירגין אינזלען (יו. עס.)" },
				{ LanguageId.yo, "Erékùṣù Virgin (U.S.)" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "维尔京群岛（美国）" },
				{ LanguageId.zu, "I-Virgin Islands (U.S.)" },
			}
		);
	}
}
