using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class WF
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "681",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Wallis- og Futuna-øerne" },
				{ LanguageId.af, "Wallis- en Futuna-eilande" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዋሊስ እና ፉቱና ደሴቶች" },
				{ LanguageId.ar, "جزر واليس وفوتونا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Uollis və Futuna adaları" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Астравы Уоліс і Футуна" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Острови Уолис и Футуна" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "ওয়ালিস এবং ফুটুনা দ্বীপপুঞ্জ" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Wallis ha Futuna" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Ostrva Wallis i Futuna" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Illes Wallis i Futuna" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Mga Isla sa Wallis ug Futuna" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Isole Wallis è Futuna" },
				{ LanguageId.cs, "Ostrovy Wallis a Futuna" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Ynysoedd Wallis a Futuna" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Wallis- und Futuna-Inseln" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νησιά Wallis και Futuna" },
				{ LanguageId.en, "Wallis and Futuna Islands" },
				{ LanguageId.eo, "Insuloj Valiso kaj Futuno" },
				{ LanguageId.es, "Islas Wallis y Futuna" },
				{ LanguageId.et, "Wallise ja Futuna saared" },
				{ LanguageId.eu, "Wallis eta Futuna uharteak" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "جزایر والیس و فوتونا" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Wallis ja Futuna saaret" },
				{ LanguageId.fil, "Mga Isla ng Wallis at Futuna" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Îles Wallis et Futuna" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Wallis en Futuna eilannen" },
				{ LanguageId.ga, "Oileáin Bhailís agus Futúna" },
				{ LanguageId.gd, "Eileanan Wallis agus Futuna" },
				{ LanguageId.gl, "Illas Wallis e Futuna" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "વોલિસ અને ફુટુના ટાપુઓ" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Wallis da Futuna Islands" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Wallis a me Futuna" },
				{ LanguageId.he, "איי וואליס ופוטונה" },
				{ LanguageId.hi, "वालिस और फ़्यूचूना द्वीप समूह" },
				{ LanguageId.hr, "Otoci Wallis i Futuna" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Wallis és Futuna-szigetek" },
				{ LanguageId.hy, "Ուոլիս և Ֆուտունա կղզիներ" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Wallis dan Futuna" },
				{ LanguageId.ig, "Wallis na Futuna Islands" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Wallis og Futuna eyjar" },
				{ LanguageId.it, "Isole Wallis e Futuna" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ウォリス フツナ諸島" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Kapuloan Wallis lan Futuna" },
				{ LanguageId.ka, "უოლისი და ფუტუნას კუნძულები" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Уоллис және Футуна аралдары" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "កោះ Wallis និង Futuna" },
				{ LanguageId.kn, "ವಾಲಿಸ್ ಮತ್ತು ಫುಟುನಾ ದ್ವೀಪಗಳು" },
				{ LanguageId.ko, "월리스푸투나 제도" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Уоллис жана Футуна аралдары" },
				{ LanguageId.la, "Wallis and Futuna" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Wallis a Futuna Inselen" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ໝູ່ເກາະ Wallis ແລະ Futuna" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Voliso ir Futūnos salos" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Volisa un Futunas salas" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Nosy Wallis sy Futuna" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Nga Moutere o Wallis me Futuna" },
				{ LanguageId.mk, "Островите Волис и Футуна" },
				{ LanguageId.ml, "വാലിസ് ആൻഡ് ഫ്യൂട്ടൂന ദ്വീപുകൾ" },
				{ LanguageId.mn, "Уоллис ба Футуна арлууд" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "वॉलिस आणि फ्युटुना बेटे" },
				{ LanguageId.ms, "Kepulauan Wallis dan Futuna" },
				{ LanguageId.mt, "Gżejjer Wallis u Futuna" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Wallis နှင့် Futuna ကျွန်းများ" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Wallis og Futuna-øyene" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "वालिस र फुटुना टापुहरू" },
				{ LanguageId.nl, "Wallis- en Futuna-eilanden" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ୱାଲିସ୍ ଏବଂ ଫୁଟୁନା ଦ୍ୱୀପପୁଞ୍ଜ |" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵਾਲਿਸ ਅਤੇ ਫੁਟੁਨਾ ਟਾਪੂ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Wyspy Wallis i Futuna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "والس او فوټونا ټاپوګان" },
				{ LanguageId.pt, "Ilhas Wallis e Futuna" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Insulele Wallis și Futuna" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Острова Уоллис и Футуна" },
				{ LanguageId.rw, "Ibirwa bya Wallis na Futuna" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "والس ۽ فوٽونا ٻيٽ" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "Wallis සහ Futuna දූපත්" },
				{ LanguageId.sk, "Ostrovy Wallis a Futuna" },
				{ LanguageId.sl, "Otoki Wallis in Futuna" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Wallis uye Futuna Islands" },
				{ LanguageId.so, "Wallis iyo Futuna Islands" },
				{ LanguageId.sq, "Ishujt Wallis dhe Futuna" },
				{ LanguageId.sr, "Острва Волис и Футуна" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Wallis le Futuna" },
				{ LanguageId.su, "Wallis jeung Kapuloan Futuna" },
				{ LanguageId.sv, "Wallis och Futunaöarna" },
				{ LanguageId.sw, "Visiwa vya Wallis na Futuna" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "வாலிஸ் மற்றும் ஃபுடுனா தீவுகள்" },
				{ LanguageId.te, "వాలిస్ మరియు ఫుటునా దీవులు" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Ҷазираҳои Уоллис ва Футуна" },
				{ LanguageId.th, "หมู่เกาะวาลลิสและฟุตูนา" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Wallis we Futuna adalary" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Wallis ve Futuna Adaları" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Валлис һәм Футуна утраулары" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "ۋاللىس ۋە فۇتۇنا ئارىلى" },
				{ LanguageId.uk, "Острови Уолліс і Футуна" },
				{ LanguageId.ur, "والس اور فٹونا جزائر" },
				{ LanguageId.uz, "Uollis va Futuna orollari" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Quần đảo Wallis và Futuna" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Iziqithi zaseWallis kunye neFutuna" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "וואַליס און פוטונאַ אינזלען" },
				{ LanguageId.yo, "Wallis ati Futuna Islands" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "瓦利斯和富图纳群岛" },
				{ LanguageId.zu, "I-Wallis ne-Futuna Islands" },
			}
		);
	}
}
