// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class WF
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "681",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Wallis og Futuna" },
				{ LanguageId.af, "Wallis en Futuna" },
				{ LanguageId.agq, "Wales à Fùwtuwnà" },
				{ LanguageId.ak, "Wallis ne Futuna" },
				{ LanguageId.am, "ዋሊስ እና ፉቱና ደሴቶች" },
				{ LanguageId.ar, "جزر والس وفوتونا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "ৱালিছ আৰু ফুটুনা" },
				{ LanguageId.asa, "Walith na Futuna" },
				{ LanguageId.ast, "Wallis y Futuna" },
				{ LanguageId.az, "Uollis və Futuna" },
				{ LanguageId.ba, "Уоллис һәм Футуна" },
				{ LanguageId.bas, "Wàlîs nì Fùtunà" },
				{ LanguageId.be, "Уоліс і Футуна" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huwalis na Hufutuna" },
				{ LanguageId.bg, "Уолис и Футуна" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Walisi-ni-Futuna" },
				{ LanguageId.bn, "ওয়ালিস ও ফুটুনা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Wallis-ha-Futuna" },
				{ LanguageId.brx, "वालिस आरो फ्युचुना" },
				{ LanguageId.bs, "Ostrva Valis i Futuna" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Wallis i Futuna" },
				{ LanguageId.ccp, "𑄤𑄣𑄨𑄌𑄴 𑄃𑄮 𑄜𑄪𑄑𑄪𑄚" },
				{ LanguageId.ce, "Уоллис а, Футуна а" },
				{ LanguageId.ceb, "Wallis & Futuna" },
				{ LanguageId.cgg, "Warris na Futuna" },
				{ LanguageId.chr, "ᏩᎵᏍ ᎠᎴ ᏊᏚᎾ" },
				{ LanguageId.ckb, "والیس و فوتونا" },
				{ LanguageId.co, "Isole Wallis è Futuna" },
				{ LanguageId.cs, "Wallis a Futuna" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Wallis a Futuna" },
				{ LanguageId.dav, "Walis na Futuna" },
				{ LanguageId.de, "Wallis und Futuna" },
				{ LanguageId.dje, "Wallis nda Futuna" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Wallis a Futuna" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "ཝལ་ལིས྄་ ཨེནཌ་ ཕུ་ཏུ་ན་" },
				{ LanguageId.ebu, "Walis na Futuna" },
				{ LanguageId.ee, "Wallis kple Futuna nutome" },
				{ LanguageId.el, "Γουάλις και Φουτούνα" },
				{ LanguageId.en, "Wallis & Futuna" },
				{ LanguageId.eo, "Valiso kaj Futuno" },
				{ LanguageId.es, "Wallis y Futuna" },
				{ LanguageId.et, "Wallis ja Futuna" },
				{ LanguageId.eu, "Wallis eta Futuna" },
				{ LanguageId.ewo, "Walís-ai-Futúna" },
				{ LanguageId.fa, "والیس و فوتونا" },
				{ LanguageId.ff, "Walis e Futuna" },
				{ LanguageId.fi, "Wallis ja Futuna" },
				{ LanguageId.fil, "Wallis & Futuna" },
				{ LanguageId.fo, "Wallis- og Futunaoyggjar" },
				{ LanguageId.fr, "Wallis-et-Futuna" },
				{ LanguageId.fur, "Wallis e Futuna" },
				{ LanguageId.fy, "Wallis en Futuna" },
				{ LanguageId.ga, "Vailís agus Futúna" },
				{ LanguageId.gd, "Uallas agus Futuna" },
				{ LanguageId.gl, "Wallis e Futuna" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Wallis und Futuuna" },
				{ LanguageId.gu, "વૉલિસ અને ફ્યુચુના" },
				{ LanguageId.guz, "Walis na Futuna" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Walis Da Futuna" },
				{ LanguageId.haw, "Nā Mokupuni ʻo Wallis a me Futuna" },
				{ LanguageId.he, "איי ווליס ופוטונה" },
				{ LanguageId.hi, "वालिस और फ़्यूचूना" },
				{ LanguageId.hr, "Wallis i Futuna" },
				{ LanguageId.hsb, "Wallis a Futuna" },
				{ LanguageId.hu, "Wallis és Futuna" },
				{ LanguageId.hy, "Ուոլիս և Ֆուտունա" },
				{ LanguageId.ia, "Wallis e Futuna" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Kepulauan Wallis dan Futuna" },
				{ LanguageId.ig, "Wallis & Futuna" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Wallis- og Fútúnaeyjar" },
				{ LanguageId.it, "Wallis e Futuna" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ウォリス・フツナ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Walis na Futuna" },
				{ LanguageId.jv, "Wallis lan Futuna" },
				{ LanguageId.ka, "უოლისი და ფუტუნა" },
				{ LanguageId.kab, "Wallis d Futuna" },
				{ LanguageId.kam, "Walis na Futuna" },
				{ LanguageId.kde, "Walis na Futuna" },
				{ LanguageId.kea, "Ualis i Futuna" },
				{ LanguageId.khq, "Wallis nda Futuna" },
				{ LanguageId.ki, "Walis na Futuna" },
				{ LanguageId.kk, "Уоллис және Футуна" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Walis ak Futuna" },
				{ LanguageId.km, "វ៉ាលីស និង​ហ្វូទូណា" },
				{ LanguageId.kn, "ವಾಲಿಸ್ ಮತ್ತು ಫುಟುನಾ" },
				{ LanguageId.ko, "왈리스-푸투나 제도" },
				{ LanguageId.kok, "वॉलिस आनी फुतुना" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "والِس تہٕ فیوٗچوٗنا" },
				{ LanguageId.ksb, "Walis na Futuna" },
				{ LanguageId.ksf, "walis ri futuna" },
				{ LanguageId.ksh, "Wallis un Futuna" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Уоллис жана Футуна" },
				{ LanguageId.la, "Wallis and Futuna" },
				{ LanguageId.lag, "Walíisi na Futúuna" },
				{ LanguageId.lb, "Wallis a Futuna" },
				{ LanguageId.lg, "Walisi ne Futuna" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Walisɛ mpé Futuna" },
				{ LanguageId.lo, "ວາລລິສ ແລະ ຟູຕູນາ" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Volisas ir Futūna" },
				{ LanguageId.luo, "Wallis gi Futuna" },
				{ LanguageId.luy, "Walis na Futuna" },
				{ LanguageId.lv, "Volisa un Futunas salas" },
				{ LanguageId.mai, "बालिस आ फुटुना" },
				{ LanguageId.mas, "Walis na Futuna" },
				{ LanguageId.mer, "Walis na Futuna" },
				{ LanguageId.mfe, "Wallis-ek-Futuna" },
				{ LanguageId.mg, "Wallis sy Futuna" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Warihi me Whutuna" },
				{ LanguageId.mk, "Валис и Футуна" },
				{ LanguageId.ml, "വാലിസ് ആന്റ് ഫ്യൂച്യുന" },
				{ LanguageId.mn, "Уоллис ба Футуна" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "वालिस आणि फ्यूचूना" },
				{ LanguageId.ms, "Wallis dan Futuna" },
				{ LanguageId.mt, "Wallis u Futuna" },
				{ LanguageId.mua, "Wallis ne Futuna" },
				{ LanguageId.my, "ဝေါလစ်နှင့် ဖူကျူးနား" },
				{ LanguageId.mzn, "والیس و فوتونا" },
				{ LanguageId.naq, "Wallis and Futuna" },
				{ LanguageId.nb, "Wallis og Futuna" },
				{ LanguageId.nd, "Wallis and Futuna" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "वालिस र फुटुना" },
				{ LanguageId.nl, "Wallis en Futuna" },
				{ LanguageId.nmg, "Wallis ba Futuna" },
				{ LanguageId.nn, "Wallis og Futuna" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߥߊߟߌߛߌ߫ ߣߌ߫ ߝߕߎߣߊ߫" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Warris na Futuna" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Waalis fi Futtuuna" },
				{ LanguageId.or, "ୱାଲିସ୍ ଏବଂ ଫୁତୁନା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਵਾਲਿਸ ਅਤੇ ਫੂਟੂਨਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Wọ́lis & Fiutúna" },
				{ LanguageId.pl, "Wallis i Futuna" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "والیس او فوتونا" },
				{ LanguageId.pt, "Wallis e Futuna" },
				{ LanguageId.qu, "Wallis y Futuna" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Wallis e Futuna" },
				{ LanguageId.rn, "Walisi na Futuna" },
				{ LanguageId.ro, "Wallis și Futuna" },
				{ LanguageId.rof, "Walis na Futuna" },
				{ LanguageId.ru, "Уоллис и Футуна" },
				{ LanguageId.rw, "Ibirwa bya Wallis na Futuna" },
				{ LanguageId.rwk, "Walis na Futuna" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Walis na Futuna" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Walisi ni Futuna" },
				{ LanguageId.sd, "والس ۽ فتونا" },
				{ LanguageId.se, "Wallis ja Futuna" },
				{ LanguageId.seh, "Wallis e Futuna" },
				{ LanguageId.ses, "Wallis nda Futuna" },
				{ LanguageId.sg, "Walîsi na Futuna" },
				{ LanguageId.shi, "ⵡⴰⵍⵉⵙ ⴷ ⴼⵓⵜⵓⵏⴰ" },
				{ LanguageId.si, "වැලිස් සහ ෆුටුනා" },
				{ LanguageId.sk, "Wallis a Futuna" },
				{ LanguageId.sl, "Wallis in Futuna" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Wallis já Futuna" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Wallis and Futuna" },
				{ LanguageId.so, "Walis & Futuna" },
				{ LanguageId.sq, "Uollis e Futuna" },
				{ LanguageId.sr, "Валис и Футуна" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Lihlekehleke tsa Wallis le Futuna" },
				{ LanguageId.su, "Wallis jeung Kapuloan Futuna" },
				{ LanguageId.sv, "Wallis- och Futunaöarna" },
				{ LanguageId.sw, "Wallis na Futuna" },
				{ LanguageId.syr, "ܘܐܠܝܣ ܘܦܘܬܘܢܐ" },
				{ LanguageId.ta, "வாலிஸ் மற்றும் ஃபுடுனா" },
				{ LanguageId.te, "వాల్లిస్ మరియు ఫుటునా" },
				{ LanguageId.teo, "Walis na Futuna" },
				{ LanguageId.tg, "Уоллис ва Футуна" },
				{ LanguageId.th, "วาลลิสและฟุตูนา" },
				{ LanguageId.ti, "ዋሊስን ፉቱናን" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Uollis we Futuna" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "ʻUvea mo Futuna" },
				{ LanguageId.tr, "Wallis ve Futuna" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Уоллис һәм Футуна" },
				{ LanguageId.twq, "Wallis nda Futuna" },
				{ LanguageId.tzm, "Walis d Futuna" },
				{ LanguageId.ug, "ۋاللىس ۋە فۇتۇنا" },
				{ LanguageId.uk, "Уолліс і Футуна" },
				{ LanguageId.ur, "ویلیز اور فیوٹیونا" },
				{ LanguageId.uz, "Uollis va Futuna" },
				{ LanguageId.vai, "ꕎꔷꔻ ꗪ ꖢꖤꕯ" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Wallis và Futuna" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Walis na Futuna" },
				{ LanguageId.wae, "Wallis und Futuna" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Walis ak Futuna" },
				{ LanguageId.xh, "EWallis & Futuna" },
				{ LanguageId.xog, "Walisi ni Futuna" },
				{ LanguageId.yav, "walíis na futúna" },
				{ LanguageId.yi, "וואַליס און פוטונאַ אינזלען" },
				{ LanguageId.yo, "Wali ati futuna" },
				{ LanguageId.zgh, "ⵡⴰⵍⵉⵙ ⴷ ⴼⵓⵜⵓⵏⴰ" },
				{ LanguageId.zh, "瓦利斯和富图纳" },
				{ LanguageId.zu, "i-Wallis ne-Futuna" },
			}
		);
	}
}
