using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class YU
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "381",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Jugoslavien (udgået)" },
				{ LanguageId.af, "Joego-Slawië (Beëindig)" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዩጎዝላቪያ (የተቋረጠ)" },
				{ LanguageId.ar, "يوغوسلافيا (توقفت)" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Yuqoslaviya (Dayandırılmış)" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Югаславія (спынена)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Югославия (прекратено)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "যুগোস্লাভিয়া (বন্ধ)" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Jugoslavija (prekinuto)" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Iugoslàvia (descatalogat)" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Yugoslavia (Gihunong)" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Jugoslavia (Discontinued)" },
				{ LanguageId.cs, "Jugoslávie (ukončeno)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Iwgoslafia (Terfynu)" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Jugoslawien (eingestellt)" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Γιουγκοσλαβία (Διακοπή)" },
				{ LanguageId.en, "Yugoslavia (Discontinued)" },
				{ LanguageId.eo, "Jugoslavio (Maldaŭrigita)" },
				{ LanguageId.es, "Yugoslavia (descontinuada)" },
				{ LanguageId.et, "Jugoslaavia (lõpetatud)" },
				{ LanguageId.eu, "Jugoslavia (Etenduta)" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "یوگسلاوی (قطع)" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Jugoslavia (poistettu)" },
				{ LanguageId.fil, "Yugoslavia (Itinigil)" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Yougoslavie (abandonné)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Joegoslaavje (beëinige)" },
				{ LanguageId.ga, "Iúgslaiv (Scortha)" },
				{ LanguageId.gd, "Iugoslabhia (Sguir dheth)" },
				{ LanguageId.gl, "Iugoslavia (descontinuado)" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "યુગોસ્લાવિયા (બંધ)" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Yugoslavia (An daina)" },
				{ LanguageId.haw, "Yugoslavia (Hoʻopau ʻia)" },
				{ LanguageId.he, "יוגוסלביה (הופסק)" },
				{ LanguageId.hi, "यूगोस्लाविया (बंद)" },
				{ LanguageId.hr, "Jugoslavija (prekinuto)" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Jugoszlávia (megszűnt)" },
				{ LanguageId.hy, "Հարավսլավիա (դադարեցվել է)" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Yugoslavia (Dihentikan)" },
				{ LanguageId.ig, "Yugoslavia (Akwụsịla)" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Júgóslavía (hætt við)" },
				{ LanguageId.it, "Jugoslavia (fuori produzione)" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ユーゴスラビア (販売終了)" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Yugoslavia (Diterusake)" },
				{ LanguageId.ka, "იუგოსლავია (შეწყვეტილია)" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Югославия (тоқтатылған)" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "យូហ្គោស្លាវី (បញ្ឈប់)" },
				{ LanguageId.kn, "ಯುಗೊಸ್ಲಾವಿಯಾ (ಮುಂದುವರಿದ)" },
				{ LanguageId.ko, "유고슬라비아 (단종됨)" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Югославия (Токтотулган)" },
				{ LanguageId.la, "Iugoslavia (Discontinued)" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Jugoslawien (opgehalen)" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ຢູໂກສະລາເວຍ (ຢຸດຕິ)" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Jugoslavija (nutraukta)" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Dienvidslāvija (pārtraukta)" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Iogoslavia (najanona)" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Yugoslavia (Ka mutu)" },
				{ LanguageId.mk, "Југославија (прекинато)" },
				{ LanguageId.ml, "യുഗോസ്ലാവിയ (നിർത്തൽ)" },
				{ LanguageId.mn, "Югослав (Үргэлжлүүлсэн)" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "युगोस्लाव्हिया (बंद)" },
				{ LanguageId.ms, "Yugoslavia (Dihentikan)" },
				{ LanguageId.mt, "Jugoslavja (Twaqqaf)" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "ယူဂိုဆလားဗီးယား (ဆက်မလုပ်တော့)" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Jugoslavia (avviklet)" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "युगोस्लाभिया (बन्द)" },
				{ LanguageId.nl, "Joegoslavië (gestaakt)" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଯୁଗୋସ୍ଲାଭିଆ (ବନ୍ଦ)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਯੂਗੋਸਲਾਵੀਆ (ਬੰਦ)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Jugosławia (wycofane)" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "یوګوسلاویا (بند شوی)" },
				{ LanguageId.pt, "Iugoslávia (descontinuado)" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Iugoslavia (Întreruptă)" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Югославия (снято с производства)" },
				{ LanguageId.rw, "Yugosilaviya (Yahagaritswe)" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "يوگوسلاويا (بند ٿيل)" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "යුගෝස්ලාවියාව (නවත්වා)" },
				{ LanguageId.sk, "Juhoslávia (ukončená)" },
				{ LanguageId.sl, "Jugoslavija (ukinjeno)" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Yugoslavia (Yakamiswa)" },
				{ LanguageId.so, "Yugoslavia (la joojiyay)" },
				{ LanguageId.sq, "Jugosllavi (E ndërprerë)" },
				{ LanguageId.sr, "Југославија (прекинуто)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Yugoslavia (E khaotsoe)" },
				{ LanguageId.su, "Yugoslavia (dieureunkeun)" },
				{ LanguageId.sv, "Jugoslavien (upphört)" },
				{ LanguageId.sw, "Yugoslavia (Imekomeshwa)" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "யூகோஸ்லாவியா (நிறுத்தப்பட்டது)" },
				{ LanguageId.te, "యుగోస్లేవియా (నిలిపివేయబడింది)" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Югославия (қатъ шудааст)" },
				{ LanguageId.th, "ยูโกสลาเวีย (ยกเลิก)" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Ugugoslawiýa (Dowamy)" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Yugoslavya (Üretilmiyor)" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Ugгославия (туктатылган)" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "يۇگوسلاۋىيە (توختىتىلدى)" },
				{ LanguageId.uk, "Югославія (припинено)" },
				{ LanguageId.ur, "یوگوسلاویہ (منقطع)" },
				{ LanguageId.uz, "Yugoslaviya (to'xtatilgan)" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Nam Tư (Ngưng)" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "IYugoslavia (Yekwa)" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "יוגאסלאוויע (אָפּגעשטעלט)" },
				{ LanguageId.yo, "Yugoslavia (Ti dawọ duro)" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "南斯拉夫（已停产）" },
				{ LanguageId.zu, "I-Yugoslavia (Inqanyuliwe)" },
			}
		);
	}
}
