using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class ZA
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "27",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sydafrika" },
				{ LanguageId.af, "Suid-Afrika" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ደቡብ አፍሪቃ" },
				{ LanguageId.ar, "جنوب أفريقيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Cənubi Afrika" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Паўднёвая Афрыка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Южна Африка" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "দক্ষিন আফ্রিকা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Južna Afrika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sud-Àfrica" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Habagatang Aprika" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Africa di u Sudu" },
				{ LanguageId.cs, "Jižní Afrika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "De Affrica" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Südafrika" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Νότια Αφρική" },
				{ LanguageId.en, "South Africa" },
				{ LanguageId.eo, "Sudafriko" },
				{ LanguageId.es, "Sudáfrica" },
				{ LanguageId.et, "Lõuna-Aafrika" },
				{ LanguageId.eu, "Hegoafrika" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "آفریقای جنوبی" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Etelä-Afrikka" },
				{ LanguageId.fil, "Timog Africa" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Afrique du Sud" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Súd-Afrika" },
				{ LanguageId.ga, "an Afraic Theas" },
				{ LanguageId.gd, "Afraga a-Deas" },
				{ LanguageId.gl, "África do Sur" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "દક્ષિણ આફ્રિકા" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Afirka ta Kudu" },
				{ LanguageId.haw, "ʻApelika Hema" },
				{ LanguageId.he, "דרום אפריקה" },
				{ LanguageId.hi, "दक्षिण अफ्रीका" },
				{ LanguageId.hr, "Južna Afrika" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Dél-Afrika" },
				{ LanguageId.hy, "Հարավային Աֆրիկա" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Afrika Selatan" },
				{ LanguageId.ig, "South Africa" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Suður-Afríka" },
				{ LanguageId.it, "Sud Africa" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "南アフリカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Afrika Kidul" },
				{ LanguageId.ka, "სამხრეთ აფრიკა" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Оңтүстік Африка" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "អា​ព្រិច​ខាងត្បូង" },
				{ LanguageId.kn, "ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ" },
				{ LanguageId.ko, "남아프리카" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түштүк Африка" },
				{ LanguageId.la, "Africa Australis" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Südafrika" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "ອາຟຣິກາໃຕ້" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "pietų Afrika" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Dienvidāfrika" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Afrika Atsimo" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Āwherika ki te Tonga" },
				{ LanguageId.mk, "Јужна Африка" },
				{ LanguageId.ml, "ദക്ഷിണാഫ്രിക്ക" },
				{ LanguageId.mn, "Өмнөд Африк" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "दक्षिण आफ्रिका" },
				{ LanguageId.ms, "Afrika Selatan" },
				{ LanguageId.mt, "Afrika t'Isfel" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "တောင်အာဖရိက" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Sør-Afrika" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "दक्षिण अफ्रिका" },
				{ LanguageId.nl, "Zuid-Afrika" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଦକ୍ଷିଣ ଆଫ୍ରିକା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਦੱਖਣੀ ਅਫਰੀਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Afryka Południowa" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سویلي افریقا" },
				{ LanguageId.pt, "África do Sul" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Africa de Sud" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Южная Африка" },
				{ LanguageId.rw, "Afurika y'Epfo" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "ڏکڻ آفريڪا " },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "දකුණු අප්රිකාව" },
				{ LanguageId.sk, "južná Afrika" },
				{ LanguageId.sl, "Južna Afrika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Chamhembe Afrika" },
				{ LanguageId.so, "Koonfur Afrika" },
				{ LanguageId.sq, "Afrika e Jugut" },
				{ LanguageId.sr, "Јужна Африка" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Afrika Boroa" },
				{ LanguageId.su, "Afrika Kidul" },
				{ LanguageId.sv, "Sydafrika" },
				{ LanguageId.sw, "Africa Kusini" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "தென்னாப்பிரிக்கா" },
				{ LanguageId.te, "దక్షిణ ఆఫ్రికా" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Африқои ҷанубӣ" },
				{ LanguageId.th, "แอฟริกาใต้" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günorta Afrika" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Güney Afrika" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Көньяк Африка" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "جەنۇبى ئافرىقا" },
				{ LanguageId.uk, "Південна Африка" },
				{ LanguageId.ur, "جنوبی افریقہ" },
				{ LanguageId.uz, "Janubiy Afrika" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Nam Phi" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Mzantsi Afrika" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "דרום אפריקע" },
				{ LanguageId.yo, "gusu Afrika" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "南非" },
				{ LanguageId.zu, "Iningizimu Afrika" },
			}
		);
	}
}
