// Country names in this file are generated from Unicode CLDR 48.2.1 by tools/GenerateCountryData.
// Where CLDR has no value for a language, the previously curated value is kept.
// CountryPhoneCode and ValidLengthsAndFormat are NOT CLDR data - edit those here by hand.
using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public static class ZA
	{
		public static CountryProperties CountryProperties { get; } = new(
			CountryPhoneCode: "27",
			ValidLengthsAndFormat: null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Sydafrika" },
				{ LanguageId.af, "Suid-Afrika" },
				{ LanguageId.agq, "Afɨlekà ghɨ Emàm ghò" },
				{ LanguageId.ak, "Abibirem Anaafoɔ" },
				{ LanguageId.am, "ደቡብ አፍሪካ" },
				{ LanguageId.ar, "جنوب أفريقيا" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "দক্ষিণ আফ্রিকা" },
				{ LanguageId.asa, "Afrika Kuthini" },
				{ LanguageId.ast, "Sudáfrica" },
				{ LanguageId.az, "Cənub Afrika" },
				{ LanguageId.ba, "Көньяҡ Африка Республикаһы" },
				{ LanguageId.bas, "Àfrǐkà Sɔ̀" },
				{ LanguageId.be, "Паўднёва-Афрыканская Рэспубліка" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "Huafrika iya Hukusini" },
				{ LanguageId.bg, "Южна Африка" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "Worodugu Afriki" },
				{ LanguageId.bn, "দক্ষিণ আফ্রিকা" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "Suafrika" },
				{ LanguageId.brx, "खोला आफ्रिका" },
				{ LanguageId.bs, "Južnoafrička Republika" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Sud-àfrica" },
				{ LanguageId.ccp, "𑄘𑄧𑄉𑄨𑄚𑄴 𑄃𑄜𑄳𑄢𑄨𑄇" },
				{ LanguageId.ce, "Къилба-Африкин Республика" },
				{ LanguageId.ceb, "South Africa" },
				{ LanguageId.cgg, "Sausi Afirika" },
				{ LanguageId.chr, "ᏧᎦᎾᏮ ᎬᎿᎨᏍᏛ" },
				{ LanguageId.ckb, "ئەفریقای باشوور" },
				{ LanguageId.co, "Africa di u Sudu" },
				{ LanguageId.cs, "Jihoafrická republika" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "De Affrica" },
				{ LanguageId.dav, "Afrika Kusini" },
				{ LanguageId.de, "Südafrika" },
				{ LanguageId.dje, "Hawsa Afriki Laboo" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "Pódpołdnjowa Afrika (Republika)" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "སཱའུཐ་ ཨཕ་རི་ཀ" },
				{ LanguageId.ebu, "Afrika Kusini" },
				{ LanguageId.ee, "Anyiehe Africa nutome" },
				{ LanguageId.el, "Νότια Αφρική" },
				{ LanguageId.en, "South Africa" },
				{ LanguageId.eo, "Sud-Afriko" },
				{ LanguageId.es, "Sudáfrica" },
				{ LanguageId.et, "Lõuna-Aafrika Vabariik" },
				{ LanguageId.eu, "Hegoafrika" },
				{ LanguageId.ewo, "Afiríka yá Súd" },
				{ LanguageId.fa, "افریقای جنوبی" },
				{ LanguageId.ff, "Afrik bŋ Worgo" },
				{ LanguageId.fi, "Etelä-Afrikka" },
				{ LanguageId.fil, "South Africa" },
				{ LanguageId.fo, "Suðurafrika" },
				{ LanguageId.fr, "Afrique du Sud" },
				{ LanguageId.fur, "Sud Afriche" },
				{ LanguageId.fy, "Sûd-Afrika" },
				{ LanguageId.ga, "an Afraic Theas" },
				{ LanguageId.gd, "Afraga a Deas" },
				{ LanguageId.gl, "Suráfrica" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "Süüdafrika" },
				{ LanguageId.gu, "દક્ષિણ આફ્રિકા" },
				{ LanguageId.guz, "Afrika Kusini" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Afirka Ta Kudu" },
				{ LanguageId.haw, "ʻApelika Hema" },
				{ LanguageId.he, "דרום אפריקה" },
				{ LanguageId.hi, "दक्षिण अफ़्रीका" },
				{ LanguageId.hr, "Južnoafrička Republika" },
				{ LanguageId.hsb, "Južna Afrika (Republika)" },
				{ LanguageId.hu, "Dél-afrikai Köztársaság" },
				{ LanguageId.hy, "Հարավաֆրիկյան Հանրապետություն" },
				{ LanguageId.ia, "Africa del Sud" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Afrika Selatan" },
				{ LanguageId.ig, "South Africa" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Suður-Afríka" },
				{ LanguageId.it, "Sudafrica" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "南アフリカ" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "Afrika Kusini" },
				{ LanguageId.jv, "Afrika Kidul" },
				{ LanguageId.ka, "სამხრეთ აფრიკის რესპუბლიკა" },
				{ LanguageId.kab, "Tafriqt Wadda" },
				{ LanguageId.kam, "Afrika Kusini" },
				{ LanguageId.kde, "Afilika Kusini" },
				{ LanguageId.kea, "Áfrika di Sul" },
				{ LanguageId.khq, "Hawsa Afriki Laboo" },
				{ LanguageId.ki, "Afrika Kusini" },
				{ LanguageId.kk, "Оңтүстік Африка" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "Emetab Afrika nebo Murot tai" },
				{ LanguageId.km, "អាហ្វ្រិកខាងត្បូង" },
				{ LanguageId.kn, "ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ" },
				{ LanguageId.ko, "남아프리카" },
				{ LanguageId.kok, "दक्षिण आफ्रिका" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "جنوبی افریقہ" },
				{ LanguageId.ksb, "Aflika Kusini" },
				{ LanguageId.ksf, "afrik anǝ a sud" },
				{ LanguageId.ksh, "de Republik Södaffrika" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Түштүк-Африка Республикасы" },
				{ LanguageId.la, "Africa Australis" },
				{ LanguageId.lag, "Afɨrɨka ya Saame" },
				{ LanguageId.lb, "Südafrika" },
				{ LanguageId.lg, "Sawusafirika" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "Afríka ya Súdi" },
				{ LanguageId.lo, "ອາຟຣິກາໃຕ້" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Pietų Afrika" },
				{ LanguageId.luo, "South Africa" },
				{ LanguageId.luy, "Afrika Kusini" },
				{ LanguageId.lv, "Dienvidāfrikas Republika" },
				{ LanguageId.mai, "दक्षिण अफ्रीका" },
				{ LanguageId.mas, "Afrika Kusini" },
				{ LanguageId.mer, "Afrika ya Southi" },
				{ LanguageId.mfe, "Sid-Afrik" },
				{ LanguageId.mg, "Afrika Atsimo" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Āwherika ki te Tonga" },
				{ LanguageId.mk, "Јужноафриканска Република" },
				{ LanguageId.ml, "ദക്ഷിണാഫ്രിക്ക" },
				{ LanguageId.mn, "Өмнөд Африк" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "दक्षिण आफ्रिका" },
				{ LanguageId.ms, "Afrika Selatan" },
				{ LanguageId.mt, "l-Afrika t’Isfel" },
				{ LanguageId.mua, "Afrika nekǝsǝŋ" },
				{ LanguageId.my, "တောင်အာဖရိက" },
				{ LanguageId.mzn, "جنوبی افریقا" },
				{ LanguageId.naq, "Suid Afrikab" },
				{ LanguageId.nb, "Sør-Afrika" },
				{ LanguageId.nd, "Mzansi ye Afrika" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "दक्षिण अफ्रिका" },
				{ LanguageId.nl, "Zuid-Afrika" },
				{ LanguageId.nmg, "Afríka yí sí" },
				{ LanguageId.nn, "Sør-Afrika" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "ߥߙߏ߬ߘߎ߮ ߝߘߊ߬ߝߌ߲߬ߠߊ߫" },
				{ LanguageId.nr, "Sewula Afrika" },
				{ LanguageId.nso, "Afrika Borwa" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "Sausi Afirika" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "Afrikaa Kibbaa" },
				{ LanguageId.or, "ଦକ୍ଷିଣ ଆଫ୍ରିକା" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਦੱਖਣੀ ਅਫਰੀਕਾ" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "Saút Áfríka" },
				{ LanguageId.pl, "Republika Południowej Afryki" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "سویلي افریقا" },
				{ LanguageId.pt, "África do Sul" },
				{ LanguageId.qu, "Sudáfrica" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "Africa dal Sid" },
				{ LanguageId.rn, "Afurika y’Epfo" },
				{ LanguageId.ro, "Africa de Sud" },
				{ LanguageId.rof, "Afrika Kusini" },
				{ LanguageId.ru, "Южно-Африканская Республика" },
				{ LanguageId.rw, "Afurika y'Epfo" },
				{ LanguageId.rwk, "Afrika Kusini" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "Afrika Kusini" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "Afilika Kusini" },
				{ LanguageId.sd, "ڏکڻ آفريقا" },
				{ LanguageId.se, "Mátta-Afrihká" },
				{ LanguageId.seh, "África do Sul" },
				{ LanguageId.ses, "Hawsa Afriki Laboo" },
				{ LanguageId.sg, "Mbongo-Afrîka" },
				{ LanguageId.shi, "ⴰⴼⵔⵉⵇⵢⴰ ⵏ ⵉⴼⴼⵓⵙ" },
				{ LanguageId.si, "දකුණු අප්‍රිකාව" },
				{ LanguageId.sk, "Južná Afrika" },
				{ LanguageId.sl, "Južnoafriška republika" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "Maadâ-Afrikka" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "South Africa" },
				{ LanguageId.so, "Koonfur Afrika" },
				{ LanguageId.sq, "Afrika e Jugut" },
				{ LanguageId.sr, "Јужноафричка Република" },
				{ LanguageId.ss, "Ningizimu Afrika" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Afrika Borwa" },
				{ LanguageId.su, "Afrika Kidul" },
				{ LanguageId.sv, "Sydafrika" },
				{ LanguageId.sw, "Afrika Kusini" },
				{ LanguageId.syr, "ܬܝܡܢ ܐܦܪܝܩܐ" },
				{ LanguageId.ta, "தென் ஆப்பிரிக்கா" },
				{ LanguageId.te, "దక్షిణ ఆఫ్రికా" },
				{ LanguageId.teo, "Afrika Kusini" },
				{ LanguageId.tg, "Африкаи Ҷанубӣ" },
				{ LanguageId.th, "แอฟริกาใต้" },
				{ LanguageId.ti, "ደቡብ ኣፍሪቃ" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Günorta Afrika" },
				{ LanguageId.tn, "Aforika Borwa" },
				{ LanguageId.to, "ʻAfilika tonga" },
				{ LanguageId.tr, "Güney Afrika" },
				{ LanguageId.ts, "Afrika Dzonga" },
				{ LanguageId.tt, "Көньяк Африка" },
				{ LanguageId.twq, "Hawsa Afriki Laboo" },
				{ LanguageId.tzm, "Tafrikt Tunẓul" },
				{ LanguageId.ug, "جەنۇبىي ئافرىقا" },
				{ LanguageId.uk, "Південно-Африканська Республіка" },
				{ LanguageId.ur, "جنوبی افریقہ" },
				{ LanguageId.uz, "Janubiy Afrika Respublikasi" },
				{ LanguageId.vai, "ꕉꔱꔸꕪ ꗛꔤ ꔒꘋꗣ ꗏ ꕸꖃꔀ" },
				{ LanguageId.ve, "Afurika Tshipembe" },
				{ LanguageId.vi, "Nam Phi" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "Afrika Kusini" },
				{ LanguageId.wae, "Südafrika" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "Afrik di Sid" },
				{ LanguageId.xh, "EMzantsi Afrika" },
				{ LanguageId.xog, "Sawusafirika" },
				{ LanguageId.yav, "afilí mbátɛ́" },
				{ LanguageId.yi, "דרום־אַפֿריקע" },
				{ LanguageId.yo, "Gúúṣù Áfíríkà" },
				{ LanguageId.zgh, "ⴰⴼⵔⵉⵇⵢⴰ ⵏ ⵉⴼⴼⵓⵙ" },
				{ LanguageId.zh, "南非" },
				{ LanguageId.zu, "iNingizimu Afrika" },
			}
		);
	}
}
