using HumanLanguages;
namespace EarthCountriesInfo.CountryInformation
{
	public sealed class ZR
	{
		public static CountryProperties CountryProperties => new(
			CountryPhoneCode: "243",
			ValidLengthsAndFormat : null,
			CountryNames: new Dictionary<LanguageId, string>()
			{
				{ LanguageId.aa, "" },
				{ LanguageId.da, "Zaire (udgået)" },
				{ LanguageId.af, "Zaïre (Beëindig)" },
				{ LanguageId.agq, "" },
				{ LanguageId.ak, "" },
				{ LanguageId.am, "ዛየር (የተቋረጠ)" },
				{ LanguageId.ar, "زائير (توقف)" },
				{ LanguageId.arn, "" },
				{ LanguageId.@as, "" },
				{ LanguageId.asa, "" },
				{ LanguageId.ast, "" },
				{ LanguageId.az, "Zaire (Dayandırılmış)" },
				{ LanguageId.ba, "" },
				{ LanguageId.bas, "" },
				{ LanguageId.be, "Заір (спынена)" },
				{ LanguageId.bem, "" },
				{ LanguageId.bez, "" },
				{ LanguageId.bg, "Заир (спрян)" },
				{ LanguageId.bin, "" },
				{ LanguageId.bm, "" },
				{ LanguageId.bn, "জায়ার (বন্ধ)" },
				{ LanguageId.bo, "" },
				{ LanguageId.br, "" },
				{ LanguageId.brx, "" },
				{ LanguageId.bs, "Zair (prekinuto)" },
				{ LanguageId.byn, "" },
				{ LanguageId.ca, "Zaire (descatalogat)" },
				{ LanguageId.ccp, "" },
				{ LanguageId.ce, "" },
				{ LanguageId.ceb, "Zaire (Gihunong)" },
				{ LanguageId.cgg, "" },
				{ LanguageId.chr, "" },
				{ LanguageId.ckb, "" },
				{ LanguageId.co, "Zaire (Discontinued)" },
				{ LanguageId.cs, "Zair (ukončeno)" },
				{ LanguageId.cu, "" },
				{ LanguageId.cy, "Zaire (Terfynu)" },
				{ LanguageId.dav, "" },
				{ LanguageId.de, "Zaire (eingestellt)" },
				{ LanguageId.dje, "" },
				{ LanguageId.doi, "" },
				{ LanguageId.dsb, "" },
				{ LanguageId.dua, "" },
				{ LanguageId.dv, "" },
				{ LanguageId.dz, "" },
				{ LanguageId.ebu, "" },
				{ LanguageId.ee, "" },
				{ LanguageId.el, "Ζαΐρ (Διακοπή)" },
				{ LanguageId.en, "Zaire (Discontinued)" },
				{ LanguageId.eo, "Zairo (Maldaŭrigita)" },
				{ LanguageId.es, "Zaire (descontinuado)" },
				{ LanguageId.et, "Zaire (lõpetatud)" },
				{ LanguageId.eu, "Zaire (Etenduta)" },
				{ LanguageId.ewo, "" },
				{ LanguageId.fa, "زئیر (قطع شده)" },
				{ LanguageId.ff, "" },
				{ LanguageId.fi, "Zaire (poistettu)" },
				{ LanguageId.fil, "Zaire (Itinigil)" },
				{ LanguageId.fo, "" },
				{ LanguageId.fr, "Zaïre (arrêté)" },
				{ LanguageId.fur, "" },
				{ LanguageId.fy, "Zaire (beëinige)" },
				{ LanguageId.ga, "Sáír (Scortha)" },
				{ LanguageId.gd, "Zaire (Sguir dheth)" },
				{ LanguageId.gl, "Zaire (descontinuado)" },
				{ LanguageId.gn, "" },
				{ LanguageId.gsw, "" },
				{ LanguageId.gu, "ઝૈર (બંધ)" },
				{ LanguageId.guz, "" },
				{ LanguageId.gv, "" },
				{ LanguageId.ha, "Zaire (An daina)" },
				{ LanguageId.haw, "Zaire (Hoʻopau ʻia)" },
				{ LanguageId.he, "זאיר (הופסק)" },
				{ LanguageId.hi, "ज़ैरे (बंद)" },
				{ LanguageId.hr, "Zair (prekinut)" },
				{ LanguageId.hsb, "" },
				{ LanguageId.hu, "Zaire (megszűnt)" },
				{ LanguageId.hy, "Զաիր (դադարեցվել է)" },
				{ LanguageId.ia, "" },
				{ LanguageId.ibb, "" },
				{ LanguageId.id, "Zaire (Dihentikan)" },
				{ LanguageId.ig, "Zaire (Akwụsịla)" },
				{ LanguageId.ii, "" },
				{ LanguageId.@is, "Zaire (hætt)" },
				{ LanguageId.it, "Zaire (fuori produzione)" },
				{ LanguageId.iu, "" },
				{ LanguageId.ja, "ザイール (販売終了)" },
				{ LanguageId.jgo, "" },
				{ LanguageId.jmc, "" },
				{ LanguageId.jv, "Zaire (Diterusake)" },
				{ LanguageId.ka, "ზაირი (შეწყვეტილია)" },
				{ LanguageId.kab, "" },
				{ LanguageId.kam, "" },
				{ LanguageId.kde, "" },
				{ LanguageId.kea, "" },
				{ LanguageId.khq, "" },
				{ LanguageId.ki, "" },
				{ LanguageId.kk, "Заир (тоқтатылған)" },
				{ LanguageId.kkj, "" },
				{ LanguageId.kl, "" },
				{ LanguageId.kln, "" },
				{ LanguageId.km, "Zaire (បញ្ឈប់)" },
				{ LanguageId.kn, "ಜೈರ್ (ಮುಂದುವರಿದ)" },
				{ LanguageId.ko, "자이르 (단종)" },
				{ LanguageId.kok, "" },
				{ LanguageId.kr, "" },
				{ LanguageId.ks, "" },
				{ LanguageId.ksb, "" },
				{ LanguageId.ksf, "" },
				{ LanguageId.ksh, "" },
				{ LanguageId.kw, "" },
				{ LanguageId.ky, "Заир (Токтотулган)" },
				{ LanguageId.la, "Zaire (Discontinued)" },
				{ LanguageId.lag, "" },
				{ LanguageId.lb, "Zaire (ausgeschloss)" },
				{ LanguageId.lg, "" },
				{ LanguageId.lkt, "" },
				{ LanguageId.ln, "" },
				{ LanguageId.lo, "Zaire (ຢຸດຕິ)" },
				{ LanguageId.lrc, "" },
				{ LanguageId.lt, "Zaire (nebegaminamas)" },
				{ LanguageId.luo, "" },
				{ LanguageId.luy, "" },
				{ LanguageId.lv, "Zaire (pārtraukta)" },
				{ LanguageId.mai, "" },
				{ LanguageId.mas, "" },
				{ LanguageId.mer, "" },
				{ LanguageId.mfe, "" },
				{ LanguageId.mg, "Zaire (Atsahatra)" },
				{ LanguageId.mgo, "" },
				{ LanguageId.mi, "Zaire (Kua mutu)" },
				{ LanguageId.mk, "Заир (прекинат)" },
				{ LanguageId.ml, "സയർ (നിർത്തൽ)" },
				{ LanguageId.mn, "Заир (Үйл ажиллагаагаа зогсоосон)" },
				{ LanguageId.mni, "" },
				{ LanguageId.moh, "" },
				{ LanguageId.mr, "झैरे (बंद)" },
				{ LanguageId.ms, "Zaire (Dihentikan)" },
				{ LanguageId.mt, "Zaire (Mwaqqaf)" },
				{ LanguageId.mua, "" },
				{ LanguageId.my, "Zaire (ဆက်မလုပ်တော့ပါ)" },
				{ LanguageId.mzn, "" },
				{ LanguageId.naq, "" },
				{ LanguageId.nb, "Zaire (avviklet)" },
				{ LanguageId.nd, "" },
				{ LanguageId.nds, "" },
				{ LanguageId.ne, "Zaire (बन्द)" },
				{ LanguageId.nl, "Zaïre (gestaakt)" },
				{ LanguageId.nmg, "" },
				{ LanguageId.nn, "" },
				{ LanguageId.nnh, "" },
				{ LanguageId.nqo, "" },
				{ LanguageId.nr, "" },
				{ LanguageId.nso, "" },
				{ LanguageId.nus, "" },
				{ LanguageId.nyn, "" },
				{ LanguageId.oc, "" },
				{ LanguageId.om, "" },
				{ LanguageId.or, "ଜାୟେର୍ (ବନ୍ଦ)" },
				{ LanguageId.os, "" },
				{ LanguageId.pa, "ਜ਼ੇਅਰ (ਬੰਦ)" },
				{ LanguageId.pap, "" },
				{ LanguageId.pcm, "" },
				{ LanguageId.pl, "Zair (wycofane)" },
				{ LanguageId.prg, "" },
				{ LanguageId.ps, "زییر (بند شوی)" },
				{ LanguageId.pt, "Zaire (descontinuado)" },
				{ LanguageId.qu, "" },
				{ LanguageId.quc, "" },
				{ LanguageId.rm, "" },
				{ LanguageId.rn, "" },
				{ LanguageId.ro, "Zaire (Întrerupt)" },
				{ LanguageId.rof, "" },
				{ LanguageId.ru, "Заир (Снято с производства)" },
				{ LanguageId.rw, "Zayire (Yahagaritswe)" },
				{ LanguageId.rwk, "" },
				{ LanguageId.sa, "" },
				{ LanguageId.sah, "" },
				{ LanguageId.saq, "" },
				{ LanguageId.sat, "" },
				{ LanguageId.sbp, "" },
				{ LanguageId.sd, "زائر (بند ٿيل)" },
				{ LanguageId.se, "" },
				{ LanguageId.seh, "" },
				{ LanguageId.ses, "" },
				{ LanguageId.sg, "" },
				{ LanguageId.shi, "" },
				{ LanguageId.si, "සයිරේ (අත්හිටු වූ)" },
				{ LanguageId.sk, "Zair (ukončené)" },
				{ LanguageId.sl, "Zaire (ukinjeno)" },
				{ LanguageId.sma, "" },
				{ LanguageId.smj, "" },
				{ LanguageId.smn, "" },
				{ LanguageId.sms, "" },
				{ LanguageId.sn, "Zaire (Yakamiswa)" },
				{ LanguageId.so, "Zaire (la joojiyay)" },
				{ LanguageId.sq, "Zaire (I ndërprerë)" },
				{ LanguageId.sr, "Заир (прекинуто)" },
				{ LanguageId.ss, "" },
				{ LanguageId.ssy, "" },
				{ LanguageId.st, "Zaire (E khaotse)" },
				{ LanguageId.su, "Zaire (dieureunkeun)" },
				{ LanguageId.sv, "Zaire (upphört)" },
				{ LanguageId.sw, "Zaire (Imekomeshwa)" },
				{ LanguageId.syr, "" },
				{ LanguageId.ta, "Zaire (நிறுத்தப்பட்டது)" },
				{ LanguageId.te, "జైర్ (నిలిపివేయబడింది)" },
				{ LanguageId.teo, "" },
				{ LanguageId.tg, "Заир (қатъ шудааст)" },
				{ LanguageId.th, "ซาอีร์ (ยกเลิก)" },
				{ LanguageId.ti, "" },
				{ LanguageId.tig, "" },
				{ LanguageId.tk, "Zair (Dowam edildi)" },
				{ LanguageId.tn, "" },
				{ LanguageId.to, "" },
				{ LanguageId.tr, "Zaire (Üretilmiyor)" },
				{ LanguageId.ts, "" },
				{ LanguageId.tt, "Заир (туктатылган)" },
				{ LanguageId.twq, "" },
				{ LanguageId.tzm, "" },
				{ LanguageId.ug, "زايىر (توختىتىلدى)" },
				{ LanguageId.uk, "Заїр (припинено)" },
				{ LanguageId.ur, "زائر (منقطع)" },
				{ LanguageId.uz, "Zaire (to'xtatilgan)" },
				{ LanguageId.vai, "" },
				{ LanguageId.ve, "" },
				{ LanguageId.vi, "Zaire (Ngưng)" },
				{ LanguageId.vo, "" },
				{ LanguageId.vun, "" },
				{ LanguageId.wae, "" },
				{ LanguageId.wal, "" },
				{ LanguageId.wo, "" },
				{ LanguageId.xh, "Zaire (Yekisiwe)" },
				{ LanguageId.xog, "" },
				{ LanguageId.yav, "" },
				{ LanguageId.yi, "זאיר (אָפּגעשטעלט)" },
				{ LanguageId.yo, "Zaire (Ti dawọ duro)" },
				{ LanguageId.zgh, "" },
				{ LanguageId.zh, "扎伊尔（已停产）" },
				{ LanguageId.zu, "I-Zaire (Inqanyuliwe)" },
			}
		);
	}
}
